import type { ChapterWordRow } from "./extract-chapters";

// HSK1 chapter (lesson) word lists — kept entirely inside website/, the same
// way HSK3's are (see hsk3-chapters-data.ts), so the website repo is
// self-contained and doesn't reach outside itself for content. Generated
// once from the (now historical, edit-in-place-if-needed) source markdown at
// characters/words/hsk1/chapterN/vocabulary.md in the main chinese/ repo —
// see that repo's git history for the original per-chapter dialogues,
// grammar notes, and radical breakdowns, none of which the site reads.

export interface Hsk1ChapterData {
  chapterNumber: number;
  title: string;
  words: ChapterWordRow[];
}

export const HSK1_CHAPTERS: Hsk1ChapterData[] = [
  {
    chapterNumber: 1,
    title: "Lesson 1 — 你好 (Nǐ hǎo) Hello",
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: "pron.", meaning: "you (singular)" },
      { chinese: "好", pinyin: "hǎo", wordType: "adj.", meaning: "good, fine" },
      { chinese: "您", pinyin: "nín", wordType: "pron.", meaning: "you (polite form)" },
      { chinese: "你们", pinyin: "nǐmen", wordType: "pron.", meaning: "you (plural)" },
      { chinese: "对不起", pinyin: "duìbuqǐ", wordType: "v.", meaning: "to be sorry" },
      { chinese: "没关系", pinyin: "méi guānxi", wordType: "phrase", meaning: "that's OK, it doesn't matter" },
    ],
  },
  {
    chapterNumber: 2,
    title: "Lesson 2 — 谢谢你 (Xièxie nǐ) Thank You",
    words: [
      { chinese: "谢谢", pinyin: "xièxie", wordType: "v.", meaning: "to thank" },
      { chinese: "不", pinyin: "bù / bú", wordType: "adv.", meaning: "no, not" },
      { chinese: "不客气", pinyin: "bú kèqi", wordType: "phrase", meaning: "you're welcome, don't mention it" },
      { chinese: "再见", pinyin: "zàijiàn", wordType: "v.", meaning: "goodbye, to see you around" },
    ],
  },
  {
    chapterNumber: 3,
    title: "Lesson 3 — 你叫什么名字 (Nǐ jiào shénme míngzi) What's Your Name",
    words: [
      { chinese: "叫", pinyin: "jiào", wordType: "v.", meaning: "to call, to be called" },
      { chinese: "什么", pinyin: "shénme", wordType: "pron.", meaning: "what" },
      { chinese: "名字", pinyin: "míngzi", wordType: "n.", meaning: "name" },
      { chinese: "我", pinyin: "wǒ", wordType: "pron.", meaning: "I, me" },
      { chinese: "是", pinyin: "shì", wordType: "v.", meaning: "to be (am / is / are)" },
      { chinese: "老师", pinyin: "lǎoshī", wordType: "n.", meaning: "teacher" },
      { chinese: "吗", pinyin: "ma", wordType: "part.", meaning: "question particle (yes/no questions)" },
      { chinese: "学生", pinyin: "xuésheng", wordType: "n.", meaning: "student" },
      { chinese: "人", pinyin: "rén", wordType: "n.", meaning: "person, human" },
    ],
  },
  {
    chapterNumber: 4,
    title: "Lesson 4 — 她是我的汉语老师 (Tā shì wǒ de Hànyǔ lǎoshī) She Is My Chinese Teacher",
    words: [
      { chinese: "她", pinyin: "tā", wordType: "pron.", meaning: "she, her" },
      { chinese: "谁", pinyin: "shéi", wordType: "pron.", meaning: "who, whom" },
      { chinese: "的", pinyin: "de", wordType: "part.", meaning: "used after an attribute (possession/description)" },
      { chinese: "汉语", pinyin: "Hànyǔ", wordType: "n.", meaning: "Chinese (language)" },
      { chinese: "哪", pinyin: "nǎ", wordType: "pron.", meaning: "which" },
      { chinese: "国", pinyin: "guó", wordType: "n.", meaning: "country, nation" },
      { chinese: "呢", pinyin: "ne", wordType: "part.", meaning: "used at the end of a question" },
      { chinese: "他", pinyin: "tā", wordType: "pron.", meaning: "he, him" },
      { chinese: "同学", pinyin: "tóngxué", wordType: "n.", meaning: "classmate" },
      { chinese: "朋友", pinyin: "péngyou", wordType: "n.", meaning: "friend" },
    ],
  },
  {
    chapterNumber: 5,
    title: "Lesson 5 — 她女儿今年二十岁 (Tā nǚ'ér jīnnián èrshí suì) Her Daughter Is 20 Years Old This Year",
    words: [
      { chinese: "家", pinyin: "jiā", wordType: "n.", meaning: "family" },
      { chinese: "有", pinyin: "yǒu", wordType: "v.", meaning: "to have, there be" },
      { chinese: "口", pinyin: "kǒu", wordType: "mw.", meaning: "measure word for members of families, etc." },
      { chinese: "女儿", pinyin: "nǚ'ér", wordType: "n.", meaning: "daughter" },
      { chinese: "几", pinyin: "jǐ", wordType: "pron.", meaning: "how many" },
      { chinese: "岁", pinyin: "suì", wordType: "mw.", meaning: "year (of age)" },
      { chinese: "了", pinyin: "le", wordType: "part.", meaning: "used at the end of or in the middle of a sentence to indicate a change or new circumstance" },
      { chinese: "今年", pinyin: "jīnnián", wordType: "n.", meaning: "this year" },
      { chinese: "多", pinyin: "duō", wordType: "adv.", meaning: "indicating degree or extent" },
      { chinese: "大", pinyin: "dà", wordType: "adj.", meaning: "(of age) old; big" },
    ],
  },
  {
    chapterNumber: 6,
    title: "Lesson 6 — 我会说汉语 (Wǒ huì shuō Hànyǔ) I Can Speak Chinese",
    words: [
      { chinese: "会", pinyin: "huì", wordType: "mod.", meaning: "can, to be able to" },
      { chinese: "说", pinyin: "shuō", wordType: "v.", meaning: "to speak, to say" },
      { chinese: "妈妈", pinyin: "māma", wordType: "n.", meaning: "mother" },
      { chinese: "菜", pinyin: "cài", wordType: "n.", meaning: "dish, cuisine" },
      { chinese: "很", pinyin: "hěn", wordType: "adv.", meaning: "very, quite" },
      { chinese: "好吃", pinyin: "hǎochī", wordType: "adj.", meaning: "delicious, tasty" },
      { chinese: "做", pinyin: "zuò", wordType: "v.", meaning: "to make, to produce" },
      { chinese: "写", pinyin: "xiě", wordType: "v.", meaning: "to write" },
      { chinese: "汉字", pinyin: "Hànzì", wordType: "n.", meaning: "Chinese character" },
      { chinese: "字", pinyin: "zì", wordType: "n.", meaning: "character, word" },
      { chinese: "怎么", pinyin: "zěnme", wordType: "pron.", meaning: "how (indicating nature, condition or manner)" },
      { chinese: "读", pinyin: "dú", wordType: "v.", meaning: "to read (aloud)" },
    ],
  },
  {
    chapterNumber: 7,
    title: "Lesson 7 — 今天几号 (Jīntiān jǐ hào) What's the Date Today",
    words: [
      { chinese: "请", pinyin: "qǐng", wordType: "v.", meaning: "(polite) please; to invite" },
      { chinese: "问", pinyin: "wèn", wordType: "v.", meaning: "to ask, to inquire" },
      { chinese: "今天", pinyin: "jīntiān", wordType: "n.", meaning: "today" },
      { chinese: "号", pinyin: "hào", wordType: "n.", meaning: "number; (for date of month) date" },
      { chinese: "月", pinyin: "yuè", wordType: "n.", meaning: "month; moon" },
      { chinese: "星期", pinyin: "xīngqī", wordType: "n.", meaning: "week" },
      { chinese: "昨天", pinyin: "zuótiān", wordType: "n.", meaning: "yesterday" },
      { chinese: "明天", pinyin: "míngtiān", wordType: "n.", meaning: "tomorrow" },
      { chinese: "去", pinyin: "qù", wordType: "v.", meaning: "to go" },
      { chinese: "学校", pinyin: "xuéxiào", wordType: "n.", meaning: "school" },
      { chinese: "看", pinyin: "kàn", wordType: "v.", meaning: "to look at, to watch, to read" },
      { chinese: "书", pinyin: "shū", wordType: "n.", meaning: "book" },
    ],
  },
  {
    chapterNumber: 8,
    title: "Lesson 8 — 我想喝茶 (Wǒ xiǎng hē chá) I'd Like Some Tea",
    words: [
      { chinese: "想", pinyin: "xiǎng", wordType: "mod.", meaning: "to want, would like" },
      { chinese: "喝", pinyin: "hē", wordType: "v.", meaning: "to drink" },
      { chinese: "茶", pinyin: "chá", wordType: "n.", meaning: "tea" },
      { chinese: "吃", pinyin: "chī", wordType: "v.", meaning: "to eat" },
      { chinese: "米饭", pinyin: "mǐfàn", wordType: "n.", meaning: "cooked rice" },
      { chinese: "下午", pinyin: "xiàwǔ", wordType: "n.", meaning: "afternoon" },
      { chinese: "商店", pinyin: "shāngdiàn", wordType: "n.", meaning: "shop, store" },
      { chinese: "买", pinyin: "mǎi", wordType: "v.", meaning: "to buy, to purchase" },
      { chinese: "个", pinyin: "gè", wordType: "mw.", meaning: "a general measure word" },
      { chinese: "杯子", pinyin: "bēizi", wordType: "n.", meaning: "cup, glass" },
      { chinese: "这", pinyin: "zhè", wordType: "pron.", meaning: "this" },
      { chinese: "多少", pinyin: "duōshao", wordType: "pron.", meaning: "how many, how much" },
      { chinese: "钱", pinyin: "qián", wordType: "n.", meaning: "money" },
      { chinese: "块", pinyin: "kuài", wordType: "mw.", meaning: "a unit of money, same as \"yuan\"" },
      { chinese: "那", pinyin: "nà", wordType: "pron.", meaning: "that" },
    ],
  },
  {
    chapterNumber: 9,
    title: "Lesson 9 — 你儿子在哪儿工作 (Nǐ érzi zài nǎr gōngzuò) Where Does Your Son Work",
    words: [
      { chinese: "小", pinyin: "xiǎo", wordType: "adj.", meaning: "small, little" },
      { chinese: "猫", pinyin: "māo", wordType: "n.", meaning: "cat" },
      { chinese: "在", pinyin: "zài", wordType: "v.", meaning: "to be in/on/at (location verb)" },
      { chinese: "那儿", pinyin: "nàr", wordType: "pron.", meaning: "there" },
      { chinese: "狗", pinyin: "gǒu", wordType: "n.", meaning: "dog" },
      { chinese: "椅子", pinyin: "yǐzi", wordType: "n.", meaning: "chair" },
      { chinese: "下面", pinyin: "xiàmiàn", wordType: "n.", meaning: "under, below" },
      { chinese: "下", pinyin: "xià", wordType: "n.", meaning: "down, below; next (as in 下个 \"next one\")" },
      { chinese: "哪儿", pinyin: "nǎr", wordType: "pron.", meaning: "where" },
      { chinese: "工作", pinyin: "gōngzuò", wordType: "v./n.", meaning: "to work; job" },
      { chinese: "儿子", pinyin: "érzi", wordType: "n.", meaning: "son" },
      { chinese: "医院", pinyin: "yīyuàn", wordType: "n.", meaning: "hospital" },
      { chinese: "医生", pinyin: "yīshēng", wordType: "n.", meaning: "doctor" },
      { chinese: "爸爸", pinyin: "bàba", wordType: "n.", meaning: "father" },
    ],
  },
  {
    chapterNumber: 10,
    title: "Lesson 10 — 我能坐这儿吗 (Wǒ néng zuò zhèr ma) Can I Sit Here",
    words: [
      { chinese: "桌子", pinyin: "zhuōzi", wordType: "n.", meaning: "desk, table" },
      { chinese: "上", pinyin: "shàng", wordType: "n.", meaning: "up, above" },
      { chinese: "电脑", pinyin: "diànnǎo", wordType: "n.", meaning: "computer" },
      { chinese: "和", pinyin: "hé", wordType: "conj.", meaning: "and" },
      { chinese: "本", pinyin: "běn", wordType: "mw.", meaning: "measure word for books" },
      { chinese: "里", pinyin: "lǐ", wordType: "n.", meaning: "inner, inside, interior" },
      { chinese: "前面", pinyin: "qiánmiàn", wordType: "n.", meaning: "front" },
      { chinese: "后面", pinyin: "hòumiàn", wordType: "n.", meaning: "back" },
      { chinese: "这儿", pinyin: "zhèr", wordType: "pron.", meaning: "here" },
      { chinese: "没有", pinyin: "méiyǒu", wordType: "adv./v.", meaning: "there is not; to not have" },
      { chinese: "没", pinyin: "méi", wordType: "adv.", meaning: "not (negates 有 and past actions)" },
      { chinese: "能", pinyin: "néng", wordType: "mod.", meaning: "can, may" },
      { chinese: "坐", pinyin: "zuò", wordType: "v.", meaning: "to sit, to be seated" },
    ],
  },
  {
    chapterNumber: 11,
    title: "Lesson 11 — 现在几点 (Xiànzài jǐ diǎn) What's the Time Now",
    words: [
      { chinese: "现在", pinyin: "xiànzài", wordType: "n.", meaning: "now" },
      { chinese: "点", pinyin: "diǎn", wordType: "mw.", meaning: "o'clock" },
      { chinese: "分", pinyin: "fēn", wordType: "mw.", meaning: "minute" },
      { chinese: "中午", pinyin: "zhōngwǔ", wordType: "n.", meaning: "noon" },
      { chinese: "吃饭", pinyin: "chī fàn", wordType: "v.", meaning: "to eat a meal" },
      { chinese: "时候", pinyin: "shíhou", wordType: "n.", meaning: "time, moment" },
      { chinese: "回", pinyin: "huí", wordType: "v.", meaning: "to come/go back, to return" },
      { chinese: "我们", pinyin: "wǒmen", wordType: "pron.", meaning: "we, us" },
      { chinese: "电影", pinyin: "diànyǐng", wordType: "n.", meaning: "film, movie" },
      { chinese: "住", pinyin: "zhù", wordType: "v.", meaning: "to live, to stay" },
      { chinese: "前", pinyin: "qián", wordType: "n.", meaning: "before, earlier than" },
    ],
  },
  {
    chapterNumber: 12,
    title: "Lesson 12 — 明天天气怎么样 (Míngtiān tiānqì zěnmeyàng) What Will the Weather Be Like Tomorrow",
    words: [
      { chinese: "天气", pinyin: "tiānqì", wordType: "n.", meaning: "weather" },
      { chinese: "怎么样", pinyin: "zěnmeyàng", wordType: "pron.", meaning: "how (indicating nature, condition or manner)" },
      { chinese: "太", pinyin: "tài", wordType: "adv.", meaning: "too, excessively; 太……了 = too/extremely" },
      { chinese: "热", pinyin: "rè", wordType: "adj.", meaning: "hot" },
      { chinese: "冷", pinyin: "lěng", wordType: "adj.", meaning: "cold" },
      { chinese: "下雨", pinyin: "xià yǔ", wordType: "v.", meaning: "to rain" },
      { chinese: "小姐", pinyin: "xiǎojiě", wordType: "n.", meaning: "miss, young lady" },
      { chinese: "来", pinyin: "lái", wordType: "v.", meaning: "to come" },
      { chinese: "身体", pinyin: "shēntǐ", wordType: "n.", meaning: "body" },
      { chinese: "爱", pinyin: "ài", wordType: "v.", meaning: "to like, to love" },
      { chinese: "些", pinyin: "xiē", wordType: "mw.", meaning: "some, a few" },
      { chinese: "水果", pinyin: "shuǐguǒ", wordType: "n.", meaning: "fruit" },
      { chinese: "水", pinyin: "shuǐ", wordType: "n.", meaning: "water" },
    ],
  },
  {
    chapterNumber: 13,
    title: "Lesson 13 — 他在学做中国菜呢 (Tā zài xué zuò Zhōngguó cài ne) He Is Learning to Cook Chinese Food",
    words: [
      { chinese: "喂", pinyin: "wèi", wordType: "interj.", meaning: "hello, hey (on the phone)" },
      { chinese: "也", pinyin: "yě", wordType: "adv.", meaning: "also, too" },
      { chinese: "学习", pinyin: "xuéxí", wordType: "v.", meaning: "to study, to learn" },
      { chinese: "学", pinyin: "xué", wordType: "v.", meaning: "to learn (a skill/subject)" },
      { chinese: "上午", pinyin: "shàngwǔ", wordType: "n.", meaning: "morning, before noon" },
      { chinese: "睡觉", pinyin: "shuì jiào", wordType: "v.", meaning: "to sleep" },
      { chinese: "电视", pinyin: "diànshì", wordType: "n.", meaning: "television" },
      { chinese: "喜欢", pinyin: "xǐhuan", wordType: "v.", meaning: "to like, to be fond of" },
      { chinese: "给", pinyin: "gěi", wordType: "prep.", meaning: "to" },
      { chinese: "打电话", pinyin: "dǎ diànhuà", wordType: "v.", meaning: "to make a phone call" },
      { chinese: "吧", pinyin: "ba", wordType: "part.", meaning: "modal particle — consultation, suggestion, or softened command" },
    ],
  },
  {
    chapterNumber: 14,
    title: "Lesson 14 — 她买了不少衣服 (Tā mǎile bù shǎo yīfu) She Has Bought Quite a Few Clothes",
    words: [
      { chinese: "东西", pinyin: "dōngxi", wordType: "n.", meaning: "thing, stuff" },
      { chinese: "一点儿", pinyin: "yīdiǎnr", wordType: "num.-m.", meaning: "a few, a little" },
      { chinese: "苹果", pinyin: "píngguǒ", wordType: "n.", meaning: "apple" },
      { chinese: "看见", pinyin: "kànjiàn", wordType: "v.", meaning: "to see, to catch sight of" },
      { chinese: "先生", pinyin: "xiānsheng", wordType: "n.", meaning: "Mr., sir" },
      { chinese: "开", pinyin: "kāi", wordType: "v.", meaning: "to drive (a vehicle); to open" },
      { chinese: "车", pinyin: "chē", wordType: "n.", meaning: "car, vehicle" },
      { chinese: "回来", pinyin: "huílai", wordType: "v.", meaning: "to come back, to return" },
      { chinese: "分钟", pinyin: "fēnzhōng", wordType: "n.", meaning: "minute (duration)" },
      { chinese: "后", pinyin: "hòu", wordType: "n.", meaning: "after, afterwards, later" },
      { chinese: "衣服", pinyin: "yīfu", wordType: "n.", meaning: "clothes, clothing" },
      { chinese: "漂亮", pinyin: "piàoliang", wordType: "adj.", meaning: "beautiful, pretty" },
      { chinese: "啊", pinyin: "a", wordType: "part.", meaning: "modal particle — confirmation or defense" },
      { chinese: "少", pinyin: "shǎo", wordType: "adj.", meaning: "few, little" },
      { chinese: "不少", pinyin: "bùshǎo", wordType: "adj.", meaning: "quite a few, many" },
      { chinese: "这些", pinyin: "zhèxiē", wordType: "pron.", meaning: "these" },
      { chinese: "都", pinyin: "dōu", wordType: "adv.", meaning: "both, all" },
    ],
  },
  {
    chapterNumber: 15,
    title: "Lesson 15 — 我是坐飞机来的 (Wǒ shì zuò fēijī lái de) I Came Here by Air",
    words: [
      { chinese: "认识", pinyin: "rènshi", wordType: "v.", meaning: "to meet, to know (a person)" },
      { chinese: "年", pinyin: "nián", wordType: "n.", meaning: "year" },
      { chinese: "大学", pinyin: "dàxué", wordType: "n.", meaning: "college, university" },
      { chinese: "饭店", pinyin: "fàndiàn", wordType: "n.", meaning: "hotel; restaurant" },
      { chinese: "出租车", pinyin: "chūzūchē", wordType: "n.", meaning: "taxi, cab" },
      { chinese: "一起", pinyin: "yīqǐ", wordType: "adv.", meaning: "together" },
      { chinese: "高兴", pinyin: "gāoxìng", wordType: "adj.", meaning: "glad, happy" },
      { chinese: "听", pinyin: "tīng", wordType: "v.", meaning: "to listen, to hear" },
      { chinese: "飞机", pinyin: "fēijī", wordType: "n.", meaning: "airplane" },
    ],
  },
];
