import type { CombinedVocabRow } from "./vocab-row";

// HSK1's combined (full-level) word list, generated once from the
// third-party PDF at raw/HSK-All-Levels-Vocabulary/ in the main chinese/
// repo with combined-vocab-corrections.ts's fixes already baked in — same
// self-contained rationale as hsk1-chapters-data.ts. No PDF parsing or
// correction step happens at runtime anymore, the same way HSK4A/4B never
// needed one (see hsk4a-combined-data.ts).

export const HSK1_COMBINED_WORDS: CombinedVocabRow[] = [
  { chinese: "我", pinyin: "wǒ", english: "I, me", category: "Personal Pron." },
  { chinese: "我们", pinyin: "wǒmen", english: "we, us (pl.)", category: "Personal Pron." },
  { chinese: "你", pinyin: "nǐ", english: "you", category: "Personal Pron." },
  { chinese: "你们", pinyin: "nǐmen", english: "you (pl.)", category: "Personal Pron." },
  { chinese: "他", pinyin: "tā", english: "he, him", category: "Personal Pron." },
  { chinese: "她", pinyin: "tā", english: "she, her", category: "Personal Pron." },
  { chinese: "他们", pinyin: "tāmen", english: "they (male+female / male, pl.)", category: "Personal Pron." },
  { chinese: "她们", pinyin: "tāmen", english: "they (females, pl.)", category: "Personal Pron." },
  { chinese: "这", pinyin: "zhè", english: "this", category: "Demonstrative Pron." },
  { chinese: "那", pinyin: "nà", english: "that", category: "Demonstrative Pron." },
  { chinese: "哪", pinyin: "nǎ", english: "which", category: "Interrogative Pron." },
  { chinese: "谁", pinyin: "shéi", english: "who", category: "Interrogative Pron." },
  { chinese: "什么", pinyin: "shénme", english: "what, why", category: "Interrogative Pron." },
  { chinese: "多少", pinyin: "duōshǎo", english: "how many, how much", category: "Interrogative Pron." },
  { chinese: "几", pinyin: "jǐ", english: "a few, how many", category: "Interrogative Pron." },
  { chinese: "怎么", pinyin: "zěnme", english: "how", category: "Interrogative Pron." },
  { chinese: "怎么样", pinyin: "zěnmeyàng", english: "how about", category: "Interrogative Pron." },
  { chinese: "一", pinyin: "yī", english: "one", category: "Numberal" },
  { chinese: "二", pinyin: "èr", english: "two", category: "Numberal" },
  { chinese: "三", pinyin: "sān", english: "three", category: "Numberal" },
  { chinese: "四", pinyin: "sì", english: "four", category: "Numberal" },
  { chinese: "五", pinyin: "wǔ", english: "five", category: "Numberal" },
  { chinese: "六", pinyin: "liù", english: "six", category: "Numberal" },
  { chinese: "七", pinyin: "qī", english: "seven", category: "Numberal" },
  { chinese: "八", pinyin: "bā", english: "eight", category: "Numberal" },
  { chinese: "九", pinyin: "jiǔ", english: "nine", category: "Numberal" },
  { chinese: "十", pinyin: "shí", english: "ten", category: "Numberal" },
  { chinese: "零", pinyin: "líng", english: "zero", category: "Numberal" },
  { chinese: "个", pinyin: "gè", english: "one, a, an", category: "Quantifier" },
  { chinese: "岁", pinyin: "suì", english: "year", category: "Quantifier" },
  { chinese: "本", pinyin: "běn", english: "volume", category: "Quantifier" },
  { chinese: "些", pinyin: "xiē", english: "some", category: "Quantifier" },
  { chinese: "块", pinyin: "kuài", english: "piece", category: "Quantifier" },
  { chinese: "不", pinyin: "bù", english: "no", category: "Adverb" },
  { chinese: "没有", pinyin: "méiyǒu", english: "there is not", category: "Adverb" },
  { chinese: "很", pinyin: "hěn", english: "quite, very", category: "Adverb" },
  { chinese: "太", pinyin: "tài", english: "too", category: "Adverb" },
  { chinese: "都", pinyin: "dōu", english: "all", category: "Adverb" },
  { chinese: "和", pinyin: "hé", english: "and", category: "Conjunction" },
  { chinese: "在", pinyin: "zài", english: "in, at", category: "Preposition" },
  { chinese: "的", pinyin: "de", english: null, category: "Auxiliary" },
  { chinese: "了", pinyin: "le", english: null, category: "Auxiliary" },
  { chinese: "吗", pinyin: "ma", english: null, category: "Auxiliary" },
  { chinese: "呢", pinyin: "ne", english: null, category: "Auxiliary" },
  { chinese: "喂", pinyin: "wèi", english: "hello", category: "Interjection" },
  { chinese: "家", pinyin: "jiā", english: "home", category: "Noun" },
  { chinese: "学校", pinyin: "xuéxiào", english: "school", category: "Noun" },
  { chinese: "饭店", pinyin: "fàndiàn", english: "hotel, restaurant", category: "Noun" },
  { chinese: "商店", pinyin: "shāngdiàn", english: "store", category: "Noun" },
  { chinese: "医院", pinyin: "yīyuàn", english: "hospital", category: "Noun" },
  { chinese: "火车站", pinyin: "huǒchēzhàn", english: "train station", category: "Noun" },
  { chinese: "中国", pinyin: "Zhōngguò", english: "China", category: "Noun" },
  { chinese: "北京", pinyin: "Běijīng", english: "Beijing", category: "Noun" },
  { chinese: "上", pinyin: "shàng", english: "up", category: "Noun" },
  { chinese: "下", pinyin: "xià", english: "down", category: "Noun" },
  { chinese: "前面", pinyin: "qiánmiàn", english: "front", category: "Noun" },
  { chinese: "后面", pinyin: "hòumiàn", english: "behind", category: "Noun" },
  { chinese: "里", pinyin: "lǐmiàn", english: "inside", category: "Noun" },
  { chinese: "今天", pinyin: "jīntiān", english: "today", category: "Noun" },
  { chinese: "明天", pinyin: "míngtiān", english: "tomorrow", category: "Noun" },
  { chinese: "昨天", pinyin: "zuótiān", english: "yesterday", category: "Noun" },
  { chinese: "上午", pinyin: "shàngwǔ", english: "morning", category: "Noun" },
  { chinese: "中午", pinyin: "zhōngwǔ", english: "noon", category: "Noun" },
  { chinese: "下午", pinyin: "xiàwǔ", english: "afternoon", category: "Noun" },
  { chinese: "年", pinyin: "nián", english: "year", category: "Noun" },
  { chinese: "月", pinyin: "yuè", english: "month", category: "Noun" },
  { chinese: "号", pinyin: "hào", english: "date, number", category: "Noun" },
  { chinese: "星期", pinyin: "xīngqī", english: "week", category: "Noun" },
  { chinese: "点", pinyin: "diǎn", english: "dot, spot", category: "Noun" },
  { chinese: "分钟", pinyin: "fēnzhōng", english: "minute", category: "Noun" },
  { chinese: "现在", pinyin: "xiànzài", english: "now", category: "Noun" },
  { chinese: "时候", pinyin: "shíhou", english: "time", category: "Noun" },
  { chinese: "爸爸", pinyin: "bàba", english: "father", category: "Noun" },
  { chinese: "妈妈", pinyin: "māma", english: "mother", category: "Noun" },
  { chinese: "儿子", pinyin: "érzi", english: "son", category: "Noun" },
  { chinese: "女儿", pinyin: "nǚér", english: "daughter", category: "Noun" },
  { chinese: "老师", pinyin: "lǎoshī", english: "teacher", category: "Noun" },
  { chinese: "学生", pinyin: "xuéshēng", english: "student", category: "Noun" },
  { chinese: "同学", pinyin: "tóngxué", english: "classmate", category: "Noun" },
  { chinese: "朋友", pinyin: "péngyǒu", english: "friend", category: "Noun" },
  { chinese: "医生", pinyin: "yīshēng", english: "doctor", category: "Noun" },
  { chinese: "先生", pinyin: "xiānsheng", english: "sir", category: "Noun" },
  { chinese: "小姐", pinyin: "xiǎojiě", english: "Miss", category: "Noun" },
  { chinese: "衣服", pinyin: "yīfu", english: "cloth", category: "Noun" },
  { chinese: "水", pinyin: "shuǐ", english: "water", category: "Noun" },
  { chinese: "菜", pinyin: "cài", english: "dish", category: "Noun" },
  { chinese: "米饭", pinyin: "mǐfàn", english: "rice", category: "Noun" },
  { chinese: "水果", pinyin: "shuǐguǒ", english: "fruit", category: "Noun" },
  { chinese: "苹果", pinyin: "píngguǒ", english: "apple", category: "Noun" },
  { chinese: "茶", pinyin: "chá", english: "tea", category: "Noun" },
  { chinese: "杯子", pinyin: "bēizi", english: "cup", category: "Noun" },
  { chinese: "钱", pinyin: "qián", english: "money", category: "Noun" },
  { chinese: "飞机", pinyin: "fēijī", english: "airplane", category: "Noun" },
  { chinese: "出租车", pinyin: "chūzūchē", english: "taxi", category: "Noun" },
  { chinese: "电视", pinyin: "diànshì", english: "television", category: "Noun" },
  { chinese: "电脑", pinyin: "diànnǎo", english: "computer", category: "Noun" },
  { chinese: "电影", pinyin: "diànyǐng", english: "movie", category: "Noun" },
  { chinese: "天气", pinyin: "tiānqì", english: "weather", category: "Noun" },
  { chinese: "猫", pinyin: "māo", english: "cat", category: "Noun" },
  { chinese: "狗", pinyin: "gǒu", english: "dog", category: "Noun" },
  { chinese: "东西", pinyin: "dōngxi", english: "thing", category: "Noun" },
  { chinese: "人", pinyin: "rén", english: "person", category: "Noun" },
  { chinese: "名字", pinyin: "míngzi", english: "name", category: "Noun" },
  { chinese: "书", pinyin: "shū", english: "book", category: "Noun" },
  { chinese: "汉语", pinyin: "hànyǔ", english: "mandarin Chinese", category: "Noun" },
  { chinese: "字", pinyin: "zì", english: "character", category: "Noun" },
  { chinese: "桌子", pinyin: "zhuōzi", english: "desk", category: "Noun" },
  { chinese: "椅子", pinyin: "yǐzi", english: "chair", category: "Noun" },
  { chinese: "谢谢", pinyin: "xièxie", english: "thank", category: "Verb" },
  { chinese: "不客气", pinyin: "búkèqì", english: "you are welcome", category: "Verb" },
  { chinese: "再见", pinyin: "zàijiàn", english: "good-bye", category: "Verb" },
  { chinese: "请", pinyin: "qǐng", english: "please", category: "Verb" },
  { chinese: "对不起", pinyin: "duìbùqǐ", english: "sorry", category: "Verb" },
  { chinese: "没关系", pinyin: "méiguānxì", english: "It doesn't matter", category: "Verb" },
  { chinese: "是", pinyin: "shì", english: "be (am, is, are)", category: "Verb" },
  { chinese: "有", pinyin: "yǒu", english: "have", category: "Verb" },
  { chinese: "看", pinyin: "kàn", english: "look", category: "Verb" },
  { chinese: "听", pinyin: "tīng", english: "listen", category: "Verb" },
  { chinese: "说话", pinyin: "shuōhuà", english: "speak", category: "Verb" },
  { chinese: "读", pinyin: "dú", english: "read", category: "Verb" },
  { chinese: "写", pinyin: "xiě", english: "write", category: "Verb" },
  { chinese: "看见", pinyin: "kànjiàn", english: "see", category: "Verb" },
  { chinese: "叫", pinyin: "jiào", english: "call", category: "Verb" },
  { chinese: "来", pinyin: "lái", english: "come", category: "Verb" },
  { chinese: "回", pinyin: "huí", english: "return", category: "Verb" },
  { chinese: "去", pinyin: "qù", english: "go", category: "Verb" },
  { chinese: "吃", pinyin: "chī", english: "eat", category: "Verb" },
  { chinese: "喝", pinyin: "hē", english: "drink", category: "Verb" },
  { chinese: "睡觉", pinyin: "shuìjiào", english: "sleep", category: "Verb" },
  { chinese: "打电话", pinyin: "dǎdiànhuà", english: "call up", category: "Verb" },
  { chinese: "做", pinyin: "zuò", english: "do", category: "Verb" },
  { chinese: "买", pinyin: "mǎi", english: "buy", category: "Verb" },
  { chinese: "开", pinyin: "kāi", english: "open", category: "Verb" },
  { chinese: "坐", pinyin: "zuò", english: "sit", category: "Verb" },
  { chinese: "住", pinyin: "zhù", english: "live", category: "Verb" },
  { chinese: "学习", pinyin: "xuéxí", english: "study", category: "Verb" },
  { chinese: "工作", pinyin: "gōngzuò", english: "work", category: "Verb" },
  { chinese: "下雨", pinyin: "xiàyǔ", english: "rain", category: "Verb" },
  { chinese: "爱", pinyin: "ài", english: "love", category: "Verb" },
  { chinese: "喜欢", pinyin: "xǐhuān", english: "love, like", category: "Verb" },
  { chinese: "想", pinyin: "xiǎng", english: "want", category: "Verb" },
  { chinese: "认识", pinyin: "rènshi", english: "know", category: "Verb" },
  { chinese: "会", pinyin: "huì", english: "can", category: "Verb" },
  { chinese: "能", pinyin: "néng", english: "can, be able to", category: "Verb" },
  { chinese: "好", pinyin: "hǎo", english: "good", category: "Adjective" },
  { chinese: "大", pinyin: "dà", english: "big", category: "Adjective" },
  { chinese: "小", pinyin: "xiǎo", english: "small", category: "Adjective" },
  { chinese: "多", pinyin: "duō", english: "many, much", category: "Adjective" },
  { chinese: "少", pinyin: "shǎo", english: "few, little", category: "Adjective" },
  { chinese: "冷", pinyin: "lěng", english: "cold", category: "Adjective" },
  { chinese: "热", pinyin: "rè", english: "hot", category: "Adjective" },
  { chinese: "高兴", pinyin: "gāoxìng", english: "happy", category: "Adjective" },
  { chinese: "漂亮", pinyin: "piàoliang", english: "beautiful", category: "Adjective" },
  { chinese: "说", pinyin: "shuō", english: "speak, say", category: "Verb" },
  { chinese: "一点儿", pinyin: "yìdiǎnr", english: "a little", category: "Quantifier" },
  { chinese: "这儿", pinyin: "zhèr", english: "here", category: "Demonstrative Pron." },
  { chinese: "那儿", pinyin: "nàr", english: "there", category: "Demonstrative Pron." },
  { chinese: "哪儿", pinyin: "nǎr", english: "where", category: "Interrogative Pron." },
];
