import type { ChapterWordRow } from "./extract-chapters";

// HSK1 chapters' full dialog vocabulary — docs/hold/25-chapter-all-words-plan.md.
// Auto-extracted (scripts-tmp-extract-dialogs.ts) from pasted textbook dialog
// text via longest-match segmentation against this app's own existing
// vocabulary (hsk{1,2,3}-{chapters,combined}-data.ts) — see
// scripts-tmp-unmatched.txt at generation time for anything that couldn't be
// matched automatically.

export interface Hsk1ChapterDialogData {
  chapterNumber: number;
  words: ChapterWordRow[];
}

export const HSK1_CHAPTER_DIALOGS: Hsk1ChapterDialogData[] = [
  {
    chapterNumber: 1,
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: "pron.", meaning: "you (singular)" },
      { chinese: "好", pinyin: "hǎo", wordType: "adj.", meaning: "good, fine" },
      { chinese: "您", pinyin: "nín", wordType: "pron.", meaning: "you (polite)" },
      { chinese: "你们", pinyin: "nǐmen", wordType: "pron.", meaning: "you (plural)" },
      { chinese: "对不起", pinyin: "duìbuqǐ", wordType: "v.", meaning: "to be sorry" },
      { chinese: "没关系", pinyin: "méi guānxi", wordType: "phrase", meaning: "that's OK, it doesn't matter" },
    ],
  },
  {
    chapterNumber: 2,
    words: [
      { chinese: "谢谢", pinyin: "xièxie", wordType: "v.", meaning: "to thank" },
      { chinese: "不", pinyin: "bù", wordType: "adv.", meaning: "no, not" },
      { chinese: "谢", pinyin: "xiè", wordType: "v.", meaning: "to thank (bound/surname form)" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "不客气", pinyin: "bú kèqi", wordType: "phrase", meaning: "you're welcome" },
      { chinese: "再见", pinyin: "zàijiàn", wordType: "v.", meaning: "to see you around" },
    ],
  },
  {
    chapterNumber: 3,
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "叫", pinyin: "jiào", wordType: "v.", meaning: "to call, to be called" },
      { chinese: "什么", pinyin: "shénme", wordType: "pron.", meaning: "what" },
      { chinese: "名字", pinyin: "míngzi", wordType: "n.", meaning: "name" },
      { chinese: "我", pinyin: "wǒ", wordType: "pron.", meaning: "I, me" },
      { chinese: "李月", pinyin: "Lǐ Yuè", wordType: "prop. n.", meaning: "Li Yue (name)" },
      { chinese: "是", pinyin: "shì", wordType: "v.", meaning: "to be" },
      { chinese: "老师", pinyin: "lǎoshī", wordType: "n.", meaning: "teacher" },
      { chinese: "吗", pinyin: "ma", wordType: "part.", meaning: "question particle" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "学生", pinyin: "xuésheng", wordType: "n.", meaning: "student" },
      { chinese: "中国", pinyin: "Zhōngguó", wordType: "prop. n.", meaning: "China" },
      { chinese: "人", pinyin: "rén", wordType: "n.", meaning: "human, person" },
      { chinese: "美国", pinyin: "Měiguó", wordType: "prop. n.", meaning: "USA" },
    ],
  },
  {
    chapterNumber: 4,
    words: [
      { chinese: "她", pinyin: "tā", wordType: "pron.", meaning: "she, her" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "谁", pinyin: "shéi", wordType: "pron.", meaning: "who, whom" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "的", pinyin: "de", wordType: "part.", meaning: "possessive particle" },
      { chinese: "汉语", pinyin: "Hànyǔ", wordType: "n.", meaning: "Chinese (language)" },
      { chinese: "老师", pinyin: "lǎoshī", wordType: null, meaning: "teacher" },
      { chinese: "叫", pinyin: "jiào", wordType: null, meaning: "to call, to be called" },
      { chinese: "李月", pinyin: "Lǐ Yuè", wordType: "prop. n.", meaning: "Li Yue (name)" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "哪", pinyin: "nǎ", wordType: "pron.", meaning: "which" },
      { chinese: "国", pinyin: "guó", wordType: "n.", meaning: "country, nation" },
      { chinese: "人", pinyin: "rén", wordType: null, meaning: "human, person" },
      { chinese: "美国", pinyin: "Měiguó", wordType: "prop. n.", meaning: "USA" },
      { chinese: "呢", pinyin: "ne", wordType: "part.", meaning: "question particle" },
      { chinese: "中国", pinyin: "Zhōngguó", wordType: "prop. n.", meaning: "China" },
      { chinese: "他", pinyin: "tā", wordType: "pron.", meaning: "he, him" },
      { chinese: "同学", pinyin: "tóngxué", wordType: "n.", meaning: "classmate" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "朋友", pinyin: "péngyou", wordType: "n.", meaning: "friend" },
    ],
  },
  {
    chapterNumber: 5,
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "家", pinyin: "jiā", wordType: "n.", meaning: "family" },
      { chinese: "有", pinyin: "yǒu", wordType: "v.", meaning: "to have, there be" },
      { chinese: "几", pinyin: "jǐ", wordType: "pron.", meaning: "how many" },
      { chinese: "口", pinyin: "kǒu", wordType: "m.", meaning: "measure word for family members" },
      { chinese: "人", pinyin: "rén", wordType: null, meaning: "human, person" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "三", pinyin: "sān", wordType: null, meaning: "three" },
      { chinese: "女儿", pinyin: "nǚ'ér", wordType: "n.", meaning: "daughter" },
      { chinese: "岁", pinyin: "suì", wordType: "m.", meaning: "year (of age)" },
      { chinese: "了", pinyin: "le", wordType: "part.", meaning: "change particle" },
      { chinese: "她", pinyin: "tā", wordType: null, meaning: "she, her" },
      { chinese: "今年", pinyin: "jīnnián", wordType: "n.", meaning: "this year" },
      { chinese: "四", pinyin: "sì", wordType: null, meaning: "four" },
      { chinese: "李", pinyin: "Lǐ", wordType: "prop. n.", meaning: "(surname) Li" },
      { chinese: "老师", pinyin: "lǎoshī", wordType: null, meaning: "teacher" },
      { chinese: "多", pinyin: "duō", wordType: "adv.", meaning: "indicating degree" },
      { chinese: "大", pinyin: "dà", wordType: "adj.", meaning: "(of age) old" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
    ],
  },
  {
    chapterNumber: 6,
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "会", pinyin: "huì", wordType: "mod.", meaning: "can, to be able to" },
      { chinese: "说", pinyin: "shuō", wordType: "v.", meaning: "to speak, to say" },
      { chinese: "汉语", pinyin: "Hànyǔ", wordType: null, meaning: "Chinese (language)" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "妈妈", pinyin: "māma", wordType: "n.", meaning: "mother" },
      { chinese: "她", pinyin: "tā", wordType: null, meaning: "she, her" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "中国", pinyin: "Zhōngguó", wordType: "prop. n.", meaning: "China" },
      { chinese: "菜", pinyin: "cài", wordType: "n.", meaning: "dish, cuisine" },
      { chinese: "好吃", pinyin: "hǎochī", wordType: "adj.", meaning: "delicious, tasty" },
      { chinese: "很", pinyin: "hěn", wordType: "adv.", meaning: "very, quite" },
      { chinese: "做", pinyin: "zuò", wordType: "v.", meaning: "to make, to produce" },
      { chinese: "写", pinyin: "xiě", wordType: "v.", meaning: "to write" },
      { chinese: "汉字", pinyin: "Hànzì", wordType: "n.", meaning: "Chinese character" },
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "字", pinyin: "zì", wordType: "n.", meaning: "character, word" },
      { chinese: "怎么", pinyin: "zěnme", wordType: "pron.", meaning: "how" },
      { chinese: "对不起", pinyin: "duìbuqǐ", wordType: null, meaning: "to be sorry" },
      { chinese: "读", pinyin: "dú", wordType: "v.", meaning: "to read" },
    ],
  },
  {
    chapterNumber: 7,
    words: [
      { chinese: "请", pinyin: "qǐng", wordType: "v.", meaning: "(polite) please" },
      { chinese: "问", pinyin: "wèn", wordType: "v.", meaning: "to ask, to inquire" },
      { chinese: "今天", pinyin: "jīntiān", wordType: "n.", meaning: "today" },
      { chinese: "几", pinyin: "jǐ", wordType: null, meaning: "how many" },
      { chinese: "号", pinyin: "hào", wordType: "n.", meaning: "(date) number" },
      { chinese: "月", pinyin: "yuè", wordType: "n.", meaning: "month" },
      { chinese: "星期", pinyin: "xīngqī", wordType: "n.", meaning: "week" },
      { chinese: "三", pinyin: "sān", wordType: null, meaning: "three" },
      { chinese: "昨天", pinyin: "zuótiān", wordType: "n.", meaning: "yesterday" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "二", pinyin: "èr", wordType: null, meaning: "two" },
      { chinese: "明天", pinyin: "míngtiān", wordType: "n.", meaning: "tomorrow" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "四", pinyin: "sì", wordType: null, meaning: "four" },
      { chinese: "六", pinyin: "liù", wordType: null, meaning: "six" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "去", pinyin: "qù", wordType: "v.", meaning: "to go" },
      { chinese: "学校", pinyin: "xuéxiào", wordType: "n.", meaning: "school" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "做", pinyin: "zuò", wordType: null, meaning: "to make, to produce" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "看", pinyin: "kàn", wordType: "v.", meaning: "to look, to watch, to read" },
      { chinese: "书", pinyin: "shū", wordType: "n.", meaning: "book" },
    ],
  },
  {
    chapterNumber: 8,
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "想", pinyin: "xiǎng", wordType: "mod.", meaning: "to want, would like" },
      { chinese: "喝", pinyin: "hē", wordType: "v.", meaning: "to drink" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "茶", pinyin: "chá", wordType: "n.", meaning: "tea" },
      { chinese: "吃", pinyin: "chī", wordType: "v.", meaning: "to eat" },
      { chinese: "米饭", pinyin: "mǐfàn", wordType: "n.", meaning: "cooked rice" },
      { chinese: "下午", pinyin: "xiàwǔ", wordType: "n.", meaning: "afternoon" },
      { chinese: "做", pinyin: "zuò", wordType: null, meaning: "to make, to produce" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "商店", pinyin: "shāngdiàn", wordType: "n.", meaning: "shop, store" },
      { chinese: "买", pinyin: "mǎi", wordType: "v.", meaning: "to buy" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "个", pinyin: "gè", wordType: "m.", meaning: "general measure word" },
      { chinese: "杯子", pinyin: "bēizi", wordType: "n.", meaning: "cup, glass" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "这", pinyin: "zhè", wordType: "pron.", meaning: "this" },
      { chinese: "多少", pinyin: "duōshao", wordType: "pron.", meaning: "how many, how much" },
      { chinese: "钱", pinyin: "qián", wordType: "n.", meaning: "money" },
      { chinese: "块", pinyin: "kuài", wordType: "m.", meaning: "unit of money (yuan)" },
      { chinese: "那", pinyin: "nà", wordType: "pron.", meaning: "that" },
    ],
  },
  {
    chapterNumber: 9,
    words: [
      { chinese: "小", pinyin: "xiǎo", wordType: "adj.", meaning: "small, little" },
      { chinese: "猫", pinyin: "māo", wordType: "n.", meaning: "cat" },
      { chinese: "在", pinyin: "zài", wordType: "v./prep.", meaning: "to be in/on/at" },
      { chinese: "哪儿", pinyin: "nǎr", wordType: "pron.", meaning: "where" },
      { chinese: "那儿", pinyin: "nàr", wordType: "pron.", meaning: "there" },
      { chinese: "狗", pinyin: "gǒu", wordType: "n.", meaning: "dog" },
      { chinese: "椅子", pinyin: "yǐzi", wordType: "n.", meaning: "chair" },
      { chinese: "下面", pinyin: "xiàmiàn", wordType: null, meaning: "under, below" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "工作", pinyin: "gōngzuò", wordType: "v./n.", meaning: "to work; job" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "学校", pinyin: "xuéxiào", wordType: null, meaning: "school" },
      { chinese: "儿子", pinyin: "érzi", wordType: "n.", meaning: "son" },
      { chinese: "医院", pinyin: "yīyuàn", wordType: "n.", meaning: "hospital" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "医生", pinyin: "yīshēng", wordType: "n.", meaning: "doctor" },
      { chinese: "爸爸", pinyin: "bàba", wordType: "n.", meaning: "father" },
      { chinese: "家", pinyin: "jiā", wordType: null, meaning: "family" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
    ],
  },
  {
    chapterNumber: 10,
    words: [
      { chinese: "桌子", pinyin: "zhuōzi", wordType: "n.", meaning: "desk, table" },
      { chinese: "上", pinyin: "shàng", wordType: "n.", meaning: "up, above" },
      { chinese: "有", pinyin: "yǒu", wordType: null, meaning: "to have, there be" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "电脑", pinyin: "diànnǎo", wordType: "n.", meaning: "computer" },
      { chinese: "和", pinyin: "hé", wordType: "conj.", meaning: "and" },
      { chinese: "本", pinyin: "běn", wordType: "m.", meaning: "measure word for books" },
      { chinese: "书", pinyin: "shū", wordType: null, meaning: "book" },
      { chinese: "杯子", pinyin: "bēizi", wordType: null, meaning: "cup, glass" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "哪儿", pinyin: "nǎr", wordType: null, meaning: "where" },
      { chinese: "里", pinyin: "lǐ", wordType: "n.", meaning: "inner, inside" },
      { chinese: "前面", pinyin: "qiánmiàn", wordType: "n.", meaning: "front" },
      { chinese: "那", pinyin: "nà", wordType: null, meaning: "that" },
      { chinese: "人", pinyin: "rén", wordType: null, meaning: "human, person" },
      { chinese: "叫", pinyin: "jiào", wordType: null, meaning: "to call, to be called" },
      { chinese: "名字", pinyin: "míngzi", wordType: null, meaning: "name" },
      { chinese: "她", pinyin: "tā", wordType: null, meaning: "she, her" },
      { chinese: "王方", pinyin: "Wáng Fāng", wordType: "prop. n.", meaning: "Wang Fang (name)" },
      { chinese: "医院", pinyin: "yīyuàn", wordType: null, meaning: "hospital" },
      { chinese: "工作", pinyin: "gōngzuò", wordType: null, meaning: "to work; job" },
      { chinese: "后面", pinyin: "hòumiàn", wordType: "n.", meaning: "back" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "谢朋", pinyin: "Xiè Péng", wordType: "prop. n.", meaning: "Xie Peng (name)" },
      { chinese: "商店", pinyin: "shāngdiàn", wordType: null, meaning: "shop, store" },
      { chinese: "这儿", pinyin: "zhèr", wordType: "pron.", meaning: "here" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "没有", pinyin: "méiyǒu", wordType: null, meaning: "there is not" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "能", pinyin: "néng", wordType: "mod.", meaning: "can, may" },
      { chinese: "坐", pinyin: "zuò", wordType: "v.", meaning: "to sit" },
      { chinese: "请", pinyin: "qǐng", wordType: null, meaning: "(polite) please" },
    ],
  },
  {
    chapterNumber: 11,
    words: [
      { chinese: "现在", pinyin: "xiànzài", wordType: "n.", meaning: "now" },
      { chinese: "几", pinyin: "jǐ", wordType: null, meaning: "how many" },
      { chinese: "点", pinyin: "diǎn", wordType: "m.", meaning: "o'clock" },
      { chinese: "十", pinyin: "shí", wordType: null, meaning: "ten" },
      { chinese: "分", pinyin: "fēn", wordType: "m.", meaning: "minute" },
      { chinese: "中午", pinyin: "zhōngwǔ", wordType: "n.", meaning: "noon" },
      { chinese: "吃饭", pinyin: "chī fàn", wordType: "v.", meaning: "to eat a meal" },
      { chinese: "二", pinyin: "èr", wordType: null, meaning: "two" },
      { chinese: "爸爸", pinyin: "bàba", wordType: null, meaning: "father" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "时候", pinyin: "shíhou", wordType: "n.", meaning: "time, moment" },
      { chinese: "回", pinyin: "huí", wordType: "v.", meaning: "to return" },
      { chinese: "家", pinyin: "jiā", wordType: null, meaning: "family" },
      { chinese: "下午", pinyin: "xiàwǔ", wordType: null, meaning: "afternoon" },
      { chinese: "五", pinyin: "wǔ", wordType: null, meaning: "five" },
      { chinese: "我们", pinyin: "wǒmen", wordType: "pron.", meaning: "we, us" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "看", pinyin: "kàn", wordType: null, meaning: "to look at, to watch, to read" },
      { chinese: "电影", pinyin: "diànyǐng", wordType: "n.", meaning: "film, movie" },
      { chinese: "六", pinyin: "liù", wordType: null, meaning: "six" },
      { chinese: "三", pinyin: "sān", wordType: null, meaning: "three" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "星期", pinyin: "xīngqī", wordType: null, meaning: "week" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "北京", pinyin: "Běijīng", wordType: "prop. n.", meaning: "Beijing" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "想", pinyin: "xiǎng", wordType: null, meaning: "to want, would like" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "住", pinyin: "zhù", wordType: "v.", meaning: "to live, to stay" },
      { chinese: "天", pinyin: "tiān", wordType: "n.", meaning: "day; sky" },
      { chinese: "前", pinyin: "qián", wordType: "n.", meaning: "before" },
      { chinese: "能", pinyin: "néng", wordType: null, meaning: "can, may" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
    ],
  },
  {
    chapterNumber: 12,
    words: [
      { chinese: "昨天", pinyin: "zuótiān", wordType: null, meaning: "yesterday" },
      { chinese: "北京", pinyin: "Běijīng", wordType: "prop. n.", meaning: "Beijing" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "天气", pinyin: "tiānqì", wordType: "n.", meaning: "weather" },
      { chinese: "怎么样", pinyin: "zěnmeyàng", wordType: "pron.", meaning: "how" },
      { chinese: "太", pinyin: "tài", wordType: "adv.", meaning: "too, excessively" },
      { chinese: "热", pinyin: "rè", wordType: "adj.", meaning: "hot" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "明天", pinyin: "míngtiān", wordType: null, meaning: "tomorrow" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "很", pinyin: "hěn", wordType: null, meaning: "very, quite" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "冷", pinyin: "lěng", wordType: "adj.", meaning: "cold" },
      { chinese: "今天", pinyin: "jīntiān", wordType: null, meaning: "today" },
      { chinese: "会", pinyin: "huì", wordType: null, meaning: "can, to be able to" },
      { chinese: "下雨", pinyin: "xià yǔ", wordType: "v.", meaning: "to rain" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "王", pinyin: "Wáng", wordType: "prop. n.", meaning: "(surname) Wang" },
      { chinese: "小姐", pinyin: "xiǎojiě", wordType: "n.", meaning: "miss, young lady" },
      { chinese: "来", pinyin: "lái", wordType: "v.", meaning: "to come" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "身体", pinyin: "shēntǐ", wordType: "n.", meaning: "body" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "爱", pinyin: "ài", wordType: "v.", meaning: "to like, to love" },
      { chinese: "吃饭", pinyin: "chī fàn", wordType: null, meaning: "to eat a meal" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
      { chinese: "吃", pinyin: "chī", wordType: null, meaning: "to eat" },
      { chinese: "些", pinyin: "xiē", wordType: "m.", meaning: "some, a few" },
      { chinese: "水果", pinyin: "shuǐguǒ", wordType: "n.", meaning: "fruit" },
      { chinese: "喝", pinyin: "hē", wordType: null, meaning: "to drink" },
      { chinese: "水", pinyin: "shuǐ", wordType: "n.", meaning: "water" },
      { chinese: "谢谢", pinyin: "xièxie", wordType: null, meaning: "to thank" },
      { chinese: "医生", pinyin: "yīshēng", wordType: null, meaning: "doctor" },
    ],
  },
  {
    chapterNumber: 13,
    words: [
      { chinese: "喂", pinyin: "wèi", wordType: "int.", meaning: "hello, hey" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "做", pinyin: "zuò", wordType: null, meaning: "to make, to produce" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "看", pinyin: "kàn", wordType: null, meaning: "to look at, to watch, to read" },
      { chinese: "书", pinyin: "shū", wordType: null, meaning: "book" },
      { chinese: "大卫", pinyin: "Dàwèi", wordType: "prop. n.", meaning: "David" },
      { chinese: "也", pinyin: "yě", wordType: "adv.", meaning: "also, too" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "没", pinyin: "méi", wordType: null, meaning: "there is not" },
      { chinese: "学", pinyin: "xué", wordType: null, meaning: "to learn (a skill/subject)" },
      { chinese: "中国", pinyin: "Zhōngguó", wordType: "prop. n.", meaning: "China" },
      { chinese: "菜", pinyin: "cài", wordType: null, meaning: "dish, cuisine" },
      { chinese: "昨天", pinyin: "zuótiān", wordType: null, meaning: "yesterday" },
      { chinese: "上午", pinyin: "shàngwǔ", wordType: "n.", meaning: "morning" },
      { chinese: "睡觉", pinyin: "shuìjiào", wordType: "v.", meaning: "to sleep" },
      { chinese: "家", pinyin: "jiā", wordType: null, meaning: "family" },
      { chinese: "电视", pinyin: "diànshì", wordType: "n.", meaning: "television" },
      { chinese: "喜欢", pinyin: "xǐhuān", wordType: "v.", meaning: "to like, to be fond of" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "电影", pinyin: "diànyǐng", wordType: null, meaning: "film, movie" },
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "李", pinyin: "Lǐ", wordType: "prop. n.", meaning: "(surname) Li" },
      { chinese: "老师", pinyin: "lǎoshī", wordType: null, meaning: "teacher" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "电话", pinyin: "diànhuà", wordType: "n.", meaning: "telephone, phone call" },
      { chinese: "她", pinyin: "tā", wordType: null, meaning: "she, her" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "现在", pinyin: "xiànzài", wordType: null, meaning: "now" },
      { chinese: "给", pinyin: "gěi", wordType: "prep.", meaning: "to (indirect object)" },
      { chinese: "打电话", pinyin: "dǎ diànhuà", wordType: "v.", meaning: "to make a phone call" },
      { chinese: "工作", pinyin: "gōngzuò", wordType: null, meaning: "to work; job" },
      { chinese: "下午", pinyin: "xiàwǔ", wordType: null, meaning: "afternoon" },
      { chinese: "打", pinyin: "dǎ", wordType: null, meaning: "to send, to remit" },
      { chinese: "吧", pinyin: "ba", wordType: "part.", meaning: "modal particle (suggestion/request)" },
    ],
  },
  {
    chapterNumber: 14,
    words: [
      { chinese: "昨天", pinyin: "zuótiān", wordType: null, meaning: "yesterday" },
      { chinese: "上午", pinyin: "shàngwǔ", wordType: null, meaning: "morning, before noon" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "哪儿", pinyin: "nǎr", wordType: null, meaning: "where" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "商店", pinyin: "shāngdiàn", wordType: null, meaning: "shop, store" },
      { chinese: "买", pinyin: "mǎi", wordType: null, meaning: "to buy, to purchase" },
      { chinese: "东西", pinyin: "dōngxi", wordType: "n.", meaning: "thing, stuff" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "一点儿", pinyin: "yīdiǎnr", wordType: "num.-m.", meaning: "a few, a little" },
      { chinese: "苹果", pinyin: "píngguǒ", wordType: "n.", meaning: "apple" },
      { chinese: "看见", pinyin: "kànjiàn", wordType: "v.", meaning: "to see" },
      { chinese: "张", pinyin: "Zhāng", wordType: "prop. n.", meaning: "Zhang (family name)" },
      { chinese: "先生", pinyin: "xiānsheng", wordType: "n.", meaning: "Mr., sir" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "学", pinyin: "xué", wordType: null, meaning: "to learn (a skill/subject)" },
      { chinese: "开", pinyin: "kāi", wordType: "v.", meaning: "to drive" },
      { chinese: "车", pinyin: "chē", wordType: "n.", meaning: "car, vehicle" },
      { chinese: "时候", pinyin: "shíhou", wordType: null, meaning: "time, moment" },
      { chinese: "能", pinyin: "néng", wordType: null, meaning: "can, may" },
      { chinese: "回来", pinyin: "huílái", wordType: "v.", meaning: "to come back" },
      { chinese: "分钟", pinyin: "fēnzhōng", wordType: "n.", meaning: "minute" },
      { chinese: "后", pinyin: "hòu", wordType: "n.", meaning: "after, afterwards" },
      { chinese: "王方", pinyin: "Wáng Fāng", wordType: "prop. n.", meaning: "Wang Fang (name)" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "衣服", pinyin: "yīfu", wordType: "n.", meaning: "clothes" },
      { chinese: "太", pinyin: "tài", wordType: null, meaning: "too, excessively" },
      { chinese: "漂亮", pinyin: "piàoliang", wordType: "adj.", meaning: "beautiful, pretty" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "啊", pinyin: "a", wordType: "part.", meaning: "modal particle (confirmation)" },
      { chinese: "她", pinyin: "tā", wordType: null, meaning: "she, her" },
      { chinese: "不少", pinyin: "bùshǎo", wordType: "adj.", meaning: "quite a few" },
      { chinese: "没", pinyin: "méi", wordType: null, meaning: "there is not" },
      { chinese: "这些", pinyin: "zhèxiē", wordType: "pron.", meaning: "these" },
      { chinese: "都", pinyin: "dōu", wordType: "adv.", meaning: "both, all" },
    ],
  },
  {
    chapterNumber: 15,
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "和", pinyin: "hé", wordType: null, meaning: "and" },
      { chinese: "李", pinyin: "Lǐ", wordType: "prop. n.", meaning: "(surname) Li" },
      { chinese: "小姐", pinyin: "xiǎojiě", wordType: null, meaning: "miss, young lady" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "时候", pinyin: "shíhou", wordType: null, meaning: "time, moment" },
      { chinese: "认识", pinyin: "rènshi", wordType: "v.", meaning: "to meet, to know" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "年", pinyin: "nián", wordType: "n.", meaning: "year" },
      { chinese: "月", pinyin: "yuè", wordType: null, meaning: "month" },
      { chinese: "你们", pinyin: "nǐmen", wordType: null, meaning: "(plural) you" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "哪儿", pinyin: "nǎr", wordType: null, meaning: "where" },
      { chinese: "学校", pinyin: "xuéxiào", wordType: null, meaning: "school" },
      { chinese: "她", pinyin: "tā", wordType: null, meaning: "she, her" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "大学", pinyin: "dàxué", wordType: "n.", meaning: "college, university" },
      { chinese: "同学", pinyin: "tóngxué", wordType: null, meaning: "classmate" },
      { chinese: "怎么", pinyin: "zěnme", wordType: null, meaning: "(indicating nature, condition or manner, etc.) how" },
      { chinese: "来", pinyin: "lái", wordType: null, meaning: "to come" },
      { chinese: "饭店", pinyin: "fàndiàn", wordType: "n.", meaning: "hotel, restaurant" },
      { chinese: "坐", pinyin: "zuò", wordType: null, meaning: "to sit, to be seated" },
      { chinese: "出租车", pinyin: "chūzūchē", wordType: "n.", meaning: "taxi, cab" },
      { chinese: "先生", pinyin: "xiānsheng", wordType: null, meaning: "Mr., sir" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "朋友", pinyin: "péngyou", wordType: null, meaning: "friend" },
      { chinese: "一起", pinyin: "yìqǐ", wordType: "adv.", meaning: "together" },
      { chinese: "开", pinyin: "kāi", wordType: null, meaning: "to drive; to open out, to unfold" },
      { chinese: "车", pinyin: "chē", wordType: null, meaning: "car, vehicle" },
      { chinese: "很", pinyin: "hěn", wordType: null, meaning: "very, quite" },
      { chinese: "高兴", pinyin: "gāoxìng", wordType: "adj.", meaning: "glad, happy" },
      { chinese: "您", pinyin: "nín", wordType: null, meaning: "(polite) you" },
      { chinese: "也", pinyin: "yě", wordType: null, meaning: "also, too" },
      { chinese: "听", pinyin: "tīng", wordType: "v.", meaning: "to listen" },
      { chinese: "张", pinyin: "zhāng", wordType: null, meaning: "used for flat objects such as paper, photos, etc." },
      { chinese: "说", pinyin: "shuō", wordType: null, meaning: "to speak, to say" },
      { chinese: "飞机", pinyin: "fēijī", wordType: "n.", meaning: "airplane" },
      { chinese: "北京", pinyin: "Běijīng", wordType: "prop. n.", meaning: "Beijing" },
    ],
  },
];
