import type { TranscriptLineRow } from "./extract-transcripts";

// HSK1 chapters' actual dialog transcripts — docs/25-chapter-all-words
// -plan.md's addendum. Auto-extracted (scripts-tmp-extract-transcripts.ts)
// from the same pasted textbook dialog text the All Words vocabulary was
// segmented from — this captures the full sentences (speaker, pinyin,
// English) rather than just the words used in them.

export interface Hsk1ChapterTranscriptData {
  chapterNumber: number;
  lines: TranscriptLineRow[];
}

export const HSK1_CHAPTER_TRANSCRIPTS: Hsk1ChapterTranscriptData[] = [
  {
    chapterNumber: 1,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: null, speaker: "A", chinese: "你好！", pinyin: "Nǐ hǎo!", english: "Hello!" },
      { order: 2, dialogNumber: 1, dialogLabel: null, speaker: "B", chinese: "你好！", pinyin: "Nǐ hǎo!", english: "Hello!" },
      { order: 3, dialogNumber: 2, dialogLabel: null, speaker: "A", chinese: "您好！", pinyin: "Nín hǎo!", english: "Hello! (polite)" },
      { order: 4, dialogNumber: 2, dialogLabel: null, speaker: "B", chinese: "你们好！", pinyin: "Nǐmen hǎo!", english: "Hello! (plural)" },
      { order: 5, dialogNumber: 3, dialogLabel: null, speaker: "A", chinese: "对不起！", pinyin: "Duìbuqǐ!", english: "I'm sorry!" },
      { order: 6, dialogNumber: 3, dialogLabel: null, speaker: "B", chinese: "没关系！", pinyin: "Méi guānxi!", english: "That's OK!" },
    ],
  },
  {
    chapterNumber: 2,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: null, speaker: "A", chinese: "谢谢！", pinyin: "Xièxie!", english: "Thank you!" },
      { order: 2, dialogNumber: 1, dialogLabel: null, speaker: "B", chinese: "不谢！", pinyin: "Bú xiè!", english: "Sure!" },
      { order: 3, dialogNumber: 2, dialogLabel: null, speaker: "A", chinese: "谢谢你！", pinyin: "Xièxie nǐ!", english: "Thank you!" },
      { order: 4, dialogNumber: 2, dialogLabel: null, speaker: "B", chinese: "不客气！", pinyin: "Bú kèqi!", english: "You're welcome!" },
      { order: 5, dialogNumber: 3, dialogLabel: null, speaker: "A", chinese: "再见！", pinyin: "Zàijiàn!", english: "Goodbye!" },
      { order: 6, dialogNumber: 3, dialogLabel: null, speaker: "B", chinese: "再见！", pinyin: "Zàijiàn!", english: "Bye!" },
    ],
  },
  {
    chapterNumber: 3,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the school", speaker: "A", chinese: "你叫什么名字？", pinyin: "Nǐ jiào shénme míngzi?", english: "What's your name?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the school", speaker: "B", chinese: "我叫李月。", pinyin: "Wǒ jiào Lǐ Yuè.", english: "My name is Li Yue." },
      { order: 3, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "A", chinese: "你是老师吗？", pinyin: "Nǐ shì lǎoshī ma?", english: "Are you a teacher?" },
      { order: 4, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "B", chinese: "我不是老师，我是学生。", pinyin: "Wǒ bú shì lǎoshī, wǒ shì xuésheng.", english: "I'm not a teacher, I'm a student." },
      { order: 5, dialogNumber: 3, dialogLabel: "In the school", speaker: "A", chinese: "你是中国人吗？", pinyin: "Nǐ shì Zhōngguó rén ma?", english: "Are you Chinese?" },
      { order: 6, dialogNumber: 3, dialogLabel: "In the school", speaker: "B", chinese: "我不是中国人，我是美国人。", pinyin: "Wǒ bú shì Zhōngguó rén, wǒ shì Měiguó rén.", english: "I'm not Chinese, I'm American." },
    ],
  },
  {
    chapterNumber: 4,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "A", chinese: "她是谁？", pinyin: "Tā shì shéi?", english: "Who is she?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "B", chinese: "她是我的汉语老师，她叫李月。", pinyin: "Tā shì wǒ de Hànyǔ lǎoshī, tā jiào Lǐ Yuè.", english: "She is my Chinese teacher. Her name is Li Yue." },
      { order: 3, dialogNumber: 2, dialogLabel: "In the library", speaker: "A", chinese: "你是哪国人？", pinyin: "Nǐ shì nǎ guó rén?", english: "Which country are you from?" },
      { order: 4, dialogNumber: 2, dialogLabel: "In the library", speaker: "B", chinese: "我是美国人。你呢？", pinyin: "Wǒ shì Měiguó rén. Nǐ ne?", english: "I'm American. What about you?" },
      { order: 5, dialogNumber: 2, dialogLabel: "In the library", speaker: "A", chinese: "我是中国人。", pinyin: "Wǒ shì Zhōngguó rén.", english: "I'm Chinese." },
      { order: 6, dialogNumber: 3, dialogLabel: "Looking at a photo", speaker: "A", chinese: "他是谁？", pinyin: "Tā shì shéi?", english: "Who is he?" },
      { order: 7, dialogNumber: 3, dialogLabel: "Looking at a photo", speaker: "B", chinese: "他是我同学。", pinyin: "Tā shì wǒ tóngxué.", english: "He is my classmate." },
      { order: 8, dialogNumber: 3, dialogLabel: "Looking at a photo", speaker: "A", chinese: "她呢？她是你同学吗？", pinyin: "Tā ne? Tā shì nǐ tóngxué ma?", english: "What about her? Is she your classmate?" },
      { order: 9, dialogNumber: 3, dialogLabel: "Looking at a photo", speaker: "B", chinese: "她不是我同学，她是我朋友。", pinyin: "Tā bú shì wǒ tóngxué, tā shì wǒ péngyou.", english: "She is not my classmate, she is my friend." },
    ],
  },
  {
    chapterNumber: 5,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the school", speaker: "A", chinese: "你家有几口人？", pinyin: "Nǐ jiā yǒu jǐ kǒu rén?", english: "How many people are there in your family?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the school", speaker: "B", chinese: "我家有三口人。", pinyin: "Wǒ jiā yǒu sān kǒu rén.", english: "There are three people in my family." },
      { order: 3, dialogNumber: 2, dialogLabel: "In the office", speaker: "A", chinese: "你女儿几岁了？", pinyin: "Nǐ nǚ'ér jǐ suì le?", english: "How old is your daughter?" },
      { order: 4, dialogNumber: 2, dialogLabel: "In the office", speaker: "B", chinese: "她今年四岁了。", pinyin: "Tā jīnnián sì suì le.", english: "She is four years old this year." },
      { order: 5, dialogNumber: 3, dialogLabel: "In the office", speaker: "A", chinese: "李老师多大了？", pinyin: "Lǐ lǎoshī duō dà le?", english: "How old is Teacher Li?" },
      { order: 6, dialogNumber: 3, dialogLabel: "In the office", speaker: "B", chinese: "她今年50岁了。", pinyin: "Tā jīnnián wǔshí suì le.", english: "She is 50 years old this year." },
      { order: 7, dialogNumber: 3, dialogLabel: "In the office", speaker: "A", chinese: "她女儿呢？", pinyin: "Tā nǚ'ér ne?", english: "What about her daughter?" },
      { order: 8, dialogNumber: 3, dialogLabel: "In the office", speaker: "B", chinese: "她女儿今年20岁。", pinyin: "Tā nǚ'ér jīnnián èrshí suì.", english: "Her daughter is 20 years old this year." },
    ],
  },
  {
    chapterNumber: 6,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the school", speaker: "A", chinese: "你会说汉语吗？", pinyin: "Nǐ huì shuō Hànyǔ ma?", english: "Can you speak Chinese?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the school", speaker: "B", chinese: "我会说汉语。", pinyin: "Wǒ huì shuō Hànyǔ.", english: "I can speak Chinese." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the school", speaker: "A", chinese: "你妈妈会说汉语吗？", pinyin: "Nǐ māma huì shuō Hànyǔ ma?", english: "Can your mother speak Chinese?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the school", speaker: "B", chinese: "她不会说。", pinyin: "Tā bú huì shuō.", english: "She can't." },
      { order: 5, dialogNumber: 2, dialogLabel: "In the kitchen", speaker: "A", chinese: "中国菜好吃吗？", pinyin: "Zhōngguó cài hǎochī ma?", english: "Is Chinese food delicious?" },
      { order: 6, dialogNumber: 2, dialogLabel: "In the kitchen", speaker: "B", chinese: "中国菜很好吃。", pinyin: "Zhōngguó cài hěn hǎochī.", english: "Chinese food is delicious." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the kitchen", speaker: "A", chinese: "你会做中国菜吗？", pinyin: "Nǐ huì zuò Zhōngguó cài ma?", english: "Can you cook Chinese food?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In the kitchen", speaker: "B", chinese: "我不会做。", pinyin: "Wǒ bú huì zuò.", english: "I can't." },
      { order: 9, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "A", chinese: "你会写汉字吗？", pinyin: "Nǐ huì xiě Hànzì ma?", english: "Can you write Chinese characters?" },
      { order: 10, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "B", chinese: "我会写。", pinyin: "Wǒ huì xiě.", english: "I can." },
      { order: 11, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "A", chinese: "这个字怎么写？", pinyin: "Zhège zì zěnme xiě?", english: "How do you write this character?" },
      { order: 12, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "B", chinese: "对不起，这个字我会读，不会写。", pinyin: "Duìbuqǐ, zhège zì wǒ huì dú, bú huì xiě.", english: "Sorry. I can read this character, but I can't write it." },
    ],
  },
  {
    chapterNumber: 7,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the bank", speaker: "A", chinese: "请问，今天几号？", pinyin: "Qǐngwèn, jīntiān jǐ hào?", english: "Excuse me, what's the date today?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the bank", speaker: "B", chinese: "今天9月1号。", pinyin: "Jīntiān jiǔ yuè yī hào.", english: "Today is September 1st." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the bank", speaker: "A", chinese: "今天星期几？", pinyin: "Jīntiān xīngqī jǐ?", english: "What day is it today?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the bank", speaker: "B", chinese: "星期三。", pinyin: "Xīngqī sān.", english: "Wednesday." },
      { order: 5, dialogNumber: 2, dialogLabel: "Looking at the calendar", speaker: "A", chinese: "昨天是几月几号？", pinyin: "Zuótiān shì jǐ yuè jǐ hào?", english: "What was the date yesterday?" },
      { order: 6, dialogNumber: 2, dialogLabel: "Looking at the calendar", speaker: "B", chinese: "昨天是8月31号，星期二。", pinyin: "Zuótiān shì bā yuè sānshíyī hào, xīngqī èr.", english: "Yesterday was August 31st, Tuesday." },
      { order: 7, dialogNumber: 2, dialogLabel: "Looking at the calendar", speaker: "A", chinese: "明天呢？", pinyin: "Míngtiān ne?", english: "What about tomorrow?" },
      { order: 8, dialogNumber: 2, dialogLabel: "Looking at the calendar", speaker: "B", chinese: "明天是9月2号，星期四。", pinyin: "Míngtiān shì jiǔ yuè èr hào, xīngqī sì.", english: "Tomorrow is September 2nd, Thursday." },
      { order: 9, dialogNumber: 3, dialogLabel: "In a coffee house", speaker: "A", chinese: "明天星期六，你去学校吗？", pinyin: "Míngtiān xīngqī liù, nǐ qù xuéxiào ma?", english: "Tomorrow is Saturday. Will you go to school?" },
      { order: 10, dialogNumber: 3, dialogLabel: "In a coffee house", speaker: "B", chinese: "我去学校。", pinyin: "Wǒ qù xuéxiào.", english: "I'll go to school." },
      { order: 11, dialogNumber: 3, dialogLabel: "In a coffee house", speaker: "A", chinese: "你去学校做什么？", pinyin: "Nǐ qù xuéxiào zuò shénme?", english: "What are you going to do there?" },
      { order: 12, dialogNumber: 3, dialogLabel: "In a coffee house", speaker: "B", chinese: "我去学校看书。", pinyin: "Wǒ qù xuéxiào kàn shū.", english: "I'm going there to read books." },
    ],
  },
  {
    chapterNumber: 8,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In a restaurant", speaker: "A", chinese: "你想喝什么？", pinyin: "Nǐ xiǎng hē shénme?", english: "What would you like to drink?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In a restaurant", speaker: "B", chinese: "我想喝茶。", pinyin: "Wǒ xiǎng hē chá.", english: "I'd like some tea." },
      { order: 3, dialogNumber: 1, dialogLabel: "In a restaurant", speaker: "A", chinese: "你想吃什么？", pinyin: "Nǐ xiǎng chī shénme?", english: "What would you like to eat?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In a restaurant", speaker: "B", chinese: "我想吃米饭。", pinyin: "Wǒ xiǎng chī mǐfàn.", english: "I'd like rice." },
      { order: 5, dialogNumber: 2, dialogLabel: "In the living room", speaker: "A", chinese: "下午你想做什么？", pinyin: "Xiàwǔ nǐ xiǎng zuò shénme?", english: "What would you like to do this afternoon?" },
      { order: 6, dialogNumber: 2, dialogLabel: "In the living room", speaker: "B", chinese: "下午我想去商店。", pinyin: "Xiàwǔ wǒ xiǎng qù shāngdiàn.", english: "I'd like to go to the store." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the living room", speaker: "A", chinese: "你想买什么？", pinyin: "Nǐ xiǎng mǎi shénme?", english: "What do you want to buy?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In the living room", speaker: "B", chinese: "我想买一个杯子。", pinyin: "Wǒ xiǎng mǎi yí gè bēizi.", english: "I want to buy a cup." },
      { order: 9, dialogNumber: 3, dialogLabel: "At the store", speaker: "A", chinese: "你好！这个杯子多少钱？", pinyin: "Nǐ hǎo! Zhège bēizi duōshao qián?", english: "Hello! How much is this cup?" },
      { order: 10, dialogNumber: 3, dialogLabel: "At the store", speaker: "B", chinese: "28块。", pinyin: "Èrshíbā kuài.", english: "28 yuan." },
      { order: 11, dialogNumber: 3, dialogLabel: "At the store", speaker: "A", chinese: "那个杯子多少钱？", pinyin: "Nàge bēizi duōshao qián?", english: "How much is that cup?" },
      { order: 12, dialogNumber: 3, dialogLabel: "At the store", speaker: "B", chinese: "那个杯子18块钱。", pinyin: "Nàge bēizi shíbā kuài qián.", english: "That cup is 18 yuan." },
    ],
  },
  {
    chapterNumber: 9,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "Looking for pets", speaker: "A", chinese: "小猫在哪儿？", pinyin: "Xiǎo māo zài nǎr?", english: "Where is the kitty?" },
      { order: 2, dialogNumber: 1, dialogLabel: "Looking for pets", speaker: "B", chinese: "小猫在那儿。", pinyin: "Xiǎo māo zài nàr.", english: "The kitty is over there." },
      { order: 3, dialogNumber: 1, dialogLabel: "Looking for pets", speaker: "A", chinese: "小狗在哪儿？", pinyin: "Xiǎo gǒu zài nǎr?", english: "Where is the puppy?" },
      { order: 4, dialogNumber: 1, dialogLabel: "Looking for pets", speaker: "B", chinese: "小狗在椅子下面。", pinyin: "Xiǎo gǒu zài yǐzi xiàmiàn.", english: "The puppy is under the chair." },
      { order: 5, dialogNumber: 2, dialogLabel: "At the railway station", speaker: "A", chinese: "你在哪儿工作？", pinyin: "Nǐ zài nǎr gōngzuò?", english: "Where do you work?" },
      { order: 6, dialogNumber: 2, dialogLabel: "At the railway station", speaker: "B", chinese: "我在学校工作。", pinyin: "Wǒ zài xuéxiào gōngzuò.", english: "I work at a school." },
      { order: 7, dialogNumber: 2, dialogLabel: "At the railway station", speaker: "A", chinese: "你儿子在哪儿工作？", pinyin: "Nǐ érzi zài nǎr gōngzuò?", english: "Where does your son work?" },
      { order: 8, dialogNumber: 2, dialogLabel: "At the railway station", speaker: "B", chinese: "我儿子在医院工作，他是医生。", pinyin: "Wǒ érzi zài yīyuàn gōngzuò, tā shì yīshēng.", english: "My son works at a hospital. He is a doctor." },
      { order: 9, dialogNumber: 3, dialogLabel: "On the phone", speaker: "A", chinese: "你爸爸在家吗？", pinyin: "Nǐ bàba zài jiā ma?", english: "Is your father at home?" },
      { order: 10, dialogNumber: 3, dialogLabel: "On the phone", speaker: "B", chinese: "不在家。", pinyin: "Bú zài jiā.", english: "He's not at home." },
      { order: 11, dialogNumber: 3, dialogLabel: "On the phone", speaker: "A", chinese: "他在哪儿呢？", pinyin: "Tā zài nǎr ne?", english: "Where is he?" },
      { order: 12, dialogNumber: 3, dialogLabel: "On the phone", speaker: "B", chinese: "他在医院。", pinyin: "Tā zài yīyuàn.", english: "He's at the hospital." },
    ],
  },
  {
    chapterNumber: 10,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the office", speaker: "A", chinese: "桌子上有什么？", pinyin: "Zhuōzi shang yǒu shénme?", english: "What is on the desk?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the office", speaker: "B", chinese: "桌子上有一个电脑和一本书。", pinyin: "Zhuōzi shang yǒu yí gè diànnǎo hé yì běn shū.", english: "There is a computer and a book on the desk." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the office", speaker: "A", chinese: "杯子在哪儿？", pinyin: "Bēizi zài nǎr?", english: "Where is the cup?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the office", speaker: "B", chinese: "杯子在桌子里。", pinyin: "Bēizi zài zhuōzi li.", english: "The cup is in the desk." },
      { order: 5, dialogNumber: 2, dialogLabel: "In the office", speaker: "A", chinese: "前面那个人叫什么名字？", pinyin: "Qiánmiàn nàge rén jiào shénme míngzi?", english: "What's the name of the person in front?" },
      { order: 6, dialogNumber: 2, dialogLabel: "In the office", speaker: "B", chinese: "她叫王方，在医院工作。", pinyin: "Tā jiào Wáng Fāng, zài yīyuàn gōngzuò.", english: "Her name is Wang Fang. She works at a hospital." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the office", speaker: "A", chinese: "后面那个人呢？他叫什么名字？", pinyin: "Hòumiàn nàge rén ne? Tā jiào shénme míngzi?", english: "What about the person behind? What's his name?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In the office", speaker: "B", chinese: "他叫谢朋，在商店工作。", pinyin: "Tā jiào Xiè Péng, zài shāngdiàn gōngzuò.", english: "His name is Xie Peng. He works at a store." },
      { order: 9, dialogNumber: 3, dialogLabel: "In the library", speaker: "A", chinese: "这儿有人吗？", pinyin: "Zhèr yǒu rén ma?", english: "Is this seat taken?" },
      { order: 10, dialogNumber: 3, dialogLabel: "In the library", speaker: "B", chinese: "没有。", pinyin: "Méiyǒu.", english: "No, it isn't." },
      { order: 11, dialogNumber: 3, dialogLabel: "In the library", speaker: "A", chinese: "我能坐这儿吗？", pinyin: "Wǒ néng zuò zhèr ma?", english: "Can I sit here?" },
      { order: 12, dialogNumber: 3, dialogLabel: "In the library", speaker: "B", chinese: "请坐。", pinyin: "Qǐng zuò.", english: "Please sit down." },
    ],
  },
  {
    chapterNumber: 11,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "Checking the time", speaker: "A", chinese: "现在几点？", pinyin: "Xiànzài jǐ diǎn?", english: "What's the time now?" },
      { order: 2, dialogNumber: 1, dialogLabel: "Checking the time", speaker: "B", chinese: "现在十点十分。", pinyin: "Xiànzài shí diǎn shí fēn.", english: "It's ten past ten." },
      { order: 3, dialogNumber: 1, dialogLabel: "Checking the time", speaker: "A", chinese: "中午几点吃饭？", pinyin: "Zhōngwǔ jǐ diǎn chī fàn?", english: "When shall we have lunch?" },
      { order: 4, dialogNumber: 1, dialogLabel: "Checking the time", speaker: "B", chinese: "十二点吃饭。", pinyin: "Shí'èr diǎn chī fàn.", english: "At twelve o'clock." },
      { order: 5, dialogNumber: 2, dialogLabel: "At home", speaker: "A", chinese: "爸爸什么时候回家？", pinyin: "Bàba shénme shíhou huí jiā?", english: "When is Dad coming home?" },
      { order: 6, dialogNumber: 2, dialogLabel: "At home", speaker: "B", chinese: "下午五点。", pinyin: "Xiàwǔ wǔ diǎn.", english: "At five in the afternoon." },
      { order: 7, dialogNumber: 2, dialogLabel: "At home", speaker: "A", chinese: "我们什么时候去看电影？", pinyin: "Wǒmen shénme shíhou qù kàn diànyǐng?", english: "When are we going to see the movie?" },
      { order: 8, dialogNumber: 2, dialogLabel: "At home", speaker: "B", chinese: "六点三十分。", pinyin: "Liù diǎn sānshí fēn.", english: "At half past six." },
      { order: 9, dialogNumber: 3, dialogLabel: "At home", speaker: "A", chinese: "我星期一去北京。", pinyin: "Wǒ xīngqī yī qù Běijīng.", english: "I'll go to Beijing on Monday." },
      { order: 10, dialogNumber: 3, dialogLabel: "At home", speaker: "B", chinese: "你想在北京住几天？", pinyin: "Nǐ xiǎng zài Běijīng zhù jǐ tiān?", english: "How long will you stay in Beijing?" },
      { order: 11, dialogNumber: 3, dialogLabel: "At home", speaker: "A", chinese: "住三天。", pinyin: "Zhù sān tiān.", english: "For three days." },
      { order: 12, dialogNumber: 3, dialogLabel: "At home", speaker: "B", chinese: "星期五前能回家吗？", pinyin: "Xīngqī wǔ qián néng huí jiā ma?", english: "Can you come back before Friday?" },
      { order: 13, dialogNumber: 3, dialogLabel: "At home", speaker: "A", chinese: "能。", pinyin: "Néng.", english: "Yes, I can." },
    ],
  },
  {
    chapterNumber: 12,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "On the road", speaker: "A", chinese: "昨天北京的天气怎么样？", pinyin: "Zuótiān Běijīng de tiānqì zěnmeyàng?", english: "How was the weather in Beijing yesterday?" },
      { order: 2, dialogNumber: 1, dialogLabel: "On the road", speaker: "B", chinese: "太热了。", pinyin: "Tài rè le.", english: "It was too hot." },
      { order: 3, dialogNumber: 1, dialogLabel: "On the road", speaker: "A", chinese: "明天呢？明天天气怎么样？", pinyin: "Míngtiān ne? Míngtiān tiānqì zěnmeyàng?", english: "What about tomorrow? What will the weather be like tomorrow?" },
      { order: 4, dialogNumber: 1, dialogLabel: "On the road", speaker: "B", chinese: "明天天气很好，不冷不热。", pinyin: "Míngtiān tiānqì hěn hǎo, bù lěng bú rè.", english: "Tomorrow's weather will be very good, neither cold nor hot." },
      { order: 5, dialogNumber: 2, dialogLabel: "On the road", speaker: "A", chinese: "今天会下雨吗？", pinyin: "Jīntiān huì xià yǔ ma?", english: "Will it rain today?" },
      { order: 6, dialogNumber: 2, dialogLabel: "On the road", speaker: "B", chinese: "今天不会下雨。", pinyin: "Jīntiān bú huì xià yǔ.", english: "It won't rain today." },
      { order: 7, dialogNumber: 2, dialogLabel: "On the road", speaker: "A", chinese: "王小姐今天会来吗？", pinyin: "Wáng xiǎojiě jīntiān huì lái ma?", english: "Will Miss Wang come today?" },
      { order: 8, dialogNumber: 2, dialogLabel: "On the road", speaker: "B", chinese: "不会来，天气太冷了。", pinyin: "Bú huì lái, tiānqì tài lěng le.", english: "She won't come. The weather is too cold." },
      { order: 9, dialogNumber: 3, dialogLabel: "In the sickroom", speaker: "A", chinese: "你身体怎么样？", pinyin: "Nǐ shēntǐ zěnmeyàng?", english: "How are you?" },
      { order: 10, dialogNumber: 3, dialogLabel: "In the sickroom", speaker: "B", chinese: "我身体不太好。天气太热了，不爱吃饭。", pinyin: "Wǒ shēntǐ bú tài hǎo. Tiānqì tài rè le, bú ài chī fàn.", english: "I'm not very well. It's too hot. I have no appetite." },
      { order: 11, dialogNumber: 3, dialogLabel: "In the sickroom", speaker: "A", chinese: "你多吃些水果，多喝水。", pinyin: "Nǐ duō chī xiē shuǐguǒ, duō hē shuǐ.", english: "Eat more fruit and drink more water." },
      { order: 12, dialogNumber: 3, dialogLabel: "In the sickroom", speaker: "B", chinese: "谢谢你，医生。", pinyin: "Xièxie nǐ, yīshēng.", english: "Thank you, doctor." },
    ],
  },
  {
    chapterNumber: 13,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "On the phone", speaker: "A", chinese: "喂，你在做什么呢？", pinyin: "Wèi, nǐ zài zuò shénme ne?", english: "Hello, what are you doing?" },
      { order: 2, dialogNumber: 1, dialogLabel: "On the phone", speaker: "B", chinese: "我在看书呢。", pinyin: "Wǒ zài kàn shū ne.", english: "I'm reading." },
      { order: 3, dialogNumber: 1, dialogLabel: "On the phone", speaker: "A", chinese: "大卫也在看书吗？", pinyin: "Dàwèi yě zài kàn shū ma?", english: "Is David reading too?" },
      { order: 4, dialogNumber: 1, dialogLabel: "On the phone", speaker: "B", chinese: "他没看书，他在学做中国菜呢。", pinyin: "Tā méi kàn shū, tā zài xué zuò Zhōngguó cài ne.", english: "He's not reading. He's learning to cook Chinese food." },
      { order: 5, dialogNumber: 2, dialogLabel: "In a coffee house", speaker: "A", chinese: "昨天上午你在做什么呢？", pinyin: "Zuótiān shàngwǔ nǐ zài zuò shénme ne?", english: "What were you doing yesterday morning?" },
      { order: 6, dialogNumber: 2, dialogLabel: "In a coffee house", speaker: "B", chinese: "我在睡觉呢。你呢？", pinyin: "Wǒ zài shuìjiào ne. Nǐ ne?", english: "I was sleeping. What about you?" },
      { order: 7, dialogNumber: 2, dialogLabel: "In a coffee house", speaker: "A", chinese: "我在家看电视呢。你喜欢看电视吗？", pinyin: "Wǒ zài jiā kàn diànshì ne. Nǐ xǐhuān kàn diànshì ma?", english: "I was watching TV at home. Do you like watching TV?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In a coffee house", speaker: "B", chinese: "我不喜欢看电视，我喜欢看电影。", pinyin: "Wǒ bù xǐhuān kàn diànshì, wǒ xǐhuān kàn diànyǐng.", english: "I don't like watching TV. I like watching movies." },
      { order: 9, dialogNumber: 3, dialogLabel: "In the school office", speaker: "A", chinese: "82304155，这是李老师的电话吗？", pinyin: "Bā èr sān líng sì yāo wǔ wǔ, zhè shì Lǐ lǎoshī de diànhuà ma?", english: "82304155. Is that Teacher Li's phone number?" },
      { order: 10, dialogNumber: 3, dialogLabel: "In the school office", speaker: "B", chinese: "不是。她的电话是82304156。", pinyin: "Bú shì. Tā de diànhuà shì bā èr sān líng sì yāo wǔ liù.", english: "No. Her number is 82304156." },
      { order: 11, dialogNumber: 3, dialogLabel: "In the school office", speaker: "A", chinese: "好，我现在给她打电话。", pinyin: "Hǎo, wǒ xiànzài gěi tā dǎ diànhuà.", english: "OK, I'll call her right now." },
      { order: 12, dialogNumber: 3, dialogLabel: "In the school office", speaker: "B", chinese: "她在工作呢，你下午打吧。", pinyin: "Tā zài gōngzuò ne, nǐ xiàwǔ dǎ ba.", english: "She's working. Call her in the afternoon." },
    ],
  },
  {
    chapterNumber: 14,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the dorm", speaker: "A", chinese: "昨天上午你去哪儿了？", pinyin: "Zuótiān shàngwǔ nǐ qù nǎr le?", english: "Where did you go yesterday morning?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the dorm", speaker: "B", chinese: "我去商店买东西了。", pinyin: "Wǒ qù shāngdiàn mǎi dōngxi le.", english: "I went to the store to buy things." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the dorm", speaker: "A", chinese: "你买什么了？", pinyin: "Nǐ mǎi shénme le?", english: "What did you buy?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the dorm", speaker: "B", chinese: "我买了一点儿苹果。", pinyin: "Wǒ mǎi le yīdiǎnr píngguǒ.", english: "I bought some apples." },
      { order: 5, dialogNumber: 2, dialogLabel: "In the office", speaker: "A", chinese: "你看见张先生了吗？", pinyin: "Nǐ kànjiàn Zhāng xiānsheng le ma?", english: "Have you seen Mr. Zhang?" },
      { order: 6, dialogNumber: 2, dialogLabel: "In the office", speaker: "B", chinese: "看见了，他去学开车了。", pinyin: "Kànjiàn le, tā qù xué kāi chē le.", english: "Yes. He's gone to learn driving." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the office", speaker: "A", chinese: "他什么时候能回来？", pinyin: "Tā shénme shíhou néng huílái?", english: "When can he come back?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In the office", speaker: "B", chinese: "40分钟后回来。", pinyin: "Sìshí fēnzhōng hòu huílái.", english: "He'll come back after 40 minutes." },
      { order: 9, dialogNumber: 3, dialogLabel: "Outside a store", speaker: "A", chinese: "王方的衣服太漂亮了！", pinyin: "Wáng Fāng de yīfu tài piàoliang le!", english: "Wang Fang's clothes are so beautiful!" },
      { order: 10, dialogNumber: 3, dialogLabel: "Outside a store", speaker: "B", chinese: "是啊，她买了不少衣服。", pinyin: "Shì a, tā mǎi le bùshǎo yīfu.", english: "Yes, she's bought quite a few clothes." },
      { order: 11, dialogNumber: 3, dialogLabel: "Outside a store", speaker: "A", chinese: "你买什么了？", pinyin: "Nǐ mǎi shénme le?", english: "What did you buy?" },
      { order: 12, dialogNumber: 3, dialogLabel: "Outside a store", speaker: "B", chinese: "我没买，这些都是王方的东西。", pinyin: "Wǒ méi mǎi, zhèxiē dōu shì Wáng Fāng de dōngxi.", english: "I bought nothing. All these are Wang Fang's things." },
    ],
  },
  {
    chapterNumber: 15,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "Meeting someone", speaker: "A", chinese: "你和李小姐是什么时候认识的？", pinyin: "Nǐ hé Lǐ xiǎojiě shì shénme shíhou rènshi de?", english: "When did you and Miss Li meet?" },
      { order: 2, dialogNumber: 1, dialogLabel: "Meeting someone", speaker: "B", chinese: "我们是2011年9月认识的。", pinyin: "Wǒmen shì èr líng yī yī nián jiǔ yuè rènshi de.", english: "We met in September 2011." },
      { order: 3, dialogNumber: 1, dialogLabel: "Meeting someone", speaker: "A", chinese: "你们在哪儿认识的？", pinyin: "Nǐmen zài nǎr rènshi de?", english: "Where did you meet?" },
      { order: 4, dialogNumber: 1, dialogLabel: "Meeting someone", speaker: "B", chinese: "我们是在学校认识的，她是我大学同学。", pinyin: "Wǒmen shì zài xuéxiào rènshi de, tā shì wǒ dàxué tóngxué.", english: "We met at school. She was my college classmate." },
      { order: 5, dialogNumber: 2, dialogLabel: "Outside a hotel", speaker: "A", chinese: "你们是怎么来饭店的？", pinyin: "Nǐmen shì zěnme lái fàndiàn de?", english: "How did you come to the restaurant?" },
      { order: 6, dialogNumber: 2, dialogLabel: "Outside a hotel", speaker: "B", chinese: "我们是坐出租车来的。", pinyin: "Wǒmen shì zuò chūzūchē lái de.", english: "We came by taxi." },
      { order: 7, dialogNumber: 2, dialogLabel: "Outside a hotel", speaker: "A", chinese: "李先生呢？", pinyin: "Lǐ xiānsheng ne?", english: "What about Mr. Li?" },
      { order: 8, dialogNumber: 2, dialogLabel: "Outside a hotel", speaker: "B", chinese: "他是和朋友一起开车来的。", pinyin: "Tā shì hé péngyou yìqǐ kāi chē lái de.", english: "He drove here with his friend." },
      { order: 9, dialogNumber: 3, dialogLabel: "In the company", speaker: "A", chinese: "很高兴认识您！李小姐。", pinyin: "Hěn gāoxìng rènshi nín! Lǐ xiǎojiě.", english: "Nice to meet you, Miss Li." },
      { order: 10, dialogNumber: 3, dialogLabel: "In the company", speaker: "B", chinese: "认识你我也很高兴！", pinyin: "Rènshi nǐ wǒ yě hěn gāoxìng!", english: "Nice to meet you too!" },
      { order: 11, dialogNumber: 3, dialogLabel: "In the company", speaker: "A", chinese: "听张先生说，您是坐飞机来北京的？", pinyin: "Tīng Zhāng xiānsheng shuō, nín shì zuò fēijī lái Běijīng de?", english: "Mr. Zhang said you came to Beijing by plane, didn't you?" },
      { order: 12, dialogNumber: 3, dialogLabel: "In the company", speaker: "B", chinese: "是的。", pinyin: "Shì de.", english: "Yes, I did." },
    ],
  },
];
