import type { CombinedVocabRow } from "./vocab-row";
import { HSK1_COMBINED_WORDS } from "./hsk1-combined-data";

// HSK2's combined (full-level) word list, transcribed directly from the
// official HSK Standard Course 2 textbook's own back-of-book appendix — see
// the comment atop hsk1-combined-data.ts for the general rationale and which
// kinds of sections get included/excluded (生词 New Words, 超纲词, and "New
// Words Made Up of Characters Learned Before" included; 专有名词 Proper
// Nouns excluded).
//
// Unlike HSK1's own appendix, book 2's 生词 table only lists words *new* to
// book 2 — it doesn't repeat book 1's vocabulary the way the old
// third-party PDF list did. "Combined" has always meant cumulative on this
// site (everything a student should know by the end of the level), so this
// file is HSK1's full list plus book 2's own new words, not book 2's list
// alone.
//
// Six of book 2's own 生词 words (吧, 给, 好吃, 身体, 问, 也, 一起) are
// exact repeats of words already in HSK1_COMBINED_WORDS — HSK1's book
// glosses them early as 超纲词 "outside the syllabus" bonus vocab, and HSK2
// then formally teaches them. Excluded from HSK2_OWN_WORDS below rather
// than duplicated, since they'd otherwise collide on the same
// chinese+pinyin key seed.ts dedupes on.
//
// Also excluded: the "补充 Supplementary Vocabulary" table (New Word +
// Learned Characters columns only, no pinyin/meaning per entry — nothing
// typable to extract), and the 汉字总表/偏旁总表 Characters/Radicals tables
// (handwriting reference, not vocabulary).
const HSK2_OWN_WORDS: CombinedVocabRow[] = [
  // 生词 New Words
  { chinese: "白", pinyin: "bái", english: "white", category: "Adjective" },
  { chinese: "百", pinyin: "bǎi", english: "hundred", category: "Numeral" },
  { chinese: "帮助", pinyin: "bāngzhù", english: "to help, to assist, to aid", category: "Verb" },
  { chinese: "报纸", pinyin: "bàozhǐ", english: "newspaper", category: "Noun" },
  { chinese: "比", pinyin: "bǐ", english: "than, (superior or inferior) to", category: "Preposition" },
  { chinese: "别", pinyin: "bié", english: "don't", category: "Adverb" },
  { chinese: "宾馆", pinyin: "bīnguǎn", english: "hotel", category: "Noun" },
  { chinese: "长", pinyin: "cháng", english: "long", category: "Adjective" },
  { chinese: "唱歌", pinyin: "chàng gē", english: "to sing", category: "Verb" },
  { chinese: "出", pinyin: "chū", english: "to come/go out", category: "Verb" },
  { chinese: "穿", pinyin: "chuān", english: "to wear, to put on", category: "Verb" },
  { chinese: "次", pinyin: "cì", english: "time", category: "Quantifier" },
  { chinese: "从", pinyin: "cóng", english: "from", category: "Preposition" },
  { chinese: "错", pinyin: "cuò", english: "wrong, incorrect", category: "Adjective" },
  { chinese: "打篮球", pinyin: "dǎ lánqiú", english: "to play basketball", category: null },
  { chinese: "大家", pinyin: "dàjiā", english: "all, everybody", category: "Pronoun" },
  { chinese: "但是", pinyin: "dànshì", english: "but, still, yet", category: "Conjunction" },
  { chinese: "到", pinyin: "dào", english: "to arrive, to reach", category: "Verb" },
  {
    chinese: "得",
    pinyin: "de",
    english: "used after a verb or an adjective to introduce a complement of result or degree",
    category: "Particle",
  },
  { chinese: "等", pinyin: "děng", english: "to wait, to await", category: "Verb" },
  { chinese: "弟弟", pinyin: "dìdi", english: "younger brother", category: "Noun" },
  { chinese: "第一", pinyin: "dì yī", english: "first", category: "Numeral" },
  { chinese: "懂", pinyin: "dǒng", english: "to understand, to know", category: "Verb" },
  { chinese: "对", pinyin: "duì", english: "(used before a noun or pronoun) to, for", category: "Preposition" },
  { chinese: "房间", pinyin: "fángjiān", english: "room", category: "Noun" },
  { chinese: "非常", pinyin: "fēicháng", english: "very, extremely", category: "Adverb" },
  { chinese: "服务员", pinyin: "fúwùyuán", english: "attendant, waiter/waitress", category: "Noun" },
  { chinese: "高", pinyin: "gāo", english: "tall, high", category: "Adjective" },
  { chinese: "告诉", pinyin: "gàosu", english: "to tell", category: "Verb" },
  { chinese: "哥哥", pinyin: "gēge", english: "elder brother", category: "Noun" },
  { chinese: "公共汽车", pinyin: "gōnggòng qìchē", english: "bus", category: null },
  { chinese: "公司", pinyin: "gōngsī", english: "company, firm", category: "Noun" },
  { chinese: "贵", pinyin: "guì", english: "expensive; (honorific term) your", category: "Adjective" },
  { chinese: "还", pinyin: "hái", english: "passably, fairly, rather", category: "Adverb" },
  { chinese: "孩子", pinyin: "háizi", english: "child, kid", category: "Noun" },
  { chinese: "黑", pinyin: "hēi", english: "black", category: "Adjective" },
  { chinese: "红", pinyin: "hóng", english: "red", category: "Adjective" },
  { chinese: "火车站", pinyin: "huǒchēzhàn", english: "railway station", category: "Noun" },
  { chinese: "机场", pinyin: "jīchǎng", english: "airport", category: "Noun" },
  { chinese: "鸡蛋", pinyin: "jīdàn", english: "(hen's) egg", category: "Noun" },
  { chinese: "件", pinyin: "jiàn", english: "(used for clothes among other items) piece", category: "Quantifier" },
  { chinese: "觉得", pinyin: "juéde", english: "to think, to feel", category: "Verb" },
  { chinese: "教室", pinyin: "jiàoshì", english: "classroom", category: "Noun" },
  { chinese: "姐姐", pinyin: "jiějie", english: "elder sister", category: "Noun" },
  { chinese: "介绍", pinyin: "jièshào", english: "to introduce, to recommend", category: "Verb" },
  { chinese: "进", pinyin: "jìn", english: "to enter, to come/go in", category: "Verb" },
  { chinese: "近", pinyin: "jìn", english: "near, close", category: "Adjective" },
  { chinese: "就", pinyin: "jiù", english: "used to indicate a conclusion or resolution", category: "Adverb" },
  { chinese: "咖啡", pinyin: "kāfēi", english: "coffee", category: "Noun" },
  { chinese: "开始", pinyin: "kāishǐ", english: "to begin, to start", category: "Verb" },
  { chinese: "考试", pinyin: "kǎoshì", english: "test, exam", category: "Noun" },
  { chinese: "可能", pinyin: "kěnéng", english: "maybe, perhaps, probably", category: "Modal Verb" },
  { chinese: "可以", pinyin: "kěyǐ", english: "not bad", category: "Adjective" },
  { chinese: "课", pinyin: "kè", english: "class, lesson", category: "Noun" },
  { chinese: "快", pinyin: "kuài", english: "quick, fast", category: "Adjective" },
  { chinese: "快乐", pinyin: "kuàilè", english: "happy, glad", category: "Adjective" },
  { chinese: "离", pinyin: "lí", english: "to be away from", category: "Verb" },
  { chinese: "两", pinyin: "liǎng", english: "two", category: "Numeral" },
  { chinese: "零", pinyin: "líng", english: "zero", category: "Numeral" },
  { chinese: "路", pinyin: "lù", english: "road, path, way", category: "Noun" },
  { chinese: "旅游", pinyin: "lǚyóu", english: "to travel, to take a trip", category: "Verb" },
  { chinese: "慢", pinyin: "màn", english: "slow", category: "Adjective" },
  { chinese: "忙", pinyin: "máng", english: "busy", category: "Adjective" },
  { chinese: "每", pinyin: "měi", english: "every, each", category: "Pronoun" },
  { chinese: "妹妹", pinyin: "mèimei", english: "younger sister", category: "Noun" },
  { chinese: "门", pinyin: "mén", english: "door, gate", category: "Noun" },
  { chinese: "面条", pinyin: "miàntiáo", english: "noodles", category: "Noun" },
  { chinese: "男", pinyin: "nán", english: "man, male", category: "Adjective" },
  { chinese: "牛奶", pinyin: "niúnǎi", english: "milk", category: "Noun" },
  { chinese: "女", pinyin: "nǚ", english: "woman, female", category: "Adjective" },
  { chinese: "旁边", pinyin: "pángbiān", english: "beside", category: "Noun" },
  { chinese: "跑步", pinyin: "pǎobù", english: "to run, to jog", category: "Verb" },
  { chinese: "便宜", pinyin: "piányi", english: "cheap, inexpensive", category: "Adjective" },
  { chinese: "票", pinyin: "piào", english: "ticket", category: "Noun" },
  { chinese: "妻子", pinyin: "qīzi", english: "wife", category: "Noun" },
  { chinese: "起床", pinyin: "qǐchuáng", english: "to get up, to get out of bed", category: "Verb" },
  { chinese: "千", pinyin: "qiān", english: "thousand", category: "Numeral" },
  { chinese: "铅笔", pinyin: "qiānbǐ", english: "pencil", category: "Noun" },
  { chinese: "晴", pinyin: "qíng", english: "sunny, fine, clear", category: "Adjective" },
  { chinese: "去年", pinyin: "qùnián", english: "last year", category: "Noun" },
  { chinese: "让", pinyin: "ràng", english: "to let, to allow", category: "Verb" },
  { chinese: "日", pinyin: "rì", english: "day, date", category: "Noun" },
  { chinese: "上班", pinyin: "shàngbān", english: "to work, to do a job", category: "Verb" },
  { chinese: "生病", pinyin: "shēngbìng", english: "to fall ill, to be sick", category: "Verb" },
  { chinese: "生日", pinyin: "shēngrì", english: "birthday", category: "Noun" },
  { chinese: "时间", pinyin: "shíjiān", english: "time", category: "Noun" },
  { chinese: "事情", pinyin: "shìqíng", english: "thing, matter, affair", category: "Noun" },
  { chinese: "手表", pinyin: "shǒubiǎo", english: "watch", category: "Noun" },
  { chinese: "手机", pinyin: "shǒujī", english: "cell phone", category: "Noun" },
  { chinese: "说话", pinyin: "shuōhuà", english: "to speak, to say, to talk", category: "Verb" },
  { chinese: "送", pinyin: "sòng", english: "to send, to deliver", category: "Verb" },
  { chinese: "虽然", pinyin: "suīrán", english: "although, though", category: "Conjunction" },
  { chinese: "所以", pinyin: "suǒyǐ", english: "so, therefore", category: "Conjunction" },
  { chinese: "它", pinyin: "tā", english: "it", category: "Pronoun" },
  { chinese: "踢足球", pinyin: "tī zúqiú", english: "to play football", category: null },
  { chinese: "题", pinyin: "tí", english: "question, problem", category: "Noun" },
  { chinese: "跳舞", pinyin: "tiàowǔ", english: "to dance", category: "Verb" },
  { chinese: "外", pinyin: "wài", english: "outer, outside", category: "Noun" },
  { chinese: "完", pinyin: "wán", english: "to finish, to end", category: "Verb" },
  { chinese: "玩儿", pinyin: "wánr", english: "to play, to have fun", category: "Verb" },
  { chinese: "晚上", pinyin: "wǎnshang", english: "evening, night", category: "Noun" },
  { chinese: "往", pinyin: "wǎng", english: "to, towards", category: "Preposition" },
  { chinese: "为什么", pinyin: "wèi shénme", english: "why", category: null },
  { chinese: "问题", pinyin: "wèntí", english: "question, problem", category: "Noun" },
  { chinese: "西瓜", pinyin: "xīguā", english: "watermelon", category: "Noun" },
  { chinese: "希望", pinyin: "xīwàng", english: "to hope, to wish", category: "Verb" },
  { chinese: "洗", pinyin: "xǐ", english: "to wash, to bathe", category: "Verb" },
  { chinese: "小时", pinyin: "xiǎoshí", english: "hour", category: "Noun" },
  { chinese: "笑", pinyin: "xiào", english: "to smile, to laugh", category: "Verb" },
  { chinese: "新", pinyin: "xīn", english: "new", category: "Adjective" },
  { chinese: "姓", pinyin: "xìng", english: "family name, surname", category: "Verb" },
  { chinese: "休息", pinyin: "xiūxi", english: "to have or take a rest", category: "Verb" },
  { chinese: "雪", pinyin: "xuě", english: "snow", category: "Noun" },
  { chinese: "颜色", pinyin: "yánsè", english: "color", category: "Noun" },
  { chinese: "眼睛", pinyin: "yǎnjing", english: "eye", category: "Noun" },
  { chinese: "羊肉", pinyin: "yángròu", english: "mutton", category: "Noun" },
  { chinese: "药", pinyin: "yào", english: "medicine, drug", category: "Noun" },
  { chinese: "要", pinyin: "yào", english: "to want to, would like to", category: "Modal Verb" },
  { chinese: "一下", pinyin: "yīxià", english: "used after a verb, indicating an act or an attempt", category: "Quantifier" },
  { chinese: "已经", pinyin: "yǐjīng", english: "already", category: "Adverb" },
  { chinese: "意思", pinyin: "yìsi", english: "meaning", category: "Noun" },
  { chinese: "因为", pinyin: "yīnwèi", english: "because, since", category: "Conjunction" },
  { chinese: "阴", pinyin: "yīn", english: "overcast, cloudy", category: "Adjective" },
  { chinese: "游泳", pinyin: "yóuyǒng", english: "to swim", category: "Verb" },
  { chinese: "右边", pinyin: "yòubiān", english: "right, right side", category: "Noun" },
  { chinese: "鱼", pinyin: "yú", english: "fish", category: "Noun" },
  { chinese: "远", pinyin: "yuǎn", english: "far, distant", category: "Adjective" },
  {
    chinese: "运动",
    pinyin: "yùndòng",
    english: "sport; to take physical exercise, to work out",
    category: "Noun",
  },
  { chinese: "再", pinyin: "zài", english: "again, once more", category: "Adverb" },
  { chinese: "早上", pinyin: "zǎoshang", english: "morning", category: "Noun" },
  { chinese: "丈夫", pinyin: "zhàngfu", english: "husband", category: "Noun" },
  { chinese: "找", pinyin: "zhǎo", english: "to look for", category: "Verb" },
  { chinese: "着", pinyin: "zhe", english: "used to indicate a state", category: "Particle" },
  { chinese: "真", pinyin: "zhēn", english: "really, indeed", category: "Adverb" },
  { chinese: "正在", pinyin: "zhèngzài", english: "in the process of", category: "Adverb" },
  { chinese: "知道", pinyin: "zhīdào", english: "to know", category: "Verb" },
  { chinese: "准备", pinyin: "zhǔnbèi", english: "to intend, to plan", category: "Verb" },
  { chinese: "走", pinyin: "zǒu", english: "to walk", category: "Verb" },
  { chinese: "最", pinyin: "zuì", english: "most, to the greatest extent", category: "Adverb" },
  { chinese: "左边", pinyin: "zuǒbiān", english: "left side", category: "Noun" },

  // 超纲词 Words Not Included in the Syllabus
  { chinese: "班", pinyin: "bān", english: "class, grade, team", category: "Noun" },
  { chinese: "度", pinyin: "dù", english: "degree", category: "Noun" },
  { chinese: "粉色", pinyin: "fěnsè", english: "pink", category: "Noun" },
  { chinese: "更", pinyin: "gèng", english: "more, to a greater extent", category: "Adverb" },
  { chinese: "公斤", pinyin: "gōngjīn", english: "kilogram", category: "Quantifier" },
  { chinese: "过", pinyin: "guò", english: "to pass (time), to spend (time)", category: "Verb" },
  { chinese: "欢迎", pinyin: "huānyíng", english: "to welcome", category: "Verb" },

  // 旧字新词 New Words Made Up of Characters Learned Before (来自本册 From This Book)
  { chinese: "帮", pinyin: "bāng", english: "to help, to assist", category: "Verb" },
  { chinese: "不错", pinyin: "búcuò", english: "pretty good", category: "Adjective" },
  {
    chinese: "出院",
    pinyin: "chū yuàn",
    english: "to leave hospital, to be discharged from hospital",
    category: null,
  },
  { chinese: "粉", pinyin: "fěn", english: "pink", category: "Adjective" },
  { chinese: "红色", pinyin: "hóngsè", english: "red", category: "Noun" },
  { chinese: "路口", pinyin: "lùkǒu", english: "crossing, crossroads", category: "Noun" },
  { chinese: "手", pinyin: "shǒu", english: "hand", category: "Noun" },
  { chinese: "外面", pinyin: "wàimiàn", english: "outside", category: "Noun" },
  { chinese: "新年", pinyin: "xīnnián", english: "New Year", category: "Noun" },
  { chinese: "以后", pinyin: "yǐhòu", english: "after, afterwards, later", category: "Noun" },
  { chinese: "有意思", pinyin: "yǒu yìsi", english: "interesting, fun", category: null },
];

export const HSK2_COMBINED_WORDS: CombinedVocabRow[] = [
  ...HSK1_COMBINED_WORDS,
  ...HSK2_OWN_WORDS,
];
