import type { ChapterWordRow } from "./extract-chapters";

// HSK2 chapters' full dialog vocabulary — docs/hold/25-chapter-all-words-plan.md.
// Auto-extracted (scripts-tmp-extract-dialogs.ts) from pasted textbook dialog
// text via longest-match segmentation against this app's own existing
// vocabulary (hsk{1,2,3}-{chapters,combined}-data.ts) — see
// scripts-tmp-unmatched.txt at generation time for anything that couldn't be
// matched automatically.

export interface Hsk2ChapterDialogData {
  chapterNumber: number;
  words: ChapterWordRow[];
}

export const HSK2_CHAPTER_DIALOGS: Hsk2ChapterDialogData[] = [
  {
    chapterNumber: 1,
    words: [
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "要", pinyin: "yào", wordType: "aux.", meaning: "to want to, would like to" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "北京", pinyin: "Běijīng", wordType: "prop. n.", meaning: "Beijing" },
      { chinese: "旅游", pinyin: "lǚyóu", wordType: "v.", meaning: "to travel, to take a trip" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "觉得", pinyin: "juéde", wordType: "v.", meaning: "to think, to feel" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "时候", pinyin: "shíhou", wordType: null, meaning: "time, moment" },
      { chinese: "最", pinyin: "zuì", wordType: "adv.", meaning: "most, to the greatest extent" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "九", pinyin: "jiǔ", wordType: null, meaning: "nine" },
      { chinese: "月", pinyin: "yuè", wordType: null, meaning: "month" },
      { chinese: "为什么", pinyin: "wèi shénme", wordType: "phrase", meaning: "why" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "天气", pinyin: "tiānqì", wordType: null, meaning: "weather" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "冷", pinyin: "lěng", wordType: null, meaning: "cold" },
      { chinese: "也", pinyin: "yě", wordType: "adv.", meaning: "also, too" },
      { chinese: "热", pinyin: "rè", wordType: null, meaning: "hot" },
      { chinese: "喜欢", pinyin: "xǐhuan", wordType: null, meaning: "to like, to be fond of" },
      { chinese: "运动", pinyin: "yùndòng", wordType: "n./v.", meaning: "sport; to exercise" },
      { chinese: "踢足球", pinyin: "tī zúqiú", wordType: "v.", meaning: "to play football" },
      { chinese: "下午", pinyin: "xiàwǔ", wordType: null, meaning: "afternoon" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "一起", pinyin: "yìqǐ", wordType: "adv.", meaning: "together" },
      { chinese: "吧", pinyin: "ba", wordType: null, meaning: "a modal particle used at the end of a sentence to indicate consultation, a suggestion, request or command" },
      { chinese: "啊", pinyin: "a", wordType: null, meaning: "a modal particle used at the end of a sentence as a sign of confirmation or defense" },
      { chinese: "买", pinyin: "mǎi", wordType: null, meaning: "to buy, to purchase" },
      { chinese: "几", pinyin: "jǐ", wordType: null, meaning: "how many" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "新", pinyin: "xīn", wordType: "adj.", meaning: "new" },
      { chinese: "椅子", pinyin: "yǐzi", wordType: null, meaning: "chair" },
      { chinese: "明天", pinyin: "míngtiān", wordType: null, meaning: "tomorrow" },
      { chinese: "怎么样", pinyin: "zěnmeyàng", wordType: null, meaning: "(indicating nature, condition or manner) how" },
      { chinese: "点", pinyin: "diǎn", wordType: null, meaning: "o'clock" },
      { chinese: "能", pinyin: "néng", wordType: null, meaning: "can, may" },
      { chinese: "回来", pinyin: "huílai", wordType: null, meaning: "to come back" },
      { chinese: "三", pinyin: "sān", wordType: null, meaning: "three" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
      { chinese: "桌子", pinyin: "zhuōzi", wordType: null, meaning: "desk, table" },
      { chinese: "下面", pinyin: "xiàmiàn", wordType: null, meaning: "under, below" },
      { chinese: "有", pinyin: "yǒu", wordType: null, meaning: "to have, there be" },
      { chinese: "猫", pinyin: "māo", wordType: null, meaning: "cat" },
      { chinese: "那", pinyin: "nà", wordType: null, meaning: "that" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "它", pinyin: "tā", wordType: "pron.", meaning: "it" },
      { chinese: "叫", pinyin: "jiào", wordType: null, meaning: "to call, to be called" },
      { chinese: "花花", pinyin: "Huāhua", wordType: "prop. n.", meaning: "name of a cat" },
      { chinese: "很", pinyin: "hěn", wordType: null, meaning: "very, quite" },
      { chinese: "漂亮", pinyin: "piàoliang", wordType: null, meaning: "beautiful, pretty" },
      { chinese: "眼睛", pinyin: "yǎnjīng", wordType: "n.", meaning: "eye" },
      { chinese: "大", pinyin: "dà", wordType: null, meaning: "(of age) old" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "六", pinyin: "liù", wordType: null, meaning: "six" },
    ],
  },
  {
    chapterNumber: 2,
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "很", pinyin: "hěn", wordType: null, meaning: "very, quite" },
      { chinese: "少", pinyin: "shǎo", wordType: null, meaning: "little, few" },
      { chinese: "生病", pinyin: "shēng bìng", wordType: "v.", meaning: "to fall ill, to be sick" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "喜欢", pinyin: "xǐhuan", wordType: null, meaning: "to like, to be fond of" },
      { chinese: "运动", pinyin: "yùndòng", wordType: null, meaning: "sport; to take physical exercise, to work out" },
      { chinese: "啊", pinyin: "a", wordType: null, meaning: "a modal particle used at the end of a sentence as a sign of confirmation or defense" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "每天", pinyin: "měi tiān", wordType: null, meaning: "every day" },
      { chinese: "早上", pinyin: "zǎoshang", wordType: "n.", meaning: "morning" },
      { chinese: "都", pinyin: "dōu", wordType: null, meaning: "both, all" },
      { chinese: "要", pinyin: "yào", wordType: null, meaning: "to want to, would like to" },
      { chinese: "出", pinyin: "chū", wordType: "v.", meaning: "to come/go out" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "跑步", pinyin: "pǎobù", wordType: "v.", meaning: "to run, to jog" },
      { chinese: "几", pinyin: "jǐ", wordType: null, meaning: "how many" },
      { chinese: "点", pinyin: "diǎn", wordType: null, meaning: "o'clock" },
      { chinese: "起床", pinyin: "qǐ chuáng", wordType: "v.", meaning: "to get up" },
      { chinese: "六", pinyin: "liù", wordType: null, meaning: "six" },
      { chinese: "吃", pinyin: "chī", wordType: null, meaning: "to eat" },
      { chinese: "药", pinyin: "yào", wordType: "n.", meaning: "medicine, drug" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "现在", pinyin: "xiànzài", wordType: null, meaning: "now" },
      { chinese: "身体", pinyin: "shēntǐ", wordType: "n.", meaning: "body" },
      { chinese: "怎么样", pinyin: "zěnmeyàng", wordType: null, meaning: "(indicating nature, condition or manner) how" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "时候", pinyin: "shíhou", wordType: null, meaning: "time, moment" },
      { chinese: "能", pinyin: "néng", wordType: null, meaning: "can, may" },
      { chinese: "出院", pinyin: "chū yuàn", wordType: "v.", meaning: "to leave hospital" },
      { chinese: "医生", pinyin: "yīshēng", wordType: null, meaning: "doctor" },
      { chinese: "说", pinyin: "shuō", wordType: null, meaning: "to speak, to say" },
      { chinese: "下", pinyin: "xià", wordType: null, meaning: "under, below; (of rain, snow, etc.) to fall" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "星期", pinyin: "xīngqī", wordType: null, meaning: "week" },
      { chinese: "大卫", pinyin: "Dàwèi", wordType: "prop. n.", meaning: "David" },
      { chinese: "今年", pinyin: "jīnnián", wordType: null, meaning: "this year" },
      { chinese: "大", pinyin: "dà", wordType: null, meaning: "(of age) old" },
      { chinese: "二", pinyin: "èr", wordType: null, meaning: "two" },
      { chinese: "十", pinyin: "shí", wordType: null, meaning: "ten" },
      { chinese: "岁", pinyin: "suì", wordType: null, meaning: "year (of age)" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "高", pinyin: "gāo", wordType: "adj.", meaning: "tall, high" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "米", pinyin: "mǐ", wordType: "m.", meaning: "meter" },
      { chinese: "八", pinyin: "bā", wordType: null, meaning: "eight" },
      { chinese: "怎么", pinyin: "zěnme", wordType: null, meaning: "(indicating nature, condition or manner, etc.) how" },
      { chinese: "知道", pinyin: "zhīdào", wordType: "v.", meaning: "to know" },
      { chinese: "这么", pinyin: "zhème", wordType: "pron.", meaning: "so, such, like this" },
      { chinese: "同学", pinyin: "tóngxué", wordType: null, meaning: "classmate" },
      { chinese: "张", pinyin: "zhāng", wordType: null, meaning: "used for flat objects such as paper, photos, etc." },
      { chinese: "老师", pinyin: "lǎoshī", wordType: null, meaning: "teacher" },
      { chinese: "也", pinyin: "yě", wordType: null, meaning: "also, too" },
      { chinese: "休息", pinyin: "xiūxi", wordType: "v.", meaning: "to have a rest" },
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "天", pinyin: "tiān", wordType: "n.", meaning: "day; sky" },
      { chinese: "忙", pinyin: "máng", wordType: "adj.", meaning: "busy" },
      { chinese: "没有", pinyin: "méiyǒu", wordType: null, meaning: "there is not" },
      { chinese: "时间", pinyin: "shíjiān", wordType: "n.", meaning: "time" },
      { chinese: "那", pinyin: "nà", wordType: null, meaning: "that" },
      { chinese: "会", pinyin: "huì", wordType: null, meaning: "can, to be able to" },
      { chinese: "累", pinyin: "lèi", wordType: "adj.", meaning: "tired" },
      { chinese: "吧", pinyin: "ba", wordType: null, meaning: "a modal particle used at the end of a sentence to indicate consultation, a suggestion, request or command" },
      { chinese: "回来", pinyin: "huílai", wordType: null, meaning: "to come back" },
    ],
  },
  {
    chapterNumber: 3,
    words: [
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "块", pinyin: "kuài", wordType: null, meaning: "a unit of money, same as \"yuan\"" },
      { chinese: "手表", pinyin: "shǒubiǎo", wordType: "n.", meaning: "watch" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "爸爸", pinyin: "bàba", wordType: null, meaning: "father" },
      { chinese: "多少", pinyin: "duōshao", wordType: null, meaning: "how many, how much" },
      { chinese: "钱", pinyin: "qián", wordType: null, meaning: "money" },
      { chinese: "买", pinyin: "mǎi", wordType: null, meaning: "to buy, to purchase" },
      { chinese: "三", pinyin: "sān", wordType: null, meaning: "three" },
      { chinese: "千", pinyin: "qiān", wordType: "num.", meaning: "thousand" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
      { chinese: "今天", pinyin: "jīntiān", wordType: null, meaning: "today" },
      { chinese: "早上", pinyin: "zǎoshang", wordType: null, meaning: "morning" },
      { chinese: "报纸", pinyin: "bàozhǐ", wordType: "n.", meaning: "newspaper" },
      { chinese: "昨天", pinyin: "zuótiān", wordType: null, meaning: "yesterday" },
      { chinese: "听", pinyin: "tīng", wordType: null, meaning: "to listen" },
      { chinese: "送", pinyin: "sòng", wordType: "v.", meaning: "to send, to deliver" },
      { chinese: "来", pinyin: "lái", wordType: null, meaning: "to come" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "看", pinyin: "kàn", wordType: null, meaning: "to look at, to watch, to read" },
      { chinese: "一下", pinyin: "yíxià", wordType: "num.-m.", meaning: "(after verb) an attempt" },
      { chinese: "牛奶", pinyin: "niúnǎi", wordType: "n.", meaning: "milk" },
      { chinese: "谁", pinyin: "shéi", wordType: null, meaning: "who, whom" },
      { chinese: "房间", pinyin: "fángjiān", wordType: "n.", meaning: "room" },
      { chinese: "和", pinyin: "hé", wordType: null, meaning: "and" },
      { chinese: "丈夫", pinyin: "zhàngfu", wordType: "n.", meaning: "husband" },
      { chinese: "旁边", pinyin: "pángbiān", wordType: "n.", meaning: "beside" },
      { chinese: "那", pinyin: "nà", wordType: null, meaning: "that" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "小", pinyin: "xiǎo", wordType: null, meaning: "small, little" },
      { chinese: "女儿", pinyin: "nǚ'ér", wordType: null, meaning: "daughter" },
      { chinese: "真", pinyin: "zhēn", wordType: "adv.", meaning: "really, indeed" },
      { chinese: "漂亮", pinyin: "piàoliang", wordType: null, meaning: "beautiful, pretty" },
      { chinese: "都", pinyin: "dōu", wordType: null, meaning: "both, all" },
      { chinese: "粉色", pinyin: "fěnsè", wordType: "n.", meaning: "pink" },
      { chinese: "啊", pinyin: "a", wordType: null, meaning: "a modal particle used at the end of a sentence as a sign of confirmation or defense" },
      { chinese: "最", pinyin: "zuì", wordType: null, meaning: "most, to the greatest extent" },
      { chinese: "喜欢", pinyin: "xǐhuan", wordType: null, meaning: "to like, to be fond of" },
      { chinese: "颜色", pinyin: "yánsè", wordType: "n.", meaning: "color" },
      { chinese: "看见", pinyin: "kànjiàn", wordType: null, meaning: "to see" },
      { chinese: "杯子", pinyin: "bēizi", wordType: null, meaning: "cup, glass" },
      { chinese: "里", pinyin: "lǐ", wordType: null, meaning: "inner, inside, interior" },
      { chinese: "有", pinyin: "yǒu", wordType: null, meaning: "to have, there be" },
      { chinese: "几", pinyin: "jǐ", wordType: null, meaning: "how many" },
      { chinese: "哪", pinyin: "nǎ", wordType: null, meaning: "which" },
      { chinese: "左边", pinyin: "zuǒbiān", wordType: "n.", meaning: "left side" },
      { chinese: "红色", pinyin: "hóngsè", wordType: "n.", meaning: "red" },
      { chinese: "给", pinyin: "gěi", wordType: null, meaning: "to" },
    ],
  },
  {
    chapterNumber: 4,
    words: [
      { chinese: "生日", pinyin: "shēngrì", wordType: "n.", meaning: "birthday" },
      { chinese: "快乐", pinyin: "kuàilè", wordType: "adj.", meaning: "happy, glad" },
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "送", pinyin: "sòng", wordType: null, meaning: "to send, to deliver" },
      { chinese: "给", pinyin: "gěi", wordType: "prep.", meaning: "(after verb) to, for" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "本", pinyin: "běn", wordType: null, meaning: "a measure word for books" },
      { chinese: "书", pinyin: "shū", wordType: null, meaning: "book" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "对", pinyin: "duì", wordType: null, meaning: "(used before a noun or pronoun) to, for" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "写", pinyin: "xiě", wordType: null, meaning: "to write" },
      { chinese: "太", pinyin: "tài", wordType: null, meaning: "too, excessively" },
      { chinese: "谢谢", pinyin: "xièxie", wordType: null, meaning: "to thank" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "早上", pinyin: "zǎoshang", wordType: null, meaning: "morning" },
      { chinese: "有", pinyin: "yǒu", wordType: null, meaning: "to have, there be" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "电话", pinyin: "diànhuà", wordType: "n.", meaning: "telephone, phone call" },
      { chinese: "谁", pinyin: "shéi", wordType: null, meaning: "who, whom" },
      { chinese: "打", pinyin: "dǎ", wordType: null, meaning: "to send, to remit" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "知道", pinyin: "zhīdào", wordType: null, meaning: "to know" },
      { chinese: "儿子", pinyin: "érzi", wordType: null, meaning: "son" },
      { chinese: "接", pinyin: "jiē", wordType: "v.", meaning: "to receive, to accept" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "晚上", pinyin: "wǎnshang", wordType: "n.", meaning: "evening, night" },
      { chinese: "问", pinyin: "wèn", wordType: "v.", meaning: "to ask" },
      { chinese: "一下", pinyin: "yīxià", wordType: null, meaning: "used after a verb, indicating an act or an attempt" },
      { chinese: "喜欢", pinyin: "xǐhuan", wordType: null, meaning: "to like, to be fond of" },
      { chinese: "踢足球", pinyin: "tī zúqiú", wordType: null, meaning: "to play football" },
      { chinese: "非常", pinyin: "fēicháng", wordType: "adv.", meaning: "very, extremely" },
      { chinese: "时候", pinyin: "shíhou", wordType: null, meaning: "time, moment" },
      { chinese: "开始", pinyin: "kāishǐ", wordType: "v.", meaning: "to begin, to start" },
      { chinese: "十", pinyin: "shí", wordType: null, meaning: "ten" },
      { chinese: "岁", pinyin: "suì", wordType: null, meaning: "year (of age)" },
      { chinese: "已经", pinyin: "yǐjīng", wordType: "adv.", meaning: "already" },
      { chinese: "踢", pinyin: "tī", wordType: "v.", meaning: "to kick" },
      { chinese: "年", pinyin: "nián", wordType: null, meaning: "year" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "这儿", pinyin: "zhèr", wordType: null, meaning: "here" },
      { chinese: "工作", pinyin: "gōngzuò", wordType: null, meaning: "to work; job" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
      { chinese: "长", pinyin: "cháng", wordType: "adj.", meaning: "long" },
      { chinese: "时间", pinyin: "shíjiān", wordType: null, meaning: "time" },
      { chinese: "两", pinyin: "liǎng", wordType: "num.", meaning: "two" },
      { chinese: "来", pinyin: "lái", wordType: null, meaning: "to come" },
      { chinese: "认识", pinyin: "rènshi", wordType: null, meaning: "to meet, to know" },
      { chinese: "谢", pinyin: "xiè", wordType: "v.", meaning: "to thank (bound/surname form)" },
      { chinese: "先生", pinyin: "xiānsheng", wordType: null, meaning: "Mr., sir" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "大学", pinyin: "dàxué", wordType: null, meaning: "college, university" },
      { chinese: "同学", pinyin: "tóngxué", wordType: null, meaning: "classmate" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "帮", pinyin: "bāng", wordType: "v.", meaning: "to help, to assist" },
      { chinese: "介绍", pinyin: "jièshào", wordType: "v.", meaning: "to introduce, to recommend" },
    ],
  },
  {
    chapterNumber: 5,
    words: [
      { chinese: "晚上", pinyin: "wǎnshang", wordType: null, meaning: "evening, night" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "饭馆", pinyin: "fànguǎn", wordType: "n.", meaning: "restaurant" },
      { chinese: "吃饭", pinyin: "chī fàn", wordType: null, meaning: "to eat a meal" },
      { chinese: "怎么样", pinyin: "zěnmeyàng", wordType: null, meaning: "(indicating nature, condition or manner) how" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "想", pinyin: "xiǎng", wordType: null, meaning: "to want, would like" },
      { chinese: "外面", pinyin: "wàimiàn", wordType: "n.", meaning: "outside" },
      { chinese: "吃", pinyin: "chī", wordType: null, meaning: "to eat" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "家", pinyin: "jiā", wordType: null, meaning: "family" },
      { chinese: "那", pinyin: "nà", wordType: null, meaning: "that" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "准备", pinyin: "zhǔnbèi", wordType: "v.", meaning: "to intend, to plan" },
      { chinese: "做", pinyin: "zuò", wordType: null, meaning: "to make, to produce" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "就", pinyin: "jiù", wordType: "adv.", meaning: "(indicates conclusion)" },
      { chinese: "爱", pinyin: "ài", wordType: null, meaning: "to like, to love" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "鱼", pinyin: "yú", wordType: "n.", meaning: "fish" },
      { chinese: "吧", pinyin: "ba", wordType: "part.", meaning: "(suggestion/request)" },
      { chinese: "帮", pinyin: "bāng", wordType: null, meaning: "to help, to assist" },
      { chinese: "看", pinyin: "kàn", wordType: null, meaning: "to look at, to watch, to read" },
      { chinese: "一下", pinyin: "yīxià", wordType: null, meaning: "used after a verb, indicating an act or an attempt" },
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "件", pinyin: "jiàn", wordType: "m.", meaning: "(for clothes) piece" },
      { chinese: "衣服", pinyin: "yīfu", wordType: null, meaning: "clothes" },
      { chinese: "颜色", pinyin: "yánsè", wordType: null, meaning: "color" },
      { chinese: "还", pinyin: "hái", wordType: "adv.", meaning: "passably, fairly" },
      { chinese: "可以", pinyin: "kěyǐ", wordType: "adj.", meaning: "not bad" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "有点儿", pinyin: "yǒudiǎnr", wordType: null, meaning: "a little, a bit" },
      { chinese: "大", pinyin: "dà", wordType: null, meaning: "(of age) old" },
      { chinese: "小", pinyin: "xiǎo", wordType: null, meaning: "small, little" },
      { chinese: "不错", pinyin: "búcuò", wordType: "adj.", meaning: "pretty good" },
      { chinese: "买", pinyin: "mǎi", wordType: null, meaning: "to buy, to purchase" },
      { chinese: "今天", pinyin: "jīntiān", wordType: null, meaning: "today" },
      { chinese: "打球", pinyin: "dǎqiú", wordType: "v.", meaning: "to play ball (game)" },
      { chinese: "两", pinyin: "liǎng", wordType: null, meaning: "two" },
      { chinese: "天", pinyin: "tiān", wordType: "n.", meaning: "day; sky" },
      { chinese: "累", pinyin: "lèi", wordType: "adj.", meaning: "tired" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "昨天", pinyin: "zuótiān", wordType: null, meaning: "yesterday" },
      { chinese: "考试", pinyin: "kǎoshì", wordType: "n.", meaning: "test, exam" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "啊", pinyin: "a", wordType: null, meaning: "a modal particle used at the end of a sentence as a sign of confirmation or defense" },
      { chinese: "觉得", pinyin: "juéde", wordType: null, meaning: "to think, to feel" },
      { chinese: "听", pinyin: "tīng", wordType: null, meaning: "to listen" },
      { chinese: "和", pinyin: "hé", wordType: null, meaning: "and" },
      { chinese: "说", pinyin: "shuō", wordType: null, meaning: "to speak, to say" },
      { chinese: "读", pinyin: "dú", wordType: null, meaning: "to read" },
      { chinese: "写", pinyin: "xiě", wordType: null, meaning: "to write" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "很", pinyin: "hěn", wordType: null, meaning: "very, quite" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
      { chinese: "字", pinyin: "zì", wordType: null, meaning: "character, word" },
      { chinese: "都", pinyin: "dōu", wordType: null, meaning: "both, all" },
      { chinese: "知道", pinyin: "zhīdào", wordType: null, meaning: "to know" },
      { chinese: "意思", pinyin: "yìsi", wordType: "n.", meaning: "meaning" },
      { chinese: "休息", pinyin: "xiūxi", wordType: null, meaning: "to have or take a rest" },
      { chinese: "喝", pinyin: "hē", wordType: null, meaning: "to drink" },
      { chinese: "咖啡", pinyin: "kāfēi", wordType: "n.", meaning: "coffee" },
      { chinese: "已经", pinyin: "yǐjīng", wordType: null, meaning: "already" },
      { chinese: "杯", pinyin: "bēi", wordType: "m.", meaning: "cup, glass (measure word)" },
      { chinese: "对", pinyin: "duì", wordType: "prep.", meaning: "to, for" },
      { chinese: "身体", pinyin: "shēntǐ", wordType: null, meaning: "body" },
      { chinese: "以后", pinyin: "yǐhòu", wordType: "n.", meaning: "after, afterwards" },
      { chinese: "少", pinyin: "shǎo", wordType: null, meaning: "little, few" },
      { chinese: "一点儿", pinyin: "yīdiǎnr", wordType: null, meaning: "a few, a little" },
      { chinese: "每天", pinyin: "měi tiān", wordType: null, meaning: "every day" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
    ],
  },
  {
    chapterNumber: 6,
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "知道", pinyin: "zhīdào", wordType: null, meaning: "to know" },
      { chinese: "小", pinyin: "xiǎo", wordType: null, meaning: "small, little" },
      { chinese: "王", pinyin: "Wáng", wordType: "prop. n.", meaning: "(surname) Wang" },
      { chinese: "今天", pinyin: "jīntiān", wordType: null, meaning: "today" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "时候", pinyin: "shíhou", wordType: null, meaning: "time, moment" },
      { chinese: "来", pinyin: "lái", wordType: null, meaning: "to come" },
      { chinese: "学校", pinyin: "xuéxiào", wordType: null, meaning: "school" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "已经", pinyin: "yǐjīng", wordType: null, meaning: "already" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "怎么", pinyin: "zěnme", wordType: null, meaning: "(indicating nature, condition or manner, etc.) how" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "门", pinyin: "mén", wordType: "n.", meaning: "door, gate" },
      { chinese: "外", pinyin: "wài", wordType: "n.", meaning: "outer, outside" },
      { chinese: "看见", pinyin: "kànjiàn", wordType: null, meaning: "to see" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "自行车", pinyin: "zìxíngchē", wordType: "n.", meaning: "bike" },
      { chinese: "羊肉", pinyin: "yángròu", wordType: "n.", meaning: "mutton" },
      { chinese: "很", pinyin: "hěn", wordType: null, meaning: "very, quite" },
      { chinese: "好吃", pinyin: "hǎochī", wordType: "adj.", meaning: "delicious, yummy" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "吃", pinyin: "chī", wordType: null, meaning: "to eat" },
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "星期", pinyin: "xīngqī", wordType: null, meaning: "week" },
      { chinese: "天", pinyin: "tiān", wordType: "n.", meaning: "day; sky" },
      { chinese: "都", pinyin: "dōu", wordType: null, meaning: "both, all" },
      { chinese: "想", pinyin: "xiǎng", wordType: null, meaning: "to want, would like" },
      { chinese: "那", pinyin: "nà", wordType: null, meaning: "that" },
      { chinese: "还", pinyin: "hái", wordType: null, meaning: "passably, fairly, rather" },
      { chinese: "一点儿", pinyin: "yīdiǎnr", wordType: null, meaning: "a few, a little" },
      { chinese: "面条", pinyin: "miàntiáo", wordType: "n.", meaning: "noodles" },
      { chinese: "吧", pinyin: "ba", wordType: null, meaning: "a modal particle used at the end of a sentence to indicate consultation, a suggestion, request or command" },
      { chinese: "昨天", pinyin: "zuótiān", wordType: null, meaning: "yesterday" },
      { chinese: "你们", pinyin: "nǐmen", wordType: null, meaning: "(plural) you" },
      { chinese: "没", pinyin: "méi", wordType: null, meaning: "there is not" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "打篮球", pinyin: "dǎ lánqiú", wordType: "v.", meaning: "to play basketball" },
      { chinese: "因为", pinyin: "yīnwèi", wordType: "conj.", meaning: "because, since" },
      { chinese: "下雨", pinyin: "xià yǔ", wordType: null, meaning: "to rain" },
      { chinese: "所以", pinyin: "suǒyǐ", wordType: "conj.", meaning: "so, therefore" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "游泳", pinyin: "yóuyǒng", wordType: "v.", meaning: "to swim" },
      { chinese: "经常", pinyin: "jīngcháng", wordType: "adv.", meaning: "often, frequently" },
      { chinese: "月", pinyin: "yuè", wordType: null, meaning: "month" },
      { chinese: "现在", pinyin: "xiànzài", wordType: null, meaning: "now" },
      { chinese: "七", pinyin: "qī", wordType: null, meaning: "seven" },
      { chinese: "十", pinyin: "shí", wordType: null, meaning: "ten" },
      { chinese: "公斤", pinyin: "gōngjīn", wordType: "m.", meaning: "kilogram" },
      { chinese: "两", pinyin: "liǎng", wordType: null, meaning: "two" },
      { chinese: "张", pinyin: "zhāng", wordType: null, meaning: "used for flat objects such as paper, photos, etc." },
      { chinese: "北京", pinyin: "Běijīng", wordType: "prop. n.", meaning: "Beijing" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "旅游", pinyin: "lǚyóu", wordType: null, meaning: "to travel, to take a trip" },
      { chinese: "听说", pinyin: "tīngshuō", wordType: null, meaning: "to hear about, to be told" },
      { chinese: "看", pinyin: "kàn", wordType: null, meaning: "to look at, to watch, to read" },
      { chinese: "姐姐", pinyin: "jiějie", wordType: "n.", meaning: "elder sister" },
    ],
  },
  {
    chapterNumber: 7,
    words: [
      { chinese: "大卫", pinyin: "Dàwèi", wordType: "prop. n.", meaning: "David" },
      { chinese: "回来", pinyin: "huílai", wordType: null, meaning: "to come back" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "没有", pinyin: "méiyǒu", wordType: null, meaning: "there is not" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "还", pinyin: "hái", wordType: null, meaning: "passably, fairly, rather" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "教室", pinyin: "jiàoshì", wordType: "n.", meaning: "classroom" },
      { chinese: "学习", pinyin: "xuéxí", wordType: null, meaning: "to study, to learn" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "已经", pinyin: "yǐjīng", wordType: null, meaning: "already" },
      { chinese: "点", pinyin: "diǎn", wordType: null, meaning: "o'clock" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
      { chinese: "怎么", pinyin: "zěnme", wordType: null, meaning: "(indicating nature, condition or manner, etc.) how" },
      { chinese: "明天", pinyin: "míngtiān", wordType: null, meaning: "tomorrow" },
      { chinese: "有", pinyin: "yǒu", wordType: null, meaning: "to have, there be" },
      { chinese: "考试", pinyin: "kǎoshì", wordType: null, meaning: "test, exam" },
      { chinese: "说", pinyin: "shuō", wordType: null, meaning: "to speak, to say" },
      { chinese: "今天", pinyin: "jīntiān", wordType: null, meaning: "today" },
      { chinese: "要", pinyin: "yào", wordType: null, meaning: "to want to, would like to" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "准备", pinyin: "zhǔnbèi", wordType: null, meaning: "to intend, to plan" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "现在", pinyin: "xiànzài", wordType: null, meaning: "now" },
      { chinese: "哪儿", pinyin: "nǎr", wordType: null, meaning: "where" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "机场", pinyin: "jīchǎng", wordType: "n.", meaning: "airport" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "路", pinyin: "lù", wordType: "n.", meaning: "road, way" },
      { chinese: "上", pinyin: "shàng", wordType: null, meaning: "up, above; to go up, to ascend" },
      { chinese: "到", pinyin: "dào", wordType: "v.", meaning: "to arrive, to reach" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "下", pinyin: "xià", wordType: null, meaning: "under, below; (of rain, snow, etc.) to fall" },
      { chinese: "飞机", pinyin: "fēijī", wordType: null, meaning: "airplane" },
      { chinese: "长", pinyin: "cháng", wordType: null, meaning: "long" },
      { chinese: "时间", pinyin: "shíjiān", wordType: null, meaning: "time" },
      { chinese: "能", pinyin: "néng", wordType: null, meaning: "can, may" },
      { chinese: "这儿", pinyin: "zhèr", wordType: null, meaning: "here" },
      { chinese: "二", pinyin: "èr", wordType: null, meaning: "two" },
      { chinese: "十", pinyin: "shí", wordType: null, meaning: "ten" },
      { chinese: "分钟", pinyin: "fēnzhōng", wordType: null, meaning: "minute" },
      { chinese: "就", pinyin: "jiù", wordType: null, meaning: "used to indicate a conclusion or resolution" },
      { chinese: "家", pinyin: "jiā", wordType: null, meaning: "family" },
      { chinese: "离", pinyin: "lí", wordType: "v.", meaning: "to be away from" },
      { chinese: "公司", pinyin: "gōngsī", wordType: "n.", meaning: "company" },
      { chinese: "远", pinyin: "yuǎn", wordType: "adj.", meaning: "far, distant" },
      { chinese: "很", pinyin: "hěn", wordType: null, meaning: "very, quite" },
      { chinese: "坐", pinyin: "zuò", wordType: null, meaning: "to sit, to be seated" },
      { chinese: "公共汽车", pinyin: "gōnggòng qìchē", wordType: "n.", meaning: "bus" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "小时", pinyin: "xiǎoshí", wordType: "n.", meaning: "hour" },
      { chinese: "太", pinyin: "tài", wordType: null, meaning: "too, excessively" },
      { chinese: "慢", pinyin: "màn", wordType: "adj.", meaning: "slow" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "开", pinyin: "kāi", wordType: null, meaning: "to drive; to open out, to unfold" },
      { chinese: "车", pinyin: "chē", wordType: null, meaning: "car, vehicle" },
      { chinese: "也", pinyin: "yě", wordType: null, meaning: "also, too" },
      { chinese: "快", pinyin: "kuài", wordType: "adj.", meaning: "quick, fast" },
      { chinese: "晚上", pinyin: "wǎnshang", wordType: null, meaning: "evening, night" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "一起", pinyin: "yìqǐ", wordType: null, meaning: "together" },
      { chinese: "吃饭", pinyin: "chī fàn", wordType: null, meaning: "to eat a meal" },
      { chinese: "吧", pinyin: "ba", wordType: null, meaning: "a modal particle used at the end of a sentence to indicate consultation, a suggestion, request or command" },
      { chinese: "给", pinyin: "gěi", wordType: null, meaning: "to" },
      { chinese: "过", pinyin: "guò", wordType: "v.", meaning: "to pass (time), to spend" },
      { chinese: "生日", pinyin: "shēngrì", wordType: null, meaning: "birthday" },
      { chinese: "星期", pinyin: "xīngqī", wordType: null, meaning: "week" },
      { chinese: "北京", pinyin: "Běijīng", wordType: "prop. n.", meaning: "Beijing" },
      { chinese: "中国", pinyin: "Zhōngguó", wordType: "prop. n.", meaning: "China" },
      { chinese: "饭馆", pinyin: "fànguǎn", wordType: "n.", meaning: "restaurant" },
      { chinese: "走", pinyin: "zǒu", wordType: "v.", meaning: "to walk" },
      { chinese: "几", pinyin: "jǐ", wordType: null, meaning: "how many" },
    ],
  },
  {
    chapterNumber: 8,
    words: [
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "下午", pinyin: "xiàwǔ", wordType: null, meaning: "afternoon" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "看", pinyin: "kàn", wordType: null, meaning: "to look at, to watch, to read" },
      { chinese: "电影", pinyin: "diànyǐng", wordType: null, meaning: "film, movie" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "今天", pinyin: "jīntiān", wordType: null, meaning: "today" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "没有", pinyin: "méiyǒu", wordType: null, meaning: "there is not" },
      { chinese: "时间", pinyin: "shíjiān", wordType: null, meaning: "time" },
      { chinese: "明天", pinyin: "míngtiān", wordType: null, meaning: "tomorrow" },
      { chinese: "再", pinyin: "zài", wordType: "adv.", meaning: "again, once more" },
      { chinese: "吧", pinyin: "ba", wordType: null, meaning: "a modal particle used at the end of a sentence to indicate consultation, a suggestion, request or command" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "想", pinyin: "xiǎng", wordType: null, meaning: "to want, would like" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "让", pinyin: "ràng", wordType: "v.", meaning: "to let, to allow" },
      { chinese: "告诉", pinyin: "gàosu", wordType: "v.", meaning: "to tell" },
      { chinese: "外边", pinyin: "wàibian", wordType: "n.", meaning: "outside" },
      { chinese: "天气", pinyin: "tiānqì", wordType: null, meaning: "weather" },
      { chinese: "很", pinyin: "hěn", wordType: null, meaning: "very, quite" },
      { chinese: "出", pinyin: "chū", wordType: null, meaning: "to come/go out" },
      { chinese: "运动", pinyin: "yùndòng", wordType: null, meaning: "sport; to take physical exercise, to work out" },
      { chinese: "等", pinyin: "děng", wordType: "v.", meaning: "to wait" },
      { chinese: "王", pinyin: "Wáng", wordType: "prop. n.", meaning: "(surname) Wang" },
      { chinese: "老师", pinyin: "lǎoshī", wordType: null, meaning: "teacher" },
      { chinese: "给", pinyin: "gěi", wordType: null, meaning: "to" },
      { chinese: "大卫", pinyin: "Dàwèi", wordType: "prop. n.", meaning: "David" },
      { chinese: "打", pinyin: "dǎ", wordType: null, meaning: "to send, to remit" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "电话", pinyin: "diànhuà", wordType: "n.", meaning: "telephone, phone call" },
      { chinese: "回来", pinyin: "huílai", wordType: null, meaning: "to come back" },
      { chinese: "找", pinyin: "zhǎo", wordType: "v.", meaning: "to look for" },
      { chinese: "有", pinyin: "yǒu", wordType: null, meaning: "to have, there be" },
      { chinese: "事情", pinyin: "shìqing", wordType: "n.", meaning: "thing, matter" },
      { chinese: "听说", pinyin: "tīngshuō", wordType: null, meaning: "to hear about, to be told" },
      { chinese: "病", pinyin: "bìng", wordType: "n.", meaning: "illness; to be sick" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "服务员", pinyin: "fúwùyuán", wordType: "n.", meaning: "attendant, waiter" },
      { chinese: "房间", pinyin: "fángjiān", wordType: null, meaning: "room" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "门", pinyin: "mén", wordType: null, meaning: "door, gate" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "开", pinyin: "kāi", wordType: null, meaning: "to drive; to open out, to unfold" },
      { chinese: "您", pinyin: "nín", wordType: null, meaning: "(polite) you" },
      { chinese: "住", pinyin: "zhù", wordType: null, meaning: "to live, to stay" },
      { chinese: "哪", pinyin: "nǎ", wordType: null, meaning: "which" },
      { chinese: "叫", pinyin: "jiào", wordType: null, meaning: "to call, to be called" },
      { chinese: "人", pinyin: "rén", wordType: null, meaning: "human, person" },
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "几", pinyin: "jǐ", wordType: null, meaning: "how many" },
      { chinese: "件", pinyin: "jiàn", wordType: null, meaning: "(used for clothes among other items) piece" },
      { chinese: "衣服", pinyin: "yīfu", wordType: null, meaning: "clothes" },
      { chinese: "怎么样", pinyin: "zěnmeyàng", wordType: null, meaning: "(indicating nature, condition or manner) how" },
      { chinese: "白", pinyin: "bái", wordType: "adj.", meaning: "white" },
      { chinese: "有点儿", pinyin: "yǒudiǎnr", wordType: null, meaning: "a little, a bit" },
      { chinese: "长", pinyin: "cháng", wordType: null, meaning: "long" },
      { chinese: "那", pinyin: "nà", wordType: null, meaning: "that" },
      { chinese: "黑", pinyin: "hēi", wordType: "adj.", meaning: "black" },
      { chinese: "贵", pinyin: "guì", wordType: "adj.", meaning: "expensive" },
      { chinese: "红", pinyin: "hóng", wordType: null, meaning: "red" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "新", pinyin: "xīn", wordType: null, meaning: "new" },
      { chinese: "来", pinyin: "lái", wordType: null, meaning: "to come" },
    ],
  },
  {
    chapterNumber: 9,
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "请", pinyin: "qǐng", wordType: null, meaning: "(polite) please" },
      { chinese: "问", pinyin: "wèn", wordType: null, meaning: "to ask, to inquire" },
      { chinese: "张", pinyin: "zhāng", wordType: null, meaning: "used for flat objects such as paper, photos, etc." },
      { chinese: "欢", pinyin: "huān", wordType: "adj.", meaning: "happy, joyful (bound form)" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "打", pinyin: "dǎ", wordType: null, meaning: "to send, to remit" },
      { chinese: "错", pinyin: "cuò", wordType: "adj.", meaning: "wrong, incorrect" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "这儿", pinyin: "zhèr", wordType: null, meaning: "here" },
      { chinese: "没有", pinyin: "méiyǒu", wordType: null, meaning: "there is not" },
      { chinese: "叫", pinyin: "jiào", wordType: null, meaning: "to call, to be called" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "对不起", pinyin: "duìbuqǐ", wordType: null, meaning: "to be sorry" },
      { chinese: "您", pinyin: "nín", wordType: null, meaning: "(polite) you" },
      { chinese: "从", pinyin: "cóng", wordType: "prep.", meaning: "from" },
      { chinese: "几", pinyin: "jǐ", wordType: null, meaning: "how many" },
      { chinese: "岁", pinyin: "suì", wordType: null, meaning: "year (of age)" },
      { chinese: "开始", pinyin: "kāishǐ", wordType: null, meaning: "to begin, to start" },
      { chinese: "学习", pinyin: "xuéxí", wordType: null, meaning: "to study, to learn" },
      { chinese: "跳舞", pinyin: "tiàowǔ", wordType: "v.", meaning: "to dance" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "第一", pinyin: "dì yī", wordType: "num.", meaning: "first" },
      { chinese: "次", pinyin: "cì", wordType: null, meaning: "time" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "七", pinyin: "qī", wordType: null, meaning: "seven" },
      { chinese: "时候", pinyin: "shíhou", wordType: null, meaning: "time, moment" },
      { chinese: "女儿", pinyin: "nǚ'ér", wordType: null, meaning: "daughter" },
      { chinese: "今年", pinyin: "jīnnián", wordType: null, meaning: "this year" },
      { chinese: "也", pinyin: "yě", wordType: null, meaning: "also, too" },
      { chinese: "希望", pinyin: "xīwàng", wordType: "v.", meaning: "to hope, to wish" },
      { chinese: "她", pinyin: "tā", wordType: null, meaning: "she, her" },
      { chinese: "能", pinyin: "néng", wordType: null, meaning: "can, may" },
      { chinese: "跟", pinyin: "gēn", wordType: null, meaning: "with" },
      { chinese: "学", pinyin: "xué", wordType: null, meaning: "to learn (a skill/subject)" },
      { chinese: "可以", pinyin: "kěyǐ", wordType: null, meaning: "not bad" },
      { chinese: "没", pinyin: "méi", wordType: null, meaning: "there is not" },
      { chinese: "问题", pinyin: "wèntí", wordType: "n.", meaning: "question, problem" },
      { chinese: "非常", pinyin: "fēicháng", wordType: null, meaning: "very, extremely" },
      { chinese: "欢迎", pinyin: "huānyíng", wordType: "v.", meaning: "to welcome" },
      { chinese: "知道", pinyin: "zhīdào", wordType: null, meaning: "to know" },
      { chinese: "大卫", pinyin: "Dàwèi", wordType: "prop. n.", meaning: "David" },
      { chinese: "找", pinyin: "zhǎo", wordType: null, meaning: "to look for" },
      { chinese: "到", pinyin: "dào", wordType: null, meaning: "to arrive, to reach" },
      { chinese: "工作", pinyin: "gōngzuò", wordType: null, meaning: "to work; job" },
      { chinese: "太", pinyin: "tài", wordType: null, meaning: "too, excessively" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "上班", pinyin: "shàngbān", wordType: "v.", meaning: "to work, to do a job" },
      { chinese: "下", pinyin: "xià", wordType: null, meaning: "under, below; (of rain, snow, etc.) to fall" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "星期", pinyin: "xīngqī", wordType: null, meaning: "week" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "喜欢", pinyin: "xǐhuan", wordType: null, meaning: "to like, to be fond of" },
      { chinese: "昨天", pinyin: "zuótiān", wordType: null, meaning: "yesterday" },
      { chinese: "考试", pinyin: "kǎoshì", wordType: null, meaning: "test, exam" },
      { chinese: "怎么样", pinyin: "zěnmeyàng", wordType: null, meaning: "(indicating nature, condition or manner) how" },
      { chinese: "都", pinyin: "dōu", wordType: null, meaning: "both, all" },
      { chinese: "听", pinyin: "tīng", wordType: null, meaning: "to listen" },
      { chinese: "懂", pinyin: "dǒng", wordType: "v.", meaning: "to understand" },
      { chinese: "做", pinyin: "zuò", wordType: null, meaning: "to make, to produce" },
      { chinese: "完", pinyin: "wán", wordType: "v.", meaning: "to finish, to end" },
      { chinese: "题", pinyin: "tí", wordType: "n.", meaning: "question, problem" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
    ],
  },
  {
    chapterNumber: 10,
    words: [
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "要", pinyin: "yào", wordType: null, meaning: "to want to, would like to" },
      { chinese: "看", pinyin: "kàn", wordType: null, meaning: "to look at, to watch, to read" },
      { chinese: "电视", pinyin: "diànshì", wordType: null, meaning: "television" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "明天", pinyin: "míngtiān", wordType: null, meaning: "tomorrow" },
      { chinese: "上午", pinyin: "shàngwǔ", wordType: null, meaning: "morning, before noon" },
      { chinese: "还", pinyin: "hái", wordType: null, meaning: "passably, fairly, rather" },
      { chinese: "有", pinyin: "yǒu", wordType: null, meaning: "to have, there be" },
      { chinese: "汉语", pinyin: "Hànyǔ", wordType: null, meaning: "Chinese (language)" },
      { chinese: "课", pinyin: "kè", wordType: "n.", meaning: "class, lesson" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "对", pinyin: "duì", wordType: null, meaning: "(used before a noun or pronoun) to, for" },
      { chinese: "学", pinyin: "xué", wordType: null, meaning: "to learn (a skill/subject)" },
      { chinese: "帮助", pinyin: "bāngzhù", wordType: "v.", meaning: "to help, to assist" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "都", pinyin: "dōu", wordType: null, meaning: "both, all" },
      { chinese: "准备", pinyin: "zhǔnbèi", wordType: null, meaning: "to intend, to plan" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "别", pinyin: "bié", wordType: "adv.", meaning: "don't" },
      { chinese: "报纸", pinyin: "bàozhǐ", wordType: null, meaning: "newspaper" },
      { chinese: "医生", pinyin: "yīshēng", wordType: null, meaning: "doctor" },
      { chinese: "说", pinyin: "shuō", wordType: null, meaning: "to speak, to say" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
      { chinese: "休息", pinyin: "xiūxi", wordType: null, meaning: "to have or take a rest" },
      { chinese: "给", pinyin: "gěi", wordType: null, meaning: "to" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "杯", pinyin: "bēi", wordType: "m.", meaning: "cup, glass (measure word)" },
      { chinese: "茶", pinyin: "chá", wordType: null, meaning: "tea" },
      { chinese: "吧", pinyin: "ba", wordType: null, meaning: "a modal particle used at the end of a sentence to indicate consultation, a suggestion, request or command" },
      { chinese: "吃", pinyin: "chī", wordType: null, meaning: "to eat" },
      { chinese: "药", pinyin: "yào", wordType: null, meaning: "medicine, drug" },
      { chinese: "后", pinyin: "hòu", wordType: null, meaning: "after, afterwards, later" },
      { chinese: "两", pinyin: "liǎng", wordType: null, meaning: "two" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "小时", pinyin: "xiǎoshí", wordType: null, meaning: "hour" },
      { chinese: "喝", pinyin: "hē", wordType: null, meaning: "to drink" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "让", pinyin: "ràng", wordType: null, meaning: "to let, to allow" },
      { chinese: "听", pinyin: "tīng", wordType: null, meaning: "to listen" },
      { chinese: "怎么", pinyin: "zěnme", wordType: null, meaning: "(indicating nature, condition or manner, etc.) how" },
      { chinese: "买", pinyin: "mǎi", wordType: null, meaning: "to buy, to purchase" },
      { chinese: "这么", pinyin: "zhème", wordType: "pron.", meaning: "so, such, like this" },
      { chinese: "东西", pinyin: "dōngxi", wordType: null, meaning: "thing, stuff" },
      { chinese: "啊", pinyin: "a", wordType: null, meaning: "a modal particle used at the end of a sentence as a sign of confirmation or defense" },
      { chinese: "哥哥", pinyin: "gēge", wordType: "n.", meaning: "elder brother" },
      { chinese: "今天", pinyin: "jīntiān", wordType: null, meaning: "today" },
      { chinese: "中午", pinyin: "zhōngwǔ", wordType: null, meaning: "noon" },
      { chinese: "回来", pinyin: "huílai", wordType: null, meaning: "to come back" },
      { chinese: "吃饭", pinyin: "chī fàn", wordType: null, meaning: "to eat a meal" },
      { chinese: "羊肉", pinyin: "yángròu", wordType: null, meaning: "mutton" },
      { chinese: "鸡蛋", pinyin: "jīdàn", wordType: "n.", meaning: "(hen's) egg" },
      { chinese: "面条", pinyin: "miàntiáo", wordType: null, meaning: "noodles" },
      { chinese: "西瓜", pinyin: "xīguā", wordType: "n.", meaning: "watermelon" },
      { chinese: "真", pinyin: "zhēn", wordType: null, meaning: "really, indeed" },
      { chinese: "不少", pinyin: "bùshǎo", wordType: null, meaning: "quite a few, many" },
      { chinese: "妈妈", pinyin: "māma", wordType: null, meaning: "mother" },
      { chinese: "正在", pinyin: "zhèngzài", wordType: "adv.", meaning: "in the process of" },
      { chinese: "午饭", pinyin: "wǔfàn", wordType: "n.", meaning: "lunch" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "找", pinyin: "zhǎo", wordType: null, meaning: "to look for" },
      { chinese: "看见", pinyin: "kànjiàn", wordType: null, meaning: "to see" },
      { chinese: "手机", pinyin: "shǒujī", wordType: "n.", meaning: "cell phone" },
      { chinese: "白色", pinyin: "báisè", wordType: "n.", meaning: "white (color)" },
      { chinese: "桌子", pinyin: "zhuōzi", wordType: null, meaning: "desk, table" },
      { chinese: "上", pinyin: "shàng", wordType: null, meaning: "up, above; to go up, to ascend" },
      { chinese: "电脑", pinyin: "diànnǎo", wordType: null, meaning: "computer" },
      { chinese: "旁边", pinyin: "pángbiān", wordType: null, meaning: "beside" },
      { chinese: "衣服", pinyin: "yīfu", wordType: null, meaning: "clothes" },
      { chinese: "红色", pinyin: "hóngsè", wordType: null, meaning: "red" },
      { chinese: "那", pinyin: "nà", wordType: null, meaning: "that" },
      { chinese: "件", pinyin: "jiàn", wordType: null, meaning: "(used for clothes among other items) piece" },
      { chinese: "帮", pinyin: "bāng", wordType: null, meaning: "to help, to assist" },
      { chinese: "洗", pinyin: "xǐ", wordType: "v.", meaning: "to wash, to bathe" },
      { chinese: "外边", pinyin: "wàibian", wordType: "n.", meaning: "outside" },
    ],
  },
  {
    chapterNumber: 11,
    words: [
      { chinese: "王方", pinyin: "Wáng Fāng", wordType: "prop. n.", meaning: "Wang Fang (name)" },
      { chinese: "昨天", pinyin: "zuótiān", wordType: null, meaning: "yesterday" },
      { chinese: "和", pinyin: "hé", wordType: null, meaning: "and" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "一起", pinyin: "yìqǐ", wordType: null, meaning: "together" },
      { chinese: "唱歌", pinyin: "chànggē", wordType: "v.", meaning: "to sing" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "人", pinyin: "rén", wordType: null, meaning: "human, person" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "谁", pinyin: "shéi", wordType: null, meaning: "who, whom" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "朋友", pinyin: "péngyou", wordType: null, meaning: "friend" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "男", pinyin: "nán", wordType: "adj.", meaning: "man, male" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "同学", pinyin: "tóngxué", wordType: null, meaning: "classmate" },
      { chinese: "介绍", pinyin: "jièshào", wordType: null, meaning: "to introduce, to recommend" },
      { chinese: "第一", pinyin: "dì yī", wordType: null, meaning: "first" },
      { chinese: "次", pinyin: "cì", wordType: null, meaning: "time" },
      { chinese: "见", pinyin: "jiàn", wordType: "v.", meaning: "to see, to meet" },
      { chinese: "左边", pinyin: "zuǒbiān", wordType: null, meaning: "left side" },
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "看", pinyin: "kàn", wordType: null, meaning: "to look at, to watch, to read" },
      { chinese: "报纸", pinyin: "bàozhǐ", wordType: null, meaning: "newspaper" },
      { chinese: "女", pinyin: "nǚ", wordType: "adj.", meaning: "woman, female" },
      { chinese: "孩子", pinyin: "háizi", wordType: "n.", meaning: "child, kid" },
      { chinese: "姐姐", pinyin: "jiějie", wordType: null, meaning: "elder sister" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "右边", pinyin: "yòubiān", wordType: "n.", meaning: "right side" },
      { chinese: "写", pinyin: "xiě", wordType: null, meaning: "to write" },
      { chinese: "字", pinyin: "zì", wordType: null, meaning: "character, word" },
      { chinese: "那", pinyin: "nà", wordType: null, meaning: "that" },
      { chinese: "哥哥", pinyin: "gēge", wordType: null, meaning: "elder brother" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
      { chinese: "大", pinyin: "dà", wordType: null, meaning: "(of age) old" },
      { chinese: "岁", pinyin: "suì", wordType: null, meaning: "year (of age)" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "比", pinyin: "bǐ", wordType: "prep.", meaning: "than" },
      { chinese: "三", pinyin: "sān", wordType: null, meaning: "three" },
      { chinese: "今天", pinyin: "jīntiān", wordType: null, meaning: "today" },
      { chinese: "西瓜", pinyin: "xīguā", wordType: null, meaning: "watermelon" },
      { chinese: "怎么", pinyin: "zěnme", wordType: null, meaning: "(indicating nature, condition or manner, etc.) how" },
      { chinese: "卖", pinyin: "mài", wordType: "v.", meaning: "to sell" },
      { chinese: "块", pinyin: "kuài", wordType: null, meaning: "a unit of money, same as \"yuan\"" },
      { chinese: "五", pinyin: "wǔ", wordType: null, meaning: "five" },
      { chinese: "斤", pinyin: "jīn", wordType: "m.", meaning: "catty (unit of weight, ~500g)" },
      { chinese: "便宜", pinyin: "piányi", wordType: "adj.", meaning: "cheap, inexpensive" },
      { chinese: "苹果", pinyin: "píngguǒ", wordType: null, meaning: "apple" },
      { chinese: "也", pinyin: "yě", wordType: null, meaning: "also, too" },
      { chinese: "些", pinyin: "xiē", wordType: null, meaning: "some, a few" },
      { chinese: "您", pinyin: "nín", wordType: null, meaning: "(polite) you" },
      { chinese: "来", pinyin: "lái", wordType: null, meaning: "to come" },
      { chinese: "点儿", pinyin: "diǎnr", wordType: "m.", meaning: "a bit, some" },
      { chinese: "吧", pinyin: "ba", wordType: null, meaning: "a modal particle used at the end of a sentence to indicate consultation, a suggestion, request or command" },
      { chinese: "前边", pinyin: "qiánbian", wordType: "n.", meaning: "front, in front" },
      { chinese: "说话", pinyin: "shuōhuà", wordType: "v.", meaning: "to speak, to talk" },
      { chinese: "就", pinyin: "jiù", wordType: null, meaning: "used to indicate a conclusion or resolution" },
      { chinese: "汉语", pinyin: "Hànyǔ", wordType: null, meaning: "Chinese (language)" },
      { chinese: "老师", pinyin: "lǎoshī", wordType: null, meaning: "teacher" },
      { chinese: "可能", pinyin: "kěnéng", wordType: "aux.", meaning: "maybe, perhaps" },
      { chinese: "认识", pinyin: "rènshi", wordType: null, meaning: "to meet, to know" },
      { chinese: "她", pinyin: "tā", wordType: null, meaning: "she, her" },
      { chinese: "新", pinyin: "xīn", wordType: null, meaning: "new" },
      { chinese: "去年", pinyin: "qùnián", wordType: "n.", meaning: "last year" },
      { chinese: "姓", pinyin: "xìng", wordType: "v.", meaning: "family name, surname" },
      { chinese: "王", pinyin: "Wáng", wordType: "prop. n.", meaning: "(surname) Wang" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "小", pinyin: "xiǎo", wordType: null, meaning: "small, little" },
      { chinese: "两", pinyin: "liǎng", wordType: null, meaning: "two" },
    ],
  },
  {
    chapterNumber: 12,
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "每天", pinyin: "měi tiān", wordType: null, meaning: "every day" },
      { chinese: "早上", pinyin: "zǎoshang", wordType: null, meaning: "morning" },
      { chinese: "几", pinyin: "jǐ", wordType: null, meaning: "how many" },
      { chinese: "点", pinyin: "diǎn", wordType: null, meaning: "o'clock" },
      { chinese: "起床", pinyin: "qǐchuáng", wordType: null, meaning: "to get up, to get out of bed" },
      { chinese: "六", pinyin: "liù", wordType: null, meaning: "six" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
      { chinese: "比", pinyin: "bǐ", wordType: null, meaning: "than, (superior or inferior) to" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "早", pinyin: "zǎo", wordType: null, meaning: "early" },
      { chinese: "起", pinyin: "qǐ", wordType: "v.", meaning: "to rise, to get up (bound form)" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "小时", pinyin: "xiǎoshí", wordType: null, meaning: "hour" },
      { chinese: "睡", pinyin: "shuì", wordType: "v.", meaning: "to sleep" },
      { chinese: "得", pinyin: "de", wordType: "part.", meaning: "(introduces complement of degree)" },
      { chinese: "也", pinyin: "yě", wordType: null, meaning: "also, too" },
      { chinese: "晚上", pinyin: "wǎnshang", wordType: null, meaning: "evening, night" },
      { chinese: "十", pinyin: "shí", wordType: null, meaning: "ten" },
      { chinese: "就", pinyin: "jiù", wordType: null, meaning: "used to indicate a conclusion or resolution" },
      { chinese: "睡觉", pinyin: "shuì jiào", wordType: null, meaning: "to sleep" },
      { chinese: "身体", pinyin: "shēntǐ", wordType: null, meaning: "body" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "再", pinyin: "zài", wordType: null, meaning: "again, once more" },
      { chinese: "来", pinyin: "lái", wordType: null, meaning: "to come" },
      { chinese: "点儿", pinyin: "diǎnr", wordType: "m.", meaning: "a bit, some" },
      { chinese: "米饭", pinyin: "mǐfàn", wordType: null, meaning: "cooked rice" },
      { chinese: "吧", pinyin: "ba", wordType: null, meaning: "a modal particle used at the end of a sentence to indicate consultation, a suggestion, request or command" },
      { chinese: "吃", pinyin: "chī", wordType: null, meaning: "to eat" },
      { chinese: "太", pinyin: "tài", wordType: null, meaning: "too, excessively" },
      { chinese: "少", pinyin: "shǎo", wordType: null, meaning: "little, few" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "不少", pinyin: "bùshǎo", wordType: null, meaning: "quite a few, many" },
      { chinese: "今天", pinyin: "jīntiān", wordType: null, meaning: "today" },
      { chinese: "很", pinyin: "hěn", wordType: null, meaning: "very, quite" },
      { chinese: "谢谢", pinyin: "xièxie", wordType: null, meaning: "to thank" },
      { chinese: "做", pinyin: "zuò", wordType: null, meaning: "to make, to produce" },
      { chinese: "饭", pinyin: "fàn", wordType: "n.", meaning: "meal, rice (bound form)" },
      { chinese: "怎么样", pinyin: "zěnmeyàng", wordType: null, meaning: "(indicating nature, condition or manner) how" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "妻子", pinyin: "qīzi", wordType: "n.", meaning: "wife" },
      { chinese: "下", pinyin: "xià", wordType: null, meaning: "under, below; (of rain, snow, etc.) to fall" },
      { chinese: "雪", pinyin: "xuě", wordType: "n.", meaning: "snow" },
      { chinese: "真", pinyin: "zhēn", wordType: null, meaning: "really, indeed" },
      { chinese: "冷", pinyin: "lěng", wordType: null, meaning: "cold" },
      { chinese: "有", pinyin: "yǒu", wordType: null, meaning: "to have, there be" },
      { chinese: "零", pinyin: "líng", wordType: "num.", meaning: "zero" },
      { chinese: "度", pinyin: "dù", wordType: "n.", meaning: "degree" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "啊", pinyin: "a", wordType: null, meaning: "a modal particle used at the end of a sentence as a sign of confirmation or defense" },
      { chinese: "穿", pinyin: "chuān", wordType: "v.", meaning: "to wear, to put on" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "进", pinyin: "jìn", wordType: "v.", meaning: "to enter" },
      { chinese: "房间", pinyin: "fángjiān", wordType: null, meaning: "room" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "忙", pinyin: "máng", wordType: null, meaning: "busy" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "弟弟", pinyin: "dìdi", wordType: "n.", meaning: "younger brother" },
      { chinese: "让", pinyin: "ràng", wordType: null, meaning: "to let, to allow" },
      { chinese: "帮", pinyin: "bāng", wordType: null, meaning: "to help, to assist" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "找", pinyin: "zhǎo", wordType: null, meaning: "to look for" },
      { chinese: "房子", pinyin: "fángzi", wordType: null, meaning: "house, building" },
      { chinese: "现在", pinyin: "xiànzài", wordType: null, meaning: "now" },
      { chinese: "家", pinyin: "jiā", wordType: null, meaning: "family" },
      { chinese: "离", pinyin: "lí", wordType: null, meaning: "to be away from" },
      { chinese: "公司", pinyin: "gōngsī", wordType: null, meaning: "company, firm" },
      { chinese: "有点儿", pinyin: "yǒudiǎnr", wordType: null, meaning: "a little, a bit" },
      { chinese: "远", pinyin: "yuǎn", wordType: null, meaning: "far, distant" },
      { chinese: "住", pinyin: "zhù", wordType: null, meaning: "to live, to stay" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "累", pinyin: "lèi", wordType: "adj.", meaning: "tired" },
      { chinese: "希望", pinyin: "xīwàng", wordType: null, meaning: "to hope, to wish" },
      { chinese: "能", pinyin: "néng", wordType: null, meaning: "can, may" },
      { chinese: "近", pinyin: "jìn", wordType: "adj.", meaning: "near, close" },
      { chinese: "一点儿", pinyin: "yīdiǎnr", wordType: null, meaning: "a few, a little" },
    ],
  },
  {
    chapterNumber: 13,
    words: [
      { chinese: "门", pinyin: "mén", wordType: null, meaning: "door, gate" },
      { chinese: "开", pinyin: "kāi", wordType: null, meaning: "to drive; to open out, to unfold" },
      { chinese: "着", pinyin: "zhe", wordType: "part.", meaning: "(indicates a state)" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "请", pinyin: "qǐng", wordType: null, meaning: "(polite) please" },
      { chinese: "进", pinyin: "jìn", wordType: null, meaning: "to enter, to come/go in" },
      { chinese: "问", pinyin: "wèn", wordType: null, meaning: "to ask, to inquire" },
      { chinese: "张", pinyin: "zhāng", wordType: null, meaning: "used for flat objects such as paper, photos, etc." },
      { chinese: "先生", pinyin: "xiānsheng", wordType: null, meaning: "Mr., sir" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "他", pinyin: "tā", wordType: null, meaning: "he, him" },
      { chinese: "出", pinyin: "chū", wordType: null, meaning: "to come/go out" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "下午", pinyin: "xiàwǔ", wordType: null, meaning: "afternoon" },
      { chinese: "再", pinyin: "zài", wordType: null, meaning: "again, once more" },
      { chinese: "来", pinyin: "lái", wordType: null, meaning: "to come" },
      { chinese: "吧", pinyin: "ba", wordType: null, meaning: "a modal particle used at the end of a sentence to indicate consultation, a suggestion, request or command" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "谢谢", pinyin: "xièxie", wordType: null, meaning: "to thank" },
      { chinese: "那", pinyin: "nà", wordType: null, meaning: "that" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "正在", pinyin: "zhèngzài", wordType: null, meaning: "in the process of" },
      { chinese: "说话", pinyin: "shuōhuà", wordType: null, meaning: "to speak, to say, to talk" },
      { chinese: "女孩儿", pinyin: "nǚháir", wordType: null, meaning: "girl" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "谁", pinyin: "shéi", wordType: null, meaning: "who, whom" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "知道", pinyin: "zhīdào", wordType: null, meaning: "to know" },
      { chinese: "她", pinyin: "tā", wordType: null, meaning: "she, her" },
      { chinese: "名字", pinyin: "míngzi", wordType: null, meaning: "name" },
      { chinese: "姓", pinyin: "xìng", wordType: null, meaning: "family name, surname" },
      { chinese: "杨", pinyin: "Yáng", wordType: "prop. n.", meaning: "(surname) Yang" },
      { chinese: "叫", pinyin: "jiào", wordType: null, meaning: "to call, to be called" },
      { chinese: "杨笑笑", pinyin: "Yáng Xiàoxiào", wordType: "prop. n.", meaning: "name of a person" },
      { chinese: "姐姐", pinyin: "jiějie", wordType: null, meaning: "elder sister" },
      { chinese: "同学", pinyin: "tóngxué", wordType: null, meaning: "classmate" },
      { chinese: "手", pinyin: "shǒu", wordType: "n.", meaning: "hand" },
      { chinese: "里", pinyin: "lǐ", wordType: null, meaning: "inner, inside, interior" },
      { chinese: "拿", pinyin: "ná", wordType: "v.", meaning: "to hold, to take" },
      { chinese: "铅笔", pinyin: "qiānbǐ", wordType: "n.", meaning: "pencil" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "认识", pinyin: "rènshi", wordType: null, meaning: "to meet, to know" },
      { chinese: "听说", pinyin: "tīngshuō", wordType: null, meaning: "to hear about, to be told" },
      { chinese: "有", pinyin: "yǒu", wordType: null, meaning: "to have, there be" },
      { chinese: "女", pinyin: "nǚ", wordType: null, meaning: "woman, female" },
      { chinese: "朋友", pinyin: "péngyou", wordType: null, meaning: "friend" },
      { chinese: "就", pinyin: "jiù", wordType: null, meaning: "used to indicate a conclusion or resolution" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "班", pinyin: "bān", wordType: "n.", meaning: "class, grade" },
      { chinese: "长", pinyin: "zhǎng", wordType: "v.", meaning: "to grow" },
      { chinese: "两", pinyin: "liǎng", wordType: null, meaning: "two" },
      { chinese: "大", pinyin: "dà", wordType: null, meaning: "(of age) old" },
      { chinese: "眼睛", pinyin: "yǎnjing", wordType: null, meaning: "eye" },
      { chinese: "非常", pinyin: "fēicháng", wordType: null, meaning: "very, extremely" },
      { chinese: "爱", pinyin: "ài", wordType: null, meaning: "to like, to love" },
      { chinese: "笑", pinyin: "xiào", wordType: "v.", meaning: "to smile, to laugh" },
      { chinese: "男", pinyin: "nán", wordType: null, meaning: "man, male" },
      { chinese: "已经", pinyin: "yǐjīng", wordType: null, meaning: "already" },
      { chinese: "前", pinyin: "qián", wordType: null, meaning: "before, earlier than" },
      { chinese: "友", pinyin: "yǒu", wordType: "n.", meaning: "friend (bound form, as in 朋友/男友)" },
      { chinese: "这儿", pinyin: "zhèr", wordType: null, meaning: "here" },
      { chinese: "离", pinyin: "lí", wordType: null, meaning: "to be away from" },
      { chinese: "新京", pinyin: "Xīnjīng", wordType: "prop. n.", meaning: "Xinjing (hotel name)" },
      { chinese: "宾馆", pinyin: "bīnguǎn", wordType: "n.", meaning: "hotel" },
      { chinese: "远", pinyin: "yuǎn", wordType: null, meaning: "far, distant" },
      { chinese: "走", pinyin: "zǒu", wordType: null, meaning: "to walk" },
      { chinese: "路", pinyin: "lù", wordType: null, meaning: "road, path, way" },
      { chinese: "二", pinyin: "èr", wordType: null, meaning: "two" },
      { chinese: "十", pinyin: "shí", wordType: null, meaning: "ten" },
      { chinese: "分钟", pinyin: "fēnzhōng", wordType: null, meaning: "minute" },
      { chinese: "到", pinyin: "dào", wordType: null, meaning: "to arrive, to reach" },
      { chinese: "能", pinyin: "néng", wordType: null, meaning: "can, may" },
      { chinese: "告诉", pinyin: "gàosu", wordType: null, meaning: "to tell" },
      { chinese: "怎么", pinyin: "zěnme", wordType: null, meaning: "(indicating nature, condition or manner, etc.) how" },
      { chinese: "从", pinyin: "cóng", wordType: null, meaning: "from" },
      { chinese: "一直", pinyin: "yìzhí", wordType: "adv.", meaning: "straight, all along" },
      { chinese: "往", pinyin: "wǎng", wordType: "prep.", meaning: "to, towards" },
      { chinese: "前面", pinyin: "qiánmiàn", wordType: null, meaning: "front" },
      { chinese: "路口", pinyin: "lùkǒu", wordType: "n.", meaning: "crossing, crossroads" },
      { chinese: "右", pinyin: "yòu", wordType: "n.", meaning: "right (direction)" },
    ],
  },
  {
    chapterNumber: 14,
    words: [
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "看", pinyin: "kàn", wordType: null, meaning: "to look at, to watch, to read" },
      { chinese: "过", pinyin: "guò", wordType: null, meaning: "to pass (time), to spend (time)" },
      { chinese: "那", pinyin: "nà", wordType: null, meaning: "that" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "电影", pinyin: "diànyǐng", wordType: null, meaning: "film, movie" },
      { chinese: "没有", pinyin: "méiyǒu", wordType: null, meaning: "there is not" },
      { chinese: "没", pinyin: "méi", wordType: null, meaning: "there is not" },
      { chinese: "听说", pinyin: "tīngshuō", wordType: null, meaning: "to hear about, to be told" },
      { chinese: "很", pinyin: "hěn", wordType: null, meaning: "very, quite" },
      { chinese: "有意思", pinyin: "yǒu yìsi", wordType: "adj.", meaning: "interesting, fun" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "下", pinyin: "xià", wordType: null, meaning: "under, below; (of rain, snow, etc.) to fall" },
      { chinese: "星期", pinyin: "xīngqī", wordType: null, meaning: "week" },
      { chinese: "一起", pinyin: "yìqǐ", wordType: null, meaning: "together" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "吧", pinyin: "ba", wordType: null, meaning: "a modal particle used at the end of a sentence to indicate consultation, a suggestion, request or command" },
      { chinese: "可以", pinyin: "kěyǐ", wordType: null, meaning: "not bad" },
      { chinese: "但是", pinyin: "dànshì", wordType: "conj.", meaning: "but, still" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "女", pinyin: "nǚ", wordType: null, meaning: "woman, female" },
      { chinese: "朋友", pinyin: "péngyou", wordType: null, meaning: "friend" },
      { chinese: "也", pinyin: "yě", wordType: null, meaning: "also, too" },
      { chinese: "想", pinyin: "xiǎng", wordType: null, meaning: "to want, would like" },
      { chinese: "中国", pinyin: "Zhōngguó", wordType: "prop. n.", meaning: "China" },
      { chinese: "还", pinyin: "hái", wordType: null, meaning: "passably, fairly, rather" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "虽然", pinyin: "suīrán", wordType: "conj.", meaning: "although, though" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "几", pinyin: "jǐ", wordType: null, meaning: "how many" },
      { chinese: "次", pinyin: "cì", wordType: "m.", meaning: "time (frequency)" },
      { chinese: "再", pinyin: "zài", wordType: null, meaning: "again, once more" },
      { chinese: "玩儿", pinyin: "wánr", wordType: "v.", meaning: "to play, to have fun" },
      { chinese: "啊", pinyin: "a", wordType: null, meaning: "a modal particle used at the end of a sentence as a sign of confirmation or defense" },
      { chinese: "到时候", pinyin: "dào shíhou", wordType: null, meaning: "that time, then" },
      { chinese: "给", pinyin: "gěi", wordType: null, meaning: "to" },
      { chinese: "打电话", pinyin: "dǎ diànhuà", wordType: null, meaning: "to make a phone call" },
      { chinese: "明天", pinyin: "míngtiān", wordType: null, meaning: "tomorrow" },
      { chinese: "天气", pinyin: "tiānqì", wordType: null, meaning: "weather" },
      { chinese: "怎么样", pinyin: "zěnmeyàng", wordType: null, meaning: "(indicating nature, condition or manner) how" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "晴", pinyin: "qíng", wordType: "adj.", meaning: "sunny, fine, clear" },
      { chinese: "天", pinyin: "tiān", wordType: "n.", meaning: "day; sky" },
      { chinese: "冷", pinyin: "lěng", wordType: null, meaning: "cold" },
      { chinese: "能", pinyin: "néng", wordType: null, meaning: "can, may" },
      { chinese: "跑步", pinyin: "pǎobù", wordType: null, meaning: "to run, to jog" },
      { chinese: "自己", pinyin: "zìjǐ", wordType: null, meaning: "self" },
      { chinese: "有", pinyin: "yǒu", wordType: null, meaning: "to have, there be" },
      { chinese: "多", pinyin: "duō", wordType: null, meaning: "indicating degree or extent" },
      { chinese: "事情", pinyin: "shìqíng", wordType: null, meaning: "thing, matter, affair" },
      { chinese: "要", pinyin: "yào", wordType: null, meaning: "to want to, would like to" },
      { chinese: "做", pinyin: "zuò", wordType: null, meaning: "to make, to produce" },
      { chinese: "在", pinyin: "zài", wordType: null, meaning: "to be in/on/at; in/on/at" },
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "商店", pinyin: "shāngdiàn", wordType: null, meaning: "shop, store" },
      { chinese: "买", pinyin: "mǎi", wordType: null, meaning: "to buy, to purchase" },
      { chinese: "东西", pinyin: "dōngxi", wordType: null, meaning: "thing, stuff" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "这儿", pinyin: "zhèr", wordType: null, meaning: "here" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "就", pinyin: "jiù", wordType: null, meaning: "used to indicate a conclusion or resolution" },
      { chinese: "不", pinyin: "bù", wordType: null, meaning: "no, not" },
      { chinese: "便宜", pinyin: "piányi", wordType: null, meaning: "cheap, inexpensive" },
      { chinese: "喜欢", pinyin: "xǐhuan", wordType: null, meaning: "to like, to be fond of" },
      { chinese: "件", pinyin: "jiàn", wordType: null, meaning: "(used for clothes among other items) piece" },
      { chinese: "衣服", pinyin: "yīfu", wordType: null, meaning: "clothes" },
      { chinese: "觉得", pinyin: "juéde", wordType: null, meaning: "to think, to feel" },
      { chinese: "有点儿", pinyin: "yǒudiǎnr", wordType: null, meaning: "a little, a bit" },
      { chinese: "贵", pinyin: "guì", wordType: null, meaning: "expensive; (honorific term) your" },
      { chinese: "两", pinyin: "liǎng", wordType: null, meaning: "two" },
      { chinese: "百", pinyin: "bǎi", wordType: "num.", meaning: "hundred" },
      { chinese: "块", pinyin: "kuài", wordType: null, meaning: "a unit of money, same as \"yuan\"" },
    ],
  },
  {
    chapterNumber: 15,
    words: [
      { chinese: "今天", pinyin: "jīntiān", wordType: null, meaning: "today" },
      { chinese: "是", pinyin: "shì", wordType: null, meaning: "to be" },
      { chinese: "月", pinyin: "yuè", wordType: null, meaning: "month" },
      { chinese: "日", pinyin: "rì", wordType: "n.", meaning: "day, date" },
      { chinese: "新年", pinyin: "xīnnián", wordType: "n.", meaning: "New Year" },
      { chinese: "就", pinyin: "jiù", wordType: null, meaning: "used to indicate a conclusion or resolution" },
      { chinese: "要", pinyin: "yào", wordType: null, meaning: "to want to, would like to" },
      { chinese: "到", pinyin: "dào", wordType: null, meaning: "to arrive, to reach" },
      { chinese: "了", pinyin: "le", wordType: null, meaning: "used at the end of or in the middle of a sentence to indicate a change or a new circumstance" },
      { chinese: "你", pinyin: "nǐ", wordType: null, meaning: "(singular) you" },
      { chinese: "准备", pinyin: "zhǔnbèi", wordType: null, meaning: "to intend, to plan" },
      { chinese: "做", pinyin: "zuò", wordType: null, meaning: "to make, to produce" },
      { chinese: "什么", pinyin: "shénme", wordType: null, meaning: "what" },
      { chinese: "我", pinyin: "wǒ", wordType: null, meaning: "I, me" },
      { chinese: "想", pinyin: "xiǎng", wordType: null, meaning: "to want, would like" },
      { chinese: "去", pinyin: "qù", wordType: null, meaning: "to go" },
      { chinese: "北京", pinyin: "Běijīng", wordType: "prop. n.", meaning: "Beijing" },
      { chinese: "旅游", pinyin: "lǚyóu", wordType: null, meaning: "to travel, to take a trip" },
      { chinese: "很", pinyin: "hěn", wordType: null, meaning: "very, quite" },
      { chinese: "不错", pinyin: "búcuò", wordType: null, meaning: "pretty good" },
      { chinese: "过", pinyin: "guò", wordType: null, meaning: "to pass (time), to spend (time)" },
      { chinese: "一", pinyin: "yī", wordType: null, meaning: "one" },
      { chinese: "次", pinyin: "cì", wordType: null, meaning: "time" },
      { chinese: "买", pinyin: "mǎi", wordType: null, meaning: "to buy, to purchase" },
      { chinese: "票", pinyin: "piào", wordType: "n.", meaning: "ticket" },
      { chinese: "吗", pinyin: "ma", wordType: null, meaning: "used at the end of a question" },
      { chinese: "还", pinyin: "hái", wordType: null, meaning: "passably, fairly, rather" },
      { chinese: "没有", pinyin: "méiyǒu", wordType: null, meaning: "there is not" },
      { chinese: "呢", pinyin: "ne", wordType: null, meaning: "used at the end of a question" },
      { chinese: "明天", pinyin: "míngtiān", wordType: null, meaning: "tomorrow" },
      { chinese: "火车站", pinyin: "huǒchēzhàn", wordType: "n.", meaning: "railway station" },
      { chinese: "时间", pinyin: "shíjiān", wordType: null, meaning: "time" },
      { chinese: "得", pinyin: "de", wordType: null, meaning: "used after a verb or an adjective to introduce a complement of result or degree" },
      { chinese: "真", pinyin: "zhēn", wordType: null, meaning: "really, indeed" },
      { chinese: "快", pinyin: "kuài", wordType: null, meaning: "quick, fast" },
      { chinese: "新", pinyin: "xīn", wordType: null, meaning: "new" },
      { chinese: "的", pinyin: "de", wordType: null, meaning: "used after an attribute" },
      { chinese: "年", pinyin: "nián", wordType: null, meaning: "year" },
      { chinese: "啊", pinyin: "a", wordType: null, meaning: "a modal particle used at the end of a sentence as a sign of confirmation or defense" },
      { chinese: "谢谢", pinyin: "xièxie", wordType: null, meaning: "to thank" },
      { chinese: "大家", pinyin: "dàjiā", wordType: "pron.", meaning: "all, everybody" },
      { chinese: "这", pinyin: "zhè", wordType: null, meaning: "this" },
      { chinese: "对", pinyin: "duì", wordType: null, meaning: "(used before a noun or pronoun) to, for" },
      { chinese: "帮助", pinyin: "bāngzhù", wordType: null, meaning: "to help, to assist, to aid" },
      { chinese: "希望", pinyin: "xīwàng", wordType: null, meaning: "to hope, to wish" },
      { chinese: "我们", pinyin: "wǒmen", wordType: null, meaning: "we, us" },
      { chinese: "公司", pinyin: "gōngsī", wordType: null, meaning: "company, firm" },
      { chinese: "明年", pinyin: "míngnián", wordType: "n.", meaning: "next year" },
      { chinese: "更", pinyin: "gèng", wordType: "adv.", meaning: "more, to a greater extent" },
      { chinese: "好", pinyin: "hǎo", wordType: null, meaning: "good, fine" },
      { chinese: "妹妹", pinyin: "mèimei", wordType: "n.", meaning: "younger sister" },
      { chinese: "怎么", pinyin: "zěnme", wordType: null, meaning: "(indicating nature, condition or manner, etc.) how" },
      { chinese: "没", pinyin: "méi", wordType: null, meaning: "there is not" },
      { chinese: "来", pinyin: "lái", wordType: null, meaning: "to come" },
      { chinese: "都", pinyin: "dōu", wordType: null, meaning: "both, all" },
      { chinese: "八", pinyin: "bā", wordType: null, meaning: "eight" },
      { chinese: "点", pinyin: "diǎn", wordType: null, meaning: "o'clock" },
      { chinese: "四", pinyin: "sì", wordType: null, meaning: "four" },
      { chinese: "十", pinyin: "shí", wordType: null, meaning: "ten" },
      { chinese: "再", pinyin: "zài", wordType: null, meaning: "again, once more" },
      { chinese: "等", pinyin: "děng", wordType: null, meaning: "to wait, to await" },
      { chinese: "她", pinyin: "tā", wordType: null, meaning: "she, her" },
      { chinese: "几", pinyin: "jǐ", wordType: null, meaning: "how many" },
      { chinese: "分钟", pinyin: "fēnzhōng", wordType: null, meaning: "minute" },
      { chinese: "吧", pinyin: "ba", wordType: null, meaning: "a modal particle used at the end of a sentence to indicate consultation, a suggestion, request or command" },
      { chinese: "半", pinyin: "bàn", wordType: null, meaning: "half" },
      { chinese: "个", pinyin: "gè", wordType: null, meaning: "a general measure word" },
      { chinese: "小时", pinyin: "xiǎoshí", wordType: null, meaning: "hour" },
      { chinese: "听", pinyin: "tīng", wordType: null, meaning: "to listen" },
      { chinese: "见", pinyin: "jiàn", wordType: "v.", meaning: "to see, to meet" },
      { chinese: "说话", pinyin: "shuōhuà", wordType: null, meaning: "to speak, to say, to talk" },
      { chinese: "天", pinyin: "tiān", wordType: "n.", meaning: "day; sky" },
      { chinese: "阴", pinyin: "yīn", wordType: "adj.", meaning: "overcast, cloudy" },
      { chinese: "回", pinyin: "huí", wordType: null, meaning: "to come/go back, to return" },
      { chinese: "下雨", pinyin: "xià yǔ", wordType: null, meaning: "to rain" },
      { chinese: "路", pinyin: "lù", wordType: null, meaning: "road, path, way" },
      { chinese: "上", pinyin: "shàng", wordType: null, meaning: "up, above; to go up, to ascend" },
      { chinese: "慢", pinyin: "màn", wordType: null, meaning: "slow" },
      { chinese: "点儿", pinyin: "diǎnr", wordType: "m.", meaning: "a bit, some" },
      { chinese: "没关系", pinyin: "méi guānxi", wordType: null, meaning: "that's OK, it doesn't matter" },
      { chinese: "坐", pinyin: "zuò", wordType: null, meaning: "to sit, to be seated" },
      { chinese: "公共汽车", pinyin: "gōnggòng qìchē", wordType: null, meaning: "bus" },
      { chinese: "再见", pinyin: "zàijiàn", wordType: null, meaning: "to see you around" },
    ],
  },
];
