import type { ChapterWordRow } from "./extract-chapters";

// HSK2 chapter (lesson) word lists — see the comment atop hsk1-chapters-data.ts;
// same rationale and generation source, just characters/words/hsk2/ instead.

export interface Hsk2ChapterData {
  chapterNumber: number;
  title: string;
  words: ChapterWordRow[];
}

export const HSK2_CHAPTERS: Hsk2ChapterData[] = [
  {
    chapterNumber: 1,
    title: "Lesson 1 — Jiǔ yuè qù Běijīng lǚyóu zuì hǎo 九月去北京旅游最好 September is the best time to visit Beijing",
    words: [
      { chinese: "旅游", pinyin: "lǚyóu", wordType: "v.", meaning: "to travel, to take a trip" },
      { chinese: "觉得", pinyin: "juéde", wordType: "v.", meaning: "to think, to feel" },
      { chinese: "最", pinyin: "zuì", wordType: "adv.", meaning: "most, to the greatest extent" },
      { chinese: "为什么", pinyin: "wèi shénme", wordType: null, meaning: "why" },
      { chinese: "也", pinyin: "yě", wordType: "adv.", meaning: "also, too" },
      { chinese: "运动", pinyin: "yùndòng", wordType: "n./v.", meaning: "sport; to take physical exercise, to work out" },
      { chinese: "踢足球", pinyin: "tī zúqiú", wordType: "phrase", meaning: "to play football" },
      { chinese: "一起", pinyin: "yīqǐ", wordType: "adv.", meaning: "together" },
      { chinese: "要", pinyin: "yào", wordType: "aux.", meaning: "to want to, would like to" },
      { chinese: "新", pinyin: "xīn", wordType: "adj.", meaning: "new" },
      { chinese: "它", pinyin: "tā", wordType: "pron.", meaning: "it" },
      { chinese: "眼睛", pinyin: "yǎnjing", wordType: "n.", meaning: "eye" },
    ],
  },
  {
    chapterNumber: 2,
    title: "Lesson 2 — Wǒ měi tiān liù diǎn qǐ chuáng 我每天六点起床 I get up at six every day",
    words: [
      { chinese: "生病", pinyin: "shēng bìng", wordType: "v.", meaning: "to fall ill, to be sick" },
      { chinese: "每", pinyin: "měi", wordType: "pron.", meaning: "every, each" },
      { chinese: "早上", pinyin: "zǎoshang", wordType: "n.", meaning: "morning" },
      { chinese: "跑步", pinyin: "pǎo bù", wordType: "v.", meaning: "to run, to jog" },
      { chinese: "起床", pinyin: "qǐ chuáng", wordType: "v.", meaning: "to get up, to get out of bed" },
      { chinese: "药", pinyin: "yào", wordType: "n.", meaning: "medicine, drug" },
      { chinese: "身体", pinyin: "shēntǐ", wordType: "n.", meaning: "body" },
      { chinese: "出院", pinyin: "chū yuàn", wordType: "v.", meaning: "to leave hospital, to be discharged" },
      { chinese: "出", pinyin: "chū", wordType: "v.", meaning: "to come out, to go out" },
      { chinese: "高", pinyin: "gāo", wordType: "adj.", meaning: "tall, high" },
      { chinese: "米", pinyin: "mǐ", wordType: "m.", meaning: "meter" },
      { chinese: "知道", pinyin: "zhīdào", wordType: "v.", meaning: "to know" },
      { chinese: "休息", pinyin: "xiūxi", wordType: "v.", meaning: "to have or take a rest" },
      { chinese: "忙", pinyin: "máng", wordType: "adj.", meaning: "busy" },
      { chinese: "时间", pinyin: "shíjiān", wordType: "n.", meaning: "time" },
    ],
  },
  {
    chapterNumber: 3,
    title: "Lesson 3 — Zuǒbiān nàge hóngsè de shì wǒ de 左边那个红色的是我的 The red one on the left is mine",
    words: [
      { chinese: "手表", pinyin: "shǒubiǎo", wordType: "n.", meaning: "watch" },
      { chinese: "千", pinyin: "qiān", wordType: "num.", meaning: "thousand" },
      { chinese: "报纸", pinyin: "bàozhǐ", wordType: "n.", meaning: "newspaper" },
      { chinese: "送", pinyin: "sòng", wordType: "v.", meaning: "to send, to deliver" },
      { chinese: "一下", pinyin: "yīxià", wordType: "num.-m.", meaning: "used after a verb, indicating an act or an attempt" },
      { chinese: "牛奶", pinyin: "niúnǎi", wordType: "n.", meaning: "milk" },
      { chinese: "房间", pinyin: "fángjiān", wordType: "n.", meaning: "room" },
      { chinese: "丈夫", pinyin: "zhàngfu", wordType: "n.", meaning: "husband" },
      { chinese: "旁边", pinyin: "pángbiān", wordType: "n.", meaning: "beside" },
      { chinese: "真", pinyin: "zhēn", wordType: "adv.", meaning: "really, indeed" },
      { chinese: "粉色", pinyin: "fěnsè", wordType: "n./adj.", meaning: "pink" },
      { chinese: "粉", pinyin: "fěn", wordType: "n.", meaning: "powder; pink (short form)" },
      { chinese: "颜色", pinyin: "yánsè", wordType: "n.", meaning: "color" },
      { chinese: "左边", pinyin: "zuǒbiān", wordType: "n.", meaning: "left side" },
      { chinese: "红色", pinyin: "hóngsè", wordType: "n./adj.", meaning: "red" },
      { chinese: "红", pinyin: "hóng", wordType: "adj.", meaning: "red (short form)" },
    ],
  },
  {
    chapterNumber: 4,
    title: "Lesson 4 — Zhège gōngzuò shì tā bāng wǒ jièshào de 这个工作是他帮我介绍的 He recommended me for this job",
    words: [
      { chinese: "生日", pinyin: "shēngrì", wordType: "n.", meaning: "birthday" },
      { chinese: "快乐", pinyin: "kuàilè", wordType: "adj.", meaning: "happy, glad" },
      { chinese: "给", pinyin: "gěi", wordType: "prep.", meaning: "(used after a verb) to, for" },
      { chinese: "接", pinyin: "jiē", wordType: "v.", meaning: "to receive, to take, to accept" },
      { chinese: "晚上", pinyin: "wǎnshang", wordType: "n.", meaning: "evening, night" },
      { chinese: "问", pinyin: "wèn", wordType: "v.", meaning: "to ask" },
      { chinese: "非常", pinyin: "fēicháng", wordType: "adv.", meaning: "very, extremely" },
      { chinese: "开始", pinyin: "kāishǐ", wordType: "v.", meaning: "to begin, to start" },
      { chinese: "已经", pinyin: "yǐjīng", wordType: "adv.", meaning: "already" },
      { chinese: "长", pinyin: "cháng", wordType: "adj.", meaning: "long" },
      { chinese: "两", pinyin: "liǎng", wordType: "num.", meaning: "two" },
      { chinese: "帮", pinyin: "bāng", wordType: "v.", meaning: "to help, to assist" },
      { chinese: "介绍", pinyin: "jièshào", wordType: "v.", meaning: "to introduce, to recommend" },
    ],
  },
  {
    chapterNumber: 5,
    title: "Lesson 5 — Jiù mǎi zhè jiàn ba 就买这件吧 Take this one",
    words: [
      { chinese: "外面", pinyin: "wàimiàn", wordType: "n.", meaning: "outside" },
      { chinese: "准备", pinyin: "zhǔnbèi", wordType: "v.", meaning: "to intend, to plan" },
      { chinese: "就", pinyin: "jiù", wordType: "adv.", meaning: "used to indicate a conclusion or resolution" },
      { chinese: "鱼", pinyin: "yú", wordType: "n.", meaning: "fish" },
      { chinese: "吧", pinyin: "ba", wordType: "part.", meaning: "used at the end of a sentence to indicate consultation, suggestion, request or command" },
      { chinese: "件", pinyin: "jiàn", wordType: "m.", meaning: "(used for clothes among other items) piece" },
      { chinese: "还", pinyin: "hái", wordType: "adv.", meaning: "passably, fairly, rather" },
      { chinese: "可以", pinyin: "kěyǐ", wordType: "adj.", meaning: "not bad" },
      { chinese: "不错", pinyin: "búcuò", wordType: "adj.", meaning: "pretty good" },
      { chinese: "考试", pinyin: "kǎoshì", wordType: "n.", meaning: "test, exam" },
      { chinese: "意思", pinyin: "yìsi", wordType: "n.", meaning: "meaning" },
      { chinese: "咖啡", pinyin: "kāfēi", wordType: "n.", meaning: "coffee" },
      { chinese: "对", pinyin: "duì", wordType: "prep.", meaning: "(used before a noun or pronoun) to, for" },
      { chinese: "以后", pinyin: "yǐhòu", wordType: "n.", meaning: "after, afterwards, later" },
    ],
  },
  {
    chapterNumber: 6,
    title: "Lesson 6 — Nǐ zěnme bù chī le 你怎么不吃了 Why don't you eat more",
    words: [
      { chinese: "门", pinyin: "mén", wordType: "n.", meaning: "door, gate" },
      { chinese: "外", pinyin: "wài", wordType: "n.", meaning: "outer, outside" },
      { chinese: "自行车", pinyin: "zìxíngchē", wordType: "n.", meaning: "bike" },
      { chinese: "羊肉", pinyin: "yángròu", wordType: "n.", meaning: "mutton" },
      { chinese: "好吃", pinyin: "hǎochī", wordType: "adj.", meaning: "delicious, yummy" },
      { chinese: "面条", pinyin: "miàntiáo", wordType: "n.", meaning: "noodles" },
      { chinese: "打篮球", pinyin: "dǎ lánqiú", wordType: "phrase", meaning: "to play basketball" },
      { chinese: "因为", pinyin: "yīnwèi", wordType: "conj.", meaning: "because, since" },
      { chinese: "所以", pinyin: "suǒyǐ", wordType: "conj.", meaning: "so, therefore" },
      { chinese: "游泳", pinyin: "yóu yǒng", wordType: "v.", meaning: "to swim" },
      { chinese: "经常", pinyin: "jīngcháng", wordType: "adv.", meaning: "often, frequently" },
      { chinese: "公斤", pinyin: "gōngjīn", wordType: "m.", meaning: "kilogram" },
      { chinese: "姐姐", pinyin: "jiějie", wordType: "n.", meaning: "elder sister" },
    ],
  },
  {
    chapterNumber: 7,
    title: "Lesson 7 — Nǐ jiā lí gōngsī yuǎn ma 你家离公司远吗 Do you live far from your company",
    words: [
      { chinese: "教室", pinyin: "jiàoshì", wordType: "n.", meaning: "classroom" },
      { chinese: "机场", pinyin: "jīchǎng", wordType: "n.", meaning: "airport" },
      { chinese: "路", pinyin: "lù", wordType: "n.", meaning: "road, path, way" },
      { chinese: "离", pinyin: "lí", wordType: "v.", meaning: "to be away from" },
      { chinese: "公司", pinyin: "gōngsī", wordType: "n.", meaning: "company, firm" },
      { chinese: "远", pinyin: "yuǎn", wordType: "adj.", meaning: "far, distant" },
      { chinese: "公共汽车", pinyin: "gōnggòng qìchē", wordType: "n.", meaning: "bus" },
      { chinese: "小时", pinyin: "xiǎoshí", wordType: "n.", meaning: "hour" },
      { chinese: "慢", pinyin: "màn", wordType: "adj.", meaning: "slow" },
      { chinese: "快", pinyin: "kuài", wordType: "adj.", meaning: "quick, fast" },
      { chinese: "过", pinyin: "guò", wordType: "v.", meaning: "to pass (time), to spend (time)" },
      { chinese: "走", pinyin: "zǒu", wordType: "v.", meaning: "to walk" },
      { chinese: "到", pinyin: "dào", wordType: "v.", meaning: "to arrive, to reach" },
    ],
  },
  {
    chapterNumber: 8,
    title: "Lesson 8 — Ràng wǒ xiǎngxiang zài gàosu nǐ 让我想想再告诉你 Let me think about it and I'll tell you later",
    words: [
      { chinese: "再", pinyin: "zài", wordType: "adv.", meaning: "again, once more" },
      { chinese: "让", pinyin: "ràng", wordType: "v.", meaning: "to let, to allow" },
      { chinese: "告诉", pinyin: "gàosu", wordType: "v.", meaning: "to tell" },
      { chinese: "等", pinyin: "děng", wordType: "v.", meaning: "to wait, to await" },
      { chinese: "找", pinyin: "zhǎo", wordType: "v.", meaning: "to look for" },
      { chinese: "事情", pinyin: "shìqing", wordType: "n.", meaning: "thing, matter, affair" },
      { chinese: "服务员", pinyin: "fúwùyuán", wordType: "n.", meaning: "attendant, waiter/waitress" },
      { chinese: "白", pinyin: "bái", wordType: "adj.", meaning: "white" },
      { chinese: "黑", pinyin: "hēi", wordType: "adj.", meaning: "black" },
      { chinese: "贵", pinyin: "guì", wordType: "adj.", meaning: "expensive" },
    ],
  },
  {
    chapterNumber: 9,
    title: "Lesson 9 — Tí tài duō, wǒ méi zuòwán 题太多，我没做完 There were too many questions; I didn't finish all of them",
    words: [
      { chinese: "错", pinyin: "cuò", wordType: "adj.", meaning: "wrong, incorrect" },
      { chinese: "从", pinyin: "cóng", wordType: "prep.", meaning: "from" },
      { chinese: "跳舞", pinyin: "tiào wǔ", wordType: "v.", meaning: "to dance" },
      { chinese: "第一", pinyin: "dì yī", wordType: "num.", meaning: "first" },
      { chinese: "希望", pinyin: "xīwàng", wordType: "v.", meaning: "to hope, to wish" },
      { chinese: "问题", pinyin: "wèntí", wordType: "n.", meaning: "question, problem" },
      { chinese: "欢迎", pinyin: "huānyíng", wordType: "v.", meaning: "to welcome" },
      { chinese: "上班", pinyin: "shàng bān", wordType: "v.", meaning: "to work, to do a job" },
      { chinese: "懂", pinyin: "dǒng", wordType: "v.", meaning: "to understand, to know" },
      { chinese: "完", pinyin: "wán", wordType: "v.", meaning: "to finish, to end" },
      { chinese: "题", pinyin: "tí", wordType: "n.", meaning: "question (exam/exercise), topic" },
    ],
  },
  {
    chapterNumber: 10,
    title: "Lesson 10 — Bié zhǎo le, shǒujī zài zhuōzi shàng ne 别找了，手机在桌子上呢 Stop looking for your cell phone; it's on the desk",
    words: [
      { chinese: "课", pinyin: "kè", wordType: "n.", meaning: "class, lesson" },
      { chinese: "帮助", pinyin: "bāngzhù", wordType: "v.", meaning: "to help, to assist, to aid" },
      { chinese: "别", pinyin: "bié", wordType: "adv.", meaning: "don't" },
      { chinese: "哥哥", pinyin: "gēge", wordType: "n.", meaning: "elder brother" },
      { chinese: "鸡蛋", pinyin: "jīdàn", wordType: "n.", meaning: "(hen's) egg" },
      { chinese: "西瓜", pinyin: "xīguā", wordType: "n.", meaning: "watermelon" },
      { chinese: "正在", pinyin: "zhèngzài", wordType: "adv.", meaning: "in the process of" },
      { chinese: "手机", pinyin: "shǒujī", wordType: "n.", meaning: "cell phone" },
      { chinese: "洗", pinyin: "xǐ", wordType: "v.", meaning: "to wash, to bathe" },
    ],
  },
  {
    chapterNumber: 11,
    title: "Lesson 11 — Tā bǐ wǒ dà sān suì 他比我大三岁 He is three years older than me",
    words: [
      { chinese: "唱歌", pinyin: "chàng gē", wordType: "v.", meaning: "to sing" },
      { chinese: "男", pinyin: "nán", wordType: "adj.", meaning: "man, male" },
      { chinese: "女", pinyin: "nǚ", wordType: "adj.", meaning: "woman, female" },
      { chinese: "孩子", pinyin: "háizi", wordType: "n.", meaning: "child, kid" },
      { chinese: "右边", pinyin: "yòubian", wordType: "n.", meaning: "right, right side" },
      { chinese: "比", pinyin: "bǐ", wordType: "prep.", meaning: "than, (superior or inferior) to" },
      { chinese: "便宜", pinyin: "piányi", wordType: "adj.", meaning: "cheap, inexpensive" },
      { chinese: "说话", pinyin: "shuō huà", wordType: "v.", meaning: "to speak, to say, to talk" },
      { chinese: "可能", pinyin: "kěnéng", wordType: "aux.", meaning: "maybe, perhaps, probably" },
      { chinese: "去年", pinyin: "qùnián", wordType: "n.", meaning: "last year" },
      { chinese: "姓", pinyin: "xìng", wordType: "v.", meaning: "family name, surname" },
    ],
  },
  {
    chapterNumber: 12,
    title: "Lesson 12 — Nǐ chuān de tài shǎo le 你穿得太少了 You wear too little",
    words: [
      { chinese: "得", pinyin: "de", wordType: "part.", meaning: "used after a verb or an adjective to introduce a complement of result or degree" },
      { chinese: "妻子", pinyin: "qīzi", wordType: "n.", meaning: "wife" },
      { chinese: "雪", pinyin: "xuě", wordType: "n.", meaning: "snow" },
      { chinese: "零", pinyin: "líng", wordType: "num.", meaning: "zero" },
      { chinese: "度", pinyin: "dù", wordType: "n.", meaning: "degree" },
      { chinese: "穿", pinyin: "chuān", wordType: "v.", meaning: "to wear, to put on" },
      { chinese: "进", pinyin: "jìn", wordType: "v.", meaning: "to enter, to come/go in" },
      { chinese: "弟弟", pinyin: "dìdi", wordType: "n.", meaning: "younger brother" },
      { chinese: "近", pinyin: "jìn", wordType: "adj.", meaning: "near, close" },
    ],
  },
  {
    chapterNumber: 13,
    title: "Lesson 13 — Mén kāi zhe ne 门开着呢 The door is open",
    words: [
      { chinese: "着", pinyin: "zhe", wordType: "part.", meaning: "used to indicate a state" },
      { chinese: "手", pinyin: "shǒu", wordType: "n.", meaning: "hand" },
      { chinese: "拿", pinyin: "ná", wordType: "v.", meaning: "to hold, to take, to bring" },
      { chinese: "铅笔", pinyin: "qiānbǐ", wordType: "n.", meaning: "pencil" },
      { chinese: "班", pinyin: "bān", wordType: "n.", meaning: "class, grade, team" },
      { chinese: "长", pinyin: "zhǎng", wordType: "v.", meaning: "to grow, to develop" },
      { chinese: "笑", pinyin: "xiào", wordType: "v.", meaning: "to smile, to laugh" },
      { chinese: "宾馆", pinyin: "bīnguǎn", wordType: "n.", meaning: "hotel" },
      { chinese: "一直", pinyin: "yīzhí", wordType: "adv.", meaning: "straight, all along" },
      { chinese: "往", pinyin: "wǎng", wordType: "prep.", meaning: "to, towards" },
      { chinese: "路口", pinyin: "lùkǒu", wordType: "n.", meaning: "crossing, crossroads" },
    ],
  },
  {
    chapterNumber: 14,
    title: "Lesson 14 — Nǐ kànguo nàge diànyǐng ma 你看过那个电影吗 Have you seen that movie",
    words: [
      { chinese: "有意思", pinyin: "yǒu yìsi", wordType: "phrase", meaning: "interesting, fun" },
      { chinese: "但是", pinyin: "dànshì", wordType: "conj.", meaning: "but, still, yet" },
      { chinese: "虽然", pinyin: "suīrán", wordType: "conj.", meaning: "although, though" },
      { chinese: "次", pinyin: "cì", wordType: "m.", meaning: "time" },
      { chinese: "玩儿", pinyin: "wánr", wordType: "v.", meaning: "to play, to have fun" },
      { chinese: "晴", pinyin: "qíng", wordType: "adj.", meaning: "sunny, fine, clear" },
      { chinese: "百", pinyin: "bǎi", wordType: "num.", meaning: "hundred" },
    ],
  },
  {
    chapterNumber: 15,
    title: "Lesson 15 — Xīnnián jiù yào dào le 新年就要到了 The New Year is coming",
    words: [
      { chinese: "日", pinyin: "rì", wordType: "n.", meaning: "day, date" },
      { chinese: "新年", pinyin: "xīnnián", wordType: "n.", meaning: "New Year" },
      { chinese: "票", pinyin: "piào", wordType: "n.", meaning: "ticket" },
      { chinese: "火车站", pinyin: "huǒchēzhàn", wordType: "n.", meaning: "railway station" },
      { chinese: "大家", pinyin: "dàjiā", wordType: "pron.", meaning: "all, everybody" },
      { chinese: "更", pinyin: "gèng", wordType: "adv.", meaning: "more, to a greater extent" },
      { chinese: "妹妹", pinyin: "mèimei", wordType: "n.", meaning: "younger sister" },
      { chinese: "阴", pinyin: "yīn", wordType: "adj.", meaning: "overcast, cloudy" },
    ],
  },
];
