import type { CombinedVocabRow } from "./vocab-row";

// HSK2's combined (full-level) word list — see the comment atop
// hsk1-combined-data.ts; same rationale and generation source.

export const HSK2_COMBINED_WORDS: CombinedVocabRow[] = [
  { chinese: "我", pinyin: "wǒ", english: "I, me", category: "Personal Pron." },
  { chinese: "我们", pinyin: "wǒmen", english: "we, us （pl.）", category: "Personal Pron." },
  { chinese: "你", pinyin: "nǐ", english: "you", category: "Personal Pron." },
  { chinese: "你们", pinyin: "nǐmen", english: "you (pl.)", category: "Personal Pron." },
  { chinese: "他", pinyin: "tā", english: "he, him", category: "Personal Pron." },
  { chinese: "她", pinyin: "tā", english: "she, her", category: "Personal Pron." },
  { chinese: "他们", pinyin: "tāmen", english: "they (male+female / male，pl.)", category: "Personal Pron." },
  { chinese: "她们", pinyin: "tāmen", english: "they (females, pl.)", category: "Personal Pron." },
  { chinese: "这", pinyin: "zhè", english: "this", category: "Demonstrative Pron." },
  { chinese: "那", pinyin: "nà", english: "that", category: "Demonstrative Pron." },
  { chinese: "哪", pinyin: "nǎ", english: "which", category: "Interrogative Pron." },
  { chinese: "谁", pinyin: "shéi", english: "who", category: "Interrogative Pron." },
  { chinese: "什么", pinyin: "shénme", english: "what, why", category: "Interrogative Pron." },
  { chinese: "多少", pinyin: "duōshǎo", english: "how many, how much", category: "Interrogative Pron." },
  { chinese: "几", pinyin: "jǐ", english: "a few, how many", category: "Interrogative Pron." },
  { chinese: "怎么", pinyin: "zěnme", english: "how", category: "Interrogative Pron." },
  { chinese: "怎么样", pinyin: "zěnmeyàng", english: "how about", category: "Interrogative Pron." },
  { chinese: "您", pinyin: "nín", english: "you", category: "Interrogative Pron." },
  { chinese: "它", pinyin: "tā", english: "it", category: "Interrogative Pron." },
  { chinese: "大家", pinyin: "dàjiā", english: "everyone", category: "Interrogative Pron." },
  { chinese: "每", pinyin: "měi", english: "every", category: "Interrogative Pron." },
  { chinese: "为什么", pinyin: "wèishénme", english: "why", category: "Interrogative Pron." },
  { chinese: "一", pinyin: "yī", english: "one", category: "Numberal" },
  { chinese: "二", pinyin: "èr", english: "two", category: "Numberal" },
  { chinese: "三", pinyin: "sān", english: "three", category: "Numberal" },
  { chinese: "四", pinyin: "sì", english: "four", category: "Numberal" },
  { chinese: "五", pinyin: "wǔ", english: "five", category: "Numberal" },
  { chinese: "六", pinyin: "liù", english: "six", category: "Numberal" },
  { chinese: "七", pinyin: "qī", english: "seven", category: "Numberal" },
  { chinese: "八", pinyin: "bā", english: "eight", category: "Numberal" },
  { chinese: "九", pinyin: "jiǔ", english: "nine", category: "Numberal" },
  { chinese: "十", pinyin: "shí", english: "ten", category: "Numberal" },
  { chinese: "零", pinyin: "líng", english: "zero", category: "Numberal" },
  { chinese: "两", pinyin: "liǎng", english: "two", category: "Numberal" },
  { chinese: "百", pinyin: "bǎi", english: "hundred", category: "Numberal" },
  { chinese: "千", pinyin: "qiān", english: "thousand", category: "Numberal" },
  { chinese: "第一", pinyin: "dìyī", english: "first", category: "Numberal" },
  { chinese: "个", pinyin: "gè", english: "one, a, an", category: "Quantifier" },
  { chinese: "岁", pinyin: "suì", english: "year", category: "Quantifier" },
  { chinese: "本", pinyin: "běn", english: "volume", category: "Quantifier" },
  { chinese: "些", pinyin: "xiē", english: "some", category: "Quantifier" },
  { chinese: "块", pinyin: "kuài", english: "piece", category: "Quantifier" },
  { chinese: "次", pinyin: "cì", english: "number", category: "Quantifier" },
  { chinese: "公斤", pinyin: "gōngjīn", english: "kilogram", category: "Quantifier" },
  { chinese: "元", pinyin: "yuán", english: "yuan", category: "Quantifier" },
  { chinese: "件", pinyin: "jiàn", english: "piece", category: "Quantifier" },
  { chinese: "张", pinyin: "zhāng", english: "sheet", category: "Quantifier" },
  { chinese: "不", pinyin: "bù", english: "no", category: "Adverb" },
  { chinese: "没有", pinyin: "méiyǒu", english: "there is not", category: "Adverb" },
  { chinese: "很", pinyin: "hěn", english: "quite, very", category: "Adverb" },
  { chinese: "太", pinyin: "tài", english: "too", category: "Adverb" },
  { chinese: "都", pinyin: "dōu", english: "all", category: "Adverb" },
  { chinese: "别", pinyin: "bié", english: "other", category: "Adverb" },
  { chinese: "非常", pinyin: "fēicháng", english: "very", category: "Adverb" },
  { chinese: "也", pinyin: "yě", english: "likewise", category: "Adverb" },
  { chinese: "还", pinyin: "hái", english: "still", category: "Adverb" },
  { chinese: "最", pinyin: "zuì", english: "most", category: "Adverb" },
  { chinese: "真", pinyin: "zhēn", english: "real", category: "Adverb" },
  { chinese: "正在", pinyin: "zhèngzài", english: "be being", category: "Adverb" },
  { chinese: "已经", pinyin: "yǐjīng", english: "already", category: "Adverb" },
  { chinese: "一起", pinyin: "yìqǐ", english: "together", category: "Adverb" },
  { chinese: "再", pinyin: "zài", english: "again", category: "Adverb" },
  { chinese: "就", pinyin: "jiǜ", english: "at once", category: "Adverb" },
  { chinese: "和", pinyin: "hé", english: "and", category: "Conjunction" },
  { chinese: "因为", pinyin: "yīnwèi", english: "because", category: "Conjunction" },
  { chinese: "所以", pinyin: "suǒyǐ", english: "so", category: "Conjunction" },
  { chinese: "但是", pinyin: "dànshì", english: "but", category: "Conjunction" },
  { chinese: "在", pinyin: "zài", english: "in, at", category: "Preposition" },
  { chinese: "从", pinyin: "cóng", english: "from", category: "Preposition" },
  { chinese: "对", pinyin: "duì", english: "right", category: "Preposition" },
  { chinese: "此", pinyin: "cǐ", english: "this", category: "Preposition" },
  { chinese: "向", pinyin: "xiàng", english: "towards", category: "Preposition" },
  { chinese: "离", pinyin: "lí", english: "leave", category: "Preposition" },
  { chinese: "的", pinyin: "de", english: null, category: "Auxiliary" },
  { chinese: "了", pinyin: "le", english: null, category: "Auxiliary" },
  { chinese: "吗", pinyin: "ma", english: null, category: "Auxiliary" },
  { chinese: "呢", pinyin: "ne", english: null, category: "Auxiliary" },
  { chinese: "得", pinyin: "dé", english: null, category: "Auxiliary" },
  { chinese: "着", pinyin: "zhe", english: null, category: "Auxiliary" },
  { chinese: "过", pinyin: "guò", english: null, category: "Auxiliary" },
  { chinese: "吧", pinyin: "ba", english: null, category: "Auxiliary" },
  { chinese: "喂", pinyin: "wèi", english: "hello", category: "Interjection" },
  { chinese: "家", pinyin: "jiā", english: "home", category: "Noun" },
  { chinese: "学校", pinyin: "xuéxiào", english: "school", category: "Noun" },
  { chinese: "饭店", pinyin: "fàndiàn", english: "hotel, restaurant", category: "Noun" },
  { chinese: "商店", pinyin: "shāngdiàn", english: "store", category: "Noun" },
  { chinese: "医院", pinyin: "yīyuàn", english: "hospital", category: "Noun" },
  { chinese: "火车站", pinyin: "huǒchēzhàn", english: "train station", category: "Noun" },
  { chinese: "中国", pinyin: "Zhōngguó", english: "China", category: "Noun" },
  { chinese: "机场", pinyin: "jīchǎng", english: "airport", category: "Noun" },
  { chinese: "教室", pinyin: "jiàoshì", english: "classroom", category: "Noun" },
  { chinese: "房间", pinyin: "fángjiān", english: "room", category: "Noun" },
  { chinese: "路", pinyin: "lù", english: "road", category: "Noun" },
  { chinese: "北京", pinyin: "Běijīng", english: "Beijing", category: "Noun" },
  { chinese: "上", pinyin: "shàng", english: "up", category: "Noun" },
  { chinese: "下", pinyin: "xià", english: "below", category: "Noun" },
  { chinese: "前面", pinyin: "qiánmiàn", english: "front", category: "Noun" },
  { chinese: "后面", pinyin: "hòumiàn", english: "behind", category: "Noun" },
  { chinese: "左边", pinyin: "zuǒbiān", english: "left", category: "Noun" },
  { chinese: "右边", pinyin: "yòubiān", english: "right", category: "Noun" },
  { chinese: "外", pinyin: "wài", english: "out", category: "Noun" },
  { chinese: "旁边", pinyin: "pángbiān", english: "side", category: "Noun" },
  { chinese: "里", pinyin: "lǐ", english: "inside", category: "Noun" },
  { chinese: "今天", pinyin: "jīntiān", english: "today", category: "Noun" },
  { chinese: "明天", pinyin: "míngtiān", english: "tomorrow", category: "Noun" },
  { chinese: "昨天", pinyin: "zuótiān", english: "yesterday", category: "Noun" },
  { chinese: "上午", pinyin: "shàngwǔ", english: "morning", category: "Noun" },
  { chinese: "中午", pinyin: "zhōngwǔ", english: "noon", category: "Noun" },
  { chinese: "下午", pinyin: "xiàwǔ", english: "afternoon", category: "Noun" },
  { chinese: "年", pinyin: "nián", english: "year", category: "Noun" },
  { chinese: "月", pinyin: "yuè", english: "month", category: "Noun" },
  { chinese: "日", pinyin: "rì", english: "day", category: "Noun" },
  { chinese: "星期", pinyin: "xīngqī", english: "week", category: "Noun" },
  { chinese: "点", pinyin: "diǎn", english: "dot, spot", category: "Noun" },
  { chinese: "分钟", pinyin: "fēnzhōng", english: "minute", category: "Noun" },
  { chinese: "现在", pinyin: "xiànzài", english: "now", category: "Noun" },
  { chinese: "时候", pinyin: "shíhou", english: "time", category: "Noun" },
  { chinese: "早上", pinyin: "zǎoshàng", english: "morning", category: "Noun" },
  { chinese: "晚上", pinyin: "wǎnshàng", english: "night", category: "Noun" },
  { chinese: "小时", pinyin: "xiǎoshí", english: "hour", category: "Noun" },
  { chinese: "时间", pinyin: "shíjiān", english: "time", category: "Noun" },
  { chinese: "去年", pinyin: "qùnián", english: "last year", category: "Noun" },
  { chinese: "号", pinyin: "hào", english: "number", category: "Noun" },
  { chinese: "生日", pinyin: "shēngrì", english: "birthday", category: "Noun" },
  { chinese: "爸爸", pinyin: "bàba", english: "father", category: "Noun" },
  { chinese: "妈妈", pinyin: "māma", english: "mother", category: "Noun" },
  { chinese: "儿子", pinyin: "érzi", english: "son", category: "Noun" },
  { chinese: "女儿", pinyin: "nǚ'ér", english: "daughter", category: "Noun" },
  { chinese: "老师", pinyin: "lǎoshī", english: "teacher", category: "Noun" },
  { chinese: "学生", pinyin: "xuéshēng", english: "student", category: "Noun" },
  { chinese: "同学", pinyin: "tóngxué", english: "shoolmate", category: "Noun" },
  { chinese: "朋友", pinyin: "péngyǒu", english: "friend", category: "Noun" },
  { chinese: "医生", pinyin: "yīshēng", english: "doctor", category: "Noun" },
  { chinese: "先生", pinyin: "xiānsheng", english: "sir", category: "Noun" },
  { chinese: "小姐", pinyin: "xiǎojiě", english: "Miss", category: "Noun" },
  { chinese: "哥哥", pinyin: "gēge", english: "older brother", category: "Noun" },
  { chinese: "姐姐", pinyin: "jiějie", english: "older sister", category: "Noun" },
  { chinese: "弟弟", pinyin: "dìdi", english: "younger brother", category: "Noun" },
  { chinese: "妹妹", pinyin: "mèimei", english: "younger sister", category: "Noun" },
  { chinese: "丈夫", pinyin: "zhàngfu", english: "husband", category: "Noun" },
  { chinese: "妻子", pinyin: "qīzi", english: "wife", category: "Noun" },
  { chinese: "孩子", pinyin: "háizi", english: "child", category: "Noun" },
  { chinese: "男", pinyin: "nán", english: "man, male", category: "Adjective" },
  { chinese: "女", pinyin: "nǚ", english: "woman, female", category: "Adjective" },
  { chinese: "服务员", pinyin: "fúwùyuán", english: "waiter", category: "Noun" },
  { chinese: "衣服", pinyin: "yīfu", english: "cloth", category: "Noun" },
  { chinese: "水", pinyin: "shuǐ", english: "water", category: "Noun" },
  { chinese: "菜", pinyin: "cài", english: "dish", category: "Noun" },
  { chinese: "米饭", pinyin: "mǐfàn", english: "rice", category: "Noun" },
  { chinese: "水果", pinyin: "shuǐguǒ", english: "fruit", category: "Noun" },
  { chinese: "苹果", pinyin: "píngguǒ", english: "apple", category: "Noun" },
  { chinese: "茶", pinyin: "chá", english: "tea", category: "Noun" },
  { chinese: "杯子", pinyin: "bēizi", english: "cup", category: "Noun" },
  { chinese: "钱", pinyin: "qián", english: "money", category: "Noun" },
  { chinese: "飞机", pinyin: "fēijī", english: "airplane", category: "Noun" },
  { chinese: "出租车", pinyin: "chūzūchē", english: "taxi", category: "Noun" },
  { chinese: "电视", pinyin: "diànshì", english: "television", category: "Noun" },
  { chinese: "电脑", pinyin: "diànnǎo", english: "computer", category: "Noun" },
  { chinese: "电影", pinyin: "diànyǐng", english: "movie", category: "Noun" },
  { chinese: "天气", pinyin: "tiānqì", english: "weather", category: "Noun" },
  { chinese: "猫", pinyin: "māo", english: "cat", category: "Noun" },
  { chinese: "狗", pinyin: "gǒu", english: "dog", category: "Noun" },
  { chinese: "东西", pinyin: "dōngxi", english: "thing", category: "Noun" },
  { chinese: "鱼", pinyin: "yú", english: "fish", category: "Noun" },
  { chinese: "羊肉", pinyin: "yángròu", english: "mutton", category: "Noun" },
  { chinese: "牛奶", pinyin: "niúnǎi", english: "milk", category: "Noun" },
  { chinese: "鸡蛋", pinyin: "jīdàn", english: "egg", category: "Noun" },
  { chinese: "西瓜", pinyin: "xīguā", english: "watermelon", category: "Noun" },
  { chinese: "咖啡", pinyin: "kāfēi", english: "coffee", category: "Noun" },
  { chinese: "自行车", pinyin: "zìxíngchē", english: "bike", category: "Noun" },
  { chinese: "船", pinyin: "chuán", english: "boat", category: "Noun" },
  { chinese: "雪", pinyin: "xuě", english: "snow", category: "Noun" },
  { chinese: "药", pinyin: "yào", english: "medicine", category: "Noun" },
  { chinese: "手机", pinyin: "shǒujī", english: "cellphone", category: "Noun" },
  { chinese: "手表", pinyin: "shǒubiǎo", english: "watch", category: "Noun" },
  { chinese: "眼睛", pinyin: "yǎnjīng", english: "eye", category: "Noun" },
  { chinese: "身体", pinyin: "shēntǐ", english: "body", category: "Noun" },
  { chinese: "公共汽车", pinyin: "gōnggòngqìchē", english: "bus", category: "Noun" },
  { chinese: "报纸", pinyin: "bàozhǐ", english: "newspaper", category: "Noun" },
  { chinese: "人", pinyin: "rén", english: "person", category: "Noun" },
  { chinese: "名字", pinyin: "míngzì", english: "name", category: "Noun" },
  { chinese: "书", pinyin: "shū", english: "book", category: "Noun" },
  { chinese: "汉语", pinyin: "hànyǔ", english: "Chinese", category: "Noun" },
  { chinese: "字", pinyin: "zì", english: "character", category: "Noun" },
  { chinese: "桌子", pinyin: "zhuōzi", english: "desk", category: "Noun" },
  { chinese: "椅子", pinyin: "yǐzi", english: "chair", category: "Noun" },
  { chinese: "门", pinyin: "mén", english: "door", category: "Noun" },
  { chinese: "题", pinyin: "tí", english: "topic", category: "Noun" },
  { chinese: "课", pinyin: "kè", english: "lesson", category: "Noun" },
  { chinese: "姓", pinyin: "xìng", english: "surname", category: "Noun" },
  { chinese: "问题", pinyin: "wèntí", english: "question", category: "Noun" },
  { chinese: "事情", pinyin: "shìqing", english: "matter", category: "Noun" },
  { chinese: "考试", pinyin: "kǎoshì", english: "exam", category: "Noun" },
  { chinese: "票", pinyin: "piào", english: "ticket", category: "Noun" },
  { chinese: "意思", pinyin: "yìsi", english: "meaning", category: "Noun" },
  { chinese: "颜色", pinyin: "yánsè", english: "color", category: "Noun" },
  { chinese: "谢谢", pinyin: "xièxie", english: "thank", category: "Verb" },
  { chinese: "不客气", pinyin: "búkèqì", english: "you are welcome", category: "Verb" },
  { chinese: "再见", pinyin: "zàijiàn", english: "good-bye", category: "Verb" },
  { chinese: "请", pinyin: "qǐng", english: "please", category: "Verb" },
  { chinese: "对不起", pinyin: "duìbùqǐ", english: "sorry", category: "Verb" },
  { chinese: "没关系", pinyin: "méiguānxi", english: "It doesn't matter", category: "Verb" },
  { chinese: "欢迎", pinyin: "huānyíng", english: "welcome", category: "Verb" },
  { chinese: "是", pinyin: "shì", english: "am, is, are", category: "Verb" },
  { chinese: "有", pinyin: "yǒu", english: "have", category: "Verb" },
  { chinese: "看", pinyin: "kàn", english: "look", category: "Verb" },
  { chinese: "听", pinyin: "tīng", english: "listen", category: "Verb" },
  { chinese: "说话", pinyin: "shuōhuà", english: "speak", category: "Verb" },
  { chinese: "读", pinyin: "dú", english: "read", category: "Verb" },
  { chinese: "写", pinyin: "xiě", english: "write", category: "Verb" },
  { chinese: "看见", pinyin: "kànjiàn", english: "see", category: "Verb" },
  { chinese: "叫", pinyin: "jiào", english: "call", category: "Verb" },
  { chinese: "来", pinyin: "lái", english: "come", category: "Verb" },
  { chinese: "回", pinyin: "huí", english: "return", category: "Verb" },
  { chinese: "去", pinyin: "qù", english: "go", category: "Verb" },
  { chinese: "吃", pinyin: "chī", english: "eat", category: "Verb" },
  { chinese: "喝", pinyin: "hē", english: "drink", category: "Verb" },
  { chinese: "睡觉", pinyin: "shuìjiào", english: "sleep", category: "Verb" },
  { chinese: "打电话", pinyin: "dǎdiànhuà", english: "call up", category: "Verb" },
  { chinese: "做", pinyin: "zuò", english: "do", category: "Verb" },
  { chinese: "买", pinyin: "mǎi", english: "buy", category: "Verb" },
  { chinese: "开", pinyin: "kāi", english: "open", category: "Verb" },
  { chinese: "坐", pinyin: "zuò", english: "sit", category: "Verb" },
  { chinese: "住", pinyin: "zhù", english: "live", category: "Verb" },
  { chinese: "学习", pinyin: "xuéxí", english: "study", category: "Verb" },
  { chinese: "工作", pinyin: "gōngzuò", english: "work", category: "Verb" },
  { chinese: "下雨", pinyin: "xiàyǔ", english: "rain", category: "Verb" },
  { chinese: "问", pinyin: "wèn", english: "ask", category: "Verb" },
  { chinese: "走", pinyin: "zǒu", english: "walk", category: "Verb" },
  { chinese: "进", pinyin: "jìn", english: "enter", category: "Verb" },
  { chinese: "出", pinyin: "chū", english: "come", category: "Verb" },
  { chinese: "跑步", pinyin: "pǎobù", english: "run", category: "Verb" },
  { chinese: "到", pinyin: "dào", english: "arrive", category: "Verb" },
  { chinese: "穿", pinyin: "chuān", english: "wear", category: "Verb" },
  { chinese: "洗", pinyin: "xǐ", english: "wash", category: "Verb" },
  { chinese: "给", pinyin: "gěi", english: "give", category: "Verb" },
  { chinese: "找", pinyin: "zhǎo", english: "find", category: "Verb" },
  { chinese: "懂", pinyin: "dǒng", english: "understand", category: "Verb" },
  { chinese: "笑", pinyin: "xiào", english: "smile", category: "Verb" },
  { chinese: "回答", pinyin: "huídá", english: "answer", category: "Verb" },
  { chinese: "告诉", pinyin: "gàosù", english: "tell", category: "Verb" },
  { chinese: "准备", pinyin: "zhǔnbèi", english: "prepare", category: "Verb" },
  { chinese: "开始", pinyin: "kāishǐ", english: "begin", category: "Verb" },
  { chinese: "介绍", pinyin: "jièshào", english: "introduce", category: "Verb" },
  { chinese: "帮助", pinyin: "bāngzhù", english: "help", category: "Verb" },
  { chinese: "玩儿", pinyin: "wánr", english: "to play, to have fun", category: "Verb" },
  { chinese: "送", pinyin: "sòng", english: "present", category: "Verb" },
  { chinese: "等", pinyin: "děng", english: "wait", category: "Verb" },
  { chinese: "让", pinyin: "ràng", english: "let", category: "Verb" },
  { chinese: "起床", pinyin: "qǐchuáng", english: "get up", category: "Verb" },
  { chinese: "唱歌", pinyin: "chànggē", english: "sing", category: "Verb" },
  { chinese: "跳舞", pinyin: "tiàowǔ", english: "dance", category: "Verb" },
  { chinese: "旅游", pinyin: "lǚyóu", english: "travel", category: "Verb" },
  { chinese: "上班", pinyin: "shàngbān", english: "be on duty", category: "Verb" },
  { chinese: "生病", pinyin: "shēngbìng", english: "fall ill", category: "Verb" },
  { chinese: "休息", pinyin: "xiūxi", english: "rest", category: "Verb" },
  { chinese: "运动", pinyin: "yùndòng", english: "exercise", category: "Verb" },
  { chinese: "游泳", pinyin: "yóuyǒng", english: "swim", category: "Verb" },
  { chinese: "踢足球", pinyin: "tīzúqiú", english: "play footbal", category: "Verb" },
  { chinese: "打篮球", pinyin: "dǎlánqiú", english: "play basketball", category: "Verb" },
  { chinese: "完", pinyin: "wán", english: "finish", category: "Verb" },
  { chinese: "爱", pinyin: "ài", english: "love", category: "Verb" },
  { chinese: "喜欢", pinyin: "xǐhuān", english: "love, like", category: "Verb" },
  { chinese: "想", pinyin: "xiǎng", english: "want", category: "Verb" },
  { chinese: "认识", pinyin: "rènshi", english: "know", category: "Verb" },
  { chinese: "觉得", pinyin: "juédé", english: "think", category: "Verb" },
  { chinese: "知道", pinyin: "zhīdao", english: "know", category: "Verb" },
  { chinese: "希望", pinyin: "xīwàng", english: "hope", category: "Verb" },
  { chinese: "会", pinyin: "huì", english: "can", category: "Verb" },
  { chinese: "能", pinyin: "néng", english: "can, be able to", category: "Verb" },
  { chinese: "可以", pinyin: "kěyǐ", english: "can", category: "Verb" },
  { chinese: "要", pinyin: "yào", english: "ask for", category: "Verb" },
  { chinese: "可能", pinyin: "kěnéng", english: "may", category: "Verb" },
  { chinese: "好", pinyin: "hǎo", english: "good", category: "Adjective" },
  { chinese: "大", pinyin: "dà", english: "big", category: "Adjective" },
  { chinese: "小", pinyin: "xiǎo", english: "small", category: "Adjective" },
  { chinese: "多", pinyin: "duō", english: "many, much", category: "Adjective" },
  { chinese: "少", pinyin: "shǎo", english: "few, little", category: "Adjective" },
  { chinese: "冷", pinyin: "lěng", english: "cold", category: "Adjective" },
  { chinese: "热", pinyin: "rè", english: "hot", category: "Adjective" },
  { chinese: "高兴", pinyin: "gāoxìng", english: "happy", category: "Adjective" },
  { chinese: "漂亮", pinyin: "piàoliang", english: "beautiful", category: "Adjective" },
  { chinese: "高", pinyin: "gāo", english: "tall", category: "Adjective" },
  { chinese: "红", pinyin: "hóng", english: "red", category: "Adjective" },
  { chinese: "白", pinyin: "bái", english: "white", category: "Adjective" },
  { chinese: "黑", pinyin: "hēi", english: "black", category: "Adjective" },
  { chinese: "忙", pinyin: "máng", english: "busy", category: "Adjective" },
  { chinese: "快", pinyin: "kuài", english: "fast", category: "Adjective" },
  { chinese: "慢", pinyin: "màn", english: "slow", category: "Adjective" },
  { chinese: "远", pinyin: "yuǎn", english: "far", category: "Adjective" },
  { chinese: "近", pinyin: "jìn", english: "close", category: "Adjective" },
  { chinese: "好吃", pinyin: "hǎochī", english: "delicioous", category: "Adjective" },
  { chinese: "累", pinyin: "lèi", english: "tired", category: "Adjective" },
  { chinese: "长", pinyin: "cháng", english: "long", category: "Adjective" },
  { chinese: "新", pinyin: "xīn", english: "new", category: "Adjective" },
  { chinese: "贵", pinyin: "guì", english: "expensive", category: "Adjective" },
  { chinese: "便宜", pinyin: "piányi", english: "cheap", category: "Adjective" },
  { chinese: "晴", pinyin: "qíng", english: "fine", category: "Adjective" },
  { chinese: "阴", pinyin: "yīn", english: "cloudy", category: "Adjective" },
  { chinese: "错", pinyin: "cuò", english: "wrong", category: "Adjective" },
  { chinese: "快乐", pinyin: "kuàilè", english: "happy", category: "Adjective" },
  { chinese: "说", pinyin: "shuō", english: "speak, say", category: "Verb" },
  { chinese: "一点儿", pinyin: "yìdiǎnr", english: "a little", category: "Quantifier" },
  { chinese: "这儿", pinyin: "zhèr", english: "here", category: "Demonstrative Pron." },
  { chinese: "那儿", pinyin: "nàr", english: "there", category: "Demonstrative Pron." },
  { chinese: "哪儿", pinyin: "nǎr", english: "where", category: "Interrogative Pron." },
  { chinese: "比", pinyin: "bǐ", english: "than", category: "Preposition" },
  { chinese: "宾馆", pinyin: "bīnguǎn", english: "hotel", category: "Noun" },
  { chinese: "公司", pinyin: "gōngsī", english: "company, firm", category: "Noun" },
  { chinese: "面条", pinyin: "miàntiáo", english: "noodles", category: "Noun" },
  { chinese: "铅笔", pinyin: "qiānbǐ", english: "pencil", category: "Noun" },
  { chinese: "虽然", pinyin: "suīrán", english: "although, though", category: "Conjunction" },
  { chinese: "往", pinyin: "wǎng", english: "to, towards", category: "Preposition" },
  { chinese: "一下", pinyin: "yíxià", english: "used after a verb, indicating a brief attempt", category: "Quantifier" },
];
