import type { TranscriptLineRow } from "./extract-transcripts";

// HSK2 chapters' actual dialog transcripts — docs/25-chapter-all-words
// -plan.md's addendum. Auto-extracted (scripts-tmp-extract-transcripts.ts)
// from the same pasted textbook dialog text the All Words vocabulary was
// segmented from — this captures the full sentences (speaker, pinyin,
// English) rather than just the words used in them.

export interface Hsk2ChapterTranscriptData {
  chapterNumber: number;
  lines: TranscriptLineRow[];
}

export const HSK2_CHAPTER_TRANSCRIPTS: Hsk2ChapterTranscriptData[] = [
  {
    chapterNumber: 1,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "Planning a trip", speaker: "A", chinese: "我要去北京旅游，你觉得什么时候去最好？", pinyin: "Wǒ yào qù Běijīng lǚyóu, nǐ juéde shénme shíhou qù zuì hǎo?", english: "I'm thinking of a trip to Beijing. When do you think is the best time?" },
      { order: 2, dialogNumber: 1, dialogLabel: "Planning a trip", speaker: "B", chinese: "九月去北京旅游最好。", pinyin: "Jiǔ yuè qù Běijīng lǚyóu zuì hǎo.", english: "September is the best time to visit Beijing." },
      { order: 3, dialogNumber: 1, dialogLabel: "Planning a trip", speaker: "A", chinese: "为什么？", pinyin: "Wèi shénme?", english: "Why?" },
      { order: 4, dialogNumber: 1, dialogLabel: "Planning a trip", speaker: "B", chinese: "九月的北京天气不冷也不热。", pinyin: "Jiǔ yuè de Běijīng tiānqì bù lěng yě bú rè.", english: "Because it's neither cold nor hot there in September." },
      { order: 5, dialogNumber: 2, dialogLabel: "Looking at a picture", speaker: "A", chinese: "你喜欢什么运动？", pinyin: "Nǐ xǐhuān shénme yùndòng?", english: "What sport do you like?" },
      { order: 6, dialogNumber: 2, dialogLabel: "Looking at a picture", speaker: "B", chinese: "我最喜欢踢足球。", pinyin: "Wǒ zuì xǐhuān tī zúqiú.", english: "I like playing football best." },
      { order: 7, dialogNumber: 2, dialogLabel: "Looking at a picture", speaker: "A", chinese: "下午我们一起去踢足球吧。", pinyin: "Xiàwǔ wǒmen yìqǐ qù tī zúqiú ba.", english: "Let's go to play football this afternoon." },
      { order: 8, dialogNumber: 2, dialogLabel: "Looking at a picture", speaker: "B", chinese: "好啊！", pinyin: "Hǎo a!", english: "Great!" },
      { order: 9, dialogNumber: 3, dialogLabel: "Buying chairs", speaker: "A", chinese: "我们要不要买几个新的椅子？", pinyin: "Wǒmen yào bu yào mǎi jǐ ge xīn de yǐzi?", english: "Don't you think we should buy some new chairs?" },
      { order: 10, dialogNumber: 3, dialogLabel: "Buying chairs", speaker: "B", chinese: "好啊。什么时候去买？", pinyin: "Hǎo a. Shénme shíhou qù mǎi?", english: "Yes. When shall we go to buy them?" },
      { order: 11, dialogNumber: 3, dialogLabel: "Buying chairs", speaker: "A", chinese: "明天下午怎么样？你明天几点能回来？", pinyin: "Míngtiān xiàwǔ zěnmeyàng? Nǐ míngtiān jǐ diǎn néng huílái?", english: "What about tomorrow afternoon? When will you be back tomorrow?" },
      { order: 12, dialogNumber: 3, dialogLabel: "Buying chairs", speaker: "B", chinese: "三点多。", pinyin: "Sān diǎn duō.", english: "A little bit later after three o'clock." },
      { order: 13, dialogNumber: 4, dialogLabel: "At home", speaker: "A", chinese: "桌子下面有个猫。", pinyin: "Zhuōzi xiàmiàn yǒu ge māo.", english: "There is a cat under the table." },
      { order: 14, dialogNumber: 4, dialogLabel: "At home", speaker: "B", chinese: "那是我的猫，它叫花花。", pinyin: "Nà shì wǒ de māo, tā jiào Huāhua.", english: "It's my cat Huahua." },
      { order: 15, dialogNumber: 4, dialogLabel: "At home", speaker: "A", chinese: "它很漂亮。", pinyin: "Tā hěn piàoliang.", english: "It's beautiful." },
      { order: 16, dialogNumber: 4, dialogLabel: "At home", speaker: "B", chinese: "是啊，我觉得它的眼睛最漂亮。", pinyin: "Shì a, wǒ juéde tā de yǎnjīng zuì piàoliang.", english: "Yes. I think it has the most beautiful eyes." },
      { order: 17, dialogNumber: 4, dialogLabel: "At home", speaker: "A", chinese: "它多大了？", pinyin: "Tā duō dà le?", english: "How old is it?" },
      { order: 18, dialogNumber: 4, dialogLabel: "At home", speaker: "B", chinese: "六个多月。", pinyin: "Liù ge duō yuè.", english: "More than six months." },
    ],
  },
  {
    chapterNumber: 2,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "On the playground", speaker: "A", chinese: "你很少生病，是不是喜欢运动？", pinyin: "Nǐ hěn shǎo shēng bìng, shì bu shì xǐhuān yùndòng?", english: "You seldom get sick. I guess you like doing sports, don't you?" },
      { order: 2, dialogNumber: 1, dialogLabel: "On the playground", speaker: "B", chinese: "是啊，我每天早上都要出去跑步。", pinyin: "Shì a, wǒ měi tiān zǎoshang dōu yào chū qù pǎobù.", english: "Yes. I go out for a jog every morning." },
      { order: 3, dialogNumber: 1, dialogLabel: "On the playground", speaker: "A", chinese: "你每天几点起床？", pinyin: "Nǐ měi tiān jǐ diǎn qǐ chuáng?", english: "What time do you get up?" },
      { order: 4, dialogNumber: 1, dialogLabel: "On the playground", speaker: "B", chinese: "我每天六点起床。", pinyin: "Wǒ měi tiān liù diǎn qǐ chuáng.", english: "I get up at six every day." },
      { order: 5, dialogNumber: 2, dialogLabel: "In the hospital", speaker: "A", chinese: "吃药了吗？现在身体怎么样？", pinyin: "Chī yào le ma? Xiànzài shēntǐ zěnmeyàng?", english: "Did you take your medicine? How do you feel now?" },
      { order: 6, dialogNumber: 2, dialogLabel: "In the hospital", speaker: "B", chinese: "吃了。现在好多了。", pinyin: "Chī le. Xiànzài hǎo duō le.", english: "Yes, I did. I feel much better now." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the hospital", speaker: "A", chinese: "什么时候能出院？", pinyin: "Shénme shíhou néng chū yuàn?", english: "When can you leave the hospital?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In the hospital", speaker: "B", chinese: "医生说下个星期。", pinyin: "Yīshēng shuō xià ge xīngqī.", english: "Next week according to the doctor." },
      { order: 9, dialogNumber: 3, dialogLabel: "On the playground", speaker: "A", chinese: "大卫今年多大？", pinyin: "Dàwèi jīnnián duō dà?", english: "How old is David?" },
      { order: 10, dialogNumber: 3, dialogLabel: "On the playground", speaker: "B", chinese: "二十多岁。", pinyin: "Èrshí duō suì.", english: "Above 20 years old." },
      { order: 11, dialogNumber: 3, dialogLabel: "On the playground", speaker: "A", chinese: "他多高？", pinyin: "Tā duō gāo?", english: "How tall is he?" },
      { order: 12, dialogNumber: 3, dialogLabel: "On the playground", speaker: "B", chinese: "一米八几。", pinyin: "Yī mǐ bā jǐ.", english: "He is more than 180 centimeters tall." },
      { order: 13, dialogNumber: 3, dialogLabel: "On the playground", speaker: "A", chinese: "你怎么知道这么多啊？", pinyin: "Nǐ zěnme zhīdào zhème duō a?", english: "How come you know so much about him?" },
      { order: 14, dialogNumber: 3, dialogLabel: "On the playground", speaker: "B", chinese: "他是我同学。", pinyin: "Tā shì wǒ tóngxué.", english: "He is my classmate." },
      { order: 15, dialogNumber: 4, dialogLabel: "In the room", speaker: "A", chinese: "张老师星期六也不休息啊？", pinyin: "Zhāng lǎoshī xīngqī liù yě bù xiūxi a?", english: "Doesn't Mr. Zhang take Saturday off?" },
      { order: 16, dialogNumber: 4, dialogLabel: "In the room", speaker: "B", chinese: "是啊，他这几天很忙，没有时间休息。", pinyin: "Shì a, tā zhè jǐ tiān hěn máng, méiyǒu shíjiān xiūxi.", english: "No. He has been busy lately. He has no time to rest." },
      { order: 17, dialogNumber: 4, dialogLabel: "In the room", speaker: "A", chinese: "那会很累吧？", pinyin: "Nà huì hěn lèi ba?", english: "That must be really tiring." },
      { order: 18, dialogNumber: 4, dialogLabel: "In the room", speaker: "B", chinese: "他每天回来都很累。", pinyin: "Tā měi tiān huílái dōu hěn lèi.", english: "Every day he comes home exhausted." },
    ],
  },
  {
    chapterNumber: 3,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the room", speaker: "A", chinese: "这块手表是你的吗？", pinyin: "Zhè kuài shǒubiǎo shì nǐ de ma?", english: "Is this watch yours?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the room", speaker: "B", chinese: "不是我的。是我爸爸的。", pinyin: "Bú shì wǒ de. Shì wǒ bàba de.", english: "No, it isn't. It's my father's." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the room", speaker: "A", chinese: "多少钱买的？", pinyin: "Duōshao qián mǎi de?", english: "How much is it?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the room", speaker: "B", chinese: "三千多块。", pinyin: "Sānqiān duō kuài.", english: "More than 3,000 yuan." },
      { order: 5, dialogNumber: 2, dialogLabel: "At home", speaker: "A", chinese: "这是今天早上的报纸吗？", pinyin: "Zhè shì jīntiān zǎoshang de bàozhǐ ma?", english: "Is it this morning's newspaper?" },
      { order: 6, dialogNumber: 2, dialogLabel: "At home", speaker: "B", chinese: "不是，是昨天的。", pinyin: "Bú shì, shì zuótiān de.", english: "No, it isn't. It's yesterday's." },
      { order: 7, dialogNumber: 2, dialogLabel: "At home", speaker: "A", chinese: "你听，是不是送报纸的来了？", pinyin: "Nǐ tīng, shì bu shì sòng bàozhǐ de lái le?", english: "Listen. Is that the man who delivers newspapers?" },
      { order: 8, dialogNumber: 2, dialogLabel: "At home", speaker: "B", chinese: "我看一下。不是，是送牛奶的。", pinyin: "Wǒ kàn yíxià. Bú shì, shì sòng niúnǎi de.", english: "Let me see. No, it's the milkman." },
      { order: 9, dialogNumber: 3, dialogLabel: "At home", speaker: "A", chinese: "这是谁的房间？", pinyin: "Zhè shì shéi de fángjiān?", english: "Whose room is this?" },
      { order: 10, dialogNumber: 3, dialogLabel: "At home", speaker: "B", chinese: "这是我和我丈夫的，旁边那个小的房间是我女儿的。", pinyin: "Zhè shì wǒ hé wǒ zhàngfu de, pángbiān nàge xiǎo de fángjiān shì wǒ nǚ'ér de.", english: "It's my husband's and mine. The small one beside it is my daughter's." },
      { order: 11, dialogNumber: 3, dialogLabel: "At home", speaker: "A", chinese: "你女儿的房间真漂亮！都是粉色的。", pinyin: "Nǐ nǚ'ér de fángjiān zhēn piàoliang! Dōu shì fěnsè de.", english: "Your daughter's room is so pretty! It's all pink." },
      { order: 12, dialogNumber: 3, dialogLabel: "At home", speaker: "B", chinese: "是啊，粉色是我女儿最喜欢的颜色。", pinyin: "Shì a, fěnsè shì wǒ nǚ'ér zuì xǐhuān de yánsè.", english: "Yes. Pink is her favorite color." },
      { order: 13, dialogNumber: 4, dialogLabel: "In the office", speaker: "A", chinese: "你看见我的杯子了吗？", pinyin: "Nǐ kànjiàn wǒ de bēizi le ma?", english: "Have you seen my cup?" },
      { order: 14, dialogNumber: 4, dialogLabel: "In the office", speaker: "B", chinese: "这里有几个杯子，哪个是你的？", pinyin: "Zhèli yǒu jǐ ge bēizi, nǎge shì nǐ de?", english: "Here are a few cups. Which one is yours?" },
      { order: 15, dialogNumber: 4, dialogLabel: "In the office", speaker: "A", chinese: "左边那个红色的是我的。", pinyin: "Zuǒbiān nàge hóngsè de shì wǒ de.", english: "The red one on the left is mine." },
      { order: 16, dialogNumber: 4, dialogLabel: "In the office", speaker: "B", chinese: "给你。", pinyin: "Gěi nǐ.", english: "Here you are." },
    ],
  },
  {
    chapterNumber: 4,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "A", chinese: "生日快乐！这是送给你的！", pinyin: "Shēngrì kuàilè! Zhè shì sòng gěi nǐ de!", english: "Happy birthday! This is for you." },
      { order: 2, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "B", chinese: "是什么？是一本书吗？", pinyin: "Shì shénme? Shì yì běn shū ma?", english: "What is it? Is it a book?" },
      { order: 3, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "A", chinese: "对，这本书是我写的。", pinyin: "Duì, zhè běn shū shì wǒ xiě de.", english: "Yes. A book written by me." },
      { order: 4, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "B", chinese: "太谢谢你了！", pinyin: "Tài xièxie nǐ le!", english: "Thank you so much!" },
      { order: 5, dialogNumber: 2, dialogLabel: "At home", speaker: "A", chinese: "早上有你一个电话。", pinyin: "Zǎoshang yǒu nǐ yí ge diànhuà.", english: "Someone called you this morning." },
      { order: 6, dialogNumber: 2, dialogLabel: "At home", speaker: "B", chinese: "电话是谁打的？", pinyin: "Diànhuà shì shéi dǎ de?", english: "Who?" },
      { order: 7, dialogNumber: 2, dialogLabel: "At home", speaker: "A", chinese: "不知道，是儿子接的。", pinyin: "Bù zhīdào, shì érzi jiē de.", english: "I don't know. Our son answered it." },
      { order: 8, dialogNumber: 2, dialogLabel: "At home", speaker: "B", chinese: "好，晚上我问一下儿子。", pinyin: "Hǎo, wǎnshang wǒ wèn yíxià érzi.", english: "OK. I'll ask him about it this evening." },
      { order: 9, dialogNumber: 3, dialogLabel: "On the playground", speaker: "A", chinese: "你喜欢踢足球吗？", pinyin: "Nǐ xǐhuān tī zúqiú ma?", english: "Do you like playing football?" },
      { order: 10, dialogNumber: 3, dialogLabel: "On the playground", speaker: "B", chinese: "非常喜欢。", pinyin: "Fēicháng xǐhuān.", english: "Yes, very much." },
      { order: 11, dialogNumber: 3, dialogLabel: "On the playground", speaker: "A", chinese: "你是什么时候开始踢足球的？", pinyin: "Nǐ shì shénme shíhou kāishǐ tī zúqiú de?", english: "When did you begin to play football?" },
      { order: 12, dialogNumber: 3, dialogLabel: "On the playground", speaker: "B", chinese: "我十一岁的时候开始踢足球，已经踢了十年了。", pinyin: "Wǒ shíyī suì de shíhou kāishǐ tī zúqiú, yǐjīng tī le shí nián le.", english: "I was 11 when I played football for the first time. It has been 10 years." },
      { order: 13, dialogNumber: 4, dialogLabel: "In the office", speaker: "A", chinese: "你在这儿工作多长时间了？", pinyin: "Nǐ zài zhèr gōngzuò duō cháng shíjiān le?", english: "How long have you been working here?" },
      { order: 14, dialogNumber: 4, dialogLabel: "In the office", speaker: "B", chinese: "已经两年多了，我是2011年来的。", pinyin: "Yǐjīng liǎng nián duō le, wǒ shì èr líng yī yī nián lái de.", english: "More than two years, since 2011." },
      { order: 15, dialogNumber: 4, dialogLabel: "In the office", speaker: "A", chinese: "你认识谢先生吗？", pinyin: "Nǐ rènshi Xiè xiānsheng ma?", english: "Do you know Mr. Xie?" },
      { order: 16, dialogNumber: 4, dialogLabel: "In the office", speaker: "B", chinese: "认识，我们是大学同学，这个工作是他帮我介绍的。", pinyin: "Rènshi, wǒmen shì dàxué tóngxué, zhège gōngzuò shì tā bāng wǒ jièshào de.", english: "Yes. He is my college classmate. He recommended me for this job." },
    ],
  },
  {
    chapterNumber: 5,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "At home", speaker: "A", chinese: "晚上我们去饭馆吃饭，怎么样？", pinyin: "Wǎnshang wǒmen qù fànguǎn chī fàn, zěnmeyàng?", english: "Let's go to a restaurant for dinner. What do you think?" },
      { order: 2, dialogNumber: 1, dialogLabel: "At home", speaker: "B", chinese: "我不想去外面吃，我想在家吃。", pinyin: "Wǒ bù xiǎng qù wàimiàn chī, wǒ xiǎng zài jiā chī.", english: "I don't want to eat out. I want to eat at home." },
      { order: 3, dialogNumber: 1, dialogLabel: "At home", speaker: "A", chinese: "那你准备做什么呢？", pinyin: "Nà nǐ zhǔnbèi zuò shénme ne?", english: "What are you planning to cook?" },
      { order: 4, dialogNumber: 1, dialogLabel: "At home", speaker: "B", chinese: "就做你爱吃的鱼吧。", pinyin: "Jiù zuò nǐ ài chī de yú ba.", english: "I'm thinking of fish, your favorite." },
      { order: 5, dialogNumber: 2, dialogLabel: "In a store", speaker: "A", chinese: "帮我看一下这件衣服怎么样。", pinyin: "Bāng wǒ kàn yíxià zhè jiàn yīfu zěnmeyàng.", english: "What do you think of this garment?" },
      { order: 6, dialogNumber: 2, dialogLabel: "In a store", speaker: "B", chinese: "颜色还可以，就是有点儿大。", pinyin: "Yánsè hái kěyǐ, jiùshì yǒudiǎnr dà.", english: "The color is OK, but it seems too large." },
      { order: 7, dialogNumber: 2, dialogLabel: "In a store", speaker: "A", chinese: "这件小的怎么样？", pinyin: "Zhè jiàn xiǎo de zěnmeyàng?", english: "What about this small one?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In a store", speaker: "B", chinese: "这件不错，就买这件吧。", pinyin: "Zhè jiàn búcuò, jiù mǎi zhè jiàn ba.", english: "This one is good. Take this one." },
      { order: 9, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "A", chinese: "今天去不去打球？", pinyin: "Jīntiān qù bu qù dǎ qiú?", english: "Will you go to play the ball today?" },
      { order: 10, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "B", chinese: "这两天有点儿累，不去打球了。", pinyin: "Zhè liǎng tiān yǒudiǎnr lèi, bú qù dǎ qiú le.", english: "No, I won't. I've been feeling tired lately." },
      { order: 11, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "A", chinese: "你在做什么呢？是在想昨天的考试吗？", pinyin: "Nǐ zài zuò shénme ne? Shì zài xiǎng zuótiān de kǎoshì ma?", english: "What are you doing? Are you thinking about yesterday's test?" },
      { order: 12, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "B", chinese: "是啊，我觉得听和说还可以，读和写不好，很多字我都不知道是什么意思。", pinyin: "Shì a, wǒ juéde tīng hé shuō hái kěyǐ, dú hé xiě bù hǎo, hěn duō zì wǒ dōu bù zhīdào shì shénme yìsi.", english: "Yes. I think I did OK in listening and speaking, but not in reading and writing. I didn't know the meanings of many characters." },
      { order: 13, dialogNumber: 4, dialogLabel: "In the company", speaker: "A", chinese: "休息一下吧，喝咖啡吗？", pinyin: "Xiūxi yíxià ba, hē kāfēi ma?", english: "Let's take a rest. Would you like some coffee?" },
      { order: 14, dialogNumber: 4, dialogLabel: "In the company", speaker: "B", chinese: "不喝了，我已经喝两杯了。", pinyin: "Bù hē le, wǒ yǐjīng hē liǎng bēi le.", english: "No, thanks. I've already had two cups." },
      { order: 15, dialogNumber: 4, dialogLabel: "In the company", speaker: "A", chinese: "是啊，咖啡喝多了对身体不好。", pinyin: "Shì a, kāfēi hē duō le duì shēntǐ bù hǎo.", english: "Right. Too much coffee is bad for our health." },
      { order: 16, dialogNumber: 4, dialogLabel: "In the company", speaker: "B", chinese: "以后我少喝一点儿，每天喝一杯。", pinyin: "Yǐhòu wǒ shǎo hē yìdiǎnr, měi tiān hē yì bēi.", english: "I'll drink less coffee. One cup a day." },
    ],
  },
  {
    chapterNumber: 6,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the school", speaker: "A", chinese: "你知道小王今天什么时候来学校吗？", pinyin: "Nǐ zhīdào Xiǎo Wáng jīntiān shénme shíhou lái xuéxiào ma?", english: "Do you know when Xiao Wang will come to school today?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the school", speaker: "B", chinese: "他已经来了。", pinyin: "Tā yǐjīng lái le.", english: "He is already here." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the school", speaker: "A", chinese: "你怎么知道他来了？", pinyin: "Nǐ zěnme zhīdào tā lái le?", english: "How do you know?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the school", speaker: "B", chinese: "我在门外看见他的自行车了。", pinyin: "Wǒ zài mén wài kànjiàn tā de zìxíngchē le.", english: "I saw his bike outside the door." },
      { order: 5, dialogNumber: 2, dialogLabel: "In a restaurant", speaker: "A", chinese: "今天的羊肉很好吃，你怎么不吃了？", pinyin: "Jīntiān de yángròu hěn hǎochī, nǐ zěnme bù chī le?", english: "The mutton today is excellent. Why don't you eat more?" },
      { order: 6, dialogNumber: 2, dialogLabel: "In a restaurant", speaker: "B", chinese: "这个星期天天都吃羊肉，不想吃了。", pinyin: "Zhège xīngqī tiāntiān dōu chī yángròu, bù xiǎng chī le.", english: "I eat mutton every day this week. I don't want to eat it any more." },
      { order: 7, dialogNumber: 2, dialogLabel: "In a restaurant", speaker: "A", chinese: "那你还想吃什么？", pinyin: "Nà nǐ hái xiǎng chī shénme?", english: "What would you like then?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In a restaurant", speaker: "B", chinese: "来一点儿面条吧。", pinyin: "Lái yìdiǎnr miàntiáo ba.", english: "Some noodles please." },
      { order: 9, dialogNumber: 3, dialogLabel: "On the playground", speaker: "A", chinese: "昨天你们怎么都没去打篮球？", pinyin: "Zuótiān nǐmen zěnme dōu méi qù dǎ lánqiú?", english: "Why didn't you guys go to play basketball yesterday?" },
      { order: 10, dialogNumber: 3, dialogLabel: "On the playground", speaker: "B", chinese: "因为昨天下雨，所以我们都没去。", pinyin: "Yīnwèi zuótiān xià yǔ, suǒyǐ wǒmen dōu méi qù.", english: "Because it rained yesterday." },
      { order: 11, dialogNumber: 3, dialogLabel: "On the playground", speaker: "A", chinese: "我去游泳了。", pinyin: "Wǒ qù yóuyǒng le.", english: "I went swimming." },
      { order: 12, dialogNumber: 3, dialogLabel: "On the playground", speaker: "B", chinese: "你经常游泳吗？", pinyin: "Nǐ jīngcháng yóuyǒng ma?", english: "Do you often swim?" },
      { order: 13, dialogNumber: 3, dialogLabel: "On the playground", speaker: "A", chinese: "这个月我天天游泳，我现在七十公斤了。", pinyin: "Zhège yuè wǒ tiāntiān yóuyǒng, wǒ xiànzài qīshí gōngjīn le.", english: "I swim every day this month. I weigh 70 kilograms now." },
      { order: 14, dialogNumber: 4, dialogLabel: "In the office", speaker: "A", chinese: "这两天怎么没看见小张？", pinyin: "Zhè liǎng tiān zěnme méi kànjiàn Xiǎo Zhāng?", english: "I haven't seen Xiao Zhang for days. What's going on?" },
      { order: 15, dialogNumber: 4, dialogLabel: "In the office", speaker: "B", chinese: "他去北京了。", pinyin: "Tā qù Běijīng le.", english: "He has gone to Beijing." },
      { order: 16, dialogNumber: 4, dialogLabel: "In the office", speaker: "A", chinese: "去北京了？是去旅游吗？", pinyin: "Qù Běijīng le? Shì qù lǚyóu ma?", english: "Gone to Beijing? For traveling?" },
      { order: 17, dialogNumber: 4, dialogLabel: "In the office", speaker: "B", chinese: "不是，听说是去看他姐姐。", pinyin: "Bú shì, tīngshuō shì qù kàn tā jiějie.", english: "No. Visiting his elder sister, as far as I've heard." },
    ],
  },
  {
    chapterNumber: 7,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "At home", speaker: "A", chinese: "大卫回来了吗？", pinyin: "Dàwèi huílái le ma?", english: "Is David back?" },
      { order: 2, dialogNumber: 1, dialogLabel: "At home", speaker: "B", chinese: "没有，他还在教室学习呢。", pinyin: "Méiyǒu, tā hái zài jiàoshì xuéxí ne.", english: "No. He is still studying in the classroom." },
      { order: 3, dialogNumber: 1, dialogLabel: "At home", speaker: "A", chinese: "已经9点多了，他怎么还在学习？", pinyin: "Yǐjīng jiǔ diǎn duō le, tā zěnme hái zài xuéxí?", english: "It's after 9 o'clock. Why is he still studying?" },
      { order: 4, dialogNumber: 1, dialogLabel: "At home", speaker: "B", chinese: "明天有考试，他说今天要好好准备。", pinyin: "Míngtiān yǒu kǎoshì, tā shuō jīntiān yào hǎohǎo zhǔnbèi.", english: "There will be a test tomorrow. He said he'll work hard in preparation for it today." },
      { order: 5, dialogNumber: 2, dialogLabel: "On the way to the airport", speaker: "A", chinese: "你现在在哪儿呢？", pinyin: "Nǐ xiànzài zài nǎr ne?", english: "Where are you now?" },
      { order: 6, dialogNumber: 2, dialogLabel: "On the way to the airport", speaker: "B", chinese: "在去机场的路上。你已经到了吗？", pinyin: "Zài qù jīchǎng de lùshang. Nǐ yǐjīng dào le ma?", english: "I'm on the way to the airport. Have you arrived?" },
      { order: 7, dialogNumber: 2, dialogLabel: "On the way to the airport", speaker: "A", chinese: "我下飞机了。你还有多长时间能到这儿？", pinyin: "Wǒ xià fēijī le. Nǐ hái yǒu duō cháng shíjiān néng dào zhèr?", english: "I've got off the plane. How many more minutes do you need to get here?" },
      { order: 8, dialogNumber: 2, dialogLabel: "On the way to the airport", speaker: "B", chinese: "二十分钟就到。", pinyin: "Èrshí fēnzhōng jiù dào.", english: "In 20 minutes." },
      { order: 9, dialogNumber: 3, dialogLabel: "In the gym", speaker: "A", chinese: "你家离公司远吗？", pinyin: "Nǐ jiā lí gōngsī yuǎn ma?", english: "Do you live far from your company?" },
      { order: 10, dialogNumber: 3, dialogLabel: "In the gym", speaker: "B", chinese: "很远，坐公共汽车要一个多小时呢！", pinyin: "Hěn yuǎn, zuò gōnggòng qìchē yào yí ge duō xiǎoshí ne!", english: "Yes, very far. It takes more than one hour by bus." },
      { order: 11, dialogNumber: 3, dialogLabel: "In the gym", speaker: "A", chinese: "坐公共汽车太慢了，你怎么不开车？", pinyin: "Zuò gōnggòng qìchē tài màn le, nǐ zěnme bù kāi chē?", english: "Buses are slow. Why don't you drive?" },
      { order: 12, dialogNumber: 3, dialogLabel: "In the gym", speaker: "B", chinese: "开车也不快，路上车太多了！", pinyin: "Kāi chē yě bù kuài, lùshang chē tài duō le!", english: "It's not fast either. There are too many cars on the road." },
      { order: 13, dialogNumber: 4, dialogLabel: "On the way", speaker: "A", chinese: "今天晚上我们一起吃饭吧，给你过生日。", pinyin: "Jīntiān wǎnshang wǒmen yìqǐ chī fàn ba, gěi nǐ guò shēngrì.", english: "Let's have dinner together tonight to celebrate your birthday." },
      { order: 14, dialogNumber: 4, dialogLabel: "On the way", speaker: "B", chinese: "今天？离我的生日还有一个多星期呢！", pinyin: "Jīntiān? Lí wǒ de shēngrì hái yǒu yí ge duō xīngqī ne!", english: "Tonight? My birthday is more than one week later." },
      { order: 15, dialogNumber: 4, dialogLabel: "On the way", speaker: "A", chinese: "下个星期我要去北京，今天过吧。", pinyin: "Xià ge xīngqī wǒ yào qù Běijīng, jīntiān guò ba.", english: "Next week I'll go to Beijing. Let's celebrate it today." },
      { order: 16, dialogNumber: 4, dialogLabel: "On the way", speaker: "B", chinese: "好吧，离这儿不远有一个中国饭馆，走几分钟就到了。", pinyin: "Hǎo ba, lí zhèr bù yuǎn yǒu yí ge Zhōngguó fànguǎn, zǒu jǐ fēnzhōng jiù dào le.", english: "Fine. There's a Chinese restaurant nearby, only a few minutes' walk away." },
    ],
  },
  {
    chapterNumber: 8,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "A", chinese: "我们下午去看电影，好吗？", pinyin: "Wǒmen xiàwǔ qù kàn diànyǐng, hǎo ma?", english: "Let's go to see a movie this afternoon, shall we?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "B", chinese: "今天下午我没有时间，明天下午再去吧。", pinyin: "Jīntiān xiàwǔ wǒ méiyǒu shíjiān, míngtiān xiàwǔ zài qù ba.", english: "I'm not free this afternoon. Let's go tomorrow afternoon." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "A", chinese: "你想看什么电影？", pinyin: "Nǐ xiǎng kàn shénme diànyǐng?", english: "Which movie would you like to see?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "B", chinese: "让我想想再告诉你。", pinyin: "Ràng wǒ xiǎngxiǎng zài gàosu nǐ.", english: "Let me think about it and I'll tell you later." },
      { order: 5, dialogNumber: 2, dialogLabel: "In the dorm", speaker: "A", chinese: "外边天气很好，我们出去运动运动吧！", pinyin: "Wàibiān tiānqì hěn hǎo, wǒmen chūqù yùndòng yùndòng ba!", english: "It's a nice day outside. Let's go out to do some exercise." },
      { order: 6, dialogNumber: 2, dialogLabel: "In the dorm", speaker: "B", chinese: "你等等我，好吗？王老师让我给大卫打个电话。", pinyin: "Nǐ děngdeng wǒ, hǎo ma? Wáng lǎoshī ràng wǒ gěi Dàwèi dǎ ge diànhuà.", english: "Please wait for me for a minute, will you? Professor Wang asked me to give David a call." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the dorm", speaker: "A", chinese: "回来再打吧。找大卫有什么事情吗？", pinyin: "Huílái zài dǎ ba. Zhǎo Dàwèi yǒu shénme shìqing ma?", english: "Call him after we come back. What's the matter?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In the dorm", speaker: "B", chinese: "听说大卫病了，我想找时间去看看他。", pinyin: "Tīngshuō Dàwèi bìng le, wǒ xiǎng zhǎo shíjiān qù kànkan tā.", english: "I heard that David is sick. I want to visit him sometime." },
      { order: 9, dialogNumber: 3, dialogLabel: "At the front desk of a hotel", speaker: "A", chinese: "服务员，我房间的门打不开了。", pinyin: "Fúwùyuán, wǒ fángjiān de mén dǎ bù kāi le.", english: "Excuse me, I can't open my door." },
      { order: 10, dialogNumber: 3, dialogLabel: "At the front desk of a hotel", speaker: "B", chinese: "您住哪个房间？", pinyin: "Nín zhù nǎge fángjiān?", english: "Which room do you stay in?" },
      { order: 11, dialogNumber: 3, dialogLabel: "At the front desk of a hotel", speaker: "A", chinese: "317。", pinyin: "Sān yāo qī.", english: "Room 317." },
      { order: 12, dialogNumber: 3, dialogLabel: "At the front desk of a hotel", speaker: "B", chinese: "好的，我叫人去看看。", pinyin: "Hǎo de, wǒ jiào rén qù kànkan.", english: "OK. I'll send someone to have a check." },
      { order: 13, dialogNumber: 4, dialogLabel: "In a store", speaker: "A", chinese: "你看看这几件衣服怎么样。", pinyin: "Nǐ kànkan zhè jǐ jiàn yīfu zěnmeyàng.", english: "What do you think of these dresses?" },
      { order: 14, dialogNumber: 4, dialogLabel: "In a store", speaker: "B", chinese: "这件白的有点儿长，那件黑的有点儿贵。", pinyin: "Zhè jiàn bái de yǒudiǎnr cháng, nà jiàn hēi de yǒudiǎnr guì.", english: "This white one is a little bit too long. That black one is a bit expensive." },
      { order: 15, dialogNumber: 4, dialogLabel: "In a store", speaker: "A", chinese: "这件红的呢？这是今天新来的。", pinyin: "Zhè jiàn hóng de ne? Zhè shì jīntiān xīn lái de.", english: "What about this red one? This one has just got here today." },
      { order: 16, dialogNumber: 4, dialogLabel: "In a store", speaker: "B", chinese: "让我再看看。", pinyin: "Ràng wǒ zài kànkan.", english: "Let me look around again." },
    ],
  },
  {
    chapterNumber: 9,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "On the phone", speaker: "A", chinese: "你好！请问张欢在吗？", pinyin: "Nǐ hǎo! Qǐngwèn Zhāng Huān zài ma?", english: "Hello! May I speak to Zhang Huan?" },
      { order: 2, dialogNumber: 1, dialogLabel: "On the phone", speaker: "B", chinese: "你打错了，我们这儿没有叫张欢的。", pinyin: "Nǐ dǎ cuò le, wǒmen zhèr méiyǒu jiào Zhāng Huān de.", english: "You've got the wrong number. There isn't a person called Zhang Huan here." },
      { order: 3, dialogNumber: 1, dialogLabel: "On the phone", speaker: "A", chinese: "对不起。", pinyin: "Duìbuqǐ.", english: "I'm sorry." },
      { order: 4, dialogNumber: 2, dialogLabel: "In the school", speaker: "A", chinese: "您从几岁开始学习跳舞？", pinyin: "Nín cóng jǐ suì kāishǐ xuéxí tiàowǔ?", english: "At what age did you start to learn dancing?" },
      { order: 5, dialogNumber: 2, dialogLabel: "In the school", speaker: "B", chinese: "我第一次跳舞是在七岁的时候。", pinyin: "Wǒ dì yī cì tiàowǔ shì zài qī suì de shíhou.", english: "I was seven when I danced for the first time." },
      { order: 6, dialogNumber: 2, dialogLabel: "In the school", speaker: "A", chinese: "我女儿今年也七岁了。我希望她能跟您学跳舞，可以吗？", pinyin: "Wǒ nǚ'ér jīnnián yě qī suì le. Wǒ xīwàng tā néng gēn nín xué tiàowǔ, kěyǐ ma?", english: "My daughter is seven now. I hope she can learn to dance from you, can she?" },
      { order: 7, dialogNumber: 2, dialogLabel: "In the school", speaker: "B", chinese: "没问题，非常欢迎。", pinyin: "Méi wèntí, fēicháng huānyíng.", english: "Sure. It's my pleasure." },
      { order: 8, dialogNumber: 3, dialogLabel: "At home", speaker: "A", chinese: "你知道吗？大卫找到工作了。", pinyin: "Nǐ zhīdào ma? Dàwèi zhǎodào gōngzuò le.", english: "You know what? David has got a job." },
      { order: 9, dialogNumber: 3, dialogLabel: "At home", speaker: "B", chinese: "太好了！他从什么时候开始上班？", pinyin: "Tài hǎo le! Tā cóng shénme shíhou kāishǐ shàngbān?", english: "That's great! When will he start to work?" },
      { order: 10, dialogNumber: 3, dialogLabel: "At home", speaker: "A", chinese: "从下个星期一开始。", pinyin: "Cóng xià ge xīngqī yī kāishǐ.", english: "Next Monday." },
      { order: 11, dialogNumber: 3, dialogLabel: "At home", speaker: "B", chinese: "这是他的第一个工作，希望他能喜欢。", pinyin: "Zhè shì tā de dì yī ge gōngzuò, xīwàng tā néng xǐhuān.", english: "This is his first job. I hope he will like it." },
      { order: 12, dialogNumber: 4, dialogLabel: "In the classroom", speaker: "A", chinese: "昨天的考试怎么样？你都听懂了吗？", pinyin: "Zuótiān de kǎoshì zěnmeyàng? Nǐ dōu tīngdǒng le ma?", english: "How was the test yesterday? Did you understand everything you heard?" },
      { order: 13, dialogNumber: 4, dialogLabel: "In the classroom", speaker: "B", chinese: "听懂了。", pinyin: "Tīngdǒng le.", english: "Yes, I did." },
      { order: 14, dialogNumber: 4, dialogLabel: "In the classroom", speaker: "A", chinese: "你都做完了没有？", pinyin: "Nǐ dōu zuòwán le méiyǒu?", english: "Did you finish the test paper?" },
      { order: 15, dialogNumber: 4, dialogLabel: "In the classroom", speaker: "B", chinese: "题太多，我没做完。", pinyin: "Tí tài duō, wǒ méi zuòwán.", english: "There were too many questions, I didn't finish all of them." },
    ],
  },
  {
    chapterNumber: 10,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "At home", speaker: "A", chinese: "不要看电视了，明天上午还有汉语课呢。", pinyin: "Búyào kàn diànshì le, míngtiān shàngwǔ hái yǒu Hànyǔ kè ne.", english: "Stop watching TV. You'll have a Chinese class tomorrow morning." },
      { order: 2, dialogNumber: 1, dialogLabel: "At home", speaker: "B", chinese: "看电视对学汉语有帮助。", pinyin: "Kàn diànshì duì xué Hànyǔ yǒu bāngzhù.", english: "Watching TV is good for Chinese learning." },
      { order: 3, dialogNumber: 1, dialogLabel: "At home", speaker: "A", chinese: "明天的课你都准备好了吗？", pinyin: "Míngtiān de kè nǐ dōu zhǔnbèi hǎo le ma?", english: "Are you well prepared for the lessons tomorrow?" },
      { order: 4, dialogNumber: 1, dialogLabel: "At home", speaker: "B", chinese: "都准备好了。", pinyin: "Dōu zhǔnbèi hǎo le.", english: "Yes, I am." },
      { order: 5, dialogNumber: 2, dialogLabel: "In the hospital", speaker: "A", chinese: "别看报纸了，医生说你要多休息。", pinyin: "Bié kàn bàozhǐ le, yīshēng shuō nǐ yào duō xiūxi.", english: "Stop reading the newspaper. The doctor said you need more rest." },
      { order: 6, dialogNumber: 2, dialogLabel: "In the hospital", speaker: "B", chinese: "好，不看了。给我一杯茶吧。", pinyin: "Hǎo, bù kàn le. Gěi wǒ yì bēi chá ba.", english: "OK. Give me a cup of tea." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the hospital", speaker: "A", chinese: "医生说吃药后两个小时不要喝茶。", pinyin: "Yīshēng shuō chī yào hòu liǎng ge xiǎoshí búyào hē chá.", english: "The doctor said you shouldn't drink tea during the first two hours after you've taken the medicine." },
      { order: 8, dialogNumber: 2, dialogLabel: "In the hospital", speaker: "B", chinese: "医生还说什么了？", pinyin: "Yīshēng hái shuō shénme le?", english: "What else did the doctor say?" },
      { order: 9, dialogNumber: 2, dialogLabel: "In the hospital", speaker: "A", chinese: "医生让你听我的。", pinyin: "Yīshēng ràng nǐ tīng wǒ de.", english: "The doctor said you should listen to me." },
      { order: 10, dialogNumber: 3, dialogLabel: "At home", speaker: "A", chinese: "你怎么买了这么多东西啊？", pinyin: "Nǐ zěnme mǎi le zhème duō dōngxi a?", english: "Why did you buy so many things?" },
      { order: 11, dialogNumber: 3, dialogLabel: "At home", speaker: "B", chinese: "哥哥今天中午回来吃饭。", pinyin: "Gēge jīntiān zhōngwǔ huílái chī fàn.", english: "Our elder brother will come back to have lunch." },
      { order: 12, dialogNumber: 3, dialogLabel: "At home", speaker: "A", chinese: "我看看买什么了。羊肉、鸡蛋、面条、西瓜……真不少！妈妈呢？", pinyin: "Wǒ kànkan mǎi shénme le. Yángròu, jīdàn, miàntiáo, xīguā... zhēn bù shǎo! Māma ne?", english: "Let me see. Mutton, eggs, noodles, watermelon... That's a lot! Where is Mom?" },
      { order: 13, dialogNumber: 3, dialogLabel: "At home", speaker: "B", chinese: "正在准备午饭呢！", pinyin: "Zhèngzài zhǔnbèi wǔfàn ne!", english: "She is preparing lunch!" },
      { order: 14, dialogNumber: 4, dialogLabel: "At home", speaker: "A", chinese: "你在找什么？", pinyin: "Nǐ zài zhǎo shénme?", english: "What are you looking for?" },
      { order: 15, dialogNumber: 4, dialogLabel: "At home", speaker: "B", chinese: "你看见我的手机了吗？白色的。", pinyin: "Nǐ kànjiàn wǒ de shǒujī le ma? Báisè de.", english: "Have you seen my cell phone? It's white." },
      { order: 16, dialogNumber: 4, dialogLabel: "At home", speaker: "A", chinese: "别找了，手机在桌子上呢，电脑旁边。", pinyin: "Bié zhǎo le, shǒujī zài zhuōzi shang ne, diànnǎo pángbiān.", english: "Stop looking for your cell phone. It's on the desk, beside the computer." },
      { order: 17, dialogNumber: 4, dialogLabel: "At home", speaker: "B", chinese: "你看见我的衣服了吗？红色的那件。", pinyin: "Nǐ kànjiàn wǒ de yīfu le ma? Hóngsè de nà jiàn.", english: "Have you seen my garment? The red one." },
      { order: 18, dialogNumber: 4, dialogLabel: "At home", speaker: "A", chinese: "那件衣服我帮你洗了，在外边呢。", pinyin: "Nà jiàn yīfu wǒ bāng nǐ xǐ le, zài wàibiān ne.", english: "I have washed it for you. It's hung outside." },
    ],
  },
  {
    chapterNumber: 11,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In a karaoke bar", speaker: "A", chinese: "王方，昨天和你一起唱歌的人是谁？", pinyin: "Wáng Fāng, zuótiān hé nǐ yìqǐ chànggē de rén shì shéi?", english: "Wang Fang, who was the guy with you in the karaoke yesterday?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In a karaoke bar", speaker: "B", chinese: "一个朋友。", pinyin: "Yí ge péngyou.", english: "A friend." },
      { order: 3, dialogNumber: 1, dialogLabel: "In a karaoke bar", speaker: "A", chinese: "什么朋友？是不是男朋友？", pinyin: "Shénme péngyou? Shì bu shì nánpéngyou?", english: "What friend? Boyfriend?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In a karaoke bar", speaker: "B", chinese: "不是不是，我同学介绍的，昨天第一次见。", pinyin: "Bú shì bú shì, wǒ tóngxué jièshào de, zuótiān dì yī cì jiàn.", english: "No. My classmate set me up with him. We met only yesterday." },
      { order: 5, dialogNumber: 2, dialogLabel: "In the dorm", speaker: "A", chinese: "左边这个看报纸的女孩子是你姐姐吗？", pinyin: "Zuǒbiān zhège kàn bàozhǐ de nǚ háizi shì nǐ jiějie ma?", english: "Is the girl on the left reading a newspaper your elder sister?" },
      { order: 6, dialogNumber: 2, dialogLabel: "In the dorm", speaker: "B", chinese: "是，右边写字的那个人是我哥哥。", pinyin: "Shì, yòubiān xiě zì de nàge rén shì wǒ gēge.", english: "Yes. And the guy on the right writing is my elder brother." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the dorm", speaker: "A", chinese: "你哥哥多大？", pinyin: "Nǐ gēge duō dà?", english: "How old is he?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In the dorm", speaker: "B", chinese: "25岁，他比我大三岁。", pinyin: "Èrshíwǔ suì, tā bǐ wǒ dà sān suì.", english: "25. He is three years older than me." },
      { order: 9, dialogNumber: 3, dialogLabel: "At the market", speaker: "A", chinese: "今天的西瓜怎么卖？", pinyin: "Jīntiān de xīguā zěnme mài?", english: "What's the price of watermelons today?" },
      { order: 10, dialogNumber: 3, dialogLabel: "At the market", speaker: "B", chinese: "三块五一斤。", pinyin: "Sān kuài wǔ yì jīn.", english: "Three yuan and a half per 500 grams." },
      { order: 11, dialogNumber: 3, dialogLabel: "At the market", speaker: "A", chinese: "比昨天便宜。", pinyin: "Bǐ zuótiān piányi.", english: "It's cheaper than the price yesterday." },
      { order: 12, dialogNumber: 3, dialogLabel: "At the market", speaker: "B", chinese: "是，苹果也比昨天便宜一些。您来点儿吧。", pinyin: "Shì, píngguǒ yě bǐ zuótiān piányi yìxiē. Nín lái diǎnr ba.", english: "Yes. The apples are also cheaper. Why not take some?" },
      { order: 13, dialogNumber: 4, dialogLabel: "In the school", speaker: "A", chinese: "前边说话的那个人就是我的汉语老师。你可能不认识她。", pinyin: "Qiánbiān shuōhuà de nàge rén jiù shì wǒ de Hànyǔ lǎoshī. Nǐ kěnéng bú rènshi tā.", english: "The woman speaking in front of us is my Chinese teacher. You may not know her." },
      { order: 14, dialogNumber: 4, dialogLabel: "In the school", speaker: "B", chinese: "是新来的汉语老师吗？", pinyin: "Shì xīn lái de Hànyǔ lǎoshī ma?", english: "Is she a new-comer?" },
      { order: 15, dialogNumber: 4, dialogLabel: "In the school", speaker: "A", chinese: "是去年来的，她姓王，28岁。", pinyin: "Shì qùnián lái de, tā xìng Wáng, èrshíbā suì.", english: "She came here last year. Her family name is Wang, 28 years old." },
      { order: 16, dialogNumber: 4, dialogLabel: "In the school", speaker: "B", chinese: "她比我们老师小两岁。", pinyin: "Tā bǐ wǒmen lǎoshī xiǎo liǎng suì.", english: "She is two years younger than my teacher." },
    ],
  },
  {
    chapterNumber: 12,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "A", chinese: "你每天早上几点起床？", pinyin: "Nǐ měi tiān zǎoshang jǐ diǎn qǐ chuáng?", english: "When do you get up every morning?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "B", chinese: "六点多。", pinyin: "Liù diǎn duō.", english: "A few minutes past six." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "A", chinese: "你比我早起一个小时。", pinyin: "Nǐ bǐ wǒ zǎo qǐ yí ge xiǎoshí.", english: "You get up one hour earlier than I do." },
      { order: 4, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "B", chinese: "我睡得也早，我每天晚上十点就睡觉。早睡早起身体好。", pinyin: "Wǒ shuì de yě zǎo, wǒ měi tiān wǎnshang shí diǎn jiù shuìjiào. Zǎo shuì zǎo qǐ shēntǐ hǎo.", english: "I go to bed early also, at 10 o'clock every night. It's healthy to keep early hours." },
      { order: 5, dialogNumber: 2, dialogLabel: "At a friend's home", speaker: "A", chinese: "再来点儿米饭吧，你吃得太少了。", pinyin: "Zài lái diǎnr mǐfàn ba, nǐ chī de tài shǎo le.", english: "Have more rice, please. You ate too little." },
      { order: 6, dialogNumber: 2, dialogLabel: "At a friend's home", speaker: "B", chinese: "不少了，今天吃得很好，太谢谢你了。", pinyin: "Bù shǎo le, jīntiān chī de hěn hǎo, tài xièxie nǐ le.", english: "Not a little actually. I've enjoyed the meal a lot. Thank you so much." },
      { order: 7, dialogNumber: 2, dialogLabel: "At a friend's home", speaker: "A", chinese: "你做饭做得怎么样？", pinyin: "Nǐ zuò fàn zuò de zěnmeyàng?", english: "How well can you cook?" },
      { order: 8, dialogNumber: 2, dialogLabel: "At a friend's home", speaker: "B", chinese: "不怎么样，我妻子比我做得好。", pinyin: "Bù zěnmeyàng, wǒ qīzi bǐ wǒ zuò de hǎo.", english: "Not very well. My wife is a better cook than I am." },
      { order: 9, dialogNumber: 3, dialogLabel: "Outside", speaker: "A", chinese: "下雪了，今天真冷。", pinyin: "Xià xuě le, jīntiān zhēn lěng.", english: "It's snowing. It's really cold today." },
      { order: 10, dialogNumber: 3, dialogLabel: "Outside", speaker: "B", chinese: "有零下10度吧？", pinyin: "Yǒu líng xià shí dù ba?", english: "The temperature may be 10 degrees below zero, am I right?" },
      { order: 11, dialogNumber: 3, dialogLabel: "Outside", speaker: "A", chinese: "是啊，你穿得太少了，我们进房间吧。", pinyin: "Shì a, nǐ chuān de tài shǎo le, wǒmen jìn fángjiān ba.", english: "Yes. You wear too little. Let's go inside the house, OK?" },
      { order: 12, dialogNumber: 3, dialogLabel: "Outside", speaker: "B", chinese: "好吧。", pinyin: "Hǎo ba.", english: "OK." },
      { order: 13, dialogNumber: 4, dialogLabel: "At home", speaker: "A", chinese: "你在忙什么呢？", pinyin: "Nǐ zài máng shénme ne?", english: "What are you busy with?" },
      { order: 14, dialogNumber: 4, dialogLabel: "At home", speaker: "B", chinese: "我弟弟让我帮他找个房子，现在他家离公司有点儿远。", pinyin: "Wǒ dìdi ràng wǒ bāng tā zhǎo ge fángzi, xiànzài tā jiā lí gōngsī yǒudiǎnr yuǎn.", english: "My younger brother asked me to find an apartment for him. He now lives far from the company." },
      { order: 15, dialogNumber: 4, dialogLabel: "At home", speaker: "A", chinese: "住得远真的很累！", pinyin: "Zhù de yuǎn zhēn de hěn lèi!", english: "It's really exhausting to live far." },
      { order: 16, dialogNumber: 4, dialogLabel: "At home", speaker: "B", chinese: "是啊，他也希望能住得近一点儿。", pinyin: "Shì a, tā yě xīwàng néng zhù de jìn yìdiǎnr.", english: "It's true. He also wants to live nearer." },
    ],
  },
  {
    chapterNumber: 13,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the office", speaker: "A", chinese: "门开着呢，请进。", pinyin: "Mén kāi zhe ne, qǐng jìn.", english: "The door is open. Come on in." },
      { order: 2, dialogNumber: 1, dialogLabel: "In the office", speaker: "B", chinese: "请问，张先生在吗？", pinyin: "Qǐngwèn, Zhāng xiānsheng zài ma?", english: "Excuse me, is Mr. Zhang in?" },
      { order: 3, dialogNumber: 1, dialogLabel: "In the office", speaker: "A", chinese: "他出去了。你下午再来吧。", pinyin: "Tā chūqù le. Nǐ xiàwǔ zài lái ba.", english: "He's gone out. Please come in the afternoon." },
      { order: 4, dialogNumber: 1, dialogLabel: "In the office", speaker: "B", chinese: "好的，谢谢！", pinyin: "Hǎo de, xièxie!", english: "OK. Thank you!" },
      { order: 5, dialogNumber: 2, dialogLabel: "In the office", speaker: "A", chinese: "那个正在说话的女孩儿是谁？", pinyin: "Nàge zhèngzài shuōhuà de nǚháir shì shéi?", english: "Who is the girl speaking?" },
      { order: 6, dialogNumber: 2, dialogLabel: "In the office", speaker: "B", chinese: "我知道她的名字，她姓杨，叫杨笑笑，她姐姐是我同学。", pinyin: "Wǒ zhīdào tā de míngzi, tā xìng Yáng, jiào Yáng Xiàoxiào, tā jiějie shì wǒ tóngxué.", english: "I know her name. Her name is Yang Xiaoxiao. Yang is her family name. Her elder sister is my classmate." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the office", speaker: "A", chinese: "那个手里拿着铅笔的呢？", pinyin: "Nàge shǒu li ná zhe qiānbǐ de ne?", english: "What about the girl with a pencil in her hand?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In the office", speaker: "B", chinese: "我不认识。", pinyin: "Wǒ bú rènshi.", english: "That one I don't know." },
      { order: 9, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "A", chinese: "听说你有女朋友了？我认识她吗？", pinyin: "Tīngshuō nǐ yǒu nǚpéngyou le? Wǒ rènshi tā ma?", english: "I heard you have a girlfriend now? Do I know her?" },
      { order: 10, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "B", chinese: "就是我们班那个长着两个大眼睛，非常爱笑的女孩儿。", pinyin: "Jiù shì wǒmen bān nàge zhǎng zhe liǎng ge dà yǎnjīng, fēicháng ài xiào de nǚháir.", english: "She is the girl in our class with big eyes and a smiling face." },
      { order: 11, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "A", chinese: "她不是有男朋友吗？", pinyin: "Tā bú shì yǒu nánpéngyou ma?", english: "She's already got a boyfriend, hasn't she?" },
      { order: 12, dialogNumber: 3, dialogLabel: "In the classroom", speaker: "B", chinese: "那个已经是她的前男友了。", pinyin: "Nàge yǐjīng shì tā de qián nányǒu le.", english: "That's her ex now." },
      { order: 13, dialogNumber: 4, dialogLabel: "On the road", speaker: "A", chinese: "请问，这儿离新京宾馆远吗？", pinyin: "Qǐngwèn, zhèr lí Xīnjīng bīnguǎn yuǎn ma?", english: "Excuse me, is Xinjing Hotel far away from here?" },
      { order: 14, dialogNumber: 4, dialogLabel: "On the road", speaker: "B", chinese: "不远，走路二十分钟就到。", pinyin: "Bù yuǎn, zǒu lù èrshí fēnzhōng jiù dào.", english: "No, it's about a 20 minutes' walk." },
      { order: 15, dialogNumber: 4, dialogLabel: "On the road", speaker: "A", chinese: "你能告诉我怎么走吗？", pinyin: "Nǐ néng gàosu wǒ zěnme zǒu ma?", english: "Could you tell me how to get there?" },
      { order: 16, dialogNumber: 4, dialogLabel: "On the road", speaker: "B", chinese: "从这儿一直往前走，到了前面的路口再往右走。", pinyin: "Cóng zhèr yìzhí wǎng qián zǒu, dào le qiánmiàn de lùkǒu zài wǎng yòu zǒu.", english: "Walk straight ahead from here and turn right at the first crossing." },
    ],
  },
  {
    chapterNumber: 14,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "A", chinese: "你看过那个电影没有？", pinyin: "Nǐ kànguo nàge diànyǐng méiyǒu?", english: "Have you seen that movie?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "B", chinese: "没看过，听说很有意思。", pinyin: "Méi kànguo, tīngshuō hěn yǒu yìsi.", english: "No. I was told it is fantastic." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "A", chinese: "那我们下个星期一起去看吧？", pinyin: "Nà wǒmen xià ge xīngqī yìqǐ qù kàn ba?", english: "Why don't we see it together next week?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "B", chinese: "可以，但是我女朋友也想去。", pinyin: "Kěyǐ, dànshì wǒ nǚpéngyou yě xiǎng qù.", english: "OK. But my girlfriend also wants to go." },
      { order: 5, dialogNumber: 2, dialogLabel: "In the office", speaker: "A", chinese: "听说你去过中国，还想去吗？", pinyin: "Tīngshuō nǐ qùguo Zhōngguó, hái xiǎng qù ma?", english: "It's said you've been to China. Do you want to go there again?" },
      { order: 6, dialogNumber: 2, dialogLabel: "In the office", speaker: "B", chinese: "我虽然去过好几次，但是还想再去玩儿玩儿。", pinyin: "Wǒ suīrán qùguo hǎo jǐ cì, dànshì hái xiǎng zài qù wánr wánr.", english: "Though I've been there several times, I still want to go for pleasure again." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the office", speaker: "A", chinese: "那我们一起去吧。", pinyin: "Nà wǒmen yìqǐ qù ba.", english: "Let's go together." },
      { order: 8, dialogNumber: 2, dialogLabel: "In the office", speaker: "B", chinese: "好啊，到时候我给你打电话。", pinyin: "Hǎo a, dào shíhou wǒ gěi nǐ dǎ diànhuà.", english: "Great. I'll call you then." },
      { order: 9, dialogNumber: 3, dialogLabel: "On the road", speaker: "A", chinese: "明天天气怎么样？", pinyin: "Míngtiān tiānqì zěnmeyàng?", english: "How will the weather be tomorrow?" },
      { order: 10, dialogNumber: 3, dialogLabel: "On the road", speaker: "B", chinese: "虽然是晴天，但是很冷。", pinyin: "Suīrán shì qíngtiān, dànshì hěn lěng.", english: "It will be fine, but cold." },
      { order: 11, dialogNumber: 3, dialogLabel: "On the road", speaker: "A", chinese: "那还能去跑步吗？", pinyin: "Nà hái néng qù pǎobù ma?", english: "In that case, is it OK to go jogging?" },
      { order: 12, dialogNumber: 3, dialogLabel: "On the road", speaker: "B", chinese: "可以，但是你自己去吧，我还有很多事情要做。", pinyin: "Kěyǐ, dànshì nǐ zìjǐ qù ba, wǒ hái yǒu hěn duō shìqing yào zuò.", english: "I think so. But I'm afraid you have to go by yourself because I have a lot of work to do." },
      { order: 13, dialogNumber: 4, dialogLabel: "In a store", speaker: "A", chinese: "你在这个商店买过东西没有？", pinyin: "Nǐ zài zhège shāngdiàn mǎiguo dōngxi méiyǒu?", english: "Have you ever bought anything in this store?" },
      { order: 14, dialogNumber: 4, dialogLabel: "In a store", speaker: "B", chinese: "买过一次，这儿的东西还可以，就是不便宜。", pinyin: "Mǎiguo yí cì, zhèr de dōngxi hái kěyǐ, jiùshì bù piányi.", english: "Yes, once. Things here are pretty good, not cheap though." },
      { order: 15, dialogNumber: 4, dialogLabel: "In a store", speaker: "A", chinese: "我喜欢这件衣服，但是觉得有点儿贵。", pinyin: "Wǒ xǐhuān zhè jiàn yīfu, dànshì juéde yǒudiǎnr guì.", english: "I like this garment, but I think it's a little expensive." },
      { order: 16, dialogNumber: 4, dialogLabel: "In a store", speaker: "B", chinese: "两百块还可以，喜欢就买吧。", pinyin: "Liǎng bǎi kuài hái kěyǐ, xǐhuān jiù mǎi ba.", english: "Two hundred yuan is not that expensive. If you like it, just buy it." },
    ],
  },
  {
    chapterNumber: 15,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "At a friend's home", speaker: "A", chinese: "今天是12月20日，新年就要到了。新年你准备做什么？", pinyin: "Jīntiān shì shí'èr yuè èrshí rì, xīnnián jiù yào dào le. Xīnnián nǐ zhǔnbèi zuò shénme?", english: "Today is December 20th. The New Year is coming. What plans do you have?" },
      { order: 2, dialogNumber: 1, dialogLabel: "At a friend's home", speaker: "B", chinese: "我想去北京旅游，北京很不错，我去过一次。", pinyin: "Wǒ xiǎng qù Běijīng lǚyóu, Běijīng hěn búcuò, wǒ qùguo yí cì.", english: "I want to take a trip to Beijing. Beijing is a nice place. I've been there once." },
      { order: 3, dialogNumber: 1, dialogLabel: "At a friend's home", speaker: "A", chinese: "你买票了吗？", pinyin: "Nǐ mǎi piào le ma?", english: "Have you bought the ticket?" },
      { order: 4, dialogNumber: 1, dialogLabel: "At a friend's home", speaker: "B", chinese: "还没有呢，明天就去火车站买票。", pinyin: "Hái méiyǒu ne, míngtiān jiù qù huǒchēzhàn mǎi piào.", english: "Not yet. I'll go to the railway station to buy it tomorrow." },
      { order: 5, dialogNumber: 2, dialogLabel: "In the company", speaker: "A", chinese: "时间过得真快，新的一年快要到了！", pinyin: "Shíjiān guò de zhēn kuài, xīn de yì nián kuài yào dào le!", english: "How time flies! The New Year is approaching!" },
      { order: 6, dialogNumber: 2, dialogLabel: "In the company", speaker: "B", chinese: "是啊，谢谢大家这一年对我的帮助！", pinyin: "Shì a, xièxie dàjiā zhè yì nián duì wǒ de bāngzhù!", english: "Yes. Thank you all for your help during the past year." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the company", speaker: "C", chinese: "希望我们的公司明年更好！", pinyin: "Xīwàng wǒmen de gōngsī míngnián gèng hǎo!", english: "I hope our company will become even better in the next year." },
      { order: 8, dialogNumber: 3, dialogLabel: "Waiting for someone", speaker: "A", chinese: "你妹妹怎么还没来？都八点四十了！", pinyin: "Nǐ mèimei zěnme hái méi lái? Dōu bā diǎn sìshí le!", english: "Why hasn't your younger sister arrived yet? It's already eight forty." },
      { order: 9, dialogNumber: 3, dialogLabel: "Waiting for someone", speaker: "B", chinese: "我们再等她几分钟吧。", pinyin: "Wǒmen zài děng tā jǐ fēnzhōng ba.", english: "Let's wait for a few more minutes." },
      { order: 10, dialogNumber: 3, dialogLabel: "Waiting for someone", speaker: "A", chinese: "都等她半个小时了！", pinyin: "Dōu děng tā bàn ge xiǎoshí le!", english: "We've already waited for half an hour." },
      { order: 11, dialogNumber: 3, dialogLabel: "Waiting for someone", speaker: "B", chinese: "她来了，我听见她说话了。", pinyin: "Tā lái le, wǒ tīngjiàn tā shuōhuà le.", english: "She is here. I heard her voice." },
      { order: 12, dialogNumber: 4, dialogLabel: "Outside a coffee house", speaker: "A", chinese: "天阴了，我要回去了。", pinyin: "Tiān yīn le, wǒ yào huíqù le.", english: "It's overcast. I have to go home." },
      { order: 13, dialogNumber: 4, dialogLabel: "Outside a coffee house", speaker: "B", chinese: "好的。快要下雨了，你路上慢点儿。", pinyin: "Hǎo de. Kuài yào xià yǔ le, nǐ lùshang màn diǎnr.", english: "OK. It's going to rain. Be careful on your way." },
      { order: 14, dialogNumber: 4, dialogLabel: "Outside a coffee house", speaker: "A", chinese: "没关系，我坐公共汽车。", pinyin: "Méi guānxi, wǒ zuò gōnggòng qìchē.", english: "Don't worry. I'll take a bus." },
      { order: 15, dialogNumber: 4, dialogLabel: "Outside a coffee house", speaker: "B", chinese: "好的。再见。", pinyin: "Hǎo de. Zàijiàn.", english: "Good. Bye." },
    ],
  },
];
