// HSK3 chapter (lesson) word lists — kept entirely inside website/ rather than
// as characters/words/hsk3/chapterN/vocabulary.md files, per explicit
// instruction not to add new content under characters/words/. Source: the
// HSK Standard Course 3 textbook's own "生词 New Words" table for each
// lesson (1-20), transcribed via LLM from the back-of-book appendix
// regrouped by lesson. Only each lesson's core New Words table is included —
// Proper Nouns are excluded (see the no-proper-nouns-in-quiz rule) and the
// "旧字新词 New Words from Learned Characters" sections are excluded the same
// way HSK1/2 chapters never included the combined appendix's compound-word
// section either.
//
// No lesson has a descriptive Chinese title in this source (unlike HSK1/2's
// "你好 Hello" style titles) — chapter titles are just "Lesson N" until/if
// that's ever supplied.
export interface Hsk3ChapterWord {
  chinese: string;
  pinyin: string;
  wordType: string | null;
  meaning: string;
}

export interface Hsk3ChapterData {
  chapterNumber: number;
  words: Hsk3ChapterWord[];
}

export const HSK3_CHAPTERS: Hsk3ChapterData[] = [
  {
    chapterNumber: 1,
    words: [
      { chinese: "啊", pinyin: "a", wordType: "part.", meaning: "used at the end of a sentence to indicate confirmation or defense" },
      { chinese: "搬", pinyin: "bān", wordType: "v.", meaning: "to move, to carry" },
      { chinese: "北方", pinyin: "běifāng", wordType: "n.", meaning: "north, northern part" },
      { chinese: "打算", pinyin: "dǎsuàn", wordType: "n./v.", meaning: "plan; to intend" },
      { chinese: "带", pinyin: "dài", wordType: "v.", meaning: "to take along, to bring" },
      { chinese: "地图", pinyin: "dìtú", wordType: "n.", meaning: "map" },
      { chinese: "复习", pinyin: "fùxí", wordType: "v.", meaning: "to review" },
      { chinese: "跟", pinyin: "gēn", wordType: "prep.", meaning: "with" },
      { chinese: "面包", pinyin: "miànbāo", wordType: "n.", meaning: "bread" },
      { chinese: "南（方）", pinyin: "nán (fāng)", wordType: "n.", meaning: "south, southern part" },
      { chinese: "一直", pinyin: "yìzhí", wordType: "adv.", meaning: "all the time" },
      { chinese: "游戏", pinyin: "yóuxì", wordType: "n.", meaning: "game" },
      { chinese: "着急", pinyin: "zháojí", wordType: "adj.", meaning: "worried, anxious" },
      { chinese: "周末", pinyin: "zhōumò", wordType: "n.", meaning: "weekend" },
      { chinese: "作业", pinyin: "zuòyè", wordType: "n.", meaning: "homework" },
    ],
  },
  {
    chapterNumber: 2,
    words: [
      { chinese: "把", pinyin: "bǎ", wordType: "m.", meaning: "used for things with a handle" },
      { chinese: "办公室", pinyin: "bàngōngshì", wordType: "n.", meaning: "office" },
      { chinese: "脚", pinyin: "jiǎo", wordType: "n.", meaning: "foot" },
      { chinese: "经理", pinyin: "jīnglǐ", wordType: "n.", meaning: "manager" },
      { chinese: "辆", pinyin: "liàng", wordType: "m.", meaning: "used for vehicle" },
      { chinese: "楼", pinyin: "lóu", wordType: "n.", meaning: "building" },
      { chinese: "拿", pinyin: "ná", wordType: "v.", meaning: "to take, to fetch" },
      { chinese: "难", pinyin: "nán", wordType: "adj.", meaning: "difficult" },
      { chinese: "胖", pinyin: "pàng", wordType: "adj.", meaning: "fat" },
      { chinese: "其实", pinyin: "qíshí", wordType: "adv.", meaning: "actually" },
      { chinese: "容易", pinyin: "róngyì", wordType: "adj.", meaning: "easy" },
      { chinese: "伞", pinyin: "sǎn", wordType: "n.", meaning: "umbrella" },
      { chinese: "瘦", pinyin: "shòu", wordType: "adj.", meaning: "thin" },
      { chinese: "树", pinyin: "shù", wordType: "n.", meaning: "tree" },
      { chinese: "疼", pinyin: "téng", wordType: "adj.", meaning: "hurt, painful" },
      { chinese: "腿", pinyin: "tuǐ", wordType: "n.", meaning: "leg" },
    ],
  },
  {
    chapterNumber: 3,
    words: [
      { chinese: "衬衫", pinyin: "chènshān", wordType: "n.", meaning: "shirt" },
      { chinese: "放", pinyin: "fàng", wordType: "v.", meaning: "to put, to place" },
      { chinese: "还是", pinyin: "háishi", wordType: "conj.", meaning: "or" },
      { chinese: "花", pinyin: "huā", wordType: "n.", meaning: "flower" },
      { chinese: "或者", pinyin: "huòzhě", wordType: "conj.", meaning: "or" },
      { chinese: "记得", pinyin: "jìde", wordType: "v.", meaning: "to remember" },
      { chinese: "裤子", pinyin: "kùzi", wordType: "n.", meaning: "pants" },
      { chinese: "绿", pinyin: "lǜ", wordType: "adj.", meaning: "green" },
      { chinese: "爬山", pinyin: "pá shān", wordType: "v.", meaning: "to climb a mountain" },
      { chinese: "舒服", pinyin: "shūfu", wordType: "adj.", meaning: "comfortable" },
      { chinese: "甜", pinyin: "tián", wordType: "adj.", meaning: "sweet" },
      { chinese: "条", pinyin: "tiáo", wordType: "m.", meaning: "used for pants, dresses, etc." },
      { chinese: "小心", pinyin: "xiǎoxīn", wordType: "adj.", meaning: "careful" },
      { chinese: "新鲜", pinyin: "xīnxiān", wordType: "adj.", meaning: "fresh" },
      { chinese: "饮料", pinyin: "yǐnliào", wordType: "n.", meaning: "drink, beverage" },
      { chinese: "元", pinyin: "yuán", wordType: "m.", meaning: "unit of money" },
      { chinese: "只", pinyin: "zhǐ", wordType: "adv.", meaning: "only, solely" },
    ],
  },
  {
    chapterNumber: 4,
    words: [
      { chinese: "比赛", pinyin: "bǐsài", wordType: "n.", meaning: "match, competition" },
      { chinese: "超市", pinyin: "chāoshì", wordType: "n.", meaning: "supermarket" },
      { chinese: "聪明", pinyin: "cōngming", wordType: "adj.", meaning: "clever, smart" },
      { chinese: "蛋糕", pinyin: "dàngāo", wordType: "n.", meaning: "cake" },
      { chinese: "饿", pinyin: "è", wordType: "adj.", meaning: "hungry" },
      { chinese: "分", pinyin: "fēn", wordType: "m.", meaning: "fen, a unit of money (=1/10 jiao)" },
      { chinese: "回答", pinyin: "huídá", wordType: "v.", meaning: "to answer" },
      { chinese: "角", pinyin: "jiǎo", wordType: "m.", meaning: "jiao, a unit of money (=1/10 yuan)" },
      { chinese: "客人", pinyin: "kèrén", wordType: "n.", meaning: "customer, guest" },
      { chinese: "年级", pinyin: "niánjí", wordType: "n.", meaning: "grade" },
      { chinese: "年轻", pinyin: "niánqīng", wordType: "adj.", meaning: "young" },
      { chinese: "努力", pinyin: "nǔlì", wordType: "adj.", meaning: "hard-working" },
      { chinese: "热情", pinyin: "rèqíng", wordType: "adj.", meaning: "warm, enthusiastic" },
      { chinese: "认真", pinyin: "rènzhēn", wordType: "adj.", meaning: "serious, earnest" },
      { chinese: "又", pinyin: "yòu", wordType: "adv.", meaning: "and" },
      { chinese: "站", pinyin: "zhàn", wordType: "v.", meaning: "to stand" },
      { chinese: "照片", pinyin: "zhàopiàn", wordType: "n.", meaning: "photo" },
      { chinese: "总是", pinyin: "zǒngshì", wordType: "adv.", meaning: "always" },
    ],
  },
  {
    chapterNumber: 5,
    words: [
      { chinese: "草", pinyin: "cǎo", wordType: "n.", meaning: "grass" },
      { chinese: "春（天）", pinyin: "chūn (tiān)", wordType: "n.", meaning: "spring" },
      { chinese: "当然", pinyin: "dāngrán", wordType: "adv.", meaning: "of course" },
      { chinese: "发烧", pinyin: "fā shāo", wordType: "v.", meaning: "to have a fever" },
      { chinese: "感冒", pinyin: "gǎnmào", wordType: "v.", meaning: "to catch a cold" },
      { chinese: "季节", pinyin: "jìjié", wordType: "n.", meaning: "season" },
      { chinese: "裙子", pinyin: "qúnzi", wordType: "n.", meaning: "dress, skirt" },
      { chinese: "为", pinyin: "wèi", wordType: "prep.", meaning: "for" },
      { chinese: "夏（天）", pinyin: "xià (tiān)", wordType: "n.", meaning: "summer" },
      { chinese: "用", pinyin: "yòng", wordType: "v.", meaning: "to need" },
      { chinese: "越", pinyin: "yuè", wordType: "adv.", meaning: "more, to a greater degree" },
      { chinese: "照顾", pinyin: "zhàogù", wordType: "v.", meaning: "to take care of" },
      { chinese: "最近", pinyin: "zuìjìn", wordType: "adv.", meaning: "lately, recently" },
    ],
  },
  {
    chapterNumber: 6,
    words: [
      { chinese: "帮忙", pinyin: "bāng máng", wordType: "v.", meaning: "to help" },
      { chinese: "锻炼", pinyin: "duànliàn", wordType: "v.", meaning: "to do physical exercise" },
      { chinese: "刚才", pinyin: "gāngcái", wordType: "n.", meaning: "just now" },
      { chinese: "更", pinyin: "gèng", wordType: "adv.", meaning: "more, even more" },
      { chinese: "公园", pinyin: "gōngyuán", wordType: "n.", meaning: "park" },
      { chinese: "讲", pinyin: "jiǎng", wordType: "v.", meaning: "to explain" },
      { chinese: "离开", pinyin: "lí kāi", wordType: "v.", meaning: "to leave, to part with" },
      { chinese: "聊天（儿）", pinyin: "liáotiān(r)", wordType: "v.", meaning: "to chat" },
      { chinese: "明白", pinyin: "míngbai", wordType: "adj.", meaning: "clear" },
      { chinese: "清楚", pinyin: "qīngchu", wordType: "adj.", meaning: "clear, distinct" },
      { chinese: "特别", pinyin: "tèbié", wordType: "adv.", meaning: "extraordinarily" },
      { chinese: "突然", pinyin: "tūrán", wordType: "adv.", meaning: "suddenly" },
      { chinese: "音乐", pinyin: "yīnyuè", wordType: "n.", meaning: "music" },
    ],
  },
  {
    chapterNumber: 7,
    words: [
      { chinese: "半", pinyin: "bàn", wordType: "num.", meaning: "half" },
      { chinese: "差", pinyin: "chà", wordType: "v.", meaning: "to fall short of" },
      { chinese: "迟到", pinyin: "chídào", wordType: "v.", meaning: "to be late" },
      { chinese: "感兴趣", pinyin: "gǎn xìngqù", wordType: null, meaning: "to be interested in" },
      { chinese: "欢迎", pinyin: "huānyíng", wordType: "v.", meaning: "to welcome" },
      { chinese: "接", pinyin: "jiē", wordType: "v.", meaning: "to meet (sb.), to pick up (sb.)" },
      { chinese: "结婚", pinyin: "jié hūn", wordType: "v.", meaning: "to marry, to get married" },
      { chinese: "久", pinyin: "jiǔ", wordType: "adj.", meaning: "for a long time, long" },
      { chinese: "刻", pinyin: "kè", wordType: "m.", meaning: "quarter" },
      { chinese: "同事", pinyin: "tóngshì", wordType: "n.", meaning: "colleague" },
      { chinese: "以前", pinyin: "yǐqián", wordType: "n.", meaning: "before, ago" },
      { chinese: "银行", pinyin: "yínháng", wordType: "n.", meaning: "bank" },
    ],
  },
  {
    chapterNumber: 8,
    words: [
      { chinese: "安静", pinyin: "ānjìng", wordType: "adj.", meaning: "quiet" },
      { chinese: "变化", pinyin: "biànhuà", wordType: "v.", meaning: "to change" },
      { chinese: "层", pinyin: "céng", wordType: "m.", meaning: "used for floors" },
      { chinese: "电梯", pinyin: "diàntī", wordType: "n.", meaning: "elevator" },
      { chinese: "害怕", pinyin: "hài pà", wordType: "v.", meaning: "to be afraid, to be scared" },
      { chinese: "几乎", pinyin: "jīhū", wordType: "adv.", meaning: "almost" },
      { chinese: "见面", pinyin: "jiàn miàn", wordType: "v.", meaning: "to meet" },
      { chinese: "健康", pinyin: "jiànkāng", wordType: "adj.", meaning: "healthy" },
      { chinese: "老", pinyin: "lǎo", wordType: "adj.", meaning: "old" },
      { chinese: "马上", pinyin: "mǎshàng", wordType: "adv.", meaning: "immediately, at once" },
      { chinese: "满意", pinyin: "mǎnyì", wordType: "v.", meaning: "to be satisfied" },
      { chinese: "洗手间", pinyin: "xǐshǒujiān", wordType: "n.", meaning: "bathroom, restroom" },
      { chinese: "熊猫", pinyin: "xióngmāo", wordType: "n.", meaning: "panda" },
      { chinese: "一会儿", pinyin: "yíhuìr", wordType: "n.", meaning: "a moment" },
      { chinese: "又", pinyin: "yòu", wordType: "adv.", meaning: "again" },
      { chinese: "重要", pinyin: "zhòngyào", wordType: "adj.", meaning: "important" },
    ],
  },
  {
    chapterNumber: 9,
    words: [
      { chinese: "班", pinyin: "bān", wordType: "n.", meaning: "class" },
      { chinese: "比较", pinyin: "bǐjiào", wordType: "adv.", meaning: "fairly, rather" },
      { chinese: "参加", pinyin: "cānjiā", wordType: "v.", meaning: "to participate" },
      { chinese: "担心", pinyin: "dān xīn", wordType: "v.", meaning: "to worry" },
      { chinese: "放心", pinyin: "fàng xīn", wordType: "v.", meaning: "to ease one's mind, to rest assured" },
      { chinese: "了解", pinyin: "liǎojiě", wordType: "v.", meaning: "to know" },
      { chinese: "先", pinyin: "xiān", wordType: "adv.", meaning: "first, in advance" },
      { chinese: "一定", pinyin: "yídìng", wordType: "adv.", meaning: "definitely, certainly" },
      { chinese: "一样", pinyin: "yíyàng", wordType: "adj.", meaning: "same, as…as…" },
      { chinese: "影响", pinyin: "yǐngxiǎng", wordType: "n.", meaning: "influence" },
      { chinese: "中间", pinyin: "zhōngjiān", wordType: "n.", meaning: "middle" },
      { chinese: "最后", pinyin: "zuìhòu", wordType: "n.", meaning: "the last one" },
    ],
  },
  {
    chapterNumber: 10,
    words: [
      { chinese: "矮", pinyin: "ǎi", wordType: "adj.", meaning: "short" },
      { chinese: "地方", pinyin: "dìfang", wordType: "n.", meaning: "place" },
      { chinese: "方便", pinyin: "fāngbiàn", wordType: "adj.", meaning: "convenient" },
      { chinese: "附近", pinyin: "fùjìn", wordType: "n.", meaning: "nearby, vicinity" },
      { chinese: "个子", pinyin: "gèzi", wordType: "n.", meaning: "height, stature" },
      { chinese: "环境", pinyin: "huánjìng", wordType: "n.", meaning: "environment" },
      { chinese: "换", pinyin: "huàn", wordType: "v.", meaning: "to change, to substitute" },
      { chinese: "旧", pinyin: "jiù", wordType: "adj.", meaning: "old, used, worn" },
      { chinese: "历史", pinyin: "lìshǐ", wordType: "n.", meaning: "history" },
      { chinese: "骑", pinyin: "qí", wordType: "v.", meaning: "to ride" },
      { chinese: "数学", pinyin: "shùxué", wordType: "n.", meaning: "maths" },
      { chinese: "体育", pinyin: "tǐyù", wordType: "n.", meaning: "P.E., sports" },
      { chinese: "主要", pinyin: "zhǔyào", wordType: "adj.", meaning: "main" },
      { chinese: "自行车", pinyin: "zìxíngchē", wordType: "n.", meaning: "bicycle" },
    ],
  },
  {
    chapterNumber: 11,
    words: [
      { chinese: "笔记本（电脑）", pinyin: "bǐjìběn (diànnǎo)", wordType: "n.", meaning: "notebook, laptop" },
      { chinese: "词典", pinyin: "cídiǎn", wordType: "n.", meaning: "dictionary" },
      { chinese: "灯", pinyin: "dēng", wordType: "n.", meaning: "light, lamp" },
      { chinese: "地铁", pinyin: "dìtiě", wordType: "n.", meaning: "subway" },
      { chinese: "电子邮件", pinyin: "diànzǐ yóujiàn", wordType: null, meaning: "e-mail" },
      { chinese: "关", pinyin: "guān", wordType: "v.", meaning: "to turn off, to close" },
      { chinese: "还", pinyin: "huán", wordType: "v.", meaning: "to return" },
      { chinese: "会议", pinyin: "huìyì", wordType: "n.", meaning: "meeting, conference" },
      { chinese: "结束", pinyin: "jiéshù", wordType: "v.", meaning: "to end, to finish" },
      { chinese: "借", pinyin: "jiè", wordType: "v.", meaning: "to borrow, to lend" },
      { chinese: "空调", pinyin: "kōngtiáo", wordType: "n.", meaning: "air conditioner" },
      { chinese: "口", pinyin: "kǒu", wordType: "m.", meaning: "mouthful" },
      { chinese: "筷子", pinyin: "kuàizi", wordType: "n.", meaning: "chopsticks" },
      { chinese: "啤酒", pinyin: "píjiǔ", wordType: "n.", meaning: "beer" },
      { chinese: "瓶子", pinyin: "píngzi", wordType: "n.", meaning: "bottle" },
      { chinese: "双", pinyin: "shuāng", wordType: "m.", meaning: "pair" },
      { chinese: "图书馆", pinyin: "túshūguǎn", wordType: "n.", meaning: "library" },
      { chinese: "忘记", pinyin: "wàngjì", wordType: "v.", meaning: "to forget" },
      { chinese: "习惯", pinyin: "xíguàn", wordType: "v./n.", meaning: "to be used to; habit" },
    ],
  },
  {
    chapterNumber: 12,
    words: [
      { chinese: "包", pinyin: "bāo", wordType: "n.", meaning: "bag, sack" },
      { chinese: "发现", pinyin: "fāxiàn", wordType: "v.", meaning: "to discover" },
      { chinese: "黑板", pinyin: "hēibǎn", wordType: "n.", meaning: "blackboard" },
      { chinese: "护照", pinyin: "hùzhào", wordType: "n.", meaning: "passport" },
      { chinese: "画", pinyin: "huà", wordType: "v./n.", meaning: "to draw, to paint; drawing, painting" },
      { chinese: "教", pinyin: "jiāo", wordType: "v.", meaning: "to teach" },
      { chinese: "起飞", pinyin: "qǐfēi", wordType: "v.", meaning: "(of an aircraft) to take off" },
      { chinese: "生气", pinyin: "shēng qì", wordType: "v.", meaning: "angry" },
      { chinese: "司机", pinyin: "sījī", wordType: "n.", meaning: "driver" },
      { chinese: "太阳", pinyin: "tàiyáng", wordType: "n.", meaning: "sun" },
      { chinese: "西", pinyin: "xī", wordType: "n.", meaning: "west" },
      { chinese: "行李箱", pinyin: "xínglixiāng", wordType: "n.", meaning: "luggage, suitcase" },
      { chinese: "需要", pinyin: "xūyào", wordType: "v.", meaning: "to need" },
      { chinese: "自己", pinyin: "zìjǐ", wordType: "pron.", meaning: "self" },
    ],
  },
  {
    chapterNumber: 13,
    words: [
      { chinese: "过去", pinyin: "guòqù", wordType: "n.", meaning: "past" },
      { chinese: "坏", pinyin: "huài", wordType: "adj.", meaning: "broken, ruined" },
      { chinese: "经常", pinyin: "jīngcháng", wordType: "adv.", meaning: "often" },
      { chinese: "礼物", pinyin: "lǐwù", wordType: "n.", meaning: "gift, present" },
      { chinese: "奶奶", pinyin: "nǎinai", wordType: "n.", meaning: "grandmother" },
      { chinese: "起来", pinyin: "qǐlai", wordType: "v.", meaning: "(indicating an upward movement) to rise" },
      { chinese: "校长", pinyin: "xiàozhǎng", wordType: "n.", meaning: "headmaster" },
      { chinese: "爷爷", pinyin: "yéye", wordType: "n.", meaning: "grandfather" },
      { chinese: "一般", pinyin: "yìbān", wordType: "adj.", meaning: "general, usual" },
      { chinese: "一边", pinyin: "yìbiān", wordType: "adv.", meaning: "indicating two actions taking place at the same time" },
      { chinese: "应该", pinyin: "yīnggāi", wordType: "v.", meaning: "should" },
      { chinese: "遇到", pinyin: "yùdào", wordType: "v.", meaning: "to come across, to run into" },
      { chinese: "愿意", pinyin: "yuànyì", wordType: "v.", meaning: "would like to" },
      { chinese: "终于", pinyin: "zhōngyú", wordType: "adv.", meaning: "finally" },
    ],
  },
  {
    chapterNumber: 14,
    words: [
      { chinese: "阿姨", pinyin: "āyí", wordType: "n.", meaning: "aunt" },
      { chinese: "冰箱", pinyin: "bīngxiāng", wordType: "n.", meaning: "refrigerator" },
      { chinese: "菜单", pinyin: "càidān", wordType: "n.", meaning: "menu" },
      { chinese: "打扫", pinyin: "dǎsǎo", wordType: "v.", meaning: "to clean, to sweep" },
      { chinese: "干净", pinyin: "gānjìng", wordType: "adj.", meaning: "clean" },
      { chinese: "故事", pinyin: "gùshì", wordType: "n.", meaning: "story" },
      { chinese: "刮风", pinyin: "guā fēng", wordType: "v.", meaning: "to be windy" },
      { chinese: "简单", pinyin: "jiǎndān", wordType: "adj.", meaning: "simple" },
      { chinese: "节目", pinyin: "jiémù", wordType: "n.", meaning: "programme" },
      { chinese: "盘子", pinyin: "pánzi", wordType: "n.", meaning: "plate" },
      { chinese: "然后", pinyin: "ránhòu", wordType: "conj.", meaning: "then, after that" },
      { chinese: "声音", pinyin: "shēngyīn", wordType: "n.", meaning: "sound, voice" },
      { chinese: "叔叔", pinyin: "shūshu", wordType: "n.", meaning: "uncle" },
      { chinese: "洗澡", pinyin: "xǐ zǎo", wordType: "v.", meaning: "to take a bath/shower" },
      { chinese: "香蕉", pinyin: "xiāngjiāo", wordType: "n.", meaning: "banana" },
      { chinese: "像", pinyin: "xiàng", wordType: "v.", meaning: "to be like" },
      { chinese: "月亮", pinyin: "yuèliang", wordType: "n.", meaning: "moon" },
    ],
  },
  {
    chapterNumber: 15,
    words: [
      { chinese: "除了", pinyin: "chúle", wordType: "prep.", meaning: "other than" },
      { chinese: "发", pinyin: "fā", wordType: "v.", meaning: "to send" },
      { chinese: "花", pinyin: "huā", wordType: "v.", meaning: "to spend" },
      { chinese: "极（了）", pinyin: "jí (le)", wordType: "adv.", meaning: "extremely" },
      { chinese: "街道", pinyin: "jiēdào", wordType: "n.", meaning: "street" },
      { chinese: "节日", pinyin: "jiérì", wordType: "n.", meaning: "festival" },
      { chinese: "句子", pinyin: "jùzi", wordType: "n.", meaning: "sentence" },
      { chinese: "练习", pinyin: "liànxí", wordType: "n.", meaning: "exercise" },
      { chinese: "留学", pinyin: "liú xué", wordType: "v.", meaning: "to study abroad" },
      { chinese: "其他", pinyin: "qítā", wordType: "pron.", meaning: "the rest" },
      { chinese: "上网", pinyin: "shàng wǎng", wordType: "v.", meaning: "to surf the Internet" },
      { chinese: "世界", pinyin: "shìjiè", wordType: "n.", meaning: "world" },
      { chinese: "水平", pinyin: "shuǐpíng", wordType: "n.", meaning: "level, standard" },
      { chinese: "提高", pinyin: "tí gāo", wordType: "v.", meaning: "to improve" },
      { chinese: "完成", pinyin: "wán chéng", wordType: "v.", meaning: "to complete" },
      { chinese: "文化", pinyin: "wénhuà", wordType: "n.", meaning: "culture" },
      { chinese: "新闻", pinyin: "xīnwén", wordType: "n.", meaning: "news" },
      { chinese: "要求", pinyin: "yāoqiú", wordType: "n.", meaning: "requirement" },
      { chinese: "注意", pinyin: "zhù yì", wordType: "v.", meaning: "to pay attention to" },
    ],
  },
  {
    chapterNumber: 16,
    words: [
      { chinese: "鼻子", pinyin: "bízi", wordType: "n.", meaning: "nose" },
      { chinese: "别人", pinyin: "biérén", wordType: "n.", meaning: "other people" },
      { chinese: "城市", pinyin: "chéngshì", wordType: "n.", meaning: "city" },
      { chinese: "公斤", pinyin: "gōngjīn", wordType: "n.", meaning: "kilogramme" },
      { chinese: "关系", pinyin: "guānxì", wordType: "n.", meaning: "relationship" },
      { chinese: "检查", pinyin: "jiǎnchá", wordType: "v.", meaning: "to check, to examine" },
      { chinese: "可爱", pinyin: "kě'ài", wordType: "adj.", meaning: "lovely, adorable" },
      { chinese: "帽子", pinyin: "màozi", wordType: "n.", meaning: "hat, cap" },
      { chinese: "米", pinyin: "mǐ", wordType: "n.", meaning: "metre" },
      { chinese: "皮鞋", pinyin: "píxié", wordType: "n.", meaning: "leather shoes" },
      { chinese: "认为", pinyin: "rènwéi", wordType: "v.", meaning: "to think, to believe" },
      { chinese: "如果", pinyin: "rúguǒ", wordType: "conj.", meaning: "if, in case" },
      { chinese: "刷牙", pinyin: "shuā yá", wordType: "v.", meaning: "to brush the teeth" },
      { chinese: "头发", pinyin: "tóufa", wordType: "n.", meaning: "hair" },
      { chinese: "长", pinyin: "zhǎng", wordType: "v.", meaning: "to grow, to develop" },
    ],
  },
  {
    chapterNumber: 17,
    words: [
      { chinese: "爱好", pinyin: "àihào", wordType: "n.", meaning: "hobby, interest" },
      { chinese: "办法", pinyin: "bànfǎ", wordType: "n.", meaning: "way, approach" },
      { chinese: "饱", pinyin: "bǎo", wordType: "adj.", meaning: "full, having eaten one's fill" },
      { chinese: "必须", pinyin: "bìxū", wordType: "adv.", meaning: "must" },
      { chinese: "冬（天）", pinyin: "dōng (tiān)", wordType: "n.", meaning: "winter" },
      { chinese: "根据", pinyin: "gēnjù", wordType: "prep.", meaning: "according to, based on" },
      { chinese: "后来", pinyin: "hòulái", wordType: "n.", meaning: "later, afterwards" },
      { chinese: "决定", pinyin: "juédìng", wordType: "v.", meaning: "to decide" },
      { chinese: "渴", pinyin: "kě", wordType: "adj.", meaning: "thirsty" },
      { chinese: "口", pinyin: "kǒu", wordType: "n.", meaning: "mouth" },
      { chinese: "邻居", pinyin: "línjū", wordType: "n.", meaning: "neighbour" },
      { chinese: "请假", pinyin: "qǐng jià", wordType: "v.", meaning: "to ask for leave" },
      { chinese: "为了", pinyin: "wèile", wordType: "prep.", meaning: "for the sake of" },
      { chinese: "选择", pinyin: "xuǎnzé", wordType: "v.", meaning: "to choose" },
      { chinese: "一共", pinyin: "yígòng", wordType: "adv.", meaning: "in total" },
    ],
  },
  {
    chapterNumber: 18,
    words: [
      { chinese: "地", pinyin: "de", wordType: "part.", meaning: "used to connect an adverbial modifier and the verb it modifies" },
      { chinese: "动物", pinyin: "dòngwù", wordType: "n.", meaning: "animal" },
      { chinese: "段", pinyin: "duàn", wordType: "m.", meaning: "used for sections or periods" },
      { chinese: "关于", pinyin: "guānyú", wordType: "prep.", meaning: "about, regarding" },
      { chinese: "国家", pinyin: "guójiā", wordType: "n.", meaning: "country, nation" },
      { chinese: "机会", pinyin: "jīhuì", wordType: "n.", meaning: "opportunity" },
      { chinese: "奇怪", pinyin: "qíguài", wordType: "adj.", meaning: "strange, odd" },
      { chinese: "同意", pinyin: "tóngyì", wordType: "v.", meaning: "to agree" },
      { chinese: "万", pinyin: "wàn", wordType: "num.", meaning: "ten thousand" },
      { chinese: "相信", pinyin: "xiāngxìn", wordType: "v.", meaning: "to believe" },
      { chinese: "向", pinyin: "xiàng", wordType: "prep.", meaning: "towards" },
      { chinese: "有名", pinyin: "yǒumíng", wordType: "adj.", meaning: "famous" },
      { chinese: "只", pinyin: "zhī", wordType: "m.", meaning: "used for certain animals" },
      { chinese: "种", pinyin: "zhǒng", wordType: "m.", meaning: "kind, type" },
      { chinese: "嘴", pinyin: "zuǐ", wordType: "n.", meaning: "mouth" },
      // "不但……而且……" (conj., not only...but also...) is a paired
      // grammar-pattern skeleton, not standalone typable vocabulary —
      // excluded for the same reason as the combined list's 只有……才……
      // (see combined-vocab-corrections.ts).
    ],
  },
  {
    chapterNumber: 19,
    words: [
      { chinese: "船", pinyin: "chuán", wordType: "n.", meaning: "boat, ship" },
      { chinese: "短", pinyin: "duǎn", wordType: "adj.", meaning: "short" },
      { chinese: "耳朵", pinyin: "ěrduo", wordType: "n.", meaning: "ear" },
      { chinese: "过", pinyin: "guò", wordType: "v.", meaning: "to spend, to pass" },
      { chinese: "经过", pinyin: "jīngguò", wordType: "v.", meaning: "to pass by" },
      { chinese: "哭", pinyin: "kū", wordType: "v.", meaning: "to cry" },
      { chinese: "蓝", pinyin: "lán", wordType: "adj.", meaning: "blue" },
      { chinese: "脸", pinyin: "liǎn", wordType: "n.", meaning: "face" },
      { chinese: "马", pinyin: "mǎ", wordType: "n.", meaning: "horse" },
      { chinese: "鸟", pinyin: "niǎo", wordType: "n.", meaning: "bird" },
      { chinese: "秋（天）", pinyin: "qiū (tiān)", wordType: "n.", meaning: "autumn, fall" },
      { chinese: "位", pinyin: "wèi", wordType: "m.", meaning: "a respectful measure word for people" },
      { chinese: "张", pinyin: "zhāng", wordType: "m.", meaning: "used for flat objects such as paper, photos, etc." },
    ],
  },
  {
    chapterNumber: 20,
    words: [
      { chinese: "被", pinyin: "bèi", wordType: "prep.", meaning: "used to indicate the passive voice" },
      { chinese: "成绩", pinyin: "chéngjì", wordType: "n.", meaning: "grade, performance, achievement" },
      { chinese: "东", pinyin: "dōng", wordType: "n.", meaning: "east" },
      { chinese: "多么", pinyin: "duōme", wordType: "adv.", meaning: "very, to a great extent" },
      { chinese: "分", pinyin: "fēn", wordType: "v.", meaning: "to distinguish" },
      { chinese: "关心", pinyin: "guānxīn", wordType: "v.", meaning: "to care for, to be interested in" },
      { chinese: "解决", pinyin: "jiějué", wordType: "v.", meaning: "to solve" },
      { chinese: "难过", pinyin: "nánguò", wordType: "adj.", meaning: "sad" },
      { chinese: "试", pinyin: "shì", wordType: "v.", meaning: "to try" },
      { chinese: "碗", pinyin: "wǎn", wordType: "n.", meaning: "bowl" },
      { chinese: "信用卡", pinyin: "xìnyòngkǎ", wordType: "n.", meaning: "credit card" },
      { chinese: "照相机", pinyin: "zhàoxiàngjī", wordType: "n.", meaning: "camera" },
      // "只有……才……" (conj., only...that/can...) excluded — grammar-pattern
      // skeleton, same reasoning as chapter 18's exclusion note above.
    ],
  },
];
