import type { CombinedVocabRow } from "./vocab-row";
import { HSK2_COMBINED_WORDS } from "./hsk2-combined-data";

// HSK3's combined (full-level) word list, transcribed directly from the
// official HSK Standard Course 3 textbook's own back-of-book appendix — see
// the comment atop hsk1-combined-data.ts for the general rationale, and the
// comment atop hsk2-combined-data.ts for why this composes onto the
// previous level's list rather than standing alone (book 3's own appendix
// only lists words new to book 3, but "combined" means cumulative here).
//
// Six parenthetical-bundling rows in the source (e.g. "南(方) nán(fāng)"),
// where the parenthesized part is actually a second, distinct word rather
// than an optional/droppable syllable, are split into two rows each — the
// same fix already applied to hsk3-chapters-data.ts's identical rows:
// 南/南方, 春/春天, 夏/夏天, 秋/秋天, 冬/冬天, 笔记本/笔记本电脑. Two other
// parenthetical rows are deliberately kept bundled, also matching
// hsk3-chapters-data.ts: 聊天（儿）(儿-erhua) and 极（了）(了-particle) —
// the parenthesized part there is a suffix, not a separate word.
//
// Excluded: 专有名词 Proper Nouns (黄河, 张, 周, and the five personal
// names — 中文 is also listed here, but it's kept via the main 生词 table
// instead, since it's ordinary vocabulary, not a name); "不但……而且……" — a
// paired grammar-pattern skeleton like "太……了" (excluded from HSK1),
// not a single typable word; and the pinyin-less "Additional Word
// Combinations" table (电子游戏, 电子词典, 花瓶, 奶瓶, 以上 — New Word +
// Learned Characters columns only, nothing typable to extract).
//
// One homograph merge *within* this book's own 生词 table (花 huā:
// "flower" (n.) and "to spend" (v.) — same problem as HSK1's 下, already
// documented in hsk1-combined-data.ts's comment). 只 (zhī / zhǐ) is NOT
// merged despite looking similar — "a measure word for certain animals"
// and "only, solely" have different pinyin, so they're distinct words that
// don't collide on seed.ts's chinese+pinyin key.
//
// Several more collisions turned up *across* levels once this book's own
// list was compared against the full cumulative HSK1+HSK2 list:
// - Straight duplicates (same character, same pinyin, same sense) —
//   skipped here since they're already in an earlier level's file: 啊
//   (HSK1's own 超纲词 list), 班/更/公斤/过/欢迎 (HSK2's own 超纲词 list —
//   HSK2 had already tagged all five as 三级/HSK3-level bonus vocab, and
//   sure enough they reappear as core HSK3 words here), 帮/以后 (HSK2's
//   "New Words Made Up of Characters Learned Before" section), and 鲜花
//   (repeats this book's own main-table entry — it's listed twice in the
//   source itself, once in 生词 and again in "New Words Made Up...").
// - New senses of an existing character — merged into the earlier level's
//   entry instead of duplicated here: 口 (HSK1 already has "a measure word
//   for family members"; this book adds "mouth" and "mouthful"), 分 (HSK1
//   already has "minute"; this book adds "a unit of money" and "to
//   distinguish"), 开 and 上 and 贵 (see hsk1/hsk2-combined-data.ts's own
//   comments for those three). See hsk1-combined-data.ts's comment for the
//   merged 口/分 rows.
//
// "Words Not Included in the Syllabus" also turned out to mostly repeat
// words already in this book's own main 生词 table (词语, 情况, 生活,
// 睡着, 太太, 特点, 眼镜, 真正 — the last one, 真正, only showed up in a
// scanned image of the table, not the plain-text transcription, since the
// "Z" row was cut off there) — skipped as duplicates rather than re-added.
// Only 各/举行/可乐/秘书/中介 were genuinely new.
//
// "New Words Made Up of Characters Learned Before" has further overlaps:
// and 贵/开/上 are new senses of characters HSK1/HSK2 already teach with a
// different meaning — merged into HSK1's 开/上 and HSK2's 贵 entries
// directly (see those files' comments) rather than duplicated here.
const HSK3_OWN_WORDS: CombinedVocabRow[] = [
  // 生词 New Words
  { chinese: "阿姨", pinyin: "āyí", english: "aunt", category: "Noun" },
  { chinese: "矮", pinyin: "ǎi", english: "short", category: "Adjective" },
  { chinese: "爱好", pinyin: "àihào", english: "hobby, interest", category: "Noun" },
  { chinese: "安静", pinyin: "ānjìng", english: "quiet", category: "Adjective" },
  { chinese: "把", pinyin: "bǎ", english: "used for things with a handle", category: "Quantifier" },
  { chinese: "搬", pinyin: "bān", english: "to move, to carry", category: "Verb" },
  { chinese: "办法", pinyin: "bànfǎ", english: "way, approach", category: "Noun" },
  { chinese: "办公室", pinyin: "bàngōngshì", english: "office", category: "Noun" },
  { chinese: "半", pinyin: "bàn", english: "half", category: "Numeral" },
  { chinese: "帮忙", pinyin: "bāng máng", english: "to help", category: "Verb" },
  { chinese: "包", pinyin: "bāo", english: "bag, sack", category: "Noun" },
  { chinese: "饱", pinyin: "bǎo", english: "full, having eaten one's fill", category: "Adjective" },
  { chinese: "北方", pinyin: "běifāng", english: "north, northern part", category: "Noun" },
  { chinese: "被", pinyin: "bèi", english: "used to indicate the passive voice", category: "Preposition" },
  { chinese: "笔记本", pinyin: "bǐjìběn", english: "notebook", category: "Noun" },
  { chinese: "笔记本电脑", pinyin: "bǐjìběn diànnǎo", english: "laptop", category: "Noun" },
  { chinese: "比较", pinyin: "bǐjiào", english: "fairly, rather", category: "Adverb" },
  { chinese: "必须", pinyin: "bìxū", english: "must", category: "Adverb" },
  { chinese: "比赛", pinyin: "bǐsài", english: "match, competition", category: "Noun" },
  { chinese: "别人", pinyin: "biéren", english: "other people", category: "Noun" },
  { chinese: "冰箱", pinyin: "bīngxiāng", english: "refrigerator", category: "Noun" },
  { chinese: "鼻子", pinyin: "bízi", english: "nose", category: "Noun" },
  { chinese: "菜单", pinyin: "càidān", english: "menu", category: "Noun" },
  { chinese: "参加", pinyin: "cānjiā", english: "to participate", category: "Verb" },
  { chinese: "草", pinyin: "cǎo", english: "grass", category: "Noun" },
  { chinese: "层", pinyin: "céng", english: "used for floors", category: "Quantifier" },
  { chinese: "差", pinyin: "chà", english: "to fall short of", category: "Verb" },
  { chinese: "衬衫", pinyin: "chènshān", english: "shirt", category: "Noun" },
  { chinese: "成绩", pinyin: "chéngjì", english: "grade, performance, achievement", category: "Noun" },
  { chinese: "城市", pinyin: "chéngshì", english: "city", category: "Noun" },
  { chinese: "迟到", pinyin: "chídào", english: "to be late", category: "Verb" },
  { chinese: "除了", pinyin: "chúle", english: "other than", category: "Preposition" },
  { chinese: "春", pinyin: "chūn", english: "spring", category: "Noun" },
  { chinese: "春天", pinyin: "chūntiān", english: "spring", category: "Noun" },
  { chinese: "词典", pinyin: "cídiǎn", english: "dictionary", category: "Noun" },
  { chinese: "词语", pinyin: "cíyǔ", english: "word, expression", category: "Noun" },
  { chinese: "聪明", pinyin: "cōngmíng", english: "clever, smart", category: "Adjective" },
  { chinese: "打扫", pinyin: "dǎsǎo", english: "to clean, to sweep", category: "Verb" },
  { chinese: "打算", pinyin: "dǎsuàn", english: "plan; to intend", category: "Noun" },
  { chinese: "带", pinyin: "dài", english: "to take along, to bring", category: "Verb" },
  { chinese: "蛋糕", pinyin: "dàngāo", english: "cake", category: "Noun" },
  { chinese: "当然", pinyin: "dāngrán", english: "of course", category: "Adverb" },
  { chinese: "担心", pinyin: "dān xīn", english: "to worry", category: "Verb" },
  {
    chinese: "地",
    pinyin: "de",
    english: "used to connect an adverbial modifier and the verb it modifies",
    category: "Particle",
  },
  { chinese: "灯", pinyin: "dēng", english: "light, lamp", category: "Noun" },
  { chinese: "地方", pinyin: "dìfang", english: "place", category: "Noun" },
  { chinese: "地铁", pinyin: "dìtiě", english: "subway", category: "Noun" },
  { chinese: "地图", pinyin: "dìtú", english: "map", category: "Noun" },
  { chinese: "电梯", pinyin: "diàntī", english: "elevator", category: "Noun" },
  { chinese: "电子邮件", pinyin: "diànzǐ yóujiàn", english: "e-mail", category: null },
  { chinese: "东", pinyin: "dōng", english: "east", category: "Noun" },
  { chinese: "冬", pinyin: "dōng", english: "winter", category: "Noun" },
  { chinese: "冬天", pinyin: "dōngtiān", english: "winter", category: "Noun" },
  { chinese: "动物", pinyin: "dòngwù", english: "animal", category: "Noun" },
  { chinese: "短", pinyin: "duǎn", english: "short", category: "Adjective" },
  { chinese: "段", pinyin: "duàn", english: "used for sections or periods", category: "Quantifier" },
  { chinese: "锻炼", pinyin: "duànliàn", english: "to do physical exercise", category: "Verb" },
  { chinese: "多么", pinyin: "duōme", english: "very, to a great extent", category: "Adverb" },
  { chinese: "饿", pinyin: "è", english: "hungry", category: "Adjective" },
  { chinese: "耳朵", pinyin: "ěrduo", english: "ear", category: "Noun" },
  { chinese: "发", pinyin: "fā", english: "to send", category: "Verb" },
  { chinese: "发烧", pinyin: "fā shāo", english: "to have a fever", category: "Verb" },
  { chinese: "发现", pinyin: "fāxiàn", english: "to discover", category: "Verb" },
  { chinese: "方便", pinyin: "fāngbiàn", english: "convenient", category: "Adjective" },
  { chinese: "放", pinyin: "fàng", english: "to put, to place", category: "Verb" },
  { chinese: "放心", pinyin: "fàng xīn", english: "to ease one's mind, to rest assured", category: "Verb" },
  { chinese: "附近", pinyin: "fùjìn", english: "nearby, vicinity", category: "Noun" },
  { chinese: "复习", pinyin: "fùxí", english: "to review", category: "Verb" },
  { chinese: "干净", pinyin: "gānjìng", english: "clean", category: "Adjective" },
  { chinese: "感冒", pinyin: "gǎnmào", english: "to catch a cold", category: "Verb" },
  { chinese: "感兴趣", pinyin: "gǎn xìngqù", english: "to be interested in", category: null },
  { chinese: "刚才", pinyin: "gāngcái", english: "just now", category: "Noun" },
  { chinese: "个子", pinyin: "gèzi", english: "height, stature", category: "Noun" },
  { chinese: "根据", pinyin: "gēnjù", english: "according to, based on", category: "Preposition" },
  { chinese: "跟", pinyin: "gēn", english: "with", category: "Preposition" },
  { chinese: "公园", pinyin: "gōngyuán", english: "park", category: "Noun" },
  { chinese: "故事", pinyin: "gùshi", english: "story", category: "Noun" },
  { chinese: "刮风", pinyin: "guā fēng", english: "to be windy", category: "Verb" },
  { chinese: "关", pinyin: "guān", english: "to turn off, to close", category: "Verb" },
  { chinese: "关系", pinyin: "guānxi", english: "relationship", category: "Noun" },
  { chinese: "关心", pinyin: "guānxīn", english: "to care for, to be interested in", category: "Verb" },
  { chinese: "关于", pinyin: "guānyú", english: "about, regarding", category: "Preposition" },
  { chinese: "国家", pinyin: "guójiā", english: "country, nation", category: "Noun" },
  { chinese: "过去", pinyin: "guòqù", english: "past", category: "Noun" },
  { chinese: "还是", pinyin: "háishi", english: "or", category: "Conjunction" },
  { chinese: "害怕", pinyin: "hàipà", english: "to be afraid, to be scared", category: "Verb" },
  { chinese: "黑板", pinyin: "hēibǎn", english: "blackboard", category: "Noun" },
  { chinese: "后来", pinyin: "hòulái", english: "later, afterwards", category: "Noun" },
  { chinese: "护照", pinyin: "hùzhào", english: "passport", category: "Noun" },
  { chinese: "花", pinyin: "huā", english: "flower; to spend", category: null },
  { chinese: "画", pinyin: "huà", english: "to draw, to paint; drawing, painting", category: "Verb" },
  { chinese: "坏", pinyin: "huài", english: "broken, ruined", category: "Adjective" },
  { chinese: "还", pinyin: "huán", english: "to return", category: "Verb" },
  { chinese: "环境", pinyin: "huánjìng", english: "environment", category: "Noun" },
  { chinese: "换", pinyin: "huàn", english: "to change, to substitute", category: "Verb" },
  { chinese: "回答", pinyin: "huídá", english: "to answer", category: "Verb" },
  { chinese: "会议", pinyin: "huìyì", english: "meeting, conference", category: "Noun" },
  { chinese: "或者", pinyin: "huòzhě", english: "or", category: "Conjunction" },
  { chinese: "几乎", pinyin: "jīhū", english: "almost", category: "Adverb" },
  { chinese: "机会", pinyin: "jīhuì", english: "opportunity", category: "Noun" },
  { chinese: "极（了）", pinyin: "jí (le)", english: "extremely", category: "Adverb" },
  { chinese: "记得", pinyin: "jìde", english: "to remember", category: "Verb" },
  { chinese: "季节", pinyin: "jìjié", english: "season", category: "Noun" },
  { chinese: "检查", pinyin: "jiǎnchá", english: "to check, to examine", category: "Verb" },
  { chinese: "简单", pinyin: "jiǎndān", english: "simple", category: "Adjective" },
  { chinese: "见面", pinyin: "jiàn miàn", english: "to meet", category: "Verb" },
  { chinese: "健康", pinyin: "jiànkāng", english: "healthy", category: "Adjective" },
  { chinese: "讲", pinyin: "jiǎng", english: "to explain", category: "Verb" },
  { chinese: "教", pinyin: "jiāo", english: "to teach", category: "Verb" },
  { chinese: "角", pinyin: "jiǎo", english: "jiao, a unit of money (=1/10 yuan)", category: "Quantifier" },
  { chinese: "脚", pinyin: "jiǎo", english: "foot", category: "Noun" },
  { chinese: "接", pinyin: "jiē", english: "to meet (sb.), to pick up (sb.)", category: "Verb" },
  { chinese: "街道", pinyin: "jiēdào", english: "street", category: "Noun" },
  { chinese: "节目", pinyin: "jiémù", english: "programme", category: "Noun" },
  { chinese: "节日", pinyin: "jiérì", english: "festival", category: "Noun" },
  { chinese: "结婚", pinyin: "jié hūn", english: "to marry, to get married", category: "Verb" },
  { chinese: "结束", pinyin: "jiéshù", english: "to end, to finish", category: "Verb" },
  { chinese: "解决", pinyin: "jiějué", english: "to solve", category: "Verb" },
  { chinese: "借", pinyin: "jiè", english: "to borrow, to lend", category: "Verb" },
  { chinese: "经常", pinyin: "jīngcháng", english: "often", category: "Adverb" },
  { chinese: "经过", pinyin: "jīngguò", english: "to pass by", category: "Verb" },
  { chinese: "经理", pinyin: "jīnglǐ", english: "manager", category: "Noun" },
  { chinese: "久", pinyin: "jiǔ", english: "for a long time, long", category: "Adjective" },
  { chinese: "旧", pinyin: "jiù", english: "old, used, worn", category: "Adjective" },
  { chinese: "句子", pinyin: "jùzi", english: "sentence", category: "Noun" },
  { chinese: "决定", pinyin: "juédìng", english: "to decide", category: "Verb" },
  { chinese: "可爱", pinyin: "kě'ài", english: "lovely, adorable", category: "Adjective" },
  { chinese: "渴", pinyin: "kě", english: "thirsty", category: "Adjective" },
  { chinese: "刻", pinyin: "kè", english: "quarter", category: "Quantifier" },
  { chinese: "客人", pinyin: "kèren", english: "customer, guest", category: "Noun" },
  { chinese: "空调", pinyin: "kōngtiáo", english: "air conditioner", category: "Noun" },
  { chinese: "哭", pinyin: "kū", english: "to cry", category: "Verb" },
  { chinese: "裤子", pinyin: "kùzi", english: "pants", category: "Noun" },
  { chinese: "筷子", pinyin: "kuàizi", english: "chopsticks", category: "Noun" },
  { chinese: "蓝", pinyin: "lán", english: "blue", category: "Adjective" },
  { chinese: "老", pinyin: "lǎo", english: "old", category: "Adjective" },
  { chinese: "离开", pinyin: "lí kāi", english: "to leave, to part with", category: "Verb" },
  { chinese: "礼物", pinyin: "lǐwù", english: "gift, present", category: "Noun" },
  { chinese: "历史", pinyin: "lìshǐ", english: "history", category: "Noun" },
  { chinese: "脸", pinyin: "liǎn", english: "face", category: "Noun" },
  { chinese: "练习", pinyin: "liànxí", english: "exercise", category: "Noun" },
  { chinese: "辆", pinyin: "liàng", english: "used for vehicle", category: "Quantifier" },
  { chinese: "聊天（儿）", pinyin: "liáotiān(r)", english: "to chat", category: "Verb" },
  { chinese: "了解", pinyin: "liǎojiě", english: "to know", category: "Verb" },
  { chinese: "邻居", pinyin: "línjū", english: "neighbour", category: "Noun" },
  { chinese: "留学", pinyin: "liú xué", english: "to study abroad", category: "Verb" },
  { chinese: "楼", pinyin: "lóu", english: "building", category: "Noun" },
  { chinese: "绿", pinyin: "lǜ", english: "green", category: "Adjective" },
  { chinese: "马", pinyin: "mǎ", english: "horse", category: "Noun" },
  { chinese: "马上", pinyin: "mǎshàng", english: "immediately, at once", category: "Adverb" },
  { chinese: "满意", pinyin: "mǎnyì", english: "to be satisfied", category: "Verb" },
  { chinese: "帽子", pinyin: "màozi", english: "hat, cap", category: "Noun" },
  { chinese: "米", pinyin: "mǐ", english: "metre", category: "Noun" },
  { chinese: "面包", pinyin: "miànbāo", english: "bread", category: "Noun" },
  { chinese: "明白", pinyin: "míngbai", english: "clear", category: "Adjective" },
  { chinese: "拿", pinyin: "ná", english: "to take, to fetch", category: "Verb" },
  { chinese: "奶奶", pinyin: "nǎinai", english: "grandmother", category: "Noun" },
  { chinese: "南", pinyin: "nán", english: "south", category: "Noun" },
  { chinese: "南方", pinyin: "nánfāng", english: "south, southern part", category: "Noun" },
  { chinese: "难", pinyin: "nán", english: "difficult", category: "Adjective" },
  { chinese: "难过", pinyin: "nánguò", english: "sad", category: "Adjective" },
  { chinese: "年级", pinyin: "niánjí", english: "grade", category: "Noun" },
  { chinese: "年轻", pinyin: "niánqīng", english: "young", category: "Adjective" },
  { chinese: "鸟", pinyin: "niǎo", english: "bird", category: "Noun" },
  { chinese: "努力", pinyin: "nǔlì", english: "hard-working", category: "Adjective" },
  { chinese: "爬山", pinyin: "pá shān", english: "to climb a mountain", category: "Verb" },
  { chinese: "盘子", pinyin: "pánzi", english: "plate", category: "Noun" },
  { chinese: "胖", pinyin: "pàng", english: "fat", category: "Adjective" },
  { chinese: "皮鞋", pinyin: "píxié", english: "leather shoes", category: "Noun" },
  { chinese: "啤酒", pinyin: "píjiǔ", english: "beer", category: "Noun" },
  { chinese: "瓶子", pinyin: "píngzi", english: "bottle", category: "Noun" },
  { chinese: "其他", pinyin: "qítā", english: "the rest", category: "Pronoun" },
  { chinese: "奇怪", pinyin: "qíguài", english: "strange, odd", category: "Adjective" },
  { chinese: "起飞", pinyin: "qǐfēi", english: "(of an aircraft) to take off", category: "Verb" },
  { chinese: "起来", pinyin: "qǐlai", english: "(indicating an upward movement) to rise", category: "Verb" },
  { chinese: "骑", pinyin: "qí", english: "to ride", category: "Verb" },
  { chinese: "其实", pinyin: "qíshí", english: "actually", category: "Adverb" },
  { chinese: "情况", pinyin: "qíngkuàng", english: "condition, situation", category: "Noun" },
  { chinese: "清楚", pinyin: "qīngchu", english: "clear, distinct", category: "Adjective" },
  { chinese: "秋", pinyin: "qiū", english: "autumn, fall", category: "Noun" },
  { chinese: "秋天", pinyin: "qiūtiān", english: "autumn, fall", category: "Noun" },
  { chinese: "裙子", pinyin: "qúnzi", english: "dress, skirt", category: "Noun" },
  { chinese: "然后", pinyin: "ránhòu", english: "then, after that", category: "Conjunction" },
  { chinese: "热情", pinyin: "rèqíng", english: "warm, enthusiastic", category: "Adjective" },
  { chinese: "认为", pinyin: "rènwéi", english: "to think, to believe", category: "Verb" },
  { chinese: "认真", pinyin: "rènzhēn", english: "serious, earnest", category: "Adjective" },
  { chinese: "容易", pinyin: "róngyì", english: "easy", category: "Adjective" },
  { chinese: "如果", pinyin: "rúguǒ", english: "if, in case", category: "Conjunction" },
  { chinese: "伞", pinyin: "sǎn", english: "umbrella", category: "Noun" },
  { chinese: "上网", pinyin: "shàng wǎng", english: "to surf the Internet", category: "Verb" },
  { chinese: "生活", pinyin: "shēnghuó", english: "life", category: "Noun" },
  { chinese: "声音", pinyin: "shēngyīn", english: "sound, voice", category: "Noun" },
  { chinese: "生气", pinyin: "shēng qì", english: "angry", category: "Verb" },
  { chinese: "世界", pinyin: "shìjiè", english: "world", category: "Noun" },
  { chinese: "试", pinyin: "shì", english: "to try", category: "Verb" },
  { chinese: "瘦", pinyin: "shòu", english: "thin", category: "Adjective" },
  { chinese: "舒服", pinyin: "shūfu", english: "comfortable", category: "Adjective" },
  { chinese: "叔叔", pinyin: "shūshu", english: "uncle", category: "Noun" },
  { chinese: "树", pinyin: "shù", english: "tree", category: "Noun" },
  { chinese: "数学", pinyin: "shùxué", english: "maths", category: "Noun" },
  { chinese: "刷牙", pinyin: "shuā yá", english: "to brush the teeth", category: "Verb" },
  { chinese: "双", pinyin: "shuāng", english: "pair", category: "Quantifier" },
  { chinese: "水平", pinyin: "shuǐpíng", english: "level, standard", category: "Noun" },
  { chinese: "睡着", pinyin: "shuì zháo", english: "to fall asleep", category: "Verb" },
  { chinese: "司机", pinyin: "sījī", english: "driver", category: "Noun" },
  { chinese: "太太", pinyin: "tàitai", english: "Mrs., madam", category: "Noun" },
  { chinese: "太阳", pinyin: "tàiyáng", english: "sun", category: "Noun" },
  { chinese: "特点", pinyin: "tèdiǎn", english: "feature", category: "Noun" },
  { chinese: "特别", pinyin: "tèbié", english: "extraordinarily", category: "Adverb" },
  { chinese: "疼", pinyin: "téng", english: "hurt, painful", category: "Adjective" },
  { chinese: "体育", pinyin: "tǐyù", english: "P.E., sports", category: "Noun" },
  { chinese: "提高", pinyin: "tígāo", english: "to improve", category: "Verb" },
  { chinese: "条", pinyin: "tiáo", english: "used for pants, dresses, etc.", category: "Quantifier" },
  { chinese: "甜", pinyin: "tián", english: "sweet", category: "Adjective" },
  { chinese: "同事", pinyin: "tóngshì", english: "colleague", category: "Noun" },
  { chinese: "同意", pinyin: "tóngyì", english: "to agree", category: "Verb" },
  { chinese: "头发", pinyin: "tóufa", english: "hair", category: "Noun" },
  { chinese: "图书馆", pinyin: "túshūguǎn", english: "library", category: "Noun" },
  { chinese: "腿", pinyin: "tuǐ", english: "leg", category: "Noun" },
  { chinese: "突然", pinyin: "tūrán", english: "suddenly", category: "Adverb" },
  { chinese: "完成", pinyin: "wánchéng", english: "to complete", category: "Verb" },
  { chinese: "碗", pinyin: "wǎn", english: "bowl", category: "Noun" },
  { chinese: "万", pinyin: "wàn", english: "ten thousand", category: "Numeral" },
  { chinese: "忘记", pinyin: "wàngjì", english: "to forget", category: "Verb" },
  { chinese: "为", pinyin: "wèi", english: "for", category: "Preposition" },
  { chinese: "位", pinyin: "wèi", english: "a respectful measure word for people", category: "Quantifier" },
  { chinese: "为了", pinyin: "wèile", english: "for the sake of", category: "Preposition" },
  { chinese: "文化", pinyin: "wénhuà", english: "culture", category: "Noun" },
  { chinese: "西", pinyin: "xī", english: "west", category: "Noun" },
  { chinese: "习惯", pinyin: "xíguàn", english: "be used to; habit", category: "Verb" },
  { chinese: "洗手间", pinyin: "xǐshǒujiān", english: "bathroom, restroom", category: "Noun" },
  { chinese: "洗澡", pinyin: "xǐ zǎo", english: "to take a bath/shower", category: "Verb" },
  { chinese: "夏", pinyin: "xià", english: "summer", category: "Noun" },
  { chinese: "夏天", pinyin: "xiàtiān", english: "summer", category: "Noun" },
  { chinese: "先", pinyin: "xiān", english: "first, in advance", category: "Adverb" },
  { chinese: "鲜花", pinyin: "xiānhuā", english: "fresh flower", category: "Noun" },
  { chinese: "新鲜", pinyin: "xīnxiān", english: "fresh", category: "Adjective" },
  { chinese: "新闻", pinyin: "xīnwén", english: "news", category: "Noun" },
  { chinese: "信用卡", pinyin: "xìnyòngkǎ", english: "credit card", category: "Noun" },
  { chinese: "相信", pinyin: "xiāngxìn", english: "to believe", category: "Verb" },
  { chinese: "香蕉", pinyin: "xiāngjiāo", english: "banana", category: "Noun" },
  { chinese: "像", pinyin: "xiàng", english: "to be like", category: "Verb" },
  { chinese: "向", pinyin: "xiàng", english: "towards", category: "Preposition" },
  { chinese: "小心", pinyin: "xiǎoxīn", english: "careful", category: "Adjective" },
  { chinese: "校长", pinyin: "xiàozhǎng", english: "headmaster", category: "Noun" },
  { chinese: "熊猫", pinyin: "xióngmāo", english: "panda", category: "Noun" },
  { chinese: "行李", pinyin: "xínglǐ", english: "luggage", category: "Noun" },
  { chinese: "行李箱", pinyin: "xínglǐxiāng", english: "luggage, suitcase", category: "Noun" },
  { chinese: "需要", pinyin: "xūyào", english: "to need", category: "Verb" },
  { chinese: "选择", pinyin: "xuǎnzé", english: "to choose", category: "Verb" },
  { chinese: "眼镜", pinyin: "yǎnjìng", english: "glasses, spectacles", category: "Noun" },
  { chinese: "要求", pinyin: "yāoqiú", english: "requirement", category: "Noun" },
  { chinese: "爷爷", pinyin: "yéye", english: "grandfather", category: "Noun" },
  {
    chinese: "一边",
    pinyin: "yībiān",
    english: "indicating two actions taking place at the same time",
    category: "Adverb",
  },
  { chinese: "一定", pinyin: "yīdìng", english: "definitely, certainly", category: "Adverb" },
  { chinese: "一共", pinyin: "yīgòng", english: "in total", category: "Adverb" },
  { chinese: "一会儿", pinyin: "yīhuìr", english: "a moment", category: "Noun" },
  { chinese: "一样", pinyin: "yīyàng", english: "same, as...as...", category: "Adjective" },
  { chinese: "一直", pinyin: "yīzhí", english: "all the time", category: "Adverb" },
  { chinese: "银行", pinyin: "yínháng", english: "bank", category: "Noun" },
  { chinese: "饮料", pinyin: "yǐnliào", english: "drink, beverage", category: "Noun" },
  { chinese: "影响", pinyin: "yǐngxiǎng", english: "influence; to affect", category: "Noun" },
  { chinese: "应该", pinyin: "yīnggāi", english: "should", category: "Verb" },
  { chinese: "用", pinyin: "yòng", english: "to need", category: "Verb" },
  { chinese: "有名", pinyin: "yǒumíng", english: "famous", category: "Adjective" },
  { chinese: "又", pinyin: "yòu", english: "again", category: "Adverb" },
  { chinese: "游戏", pinyin: "yóuxì", english: "game", category: "Noun" },
  { chinese: "愿意", pinyin: "yuànyì", english: "would like to", category: "Verb" },
  { chinese: "越", pinyin: "yuè", english: "more, to a greater degree", category: "Adverb" },
  { chinese: "月亮", pinyin: "yuèliang", english: "moon", category: "Noun" },
  { chinese: "遇到", pinyin: "yùdào", english: "to come across, to run into", category: "Verb" },
  { chinese: "元", pinyin: "yuán", english: "unit of money", category: "Quantifier" },
  { chinese: "站", pinyin: "zhàn", english: "to stand", category: "Verb" },
  { chinese: "张", pinyin: "zhāng", english: "used for flat objects such as paper, photos, etc.", category: "Quantifier" },
  { chinese: "长", pinyin: "zhǎng", english: "to grow, to develop", category: "Verb" },
  { chinese: "照相机", pinyin: "zhàoxiàngjī", english: "camera", category: "Noun" },
  { chinese: "照顾", pinyin: "zhàogù", english: "to take care of", category: "Verb" },
  { chinese: "着急", pinyin: "zháojí", english: "worried, anxious", category: "Adjective" },
  { chinese: "真正", pinyin: "zhēnzhèng", english: "really, truly", category: "Adverb" },
  { chinese: "只", pinyin: "zhī", english: "used for certain animals", category: "Quantifier" },
  { chinese: "只", pinyin: "zhǐ", english: "only, solely", category: "Adverb" },
  { chinese: "终于", pinyin: "zhōngyú", english: "finally", category: "Adverb" },
  { chinese: "中文", pinyin: "zhōngwén", english: "Chinese language", category: "Noun" },
  { chinese: "中间", pinyin: "zhōngjiān", english: "middle", category: "Noun" },
  { chinese: "重要", pinyin: "zhòngyào", english: "important", category: "Adjective" },
  { chinese: "种", pinyin: "zhǒng", english: "kind, type", category: "Quantifier" },
  { chinese: "周末", pinyin: "zhōumò", english: "weekend", category: "Noun" },
  { chinese: "注意", pinyin: "zhùyì", english: "to pay attention to", category: "Verb" },
  { chinese: "自行车", pinyin: "zìxíngchē", english: "bicycle", category: "Noun" },
  { chinese: "自己", pinyin: "zìjǐ", english: "self", category: "Pronoun" },
  { chinese: "总是", pinyin: "zǒngshì", english: "always", category: "Adverb" },
  { chinese: "嘴", pinyin: "zuǐ", english: "mouth", category: "Noun" },
  { chinese: "最近", pinyin: "zuìjìn", english: "lately, recently", category: "Adverb" },
  { chinese: "最后", pinyin: "zuìhòu", english: "the last one", category: "Noun" },
  { chinese: "作业", pinyin: "zuòyè", english: "homework", category: "Noun" },

  // 超纲词 Words Not Included in the Syllabus (only the genuinely new ones —
  // see file comment above for the ones skipped as duplicates)
  { chinese: "各", pinyin: "gè", english: "each", category: "Pronoun" },
  { chinese: "举行", pinyin: "jǔxíng", english: "to hold (a meeting, an event, etc.)", category: "Verb" },
  { chinese: "可乐", pinyin: "kělè", english: "cola, Coke", category: "Noun" },
  { chinese: "秘书", pinyin: "mìshū", english: "secretary", category: "Noun" },
  { chinese: "中介", pinyin: "zhōngjiè", english: "intermediary, agent", category: "Noun" },

  // 旧字新词 New Words Made Up of Characters Learned Before (来自本册 From
  // This Book) — see file comment above for entries skipped as duplicates
  // or merged into an earlier level's file instead.
  { chinese: "办事", pinyin: "bàn shì", english: "to work, to handle affairs", category: "Verb" },
  { chinese: "变", pinyin: "biàn", english: "to change, to become", category: "Verb" },
  { chinese: "春节", pinyin: "Chūnjié", english: "Spring Festival", category: "Noun" },
  { chinese: "打", pinyin: "dǎ", english: "to send, to remit", category: "Verb" },
  { chinese: "到时候", pinyin: "dào shíhou", english: "that time, then", category: null },
  { chinese: "房子", pinyin: "fángzi", english: "house, building", category: "Noun" },
  { chinese: "刚", pinyin: "gāng", english: "just, only a short while ago", category: "Adverb" },
  { chinese: "歌舞", pinyin: "gēwǔ", english: "sing and dance", category: "Verb" },
  { chinese: "红酒", pinyin: "hóng jiǔ", english: "red wine", category: "Noun" },
  { chinese: "句", pinyin: "jù", english: "a measure word used for sentences", category: "Quantifier" },
  { chinese: "每天", pinyin: "měi tiān", english: "every day", category: null },
  {
    chinese: "哪里",
    pinyin: "nǎli",
    english: "(self-deprecatory expression) not at all",
    category: "Pronoun",
  },
  { chinese: "女孩儿", pinyin: "nǚháir", english: "girl", category: "Noun" },
  { chinese: "钱包", pinyin: "qiánbāo", english: "purse, wallet", category: "Noun" },
  { chinese: "人名", pinyin: "rén míng", english: "name (of a person)", category: "Noun" },
  { chinese: "认", pinyin: "rèn", english: "to recognise, to identify", category: "Verb" },
  { chinese: "听说", pinyin: "tīngshuō", english: "to hear about, to be told", category: "Verb" },
  { chinese: "外地", pinyin: "wàidì", english: "other places", category: "Noun" },
  { chinese: "香瓜", pinyin: "xiāngguā", english: "casaba", category: "Noun" },
  { chinese: "一般来说", pinyin: "yībān lái shuō", english: "generally speaking", category: null },
  { chinese: "音乐会", pinyin: "yīnyuèhuì", english: "concert", category: "Noun" },
  { chinese: "有点儿", pinyin: "yǒudiǎnr", english: "a little, a bit", category: "Adverb" },
  { chinese: "早", pinyin: "zǎo", english: "early", category: "Adjective" },
  { chinese: "怎么办", pinyin: "zěnme bàn", english: "(used to ask for a solution) what to do", category: null },
  { chinese: "照", pinyin: "zhào", english: "to photograph", category: "Verb" },
  { chinese: "中秋节", pinyin: "Zhōngqiū Jié", english: "Mid-Autumn Festival", category: "Noun" },
];

export const HSK3_COMBINED_WORDS: CombinedVocabRow[] = [
  ...HSK2_COMBINED_WORDS,
  ...HSK3_OWN_WORDS,
];
