import type { CombinedVocabRow } from "./vocab-row";

// HSK3's combined (full-level) word list — see the comment atop
// hsk1-combined-data.ts; same rationale and generation source.

export const HSK3_COMBINED_WORDS: CombinedVocabRow[] = [
  { chinese: "阿姨", pinyin: "āyí", english: "aunt", category: null },
  { chinese: "啊", pinyin: "a", english: "ah", category: null },
  { chinese: "矮", pinyin: "ǎi", english: "short", category: null },
  { chinese: "爱", pinyin: "ài", english: "love", category: null },
  { chinese: "爱好", pinyin: "àihào", english: "hobby", category: null },
  { chinese: "安静", pinyin: "ānjìng", english: "Be quiet", category: null },
  { chinese: "八", pinyin: "bā", english: "Eight", category: null },
  { chinese: "把", pinyin: "bǎ", english: "hold", category: null },
  { chinese: "爸爸", pinyin: "bàba", english: "Dad", category: null },
  { chinese: "吧", pinyin: "ba", english: null, category: null },
  { chinese: "白", pinyin: "bái", english: "white", category: null },
  { chinese: "百", pinyin: "bǎi", english: "hundred", category: null },
  { chinese: "班", pinyin: "bān", english: "class", category: null },
  { chinese: "搬", pinyin: "bān", english: null, category: null },
  { chinese: "半", pinyin: "bàn", english: "half", category: null },
  { chinese: "办法", pinyin: "bànfǎ", english: "Way", category: null },
  { chinese: "办公室", pinyin: "bàngōngshì", english: "Office", category: null },
  { chinese: "帮忙", pinyin: "bāngmáng", english: "Help", category: null },
  { chinese: "帮助", pinyin: "bāngzhù", english: "Help", category: null },
  { chinese: "包", pinyin: "bāo", english: "package", category: null },
  { chinese: "饱", pinyin: "bǎo", english: "full", category: null },
  { chinese: "报纸", pinyin: "bàozhǐ", english: "Newspaper", category: null },
  { chinese: "杯子", pinyin: "bēizi", english: "glass", category: null },
  { chinese: "北方", pinyin: "běifāng", english: "north", category: null },
  { chinese: "北京", pinyin: "Běijīng", english: "Beijing", category: null },
  { chinese: "被", pinyin: "bèi", english: "cover", category: null },
  { chinese: "本", pinyin: "běn", english: "book", category: null },
  { chinese: "鼻子", pinyin: "bízi", english: "nose", category: null },
  { chinese: "比", pinyin: "bǐ", english: "than", category: null },
  { chinese: "比较", pinyin: "bǐjiào", english: "compare", category: null },
  { chinese: "比赛", pinyin: "bǐsài", english: "Match", category: null },
  { chinese: "必须", pinyin: "bìxū", english: "Must", category: null },
  { chinese: "变化", pinyin: "biànhuà", english: "change", category: null },
  { chinese: "表示", pinyin: "biǎoshì", english: "Express", category: null },
  { chinese: "表演", pinyin: "biǎoyǎn", english: "perform", category: null },
  { chinese: "别", pinyin: "bié", english: "other", category: null },
  { chinese: "别人", pinyin: "biéren", english: "Others", category: null },
  { chinese: "宾馆", pinyin: "bīnguǎn", english: "hotel", category: null },
  { chinese: "冰箱", pinyin: "bīngxiāng", english: "Refrigerator", category: null },
  { chinese: "不客气", pinyin: "búkèqi", english: "You are welcome", category: null },
  { chinese: "不", pinyin: "bù", english: "No", category: null },
  { chinese: "才", pinyin: "cái", english: "just", category: null },
  { chinese: "菜", pinyin: "cài", english: "food,dish", category: null },
  { chinese: "菜单", pinyin: "càidān", english: "menu", category: null },
  { chinese: "参加", pinyin: "cānjiā", english: "participate in", category: null },
  { chinese: "草", pinyin: "cǎo", english: "grass", category: null },
  { chinese: "层", pinyin: "céng", english: "layer", category: null },
  { chinese: "茶", pinyin: "chá", english: "tea", category: null },
  { chinese: "差", pinyin: "chà", english: "bad", category: null },
  { chinese: "长", pinyin: "cháng", english: "long", category: null },
  { chinese: "唱歌", pinyin: "chànggē", english: "Sing", category: null },
  { chinese: "超市", pinyin: "chāoshì", english: "Supermarket", category: null },
  { chinese: "衬衫", pinyin: "chènshān", english: "shirt", category: null },
  { chinese: "成绩", pinyin: "chéngjì", english: "achievement", category: null },
  { chinese: "城市", pinyin: "chéngshì", english: "City", category: null },
  { chinese: "吃", pinyin: "chī", english: "eat", category: null },
  { chinese: "迟到", pinyin: "chídào", english: "Late", category: null },
  { chinese: "出", pinyin: "chū", english: "come out", category: null },
  { chinese: "出现", pinyin: "chūxiàn", english: "Appear", category: null },
  { chinese: "出租车", pinyin: "chūzūchē", english: "Taxi", category: null },
  { chinese: "厨房", pinyin: "chúfáng", english: "Kitchen", category: null },
  { chinese: "除了", pinyin: "chúle", english: "except, besides", category: null },
  { chinese: "穿", pinyin: "chuān", english: "Wear", category: null },
  { chinese: "船", pinyin: "chuán", english: "ship", category: null },
  { chinese: "春", pinyin: "chūn", english: "spring", category: null },
  { chinese: "词语", pinyin: "cíyǔ", english: "terms, words", category: null },
  { chinese: "次", pinyin: "cì", english: "times", category: null },
  { chinese: "聪明", pinyin: "cōngming", english: "clever", category: null },
  { chinese: "从", pinyin: "cóng", english: "from", category: null },
  { chinese: "错", pinyin: "cuò", english: "Wrong", category: null },
  { chinese: "打电话", pinyin: "dǎdiànhuà", english: "call", category: null },
  { chinese: "打篮球", pinyin: "dǎlánqiú", english: "Play basketball", category: null },
  { chinese: "打扫", pinyin: "dǎsǎo", english: "Clean", category: null },
  { chinese: "打算", pinyin: "dǎsuàn", english: "Plan", category: null },
  { chinese: "大", pinyin: "dà", english: "big", category: null },
  { chinese: "大家", pinyin: "dàjiā", english: "everybody", category: null },
  { chinese: "带", pinyin: "dài", english: "belt", category: null },
  { chinese: "担心", pinyin: "dānxīn", english: "Worry", category: null },
  { chinese: "蛋糕", pinyin: "dàngāo", english: "Cake", category: null },
  { chinese: "但是", pinyin: "dànshì", english: "however", category: null },
  { chinese: "当然", pinyin: "dāngrán", english: "Of course", category: null },
  { chinese: "到", pinyin: "dào", english: "reach", category: null },
  { chinese: "地", pinyin: "de", english: null, category: null },
  { chinese: "的", pinyin: "de", english: null, category: null },
  { chinese: "得", pinyin: "dé", english: null, category: null },
  { chinese: "灯", pinyin: "dēng", english: "lamp", category: null },
  { chinese: "等", pinyin: "děng", english: "etc.", category: null },
  { chinese: "低", pinyin: "dī", english: "low", category: null },
  { chinese: "弟弟", pinyin: "dìdi", english: "Younger brother", category: null },
  { chinese: "地方", pinyin: "dìfang", english: "local", category: null },
  { chinese: "地铁", pinyin: "dìtiě", english: "metro", category: null },
  { chinese: "地图", pinyin: "dìtú", english: "Map", category: null },
  { chinese: "第一", pinyin: "dìyī", english: "first", category: null },
  { chinese: "点", pinyin: "diǎn", english: "spot", category: null },
  { chinese: "电脑", pinyin: "diànnǎo", english: "Computer", category: null },
  { chinese: "电视", pinyin: "diànshì", english: "television", category: null },
  { chinese: "电梯", pinyin: "diàntī", english: "Elevator.", category: null },
  { chinese: "电影", pinyin: "diànyǐng", english: "Film", category: null },
  { chinese: "电子邮件", pinyin: "diànzǐyóujiàn", english: "E-mail", category: null },
  { chinese: "东", pinyin: "dōng", english: "east", category: null },
  { chinese: "东西", pinyin: "dōngxi", english: "thing", category: null },
  { chinese: "冬", pinyin: "dōng", english: "winter", category: null },
  { chinese: "懂", pinyin: "dǒng", english: "understand", category: null },
  { chinese: "动物", pinyin: "dòngwù", english: "Animal", category: null },
  { chinese: "都", pinyin: "dōu", english: "all", category: null },
  { chinese: "读", pinyin: "dú", english: "read", category: null },
  { chinese: "短", pinyin: "duǎn", english: "short", category: null },
  { chinese: "段", pinyin: "duàn", english: "paragraph", category: null },
  { chinese: "锻炼", pinyin: "duànliàn", english: "Physical exercise", category: null },
  { chinese: "对", pinyin: "duì", english: "Yes", category: null },
  { chinese: "对不起", pinyin: "duìbuqǐ", english: "I'm sorry.", category: null },
  { chinese: "多", pinyin: "duō", english: "many", category: null },
  { chinese: "多么", pinyin: "duōme", english: "such", category: null },
  { chinese: "多少", pinyin: "duōshao", english: "how much", category: null },
  { chinese: "饿", pinyin: "è", english: "hungry", category: null },
  { chinese: "而且", pinyin: "érqiě", english: "And", category: null },
  { chinese: "儿子", pinyin: "érzi", english: "Son", category: null },
  { chinese: "耳朵", pinyin: "ěrduo", english: "Ears", category: null },
  { chinese: "二", pinyin: "èr", english: "Two", category: null },
  { chinese: "发烧", pinyin: "fāshāo", english: "Have a fever", category: null },
  { chinese: "发现", pinyin: "fāxiàn", english: "find, discover", category: null },
  { chinese: "饭馆", pinyin: "fànguǎn", english: "restaurant", category: null },
  { chinese: "方便", pinyin: "fāngbiàn", english: "convenient", category: null },
  { chinese: "房间", pinyin: "fángjiān", english: "Room", category: null },
  { chinese: "放", pinyin: "fàng", english: "discharge", category: null },
  { chinese: "放心", pinyin: "fàngxīn", english: "Don't worry", category: null },
  { chinese: "非常", pinyin: "fēicháng", english: "very", category: null },
  { chinese: "飞机", pinyin: "fēijī", english: "aircraft", category: null },
  { chinese: "分", pinyin: "fēn", english: "minute", category: null },
  { chinese: "分钟", pinyin: "fēnzhōng", english: "Minute", category: null },
  { chinese: "服务员", pinyin: "fúwùyuán", english: "Waiter", category: null },
  { chinese: "附近", pinyin: "fùjìn", english: "nearby", category: null },
  { chinese: "复习", pinyin: "fùxí", english: "Review", category: null },
  { chinese: "干净", pinyin: "gānjìng", english: "clean", category: null },
  { chinese: "敢", pinyin: "gǎn", english: "dare", category: null },
  { chinese: "感冒", pinyin: "gǎnmào", english: "get a cold", category: null },
  { chinese: "刚才", pinyin: "gāngcái", english: "just", category: null },
  { chinese: "高", pinyin: "gāo", english: "high", category: null },
  { chinese: "高兴", pinyin: "gāoxìng", english: "happy", category: null },
  { chinese: "告诉", pinyin: "gàosu", english: "tell", category: null },
  { chinese: "哥哥", pinyin: "gēge", english: "older brother", category: null },
  { chinese: "个", pinyin: "gè", english: "individual", category: null },
  { chinese: "给", pinyin: "gěi", english: "to", category: null },
  { chinese: "跟", pinyin: "gēn", english: "with", category: null },
  { chinese: "根据", pinyin: "gēnjù", english: "according to", category: null },
  { chinese: "更", pinyin: "gèng", english: "more", category: null },
  { chinese: "公共汽车", pinyin: "gōnggòngqìchē", english: "Bus", category: null },
  { chinese: "公斤", pinyin: "gōngjīn", english: "Kg.", category: null },
  { chinese: "公司", pinyin: "gōngsī", english: "company", category: null },
  { chinese: "公园", pinyin: "gōngyuán", english: "Park", category: null },
  { chinese: "工作", pinyin: "gōngzuò", english: "work", category: null },
  { chinese: "狗", pinyin: "gǒu", english: "Dog", category: null },
  { chinese: "故事", pinyin: "gùshi", english: "Story", category: null },
  { chinese: "刮风", pinyin: "guāfēng", english: "Windy", category: null },
  { chinese: "关", pinyin: "guān", english: "shut", category: null },
  { chinese: "关系", pinyin: "guānxì", english: "relationship", category: null },
  { chinese: "关心", pinyin: "guānxīn", english: "Care for", category: null },
  { chinese: "关于", pinyin: "guānyú", english: "about", category: null },
  { chinese: "贵", pinyin: "guì", english: "Expensive", category: null },
  { chinese: "国家", pinyin: "guójiā", english: "Country", category: null },
  { chinese: "果汁", pinyin: "guǒzhī", english: "fruit juice", category: null },
  { chinese: "过去", pinyin: "guòqù", english: "Past times", category: null },
  { chinese: "过", pinyin: "guo", english: "too", category: null },
  { chinese: "还", pinyin: "hái", english: "still", category: null },
  { chinese: "还是", pinyin: "háishì", english: "still", category: null },
  { chinese: "孩子", pinyin: "háizi", english: "Children", category: null },
  { chinese: "害怕", pinyin: "hàipà", english: "Fear", category: null },
  { chinese: "汉语", pinyin: "hànyǔ", english: "Chinese", category: null },
  { chinese: "好", pinyin: "hǎo", english: "good", category: null },
  { chinese: "好吃", pinyin: "hǎochī", english: "Yummy", category: null },
  { chinese: "号", pinyin: "hào", english: "Number", category: null },
  { chinese: "喝", pinyin: "hē", english: "drink", category: null },
  { chinese: "和", pinyin: "hé", english: "and", category: null },
  { chinese: "河", pinyin: "hé", english: "river", category: null },
  { chinese: "黑", pinyin: "hēi", english: "black", category: null },
  { chinese: "黑板", pinyin: "hēibǎn", english: "blackboard", category: null },
  { chinese: "很", pinyin: "hěn", english: "very", category: null },
  { chinese: "红", pinyin: "hóng", english: "red", category: null },
  { chinese: "后面", pinyin: "hòumiàn", english: "behind", category: null },
  { chinese: "护照", pinyin: "hùzhào", english: "passport", category: null },
  { chinese: "花", pinyin: "huā", english: "flower; to spend", category: null },
  { chinese: "花园", pinyin: "huāyuán", english: "Garden", category: null },
  { chinese: "画", pinyin: "huà", english: "painting", category: null },
  { chinese: "坏", pinyin: "huài", english: "bad", category: null },
  { chinese: "欢迎", pinyin: "huānyíng", english: "Welcome", category: null },
  { chinese: "还", pinyin: "huán", english: "return", category: null },
  { chinese: "环境", pinyin: "huánjìng", english: "Environment", category: null },
  { chinese: "换", pinyin: "huàn", english: "change", category: null },
  { chinese: "黄", pinyin: "huáng", english: "yellow", category: null },
  { chinese: "回", pinyin: "huí", english: "return", category: null },
  { chinese: "回答", pinyin: "huídá", english: "Answer", category: null },
  { chinese: "会", pinyin: "huì", english: "can；be able to", category: null },
  { chinese: "会议", pinyin: "huìyì", english: "Meeting", category: null },
  { chinese: "火车站", pinyin: "huǒchēzhàn", english: "Train station", category: null },
  { chinese: "或者", pinyin: "huòzhě", english: "perhaps", category: null },
  { chinese: "机场", pinyin: "jīchǎng", english: "Airport", category: null },
  { chinese: "鸡蛋", pinyin: "jīdàn", english: "Egg", category: null },
  { chinese: "几乎", pinyin: "jīhū", english: "almost", category: null },
  { chinese: "机会", pinyin: "jīhuì", english: "Opportunity", category: null },
  { chinese: "极", pinyin: "jí", english: "extremely", category: null },
  { chinese: "几", pinyin: "jǐ", english: "several", category: null },
  { chinese: "记得", pinyin: "jìde", english: "remember", category: null },
  { chinese: "季节", pinyin: "jìjié", english: "Season", category: null },
  { chinese: "家", pinyin: "jiā", english: "home", category: null },
  { chinese: "检查", pinyin: "jiǎnchá", english: "inspect", category: null },
  { chinese: "简单", pinyin: "jiǎndān", english: "simple", category: null },
  { chinese: "件", pinyin: "jiàn", english: "piece", category: null },
  { chinese: "健康", pinyin: "jiànkāng", english: "Healthy", category: null },
  { chinese: "见面", pinyin: "jiànmiàn", english: "meet", category: null },
  { chinese: "讲", pinyin: "jiǎng", english: "speak", category: null },
  { chinese: "教", pinyin: "jiāo", english: "teach", category: null },
  { chinese: "角", pinyin: "jiǎo", english: "horn", category: null },
  { chinese: "脚", pinyin: "jiǎo", english: "foot", category: null },
  { chinese: "叫", pinyin: "jiào", english: "call", category: null },
  { chinese: "教室", pinyin: "jiàoshì", english: "Classroom", category: null },
  { chinese: "接", pinyin: "jiē", english: "pick,get", category: null },
  { chinese: "街道", pinyin: "jiēdào", english: "Street", category: null },
  { chinese: "结婚", pinyin: "jiéhūn", english: "marry", category: null },
  { chinese: "结束", pinyin: "jiéshù", english: "End", category: null },
  { chinese: "节目", pinyin: "jiémù", english: "program", category: null },
  { chinese: "节日", pinyin: "jiérì", english: "festival", category: null },
  { chinese: "姐姐", pinyin: "jiějie", english: "sister", category: null },
  { chinese: "解决", pinyin: "jiějué", english: "Solve", category: null },
  { chinese: "借", pinyin: "jiè", english: "borrow", category: null },
  { chinese: "介绍", pinyin: "jièshào", english: "introduce", category: null },
  { chinese: "今天", pinyin: "jīntiān", english: "Today", category: null },
  { chinese: "进", pinyin: "jìn", english: "enter", category: null },
  { chinese: "近", pinyin: "jìn", english: "near", category: null },
  { chinese: "经常", pinyin: "jīngcháng", english: "Often", category: null },
  { chinese: "经过", pinyin: "jīngguò", english: "After, through", category: null },
  { chinese: "经理", pinyin: "jīnglǐ", english: "manager", category: null },
  { chinese: "九", pinyin: "jiǔ", english: "Nine", category: null },
  { chinese: "久", pinyin: "jiǔ", english: "long", category: null },
  { chinese: "旧", pinyin: "jiù", english: "old,used", category: null },
  { chinese: "就", pinyin: "jiù", english: null, category: null },
  { chinese: "举行", pinyin: "jǔxíng", english: "hold", category: null },
  { chinese: "句子", pinyin: "jùzi", english: "sentence", category: null },
  { chinese: "觉得", pinyin: "juéde", english: "Think", category: null },
  { chinese: "决定", pinyin: "juédìng", english: "Decision", category: null },
  { chinese: "咖啡", pinyin: "kāfēi", english: "Coffee", category: null },
  { chinese: "开", pinyin: "kāi", english: "open", category: null },
  { chinese: "开始", pinyin: "kāishǐ", english: "start", category: null },
  { chinese: "看", pinyin: "kàn", english: "see", category: null },
  { chinese: "看见", pinyin: "kànjiàn", english: "seeing", category: null },
  { chinese: "考试", pinyin: "kǎoshì", english: "Examination", category: null },
  { chinese: "渴", pinyin: "kě", english: "thirsty", category: null },
  { chinese: "可爱", pinyin: "kě'ài", english: "Lovely", category: null },
  { chinese: "可能", pinyin: "kěnéng", english: "Probably", category: null },
  { chinese: "可以", pinyin: "kěyǐ", english: "Sure", category: null },
  { chinese: "刻", pinyin: "kè", english: "moment", category: null },
  { chinese: "课", pinyin: "kè", english: "course", category: null },
  { chinese: "客人", pinyin: "kèrén", english: "Guest", category: null },
  { chinese: "空调", pinyin: "kōngtiáo", english: "Air conditioner", category: null },
  { chinese: "口", pinyin: "kǒu", english: "mouth", category: null },
  { chinese: "哭", pinyin: "kū", english: "cry", category: null },
  { chinese: "裤子", pinyin: "kùzi", english: "trousers", category: null },
  { chinese: "块", pinyin: "kuài", english: "block", category: null },
  { chinese: "快", pinyin: "kuài", english: "fast", category: null },
  { chinese: "快乐", pinyin: "kuàilè", english: "happy", category: null },
  { chinese: "筷子", pinyin: "kuàizi", english: "chopsticks", category: null },
  { chinese: "来", pinyin: "lái", english: "come", category: null },
  { chinese: "蓝", pinyin: "lán", english: "blue", category: null },
  { chinese: "老", pinyin: "lǎo", english: "old", category: null },
  { chinese: "老师", pinyin: "lǎoshī", english: "Teacher", category: null },
  { chinese: "了", pinyin: "le", english: null, category: null },
  { chinese: "累", pinyin: "lèi", english: "tired", category: null },
  { chinese: "冷", pinyin: "lěng", english: "cold", category: null },
  { chinese: "离", pinyin: "lí", english: "leave", category: null },
  { chinese: "离开", pinyin: "líkāi", english: "leave", category: null },
  { chinese: "里", pinyin: "lǐ", english: "in", category: null },
  { chinese: "礼物", pinyin: "lǐwù", english: "gift", category: null },
  { chinese: "历史", pinyin: "lìshǐ", english: "History", category: null },
  { chinese: "脸", pinyin: "liǎn", english: "face", category: null },
  { chinese: "练习", pinyin: "liànxí", english: "Practice", category: null },
  { chinese: "两", pinyin: "liǎng", english: "Two", category: null },
  { chinese: "辆", pinyin: "liàng", english: "Car", category: null },
  { chinese: "了解", pinyin: "liǎojiě", english: "understand", category: null },
  { chinese: "邻居", pinyin: "línjū", english: "neighbor", category: null },
  { chinese: "零", pinyin: "líng", english: "Zero", category: null },
  { chinese: "六", pinyin: "liù", english: "Six", category: null },
  { chinese: "楼", pinyin: "lóu", english: "floor", category: null },
  { chinese: "路", pinyin: "lù", english: "road", category: null },
  { chinese: "旅游", pinyin: "lǚyóu", english: "Tourism", category: null },
  { chinese: "绿", pinyin: "lǜ", english: "green", category: null },
  { chinese: "妈妈", pinyin: "māma", english: "Mom", category: null },
  { chinese: "马", pinyin: "mǎ", english: "Horse", category: null },
  { chinese: "马上", pinyin: "mǎshàng", english: "Right off", category: null },
  { chinese: "吗", pinyin: "ma", english: null, category: null },
  { chinese: "买", pinyin: "mǎi", english: "buy", category: null },
  { chinese: "卖", pinyin: "mài", english: "sell", category: null },
  { chinese: "满意", pinyin: "mǎnyì", english: "Satisfied", category: null },
  { chinese: "慢", pinyin: "màn", english: "slow", category: null },
  { chinese: "忙", pinyin: "máng", english: "busy", category: null },
  { chinese: "猫", pinyin: "māo", english: "cat", category: null },
  { chinese: "帽子", pinyin: "màozi", english: "Hat", category: null },
  { chinese: "没", pinyin: "méi", english: "no", category: null },
  { chinese: "没关系", pinyin: "méiguānxi", english: "No problem", category: null },
  { chinese: "每", pinyin: "měi", english: "each", category: null },
  { chinese: "妹妹", pinyin: "mèimei", english: "Younger sister", category: null },
  { chinese: "门", pinyin: "mén", english: "door", category: null },
  { chinese: "米", pinyin: "mǐ", english: "rice", category: null },
  { chinese: "米饭", pinyin: "mǐfàn", english: "Steamed Rice", category: null },
  { chinese: "面包", pinyin: "miànbāo", english: "Bread", category: null },
  { chinese: "面条", pinyin: "miàntiáo", english: "noodle", category: null },
  { chinese: "明白", pinyin: "míngbai", english: "clear", category: null },
  { chinese: "明天", pinyin: "míngtiān", english: "Tomorrow", category: null },
  { chinese: "名字", pinyin: "míngzi", english: "Name", category: null },
  { chinese: "拿", pinyin: "ná", english: "take", category: null },
  { chinese: "哪", pinyin: "nǎ", english: "which", category: null },
  { chinese: "那", pinyin: "nà", english: "that", category: null },
  { chinese: "奶奶", pinyin: "nǎinai", english: "grandma", category: null },
  { chinese: "南", pinyin: "nán", english: "south", category: null },
  { chinese: "男人", pinyin: "nánrén", english: "Man", category: null },
  { chinese: "难", pinyin: "nán", english: "difficult", category: null },
  { chinese: "难过", pinyin: "nánguò", english: "sad", category: null },
  { chinese: "呢", pinyin: "ne", english: null, category: null },
  { chinese: "能", pinyin: "néng", english: "can", category: null },
  { chinese: "你", pinyin: "nǐ", english: "you", category: null },
  { chinese: "年", pinyin: "nián", english: "year", category: null },
  { chinese: "年级", pinyin: "niánjí", english: "grade", category: null },
  { chinese: "年轻", pinyin: "niánqīng", english: "Young", category: null },
  { chinese: "鸟", pinyin: "niǎo", english: "bird", category: null },
  { chinese: "您", pinyin: "nín", english: "you", category: null },
  { chinese: "牛奶", pinyin: "niúnǎi", english: "milk", category: null },
  { chinese: "努力", pinyin: "nǔlì", english: "Strive", category: null },
  { chinese: "女儿", pinyin: "nǚ'ér", english: "daughter", category: null },
  { chinese: "女人", pinyin: "nǚrén", english: "woman", category: null },
  { chinese: "爬山", pinyin: "páshān", english: "Mountain climbing", category: null },
  { chinese: "盘子", pinyin: "pánzi", english: "plate", category: null },
  { chinese: "旁边", pinyin: "pángbiān", english: "Side", category: null },
  { chinese: "胖", pinyin: "pàng", english: "fat", category: null },
  { chinese: "跑步", pinyin: "pǎobù", english: "Run", category: null },
  { chinese: "朋友", pinyin: "péngyou", english: "Friend", category: null },
  { chinese: "啤酒", pinyin: "píjiǔ", english: "Beer", category: null },
  { chinese: "便宜", pinyin: "piányi", english: "Cheap", category: null },
  { chinese: "票", pinyin: "piào", english: "ticket", category: null },
  { chinese: "漂亮", pinyin: "piàoliang", english: "Well done!", category: null },
  { chinese: "苹果", pinyin: "píngguǒ", english: "Apple", category: null },
  { chinese: "葡萄", pinyin: "pútao", english: "Grape", category: null },
  { chinese: "普通话", pinyin: "pǔtōnghuà", english: "Mandarin", category: null },
  { chinese: "七", pinyin: "qī", english: "Seven", category: null },
  { chinese: "妻子", pinyin: "qīzi", english: "Wife", category: null },
  { chinese: "其实", pinyin: "qíshí", english: "actually", category: null },
  { chinese: "其他", pinyin: "qítā", english: "Other", category: null },
  { chinese: "骑", pinyin: "qí", english: "ride", category: null },
  { chinese: "奇怪", pinyin: "qíguài", english: "strange", category: null },
  { chinese: "起床", pinyin: "qǐchuáng", english: "Get up", category: null },
  { chinese: "千", pinyin: "qiān", english: "thousand", category: null },
  { chinese: "铅笔", pinyin: "qiānbǐ", english: "pencil", category: null },
  { chinese: "钱", pinyin: "qián", english: "money", category: null },
  { chinese: "前面", pinyin: "qiánmiàn", english: "Front", category: null },
  { chinese: "清楚", pinyin: "qīngchu", english: "clear", category: null },
  { chinese: "晴", pinyin: "qíng", english: "Sunny", category: null },
  { chinese: "请", pinyin: "qǐng", english: "please", category: null },
  { chinese: "秋", pinyin: "qiū", english: "autumn", category: null },
  { chinese: "去", pinyin: "qù", english: "go", category: null },
  { chinese: "去年", pinyin: "qùnián", english: "Last year", category: null },
  { chinese: "裙子", pinyin: "qúnzi", english: "skirt", category: null },
  { chinese: "然后", pinyin: "ránhòu", english: "Then", category: null },
  { chinese: "让", pinyin: "ràng", english: "Give Way", category: null },
  { chinese: "热", pinyin: "rè", english: "hot", category: null },
  { chinese: "热情", pinyin: "rèqíng", english: "Enthusiasm", category: null },
  { chinese: "人", pinyin: "rén", english: "people, person", category: null },
  { chinese: "认识", pinyin: "rènshi", english: "know", category: null },
  { chinese: "认为", pinyin: "rènwéi", english: "think", category: null },
  { chinese: "认真", pinyin: "rènzhēn", english: "earnest", category: null },
  { chinese: "日", pinyin: "rì", english: "day", category: null },
  { chinese: "容易", pinyin: "róngyì", english: "easily", category: null },
  { chinese: "如果", pinyin: "rúguǒ", english: "If", category: null },
  { chinese: "三", pinyin: "sān", english: "Three", category: null },
  { chinese: "伞", pinyin: "sǎn", english: "umbrella", category: null },
  { chinese: "商店", pinyin: "shāngdiàn", english: "Shop", category: null },
  { chinese: "上", pinyin: "shàng", english: "upper", category: null },
  { chinese: "上班", pinyin: "shàngbān", english: "go to work", category: null },
  { chinese: "上网", pinyin: "shàngwǎng", english: "Surf the Internet", category: null },
  { chinese: "上午", pinyin: "shàngwǔ", english: "morning", category: null },
  { chinese: "少", pinyin: "shǎo", english: "less", category: null },
  { chinese: "谁", pinyin: "shéi", english: "who", category: null },
  { chinese: "身体", pinyin: "shēntǐ", english: "body", category: null },
  { chinese: "什么", pinyin: "shénme", english: "What", category: null },
  { chinese: "生病", pinyin: "shēngbìng", english: "Fall ill", category: null },
  { chinese: "生气", pinyin: "shēngqì", english: "get angry", category: null },
  { chinese: "生日", pinyin: "shēngrì", english: "Birthday", category: null },
  { chinese: "声音", pinyin: "shēngyīn", english: "voice", category: null },
  { chinese: "十", pinyin: "shí", english: "Ten", category: null },
  { chinese: "时候", pinyin: "shíhou", english: "time", category: null },
  { chinese: "时间", pinyin: "shíjiān", english: "time", category: null },
  { chinese: "使", pinyin: "shǐ", english: "make", category: null },
  { chinese: "是", pinyin: "shì", english: "yes", category: null },
  { chinese: "世界", pinyin: "shìjiè", english: "world", category: null },
  { chinese: "事情", pinyin: "shìqing", english: "Thing", category: null },
  { chinese: "手表", pinyin: "shǒubiǎo", english: "Wrist Watch", category: null },
  { chinese: "手机", pinyin: "shǒujī", english: "Mobile phone", category: null },
  { chinese: "瘦", pinyin: "shòu", english: "thin", category: null },
  { chinese: "书", pinyin: "shū", english: "book", category: null },
  { chinese: "舒服", pinyin: "shūfu", english: "comfortable", category: null },
  { chinese: "叔叔", pinyin: "shūshu", english: "uncle", category: null },
  { chinese: "树", pinyin: "shù", english: "tree", category: null },
  { chinese: "数学", pinyin: "shùxué", english: "Mathematics", category: null },
  { chinese: "刷牙", pinyin: "shuāyá", english: "Brush one's teeth", category: null },
  { chinese: "双", pinyin: "shuāng", english: "double, pair", category: null },
  { chinese: "水", pinyin: "shuǐ", english: "water", category: null },
  { chinese: "水果", pinyin: "shuǐguǒ", english: "Fruits", category: null },
  { chinese: "水平", pinyin: "shuǐpíng", english: "level", category: null },
  { chinese: "睡觉", pinyin: "shuìjiào", english: "sleep", category: null },
  { chinese: "说话", pinyin: "shuōhuà", english: "talk", category: null },
  { chinese: "司机", pinyin: "sījī", english: "Driver", category: null },
  { chinese: "四", pinyin: "sì", english: "Four", category: null },
  { chinese: "送", pinyin: "sòng", english: "give", category: null },
  { chinese: "虽然", pinyin: "suīrán", english: "although", category: null },
  { chinese: "岁", pinyin: "suì", english: "year", category: null },
  { chinese: "所以", pinyin: "suǒyǐ", english: "therefore", category: null },
  { chinese: "他", pinyin: "tā", english: "he", category: null },
  { chinese: "她", pinyin: "tā", english: "she", category: null },
  { chinese: "它", pinyin: "tā", english: "it", category: null },
  { chinese: "太", pinyin: "tài", english: "too", category: null },
  { chinese: "太阳", pinyin: "tàiyáng", english: "sun", category: null },
  { chinese: "糖", pinyin: "táng", english: "sugar", category: null },
  { chinese: "特别", pinyin: "tèbié", english: "Especially", category: null },
  { chinese: "疼", pinyin: "téng", english: "hurt", category: null },
  { chinese: "踢足球", pinyin: "tīzúqiú", english: "Play football", category: null },
  { chinese: "题", pinyin: "tí", english: "topic", category: null },
  { chinese: "提高", pinyin: "tígāo", english: "increase", category: null },
  { chinese: "体育", pinyin: "tǐyù", english: "Sports", category: null },
  { chinese: "天气", pinyin: "tiānqì", english: "weather", category: null },
  { chinese: "甜", pinyin: "tián", english: "sweet", category: null },
  { chinese: "条", pinyin: "tiáo", english: "strip", category: null },
  { chinese: "跳舞", pinyin: "tiàowǔ", english: "dance", category: null },
  { chinese: "听", pinyin: "tīng", english: "hear", category: null },
  { chinese: "同事", pinyin: "tóngshì", english: "Colleague", category: null },
  { chinese: "同学", pinyin: "tóngxué", english: "Classmate", category: null },
  { chinese: "同意", pinyin: "tóngyì", english: "Agree", category: null },
  { chinese: "头发", pinyin: "tóufa", english: "Hair", category: null },
  { chinese: "突然", pinyin: "tūrán", english: "suddenly", category: null },
  { chinese: "图书馆", pinyin: "túshūguǎn", english: "Library", category: null },
  { chinese: "腿", pinyin: "tuǐ", english: "leg", category: null },
  { chinese: "外", pinyin: "wài", english: "abroad, outside", category: null },
  { chinese: "完", pinyin: "wán", english: "finish", category: null },
  { chinese: "完成", pinyin: "wánchéng", english: "complete", category: null },
  { chinese: "玩", pinyin: "wán", english: "play", category: null },
  { chinese: "碗", pinyin: "wǎn", english: "bowl", category: null },
  { chinese: "晚上", pinyin: "wǎnshang", english: "Night", category: null },
  { chinese: "万", pinyin: "wàn", english: "ten thousand", category: null },
  { chinese: "忘记", pinyin: "wàngjì", english: "forget", category: null },
  { chinese: "喂", pinyin: "wèi", english: "feed", category: null },
  { chinese: "为", pinyin: "wèi", english: "for", category: null },
  { chinese: "为了", pinyin: "wèile", english: "in order to", category: null },
  { chinese: "为什么", pinyin: "wèishénme", english: "Why", category: null },
  { chinese: "位", pinyin: "wèi", english: "position", category: null },
  { chinese: "文化", pinyin: "wénhuà", english: "Culture", category: null },
  { chinese: "问", pinyin: "wèn", english: "ask", category: null },
  { chinese: "问题", pinyin: "wèntí", english: "problem", category: null },
  { chinese: "我", pinyin: "wǒ", english: "I", category: null },
  { chinese: "我们", pinyin: "wǒmen", english: "We", category: null },
  { chinese: "五", pinyin: "wǔ", english: "Five", category: null },
  { chinese: "西", pinyin: "xī", english: "west", category: null },
  { chinese: "西瓜", pinyin: "xīguā", english: "watermelon", category: null },
  { chinese: "希望", pinyin: "xīwàng", english: "hope", category: null },
  { chinese: "习惯", pinyin: "xíguàn", english: "Habit", category: null },
  { chinese: "洗", pinyin: "xǐ", english: "wash", category: null },
  { chinese: "洗手间", pinyin: "xǐshǒujiān", english: "Restroom", category: null },
  { chinese: "洗澡", pinyin: "xǐzǎo", english: "Take a shower", category: null },
  { chinese: "喜欢", pinyin: "xǐhuan", english: "like", category: null },
  { chinese: "下", pinyin: "xià", english: "lower, down", category: null },
  { chinese: "下午", pinyin: "xiàwǔ", english: "Afternoon", category: null },
  { chinese: "下雨", pinyin: "xiàyǔ", english: "rain", category: null },
  { chinese: "夏", pinyin: "xià", english: "summer", category: null },
  { chinese: "先", pinyin: "xiān", english: "first", category: null },
  { chinese: "先生", pinyin: "xiānsheng", english: "Sir", category: null },
  { chinese: "现在", pinyin: "xiànzài", english: "Now", category: null },
  { chinese: "香蕉", pinyin: "xiāngjiāo", english: "Banana", category: null },
  { chinese: "相同", pinyin: "xiāngtóng", english: "identical", category: null },
  { chinese: "相信", pinyin: "xiāngxìn", english: "believe", category: null },
  { chinese: "想", pinyin: "xiǎng", english: "think", category: null },
  { chinese: "向", pinyin: "xiàng", english: "towards", category: null },
  { chinese: "像", pinyin: "xiàng", english: "image", category: null },
  { chinese: "小", pinyin: "xiǎo", english: "Small", category: null },
  { chinese: "小姐", pinyin: "xiǎojiě", english: "Miss", category: null },
  { chinese: "小时", pinyin: "xiǎoshí", english: "hour", category: null },
  { chinese: "小心", pinyin: "xiǎoxīn", english: "watch out", category: null },
  { chinese: "笑", pinyin: "xiào", english: "laugh, smile", category: null },
  { chinese: "校长", pinyin: "xiàozhǎng", english: "Principal", category: null },
  { chinese: "些", pinyin: "xiē", english: "some", category: null },
  { chinese: "鞋", pinyin: "xié", english: "shoes", category: null },
  { chinese: "写", pinyin: "xiě", english: "write", category: null },
  { chinese: "谢谢", pinyin: "xièxie", english: "Thank you", category: null },
  { chinese: "新", pinyin: "xīn", english: "new", category: null },
  { chinese: "新闻", pinyin: "xīnwén", english: "news", category: null },
  { chinese: "新鲜", pinyin: "xīnxiān", english: "fresh", category: null },
  { chinese: "信", pinyin: "xìn", english: "letter", category: null },
  { chinese: "星期", pinyin: "xīngqī", english: "week", category: null },
  { chinese: "行李箱", pinyin: "xínglixiāng", english: "Trunk", category: null },
  { chinese: "姓", pinyin: "xìng", english: "surname", category: null },
  { chinese: "兴趣", pinyin: "xìngqù", english: "Interest", category: null },
  { chinese: "熊猫", pinyin: "xióngmāo", english: "Panda", category: null },
  { chinese: "休息", pinyin: "xiūxi", english: "Rest", category: null },
  { chinese: "需要", pinyin: "xūyào", english: "Need", category: null },
  { chinese: "选择", pinyin: "xuǎnzé", english: "Choice", category: null },
  { chinese: "学生", pinyin: "xuésheng", english: "Student", category: null },
  { chinese: "学习", pinyin: "xuéxí", english: "Study", category: null },
  { chinese: "学校", pinyin: "xuéxiào", english: "School", category: null },
  { chinese: "雪", pinyin: "xuě", english: "Snow", category: null },
  { chinese: "颜色", pinyin: "yánsè", english: "colour", category: null },
  { chinese: "眼镜", pinyin: "yǎnjìng", english: "glasses", category: null },
  { chinese: "眼睛", pinyin: "yǎnjing", english: "Eye", category: null },
  { chinese: "羊肉", pinyin: "yángròu", english: "mutton", category: null },
  { chinese: "要求", pinyin: "yāoqiú", english: "Requirement", category: null },
  { chinese: "药", pinyin: "yào", english: "drug", category: null },
  { chinese: "要", pinyin: "yào", english: "want", category: null },
  { chinese: "爷爷", pinyin: "yéye", english: "grandpa", category: null },
  { chinese: "也", pinyin: "yě", english: "also", category: null },
  { chinese: "一", pinyin: "yī", english: "One", category: null },
  { chinese: "衣服", pinyin: "yīfu", english: "clothes", category: null },
  { chinese: "医生", pinyin: "yīshēng", english: "Doctor", category: null },
  { chinese: "医院", pinyin: "yīyuàn", english: "Hospital", category: null },
  { chinese: "一定", pinyin: "yídìng", english: "Certain", category: null },
  { chinese: "一共", pinyin: "yígòng", english: "Altogether", category: null },
  { chinese: "一会儿", pinyin: "yíhuìr", english: "a while", category: null },
  { chinese: "一样", pinyin: "yíyàng", english: "equally", category: null },
  { chinese: "以后", pinyin: "yǐhòu", english: "In the future", category: null },
  { chinese: "以前", pinyin: "yǐqián", english: "before", category: null },
  { chinese: "以为", pinyin: "yǐwéi", english: "Think", category: null },
  { chinese: "已经", pinyin: "yǐjīng", english: "Already", category: null },
  { chinese: "椅子", pinyin: "yǐzi", english: "Chair", category: null },
  { chinese: "一般", pinyin: "yìbān", english: "commonly", category: null },
  { chinese: "一边", pinyin: "yìbiān", english: "One side", category: null },
  { chinese: "一起", pinyin: "yìqǐ", english: "together", category: null },
  { chinese: "一直", pinyin: "yìzhí", english: "always", category: null },
  { chinese: "意思", pinyin: "yìsi", english: "Meaning", category: null },
  { chinese: "阴", pinyin: "yīn", english: "Yin", category: null },
  { chinese: "因为", pinyin: "yīnwèi", english: "because", category: null },
  { chinese: "音乐", pinyin: "yīnyuè", english: "Music", category: null },
  { chinese: "银行", pinyin: "yínháng", english: "Bank", category: null },
  { chinese: "应该", pinyin: "yīnggāi", english: "Should", category: null },
  { chinese: "影响", pinyin: "yǐngxiǎng", english: "Influence", category: null },
  { chinese: "用", pinyin: "yòng", english: "use", category: null },
  { chinese: "游戏", pinyin: "yóuxì", english: "Game", category: null },
  { chinese: "游泳", pinyin: "yóuyǒng", english: "Swimming", category: null },
  { chinese: "有", pinyin: "yǒu", english: "have", category: null },
  { chinese: "有名", pinyin: "yǒumíng", english: "Famous", category: null },
  { chinese: "又", pinyin: "yòu", english: "again", category: null },
  { chinese: "右边", pinyin: "yòubian", english: "Right", category: null },
  { chinese: "鱼", pinyin: "yú", english: "fish", category: null },
  { chinese: "遇到", pinyin: "yùdào", english: "encounter", category: null },
  { chinese: "元", pinyin: "yuán", english: "element; yuan", category: null },
  { chinese: "远", pinyin: "yuǎn", english: "far", category: null },
  { chinese: "愿意", pinyin: "yuànyì", english: "Be willing", category: null },
  { chinese: "月", pinyin: "yuè", english: "month", category: null },
  { chinese: "月亮", pinyin: "yuèliang", english: "Moon", category: null },
  { chinese: "越", pinyin: "yuè", english: "the more", category: null },
  { chinese: "云", pinyin: "yún", english: "cloud", category: null },
  { chinese: "运动", pinyin: "yùndòng", english: "excercise", category: null },
  { chinese: "在", pinyin: "zài", english: "stay; in process of", category: null },
  { chinese: "再", pinyin: "zài", english: "again", category: null },
  { chinese: "再见", pinyin: "zàijiàn", english: "Bye", category: null },
  { chinese: "早上", pinyin: "zǎoshang", english: "Morning", category: null },
  { chinese: "怎么", pinyin: "zěnme", english: "How", category: null },
  { chinese: "怎么样", pinyin: "zěnmeyàng", english: "How about", category: null },
  { chinese: "站", pinyin: "zhàn", english: "station", category: null },
  { chinese: "张", pinyin: "zhāng", english: "Zhang (surname)", category: null },
  { chinese: "长", pinyin: "zhǎng", english: "grow", category: null },
  { chinese: "丈夫", pinyin: "zhàngfu", english: "husband", category: null },
  { chinese: "着急", pinyin: "zháojí", english: "Worry", category: null },
  { chinese: "找", pinyin: "zhǎo", english: "look for", category: null },
  { chinese: "照顾", pinyin: "zhàogù", english: "look after", category: null },
  { chinese: "照片", pinyin: "zhàopiàn", english: "Photo", category: null },
  { chinese: "照相机", pinyin: "zhàoxiàngjī", english: "Camera", category: null },
  { chinese: "这", pinyin: "zhè", english: "this", category: null },
  { chinese: "着", pinyin: "zhe", english: null, category: null },
  { chinese: "真", pinyin: "zhēn", english: "real, true", category: null },
  { chinese: "正在", pinyin: "zhèngzài", english: "in process of", category: null },
  { chinese: "知道", pinyin: "zhīdào", english: "know", category: null },
  { chinese: "只", pinyin: "zhǐ", english: "only", category: null },
  { chinese: "中国", pinyin: "zhōngguó", english: "China", category: null },
  { chinese: "中间", pinyin: "zhōngjiān", english: "Middle", category: null },
  { chinese: "中午", pinyin: "zhōngwǔ", english: "Noon", category: null },
  { chinese: "终于", pinyin: "zhōngyú", english: "finally", category: null },
  { chinese: "种", pinyin: "zhǒng", english: "species", category: null },
  { chinese: "重要", pinyin: "zhòngyào", english: "important", category: null },
  { chinese: "周末", pinyin: "zhōumò", english: "Weekend", category: null },
  { chinese: "主要", pinyin: "zhǔyào", english: "main", category: null },
  { chinese: "住", pinyin: "zhù", english: "live", category: null },
  { chinese: "祝", pinyin: "zhù", english: "wish", category: null },
  { chinese: "注意", pinyin: "zhùyì", english: "Be careful", category: null },
  { chinese: "准备", pinyin: "zhǔnbèi", english: "prepare", category: null },
  { chinese: "桌子", pinyin: "zhuōzi", english: "Table", category: null },
  { chinese: "字", pinyin: "zì", english: "character", category: null },
  { chinese: "字典", pinyin: "zìdiǎn", english: "Dictionaries", category: null },
  { chinese: "自己", pinyin: "zìjǐ", english: "Own, self", category: null },
  { chinese: "自行车", pinyin: "zìxíngchē", english: "Bicycle", category: null },
  { chinese: "总是", pinyin: "zǒngshì", english: "always", category: null },
  { chinese: "走", pinyin: "zǒu", english: "go， walk", category: null },
  { chinese: "最", pinyin: "zuì", english: "most", category: null },
  { chinese: "最近", pinyin: "zuìjìn", english: "lately", category: null },
  { chinese: "昨天", pinyin: "zuótiān", english: "Yesterday", category: null },
  { chinese: "左边", pinyin: "zuǒbian", english: "left", category: null },
  { chinese: "坐", pinyin: "zuò", english: "sit", category: null },
  { chinese: "做", pinyin: "zuò", english: "do", category: null },
  { chinese: "作业", pinyin: "zuòyè", english: "task", category: null },
  { chinese: "作用", pinyin: "zuòyòng", english: "Effect", category: null },
  { chinese: "词典", pinyin: "cídiǎn", english: "dictionary", category: "Noun" },
  { chinese: "笔记本", pinyin: "bǐjìběn", english: "notebook", category: "Noun" },
  { chinese: "笔记本电脑", pinyin: "bǐjìběn diànnǎo", english: "laptop", category: "Noun" },
  { chinese: "感兴趣", pinyin: "gǎn xìngqù", english: "to be interested in", category: null },
  { chinese: "个子", pinyin: "gèzi", english: "height, stature", category: "Noun" },
  { chinese: "后来", pinyin: "hòulái", english: "later, afterwards", category: "Noun" },
  { chinese: "聊天（儿）", pinyin: "liáotiān(r)", english: "to chat", category: "Verb" },
  { chinese: "留学", pinyin: "liú xué", english: "to study abroad", category: "Verb" },
  { chinese: "皮鞋", pinyin: "píxié", english: "leather shoes", category: "Noun" },
  { chinese: "瓶子", pinyin: "píngzi", english: "bottle", category: "Noun" },
  { chinese: "起飞", pinyin: "qǐfēi", english: "(of an aircraft) to take off", category: "Verb" },
  { chinese: "起来", pinyin: "qǐlai", english: "(indicating an upward movement) to rise", category: "Verb" },
  { chinese: "请假", pinyin: "qǐng jià", english: "to ask for leave", category: "Verb" },
  { chinese: "试", pinyin: "shì", english: "to try", category: "Verb" },
  { chinese: "信用卡", pinyin: "xìnyòngkǎ", english: "credit card", category: "Noun" },
  { chinese: "饮料", pinyin: "yǐnliào", english: "drink, beverage", category: "Noun" },
  { chinese: "嘴", pinyin: "zuǐ", english: "mouth", category: "Noun" },
  { chinese: "最后", pinyin: "zuìhòu", english: "the last one", category: "Noun" },
  { chinese: "只", pinyin: "zhī", english: "used for certain animals", category: "Quantifier" },
  { chinese: "这儿", pinyin: "zhèr", english: "here", category: null },
  { chinese: "那儿", pinyin: "nàr", english: "there", category: null },
  { chinese: "哪儿", pinyin: "nǎr", english: "where", category: null },
];
