import type { TranscriptLineRow } from "./extract-transcripts";

// HSK3 chapters' actual dialog transcripts — docs/25-chapter-all-words
// -plan.md's addendum. Auto-extracted (scripts-tmp-extract-transcripts.ts)
// from the same pasted textbook dialog text the All Words vocabulary was
// segmented from — this captures the full sentences (speaker, pinyin,
// English) rather than just the words used in them.

export interface Hsk3ChapterTranscriptData {
  chapterNumber: number;
  lines: TranscriptLineRow[];
}

export const HSK3_CHAPTER_TRANSCRIPTS: Hsk3ChapterTranscriptData[] = [
  {
    chapterNumber: 1,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "Talking about the plan for the weekend", speaker: "小丽", chinese: "周末你有什么打算？", pinyin: "Zhōumò nǐ yǒu shénme dǎsuàn?", english: "What's your plan for the weekend?" },
      { order: 2, dialogNumber: 1, dialogLabel: "Talking about the plan for the weekend", speaker: "小刚", chinese: "我早就想好了，请你吃饭、看电影、喝咖啡。", pinyin: "Wǒ zǎo jiù xiǎnghǎo le, qǐng nǐ chī fàn, kàn diànyǐng, hē kāfēi.", english: "I've already planned it: I'll treat you to a meal, a movie, and coffee." },
      { order: 3, dialogNumber: 1, dialogLabel: "Talking about the plan for the weekend", speaker: "小丽", chinese: "请我？", pinyin: "Qǐng wǒ?", english: "Treat me?" },
      { order: 4, dialogNumber: 1, dialogLabel: "Talking about the plan for the weekend", speaker: "小刚", chinese: "是啊，我已经找好饭馆了，电影票也买好了。", pinyin: "Shì a, wǒ yǐjīng zhǎohǎo fànguǎnr le, diànyǐngpiào yě mǎihǎo le.", english: "Yes, I've already found a restaurant and bought the movie tickets." },
      { order: 5, dialogNumber: 1, dialogLabel: "Talking about the plan for the weekend", speaker: "小丽", chinese: "我还没想好要不要跟你去呢。", pinyin: "Wǒ hái méi xiǎnghǎo yào bu yào gēn nǐ qù ne.", english: "I haven't decided whether to go with you yet." },
      { order: 6, dialogNumber: 2, dialogLabel: "At home", speaker: "妈妈", chinese: "你一直玩儿电脑游戏，作业写完了吗？", pinyin: "Nǐ yìzhí wánr diànnǎo yóuxì, zuòyè xiěwán le ma?", english: "You've been playing computer games all the time. Have you finished your homework?" },
      { order: 7, dialogNumber: 2, dialogLabel: "At home", speaker: "儿子", chinese: "都写完了。", pinyin: "Dōu xiěwán le.", english: "I've finished it all." },
      { order: 8, dialogNumber: 2, dialogLabel: "At home", speaker: "妈妈", chinese: "明天不是有考试吗？你怎么一点儿也不着急？", pinyin: "Míngtiān bú shì yǒu kǎoshì ma? Nǐ zěnme yìdiǎnr yě bù zháojí?", english: "Don't you have an exam tomorrow? Why aren't you worried at all?" },
      { order: 9, dialogNumber: 2, dialogLabel: "At home", speaker: "儿子", chinese: "我早就复习好了。", pinyin: "Wǒ zǎo jiù fùxí hǎo le.", english: "I've already reviewed everything." },
      { order: 10, dialogNumber: 2, dialogLabel: "At home", speaker: "妈妈", chinese: "那也不能一直玩儿啊。", pinyin: "Nà yě bù néng yìzhí wánr a.", english: "But you still can't play all the time." },
      { order: 11, dialogNumber: 3, dialogLabel: "Talking about the travel plan", speaker: "小丽", chinese: "下个月我去旅游，你能跟我一起去吗？", pinyin: "Xià ge yuè wǒ qù lǚyóu, nǐ néng gēn wǒ yìqǐ qù ma?", english: "I'm going traveling next month. Can you come with me?" },
      { order: 12, dialogNumber: 3, dialogLabel: "Talking about the travel plan", speaker: "小刚", chinese: "我还没想好呢。你觉得哪儿最好玩儿？", pinyin: "Wǒ hái méi xiǎnghǎo ne. Nǐ juéde nǎr zuì hǎowánr?", english: "I haven't decided yet. Where do you think is the most fun?" },
      { order: 13, dialogNumber: 3, dialogLabel: "Talking about the travel plan", speaker: "小丽", chinese: "南方啊，我们去年就是这个时候去的。", pinyin: "Nánfāng a, wǒmen qùnián jiù shì zhège shíhou qù de.", english: "The south! We went there at this time last year." },
      { order: 14, dialogNumber: 3, dialogLabel: "Talking about the travel plan", speaker: "小刚", chinese: "南方太热了，北方好一些，不冷也不热。", pinyin: "Nánfāng tài rè le, běifāng hǎo yìxiē, bù lěng yě bú rè.", english: "The south is too hot. The north is better – neither cold nor hot." },
      { order: 15, dialogNumber: 4, dialogLabel: "Preparing for their trip", speaker: "小刚", chinese: "水果、面包、茶都准备好了，我们还带什么？", pinyin: "Shuǐguǒ, miànbāo, chá dōu zhǔnbèi hǎo le, wǒmen hái dài shénme?", english: "The fruit, bread, and tea are all ready. What else should we bring?" },
      { order: 16, dialogNumber: 4, dialogLabel: "Preparing for their trip", speaker: "小丽", chinese: "手机、电脑、地图，一个也不能少。", pinyin: "Shǒujī, diànnǎo, dìtú, yí ge yě bù néng shǎo.", english: "Phone, computer, map – not one can be missing." },
      { order: 17, dialogNumber: 4, dialogLabel: "Preparing for their trip", speaker: "小刚", chinese: "这些我昨天下午就准备好了。", pinyin: "Zhèxiē wǒ zuótiān xiàwǔ jiù zhǔnbèi hǎo le.", english: "I already prepared all these yesterday afternoon." },
      { order: 18, dialogNumber: 4, dialogLabel: "Preparing for their trip", speaker: "小丽", chinese: "再多带几件衣服吧。", pinyin: "Zài duō dài jǐ jiàn yīfu ba.", english: "Bring a few more clothes." },
      { order: 19, dialogNumber: 4, dialogLabel: "Preparing for their trip", speaker: "小刚", chinese: "我们是去旅游，不是搬家，还是少带一些吧。", pinyin: "Wǒmen shì qù lǚyóu, bú shì bān jiā, háishì shǎo dài yìxiē ba.", english: "We're going traveling, not moving house. Let's bring less." },
    ],
  },
  {
    chapterNumber: 2,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "On the way going down the mountain", speaker: "小丽", chinese: "休息一下吧。", pinyin: "Xiūxi yíxià ba.", english: "Let's take a rest." },
      { order: 2, dialogNumber: 1, dialogLabel: "On the way going down the mountain", speaker: "小刚", chinese: "怎么了？", pinyin: "Zěnme le?", english: "What's wrong?" },
      { order: 3, dialogNumber: 1, dialogLabel: "On the way going down the mountain", speaker: "小丽", chinese: "我现在腿也疼，脚也疼。", pinyin: "Wǒ xiànzài tuǐ yě téng, jiǎo yě téng.", english: "My legs and feet hurt." },
      { order: 4, dialogNumber: 1, dialogLabel: "On the way going down the mountain", speaker: "小刚", chinese: "好，那边树多，我们过去坐一下吧。", pinyin: "Hǎo, nàbiān shù duō, wǒmen guòqu zuò yíxià ba.", english: "OK, there are many trees over there. Let's go sit for a while." },
      { order: 5, dialogNumber: 1, dialogLabel: "On the way going down the mountain", speaker: "小丽", chinese: "上来的时候我怎么没觉得这么累？", pinyin: "Shànglai de shíhou wǒ zěnme méi juéde zhème lèi?", english: "Why didn't I feel this tired when we were going up?" },
      { order: 6, dialogNumber: 1, dialogLabel: "On the way going down the mountain", speaker: "小刚", chinese: "上山容易下山难，你不知道？", pinyin: "Shàng shān róngyì xià shān nán, nǐ bù zhīdào?", english: "Going up is easy, going down is hard – didn't you know?" },
      { order: 7, dialogNumber: 2, dialogLabel: "On the phone", speaker: "周太太", chinese: "喂，你好，请问周明在吗？", pinyin: "Wèi, nǐ hǎo, qǐngwèn Zhōu Míng zài ma?", english: "Hello, may I speak to Zhou Ming?" },
      { order: 8, dialogNumber: 2, dialogLabel: "On the phone", speaker: "秘书", chinese: "周经理出去了，不在办公室。", pinyin: "Zhōu jīnglǐ chūqu le, bú zài bàngōngshì.", english: "Manager Zhou has gone out. He's not in the office." },
      { order: 9, dialogNumber: 2, dialogLabel: "On the phone", speaker: "周太太", chinese: "他去哪儿了？什么时候回来？", pinyin: "Tā qù nǎr le? Shénme shíhou huílai?", english: "Where did he go? When will he be back?" },
      { order: 10, dialogNumber: 2, dialogLabel: "On the phone", speaker: "秘书", chinese: "他出去办事了，下午回来。", pinyin: "Tā chūqu bàn shì le, xiàwǔ huílai.", english: "He went out on business. He'll be back this afternoon." },
      { order: 11, dialogNumber: 2, dialogLabel: "On the phone", speaker: "周太太", chinese: "回来了就让他给我打个电话。", pinyin: "Huílai le jiù ràng tā gěi wǒ dǎ ge diànhuà.", english: "When he comes back, ask him to call me." },
      { order: 12, dialogNumber: 2, dialogLabel: "On the phone", speaker: "秘书", chinese: "好的，他到了办公室我就告诉他。", pinyin: "Hǎo de, tā dàole bàngōngshì wǒ jiù gàosu tā.", english: "OK, I'll tell him as soon as he gets to the office." },
      { order: 13, dialogNumber: 3, dialogLabel: "Parting at the exit of the building", speaker: "小刚", chinese: "雨下得真大。你怎么回去？我送你吧。", pinyin: "Yǔ xià de zhēn dà. Nǐ zěnme huíqu? Wǒ sòng nǐ ba.", english: "The rain is really heavy. How will you get back? I'll take you." },
      { order: 14, dialogNumber: 3, dialogLabel: "Parting at the exit of the building", speaker: "小丽", chinese: "没事，我出去叫辆出租车就行了。", pinyin: "Méi shì, wǒ chūqu jiào liàng chūzūchē jiù xíng le.", english: "It's OK. I'll just go out and get a taxi." },
      { order: 15, dialogNumber: 3, dialogLabel: "Parting at the exit of the building", speaker: "小刚", chinese: "那你等等，我上楼去给你拿把伞。", pinyin: "Nà nǐ děngdeng, wǒ shàng lóu qù gěi nǐ ná bǎ sǎn.", english: "Wait a moment. I'll go upstairs and get you an umbrella." },
      { order: 16, dialogNumber: 3, dialogLabel: "Parting at the exit of the building", speaker: "小丽", chinese: "好的。我跟你一起上去吧。", pinyin: "Hǎo de. Wǒ gēn nǐ yìqǐ shàngqu ba.", english: "OK. I'll go up with you." },
      { order: 17, dialogNumber: 3, dialogLabel: "Parting at the exit of the building", speaker: "小刚", chinese: "你在这儿等吧，我拿了伞就下来。", pinyin: "Nǐ zài zhèr děng ba, wǒ nále sǎn jiù xiàlai.", english: "Wait here. I'll come right down after I get the umbrella." },
      { order: 18, dialogNumber: 4, dialogLabel: "At home", speaker: "周太太", chinese: "你看，我这么胖，怎么办呢？", pinyin: "Nǐ kàn, wǒ zhème pàng, zěnme bàn ne?", english: "Look, I'm so fat. What should I do?" },
      { order: 19, dialogNumber: 4, dialogLabel: "At home", speaker: "周明", chinese: "你每天晚上吃了饭就睡觉，也不出去走走，能不胖吗？", pinyin: "Nǐ měi tiān wǎnshang chīle fàn jiù shuìjiào, yě bù chūqu zǒuzou, néng bú pàng ma?", english: "You go to bed right after dinner every night and don't go out for a walk. How could you not get fat?" },
      { order: 20, dialogNumber: 4, dialogLabel: "At home", speaker: "周太太", chinese: "其实我每天都运动。", pinyin: "Qíshí wǒ měi tiān dōu yùndòng.", english: "Actually, I exercise every day." },
      { order: 21, dialogNumber: 4, dialogLabel: "At home", speaker: "周明", chinese: "但是你一点儿也没瘦！你做什么运动了？", pinyin: "Dànshì nǐ yìdiǎnr yě méi shòu! Nǐ zuò shénme yùndòng le?", english: "But you haven't lost any weight! What exercise do you do?" },
      { order: 22, dialogNumber: 4, dialogLabel: "At home", speaker: "周太太", chinese: "做饭啊。", pinyin: "Zuò fàn a.", english: "Cooking!" },
    ],
  },
  {
    chapterNumber: 3,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "小刚", chinese: "明天是晴天还是阴天？", pinyin: "Míngtiān shì qíngtiān háishì yīntiān?", english: "Will it be sunny or cloudy tomorrow?" },
      { order: 2, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "小丽", chinese: "阴天，电视上说多云。怎么了？有事？", pinyin: "Yīntiān, diànshì shang shuō duōyún. Zěnme le? Yǒu shì?", english: "Cloudy. The TV says it'll be overcast. Why? Is something wrong?" },
      { order: 3, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "小刚", chinese: "没事，我们明天要去爬山。", pinyin: "Méi shì, wǒmen míngtiān yào qù pá shān.", english: "Nothing. We're going hiking tomorrow." },
      { order: 4, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "小丽", chinese: "爬山的时候要小心点儿。", pinyin: "Pá shān de shíhou yào xiǎoxīn diǎnr.", english: "Be careful when you hike." },
      { order: 5, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "小刚", chinese: "好，你也去吗？", pinyin: "Hǎo, nǐ yě qù ma?", english: "OK. Are you going too?" },
      { order: 6, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "小丽", chinese: "我不去，我有事。", pinyin: "Wǒ bú qù, wǒ yǒu shì.", english: "No, I have things to do." },
      { order: 7, dialogNumber: 2, dialogLabel: "In a mall", speaker: "周太太", chinese: "你觉得这条裤子怎么样？", pinyin: "Nǐ juéde zhè tiáo kùzi zěnmeyàng?", english: "What do you think of these pants?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In a mall", speaker: "周明", chinese: "我记得你已经有两条这样的裤子了。", pinyin: "Wǒ jìde nǐ yǐjīng yǒu liǎng tiáo zhèyàng de kùzi le.", english: "I remember you already have two pairs like this." },
      { order: 9, dialogNumber: 2, dialogLabel: "In a mall", speaker: "周太太", chinese: "那我们再看看别的。", pinyin: "Nà wǒmen zài kànkan biéde.", english: "Then let's look at others." },
      { order: 10, dialogNumber: 2, dialogLabel: "In a mall", speaker: "周明", chinese: "这件衬衫怎么样？", pinyin: "Zhè jiàn chènshān zěnmeyàng?", english: "How about this shirt?" },
      { order: 11, dialogNumber: 2, dialogLabel: "In a mall", speaker: "周太太", chinese: "还不错，多少钱？", pinyin: "Hái búcuò, duōshao qián?", english: "Not bad. How much is it?" },
      { order: 12, dialogNumber: 2, dialogLabel: "In a mall", speaker: "周明", chinese: "这上面写着320元。", pinyin: "Zhè shàngmian xiězhe sān bǎi èrshí yuán.", english: "It says 320 yuan here." },
      { order: 13, dialogNumber: 2, dialogLabel: "In a mall", speaker: "周太太", chinese: "买一件。", pinyin: "Mǎi yí jiàn.", english: "Buy it." },
      { order: 14, dialogNumber: 3, dialogLabel: "In a fruit store", speaker: "周太太", chinese: "这些水果真新鲜，我们买西瓜还是苹果？", pinyin: "Zhèxiē shuǐguǒ zhēn xīnxiān, wǒmen mǎi xīguā háishì píngguǒ?", english: "These fruits are really fresh. Should we buy watermelon or apples?" },
      { order: 15, dialogNumber: 3, dialogLabel: "In a fruit store", speaker: "周明", chinese: "西瓜吧。你看，这上面写着\"西瓜不甜不要钱\"。", pinyin: "Xīguā ba. Nǐ kàn, zhè shàngmian xiězhe \"xīguā bù tián bú yào qián\".", english: "Watermelon. Look, it says \"If it's not sweet, it's free.\"" },
      { order: 16, dialogNumber: 3, dialogLabel: "In a fruit store", speaker: "周太太", chinese: "那我们买一个大点儿的吧。", pinyin: "Nà wǒmen mǎi yí ge dà diǎnr de ba.", english: "Then let's buy a bigger one." },
      { order: 17, dialogNumber: 3, dialogLabel: "In a fruit store", speaker: "周明", chinese: "再买几个苹果。", pinyin: "Zài mǎi jǐ ge píngguǒ.", english: "Let's buy some apples too." },
      { order: 18, dialogNumber: 3, dialogLabel: "In a fruit store", speaker: "周太太", chinese: "好啊，今天晚上只吃水果不吃饭！", pinyin: "Hǎo a, jīntiān wǎnshang zhǐ chī shuǐguǒ bù chī fàn!", english: "Great! Tonight we'll only eat fruit, not dinner!" },
      { order: 19, dialogNumber: 4, dialogLabel: "In the lounge", speaker: "小丽", chinese: "桌子上放着很多饮料，你喝什么？", pinyin: "Zhuōzi shang fàngzhe hěn duō yǐnliào, nǐ hē shénme?", english: "There are many drinks on the table. What would you like?" },
      { order: 20, dialogNumber: 4, dialogLabel: "In the lounge", speaker: "小刚", chinese: "茶或者咖啡都可以。你呢？你喝什么？", pinyin: "Chá huòzhě kāfēi dōu kěyǐ. Nǐ ne? Nǐ hē shénme?", english: "Tea or coffee is fine. What about you?" },
      { order: 21, dialogNumber: 4, dialogLabel: "In the lounge", speaker: "小丽", chinese: "我喝茶，茶是我的最爱。天冷了或者工作累了的时候，喝杯热茶会很舒服。", pinyin: "Wǒ hē chá, chá shì wǒ de zuì ài. Tiān lěng le huòzhě gōngzuò lèi le de shíhou, hē bēi rè chá huì hěn shūfu.", english: "I'll have tea. Tea is my favorite. When it's cold or I'm tired from work, a cup of hot tea makes me feel comfortable." },
      { order: 22, dialogNumber: 4, dialogLabel: "In the lounge", speaker: "小刚", chinese: "你喜欢喝什么茶？", pinyin: "Nǐ xǐhuān hē shénme chá?", english: "What kind of tea do you like?" },
      { order: 23, dialogNumber: 4, dialogLabel: "In the lounge", speaker: "小丽", chinese: "花茶、绿茶、红茶，我都喜欢。", pinyin: "Huāchá, lǜchá, hóngchá, wǒ dōu xǐhuān.", english: "Scented tea, green tea, black tea – I like them all." },
    ],
  },
  {
    chapterNumber: 4,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "小明", chinese: "这是你们比赛的照片吗？", pinyin: "Zhè shì nǐmen bǐsài de zhàopiàn ma?", english: "Is this the photo from your competition?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "马可", chinese: "是，这是我们比赛后照的。", pinyin: "Shì, zhè shì wǒmen bǐsài hòu zhào de.", english: "Yes, it was taken after the competition." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "小明", chinese: "照得不错，你们都是一个年级的吗？", pinyin: "Zhào de búcuò, nǐmen dōu shì yí ge niánjí de ma?", english: "Looks good. Are you all in the same grade?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "马可", chinese: "不是。那个又高又漂亮的女孩儿是二年级的。", pinyin: "Bú shì. Nàge yòu gāo yòu piàoliang de nǚháir shì èr niánjí de.", english: "No. That tall and pretty girl is in second grade." },
      { order: 5, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "小明", chinese: "旁边那个拿着书笑的人是谁？", pinyin: "Pángbiān nàge ná zhe shū xiào de rén shì shéi?", english: "Who is that person next to her, holding a book and smiling?" },
      { order: 6, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "马可", chinese: "那是我！", pinyin: "Nà shì wǒ!", english: "That's me!" },
      { order: 7, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "小丽", chinese: "你觉得小红怎么样？", pinyin: "Nǐ juéde Xiǎo Hóng zěnmeyàng?", english: "What do you think of Xiaohong?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "同学", chinese: "她又聪明又热情，也很努力。", pinyin: "Tā yòu cōngmíng yòu rèqíng, yě hěn nǔlì.", english: "She's smart, warm, and hardworking." },
      { order: 9, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "小丽", chinese: "我看她总是笑着回答老师的问题。", pinyin: "Wǒ kàn tā zǒngshì xiàozhe huídá lǎoshī de wèntí.", english: "I see she always smiles when answering the teacher's questions." },
      { order: 10, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "同学", chinese: "她对每个人都笑，也常常对我笑。", pinyin: "Tā duì měi ge rén dōu xiào, yě chángcháng duì wǒ xiào.", english: "She smiles at everyone, and often at me too." },
      { order: 11, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "小丽", chinese: "你是不是喜欢她啊？", pinyin: "Nǐ shì bu shì xǐhuān tā a?", english: "Do you like her?" },
      { order: 12, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "同学", chinese: "喜欢她的人太多了，你看那些拿着鲜花站在门口的，都是等她的。", pinyin: "Xǐhuān tā de rén tài duō le, nǐ kàn nàxiē ná zhe xiānhuā zhàn zài ménkǒu de, dōu shì děng tā de.", english: "Too many people like her. Look at those standing at the door with flowers – they're all waiting for her." },
      { order: 13, dialogNumber: 3, dialogLabel: "At the entrance of a supermarket", speaker: "小刚", chinese: "我有点儿饿了，我们进超市买点儿东西吧。", pinyin: "Wǒ yǒudiǎnr è le, wǒmen jìn chāoshì mǎi diǎnr dōngxi ba.", english: "I'm a little hungry. Let's go into the supermarket and buy something." },
      { order: 14, dialogNumber: 3, dialogLabel: "At the entrance of a supermarket", speaker: "小丽", chinese: "好啊，这家超市的蛋糕又便宜又好吃，一块只要2.99元。", pinyin: "Hǎo a, zhè jiā chāoshì de dàngāo yòu piányi yòu hǎochī, yí kuài zhǐ yào èr diǎn jiǔ jiǔ yuán.", english: "Great. This supermarket's cakes are cheap and delicious – only 2.99 yuan each." },
      { order: 15, dialogNumber: 3, dialogLabel: "At the entrance of a supermarket", speaker: "小刚", chinese: "我们买两块，回家吃着蛋糕看电视，怎么样？", pinyin: "Wǒmen mǎi liǎng kuài, huí jiā chī zhe dàngāo kàn diànshì, zěnmeyàng?", english: "Let's buy two, go home, eat cake and watch TV. What do you think?" },
      { order: 16, dialogNumber: 3, dialogLabel: "At the entrance of a supermarket", speaker: "小丽", chinese: "好啊，我再去买一些喝的。", pinyin: "Hǎo a, wǒ zài qù mǎi yìxiē hē de.", english: "Great. I'll go buy some drinks too." },
      { order: 17, dialogNumber: 3, dialogLabel: "At the entrance of a supermarket", speaker: "小刚", chinese: "喝着咖啡吃蛋糕，太好了！", pinyin: "Hē zhe kāfēi chī dàngāo, tài hǎo le!", english: "Drinking coffee and eating cake – perfect!" },
      { order: 18, dialogNumber: 4, dialogLabel: "In a restaurant", speaker: "经理", chinese: "您好！您找谁？", pinyin: "Nín hǎo! Nín zhǎo shéi?", english: "Hello! Who are you looking for?" },
      { order: 19, dialogNumber: 4, dialogLabel: "In a restaurant", speaker: "客人", chinese: "你们这儿是不是有一个又年轻又漂亮的服务员？", pinyin: "Nǐmen zhèr shì bu shì yǒu yí ge yòu niánqīng yòu piàoliang de fúwùyuán?", english: "Do you have a young and pretty waitress here?" },
      { order: 20, dialogNumber: 4, dialogLabel: "In a restaurant", speaker: "经理", chinese: "我们这儿年轻、漂亮的服务员有很多。", pinyin: "Wǒmen zhèr niánqīng, piàoliang de fúwùyuán yǒu hěn duō.", english: "We have many young and pretty waitresses here." },
      { order: 21, dialogNumber: 4, dialogLabel: "In a restaurant", speaker: "客人", chinese: "她工作又认真又热情。", pinyin: "Tā gōngzuò yòu rènzhēn yòu rèqíng.", english: "She's serious and enthusiastic about her work." },
      { order: 22, dialogNumber: 4, dialogLabel: "In a restaurant", speaker: "经理", chinese: "您能再说说吗？", pinyin: "Nín néng zài shuōshuo ma?", english: "Can you describe her more?" },
      { order: 23, dialogNumber: 4, dialogLabel: "In a restaurant", speaker: "客人", chinese: "她总是笑着跟客人说话。", pinyin: "Tā zǒngshì xiàozhe gēn kèrén shuōhuà.", english: "She always smiles when talking to customers." },
      { order: 24, dialogNumber: 4, dialogLabel: "In a restaurant", speaker: "经理", chinese: "啊，我知道了，你说的是李小美吧？", pinyin: "A, wǒ zhīdào le, nǐ shuō de shì Lǐ Xiǎoměi ba?", english: "Ah, I know who you mean. You're talking about Li Xiaomei, right?" },
    ],
  },
  {
    chapterNumber: 5,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "朋友", chinese: "我听说你身体不舒服，怎么了？", pinyin: "Wǒ tīngshuō nǐ shēntǐ bù shūfu, zěnme le?", english: "I heard you're not feeling well. What's wrong?" },
      { order: 2, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "小丽", chinese: "前几天有点儿发烧，现在好多了。", pinyin: "Qián jǐ tiān yǒudiǎnr fāshāo, xiànzài hǎo duō le.", english: "I had a bit of a fever a few days ago. I'm much better now." },
      { order: 3, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "朋友", chinese: "喝杯茶吧，这是我为你买的绿茶，很不错。", pinyin: "Hē bēi chá ba, zhè shì wǒ wèi nǐ mǎi de lǜchá, hěn búcuò.", english: "Have some tea. This is green tea I bought for you. It's very good." },
      { order: 4, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "小丽", chinese: "谢谢，我要吃药，不喝茶了。", pinyin: "Xièxie, wǒ yào chī yào, bù hē chá le.", english: "Thanks, but I need to take medicine, so I can't drink tea." },
      { order: 5, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "朋友", chinese: "那喝杯水吧。", pinyin: "Nà hē bēi shuǐ ba.", english: "Then have some water." },
      { order: 6, dialogNumber: 1, dialogLabel: "At Xiaoli's home", speaker: "小丽", chinese: "好的。", pinyin: "Hǎo de.", english: "OK." },
      { order: 7, dialogNumber: 2, dialogLabel: "On the phone", speaker: "周太太", chinese: "对不起，我明天不能和你们出去玩儿了。", pinyin: "Duìbuqǐ, wǒ míngtiān bù néng hé nǐmen chūqu wánr le.", english: "Sorry, I can't go out with you tomorrow." },
      { order: 8, dialogNumber: 2, dialogLabel: "On the phone", speaker: "张太太", chinese: "为什么？怎么了？", pinyin: "Wèi shénme? Zěnme le?", english: "Why? What's wrong?" },
      { order: 9, dialogNumber: 2, dialogLabel: "On the phone", speaker: "周太太", chinese: "我儿子生病了，我要在家照顾他。", pinyin: "Wǒ érzi shēngbìng le, wǒ yào zài jiā zhàogù tā.", english: "My son is sick. I need to take care of him at home." },
      { order: 10, dialogNumber: 2, dialogLabel: "On the phone", speaker: "张太太", chinese: "他吃药了吗？要不要去医院？", pinyin: "Tā chī yào le ma? Yào bu yào qù yīyuàn?", english: "Has he taken medicine? Does he need to go to the hospital?" },
      { order: 11, dialogNumber: 2, dialogLabel: "On the phone", speaker: "周太太", chinese: "不用去医院，昨天吃了感冒药，现在好一些了。", pinyin: "Bú yòng qù yīyuàn, zuótiān chīle gǎnmào yào, xiànzài hǎo yìxiē le.", english: "No need. He took cold medicine yesterday and is feeling better now." },
      { order: 12, dialogNumber: 2, dialogLabel: "On the phone", speaker: "张太太", chinese: "那我们下次再一起出去玩儿吧。", pinyin: "Nà wǒmen xià cì zài yìqǐ chūqu wánr ba.", english: "Then let's go out together another time." },
      { order: 13, dialogNumber: 3, dialogLabel: "At Xiaogang's home", speaker: "小丽", chinese: "你最喜欢哪个季节？", pinyin: "Nǐ zuì xǐhuān nǎge jìjié?", english: "Which season do you like best?" },
      { order: 14, dialogNumber: 3, dialogLabel: "At Xiaogang's home", speaker: "小刚", chinese: "当然是春天，天气不那么冷了，草和树都绿了，花也开了。", pinyin: "Dāngrán shì chūntiān, tiānqì bù nàme lěng le, cǎo hé shù dōu lǜ le, huā yě kāi le.", english: "Spring, of course. The weather isn't that cold, the grass and trees turn green, and flowers bloom." },
      { order: 15, dialogNumber: 3, dialogLabel: "At Xiaogang's home", speaker: "小丽", chinese: "我最喜欢夏天，因为我可以穿漂亮的裙子了。", pinyin: "Wǒ zuì xǐhuān xiàtiān, yīnwèi wǒ kěyǐ chuān piàoliang de qúnzi le.", english: "I like summer best because I can wear pretty skirts." },
      { order: 16, dialogNumber: 3, dialogLabel: "At Xiaogang's home", speaker: "小刚", chinese: "那我也喜欢夏天了。", pinyin: "Nà wǒ yě xǐhuān xiàtiān le.", english: "Then I like summer too." },
      { order: 17, dialogNumber: 3, dialogLabel: "At Xiaogang's home", speaker: "小丽", chinese: "怎么？你也有漂亮的裙子？", pinyin: "Zěnme? Nǐ yě yǒu piàoliang de qúnzi?", english: "What? Do you have pretty skirts too?" },
      { order: 18, dialogNumber: 3, dialogLabel: "At Xiaogang's home", speaker: "小刚", chinese: "不，我喜欢看你穿漂亮的裙子。", pinyin: "Bù, wǒ xǐhuān kàn nǐ chuān piàoliang de qúnzi.", english: "No. I like seeing you in pretty skirts." },
      { order: 19, dialogNumber: 4, dialogLabel: "At Xiaogang's home", speaker: "小丽", chinese: "我最近越来越胖了。", pinyin: "Wǒ zuìjìn yuè lái yuè pàng le.", english: "I've been getting fatter and fatter lately." },
      { order: 20, dialogNumber: 4, dialogLabel: "At Xiaogang's home", speaker: "小刚", chinese: "谁说的？我觉得你越来越漂亮了。", pinyin: "Shéi shuō de? Wǒ juéde nǐ yuè lái yuè piàoliang le.", english: "Who said that? I think you're getting prettier and prettier." },
      { order: 21, dialogNumber: 4, dialogLabel: "At Xiaogang's home", speaker: "小丽", chinese: "你看，这条裙子是去年买的，今年就不能穿了。", pinyin: "Nǐ kàn, zhè tiáo qúnzi shì qùnián mǎi de, jīnnián jiù bù néng chuān le.", english: "Look, I bought this skirt last year, but I can't wear it this year." },
      { order: 22, dialogNumber: 4, dialogLabel: "At Xiaogang's home", speaker: "小刚", chinese: "那是因为你吃得太多了，少吃点儿吧。", pinyin: "Nà shì yīnwèi nǐ chī de tài duō le, shǎo chī diǎnr ba.", english: "That's because you eat too much. Eat less." },
      { order: 23, dialogNumber: 4, dialogLabel: "At Xiaogang's home", speaker: "小丽", chinese: "我做的饭越来越好吃，我能少吃吗？", pinyin: "Wǒ zuò de fàn yuè lái yuè hǎochī, wǒ néng shǎo chī ma?", english: "My cooking is getting better and better. How can I eat less?" },
    ],
  },
  {
    chapterNumber: 6,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the living room", speaker: "周明", chinese: "我的眼镜呢？怎么突然找不到了？你看见了吗？", pinyin: "Wǒ de yǎnjìng ne? Zěnme tūrán zhǎo bu dào le? Nǐ kànjiàn le ma?", english: "Where are my glasses? Why can't I find them all of a sudden? Did you see them?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the living room", speaker: "周太太", chinese: "我没看见啊。", pinyin: "Wǒ méi kànjiàn a.", english: "I didn't see them." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the living room", speaker: "周明", chinese: "我离不开眼镜，没有眼镜，我一个字也看不清楚。", pinyin: "Wǒ lí bu kāi yǎnjìng, méiyǒu yǎnjìng, wǒ yí ge zì yě kàn bu qīngchu.", english: "I can't do without my glasses. Without them, I can't see a single word clearly." },
      { order: 4, dialogNumber: 1, dialogLabel: "In the living room", speaker: "周太太", chinese: "你去房间找找，是不是刚才放在桌子上了？", pinyin: "Nǐ qù fángjiān zhǎozhao, shì bu shì gāngcái fàng zài zhuōzi shang le?", english: "Go look in the room. Didn't you put them on the desk just now?" },
      { order: 5, dialogNumber: 1, dialogLabel: "In the living room", speaker: "周明", chinese: "我怎么看得到啊？你快过来帮忙啊。", pinyin: "Wǒ zěnme kàn de dào a? Nǐ kuài guòlái bāngmáng a.", english: "How can I see them? Come help me!" },
      { order: 6, dialogNumber: 1, dialogLabel: "In the living room", speaker: "周太太", chinese: "好吧，我帮你去找找。", pinyin: "Hǎo ba, wǒ bāng nǐ qù zhǎozhao.", english: "OK, I'll go look for you." },
      { order: 7, dialogNumber: 2, dialogLabel: "On the phone", speaker: "同学", chinese: "今天的作业你做完了吗？", pinyin: "Jīntiān de zuòyè nǐ zuòwán le ma?", english: "Have you finished today's homework?" },
      { order: 8, dialogNumber: 2, dialogLabel: "On the phone", speaker: "儿子", chinese: "刚做完，你呢？", pinyin: "Gāng zuòwán, nǐ ne?", english: "Just finished. What about you?" },
      { order: 9, dialogNumber: 2, dialogLabel: "On the phone", speaker: "同学", chinese: "今天这些题特别难，我看不懂，不会做，你能帮我吗？", pinyin: "Jīntiān zhèxiē tí tèbié nán, wǒ kàn bu dǒng, bú huì zuò, nǐ néng bāng wǒ ma?", english: "Today's questions are especially hard. I can't understand them and don't know how to do them. Can you help me?" },
      { order: 10, dialogNumber: 2, dialogLabel: "On the phone", speaker: "儿子", chinese: "电话里讲不明白，你来我家吧，我给你讲讲。", pinyin: "Diànhuà li jiǎng bu míngbai, nǐ lái wǒ jiā ba, wǒ gěi nǐ jiǎngjiang.", english: "I can't explain clearly over the phone. Come to my place and I'll explain it to you." },
      { order: 11, dialogNumber: 2, dialogLabel: "On the phone", speaker: "同学", chinese: "好啊，我锻炼完了就过去。", pinyin: "Hǎo a, wǒ duànliàn wán le jiù guòqu.", english: "OK, I'll come over after I finish exercising." },
      { order: 12, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "你怎么有点儿不高兴？", pinyin: "Nǐ zěnme yǒudiǎnr bù gāoxìng?", english: "Why are you a bit unhappy?" },
      { order: 13, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小刚", chinese: "我想请小丽吃饭，但是找不到好饭馆。", pinyin: "Wǒ xiǎng qǐng Xiǎolì chī fàn, dànshì zhǎo bu dào hǎo fànguǎnr.", english: "I want to treat Xiaoli to dinner, but I can't find a good restaurant." },
      { order: 14, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "那你请她听音乐会吧，她喜欢听音乐。", pinyin: "Nà nǐ qǐng tā tīng yīnyuèhuì ba, tā xǐhuān tīng yīnyuè.", english: "Then invite her to a concert. She likes listening to music." },
      { order: 15, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小刚", chinese: "音乐会人太多，买不到票。", pinyin: "Yīnyuèhuì rén tài duō, mǎi bu dào piào.", english: "There are too many people at concerts. I can't get tickets." },
      { order: 16, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "那去公园走走，聊聊天儿吧。", pinyin: "Nà qù gōngyuán zǒuzou, liáoliao tiānr ba.", english: "Then go for a walk in the park and chat." },
      { order: 17, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小刚", chinese: "公园太大，多累啊。", pinyin: "Gōngyuán tài dà, duō lèi a.", english: "The park is too big. So tiring!" },
      { order: 18, dialogNumber: 4, dialogLabel: "In the living room", speaker: "周太太", chinese: "你怎么还喝咖啡？", pinyin: "Nǐ zěnme hái hē kāfēi?", english: "Why are you still drinking coffee?" },
      { order: 19, dialogNumber: 4, dialogLabel: "In the living room", speaker: "周明", chinese: "怎么了？", pinyin: "Zěnme le?", english: "What's wrong?" },
      { order: 20, dialogNumber: 4, dialogLabel: "In the living room", speaker: "周太太", chinese: "你不是说晚上睡不着觉吗？", pinyin: "Nǐ bú shì shuō wǎnshang shuì bu zháo jiào ma?", english: "Didn't you say you can't fall asleep at night?" },
      { order: 21, dialogNumber: 4, dialogLabel: "In the living room", speaker: "周明", chinese: "没事，我只喝一杯。", pinyin: "Méi shì, wǒ zhǐ hē yì bēi.", english: "It's OK. I'm only having one cup." },
      { order: 22, dialogNumber: 4, dialogLabel: "In the living room", speaker: "周太太", chinese: "你还是喝杯牛奶吧，可以睡得更好些。", pinyin: "Nǐ háishì hē bēi niúnǎi ba, kěyǐ shuì de gèng hǎo xiē.", english: "You'd better drink a glass of milk. It'll help you sleep better." },
      { order: 23, dialogNumber: 4, dialogLabel: "In the living room", speaker: "周明", chinese: "好吧，牛奶呢？", pinyin: "Hǎo ba, niúnǎi ne?", english: "OK. Where's the milk?" },
      { order: 24, dialogNumber: 4, dialogLabel: "In the living room", speaker: "周太太", chinese: "还没买呢。", pinyin: "Hái méi mǎi ne.", english: "Haven't bought it yet." },
    ],
  },
  {
    chapterNumber: 7,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the office", speaker: "同事", chinese: "那个漂亮的新同事是谁？", pinyin: "Nàge piàoliang de xīn tóngshì shì shéi?", english: "Who is that pretty new colleague?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the office", speaker: "小刚", chinese: "那是小丽。", pinyin: "Nà shì Xiǎolì.", english: "That's Xiaoli." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the office", speaker: "同事", chinese: "她刚来北京吗？", pinyin: "Tā gāng lái Běijīng ma?", english: "Did she just come to Beijing?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the office", speaker: "小刚", chinese: "不，她在北京工作三年了。", pinyin: "Bù, tā zài Běijīng gōngzuò sān nián le.", english: "No, she's been working in Beijing for three years." },
      { order: 5, dialogNumber: 1, dialogLabel: "In the office", speaker: "同事", chinese: "以前她在哪儿工作？", pinyin: "Yǐqián tā zài nǎr gōngzuò?", english: "Where did she work before?" },
      { order: 6, dialogNumber: 1, dialogLabel: "In the office", speaker: "小刚", chinese: "她在银行工作了两年以后来的我们公司。", pinyin: "Tā zài yínháng gōngzuò le liǎng nián yǐhòu lái de wǒmen gōngsī.", english: "She worked in a bank for two years before joining our company." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the lounge", speaker: "同事", chinese: "周末你跟小丽去哪儿玩儿了？", pinyin: "Zhōumò nǐ gēn Xiǎolì qù nǎr wánr le?", english: "Where did you and Xiaoli go this weekend?" },
      { order: 8, dialogNumber: 2, dialogLabel: "In the lounge", speaker: "小刚", chinese: "我们去唱歌了。", pinyin: "Wǒmen qù chànggē le.", english: "We went singing." },
      { order: 9, dialogNumber: 2, dialogLabel: "In the lounge", speaker: "同事", chinese: "你们唱了多久？", pinyin: "Nǐmen chàngle duō jiǔ?", english: "How long did you sing?" },
      { order: 10, dialogNumber: 2, dialogLabel: "In the lounge", speaker: "小刚", chinese: "我们唱了两个小时歌，晚上还去听音乐会了。", pinyin: "Wǒmen chàngle liǎng ge xiǎoshí gē, wǎnshang hái qù tīng yīnyuèhuì le.", english: "We sang for two hours, and in the evening we went to a concert too." },
      { order: 11, dialogNumber: 2, dialogLabel: "In the lounge", speaker: "同事", chinese: "你们都对音乐感兴趣吗？", pinyin: "Nǐmen dōu duì yīnyuè gǎn xìngqù ma?", english: "Are you both interested in music?" },
      { order: 12, dialogNumber: 2, dialogLabel: "In the lounge", speaker: "小刚", chinese: "她对音乐感兴趣，我对她更感兴趣。", pinyin: "Tā duì yīnyuè gǎn xìngqù, wǒ duì tā gèng gǎn xìngqù.", english: "She's interested in music, but I'm more interested in her." },
      { order: 13, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小刚", chinese: "我跟小丽下个月结婚，到时候欢迎你来。", pinyin: "Wǒ gēn Xiǎolì xià ge yuè jiéhūn, dào shíhou huānyíng nǐ lái.", english: "Xiaoli and I are getting married next month. You're welcome to come." },
      { order: 14, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "什么？结婚？", pinyin: "Shénme? Jiéhūn?", english: "What? Getting married?" },
      { order: 15, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小刚", chinese: "对啊，突然吗？", pinyin: "Duì a, tūrán ma?", english: "Yes. Is it sudden?" },
      { order: 16, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "你们不是刚认识吗？", pinyin: "Nǐmen bú shì gāng rènshi ma?", english: "Didn't you two just meet?" },
      { order: 17, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小刚", chinese: "我跟她都认识五年了。", pinyin: "Wǒ gēn tā dōu rènshi wǔ nián le.", english: "I've known her for five years." },
      { order: 18, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "你跟她结婚，那我怎么办啊？", pinyin: "Nǐ gēn tā jiéhūn, nà wǒ zěnme bàn a?", english: "If you marry her, what about me?" },
      { order: 19, dialogNumber: 4, dialogLabel: "At the exit of the office building", speaker: "小丽", chinese: "你看看手表，怎么迟到了？", pinyin: "Nǐ kànkan shǒubiǎo, zěnme chídào le?", english: "Look at your watch. Why are you late?" },
      { order: 20, dialogNumber: 4, dialogLabel: "At the exit of the office building", speaker: "小刚", chinese: "没迟到啊。", pinyin: "Méi chídào a.", english: "I'm not late." },
      { order: 21, dialogNumber: 4, dialogLabel: "At the exit of the office building", speaker: "小丽", chinese: "你不是说七点半来接我吗？你迟到了一刻钟。", pinyin: "Nǐ bú shì shuō qī diǎn bàn lái jiē wǒ ma? Nǐ chídàole yí kè zhōng.", english: "Didn't you say you'd pick me up at 7:30? You're 15 minutes late." },
      { order: 22, dialogNumber: 4, dialogLabel: "At the exit of the office building", speaker: "小刚", chinese: "现在不是七点半吗？", pinyin: "Xiànzài bú shì qī diǎn bàn ma?", english: "Isn't it 7:30 now?" },
      { order: 23, dialogNumber: 4, dialogLabel: "At the exit of the office building", speaker: "小丽", chinese: "已经差一刻八点了！我都在这儿坐了半个小时了。", pinyin: "Yǐjīng chà yí kè bā diǎn le! Wǒ dōu zài zhèr zuòle bàn ge xiǎoshí le.", english: "It's already a quarter to eight! I've been sitting here for half an hour." },
      { order: 24, dialogNumber: 4, dialogLabel: "At the exit of the office building", speaker: "小刚", chinese: "不是我迟到了，是你的表快了一刻钟。", pinyin: "Bú shì wǒ chídào le, shì nǐ de biǎo kuàile yí kè zhōng.", english: "I'm not late. Your watch is 15 minutes fast." },
    ],
  },
  {
    chapterNumber: 8,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the lounge", speaker: "同事", chinese: "听说你最近打算买房子？", pinyin: "Tīngshuō nǐ zuìjìn dǎsuàn mǎi fángzi?", english: "I heard you're planning to buy a house?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the lounge", speaker: "小丽", chinese: "是，昨天去看了看，今天又去看了看，明天还要再去看一看。", pinyin: "Shì, zuótiān qù kànle kàn, jīntiān yòu qù kànle kàn, míngtiān hái yào zài qù kàn yí kàn.", english: "Yes. I looked yesterday, looked again today, and will look again tomorrow." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the lounge", speaker: "同事", chinese: "都不满意吗？", pinyin: "Dōu bù mǎnyì ma?", english: "Are you not satisfied with any?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the lounge", speaker: "小丽", chinese: "一个没有电梯，不方便。一个有电梯，但是在二十层。", pinyin: "Yí ge méiyǒu diàntī, bù fāngbiàn. Yí ge yǒu diàntī, dànshì zài èrshí céng.", english: "One doesn't have an elevator – inconvenient. The other has an elevator, but it's on the 20th floor." },
      { order: 5, dialogNumber: 1, dialogLabel: "In the lounge", speaker: "同事", chinese: "二十层怎么了？", pinyin: "Èrshí céng zěnme le?", english: "What's wrong with the 20th floor?" },
      { order: 6, dialogNumber: 1, dialogLabel: "In the lounge", speaker: "小丽", chinese: "太高了，往下看多害怕啊！", pinyin: "Tài gāo le, wǎng xià kàn duō hàipà a!", english: "It's too high. Looking down is so scary!" },
      { order: 7, dialogNumber: 2, dialogLabel: "At school", speaker: "小明", chinese: "听说你下个星期就要回国了？", pinyin: "Tīngshuō nǐ xià ge xīngqī jiù yào huí guó le?", english: "I heard you're going back to your country next week?" },
      { order: 8, dialogNumber: 2, dialogLabel: "At school", speaker: "马可", chinese: "是啊，真不想离开北京。", pinyin: "Shì a, zhēn bù xiǎng líkāi Běijīng.", english: "Yes. I really don't want to leave Beijing." },
      { order: 9, dialogNumber: 2, dialogLabel: "At school", speaker: "小明", chinese: "我下星期不在北京，不能去机场送你了。", pinyin: "Wǒ xià xīngqī bú zài Běijīng, bù néng qù jīchǎng sòng nǐ le.", english: "I won't be in Beijing next week, so I can't see you off at the airport." },
      { order: 10, dialogNumber: 2, dialogLabel: "At school", speaker: "马可", chinese: "没关系，你忙吧。", pinyin: "Méi guānxi, nǐ máng ba.", english: "It's OK. You're busy." },
      { order: 11, dialogNumber: 2, dialogLabel: "At school", speaker: "小明", chinese: "这个小熊猫送给你，欢迎你以后再到中国来。", pinyin: "Zhège xiǎo xióngmāo sòng gěi nǐ, huānyíng nǐ yǐhòu zài dào Zhōngguó lái.", english: "This little panda is for you. You're welcome to come to China again." },
      { order: 12, dialogNumber: 2, dialogLabel: "At school", speaker: "马可", chinese: "谢谢。希望以后能再见面。", pinyin: "Xièxie. Xīwàng yǐhòu néng zài jiànmiàn.", english: "Thanks. I hope we can meet again." },
      { order: 13, dialogNumber: 3, dialogLabel: "In a coffee house", speaker: "小丽", chinese: "小刚，我们坐哪儿？", pinyin: "Xiǎogāng, wǒmen zuò nǎr?", english: "Xiaogang, where should we sit?" },
      { order: 14, dialogNumber: 3, dialogLabel: "In a coffee house", speaker: "小刚", chinese: "你坐哪儿我就坐哪儿。", pinyin: "Nǐ zuò nǎr wǒ jiù zuò nǎr.", english: "Wherever you sit, I'll sit." },
      { order: 15, dialogNumber: 3, dialogLabel: "In a coffee house", speaker: "小丽", chinese: "坐这儿吧，这儿安静。你想喝什么饮料？", pinyin: "Zuò zhèr ba, zhèr ānjìng. Nǐ xiǎng hē shénme yǐnliào?", english: "Let's sit here. It's quiet here. What drink do you want?" },
      { order: 16, dialogNumber: 3, dialogLabel: "In a coffee house", speaker: "小刚", chinese: "你喝什么我就喝什么。", pinyin: "Nǐ hē shénme wǒ jiù hē shénme.", english: "Whatever you drink, I'll drink." },
      { order: 17, dialogNumber: 3, dialogLabel: "In a coffee house", speaker: "小丽", chinese: "喝可乐吧。你等我一会儿，我马上回来。", pinyin: "Hē kělè ba. Nǐ děng wǒ yíhuìr, wǒ mǎshàng huílái.", english: "Let's have Coke. Wait a moment for me. I'll be right back." },
      { order: 18, dialogNumber: 3, dialogLabel: "In a coffee house", speaker: "小刚", chinese: "小丽，你去哪儿？你去哪儿我就去哪儿。", pinyin: "Xiǎolì, nǐ qù nǎr? Nǐ qù nǎr wǒ jiù qù nǎr.", english: "Xiaoli, where are you going? Wherever you go, I'll go." },
      { order: 19, dialogNumber: 3, dialogLabel: "In a coffee house", speaker: "小丽", chinese: "我去洗手间。", pinyin: "Wǒ qù xǐshǒujiān.", english: "I'm going to the restroom." },
      { order: 20, dialogNumber: 4, dialogLabel: "At Zhou Ming's home", speaker: "老同学", chinese: "快五年了，你几乎没变化。", pinyin: "Kuài wǔ nián le, nǐ jīhū méi biànhuà.", english: "Almost five years. You've hardly changed." },
      { order: 21, dialogNumber: 4, dialogLabel: "At Zhou Ming's home", speaker: "周太太", chinese: "谁说的？我胖了，以前的衣服都不能穿了。", pinyin: "Shéi shuō de? Wǒ pàng le, yǐqián de yīfu dōu bù néng chuān le.", english: "Who said that? I've gained weight. I can't wear my old clothes anymore." },
      { order: 22, dialogNumber: 4, dialogLabel: "At Zhou Ming's home", speaker: "老同学", chinese: "健康最重要，胖瘦没关系。", pinyin: "Jiànkāng zuì zhòngyào, pàng shòu méi guānxi.", english: "Health is the most important thing. Being fat or thin doesn't matter." },
      { order: 23, dialogNumber: 4, dialogLabel: "At Zhou Ming's home", speaker: "周太太", chinese: "是呀，想吃什么就吃什么。", pinyin: "Shì a, xiǎng chī shénme jiù chī shénme.", english: "Yes. Whatever I want to eat, I eat." },
      { order: 24, dialogNumber: 4, dialogLabel: "At Zhou Ming's home", speaker: "老同学", chinese: "你做饭还是周明做饭？", pinyin: "Nǐ zuò fàn háishì Zhōu Míng zuò fàn?", english: "Do you cook, or does Zhou Ming cook?" },
      { order: 25, dialogNumber: 4, dialogLabel: "At Zhou Ming's home", speaker: "周太太", chinese: "我做，我想吃什么就做什么，想吃多少就做多少。", pinyin: "Wǒ zuò, wǒ xiǎng chī shénme jiù zuò shénme, xiǎng chī duōshao jiù zuò duōshao.", english: "I cook. Whatever I want to eat, I cook; however much I want to eat, I cook." },
    ],
  },
  {
    chapterNumber: 9,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "大山", chinese: "马可，你的中文越说越好了！", pinyin: "Mǎkě, nǐ de Zhōngwén yuè shuō yuè hǎo le!", english: "Marco, your Chinese is getting better and better!" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "马可", chinese: "哪里哪里，我们班王静说得更好。", pinyin: "Nǎli nǎli, wǒmen bān Wáng Jìng shuō de gèng hǎo.", english: "Not at all. Wang Jing in our class speaks even better." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "大山", chinese: "怎么好？", pinyin: "Zěnme hǎo?", english: "How so?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "马可", chinese: "她的汉语说得跟中国人一样好。", pinyin: "Tā de Hànyǔ shuō de gēn Zhōngguóren yíyàng hǎo.", english: "She speaks Chinese as well as a native." },
      { order: 5, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "大山", chinese: "王静？我怎么没听说过这个名字？", pinyin: "Wáng Jìng? Wǒ zěnme méi tīngshuōguo zhège míngzi?", english: "Wang Jing? Why haven't I heard of this name?" },
      { order: 6, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "马可", chinese: "她是我们的汉语老师。", pinyin: "Tā shì wǒmen de Hànyǔ lǎoshī.", english: "She's our Chinese teacher." },
      { order: 7, dialogNumber: 2, dialogLabel: "In a bakery", speaker: "小丽", chinese: "别吃了，你已经吃了三块蛋糕了。", pinyin: "Bié chī le, nǐ yǐjīng chīle sān kuài dàngāo le.", english: "Stop eating. You've already had three pieces of cake." },
      { order: 8, dialogNumber: 2, dialogLabel: "In a bakery", speaker: "小刚", chinese: "这是最后一块。", pinyin: "Zhè shì zuìhòu yí kuài.", english: "This is the last one." },
      { order: 9, dialogNumber: 2, dialogLabel: "In a bakery", speaker: "小丽", chinese: "你总是吃甜的东西，会越吃越胖。", pinyin: "Nǐ zǒngshì chī tián de dōngxi, huì yuè chī yuè pàng.", english: "You always eat sweet things. You'll get fatter and fatter." },
      { order: 10, dialogNumber: 2, dialogLabel: "In a bakery", speaker: "小刚", chinese: "你放心，我一定不会变胖。", pinyin: "Nǐ fàngxīn, wǒ yídìng bú huì biàn pàng.", english: "Don't worry. I definitely won't get fat." },
      { order: 11, dialogNumber: 2, dialogLabel: "In a bakery", speaker: "小丽", chinese: "为什么？", pinyin: "Wèi shénme?", english: "Why?" },
      { order: 12, dialogNumber: 2, dialogLabel: "In a bakery", speaker: "小刚", chinese: "我们家的人都很瘦，吃不胖。", pinyin: "Wǒmen jiā de rén dōu hěn shòu, chī bu pàng.", english: "Everyone in my family is thin. We can't get fat from eating." },
      { order: 13, dialogNumber: 3, dialogLabel: "On the mountain", speaker: "小丽", chinese: "我有点儿害怕。", pinyin: "Wǒ yǒudiǎnr hàipà.", english: "I'm a little scared." },
      { order: 14, dialogNumber: 3, dialogLabel: "On the mountain", speaker: "小刚", chinese: "怎么了？", pinyin: "Zěnme le?", english: "What's wrong?" },
      { order: 15, dialogNumber: 3, dialogLabel: "On the mountain", speaker: "小丽", chinese: "山越高，路越难走。我也越爬越冷。", pinyin: "Shān yuè gāo, lù yuè nán zǒu. Wǒ yě yuè pá yuè lěng.", english: "The higher the mountain, the harder the path. I'm also getting colder as I climb." },
      { order: 16, dialogNumber: 3, dialogLabel: "On the mountain", speaker: "小刚", chinese: "不用担心，有我呢，我对这儿比较了解。", pinyin: "Bú yòng dānxīn, yǒu wǒ ne, wǒ duì zhèr bǐjiào liǎojiě.", english: "Don't worry. I'm here. I know this place pretty well." },
      { order: 17, dialogNumber: 3, dialogLabel: "On the mountain", speaker: "小丽", chinese: "那我们先休息一下，一会儿再爬。", pinyin: "Nà wǒmen xiān xiūxi yíxià, yíhuìr zài pá.", english: "Then let's rest for a while and climb again later." },
      { order: 18, dialogNumber: 3, dialogLabel: "On the mountain", speaker: "小刚", chinese: "好，一会儿我们可以从中间这条路上去。", pinyin: "Hǎo, yíhuìr wǒmen kěyǐ cóng zhōngjiān zhè tiáo lù shàngqu.", english: "OK. Later we can go up the path in the middle." },
      { order: 19, dialogNumber: 4, dialogLabel: "At Xiaoming's home", speaker: "同学", chinese: "小明，你的眼睛怎么跟大熊猫一样了？", pinyin: "Xiǎomíng, nǐ de yǎnjīng zěnme gēn dà xióngmāo yíyàng le?", english: "Xiaoming, why do your eyes look like a panda's?" },
      { order: 20, dialogNumber: 4, dialogLabel: "At Xiaoming's home", speaker: "小明", chinese: "我这几天脚疼，没休息好。", pinyin: "Wǒ zhè jǐ tiān jiǎo téng, méi xiūxi hǎo.", english: "My feet have been hurting these days. I haven't rested well." },
      { order: 21, dialogNumber: 4, dialogLabel: "At Xiaoming's home", speaker: "同学", chinese: "去医院了吗？医生说什么？", pinyin: "Qù yīyuàn le ma? Yīshēng shuō shénme?", english: "Did you go to the hospital? What did the doctor say?" },
      { order: 22, dialogNumber: 4, dialogLabel: "At Xiaoming's home", speaker: "小明", chinese: "他让我多休息。休息得越多，好得越快。", pinyin: "Tā ràng wǒ duō xiūxi. Xiūxi de yuè duō, hǎo de yuè kuài.", english: "He told me to rest more. The more I rest, the faster I'll recover." },
      { order: 23, dialogNumber: 4, dialogLabel: "At Xiaoming's home", speaker: "同学", chinese: "下个月的篮球比赛，你能参加吗？", pinyin: "Xià ge yuè de lánqiú bǐsài, nǐ néng cānjiā ma?", english: "Can you participate in next month's basketball game?" },
      { order: 24, dialogNumber: 4, dialogLabel: "At Xiaoming's home", speaker: "小明", chinese: "一定能参加，一点儿影响也没有。", pinyin: "Yídìng néng cānjiā, yìdiǎnr yǐngxiǎng yě méiyǒu.", english: "I can definitely participate. No problem at all." },
    ],
  },
  {
    chapterNumber: 10,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "朋友", chinese: "大山，你和马可谁个子高？", pinyin: "Dàshān, nǐ hé Mǎkě shéi gèzi gāo?", english: "Dashan, who is taller, you or Marco?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "大山", chinese: "马可比我高，我比马可矮一点儿。", pinyin: "Mǎkě bǐ wǒ gāo, wǒ bǐ Mǎkě ǎi yìdiǎnr.", english: "Marco is taller than me. I'm a bit shorter than Marco." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "朋友", chinese: "那你们谁大？", pinyin: "Nà nǐmen shéi dà?", english: "Then who's older?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "大山", chinese: "我比马可大两岁。", pinyin: "Wǒ bǐ Mǎkě dà liǎng suì.", english: "I'm two years older than Marco." },
      { order: 5, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "朋友", chinese: "你们谁的汉语说得更好？", pinyin: "Nǐmen shéi de Hànyǔ shuō de gèng hǎo?", english: "Who speaks Chinese better?" },
      { order: 6, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "大山", chinese: "马可比我说得好一些，我的汉语没有他好。", pinyin: "Mǎkě bǐ wǒ shuō de hǎo yìxiē, wǒ de Hànyǔ méiyǒu tā hǎo.", english: "Marco speaks a bit better than me. My Chinese isn't as good as his." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "小明", chinese: "我喜欢历史课、体育课，不喜欢数学课。", pinyin: "Wǒ xǐhuān lìshǐ kè, tǐyù kè, bù xǐhuān shùxué kè.", english: "I like history and PE, but I don't like maths." },
      { order: 8, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "同学", chinese: "为什么？数学也很有意思啊。", pinyin: "Wèi shénme? Shùxué yě hěn yǒu yìsi a.", english: "Why? Maths is also very interesting." },
      { order: 9, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "小明", chinese: "我觉得数学比历史难多了，我听不懂。", pinyin: "Wǒ juéde shùxué bǐ lìshǐ nán duō le, wǒ tīng bu dǒng.", english: "I think maths is much harder than history. I can't understand it." },
      { order: 10, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "同学", chinese: "别担心，我可以帮你。", pinyin: "Bié dānxīn, wǒ kěyǐ bāng nǐ.", english: "Don't worry. I can help you." },
      { order: 11, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "小明", chinese: "好啊，我们每天学多长时间？", pinyin: "Hǎo a, wǒmen měi tiān xué duō cháng shíjiān?", english: "Great. How long will we study each day?" },
      { order: 12, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "同学", chinese: "一两个小时吧。", pinyin: "Yì liǎng ge xiǎoshí ba.", english: "An hour or two." },
      { order: 13, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "你最近比以前来得早多了，搬家了？", pinyin: "Nǐ zuìjìn bǐ yǐqián lái de zǎo duō le, bān jiā le?", english: "You've been coming much earlier than before. Did you move?" },
      { order: 14, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小丽", chinese: "是啊，你不知道？我上个月就搬家了，走路二十分钟就到。", pinyin: "Shì a, nǐ bù zhīdào? Wǒ shàng ge yuè jiù bān jiā le, zǒu lù èrshí fēnzhōng jiù dào.", english: "Yes. Didn't you know? I moved last month. It's only a 20-minute walk." },
      { order: 15, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "那很方便啊。", pinyin: "Nà hěn fāngbiàn a.", english: "That's very convenient." },
      { order: 16, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小丽", chinese: "我还打算买辆自行车，骑车七八分钟就能到。", pinyin: "Wǒ hái dǎsuàn mǎi liàng zìxíngchē, qí chē qī bā fēnzhōng jiù néng dào.", english: "I also plan to buy a bicycle. It'll take only seven or eight minutes by bike." },
      { order: 17, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "你不是有一辆吗？", pinyin: "Nǐ bú shì yǒu yí liàng ma?", english: "Don't you already have one?" },
      { order: 18, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小丽", chinese: "那辆太旧了，要换一辆，很便宜，两三百块钱。", pinyin: "Nà liàng tài jiù le, yào huàn yí liàng, hěn piányi, liǎng sān bǎi kuài qián.", english: "That one is too old. I need to replace it. It's cheap – only two or three hundred yuan." },
      { order: 19, dialogNumber: 4, dialogLabel: "Looking at houses", speaker: "大山", chinese: "这两个地方的房子一样吗？", pinyin: "Zhè liǎng ge dìfang de fángzi yíyàng ma?", english: "Are the houses in these two places the same?" },
      { order: 20, dialogNumber: 4, dialogLabel: "Looking at houses", speaker: "中介", chinese: "不一样。您看，学校外边的房子比学校里边的大一些。", pinyin: "Bù yíyàng. Nín kàn, xuéxiào wàibiān de fángzi bǐ xuéxiào lǐbiān de dà yìxiē.", english: "Not the same. Look, the houses outside the school are a bit bigger than those inside." },
      { order: 21, dialogNumber: 4, dialogLabel: "Looking at houses", speaker: "大山", chinese: "大小没关系，主要是环境，哪个更安静？", pinyin: "Dàxiǎo méi guānxi, zhǔyào shì huánjìng, nǎge gèng ānjìng?", english: "Size doesn't matter. The main thing is the environment. Which is quieter?" },
      { order: 22, dialogNumber: 4, dialogLabel: "Looking at houses", speaker: "中介", chinese: "学校里边的没有学校外边的那么安静。", pinyin: "Xuéxiào lǐbiān de méiyǒu xuéxiào wàibiān de nàme ānjìng.", english: "The ones inside the school aren't as quiet as those outside." },
      { order: 23, dialogNumber: 4, dialogLabel: "Looking at houses", speaker: "大山", chinese: "哪个方便一些呢？", pinyin: "Nǎge fāngbiàn yìxiē ne?", english: "Which is more convenient?" },
      { order: 24, dialogNumber: 4, dialogLabel: "Looking at houses", speaker: "中介", chinese: "学校里边比学校外边方便，附近有三四个车站。", pinyin: "Xuéxiào lǐbiān bǐ xuéxiào wàibiān fāngbiàn, fùjìn yǒu sān sì ge chēzhàn.", english: "The ones inside the school are more convenient than those outside. There are three or four bus stops nearby." },
    ],
  },
  {
    chapterNumber: 11,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "小明", chinese: "我先走了。", pinyin: "Wǒ xiān zǒu le.", english: "I'm leaving first." },
      { order: 2, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "同学", chinese: "你去哪儿？", pinyin: "Nǐ qù nǎr?", english: "Where are you going?" },
      { order: 3, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "小明", chinese: "我去图书馆借本书。", pinyin: "Wǒ qù túshūguǎn jiè běn shū.", english: "I'm going to the library to borrow a book." },
      { order: 4, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "同学", chinese: "帮我把这本词典还了吧。", pinyin: "Bāng wǒ bǎ zhè běn cídiǎn huán le ba.", english: "Help me return this dictionary." },
      { order: 5, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "小明", chinese: "好，等一会儿你离开教室的时候，记得把灯关了。", pinyin: "Hǎo, děng yíhuìr nǐ líkāi jiàoshì de shíhou, jìde bǎ dēng guān le.", english: "OK. When you leave the classroom later, remember to turn off the lights." },
      { order: 6, dialogNumber: 1, dialogLabel: "In the classroom", speaker: "同学", chinese: "好的，放心吧。", pinyin: "Hǎo de, fàngxīn ba.", english: "OK. Don't worry." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the conference room", speaker: "周明", chinese: "会议结束后，别忘记把空调关了。", pinyin: "Huìyì jiéshù hòu, bié wàngjì bǎ kōngtiáo guān le.", english: "After the meeting ends, don't forget to turn off the air conditioner." },
      { order: 8, dialogNumber: 2, dialogLabel: "In the conference room", speaker: "小丽", chinese: "好的。王经理两点左右来了个电话。", pinyin: "Hǎo de. Wáng jīnglǐ liǎng diǎn zuǒyòu láile ge diànhuà.", english: "OK. Manager Wang called around two o'clock." },
      { order: 9, dialogNumber: 2, dialogLabel: "In the conference room", speaker: "周明", chinese: "他已经到北京了？", pinyin: "Tā yǐjīng dào Běijīng le?", english: "Has he already arrived in Beijing?" },
      { order: 10, dialogNumber: 2, dialogLabel: "In the conference room", speaker: "小丽", chinese: "是的，他正坐地铁来我们公司呢。", pinyin: "Shì de, tā zhèng zuò dìtiě lái wǒmen gōngsī ne.", english: "Yes. He's taking the subway to our company right now." },
      { order: 11, dialogNumber: 2, dialogLabel: "In the conference room", speaker: "周明", chinese: "等他到了就告诉我。", pinyin: "Děng tā dàole jiù gàosu wǒ.", english: "Tell me when he arrives." },
      { order: 12, dialogNumber: 3, dialogLabel: "In the living room", speaker: "妈妈", chinese: "还差一双筷子，你去拿一下。", pinyin: "Hái chà yì shuāng kuàizi, nǐ qù ná yíxià.", english: "We're still missing a pair of chopsticks. Go get them." },
      { order: 13, dialogNumber: 3, dialogLabel: "In the living room", speaker: "儿子", chinese: "今天怎么做了这么多菜？", pinyin: "Jīntiān zěnme zuòle zhème duō cài?", english: "Why did you make so many dishes today?" },
      { order: 14, dialogNumber: 3, dialogLabel: "In the living room", speaker: "妈妈", chinese: "今天是你爸爸的生日。", pinyin: "Jīntiān shì nǐ bàba de shēngrì.", english: "Today is your father's birthday." },
      { order: 15, dialogNumber: 3, dialogLabel: "In the living room", speaker: "儿子", chinese: "真的啊？我把爸爸的生日忘了。那我们今天喝点儿啤酒吧。", pinyin: "Zhēn de a? Wǒ bǎ bàba de shēngrì wàng le. Nà wǒmen jīntiān hē diǎnr píjiǔ ba.", english: "Really? I forgot Dad's birthday. Then let's have some beer today." },
      { order: 16, dialogNumber: 3, dialogLabel: "In the living room", speaker: "妈妈", chinese: "医生说你爸爸一口酒都不能喝，别让他看见酒瓶子。", pinyin: "Yīshēng shuō nǐ bàba yì kǒu jiǔ dōu bù néng hē, bié ràng tā kànjiàn jiǔ píngzi.", english: "The doctor said your father can't drink a single drop of alcohol. Don't let him see the beer bottle." },
    ],
  },
  {
    chapterNumber: 12,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "At home", speaker: "小丽", chinese: "今天太阳从西边出来了吗？", pinyin: "Jīntiān tàiyáng cóng xībiān chūlái le ma?", english: "Did the sun rise from the west today?" },
      { order: 2, dialogNumber: 1, dialogLabel: "At home", speaker: "小刚", chinese: "怎么了？", pinyin: "Zěnme le?", english: "What's wrong?" },
      { order: 3, dialogNumber: 1, dialogLabel: "At home", speaker: "小丽", chinese: "你怎么这么早就要睡觉了？以前都要12点以后才睡觉。", pinyin: "Nǐ zěnme zhème zǎo jiù yào shuìjiào le? Yǐqián dōu yào shí'èr diǎn yǐhòu cái shuìjiào.", english: "Why are you going to bed so early? You used to go to bed after 12." },
      { order: 4, dialogNumber: 1, dialogLabel: "At home", speaker: "小刚", chinese: "我明天8点就要到公司。", pinyin: "Wǒ míngtiān bā diǎn jiù yào dào gōngsī.", english: "I have to be at the company at 8 tomorrow." },
      { order: 5, dialogNumber: 1, dialogLabel: "At home", speaker: "小丽", chinese: "有事吗？", pinyin: "Yǒu shì ma?", english: "Is there something going on?" },
      { order: 6, dialogNumber: 1, dialogLabel: "At home", speaker: "小刚", chinese: "经理生气了，他告诉我，明天8点不到，以后就别来了。", pinyin: "Jīnglǐ shēngqì le, tā gàosu wǒ, míngtiān bā diǎn bú dào, yǐhòu jiù bié lái le.", english: "The manager is angry. He told me that if I'm not there by 8 tomorrow, I shouldn't come anymore." },
      { order: 7, dialogNumber: 2, dialogLabel: "At home", speaker: "小刚", chinese: "我要跟周经理去外地办事，明天的飞机。", pinyin: "Wǒ yào gēn Zhōu jīnglǐ qù wàidì bàn shì, míngtiān de fēijī.", english: "I'm going on a business trip with Manager Zhou. My flight is tomorrow." },
      { order: 8, dialogNumber: 2, dialogLabel: "At home", speaker: "小丽", chinese: "那我帮你把衣服放到行李箱里吧。什么时候回来？", pinyin: "Nà wǒ bāng nǐ bǎ yīfu fàng dào xínglǐxiāng li ba. Shénme shíhou huílái?", english: "Then let me help you put your clothes in the suitcase. When will you be back?" },
      { order: 9, dialogNumber: 2, dialogLabel: "At home", speaker: "小刚", chinese: "一个星期就回来。", pinyin: "Yí ge xīngqī jiù huílái.", english: "I'll be back in a week." },
      { order: 10, dialogNumber: 2, dialogLabel: "At home", speaker: "小丽", chinese: "啊？一个星期以后才回来？", pinyin: "A? Yí ge xīngqī yǐhòu cái huílái?", english: "Ah? You won't be back until after a week?" },
      { order: 11, dialogNumber: 2, dialogLabel: "At home", speaker: "小刚", chinese: "你要自己照顾好自己，我已经给你准备好吃的和喝的了。", pinyin: "Nǐ yào zìjǐ zhàogù hǎo zìjǐ, wǒ yǐjīng gěi nǐ zhǔnbèi hǎo chī de hé hē de le.", english: "You need to take good care of yourself. I've already prepared food and drinks for you." },
      { order: 12, dialogNumber: 2, dialogLabel: "At home", speaker: "小丽", chinese: "好吧。我已经把我的照片放在你的包里了。", pinyin: "Hǎo ba. Wǒ yǐjīng bǎ wǒ de zhàopiàn fàng zài nǐ de bāo li le.", english: "OK. I've already put my photo in your bag." },
      { order: 13, dialogNumber: 3, dialogLabel: "At the airport", speaker: "周明", chinese: "你怎么才来？", pinyin: "Nǐ zěnme cái lái?", english: "Why are you just getting here?" },
      { order: 14, dialogNumber: 3, dialogLabel: "At the airport", speaker: "小刚", chinese: "对不起，周经理，来机场的路上我才发现忘带护照了。", pinyin: "Duìbuqǐ, Zhōu jīnglǐ, lái jīchǎng de lùshang wǒ cái fāxiàn wàng dài hùzhào le.", english: "Sorry, Manager Zhou. It was only on the way to the airport that I realized I forgot my passport." },
      { order: 15, dialogNumber: 3, dialogLabel: "At the airport", speaker: "周明", chinese: "快点吧，飞机就要起飞了。", pinyin: "Kuài diǎn ba, fēijī jiù yào qǐfēi le.", english: "Hurry up. The plane is about to take off." },
      { order: 16, dialogNumber: 3, dialogLabel: "At the airport", speaker: "小刚", chinese: "您有钱吗？司机把我送到机场的时候，我才发现忘记带钱包了。", pinyin: "Nín yǒu qián ma? Sījī bǎ wǒ sòng dào jīchǎng de shíhou, wǒ cái fāxiàn wàngjì dài qiánbāo le.", english: "Do you have money? It was only when the driver dropped me off at the airport that I realized I forgot my wallet." },
      { order: 17, dialogNumber: 3, dialogLabel: "At the airport", speaker: "周明", chinese: "我看你还是把重要的东西放在我这儿吧。", pinyin: "Wǒ kàn nǐ háishì bǎ zhòngyào de dōngxi fàng zài wǒ zhèr ba.", english: "I think you'd better leave your important things with me." },
    ],
  },
  {
    chapterNumber: 13,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "At home", speaker: "小丽", chinese: "你终于回来了！从哪儿买回来这么多东西啊？", pinyin: "Nǐ zhōngyú huílái le! Cóng nǎr mǎi huílái zhème duō dōngxi a?", english: "You're finally back! Where did you buy so many things?" },
      { order: 2, dialogNumber: 1, dialogLabel: "At home", speaker: "小刚", chinese: "都是从那边的商店买回来的。", pinyin: "Dōu shì cóng nà biān de shāngdiàn mǎi huílái de.", english: "I bought them all from the shops over there." },
      { order: 3, dialogNumber: 1, dialogLabel: "At home", speaker: "小丽", chinese: "怎么还买红酒回来了？谁喝啊？", pinyin: "Zěnme hái mǎi hóngjiǔ huílái le? Shéi hē a?", english: "Why did you buy red wine too? Who's going to drink it?" },
      { order: 4, dialogNumber: 1, dialogLabel: "At home", speaker: "小刚", chinese: "这是给爷爷的礼物，明天我们一起送过去，看看爷爷奶奶。", pinyin: "Zhè shì gěi yéye de lǐwù, míngtiān wǒmen yìqǐ sòng guòqu, kànkan yéye nǎinai.", english: "This is a gift for Grandpa. Tomorrow we'll go together to deliver it and visit Grandpa and Grandma." },
      { order: 5, dialogNumber: 1, dialogLabel: "At home", speaker: "小丽", chinese: "那我的礼物呢？快拿出来让我看看。", pinyin: "Nà wǒ de lǐwù ne? Kuài ná chūlái ràng wǒ kànkan.", english: "What about my gift? Hurry and take it out for me to see." },
      { order: 6, dialogNumber: 1, dialogLabel: "At home", speaker: "小刚", chinese: "我不是已经回来了吗？", pinyin: "Wǒ bú shì yǐjīng huílái le ma?", english: "Haven't I already come back?" },
      { order: 7, dialogNumber: 2, dialogLabel: "At home", speaker: "小丽", chinese: "我今天看见你和一个女的进了咖啡店，她是谁啊？", pinyin: "Wǒ jīntiān kànjiàn nǐ hé yí ge nǚ de jìnle kāfēidiàn, tā shì shéi a?", english: "I saw you go into a coffee shop with a woman today. Who is she?" },
      { order: 8, dialogNumber: 2, dialogLabel: "At home", speaker: "小刚", chinese: "她是我今天在路上遇到的一个老同学。", pinyin: "Tā shì wǒ jīntiān zài lùshang yùdào de yí ge lǎo tóngxué.", english: "She's an old classmate I ran into on the road today." },
      { order: 9, dialogNumber: 2, dialogLabel: "At home", speaker: "小丽", chinese: "你们就一起去喝咖啡了？", pinyin: "Nǐmen jiù yìqǐ qù hē kāfēi le?", english: "You just went for coffee together?" },
      { order: 10, dialogNumber: 2, dialogLabel: "At home", speaker: "小刚", chinese: "是啊，一边喝咖啡一边说了些过去的事。", pinyin: "Shì a, yībiān hē kāfēi yībiān shuōle xiē guòqù de shì.", english: "Yes. We talked about some past things while drinking coffee." },
      { order: 11, dialogNumber: 2, dialogLabel: "At home", speaker: "小丽", chinese: "你回来得这么晚，是说了很多过去的事吗？", pinyin: "Nǐ huílái de zhème wǎn, shì shuōle hěn duō guòqù de shì ma?", english: "You came back so late. Did you talk about a lot of past things?" },
      { order: 12, dialogNumber: 2, dialogLabel: "At home", speaker: "小刚", chinese: "不是。没有公共汽车了，我是走回来的。", pinyin: "Bú shì. Méiyǒu gōnggòng qìchē le, wǒ shì zǒu huílái de.", english: "No. There were no buses, so I walked back." },
      { order: 13, dialogNumber: 3, dialogLabel: "On the phone", speaker: "同事", chinese: "小丽，周末你一般跟小刚出去看电影吗？", pinyin: "Xiǎolì, zhōumò nǐ yībān gēn Xiǎogāng chūqu kàn diànyǐng ma?", english: "Xiaoli, do you usually go to the movies with Xiaogang on weekends?" },
      { order: 14, dialogNumber: 3, dialogLabel: "On the phone", speaker: "小丽", chinese: "我很少去电影院看电影，我更愿意在家看电视。", pinyin: "Wǒ hěn shǎo qù diànyǐngyuàn kàn diànyǐng, wǒ gèng yuànyì zài jiā kàn diànshì.", english: "I rarely go to the cinema. I prefer watching TV at home." },
      { order: 15, dialogNumber: 3, dialogLabel: "On the phone", speaker: "同事", chinese: "看电视有什么意思啊？", pinyin: "Kàn diànshì yǒu shénme yìsi a?", english: "What's so interesting about watching TV?" },
      { order: 16, dialogNumber: 3, dialogLabel: "On the phone", speaker: "小丽", chinese: "可以一边吃一边看，坐久了还可以站起来休息一会儿。", pinyin: "Kěyǐ yībiān chī yībiān kàn, zuò jiǔ le hái kěyǐ zhàn qǐlái xiūxi yíhuìr.", english: "I can eat while watching, and if I sit for too long, I can stand up and rest for a while." },
      { order: 17, dialogNumber: 3, dialogLabel: "On the phone", speaker: "同事", chinese: "你应该多出去走走，这样你们的生活会更有意思。", pinyin: "Nǐ yīnggāi duō chūqu zǒuzou, zhèyàng nǐmen de shēnghuó huì gèng yǒu yìsi.", english: "You should go out more. That would make your life more interesting." },
      { order: 18, dialogNumber: 3, dialogLabel: "On the phone", speaker: "小丽", chinese: "有他在，我的生活已经很有意思了。", pinyin: "Yǒu tā zài, wǒ de shēnghuó yǐjīng hěn yǒu yìsi le.", english: "With him around, my life is already very interesting." },
    ],
  },
  {
    chapterNumber: 14,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "At home", speaker: "周太太", chinese: "客人就要来了，你怎么还不打扫房间啊？", pinyin: "Kèrén jiù yào lái le, nǐ zěnme hái bù dǎsǎo fángjiān a?", english: "The guests are about to arrive. Why haven't you cleaned the room yet?" },
      { order: 2, dialogNumber: 1, dialogLabel: "At home", speaker: "周明", chinese: "别着急，我让孩子们打扫呢，客人来的时候，他们会把房间打扫干净。", pinyin: "Bié zháojí, wǒ ràng háizimen dǎsǎo ne, kèrén lái de shíhou, tāmen huì bǎ fángjiān dǎsǎo gānjìng.", english: "Don't worry. I've asked the kids to clean. When the guests arrive, they'll have the room clean." },
      { order: 3, dialogNumber: 1, dialogLabel: "At home", speaker: "周太太", chinese: "那你也不能看电视啊。", pinyin: "Nà nǐ yě bù néng kàn diànshì a.", english: "But you still can't watch TV." },
      { order: 4, dialogNumber: 1, dialogLabel: "At home", speaker: "周明", chinese: "你让我做什么？", pinyin: "Nǐ ràng wǒ zuò shénme?", english: "What do you want me to do?" },
      { order: 5, dialogNumber: 1, dialogLabel: "At home", speaker: "周太太", chinese: "先把茶和杯子放好，然后把冰箱里的西瓜拿出来。", pinyin: "Xiān bǎ chá hé bēizi fàng hǎo, ránhòu bǎ bīngxiāng li de xīguā ná chūlái.", english: "First put the tea and cups in place, then take the watermelon out of the fridge." },
      { order: 6, dialogNumber: 1, dialogLabel: "At home", speaker: "周明", chinese: "太热了，我还是先把空调打开吧。", pinyin: "Tài rè le, wǒ háishì xiān bǎ kōngtiáo dǎkāi ba.", english: "It's too hot. I'd better turn on the air conditioner first." },
      { order: 7, dialogNumber: 2, dialogLabel: "On the phone", speaker: "同事", chinese: "你在忙什么呢？刚才打你的手机你也不接。", pinyin: "Nǐ zài máng shénme ne? Gāngcái dǎ nǐ de shǒujī nǐ yě bù jiē.", english: "What are you busy with? I called your cell phone just now and you didn't answer." },
      { order: 8, dialogNumber: 2, dialogLabel: "On the phone", speaker: "小刚", chinese: "对不起，我刚洗了个澡，没听见。有什么事吗？", pinyin: "Duìbuqǐ, wǒ gāng xǐle ge zǎo, méi tīngjiàn. Yǒu shénme shì ma?", english: "Sorry. I just took a shower and didn't hear it. What's up?" },
      { order: 9, dialogNumber: 2, dialogLabel: "On the phone", speaker: "同事", chinese: "我想问问你公司里的一些事情。", pinyin: "Wǒ xiǎng wènwen nǐ gōngsī li de yìxiē shìqing.", english: "I wanted to ask you about some things at the company." },
      { order: 10, dialogNumber: 2, dialogLabel: "On the phone", speaker: "小刚", chinese: "你先等一下，我去把电视关了。", pinyin: "Nǐ xiān děng yíxià, wǒ qù bǎ diànshì guān le.", english: "Wait a moment. I'll go turn off the TV." },
      { order: 11, dialogNumber: 2, dialogLabel: "On the phone", speaker: "同事", chinese: "没关系，你先把电视节目看完吧，然后再给我回电话。", pinyin: "Méi guānxi, nǐ xiān bǎ diànshì jiémù kàn wán ba, ránhòu zài gěi wǒ huí diànhuà.", english: "It's OK. Finish watching your TV program first, then call me back." },
      { order: 12, dialogNumber: 3, dialogLabel: "At Xiaoming's home", speaker: "同学", chinese: "今晚的月亮真漂亮，像白色的盘子一样。", pinyin: "Jīn wǎn de yuèliang zhēn piàoliang, xiàng báisè de pánzi yíyàng.", english: "Tonight's moon is so beautiful. It looks like a white plate." },
      { order: 13, dialogNumber: 3, dialogLabel: "At Xiaoming's home", speaker: "小明", chinese: "是啊，外边也不刮风，我们坐在外边一边看月亮一边吃东西，怎么样？", pinyin: "Shì a, wàibiān yě bù guāfēng, wǒmen zuò zài wàibiān yībiān kàn yuèliang yībiān chī dōngxi, zěnmeyàng?", english: "Yes, and it's not windy outside. How about we sit outside, watch the moon, and eat something?" },
      { order: 14, dialogNumber: 3, dialogLabel: "At Xiaoming's home", speaker: "同学", chinese: "好啊，我先把桌椅搬出去，然后你把水果拿过来，我们听叔叔阿姨讲讲他们年轻时候的故事。", pinyin: "Hǎo a, wǒ xiān bǎ zhuōyǐ bān chūqu, ránhòu nǐ bǎ shuǐguǒ ná guòlái, wǒmen tīng shūshu āyí jiǎngjiang tāmen niánqīng shíhou de gùshi.", english: "Great. I'll move the table and chairs out first, then you bring the fruit over. We can listen to Uncle and Auntie tell stories from their youth." },
      { order: 15, dialogNumber: 3, dialogLabel: "At Xiaoming's home", speaker: "小明", chinese: "太好了！记得给大山打个电话，让他马上过来。", pinyin: "Tài hǎo le! Jìde gěi Dàshān dǎ ge diànhuà, ràng tā mǎshàng guòlái.", english: "Awesome! Remember to call Dashan and tell him to come right away." },
      { order: 16, dialogNumber: 3, dialogLabel: "At Xiaoming's home", speaker: "同学", chinese: "不用打了，你听外边的声音，一定是大山。", pinyin: "Bú yòng dǎ le, nǐ tīng wàibiān de shēngyīn, yídìng shì Dàshān.", english: "No need to call. Listen to the voice outside – it must be Dashan." },
    ],
  },
  {
    chapterNumber: 15,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the office", speaker: "大山", chinese: "老师，我来中国留学两年了，但是我的汉语水平提高得一点儿也不快啊。", pinyin: "Lǎoshī, wǒ lái Zhōngguó liúxué liǎng nián le, dànshì wǒ de Hànyǔ shuǐpíng tígāo de yìdiǎnr yě bù kuài a.", english: "Teacher, I've been studying in China for two years, but my Chinese level hasn't improved much at all." },
      { order: 2, dialogNumber: 1, dialogLabel: "In the office", speaker: "老师", chinese: "你每天认真学习，做练习、完成作业，一直不错啊。", pinyin: "Nǐ měi tiān rènzhēn xuéxí, zuò liànxí, wánchéng zuòyè, yìzhí búcuò a.", english: "You study hard every day, do exercises, and finish homework. You've been doing well." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the office", speaker: "大山", chinese: "这是我昨天的作业，您帮我看看对不对。", pinyin: "Zhè shì wǒ zuótiān de zuòyè, nín bāng wǒ kànkan duì bu duì.", english: "This is my homework from yesterday. Please check if it's correct." },
      { order: 4, dialogNumber: 1, dialogLabel: "In the office", speaker: "老师", chinese: "写得不错，除了这个句子意思有些不清楚外，其他都没什么问题。", pinyin: "Xiě de búcuò, chúle zhège jùzi yìsi yǒuxiē bù qīngchu wài, qítā dōu méi shénme wèntí.", english: "Well written. Except that the meaning of this sentence is a bit unclear, the rest are all fine." },
      { order: 5, dialogNumber: 1, dialogLabel: "In the office", speaker: "大山", chinese: "谢谢老师！", pinyin: "Xièxie lǎoshī!", english: "Thank you, teacher!" },
      { order: 6, dialogNumber: 1, dialogLabel: "In the office", speaker: "老师", chinese: "以后有什么不明白的地方，可以给我打电话或者发电子邮件。", pinyin: "Yǐhòu yǒu shénme bù míngbai de dìfang, kěyǐ gěi wǒ dǎ diànhuà huòzhě fā diànzǐ yóujiàn.", english: "If there's anything you don't understand in the future, you can call me or send me an email." },
      { order: 7, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "学生", chinese: "老师，除了小云，其他人都来了。", pinyin: "Lǎoshī, chúle Xiǎoyún, qítā rén dōu lái le.", english: "Teacher, everyone has come except Xiaoyun." },
      { order: 8, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "老师", chinese: "比赛马上就要开始了，小云怎么还没来？", pinyin: "Bǐsài mǎshàng jiù yào kāishǐ le, Xiǎoyún zěnme hái méi lái?", english: "The competition is about to start. Why hasn't Xiaoyun arrived yet?" },
      { order: 9, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "学生", chinese: "刚才给她打电话了，她在路上呢。", pinyin: "Gāngcái gěi tā dǎ diànhuà le, tā zài lùshang ne.", english: "I called her just now. She's on the way." },
      { order: 10, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "老师", chinese: "不等她了，我先给大家讲讲这次比赛的要求和一些需要注意的地方。", pinyin: "Bù děng tā le, wǒ xiān gěi dàjiā jiǎngjiang zhè cì bǐsài de yāoqiú hé yìxiē xūyào zhùyì de dìfang.", english: "Let's not wait for her. I'll first explain the requirements of this competition and some things to pay attention to." },
      { order: 11, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "学生", chinese: "老师，您放心，今天的比赛我们一定能拿第一。", pinyin: "Lǎoshī, nín fàngxīn, jīntiān de bǐsài wǒmen yídìng néng ná dì yī.", english: "Teacher, don't worry. We'll definitely get first place in today's competition." },
      { order: 12, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "现在用电脑上网真方便啊！", pinyin: "Xiànzài yòng diànnǎo shàngwǎng zhēn fāngbiàn a!", english: "It's so convenient to use a computer to go online now!" },
      { order: 13, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小刚", chinese: "是啊，除了看新闻，人们还可以在网上听歌、看电影、买东西。", pinyin: "Shì a, chúle kàn xīnwén, rénmen hái kěyǐ zài wǎngshang tīng gē, kàn diànyǐng, mǎi dōngxi.", english: "Yes. Besides reading news, people can also listen to music, watch movies, and shop online." },
      { order: 14, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "对了，你从网上买的那件衣服呢？怎么没见你穿？", pinyin: "Duìle, nǐ cóng wǎngshang mǎi de nà jiàn yīfu ne? Zěnme méi jiàn nǐ chuān?", english: "By the way, what about that piece of clothing you bought online? Why haven't I seen you wear it?" },
      { order: 15, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小刚", chinese: "那件衣服我穿着有点儿小，给我弟弟了。", pinyin: "Nà jiàn yīfu wǒ chuān zhe yǒudiǎnr xiǎo, gěi wǒ dìdi le.", english: "That piece of clothing is a bit small on me. I gave it to my younger brother." },
      { order: 16, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "同事", chinese: "他满意吗？", pinyin: "Tā mǎnyì ma?", english: "Is he satisfied?" },
      { order: 17, dialogNumber: 3, dialogLabel: "In the lounge", speaker: "小刚", chinese: "不用花钱，还有新衣服穿，他满意极了。", pinyin: "Bú yòng huā qián, hái yǒu xīn yīfu chuān, tā mǎnyì jí le.", english: "He didn't have to spend money and got new clothes – he's extremely satisfied." },
    ],
  },
  {
    chapterNumber: 16,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the company", speaker: "小丽", chinese: "我不喜欢一直住在同一个城市，想去其他城市看一看。", pinyin: "Wǒ bù xǐhuān yìzhí zhù zài tóng yí ge chéngshì, xiǎng qù qítā chéngshì kàn yí kàn.", english: "I don't like living in the same city all the time. I want to go see other cities." },
      { order: 2, dialogNumber: 1, dialogLabel: "In the company", speaker: "周明", chinese: "我年轻的时候也这么想，但是那时候没有钱，如果有钱，就去了。", pinyin: "Wǒ niánqīng de shíhou yě zhème xiǎng, dànshì nà shíhou méiyǒu qián, rúguǒ yǒu qián, jiù qù le.", english: "I thought the same when I was young, but I didn't have money then. If I had had money, I would have gone." },
      { order: 3, dialogNumber: 1, dialogLabel: "In the company", speaker: "小丽", chinese: "那您现在为什么不去？", pinyin: "Nà nín xiànzài wèi shénme bú qù?", english: "Then why don't you go now?" },
      { order: 4, dialogNumber: 1, dialogLabel: "In the company", speaker: "周明", chinese: "现在钱不是问题了，主要是没有时间。", pinyin: "Xiànzài qián bú shì wèntí le, zhǔyào shì méiyǒu shíjiān.", english: "Now money isn't the problem. The main issue is not having time." },
      { order: 5, dialogNumber: 1, dialogLabel: "In the company", speaker: "小丽", chinese: "我认为现在您有时间也不会出去玩儿。", pinyin: "Wǒ rènwéi xiànzài nín yǒu shíjiān yě bú huì chūqu wánr.", english: "I think even if you had time now, you still wouldn't go out." },
      { order: 6, dialogNumber: 1, dialogLabel: "In the company", speaker: "周明", chinese: "你说得对，我现在累得下了班就想睡觉。", pinyin: "Nǐ shuō de duì, wǒ xiànzài lèi de xiàle bān jiù xiǎng shuìjiào.", english: "You're right. I'm so tired now that all I want to do after work is sleep." },
      { order: 7, dialogNumber: 2, dialogLabel: "At a colleague's home", speaker: "同事", chinese: "谢谢你们来看我女儿。你送的小皮鞋和小帽子真漂亮！", pinyin: "Xièxie nǐmen lái kàn wǒ nǚ'ér. Nǐ sòng de xiǎo píxié hé xiǎo màozi zhēn piàoliang!", english: "Thank you for coming to see my daughter. The little leather shoes and hat you gave are so beautiful!" },
      { order: 8, dialogNumber: 2, dialogLabel: "At a colleague's home", speaker: "小丽", chinese: "别客气，你女儿长得白白的、胖胖的，真可爱！现在多高了？", pinyin: "Bié kèqi, nǐ nǚ'ér zhǎng de báibái de, pàngpàng de, zhēn kě'ài! Xiànzài duō gāo le?", english: "Don't mention it. Your daughter is fair and chubby – so adorable! How tall is she now?" },
      { order: 9, dialogNumber: 2, dialogLabel: "At a colleague's home", speaker: "同事", chinese: "快1米了，25公斤。", pinyin: "Kuài yī mǐ le, èrshíwǔ gōngjīn.", english: "Almost one meter, 25 kilograms." },
      { order: 10, dialogNumber: 2, dialogLabel: "At a colleague's home", speaker: "小丽", chinese: "你看她鼻子小小的，头发黑黑的；长得像谁？", pinyin: "Nǐ kàn tā bízi xiǎoxiǎo de, tóufa hēihēi de; zhǎng de xiàng shéi?", english: "Look at her – small nose, black hair. Who does she look like?" },
      { order: 11, dialogNumber: 2, dialogLabel: "At a colleague's home", speaker: "同事", chinese: "像她爸爸，刚出生时她爸爸高兴得一个晚上都没睡着。", pinyin: "Xiàng tā bàba, gāng chūshēng shí tā bàba gāoxìng de yí ge wǎnshang dōu méi shuìzháo.", english: "She looks like her father. When she was born, her father was so happy he couldn't sleep the whole night." },
      { order: 12, dialogNumber: 3, dialogLabel: "In the company", speaker: "小刚", chinese: "我的牙还是很疼。", pinyin: "Wǒ de yá háishì hěn téng.", english: "My tooth still hurts a lot." },
      { order: 13, dialogNumber: 3, dialogLabel: "In the company", speaker: "同事", chinese: "如果不舒服，就去医院检查一下吧。", pinyin: "Rúguǒ bù shūfu, jiù qù yīyuàn jiǎnchá yíxià ba.", english: "If you're not feeling well, go to the hospital and get it checked." },
      { order: 14, dialogNumber: 3, dialogLabel: "In the company", speaker: "小刚", chinese: "检查好几次了，但是没什么用。", pinyin: "Jiǎnchá hǎo jǐ cì le, dànshì méi shénme yòng.", english: "I've had it checked several times, but it's not much use." },
      { order: 15, dialogNumber: 3, dialogLabel: "In the company", speaker: "同事", chinese: "大夫怎么说的？", pinyin: "Dàifu zěnme shuō de?", english: "What did the doctor say?" },
      { order: 16, dialogNumber: 3, dialogLabel: "In the company", speaker: "小刚", chinese: "每次医生都告诉我，回家好好儿刷牙。", pinyin: "Měi cì yīshēng dōu gàosu wǒ, huí jiā hǎohāor shuāyá.", english: "Every time the doctor tells me to go home and brush my teeth properly." },
    ],
  },
  {
    chapterNumber: 17,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the company", speaker: "小丽", chinese: "周经理，下个星期我可以请几天假吗？", pinyin: "Zhōu jīnglǐ, xià ge xīngqī wǒ kěyǐ qǐng jǐ tiān jià ma?", english: "Manager Zhou, can I take a few days off next week?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the company", speaker: "周明", chinese: "你有什么事？", pinyin: "Nǐ yǒu shénme shì?", english: "What's the matter?" },
      { order: 3, dialogNumber: 1, dialogLabel: "In the company", speaker: "小丽", chinese: "我的一个老朋友结婚，我跟他两年没见了。", pinyin: "Wǒ de yí ge lǎo péngyou jiéhūn, wǒ gēn tā liǎng nián méi jiàn le.", english: "An old friend of mine is getting married. I haven't seen him for two years." },
      { order: 4, dialogNumber: 1, dialogLabel: "In the company", speaker: "周明", chinese: "你一共想请几天假？", pinyin: "Nǐ yígòng xiǎng qǐng jǐ tiān jià?", english: "How many days do you want to take off in total?" },
      { order: 5, dialogNumber: 1, dialogLabel: "In the company", speaker: "小丽", chinese: "三天。", pinyin: "Sān tiān.", english: "Three days." },
      { order: 6, dialogNumber: 2, dialogLabel: "In the company", speaker: "同事", chinese: "小丽，那个高高的男人是你们公司的吗？你对他了解吗？", pinyin: "Xiǎolì, nàge gāogāo de nánrén shì nǐmen gōngsī de ma? Nǐ duì tā liǎojiě ma?", english: "Xiaoli, is that tall man from your company? Do you know him?" },
      { order: 7, dialogNumber: 2, dialogLabel: "In the company", speaker: "小丽", chinese: "我们过去是邻居，后来是大学同学，关系一直很不错。", pinyin: "Wǒmen guòqù shì línjū, hòulái shì dàxué tóngxué, guānxi yìzhí hěn búcuò.", english: "We used to be neighbors, and later we were college classmates. Our relationship has always been very good." },
      { order: 8, dialogNumber: 2, dialogLabel: "In the company", speaker: "同事", chinese: "他一般喜欢做什么？", pinyin: "Tā yībān xǐhuān zuò shénme?", english: "What does he usually like to do?" },
      { order: 9, dialogNumber: 2, dialogLabel: "In the company", speaker: "小丽", chinese: "他有很多爱好，唱歌、画画儿、踢足球，什么都会。", pinyin: "Tā yǒu hěn duō àihào, chànggē, huà huàr, tī zúqiú, shénme dōu huì.", english: "He has many hobbies – singing, drawing, playing football. He can do everything." },
      { order: 10, dialogNumber: 2, dialogLabel: "In the company", speaker: "同事", chinese: "真的？那你介绍我们认识认识吧。", pinyin: "Zhēn de? Nà nǐ jièshào wǒmen rènshi rènshi ba.", english: "Really? Then introduce us!" },
      { order: 11, dialogNumber: 2, dialogLabel: "In the company", speaker: "小丽", chinese: "不行，现在他是我丈夫。", pinyin: "Bù xíng, xiànzài tā shì wǒ zhàngfu.", english: "No way. He's my husband now." },
      { order: 12, dialogNumber: 3, dialogLabel: "At home", speaker: "周太太", chinese: "最近我觉得哪儿都不舒服，你带我去医院检查检查吧。", pinyin: "Zuìjìn wǒ juéde nǎr dōu bù shūfu, nǐ dài wǒ qù yīyuàn jiǎnchá jiǎnchá ba.", english: "Lately I feel uncomfortable everywhere. Take me to the hospital for a checkup." },
      { order: 13, dialogNumber: 3, dialogLabel: "At home", speaker: "周明", chinese: "不用去医院，谁都有办法看好你的\"病\"。我问你，你多久没运动了？", pinyin: "Bú yòng qù yīyuàn, shéi dōu yǒu bànfǎ kànhǎo nǐ de \"bìng\". Wǒ wèn nǐ, nǐ duō jiǔ méi yùndòng le?", english: "No need to go to the hospital. Everyone has a way to cure your \"illness\". Let me ask you – how long has it been since you last exercised?" },
      { order: 14, dialogNumber: 3, dialogLabel: "At home", speaker: "周太太", chinese: "我三年没运动了。", pinyin: "Wǒ sān nián méi yùndòng le.", english: "I haven't exercised for three years." },
      { order: 15, dialogNumber: 3, dialogLabel: "At home", speaker: "周明", chinese: "谁都知道运动对身体好。但是你吃饱了就睡。", pinyin: "Shéi dōu zhīdào yùndòng duì shēntǐ hǎo. Dànshì nǐ chībǎo le jiù shuì.", english: "Everyone knows exercise is good for health. But you go to sleep right after eating your fill." },
      { order: 16, dialogNumber: 3, dialogLabel: "At home", speaker: "周太太", chinese: "为了健康，我真应该多锻炼锻炼了。从明天起，我决定每天去长跑。", pinyin: "Wèile jiànkāng, wǒ zhēn yīnggāi duō duànliàn duànliàn le. Cóng míngtiān qǐ, wǒ juédìng měi tiān qù chángpǎo.", english: "For the sake of my health, I really should exercise more. Starting tomorrow, I've decided to go running every day." },
    ],
  },
  {
    chapterNumber: 18,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "On the phone", speaker: "朋友", chinese: "老周，我打算买房子了，想向你借点儿钱。", pinyin: "Lǎo Zhōu, wǒ dǎsuàn mǎi fángzi le, xiǎng xiàng nǐ jiè diǎnr qián.", english: "Old Zhou, I'm planning to buy a house. I want to borrow some money from you." },
      { order: 2, dialogNumber: 1, dialogLabel: "On the phone", speaker: "周明", chinese: "没问题，只要我有，就一定会借给你的。还差多少？", pinyin: "Méi wèntí, zhǐyào wǒ yǒu, jiù yídìng huì jiè gěi nǐ de. Hái chà duōshao?", english: "No problem. As long as I have it, I'll definitely lend it to you. How much are you short?" },
      { order: 3, dialogNumber: 1, dialogLabel: "On the phone", speaker: "朋友", chinese: "还差5万块钱。", pinyin: "Hái chà wǔ wàn kuài qián.", english: "I'm still short 50,000 yuan." },
      { order: 4, dialogNumber: 1, dialogLabel: "On the phone", speaker: "周明", chinese: "好，钱下午打给你。你打算在哪儿买房？", pinyin: "Hǎo, qián xiàwǔ dǎ gěi nǐ. Nǐ dǎsuàn zài nǎr mǎi fáng?", english: "OK. I'll transfer the money to you this afternoon. Where are you planning to buy the house?" },
      { order: 5, dialogNumber: 1, dialogLabel: "On the phone", speaker: "朋友", chinese: "就在我们医院前面。", pinyin: "Jiù zài wǒmen yīyuàn qiánmiàn.", english: "Right in front of our hospital." },
      { order: 6, dialogNumber: 1, dialogLabel: "On the phone", speaker: "周明", chinese: "那你以后去医院就方便了。", pinyin: "Nà nǐ yǐhòu qù yīyuàn jiù fāngbiàn le.", english: "Then it'll be convenient for you to go to the hospital." },
      { order: 7, dialogNumber: 2, dialogLabel: "In a store", speaker: "小明", chinese: "妈妈，你看那只狗多可爱，眼睛大大的，嘴小小的，我们买回去吧。", pinyin: "Māma, nǐ kàn nà zhī gǒu duō kě'ài, yǎnjīng dàdà de, zuǐ xiǎoxiǎo de, wǒmen mǎi huíqù ba.", english: "Mom, look at that dog – so cute! Big eyes, small mouth. Let's buy it and take it home." },
      { order: 8, dialogNumber: 2, dialogLabel: "In a store", speaker: "妈妈", chinese: "动物和小孩儿一样，都需要人照顾。买回家去，谁照顾它啊？", pinyin: "Dòngwù hé xiǎoháir yíyàng, dōu xūyào rén zhàogù. Mǎi huí jiā qù, shéi zhàogù tā a?", english: "Animals are like children – they all need people to take care of them. If we take it home, who will take care of it?" },
      { order: 9, dialogNumber: 2, dialogLabel: "In a store", speaker: "小明", chinese: "我照顾啊。", pinyin: "Wǒ zhàogù a.", english: "I will." },
      { order: 10, dialogNumber: 2, dialogLabel: "In a store", speaker: "妈妈", chinese: "这段时间你自己的衣服都没洗，你能照顾好它吗？", pinyin: "Zhè duàn shíjiān nǐ zìjǐ de yīfu dōu méi xǐ, nǐ néng zhàogù hǎo tā ma?", english: "You haven't even washed your own clothes lately. Can you really take good care of it?" },
      { order: 11, dialogNumber: 2, dialogLabel: "In a store", speaker: "小明", chinese: "只要你给我买，我就能照顾好它。", pinyin: "Zhǐyào nǐ gěi wǒ mǎi, wǒ jiù néng zhàogù hǎo tā.", english: "As long as you buy it for me, I'll be able to take good care of it." },
      { order: 12, dialogNumber: 3, dialogLabel: "In the company", speaker: "经理", chinese: "说说你为什么选择来我们公司工作。", pinyin: "Shuōshuo nǐ wèi shénme xuǎnzé lái wǒmen gōngsī gōngzuò.", english: "Tell me why you chose to come to our company." },
      { order: 13, dialogNumber: 3, dialogLabel: "In the company", speaker: "学生", chinese: "贵公司不但很有名，而且工作环境好。", pinyin: "Guì gōngsī búdàn hěn yǒumíng, érqiě gōngzuò huánjìng hǎo.", english: "Your company is not only very famous, but also has a good working environment." },
      { order: 14, dialogNumber: 3, dialogLabel: "In the company", speaker: "经理", chinese: "做这个工作有点儿累，需要经常去外地。你家人同意吗？", pinyin: "Zuò zhège gōngzuò yǒudiǎnr lèi, xūyào jīngcháng qù wàidì. Nǐ jiārén tóngyì ma?", english: "This job is a bit tiring and requires frequent travel. Does your family agree?" },
      { order: 15, dialogNumber: 3, dialogLabel: "In the company", speaker: "学生", chinese: "只要我愿意，我相信他们就会同意的。", pinyin: "Zhǐyào wǒ yuànyì, wǒ xiāngxìn tāmen jiù huì tóngyì de.", english: "As long as I'm willing, I believe they'll agree." },
      { order: 16, dialogNumber: 3, dialogLabel: "In the company", speaker: "经理", chinese: "好，那你明天来上班吧。关于这个工作，还有什么问题吗？", pinyin: "Hǎo, nà nǐ míngtiān lái shàngbān ba. Guānyú zhège gōngzuò, hái yǒu shénme wèntí ma?", english: "OK. Then come to work tomorrow. Regarding this job, do you have any other questions?" },
      { order: 17, dialogNumber: 3, dialogLabel: "In the company", speaker: "学生", chinese: "没有了，谢谢您给我这个机会，我会努力的。", pinyin: "Méiyǒu le, xièxie nín gěi wǒ zhège jīhuì, wǒ huì nǔlì de.", english: "No more. Thank you for giving me this opportunity. I'll work hard." },
    ],
  },
  {
    chapterNumber: 19,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "At home", speaker: "爸爸", chinese: "女儿最近喜欢把头发放在耳朵后面，你知道为什么吗？", pinyin: "Nǚ'ér zuìjìn xǐhuān bǎ tóufa fàng zài ěrduo hòumiàn, nǐ zhīdào wèi shénme ma?", english: "Our daughter has recently been liking to put her hair behind her ears. Do you know why?" },
      { order: 2, dialogNumber: 1, dialogLabel: "At home", speaker: "妈妈", chinese: "这样可以使她的脸看上去漂亮一些。", pinyin: "Zhèyàng kěyǐ shǐ tā de liǎn kàn shàngqu piàoliang yìxiē.", english: "This makes her face look a bit prettier." },
      { order: 3, dialogNumber: 1, dialogLabel: "At home", speaker: "爸爸", chinese: "我最近觉得她和以前不太一样了。", pinyin: "Wǒ zuìjìn juéde tā hé yǐqián bú tài yíyàng le.", english: "I've recently felt that she's not quite the same as before." },
      { order: 4, dialogNumber: 1, dialogLabel: "At home", speaker: "妈妈", chinese: "女儿变化不小，她小时候喜欢短头发，像男孩子一样。", pinyin: "Nǚ'ér biànhuà bù xiǎo, tā xiǎo shíhou xǐhuān duǎn tóufa, xiàng nán háizi yíyàng.", english: "Our daughter has changed a lot. When she was little, she liked short hair, like a boy." },
      { order: 5, dialogNumber: 1, dialogLabel: "At home", speaker: "爸爸", chinese: "我也想起来了。她现在慢慢地开始像个女孩子了。", pinyin: "Wǒ yě xiǎng qǐlái le. Tā xiànzài mànmàn de kāishǐ xiàng ge nǚ háizi le.", english: "I remember now too. She's slowly starting to look like a girl." },
      { order: 6, dialogNumber: 2, dialogLabel: "Looking at a photo", speaker: "小丽", chinese: "上次我们参加骑马比赛的照片，我选了几张洗出来了。", pinyin: "Shàng cì wǒmen cānjiā qí mǎ bǐsài de zhàopiàn, wǒ xuǎnle jǐ zhāng xǐ chūlái le.", english: "I picked a few photos from last time's horse-riding competition and had them developed." },
      { order: 7, dialogNumber: 2, dialogLabel: "Looking at a photo", speaker: "同事", chinese: "快给我看看。骑得最快的这位是谁？", pinyin: "Kuài gěi wǒ kànkan. Qí de zuì kuài de zhè wèi shì shéi?", english: "Let me see! Who is this one riding the fastest?" },
      { order: 8, dialogNumber: 2, dialogLabel: "Looking at a photo", speaker: "小丽", chinese: "你没看出来吗？他是小刚啊。", pinyin: "Nǐ méi kàn chūlái ma? Tā shì Xiǎogāng a.", english: "Didn't you recognise him? It's Xiaogang." },
      { order: 9, dialogNumber: 2, dialogLabel: "Looking at a photo", speaker: "同事", chinese: "怎么看上去跟现在不太一样？", pinyin: "Zěnme kàn shàngqu gēn xiànzài bú tài yíyàng?", english: "Why doesn't he look quite the same as now?" },
      { order: 10, dialogNumber: 2, dialogLabel: "Looking at a photo", speaker: "小丽", chinese: "他上班穿西服、衬衫，比赛的时候穿的是运动服。", pinyin: "Tā shàngbān chuān xīfú, chènshān, bǐsài de shíhou chuān de shì yùndòngfú.", english: "He wears a suit and shirt to work, but during the competition he wore sportswear." },
      { order: 11, dialogNumber: 2, dialogLabel: "Looking at a photo", speaker: "同事", chinese: "他今天穿蓝西服，看上去像40多岁，还是穿运动服让他更年轻。", pinyin: "Tā jīntiān chuān lán xīfú, kàn shàngqu xiàng sìshí duō suì, háishì chuān yùndòngfú ràng tā gèng niánqīng.", english: "He's wearing a blue suit today and looks over 40. Sportswear makes him look younger." },
      { order: 12, dialogNumber: 3, dialogLabel: "At Xiaoli's home", speaker: "朋友", chinese: "我们一年没见面了吧？", pinyin: "Wǒmen yì nián méi jiànmiàn le ba?", english: "We haven't seen each other for a year, have we?" },
      { order: 13, dialogNumber: 3, dialogLabel: "At Xiaoli's home", speaker: "小丽", chinese: "听说你都有女儿了？她多大了？", pinyin: "Tīngshuō nǐ dōu yǒu nǚ'ér le? Tā duō dà le?", english: "I heard you have a daughter now? How old is she?" },
      { order: 14, dialogNumber: 3, dialogLabel: "At Xiaoli's home", speaker: "朋友", chinese: "她去年秋天出生的，刚过完一岁生日。", pinyin: "Tā qùnián qiūtiān chūshēng de, gāng guòwán yī suì shēngrì.", english: "She was born last autumn. She just had her first birthday." },
      { order: 15, dialogNumber: 3, dialogLabel: "At Xiaoli's home", speaker: "小丽", chinese: "她喜欢什么？我送给她。", pinyin: "Tā xǐhuān shénme? Wǒ sòng gěi tā.", english: "What does she like? I'll give it to her." },
      { order: 16, dialogNumber: 3, dialogLabel: "At Xiaoli's home", speaker: "朋友", chinese: "她就喜欢听她爸爸学鸟叫。哭的时候，只要他爸爸学小鸟叫，她马上就安静下来了。", pinyin: "Tā jiù xǐhuān tīng tā bàba xué niǎo jiào. Kū de shíhou, zhǐyào tā bàba xué xiǎo niǎo jiào, tā mǎshàng jiù ānjìng xiàlái le.", english: "She just likes to hear her father imitate bird calls. When she cries, as long as her father imitates a little bird, she immediately calms down." },
      { order: 17, dialogNumber: 3, dialogLabel: "At Xiaoli's home", speaker: "小丽", chinese: "啊？这个礼物我没办法送。", pinyin: "A? Zhège lǐwù wǒ méi bànfǎ sòng.", english: "Ah? I can't give that as a gift!" },
    ],
  },
  {
    chapterNumber: 20,
    lines: [
      { order: 1, dialogNumber: 1, dialogLabel: "In the lounge", speaker: "小丽", chinese: "我的照相机被谁拿走了？怎么找不到了？", pinyin: "Wǒ de zhàoxiàngjī bèi shéi názǒu le? Zěnme zhǎo bu dào le?", english: "Who took my camera? Why can't I find it?" },
      { order: 2, dialogNumber: 1, dialogLabel: "In the lounge", speaker: "同事", chinese: "你再找找。是不是没带来？", pinyin: "Nǐ zài zhǎozhao. Shì bu shì méi dàilái?", english: "Look again. Maybe you didn't bring it?" },
      { order: 3, dialogNumber: 1, dialogLabel: "In the lounge", speaker: "小丽", chinese: "我找了，没找到啊。", pinyin: "Wǒ zhǎo le, méi zhǎodào a.", english: "I looked, but I couldn't find it." },
      { order: 4, dialogNumber: 1, dialogLabel: "In the lounge", speaker: "同事", chinese: "别难过，再买一个吧，公司东门外不就有一个大商场吗？", pinyin: "Bié nánguò, zài mǎi yí ge ba, gōngsī dōngmén wài bú jiù yǒu yí ge dà shāngchǎng ma?", english: "Don't be sad. Buy another one. Isn't there a big mall just outside the company's east gate?" },
      { order: 5, dialogNumber: 1, dialogLabel: "In the lounge", speaker: "小丽", chinese: "但是我这个月信用卡里的钱已经花得差不多了。", pinyin: "Dànshì wǒ zhège yuè xìnyòngkǎ li de qián yǐjīng huā de chà bu duō le.", english: "But I've already spent most of the money on my credit card this month." },
      { order: 6, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "小明", chinese: "你怎么突然关心起体育来了？", pinyin: "Nǐ zěnme tūrán guānxīn qǐ tǐyù lái le?", english: "Why have you suddenly become interested in sports?" },
      { order: 7, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "朋友", chinese: "我的男朋友喜欢看足球比赛，我被他影响的。", pinyin: "Wǒ de nánpéngyou xǐhuān kàn zúqiú bǐsài, wǒ bèi tā yǐngxiǎng de.", english: "My boyfriend likes watching football matches. I've been influenced by him." },
      { order: 8, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "小明", chinese: "看来只有爱，才能让人有变化。", pinyin: "Kànlái zhǐyǒu ài, cái néng ràng rén yǒu biànhuà.", english: "It seems that only love can make a person change." },
      { order: 9, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "朋友", chinese: "是啊，为了和他的爱好一样，我天天看球赛。", pinyin: "Shì a, wèile hé tā de àihào yíyàng, wǒ tiāntiān kàn qiúsài.", english: "Yes. To have the same hobby as him, I watch matches every day." },
      { order: 10, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "小明", chinese: "除了足球，他还影响你什么了？", pinyin: "Chúle zúqiú, tā hái yǐngxiǎng nǐ shénme le?", english: "Besides football, what else has he influenced you in?" },
      { order: 11, dialogNumber: 2, dialogLabel: "In the classroom", speaker: "朋友", chinese: "我最近天天上网玩儿游戏，我的成绩差极了。", pinyin: "Wǒ zuìjìn tiāntiān shàngwǎng wánr yóuxì, wǒ de chéngjī chà jí le.", english: "Lately I've been playing games online every day. My grades are terrible." },
      { order: 12, dialogNumber: 3, dialogLabel: "In the restaurant", speaker: "朋友", chinese: "那个拿着碗吃饭的人是你哥哥吗？他和你长得真像。", pinyin: "Nàge ná zhe wǎn chī fàn de rén shì nǐ gēge ma? Tā hé nǐ zhǎng de zhēn xiàng.", english: "Is that person holding a bowl and eating your older brother? He really looks like you." },
      { order: 13, dialogNumber: 3, dialogLabel: "In the restaurant", speaker: "大卫", chinese: "我们经常被别人认错。", pinyin: "Wǒmen jīngcháng bèi biérén rèncuò.", english: "We're often mistaken for each other." },
      { order: 14, dialogNumber: 3, dialogLabel: "In the restaurant", speaker: "朋友", chinese: "只有你们的爸爸妈妈才能分出来哪个是哥哥，哪个是弟弟吧。", pinyin: "Zhǐyǒu nǐmen de bàba māma cái néng fēn chūlái nǎge shì gēge, nǎge shì dìdi ba.", english: "Only your parents can tell which one is the older brother and which is the younger brother, right?" },
      { order: 15, dialogNumber: 3, dialogLabel: "In the restaurant", speaker: "大卫", chinese: "除了父母以外，还有我们自己也能啊。", pinyin: "Chúle fùmǔ yǐwài, hái yǒu wǒmen zìjǐ yě néng a.", english: "Besides our parents, we ourselves can too." },
      { order: 16, dialogNumber: 3, dialogLabel: "In the restaurant", speaker: "朋友", chinese: "你们两个除了长得像，还有什么相同的地方？", pinyin: "Nǐmen liǎng ge chúle zhǎng de xiàng, hái yǒu shénme xiāngtóng de dìfang?", english: "Besides looking alike, what else do you two have in common?" },
      { order: 17, dialogNumber: 3, dialogLabel: "In the restaurant", speaker: "大卫", chinese: "我们住在同一个楼、同一个房间……", pinyin: "Wǒmen zhù zài tóng yí ge lóu, tóng yí ge fángjiān...", english: "We live in the same building, the same room..." },
    ],
  },
];
