import type { CombinedVocabRow } from "./vocab-row";

// HSK4A's combined word list, unlike HSK1-3, is not parsed from a PDF — it's
// transcribed directly from the "生词 New Words" appendix (pages 131-144) of
// the HSK 4 (上册) Standard Course textbook, as pasted by the user
// word-for-word. No PDF-diff corrections are needed since the source is
// already a clean transcription.
//
// Deliberately excluded, per the same appendix: 专有名词 Proper Nouns (see
// the no-proper-nouns rule), 超纲词 Words Not Included in the Syllabus,
// 旧字新词 New Words Made Up of Characters Learned Before, and 补充
// Supplementary Vocabulary — none of these are the book's official new-word
// list.
export const HSK4A_COMBINED_WORDS: CombinedVocabRow[] = [
  { chinese: "爱情", pinyin: "àiqíng", english: "love (between a man and a woman)", category: "Noun" },
  { chinese: "安排", pinyin: "ānpái", english: "to arrange", category: "Verb" },
  { chinese: "按时", pinyin: "ànshí", english: "on time, on schedule", category: "Adverb" },
  { chinese: "按照", pinyin: "ànzhào", english: "according to", category: "Preposition" },

  { chinese: "百分之", pinyin: "bǎi fēn zhī", english: "percent", category: null },
  { chinese: "保证", pinyin: "bǎozhèng", english: "to guarantee", category: "Verb" },
  { chinese: "倍", pinyin: "bèi", english: "times, -fold", category: "Quantifier" },
  { chinese: "本来", pinyin: "běnlái", english: "originally, at first", category: "Adverb" },
  { chinese: "比如", pinyin: "bǐrú", english: "for example, such as", category: "Verb" },
  { chinese: "毕业", pinyin: "bì yè", english: "to graduate", category: "Verb" },
  { chinese: "标准", pinyin: "biāozhǔn", english: "standard", category: "Noun" },
  { chinese: "饼干", pinyin: "bǐnggān", english: "biscuit", category: "Noun" },
  { chinese: "不得不", pinyin: "bù dé bù", english: "to have to, to have no choice but", category: null },
  { chinese: "不管", pinyin: "bùguǎn", english: "no matter (what, how, etc.)", category: "Conjunction" },
  { chinese: "不过", pinyin: "búguò", english: "but, yet", category: "Conjunction" },
  { chinese: "不仅", pinyin: "bùjǐn", english: "not only", category: "Conjunction" },

  { chinese: "擦", pinyin: "cā", english: "to wipe", category: "Verb" },
  { chinese: "材料", pinyin: "cáiliào", english: "data, material", category: "Noun" },
  { chinese: "差不多", pinyin: "chàbuduō", english: "almost", category: "Adverb" },
  { chinese: "尝", pinyin: "cháng", english: "to taste", category: "Verb" },
  { chinese: "超过", pinyin: "chāoguò", english: "to exceed, to surpass", category: "Verb" },
  { chinese: "成功", pinyin: "chénggōng", english: "successful", category: "Adjective" },
  { chinese: "成为", pinyin: "chéngwéi", english: "to become", category: "Verb" },
  { chinese: "诚实", pinyin: "chéngshí", english: "honest", category: "Adjective" },
  { chinese: "重新", pinyin: "chóngxīn", english: "again, once more", category: "Adverb" },
  { chinese: "抽烟", pinyin: "chōu yān", english: "to smoke", category: null },
  { chinese: "出现", pinyin: "chūxiàn", english: "to appear, to emerge", category: "Verb" },
  { chinese: "窗户", pinyin: "chuānghu", english: "window", category: "Noun" },
  { chinese: "从来", pinyin: "cónglái", english: "always, all along", category: "Adverb" },

  { chinese: "答案", pinyin: "dá'àn", english: "answer, key", category: "Noun" },
  { chinese: "打扰", pinyin: "dǎrǎo", english: "to disturb, to bother", category: "Verb" },
  { chinese: "打折", pinyin: "dǎ zhé", english: "to give a discount", category: "Verb" },
  { chinese: "大使馆", pinyin: "dàshǐguǎn", english: "embassy", category: "Noun" },
  { chinese: "大夫", pinyin: "dàifu", english: "doctor", category: "Noun" },
  { chinese: "当", pinyin: "dāng", english: "when, just at (a time or place)", category: "Preposition" },
  { chinese: "当时", pinyin: "dāngshí", english: "then, at that time", category: "Noun" },
  { chinese: "到处", pinyin: "dàochù", english: "everywhere", category: "Adverb" },
  { chinese: "得", pinyin: "děi", english: "must, have to", category: "Modal Verb" },
  { chinese: "等", pinyin: "děng", english: "etc., and so on", category: "Particle" },
  { chinese: "低", pinyin: "dī", english: "low", category: "Adjective" },
  { chinese: "调查", pinyin: "diàochá", english: "to survey, to investigate", category: "Verb" },
  {
    chinese: "掉",
    pinyin: "diào",
    english: "used after certain verbs, indicating the result of an action",
    category: "Verb",
  },
  { chinese: "动作", pinyin: "dòngzuò", english: "action, movement", category: "Noun" },
  { chinese: "堵车", pinyin: "dǔ chē", english: "traffic jam", category: null },
  { chinese: "肚子", pinyin: "dùzi", english: "belly, stomach", category: "Noun" },
  { chinese: "短信", pinyin: "duǎnxìn", english: "text message", category: "Noun" },

  { chinese: "而", pinyin: "ér", english: "(showing a contrast) while, yet", category: "Conjunction" },

  { chinese: "发生", pinyin: "fāshēng", english: "to happen, to take place", category: "Verb" },
  { chinese: "发展", pinyin: "fāzhǎn", english: "to develop, to promote", category: "Verb" },
  { chinese: "法律", pinyin: "fǎlǜ", english: "law", category: "Noun" },
  { chinese: "翻译", pinyin: "fānyì", english: "translator, interpreter", category: "Noun" },
  { chinese: "烦恼", pinyin: "fánnǎo", english: "worried, vexed", category: "Adjective" },
  { chinese: "反对", pinyin: "fǎnduì", english: "to oppose, to object to", category: "Verb" },
  { chinese: "方法", pinyin: "fāngfǎ", english: "method, way", category: "Noun" },
  { chinese: "方面", pinyin: "fāngmiàn", english: "aspect", category: "Noun" },
  { chinese: "方向", pinyin: "fāngxiàng", english: "direction, orientation", category: "Noun" },
  { chinese: "放弃", pinyin: "fàngqì", english: "to give up", category: "Verb" },
  { chinese: "放松", pinyin: "fàngsōng", english: "to relax", category: "Verb" },
  { chinese: "份", pinyin: "fèn", english: "used for jobs among other things", category: "Quantifier" },
  { chinese: "丰富", pinyin: "fēngfù", english: "to enrich", category: "Verb" },
  { chinese: "符合", pinyin: "fúhé", english: "to accord with", category: "Verb" },
  { chinese: "负责", pinyin: "fùzé", english: "to be in charge of", category: "Verb" },
  { chinese: "富", pinyin: "fù", english: "rich, wealthy", category: "Adjective" },

  { chinese: "改变", pinyin: "gǎibiàn", english: "to change", category: "Verb" },
  { chinese: "感动", pinyin: "gǎndòng", english: "to touch, to move", category: "Verb" },
  { chinese: "感觉", pinyin: "gǎnjué", english: "feeling", category: "Noun" },
  { chinese: "感情", pinyin: "gǎnqíng", english: "affection, love", category: "Noun" },
  { chinese: "感谢", pinyin: "gǎnxiè", english: "to thank", category: "Verb" },
  { chinese: "刚", pinyin: "gāng", english: "just, not long", category: "Adverb" },
  { chinese: "各", pinyin: "gè", english: "various, different", category: "Pronoun" },
  { chinese: "工资", pinyin: "gōngzī", english: "pay, salary", category: "Noun" },
  { chinese: "共同", pinyin: "gòngtóng", english: "common, shared", category: "Adjective" },
  { chinese: "购物", pinyin: "gòu wù", english: "to shop, to buy things", category: null },
  { chinese: "够", pinyin: "gòu", english: "to be enough", category: "Verb" },
  { chinese: "估计", pinyin: "gūjì", english: "to estimate, to reckon", category: "Verb" },
  { chinese: "顾客", pinyin: "gùkè", english: "customer, client", category: "Noun" },
  { chinese: "关键", pinyin: "guānjiàn", english: "hinge, crux", category: "Noun" },
  { chinese: "光", pinyin: "guāng", english: "only, merely", category: "Adverb" },
  { chinese: "广告", pinyin: "guǎnggào", english: "advertisement", category: "Noun" },
  { chinese: "逛", pinyin: "guàng", english: "to stroll, to roam", category: "Verb" },
  { chinese: "国际", pinyin: "guójì", english: "international", category: "Noun" },
  { chinese: "果汁", pinyin: "guǒzhī", english: "fruit juice", category: "Noun" },
  { chinese: "过程", pinyin: "guòchéng", english: "course, process", category: "Noun" },

  { chinese: "汗", pinyin: "hàn", english: "sweat, perspiration", category: "Noun" },
  { chinese: "好处", pinyin: "hǎochù", english: "benefit, advantage", category: "Noun" },
  { chinese: "好像", pinyin: "hǎoxiàng", english: "as if", category: "Adverb" },
  { chinese: "后悔", pinyin: "hòuhuǐ", english: "to regret", category: "Verb" },
  { chinese: "互相", pinyin: "hùxiāng", english: "mutually", category: "Adverb" },
  { chinese: "回忆", pinyin: "huíyì", english: "to call to mind, to recall", category: "Verb" },
  { chinese: "活动", pinyin: "huódòng", english: "activity, event", category: "Noun" },
  { chinese: "获得", pinyin: "huòdé", english: "to get, to obtain", category: "Verb" },

  { chinese: "积极", pinyin: "jījí", english: "positive", category: "Adjective" },
  { chinese: "积累", pinyin: "jīlěi", english: "to accumulate", category: "Verb" },
  { chinese: "及时", pinyin: "jíshí", english: "in time", category: "Adverb" },
  { chinese: "即使", pinyin: "jíshǐ", english: "even if", category: "Conjunction" },
  { chinese: "计划", pinyin: "jìhuà", english: "plan; to intend to", category: null },
  { chinese: "寄", pinyin: "jì", english: "to mail, to send", category: "Verb" },
  { chinese: "加班", pinyin: "jiā bān", english: "to work overtime", category: null },
  { chinese: "家具", pinyin: "jiājù", english: "furniture", category: "Noun" },
  { chinese: "价格", pinyin: "jiàgé", english: "price", category: "Noun" },
  { chinese: "坚持", pinyin: "jiānchí", english: "to insist, to persist", category: "Verb" },
  { chinese: "减肥", pinyin: "jiǎn féi", english: "to lose weight", category: null },
  { chinese: "建议", pinyin: "jiànyì", english: "suggestion, advice", category: "Noun" },
  { chinese: "将来", pinyin: "jiānglái", english: "future", category: "Noun" },
  { chinese: "奖金", pinyin: "jiǎngjīn", english: "money award, bonus", category: "Noun" },
  { chinese: "降低", pinyin: "jiàngdī", english: "to lower, to reduce", category: "Verb" },
  { chinese: "交", pinyin: "jiāo", english: "to make (friends)", category: "Verb" },
  { chinese: "交流", pinyin: "jiāoliú", english: "to exchange, to communicate", category: "Verb" },
  { chinese: "教授", pinyin: "jiàoshòu", english: "professor", category: "Noun" },
  { chinese: "接受", pinyin: "jiēshòu", english: "to accept", category: "Verb" },
  { chinese: "结果", pinyin: "jiéguǒ", english: "result", category: "Noun" },
  { chinese: "尽管", pinyin: "jǐnguǎn", english: "although", category: "Conjunction" },
  { chinese: "紧张", pinyin: "jǐnzhāng", english: "nervous", category: "Adjective" },
  { chinese: "经济", pinyin: "jīngjì", english: "economy", category: "Noun" },
  { chinese: "经历", pinyin: "jīnglì", english: "to go through, to experience", category: "Verb" },
  { chinese: "经验", pinyin: "jīngyàn", english: "experience", category: "Noun" },
  { chinese: "景色", pinyin: "jǐngsè", english: "scene, view", category: "Noun" },
  { chinese: "竟然", pinyin: "jìngrán", english: "indicating unexpectedness", category: "Adverb" },
  { chinese: "镜子", pinyin: "jìngzi", english: "mirror", category: "Noun" },
  { chinese: "举办", pinyin: "jǔbàn", english: "to hold, to conduct", category: "Verb" },
  { chinese: "举行", pinyin: "jǔxíng", english: "to hold (a meeting, event, etc.)", category: "Verb" },
  { chinese: "距离", pinyin: "jùlí", english: "distance", category: "Noun" },
  {
    chinese: "聚会",
    pinyin: "jùhuì",
    english: "to have a party; party, get-together",
    category: null,
  },

  { chinese: "开玩笑", pinyin: "kāi wánxiào", english: "to be kidding", category: null },
  { chinese: "考虑", pinyin: "kǎolǜ", english: "to consider", category: "Verb" },
  { chinese: "科学", pinyin: "kēxué", english: "science", category: "Noun" },
  { chinese: "咳嗽", pinyin: "késou", english: "to cough", category: "Verb" },
  { chinese: "可是", pinyin: "kěshì", english: "but, however", category: "Conjunction" },
  { chinese: "肯定", pinyin: "kěndìng", english: "surely, certainly", category: "Adverb" },
  { chinese: "空气", pinyin: "kōngqì", english: "air", category: "Noun" },
  { chinese: "空儿", pinyin: "kòngr", english: "free time, spare time", category: "Noun" },
  { chinese: "困", pinyin: "kùn", english: "sleepy", category: "Adjective" },
  { chinese: "困难", pinyin: "kùnnan", english: "difficulty", category: "Noun" },

  { chinese: "拉", pinyin: "lā", english: "to pull, to drag", category: "Verb" },
  {
    chinese: "来不及",
    pinyin: "láibují",
    english: "to have not enough time to, to be too late to",
    category: "Verb",
  },
  { chinese: "浪费", pinyin: "làngfèi", english: "to waste", category: "Verb" },
  { chinese: "浪漫", pinyin: "làngmàn", english: "romantic", category: "Adjective" },
  { chinese: "礼拜天", pinyin: "lǐbàitiān", english: "Sunday", category: "Noun" },
  { chinese: "理解", pinyin: "lǐjiě", english: "to understand", category: "Verb" },
  { chinese: "理想", pinyin: "lǐxiǎng", english: "ideal", category: "Noun" },
  { chinese: "例如", pinyin: "lìrú", english: "for example", category: "Verb" },
  { chinese: "俩", pinyin: "liǎ", english: "two, both", category: "Quantifier" },
  { chinese: "联系", pinyin: "liánxì", english: "to contact", category: "Verb" },
  { chinese: "另外", pinyin: "lìngwài", english: "besides, in addition", category: "Conjunction" },
  { chinese: "留", pinyin: "liú", english: "to leave", category: "Verb" },
  { chinese: "流行", pinyin: "liúxíng", english: "to be popular", category: "Verb" },
  { chinese: "律师", pinyin: "lǜshī", english: "lawyer", category: "Noun" },
  { chinese: "乱", pinyin: "luàn", english: "hurry-scurry, confused", category: "Adjective" },

  { chinese: "麻烦", pinyin: "máfan", english: "to bother", category: "Verb" },
  { chinese: "满", pinyin: "mǎn", english: "to reach a quota or limit", category: "Verb" },
  { chinese: "免费", pinyin: "miǎn fèi", english: "to be free of charge", category: "Verb" },
  { chinese: "母亲", pinyin: "mǔqīn", english: "mother", category: "Noun" },

  { chinese: "耐心", pinyin: "nàixīn", english: "patience", category: "Noun" },
  {
    chinese: "难道",
    pinyin: "nándào",
    english: "used in a rhetorical question for emphasis",
    category: "Adverb",
  },
  { chinese: "内", pinyin: "nèi", english: "in, within", category: "Noun" },
  { chinese: "能力", pinyin: "nénglì", english: "ability, competence", category: "Noun" },
  { chinese: "年龄", pinyin: "niánlíng", english: "age", category: "Noun" },

  { chinese: "判断", pinyin: "pànduàn", english: "to judge, to decide", category: "Verb" },
  { chinese: "陪", pinyin: "péi", english: "to accompany", category: "Verb" },
  { chinese: "皮肤", pinyin: "pífū", english: "skin", category: "Noun" },
  { chinese: "脾气", pinyin: "píqi", english: "temper, disposition", category: "Noun" },
  { chinese: "篇", pinyin: "piān", english: "used for writings, papers or articles", category: "Quantifier" },
  { chinese: "平时", pinyin: "píngshí", english: "normal times", category: "Noun" },
  { chinese: "葡萄", pinyin: "pútáo", english: "grape", category: "Noun" },

  { chinese: "其次", pinyin: "qícì", english: "second, next", category: "Pronoun" },
  { chinese: "其中", pinyin: "qízhōng", english: "among (which, them, etc.)", category: "Noun" },
  { chinese: "气候", pinyin: "qìhòu", english: "climate", category: "Noun" },
  { chinese: "巧克力", pinyin: "qiǎokèlì", english: "chocolate", category: "Noun" },
  { chinese: "亲戚", pinyin: "qīnqi", english: "relative, kinsfolk", category: "Noun" },
  { chinese: "轻", pinyin: "qīng", english: "light, of little weight", category: "Adjective" },
  { chinese: "轻松", pinyin: "qīngsōng", english: "relaxed, effortless", category: "Adjective" },
  { chinese: "情况", pinyin: "qíngkuàng", english: "situation, circumstances", category: "Noun" },
  { chinese: "穷", pinyin: "qióng", english: "poor, impoverished", category: "Adjective" },
  { chinese: "区别", pinyin: "qūbié", english: "difference, distinction", category: "Noun" },
  { chinese: "取", pinyin: "qǔ", english: "to gain, to seek", category: "Verb" },
  { chinese: "缺点", pinyin: "quēdiǎn", english: "shortcoming", category: "Noun" },
  { chinese: "缺少", pinyin: "quēshǎo", english: "to lack", category: "Verb" },
  { chinese: "却", pinyin: "què", english: "but, yet", category: "Adverb" },
  { chinese: "确实", pinyin: "quèshí", english: "truly, indeed", category: "Adverb" },

  { chinese: "任何", pinyin: "rènhé", english: "any, whatever", category: "Pronoun" },

  { chinese: "散步", pinyin: "sàn bù", english: "to take a walk", category: "Verb" },
  { chinese: "沙发", pinyin: "shāfā", english: "sofa", category: "Noun" },
  { chinese: "伤心", pinyin: "shāng xīn", english: "sad, sorrowful", category: "Adjective" },
  { chinese: "深", pinyin: "shēn", english: "deep", category: "Adjective" },
  { chinese: "甚至", pinyin: "shènzhì", english: "even, so far as to", category: "Conjunction" },
  { chinese: "生活", pinyin: "shēnghuó", english: "life; to live", category: null },
  { chinese: "生命", pinyin: "shēngmìng", english: "life", category: "Noun" },
  { chinese: "生意", pinyin: "shēngyi", english: "business, trade", category: "Noun" },
  { chinese: "失败", pinyin: "shībài", english: "to fail", category: "Verb" },
  {
    chinese: "师傅",
    pinyin: "shīfu",
    english: "a polite title for one with accomplished skills in a trade or handicraft",
    category: "Noun",
  },
  { chinese: "实际", pinyin: "shíjì", english: "reality", category: "Noun" },
  { chinese: "实在", pinyin: "shízài", english: "really", category: "Adverb" },
  { chinese: "使", pinyin: "shǐ", english: "to make, to cause", category: "Verb" },
  { chinese: "适合", pinyin: "shìhé", english: "to suit, to fit", category: "Verb" },
  { chinese: "适应", pinyin: "shìyìng", english: "to get used to", category: "Verb" },
  { chinese: "收入", pinyin: "shōurù", english: "income", category: "Noun" },
  { chinese: "首先", pinyin: "shǒuxiān", english: "first", category: "Pronoun" },
  { chinese: "受到", pinyin: "shòudào", english: "to receive", category: "Verb" },
  { chinese: "售货员", pinyin: "shòuhuòyuán", english: "salesperson", category: "Noun" },
  { chinese: "熟悉", pinyin: "shúxī", english: "to be familiar with", category: "Verb" },
  { chinese: "数字", pinyin: "shùzì", english: "number", category: "Noun" },
  { chinese: "帅", pinyin: "shuài", english: "handsome", category: "Adjective" },
  { chinese: "顺便", pinyin: "shùnbiàn", english: "in passing", category: "Adverb" },
  { chinese: "顺利", pinyin: "shùnlì", english: "smooth", category: "Adjective" },
  { chinese: "说明", pinyin: "shuōmíng", english: "to explain, to show", category: "Verb" },
  { chinese: "硕士", pinyin: "shuòshì", english: "Master, person who has a master's degree", category: "Noun" },
  { chinese: "随便", pinyin: "suíbiàn", english: "casual, at random", category: "Adjective" },
  { chinese: "所有", pinyin: "suǒyǒu", english: "all", category: "Adjective" },

  { chinese: "台", pinyin: "tái", english: "used for machines", category: "Quantifier" },
  { chinese: "态度", pinyin: "tàidù", english: "attitude", category: "Noun" },
  { chinese: "谈", pinyin: "tán", english: "to talk, to discuss", category: "Verb" },
  { chinese: "糖", pinyin: "táng", english: "sugar, candy", category: "Noun" },
  { chinese: "躺", pinyin: "tǎng", english: "to lie (on one's back)", category: "Verb" },
  { chinese: "讨厌", pinyin: "tǎoyàn", english: "to dislike", category: "Verb" },
  { chinese: "特点", pinyin: "tèdiǎn", english: "characteristic", category: "Noun" },
  { chinese: "提", pinyin: "tí", english: "to mention", category: "Verb" },
  { chinese: "提供", pinyin: "tígōng", english: "to provide", category: "Verb" },
  { chinese: "提前", pinyin: "tíqián", english: "to do (sth.) in advance or ahead of time", category: "Verb" },
  { chinese: "提醒", pinyin: "tí xǐng", english: "to remind", category: "Verb" },
  { chinese: "条件", pinyin: "tiáojiàn", english: "condition", category: "Noun" },
  { chinese: "挺", pinyin: "tǐng", english: "quite, rather", category: "Adverb" },
  { chinese: "通过", pinyin: "tōngguò", english: "through, by means of", category: "Preposition" },
  { chinese: "通知", pinyin: "tōngzhī", english: "to inform", category: "Verb" },

  { chinese: "袜子", pinyin: "wàzi", english: "socks", category: "Noun" },
  { chinese: "完全", pinyin: "wánquán", english: "completely", category: "Adverb" },
  { chinese: "网球", pinyin: "wǎngqiú", english: "tennis", category: "Noun" },
  { chinese: "往往", pinyin: "wǎngwǎng", english: "often, usually", category: "Adverb" },
  { chinese: "味道", pinyin: "wèidào", english: "taste", category: "Noun" },
  { chinese: "无聊", pinyin: "wúliáo", english: "boring", category: "Adjective" },

  { chinese: "西红柿", pinyin: "xīhóngshì", english: "tomato", category: "Noun" },
  { chinese: "吸引", pinyin: "xīyǐn", english: "to attract", category: "Verb" },
  { chinese: "现金", pinyin: "xiànjīn", english: "cash", category: "Noun" },
  { chinese: "羡慕", pinyin: "xiànmù", english: "to envy, to admire", category: "Verb" },
  { chinese: "橡皮", pinyin: "xiàngpí", english: "eraser, rubber", category: "Noun" },
  { chinese: "消息", pinyin: "xiāoxi", english: "news", category: "Noun" },
  { chinese: "小说", pinyin: "xiǎoshuō", english: "novel, fiction", category: "Noun" },
  { chinese: "效果", pinyin: "xiàoguǒ", english: "effect", category: "Noun" },
  { chinese: "心情", pinyin: "xīnqíng", english: "mood, state of mind", category: "Noun" },
  { chinese: "辛苦", pinyin: "xīnkǔ", english: "hard, toilsome", category: "Adjective" },
  { chinese: "信心", pinyin: "xìnxīn", english: "confidence", category: "Noun" },
  { chinese: "兴奋", pinyin: "xīngfèn", english: "excited", category: "Adjective" },
  { chinese: "幸福", pinyin: "xìngfú", english: "happy", category: "Adjective" },
  { chinese: "性格", pinyin: "xìnggé", english: "character, personality", category: "Noun" },
  { chinese: "修理", pinyin: "xiūlǐ", english: "to repair, to mend", category: "Verb" },
  { chinese: "许多", pinyin: "xǔduō", english: "many, plenty of", category: "Numeral" },

  { chinese: "压力", pinyin: "yālì", english: "pressure, stress", category: "Noun" },
  { chinese: "严重", pinyin: "yánzhòng", english: "serious, grave", category: "Adjective" },
  { chinese: "研究", pinyin: "yánjiū", english: "to study, to do research", category: "Verb" },
  { chinese: "阳光", pinyin: "yángguāng", english: "optimistic, cheerful", category: "Adjective" },
  { chinese: "样子", pinyin: "yàngzi", english: "look, appearance", category: "Noun" },
  { chinese: "邀请", pinyin: "yāoqǐng", english: "to invite", category: "Verb" },
  { chinese: "要是", pinyin: "yàoshi", english: "if, supposing", category: "Conjunction" },
  { chinese: "一切", pinyin: "yíqiè", english: "all, every", category: "Pronoun" },
  { chinese: "以为", pinyin: "yǐwéi", english: "to think, to believe", category: "Verb" },
  { chinese: "艺术", pinyin: "yìshù", english: "art", category: "Noun" },
  { chinese: "因此", pinyin: "yīncǐ", english: "therefore, so", category: "Conjunction" },
  { chinese: "印象", pinyin: "yìnxiàng", english: "impression", category: "Noun" },
  { chinese: "赢", pinyin: "yíng", english: "to win", category: "Verb" },
  { chinese: "应聘", pinyin: "yìngpìn", english: "to apply for a job", category: "Verb" },
  { chinese: "永远", pinyin: "yǒngyuǎn", english: "forever", category: "Adverb" },
  { chinese: "勇敢", pinyin: "yǒnggǎn", english: "brave, courageous", category: "Adjective" },
  { chinese: "优点", pinyin: "yōudiǎn", english: "merit", category: "Noun" },
  { chinese: "优秀", pinyin: "yōuxiù", english: "excellent, outstanding", category: "Adjective" },
  { chinese: "幽默", pinyin: "yōumò", english: "humorous", category: "Adjective" },
  { chinese: "尤其", pinyin: "yóuqí", english: "especially", category: "Adverb" },
  { chinese: "由于", pinyin: "yóuyú", english: "because, since", category: "Conjunction" },
  { chinese: "友谊", pinyin: "yǒuyì", english: "friendship", category: "Noun" },
  { chinese: "愉快", pinyin: "yúkuài", english: "glad, cheerful", category: "Adjective" },
  { chinese: "与", pinyin: "yǔ", english: "with", category: "Preposition" },
  { chinese: "原来", pinyin: "yuánlái", english: "original", category: "Adjective" },
  { chinese: "原因", pinyin: "yuányīn", english: "reason", category: "Noun" },
  { chinese: "约会", pinyin: "yuēhuì", english: "to date, to go to an appointment", category: "Verb" },

  { chinese: "咱们", pinyin: "zánmen", english: "we, us", category: "Pronoun" },
  { chinese: "暂时", pinyin: "zànshí", english: "temporary, for the time being", category: "Noun" },
  { chinese: "责任", pinyin: "zérèn", english: "responsibility, duty", category: "Noun" },
  { chinese: "招聘", pinyin: "zhāopìn", english: "to recruit", category: "Verb" },
];
