import type { CombinedVocabRow } from "./pdf-vocab-table";

// HSK4B's combined word list, transcribed directly from the "生词 New Words"
// appendix (pages 143-157) of the HSK 4 (下册) Standard Course textbook, the
// same way HSK4A's is (see hsk4a-combined-data.ts) — no PDF, no corrections
// needed.
//
// Deliberately excluded, per the same appendix: 专有名词 Proper Nouns (see
// the no-proper-nouns rule), 超纲词 Words Not Included in the Syllabus,
// 旧字新词 New Words Made Up of Characters Learned Before, and 补充
// Supplementary Vocabulary.
//
// 省 (shěng) is taught twice in this book with the same reading but two
// different senses — "province" (lesson 13, noun) and "to save, to
// economize" (lesson 14, verb) — unlike homographs such as 还 hái/huán or
// 只 zhǐ/zhī, these share both characters AND pinyin, so seed.ts's
// chinese+pinyin dedup key can't tell the two rows apart. Merged into one
// row's meaning, the same way 花 (flower; to spend) was merged for HSK3.
export const HSK4B_COMBINED_WORDS: CombinedVocabRow[] = [
  { chinese: "安全", pinyin: "ānquán", english: "safe, secure", category: "Adjective" },

  { chinese: "棒", pinyin: "bàng", english: "excellent, amazing", category: "Adjective" },
  { chinese: "包子", pinyin: "bāozi", english: "steamed stuffed bun", category: "Noun" },
  { chinese: "保护", pinyin: "bǎohù", english: "to protect", category: "Verb" },
  { chinese: "报名", pinyin: "bào míng", english: "to apply, to sign up", category: "Verb" },
  { chinese: "抱", pinyin: "bào", english: "to hold in the arms, to hug", category: "Verb" },
  { chinese: "抱歉", pinyin: "bàoqiàn", english: "to be sorry", category: "Verb" },
  { chinese: "笨", pinyin: "bèn", english: "stupid, foolish", category: "Adjective" },
  {
    chinese: "遍",
    pinyin: "biàn",
    english: "(denoting an action from beginning to end) time",
    category: "Quantifier",
  },
  { chinese: "表格", pinyin: "biǎogé", english: "form, table", category: "Noun" },
  { chinese: "表示", pinyin: "biǎoshì", english: "to express, to indicate", category: "Verb" },
  { chinese: "表演", pinyin: "biǎoyǎn", english: "to act, to perform", category: "Verb" },
  { chinese: "表扬", pinyin: "biǎoyáng", english: "to praise, to commend", category: "Verb" },
  { chinese: "并且", pinyin: "bìngqiě", english: "and", category: "Conjunction" },
  { chinese: "博士", pinyin: "bóshì", english: "doctor (academic degree)", category: "Noun" },
  { chinese: "部分", pinyin: "bùfen", english: "part", category: "Noun" },

  { chinese: "猜", pinyin: "cāi", english: "to guess", category: "Verb" },
  { chinese: "参观", pinyin: "cānguān", english: "to visit, to look around", category: "Verb" },
  { chinese: "餐厅", pinyin: "cāntīng", english: "restaurant", category: "Noun" },
  { chinese: "厕所", pinyin: "cèsuǒ", english: "lavatory, toilet", category: "Noun" },
  {
    chinese: "场",
    pinyin: "chǎng",
    english: "used for sports or recreational events, etc.",
    category: "Quantifier",
  },
  {
    chinese: "乘坐",
    pinyin: "chéngzuò",
    english: "to take (a vehicle), to ride (in a vehicle)",
    category: "Verb",
  },
  { chinese: "吃惊", pinyin: "chī jīng", english: "to be surprised, to be shocked", category: "Verb" },
  { chinese: "出差", pinyin: "chū chāi", english: "to go on a business trip", category: "Verb" },
  { chinese: "出发", pinyin: "chūfā", english: "to depart, to set off", category: "Verb" },
  { chinese: "出生", pinyin: "chūshēng", english: "to be born", category: "Verb" },
  { chinese: "厨房", pinyin: "chúfáng", english: "kitchen", category: "Noun" },
  { chinese: "传真", pinyin: "chuánzhēn", english: "to send by fax", category: "Verb" },
  { chinese: "词语", pinyin: "cíyǔ", english: "word, expression", category: "Noun" },
  { chinese: "粗心", pinyin: "cūxīn", english: "careless, thoughtless", category: "Adjective" },
  { chinese: "存", pinyin: "cún", english: "to store, to keep", category: "Verb" },
  { chinese: "错误", pinyin: "cuòwù", english: "wrong", category: "Adjective" },

  { chinese: "打扮", pinyin: "dǎbàn", english: "to dress up, to deck out", category: "Verb" },
  { chinese: "打印", pinyin: "dǎyìn", english: "to print out", category: "Verb" },
  { chinese: "打招呼", pinyin: "dǎ zhāohu", english: "to greet, to say hello", category: null },
  { chinese: "打针", pinyin: "dǎ zhēn", english: "to give or have an injection", category: null },
  { chinese: "大概", pinyin: "dàgài", english: "roughly, approximately", category: "Adverb" },
  { chinese: "大约", pinyin: "dàyuē", english: "approximately, about", category: "Adverb" },
  { chinese: "戴", pinyin: "dài", english: "to wear (accessories)", category: "Verb" },
  { chinese: "刀", pinyin: "dāo", english: "knife", category: "Noun" },
  { chinese: "导游", pinyin: "dǎoyóu", english: "tour guide", category: "Noun" },
  {
    chinese: "到底",
    pinyin: "dàodǐ",
    english: "(used in questions for emphasis) ... on earth",
    category: "Adverb",
  },
  { chinese: "倒", pinyin: "dào", english: "(used to indicate contrast) yet, actually", category: "Adverb" },
  { chinese: "道歉", pinyin: "dào qiàn", english: "to apologize", category: "Verb" },
  { chinese: "得意", pinyin: "déyì", english: "complacent, gloating", category: "Adjective" },
  { chinese: "登机牌", pinyin: "dēngjīpái", english: "boarding pass", category: "Noun" },
  { chinese: "底", pinyin: "dǐ", english: "bottom, base", category: "Noun" },
  { chinese: "地点", pinyin: "dìdiǎn", english: "place, site", category: "Noun" },
  { chinese: "地球", pinyin: "dìqiú", english: "earth, globe", category: "Noun" },
  { chinese: "地址", pinyin: "dìzhǐ", english: "address", category: "Noun" },
  { chinese: "丢", pinyin: "diū", english: "to throw, to cast", category: "Verb" },
  { chinese: "对话", pinyin: "duìhuà", english: "to have a dialogue", category: "Verb" },
  { chinese: "对面", pinyin: "duìmiàn", english: "opposite, across", category: "Noun" },
  { chinese: "对于", pinyin: "duìyú", english: "for, to, with regard to", category: "Preposition" },

  { chinese: "儿童", pinyin: "értóng", english: "children", category: "Noun" },

  { chinese: "房东", pinyin: "fángdōng", english: "landlord/landlady", category: "Noun" },
  { chinese: "放暑假", pinyin: "fàng shǔjià", english: "to be on summer vacation", category: null },
  { chinese: "否则", pinyin: "fǒuzé", english: "or, otherwise", category: "Conjunction" },
  { chinese: "父亲", pinyin: "fùqīn", english: "father", category: "Noun" },
  { chinese: "付款", pinyin: "fù kuǎn", english: "to pay a sum of money", category: null },
  { chinese: "复印", pinyin: "fùyìn", english: "to photocopy, to xerox", category: "Verb" },
  { chinese: "复杂", pinyin: "fùzá", english: "complicated", category: "Adjective" },

  { chinese: "干杯", pinyin: "gān bēi", english: "to drink a toast", category: "Verb" },
  { chinese: "赶", pinyin: "gǎn", english: "to rush for, to hurry", category: "Verb" },
  { chinese: "敢", pinyin: "gǎn", english: "to dare", category: "Verb" },
  { chinese: "干", pinyin: "gàn", english: "to do, to act", category: "Verb" },
  { chinese: "高速公路", pinyin: "gāosù gōnglù", english: "expressway", category: null },
  { chinese: "胳膊", pinyin: "gēbo", english: "arm", category: "Noun" },
  { chinese: "公里", pinyin: "gōnglǐ", english: "kilometer", category: "Quantifier" },
  { chinese: "功夫", pinyin: "gōngfu", english: "kung fu", category: "Noun" },
  { chinese: "鼓励", pinyin: "gǔlì", english: "to encourage", category: "Verb" },
  { chinese: "故意", pinyin: "gùyì", english: "intentionally, on purpose", category: "Adverb" },
  { chinese: "挂", pinyin: "guà", english: "to hang, to put up", category: "Verb" },
  { chinese: "观众", pinyin: "guānzhòng", english: "audience", category: "Noun" },
  { chinese: "管理", pinyin: "guǎnlǐ", english: "to manage, to administer", category: "Verb" },
  { chinese: "广播", pinyin: "guǎngbō", english: "broadcast, radio program", category: "Noun" },
  { chinese: "规定", pinyin: "guīdìng", english: "rule, regulation", category: "Noun" },
  { chinese: "国籍", pinyin: "guójí", english: "nationality, citizenship", category: "Noun" },

  { chinese: "海洋", pinyin: "hǎiyáng", english: "sea, ocean", category: "Noun" },
  { chinese: "害羞", pinyin: "hàixiū", english: "to be shy, to be timid", category: "Verb" },
  { chinese: "寒假", pinyin: "hánjià", english: "winter vacation", category: "Noun" },
  { chinese: "航班", pinyin: "hángbān", english: "scheduled flight", category: "Noun" },
  { chinese: "号码", pinyin: "hàomǎ", english: "number", category: "Noun" },
  { chinese: "合格", pinyin: "hégé", english: "qualified, up to standard", category: "Adjective" },
  { chinese: "合适", pinyin: "héshì", english: "fit, suitable", category: "Adjective" },
  { chinese: "盒子", pinyin: "hézi", english: "box, case", category: "Noun" },
  { chinese: "厚", pinyin: "hòu", english: "deep, profound", category: "Adjective" },
  { chinese: "互联网", pinyin: "hùliánwǎng", english: "Internet", category: "Noun" },
  { chinese: "护士", pinyin: "hùshi", english: "nurse", category: "Noun" },
  { chinese: "怀疑", pinyin: "huáiyí", english: "to suspect, to doubt", category: "Verb" },
  { chinese: "活泼", pinyin: "huópō", english: "lively, vivacious", category: "Adjective" },
  { chinese: "火", pinyin: "huǒ", english: "hot, popular", category: "Adjective" },

  { chinese: "基础", pinyin: "jīchǔ", english: "basis, foundation", category: "Noun" },
  { chinese: "激动", pinyin: "jīdòng", english: "excited, emotional", category: "Adjective" },
  { chinese: "记者", pinyin: "jìzhě", english: "journalist, reporter", category: "Noun" },
  { chinese: "技术", pinyin: "jìshù", english: "technology", category: "Noun" },
  { chinese: "既然", pinyin: "jìrán", english: "since, as, now that", category: "Conjunction" },
  { chinese: "继续", pinyin: "jìxù", english: "to go on, to continue", category: "Verb" },
  { chinese: "加油站", pinyin: "jiāyóuzhàn", english: "gas station", category: "Noun" },
  { chinese: "假", pinyin: "jiǎ", english: "false, fake", category: "Adjective" },
  { chinese: "减少", pinyin: "jiǎnshǎo", english: "to reduce, to decrease", category: "Verb" },
  { chinese: "降落", pinyin: "jiàngluò", english: "to descend, to land", category: "Verb" },
  { chinese: "交通", pinyin: "jiāotōng", english: "traffic, communication", category: "Noun" },
  { chinese: "郊区", pinyin: "jiāoqū", english: "suburb, outskirts", category: "Noun" },
  { chinese: "骄傲", pinyin: "jiāo'ào", english: "arrogant, conceited", category: "Adjective" },
  { chinese: "饺子", pinyin: "jiǎozi", english: "jiaozi, dumpling", category: "Noun" },
  { chinese: "教育", pinyin: "jiàoyù", english: "to educate", category: "Verb" },
  { chinese: "接着", pinyin: "jiēzhe", english: "then, immediately after that", category: "Adverb" },
  { chinese: "节", pinyin: "jié", english: "section, length", category: "Quantifier" },
  { chinese: "节约", pinyin: "jiéyuē", english: "to economize, to save", category: "Verb" },
  { chinese: "解释", pinyin: "jiěshì", english: "to explain", category: "Verb" },
  { chinese: "进行", pinyin: "jìnxíng", english: "to conduct, to carry out", category: "Verb" },
  { chinese: "禁止", pinyin: "jìnzhǐ", english: "to prohibit, to forbid", category: "Verb" },
  { chinese: "京剧", pinyin: "jīngjù", english: "Beijing opera", category: "Noun" },
  { chinese: "精彩", pinyin: "jīngcǎi", english: "wonderful, splendid", category: "Adjective" },
  { chinese: "警察", pinyin: "jǐngchá", english: "police", category: "Noun" },
  { chinese: "竞争", pinyin: "jìngzhēng", english: "to compete", category: "Verb" },
  {
    chinese: "究竟",
    pinyin: "jiūjìng",
    english: "(used in questions for emphasis) exactly",
    category: "Adverb",
  },
  { chinese: "举", pinyin: "jǔ", english: "to give, to enumerate", category: "Verb" },
  { chinese: "拒绝", pinyin: "jùjué", english: "to refuse, to reject", category: "Verb" },

  { chinese: "开心", pinyin: "kāixīn", english: "happy, glad", category: "Adjective" },
  { chinese: "看法", pinyin: "kànfǎ", english: "viewpoint, opinion", category: "Noun" },
  { chinese: "烤鸭", pinyin: "kǎoyā", english: "roast duck", category: "Noun" },
  { chinese: "棵", pinyin: "kē", english: "used for plants", category: "Quantifier" },
  { chinese: "可怜", pinyin: "kělián", english: "pitiable, poor", category: "Adjective" },
  { chinese: "可惜", pinyin: "kěxī", english: "pitiful, regretful", category: "Adjective" },
  { chinese: "客厅", pinyin: "kètīng", english: "living room", category: "Noun" },
  { chinese: "空", pinyin: "kōng", english: "empty", category: "Adjective" },
  {
    chinese: "恐怕",
    pinyin: "kǒngpà",
    english: "(indicating an estimation) I guess...",
    category: "Adverb",
  },
  { chinese: "苦", pinyin: "kǔ", english: "bitter", category: "Adjective" },
  { chinese: "矿泉水", pinyin: "kuàngquánshuǐ", english: "mineral water", category: "Noun" },

  { chinese: "垃圾桶", pinyin: "lājītǒng", english: "dustbin, trash can", category: "Noun" },
  { chinese: "辣", pinyin: "là", english: "hot, spicy", category: "Adjective" },
  { chinese: "来得及", pinyin: "láidejí", english: "there's still time (to do sth.)", category: "Verb" },
  { chinese: "来自", pinyin: "láizì", english: "to be from", category: "Verb" },
  { chinese: "懒", pinyin: "lǎn", english: "lazy", category: "Adjective" },
  { chinese: "老虎", pinyin: "lǎohǔ", english: "tiger", category: "Noun" },
  { chinese: "冷静", pinyin: "lěngjìng", english: "calm, composed", category: "Adjective" },
  { chinese: "礼貌", pinyin: "lǐmào", english: "polite", category: "Noun" },
  { chinese: "理发", pinyin: "lǐ fà", english: "to get a haircut", category: null },
  { chinese: "力气", pinyin: "lìqi", english: "physical strength, effort", category: "Noun" },
  { chinese: "厉害", pinyin: "lìhai", english: "awesome, serious", category: "Adjective" },
  { chinese: "连", pinyin: "lián", english: "even", category: "Preposition" },
  { chinese: "凉快", pinyin: "liángkuai", english: "pleasantly cool", category: "Adjective" },
  { chinese: "零钱", pinyin: "língqián", english: "small change", category: "Noun" },
  { chinese: "流利", pinyin: "liúlì", english: "fluent", category: "Adjective" },
  { chinese: "旅行", pinyin: "lǚxíng", english: "to travel, to tour", category: "Verb" },

  { chinese: "马虎", pinyin: "mǎhu", english: "careless, slipshod", category: "Adjective" },
  { chinese: "毛", pinyin: "máo", english: "hair, fur", category: "Noun" },
  { chinese: "毛巾", pinyin: "máojīn", english: "towel", category: "Noun" },
  { chinese: "美丽", pinyin: "měilì", english: "beautiful", category: "Adjective" },
  { chinese: "梦", pinyin: "mèng", english: "dream", category: "Noun" },
  { chinese: "迷路", pinyin: "mí lù", english: "to lose one's way", category: "Verb" },
  { chinese: "密码", pinyin: "mìmǎ", english: "password", category: "Noun" },
  { chinese: "秒", pinyin: "miǎo", english: "second, 1/60 minute", category: "Quantifier" },
  { chinese: "民族", pinyin: "mínzú", english: "nationality, ethnic group", category: "Noun" },
  { chinese: "目的", pinyin: "mùdì", english: "aim, purpose", category: "Noun" },

  { chinese: "难受", pinyin: "nánshòu", english: "sad, unhappy", category: "Adjective" },
  { chinese: "内容", pinyin: "nèiróng", english: "content", category: "Noun" },
  { chinese: "弄", pinyin: "nòng", english: "to do, to make", category: "Verb" },
  { chinese: "暖", pinyin: "nuǎn", english: "warm", category: "Adjective" },
  { chinese: "暖和", pinyin: "nuǎnhuo", english: "warm", category: "Adjective" },

  { chinese: "偶尔", pinyin: "ǒu'ěr", english: "occasionally, once in a while", category: "Adverb" },

  { chinese: "排队", pinyin: "pái duì", english: "to form a line, to line up", category: "Verb" },
  { chinese: "排列", pinyin: "páiliè", english: "to put in order, to arrange", category: "Verb" },
  { chinese: "批评", pinyin: "pīpíng", english: "to criticize", category: "Verb" },
  { chinese: "骗", pinyin: "piàn", english: "to cheat, to deceive", category: "Verb" },
  { chinese: "乒乓球", pinyin: "pīngpāngqiú", english: "table tennis, ping-pong", category: "Noun" },
  { chinese: "破", pinyin: "pò", english: "broken, torn", category: "Adjective" },
  { chinese: "普遍", pinyin: "pǔbiàn", english: "universal, common", category: "Adjective" },
  { chinese: "普通话", pinyin: "pǔtōnghuà", english: "Mandarin Chinese", category: "Noun" },

  { chinese: "千万", pinyin: "qiānwàn", english: "must, to be sure to", category: "Adverb" },
  { chinese: "签证", pinyin: "qiānzhèng", english: "visa", category: "Noun" },
  { chinese: "敲", pinyin: "qiāo", english: "to knock, to beat, to strike", category: "Verb" },
  { chinese: "桥", pinyin: "qiáo", english: "bridge", category: "Noun" },
  { chinese: "全部", pinyin: "quánbù", english: "all, whole", category: "Noun" },

  { chinese: "然而", pinyin: "rán'ér", english: "but, however", category: "Conjunction" },
  { chinese: "热闹", pinyin: "rènao", english: "busy, bustling", category: "Adjective" },
  { chinese: "任务", pinyin: "rènwu", english: "task, mission", category: "Noun" },
  { chinese: "扔", pinyin: "rēng", english: "to throw away", category: "Verb" },
  { chinese: "仍然", pinyin: "réngrán", english: "still, yet", category: "Adverb" },
  { chinese: "日记", pinyin: "rìjì", english: "diary, journal", category: "Noun" },
  { chinese: "入口", pinyin: "rùkǒu", english: "entrance", category: "Noun" },

  { chinese: "森林", pinyin: "sēnlín", english: "forest", category: "Noun" },
  { chinese: "商量", pinyin: "shāngliang", english: "to discuss, to consult", category: "Verb" },
  { chinese: "稍微", pinyin: "shāowēi", english: "a little, slightly", category: "Adverb" },
  { chinese: "勺(子)", pinyin: "sháo(zi)", english: "spoon", category: "Noun" },
  { chinese: "社会", pinyin: "shèhuì", english: "society", category: "Noun" },
  { chinese: "申请", pinyin: "shēnqǐng", english: "to apply for", category: "Verb" },
  {
    chinese: "省",
    pinyin: "shěng",
    english: "province; to save, to economize",
    category: null,
  },
  { chinese: "剩", pinyin: "shèng", english: "to be left over, to remain", category: "Verb" },
  { chinese: "失望", pinyin: "shīwàng", english: "disappointed", category: "Verb" },
  { chinese: "十分", pinyin: "shífēn", english: "very, extremely", category: "Adverb" },
  { chinese: "使用", pinyin: "shǐyòng", english: "to use", category: "Verb" },
  { chinese: "世纪", pinyin: "shìjì", english: "century", category: "Noun" },
  { chinese: "是否", pinyin: "shìfǒu", english: "if, whether", category: "Adverb" },
  { chinese: "收", pinyin: "shōu", english: "to receive", category: "Verb" },
  { chinese: "收拾", pinyin: "shōushi", english: "to put in order, to pack", category: "Verb" },
  { chinese: "首都", pinyin: "shǒudū", english: "capital (of a country)", category: "Noun" },
  { chinese: "受不了", pinyin: "shòubùliǎo", english: "cannot stand, cannot bear", category: null },
  { chinese: "输", pinyin: "shū", english: "to lose, to suffer defeat", category: "Verb" },
  { chinese: "数量", pinyin: "shùliàng", english: "quantity, amount", category: "Noun" },
  { chinese: "顺序", pinyin: "shùnxù", english: "order, sequence", category: "Noun" },
  { chinese: "死", pinyin: "sǐ", english: "rigid, inflexible", category: "Adjective" },
  { chinese: "速度", pinyin: "sùdù", english: "speed", category: "Noun" },
  { chinese: "塑料袋", pinyin: "sùliàodài", english: "plastic bag", category: "Noun" },
  { chinese: "酸", pinyin: "suān", english: "sour, tart", category: "Adjective" },
  { chinese: "随着", pinyin: "suízhe", english: "along with, as", category: "Preposition" },
  { chinese: "孙子", pinyin: "sūnzi", english: "grandson", category: "Noun" },

  { chinese: "抬", pinyin: "tái", english: "to lift, to raise", category: "Verb" },
  { chinese: "弹钢琴", pinyin: "tán gāngqín", english: "to play the piano", category: null },
  { chinese: "汤", pinyin: "tāng", english: "soup", category: "Noun" },
  { chinese: "趟", pinyin: "tàng", english: "(used for a round trip) time", category: "Quantifier" },
  { chinese: "讨论", pinyin: "tǎolùn", english: "to discuss, to talk over", category: "Verb" },
  { chinese: "填空", pinyin: "tián kòng", english: "to fill in a blank", category: "Verb" },
  { chinese: "停", pinyin: "tíng", english: "to stop, to cease", category: "Verb" },
  { chinese: "同情", pinyin: "tóngqíng", english: "to show sympathy for", category: "Verb" },
  { chinese: "同时", pinyin: "tóngshí", english: "at the same time, meanwhile", category: "Conjunction" },
  { chinese: "推", pinyin: "tuī", english: "to put off, to postpone", category: "Verb" },
  { chinese: "推迟", pinyin: "tuīchí", english: "to postpone, to delay", category: "Verb" },
  { chinese: "脱", pinyin: "tuō", english: "to take off", category: "Verb" },

  { chinese: "网站", pinyin: "wǎngzhàn", english: "website", category: "Noun" },
  { chinese: "危险", pinyin: "wēixiǎn", english: "dangerous", category: "Adjective" },
  { chinese: "卫生间", pinyin: "wèishēngjiān", english: "restroom, bathroom", category: "Noun" },
  { chinese: "温度", pinyin: "wēndù", english: "temperature", category: "Noun" },
  { chinese: "文章", pinyin: "wénzhāng", english: "essay, article", category: "Noun" },
  { chinese: "污染", pinyin: "wūrǎn", english: "to pollute", category: "Verb" },
  { chinese: "无", pinyin: "wú", english: "not to have, to be without", category: "Verb" },
  { chinese: "无法", pinyin: "wúfǎ", english: "cannot, to be unable (to do sth.)", category: "Verb" },
  {
    chinese: "无论",
    pinyin: "wúlùn",
    english: "regardless of, no matter (what, how, when, etc.)",
    category: "Conjunction",
  },
  { chinese: "误会", pinyin: "wùhuì", english: "misunderstanding", category: "Noun" },

  { chinese: "咸", pinyin: "xián", english: "salty", category: "Adjective" },
  { chinese: "相反", pinyin: "xiāngfǎn", english: "on the contrary", category: "Conjunction" },
  { chinese: "相同", pinyin: "xiāngtóng", english: "same", category: "Adjective" },
  { chinese: "香", pinyin: "xiāng", english: "fragrant, scented", category: "Adjective" },
  { chinese: "详细", pinyin: "xiángxì", english: "detailed", category: "Adjective" },
  { chinese: "响", pinyin: "xiǎng", english: "to sound, to ring", category: "Verb" },
  { chinese: "小吃", pinyin: "xiǎochī", english: "small and cheap dishes", category: "Noun" },
  { chinese: "小伙子", pinyin: "xiǎohuǒzi", english: "young man", category: "Noun" },
  { chinese: "笑话", pinyin: "xiàohua", english: "joke", category: "Noun" },
  { chinese: "允许", pinyin: "yǔnxǔ", english: "to allow, to permit", category: "Verb" },

  { chinese: "杂志", pinyin: "zázhì", english: "magazine", category: "Noun" },
  { chinese: "脏", pinyin: "zāng", english: "dirty", category: "Adjective" },
  { chinese: "增加", pinyin: "zēngjiā", english: "to increase, to add", category: "Verb" },
  {
    chinese: "占线",
    pinyin: "zhànxiàn",
    english: "(of a telephone line) to be busy, to be engaged",
    category: "Verb",
  },
  { chinese: "照", pinyin: "zhào", english: "to take a picture, to photograph", category: "Verb" },
  { chinese: "整理", pinyin: "zhěnglǐ", english: "to tidy up, to arrange", category: "Verb" },
  { chinese: "正常", pinyin: "zhèngcháng", english: "normal, regular", category: "Adjective" },
  {
    chinese: "之",
    pinyin: "zhī",
    english: "connecting the modifier and the word modified",
    category: "Particle",
  },
  { chinese: "直接", pinyin: "zhíjiē", english: "direct, straight", category: "Adjective" },
  { chinese: "只好", pinyin: "zhǐhǎo", english: "cannot but, to be forced to", category: "Adverb" },
  { chinese: "纸袋", pinyin: "zhǐdài", english: "paper bag", category: "Noun" },
  { chinese: "重", pinyin: "zhòng", english: "heavy, weighty", category: "Adjective" },
  { chinese: "重点", pinyin: "zhòngdiǎn", english: "focal point, emphasis", category: "Noun" },
  { chinese: "重视", pinyin: "zhòngshì", english: "to attach importance to", category: "Verb" },
  { chinese: "祝贺", pinyin: "zhùhè", english: "to congratulate", category: "Verb" },
  { chinese: "著名", pinyin: "zhùmíng", english: "famous, well-known", category: "Adjective" },
  { chinese: "转", pinyin: "zhuàn", english: "to turn, to shift", category: "Verb" },
  { chinese: "准确", pinyin: "zhǔnquè", english: "accurate, precise", category: "Adjective" },
  { chinese: "仔细", pinyin: "zǐxì", english: "careful, meticulous", category: "Adjective" },
  { chinese: "自信", pinyin: "zìxìn", english: "self-confident", category: "Adjective" },
  { chinese: "租", pinyin: "zū", english: "to rent, to lease", category: "Verb" },
  { chinese: "尊重", pinyin: "zūnzhòng", english: "to respect", category: "Verb" },
  { chinese: "左右", pinyin: "zuǒyòu", english: "around, or so", category: "Noun" },
  { chinese: "作用", pinyin: "zuòyòng", english: "function", category: "Noun" },
  { chinese: "作者", pinyin: "zuòzhě", english: "author", category: "Noun" },
  {
    chinese: "座",
    pinyin: "zuò",
    english: "used for bridges, mountains, buildings, etc.",
    category: "Quantifier",
  },
  { chinese: "座位", pinyin: "zuòwèi", english: "seat", category: "Noun" },
];
