// HSK4B's per-lesson chapter data, transcribed directly from Part 1 of the
// HSK 4 (下册) Standard Course textbook's "生词 New Words" lists, the same
// way HSK4A's is (see hsk4a-chapters-data.ts). Each lesson's 专有名词 Proper
// Nouns section is deliberately excluded — see the no-proper-nouns rule in
// project memory.
//
// chapterNumber follows the textbook's own continuous lesson numbering
// (11-20, picking up where HSK4A's tenth lesson left off) rather than
// restarting at 1, so the in-app "Lesson N" title matches what's printed in
// the physical book.
export interface Hsk4bWordData {
  chinese: string;
  pinyin: string;
  wordType: string | null;
  meaning: string;
}

export interface Hsk4bChapterData {
  chapterNumber: number;
  words: Hsk4bWordData[];
}

export const HSK4B_CHAPTERS: Hsk4bChapterData[] = [
  {
    chapterNumber: 11,
    words: [
      { chinese: "流利", pinyin: "liúlì", wordType: "adj.", meaning: "fluent" },
      { chinese: "厉害", pinyin: "lìhai", wordType: "adj.", meaning: "awesome, serious" },
      { chinese: "语法", pinyin: "yǔfǎ", wordType: "n.", meaning: "grammar" },
      { chinese: "准确", pinyin: "zhǔnquè", wordType: "adj.", meaning: "accurate, precise" },
      { chinese: "词语", pinyin: "cíyǔ", wordType: "n.", meaning: "word, expression" },
      { chinese: "连", pinyin: "lián", wordType: "prep.", meaning: "even" },
      { chinese: "阅读", pinyin: "yuèdú", wordType: "v.", meaning: "to read" },
      { chinese: "来得及", pinyin: "láidejí", wordType: "v.", meaning: "there's still time (to do sth.)" },
      { chinese: "复杂", pinyin: "fùzá", wordType: "adj.", meaning: "complicated" },
      { chinese: "只好", pinyin: "zhǐhǎo", wordType: "adv.", meaning: "cannot but, to be forced to" },
      { chinese: "填空", pinyin: "tián kòng", wordType: "v.", meaning: "to fill in a blank" },
      { chinese: "猜", pinyin: "cāi", wordType: "v.", meaning: "to guess" },
      { chinese: "否则", pinyin: "fǒuzé", wordType: "conj.", meaning: "or, otherwise" },
      { chinese: "客厅", pinyin: "kètīng", wordType: "n.", meaning: "living room" },
      {
        chinese: "无论",
        pinyin: "wúlùn",
        wordType: "conj.",
        meaning: "regardless of, no matter (what, how, when, etc.)",
      },
      { chinese: "杂志", pinyin: "zázhì", wordType: "n.", meaning: "magazine" },
      { chinese: "著名", pinyin: "zhùmíng", wordType: "adj.", meaning: "famous, well-known" },
      { chinese: "页", pinyin: "yè", wordType: "m.", meaning: "page" },
      { chinese: "增加", pinyin: "zēngjiā", wordType: "v.", meaning: "to increase, to add" },
      { chinese: "文章", pinyin: "wénzhāng", wordType: "n.", meaning: "essay, article" },
      {
        chinese: "之",
        pinyin: "zhī",
        wordType: "part.",
        meaning: "connecting the modifier and the word modified",
      },
      { chinese: "内容", pinyin: "nèiróng", wordType: "n.", meaning: "content" },
      { chinese: "然而", pinyin: "rán'ér", wordType: "conj.", meaning: "but, however" },
      { chinese: "看法", pinyin: "kànfǎ", wordType: "n.", meaning: "viewpoint, opinion" },
      { chinese: "相同", pinyin: "xiāngtóng", wordType: "adj.", meaning: "same" },
      { chinese: "顺序", pinyin: "shùnxù", wordType: "n.", meaning: "order, sequence" },
      { chinese: "表示", pinyin: "biǎoshì", wordType: "v.", meaning: "to express, to indicate" },
      { chinese: "养成", pinyin: "yǎngchéng", wordType: "v.", meaning: "to develop, to form" },
      { chinese: "同时", pinyin: "tóngshí", wordType: "conj.", meaning: "at the same time, meanwhile" },
      { chinese: "精彩", pinyin: "jīngcǎi", wordType: "adj.", meaning: "wonderful, splendid" },
    ],
  },
  {
    chapterNumber: 12,
    words: [
      { chinese: "规定", pinyin: "guīdìng", wordType: "n.", meaning: "rule, regulation" },
      { chinese: "死", pinyin: "sǐ", wordType: "adj.", meaning: "rigid, inflexible" },
      { chinese: "可惜", pinyin: "kěxī", wordType: "adj.", meaning: "pitiful, regretful" },
      { chinese: "全部", pinyin: "quánbù", wordType: "n.", meaning: "all, whole" },
      { chinese: "也许", pinyin: "yěxǔ", wordType: "adv.", meaning: "maybe, perhaps" },
      { chinese: "商量", pinyin: "shāngliang", wordType: "v.", meaning: "to discuss, to consult" },
      { chinese: "并且", pinyin: "bìngqiě", wordType: "conj.", meaning: "and" },
      { chinese: "盐", pinyin: "yán", wordType: "n.", meaning: "salt" },
      { chinese: "勺(子)", pinyin: "sháo(zi)", wordType: "n.", meaning: "spoon" },
      { chinese: "保护", pinyin: "bǎohù", wordType: "v.", meaning: "to protect" },
      { chinese: "作用", pinyin: "zuòyòng", wordType: "n.", meaning: "function" },
      { chinese: "无法", pinyin: "wúfǎ", wordType: "v.", meaning: "cannot, to be unable (to do sth.)" },
      { chinese: "无", pinyin: "wú", wordType: "v.", meaning: "not to have, to be without" },
      { chinese: "节", pinyin: "jié", wordType: "m.", meaning: "section, length" },
      { chinese: "详细", pinyin: "xiángxì", wordType: "adj.", meaning: "detailed" },
      { chinese: "解释", pinyin: "jiěshì", wordType: "v.", meaning: "to explain" },
      { chinese: "对于", pinyin: "duìyú", wordType: "prep.", meaning: "for, to, with regard to" },
      { chinese: "叶子", pinyin: "yèzi", wordType: "n.", meaning: "leaf" },
      { chinese: "教育", pinyin: "jiàoyù", wordType: "v.", meaning: "to educate" },
      { chinese: "使用", pinyin: "shǐyòng", wordType: "v.", meaning: "to use" },
      { chinese: "语言", pinyin: "yǔyán", wordType: "n.", meaning: "language" },
      { chinese: "直接", pinyin: "zhíjiē", wordType: "adj.", meaning: "direct, straight" },
      { chinese: "引起", pinyin: "yǐnqǐ", wordType: "v.", meaning: "to cause, to lead to" },
      { chinese: "误会", pinyin: "wùhuì", wordType: "n.", meaning: "misunderstanding" },
      { chinese: "友好", pinyin: "yǒuhǎo", wordType: "adj.", meaning: "friendly" },
      {
        chinese: "事半功倍",
        pinyin: "shì bàn gōng bèi",
        wordType: null,
        meaning: "to achieve twice the result with half the effort",
      },
      { chinese: "节约", pinyin: "jiéyuē", wordType: "v.", meaning: "to economize, to save" },
      { chinese: "力气", pinyin: "lìqi", wordType: "n.", meaning: "physical strength, effort" },
      { chinese: "相反", pinyin: "xiāngfǎn", wordType: "conj.", meaning: "on the contrary" },
      { chinese: "任务", pinyin: "rènwu", wordType: "n.", meaning: "task, mission" },
      { chinese: "意见", pinyin: "yìjiàn", wordType: "n.", meaning: "opinion, suggestion" },
      { chinese: "仔细", pinyin: "zǐxì", wordType: "adj.", meaning: "careful, meticulous" },
      { chinese: "达到", pinyin: "dádào", wordType: "v.", meaning: "to reach, to attain" },
    ],
  },
  {
    chapterNumber: 13,
    words: [
      { chinese: "京剧", pinyin: "jīngjù", wordType: "n.", meaning: "Beijing opera" },
      { chinese: "演员", pinyin: "yǎnyuán", wordType: "n.", meaning: "actor/actress" },
      { chinese: "观众", pinyin: "guānzhòng", wordType: "n.", meaning: "audience" },
      { chinese: "厚", pinyin: "hòu", wordType: "adj.", meaning: "deep, profound" },
      { chinese: "演出", pinyin: "yǎnchū", wordType: "v.", meaning: "to perform, to put on (a show)" },
      { chinese: "大概", pinyin: "dàgài", wordType: "adv.", meaning: "roughly, approximately" },
      { chinese: "来自", pinyin: "láizì", wordType: "v.", meaning: "to be from" },
      {
        chinese: "遍",
        pinyin: "biàn",
        wordType: "m.",
        meaning: "(denoting an action from beginning to end) time",
      },
      { chinese: "偶尔", pinyin: "ǒu'ěr", wordType: "adv.", meaning: "occasionally, once in a while" },
      { chinese: "吃惊", pinyin: "chī jīng", wordType: "v.", meaning: "to be surprised, to be shocked" },
      { chinese: "基础", pinyin: "jīchǔ", wordType: "n.", meaning: "basis, foundation" },
      { chinese: "表演", pinyin: "biǎoyǎn", wordType: "v.", meaning: "to act, to perform" },
      { chinese: "正常", pinyin: "zhèngcháng", wordType: "adj.", meaning: "normal, regular" },
      { chinese: "申请", pinyin: "shēnqǐng", wordType: "v.", meaning: "to apply for" },
      { chinese: "有趣", pinyin: "yǒuqù", wordType: "adj.", meaning: "interesting, fun" },
      { chinese: "开心", pinyin: "kāixīn", wordType: "adj.", meaning: "happy, glad" },
      { chinese: "继续", pinyin: "jìxù", wordType: "v.", meaning: "to go on, to continue" },
      { chinese: "由", pinyin: "yóu", wordType: "prep.", meaning: "by (sb.)" },
      { chinese: "讨论", pinyin: "tǎolùn", wordType: "v.", meaning: "to discuss, to talk over" },
      { chinese: "大约", pinyin: "dàyuē", wordType: "adv.", meaning: "approximately, about" },
      { chinese: "餐厅", pinyin: "cāntīng", wordType: "n.", meaning: "restaurant" },
      { chinese: "纸袋", pinyin: "zhǐdài", wordType: "n.", meaning: "paper bag" },
      { chinese: "袋(子)", pinyin: "dài(zi)", wordType: "n.", meaning: "bag, sack" },
      { chinese: "互联网", pinyin: "hùliánwǎng", wordType: "n.", meaning: "Internet" },
      { chinese: "进行", pinyin: "jìnxíng", wordType: "v.", meaning: "to conduct, to carry out" },
      { chinese: "错误", pinyin: "cuòwù", wordType: "adj.", meaning: "wrong" },
      { chinese: "随着", pinyin: "suízhe", wordType: "prep.", meaning: "along with, as" },
      { chinese: "十分", pinyin: "shífēn", wordType: "adv.", meaning: "very, extremely" },
      { chinese: "普遍", pinyin: "pǔbiàn", wordType: "adj.", meaning: "universal, common" },
      { chinese: "部分", pinyin: "bùfen", wordType: "n.", meaning: "part" },
      { chinese: "稍微", pinyin: "shāowēi", wordType: "adv.", meaning: "a little, slightly" },
      { chinese: "苦", pinyin: "kǔ", wordType: "adj.", meaning: "bitter" },
      { chinese: "省", pinyin: "shěng", wordType: "n.", meaning: "province" },
    ],
  },
  {
    chapterNumber: 14,
    words: [
      { chinese: "出差", pinyin: "chū chāi", wordType: "v.", meaning: "to go on a business trip" },
      { chinese: "毛巾", pinyin: "máojīn", wordType: "n.", meaning: "towel" },
      { chinese: "牙膏", pinyin: "yágāo", wordType: "n.", meaning: "toothpaste" },
      { chinese: "重", pinyin: "zhòng", wordType: "adj.", meaning: "heavy, weighty" },
      { chinese: "行", pinyin: "xíng", wordType: "v.", meaning: "to be OK, to be all right" },
      { chinese: "省", pinyin: "shěng", wordType: "v.", meaning: "to save, to economize" },
      { chinese: "污染", pinyin: "wūrǎn", wordType: "v.", meaning: "to pollute" },
      { chinese: "卫生间", pinyin: "wèishēngjiān", wordType: "n.", meaning: "restroom, bathroom" },
      { chinese: "脏", pinyin: "zāng", wordType: "adj.", meaning: "dirty" },
      { chinese: "抱歉", pinyin: "bàoqiàn", wordType: "v.", meaning: "to be sorry" },
      { chinese: "空", pinyin: "kōng", wordType: "adj.", meaning: "empty" },
      { chinese: "盒子", pinyin: "hézi", wordType: "n.", meaning: "box, case" },
      { chinese: "扔", pinyin: "rēng", wordType: "v.", meaning: "to throw away" },
      { chinese: "以", pinyin: "yǐ", wordType: "prep.", meaning: "via, by means of" },
      { chinese: "速度", pinyin: "sùdù", wordType: "n.", meaning: "speed" },
      { chinese: "地球", pinyin: "dìqiú", wordType: "n.", meaning: "earth, globe" },
      { chinese: "既然", pinyin: "jìrán", wordType: "conj.", meaning: "since, as, now that" },
      { chinese: "停", pinyin: "tíng", wordType: "v.", meaning: "to stop, to cease" },
      { chinese: "得意", pinyin: "déyì", wordType: "adj.", meaning: "complacent, gloating" },
      { chinese: "目的", pinyin: "mùdì", wordType: "n.", meaning: "aim, purpose" },
      { chinese: "暖", pinyin: "nuǎn", wordType: "adj.", meaning: "warm" },
      { chinese: "塑料袋", pinyin: "sùliàodài", wordType: "n.", meaning: "plastic bag" },
      { chinese: "于是", pinyin: "yúshì", wordType: "conj.", meaning: "hence, therefore" },
      { chinese: "鼓励", pinyin: "gǔlì", wordType: "v.", meaning: "to encourage" },
      { chinese: "拒绝", pinyin: "jùjué", wordType: "v.", meaning: "to refuse, to reject" },
      { chinese: "减少", pinyin: "jiǎnshǎo", wordType: "v.", meaning: "to reduce, to decrease" },
      { chinese: "数量", pinyin: "shùliàng", wordType: "n.", meaning: "quantity, amount" },
      { chinese: "温度", pinyin: "wēndù", wordType: "n.", meaning: "temperature" },
      {
        chinese: "乘坐",
        pinyin: "chéngzuò",
        wordType: "v.",
        meaning: "to take (a vehicle), to ride (in a vehicle)",
      },
      { chinese: "丢", pinyin: "diū", wordType: "v.", meaning: "to throw, to cast" },
      { chinese: "垃圾桶", pinyin: "lājītǒng", wordType: "n.", meaning: "dustbin, trash can" },
      { chinese: "美丽", pinyin: "měilì", wordType: "adj.", meaning: "beautiful" },
    ],
  },
  {
    chapterNumber: 15,
    words: [
      { chinese: "弹钢琴", pinyin: "tán gāngqín", wordType: null, meaning: "to play the piano" },
      { chinese: "棒", pinyin: "bàng", wordType: "adj.", meaning: "excellent, amazing" },
      { chinese: "孙子", pinyin: "sūnzi", wordType: "n.", meaning: "grandson" },
      { chinese: "寒假", pinyin: "hánjià", wordType: "n.", meaning: "winter vacation" },
      { chinese: "父亲", pinyin: "fùqīn", wordType: "n.", meaning: "father" },
      { chinese: "闹钟", pinyin: "nàozhōng", wordType: "n.", meaning: "alarm clock" },
      { chinese: "响", pinyin: "xiǎng", wordType: "v.", meaning: "to sound, to ring" },
      { chinese: "醒", pinyin: "xǐng", wordType: "v.", meaning: "to wake up, to be awake" },
      { chinese: "赶", pinyin: "gǎn", wordType: "v.", meaning: "to rush for, to hurry" },
      { chinese: "厕所", pinyin: "cèsuǒ", wordType: "n.", meaning: "lavatory, toilet" },
      { chinese: "批评", pinyin: "pīpíng", wordType: "v.", meaning: "to criticize" },
      { chinese: "弄", pinyin: "nòng", wordType: "v.", meaning: "to do, to make" },
      { chinese: "管理", pinyin: "guǎnlǐ", wordType: "v.", meaning: "to manage, to administer" },
      { chinese: "打针", pinyin: "dǎ zhēn", wordType: "v.", meaning: "to give or have an injection" },
      { chinese: "护士", pinyin: "hùshi", wordType: "n.", meaning: "nurse" },
      { chinese: "表扬", pinyin: "biǎoyáng", wordType: "v.", meaning: "to praise, to commend" },
      { chinese: "千万", pinyin: "qiānwàn", wordType: "adv.", meaning: "must, to be sure to" },
      { chinese: "怀疑", pinyin: "huáiyí", wordType: "v.", meaning: "to suspect, to doubt" },
      { chinese: "故意", pinyin: "gùyì", wordType: "adv.", meaning: "intentionally, on purpose" },
      { chinese: "敲", pinyin: "qiāo", wordType: "v.", meaning: "to knock, to beat, to strike" },
      { chinese: "整理", pinyin: "zhěnglǐ", wordType: "v.", meaning: "to tidy up, to arrange" },
      { chinese: "合适", pinyin: "héshì", wordType: "adj.", meaning: "fit, suitable" },
      { chinese: "骗", pinyin: "piàn", wordType: "v.", meaning: "to cheat, to deceive" },
      { chinese: "儿童", pinyin: "értóng", wordType: "n.", meaning: "children" },
      { chinese: "假", pinyin: "jiǎ", wordType: "adj.", meaning: "false, fake" },
      { chinese: "左右", pinyin: "zuǒyòu", wordType: "n.", meaning: "around, or so" },
      { chinese: "懒", pinyin: "lǎn", wordType: "adj.", meaning: "lazy" },
      { chinese: "笨", pinyin: "bèn", wordType: "adj.", meaning: "stupid, foolish" },
      { chinese: "粗心", pinyin: "cūxīn", wordType: "adj.", meaning: "careless, thoughtless" },
      { chinese: "骄傲", pinyin: "jiāo'ào", wordType: "adj.", meaning: "arrogant, conceited" },
      { chinese: "害羞", pinyin: "hàixiū", wordType: "v.", meaning: "to be shy, to be timid" },
    ],
  },
  {
    chapterNumber: 16,
    words: [
      { chinese: "博士", pinyin: "bóshì", wordType: "n.", meaning: "doctor (academic degree)" },
      { chinese: "签证", pinyin: "qiānzhèng", wordType: "n.", meaning: "visa" },
      { chinese: "报名", pinyin: "bào míng", wordType: "v.", meaning: "to apply, to sign up" },
      { chinese: "表格", pinyin: "biǎogé", wordType: "n.", meaning: "form, table" },
      { chinese: "传真", pinyin: "chuánzhēn", wordType: "v.", meaning: "to send by fax" },
      { chinese: "号码", pinyin: "hàomǎ", wordType: "n.", meaning: "number" },
      { chinese: "参观", pinyin: "cānguān", wordType: "v.", meaning: "to visit, to look around" },
      { chinese: "激动", pinyin: "jīdòng", wordType: "adj.", meaning: "excited, emotional" },
      { chinese: "小伙子", pinyin: "xiǎohuǒzi", wordType: "n.", meaning: "young man" },
      { chinese: "记者", pinyin: "jìzhě", wordType: "n.", meaning: "journalist, reporter" },
      { chinese: "代表", pinyin: "dàibiǎo", wordType: "v.", meaning: "to represent, to stand for" },
      {
        chinese: "恐怕",
        pinyin: "kǒngpà",
        wordType: "adv.",
        meaning: "(indicating an estimation) I guess...",
      },
      { chinese: "失望", pinyin: "shīwàng", wordType: "v.", meaning: "disappointed" },
      { chinese: "郊区", pinyin: "jiāoqū", wordType: "n.", meaning: "suburb, outskirts" },
      {
        chinese: "到底",
        pinyin: "dàodǐ",
        wordType: "adv.",
        meaning: "(used in questions for emphasis) ... on earth",
      },
      {
        chinese: "呀",
        pinyin: "ya",
        wordType: "part.",
        meaning:
          "a variant of the interjection \"啊\" used at the end of a question to soften the tone",
      },
      { chinese: "导游", pinyin: "dǎoyóu", wordType: "n.", meaning: "tour guide" },
      { chinese: "礼貌", pinyin: "lǐmào", wordType: "n.", meaning: "polite" },
      { chinese: "原谅", pinyin: "yuánliàng", wordType: "v.", meaning: "to forgive" },
      { chinese: "挂", pinyin: "guà", wordType: "v.", meaning: "to hang, to put up" },
      { chinese: "同情", pinyin: "tóngqíng", wordType: "v.", meaning: "to show sympathy for" },
      { chinese: "推", pinyin: "tuī", wordType: "v.", meaning: "to put off, to postpone" },
      { chinese: "预习", pinyin: "yùxí", wordType: "v.", meaning: "to prepare lessons before class" },
      { chinese: "重点", pinyin: "zhòngdiǎn", wordType: "n.", meaning: "focal point, emphasis" },
      { chinese: "马虎", pinyin: "mǎhu", wordType: "adj.", meaning: "careless, slipshod" },
      { chinese: "自信", pinyin: "zìxìn", wordType: "adj.", meaning: "self-confident" },
      { chinese: "冷静", pinyin: "lěngjìng", wordType: "adj.", meaning: "calm, composed" },
      { chinese: "输", pinyin: "shū", wordType: "v.", meaning: "to lose, to suffer defeat" },
      { chinese: "重视", pinyin: "zhòngshì", wordType: "v.", meaning: "to attach importance to" },
      { chinese: "敢", pinyin: "gǎn", wordType: "v.", meaning: "to dare" },
      { chinese: "尊重", pinyin: "zūnzhòng", wordType: "v.", meaning: "to respect" },
    ],
  },
  {
    chapterNumber: 17,
    words: [
      { chinese: "凉快", pinyin: "liángkuai", wordType: "adj.", meaning: "pleasantly cool" },
      { chinese: "热闹", pinyin: "rènao", wordType: "adj.", meaning: "busy, bustling" },
      { chinese: "云", pinyin: "yún", wordType: "n.", meaning: "cloud" },
      { chinese: "广播", pinyin: "guǎngbō", wordType: "n.", meaning: "broadcast, radio program" },
      { chinese: "照", pinyin: "zhào", wordType: "v.", meaning: "to take a picture, to photograph" },
      {
        chinese: "倒",
        pinyin: "dào",
        wordType: "adv.",
        meaning: "(used to indicate contrast) yet, actually",
      },
      { chinese: "毛", pinyin: "máo", wordType: "n.", meaning: "hair, fur" },
      { chinese: "抱", pinyin: "bào", wordType: "v.", meaning: "to hold in the arms, to hug" },
      { chinese: "干", pinyin: "gàn", wordType: "v.", meaning: "to do, to act" },
      { chinese: "严格", pinyin: "yángé", wordType: "adj.", meaning: "strict, rigorous" },
      { chinese: "难受", pinyin: "nánshòu", wordType: "adj.", meaning: "sad, unhappy" },
      { chinese: "趟", pinyin: "tàng", wordType: "m.", meaning: "(used for a round trip) time" },
      { chinese: "放暑假", pinyin: "fàng shǔjià", wordType: null, meaning: "to be on summer vacation" },
      { chinese: "老虎", pinyin: "lǎohǔ", wordType: "n.", meaning: "tiger" },
      { chinese: "入口", pinyin: "rùkǒu", wordType: "n.", meaning: "entrance" },
      { chinese: "排队", pinyin: "pái duì", wordType: "v.", meaning: "to form a line, to line up" },
      { chinese: "活泼", pinyin: "huópō", wordType: "adj.", meaning: "lively, vivacious" },
      { chinese: "社会", pinyin: "shèhuì", wordType: "n.", meaning: "society" },
      { chinese: "竞争", pinyin: "jìngzhēng", wordType: "v.", meaning: "to compete" },
      { chinese: "森林", pinyin: "sēnlín", wordType: "n.", meaning: "forest" },
      { chinese: "剩", pinyin: "shèng", wordType: "v.", meaning: "to be left over, to remain" },
      { chinese: "暖和", pinyin: "nuǎnhuo", wordType: "adj.", meaning: "warm" },
      { chinese: "海洋", pinyin: "hǎiyáng", wordType: "n.", meaning: "sea, ocean" },
      { chinese: "底", pinyin: "dǐ", wordType: "n.", meaning: "bottom, base" },
      { chinese: "美人鱼", pinyin: "Měirényú", wordType: "n.", meaning: "mermaid" },
      { chinese: "公里", pinyin: "gōnglǐ", wordType: "m.", meaning: "kilometer" },
      { chinese: "仍然", pinyin: "réngrán", wordType: "adv.", meaning: "still, yet" },
      { chinese: "排列", pinyin: "páiliè", wordType: "v.", meaning: "to put in order, to arrange" },
      { chinese: "梦", pinyin: "mèng", wordType: "n.", meaning: "dream" },
    ],
  },
  {
    chapterNumber: 18,
    words: [
      { chinese: "降落", pinyin: "jiàngluò", wordType: "v.", meaning: "to descend, to land" },
      { chinese: "火", pinyin: "huǒ", wordType: "adj.", meaning: "hot, popular" },
      { chinese: "作者", pinyin: "zuòzhě", wordType: "n.", meaning: "author" },
      { chinese: "交通", pinyin: "jiāotōng", wordType: "n.", meaning: "traffic, communication" },
      { chinese: "技术", pinyin: "jìshù", wordType: "n.", meaning: "technology" },
      { chinese: "是否", pinyin: "shìfǒu", wordType: "adv.", meaning: "if, whether" },
      { chinese: "秒", pinyin: "miǎo", wordType: "m.", meaning: "second, 1/60 minute" },
      { chinese: "方式", pinyin: "fāngshì", wordType: "n.", meaning: "way, mode" },
      { chinese: "受不了", pinyin: "shòubùliǎo", wordType: null, meaning: "cannot stand, cannot bear" },
      { chinese: "日记", pinyin: "rìjì", wordType: "n.", meaning: "diary, journal" },
      { chinese: "安全", pinyin: "ānquán", wordType: "adj.", meaning: "safe, secure" },
      { chinese: "密码", pinyin: "mìmǎ", wordType: "n.", meaning: "password" },
      { chinese: "允许", pinyin: "yǔnxǔ", wordType: "v.", meaning: "to allow, to permit" },
      {
        chinese: "座",
        pinyin: "zuò",
        wordType: "m.",
        meaning: "used for bridges, mountains, buildings, etc.",
      },
      { chinese: "桥", pinyin: "qiáo", wordType: "n.", meaning: "bridge" },
      { chinese: "危险", pinyin: "wēixiǎn", wordType: "adj.", meaning: "dangerous" },
      { chinese: "接着", pinyin: "jiēzhe", wordType: "adv.", meaning: "then, immediately after that" },
      { chinese: "警察", pinyin: "jǐngchá", wordType: "n.", meaning: "police" },
      { chinese: "抓", pinyin: "zhuā", wordType: "v.", meaning: "to catch, to arrest" },
      { chinese: "咸", pinyin: "xián", wordType: "adj.", meaning: "salty" },
      { chinese: "矿泉水", pinyin: "kuàngquánshuǐ", wordType: "n.", meaning: "mineral water" },
      { chinese: "付款", pinyin: "fù kuǎn", wordType: null, meaning: "to pay a sum of money" },
      { chinese: "举", pinyin: "jǔ", wordType: "v.", meaning: "to give, to enumerate" },
      { chinese: "迷路", pinyin: "mí lù", wordType: "v.", meaning: "to lose one's way" },
      { chinese: "地址", pinyin: "dìzhǐ", wordType: "n.", meaning: "address" },
      { chinese: "地点", pinyin: "dìdiǎn", wordType: "n.", meaning: "place, site" },
      { chinese: "世纪", pinyin: "shìjì", wordType: "n.", meaning: "century" },
      { chinese: "邮局", pinyin: "yóujú", wordType: "n.", meaning: "post office" },
      { chinese: "收", pinyin: "shōu", wordType: "v.", meaning: "to receive" },
      { chinese: "信封", pinyin: "xìnfēng", wordType: "n.", meaning: "envelope" },
      { chinese: "网站", pinyin: "wǎngzhàn", wordType: "n.", meaning: "website" },
      { chinese: "信息", pinyin: "xìnxī", wordType: "n.", meaning: "news, information" },
    ],
  },
  {
    chapterNumber: 19,
    words: [
      { chinese: "学期", pinyin: "xuéqī", wordType: "n.", meaning: "term, semester" },
      { chinese: "出生", pinyin: "chūshēng", wordType: "v.", meaning: "to be born" },
      { chinese: "性别", pinyin: "xìngbié", wordType: "n.", meaning: "sex, gender" },
      { chinese: "道歉", pinyin: "dào qiàn", wordType: "v.", meaning: "to apologize" },
      { chinese: "打印", pinyin: "dǎyìn", wordType: "v.", meaning: "to print out" },
      { chinese: "复印", pinyin: "fùyìn", wordType: "v.", meaning: "to photocopy, to xerox" },
      { chinese: "刀", pinyin: "dāo", wordType: "n.", meaning: "knife" },
      { chinese: "破", pinyin: "pò", wordType: "adj.", meaning: "broken, torn" },
      { chinese: "脱", pinyin: "tuō", wordType: "v.", meaning: "to take off" },
      { chinese: "零钱", pinyin: "língqián", wordType: "n.", meaning: "small change" },
      { chinese: "包子", pinyin: "bāozi", wordType: "n.", meaning: "steamed stuffed bun" },
      { chinese: "打招呼", pinyin: "dǎ zhāohu", wordType: null, meaning: "to greet, to say hello" },
      { chinese: "戴", pinyin: "dài", wordType: "v.", meaning: "to wear (accessories)" },
      { chinese: "眼镜", pinyin: "yǎnjìng", wordType: "n.", meaning: "glasses, spectacles" },
      { chinese: "舞蹈", pinyin: "wǔdǎo", wordType: "n.", meaning: "dance" },
      { chinese: "国籍", pinyin: "guójí", wordType: "n.", meaning: "nationality, citizenship" },
      { chinese: "抬", pinyin: "tái", wordType: "v.", meaning: "to lift, to raise" },
      { chinese: "胳膊", pinyin: "gēbo", wordType: "n.", meaning: "arm" },
      { chinese: "转", pinyin: "zhuàn", wordType: "v.", meaning: "to turn, to shift" },
      { chinese: "租", pinyin: "zū", wordType: "v.", meaning: "to rent, to lease" },
      { chinese: "吵", pinyin: "chǎo", wordType: "adj.", meaning: "noisy" },
      { chinese: "厨房", pinyin: "chúfáng", wordType: "n.", meaning: "kitchen" },
      { chinese: "房东", pinyin: "fángdōng", wordType: "n.", meaning: "landlord/landlady" },
      {
        chinese: "占线",
        pinyin: "zhànxiàn",
        wordType: "v.",
        meaning: "(of a telephone line) to be busy, to be engaged",
      },
      { chinese: "功夫", pinyin: "gōngfu", wordType: "n.", meaning: "kung fu" },
      { chinese: "乒乓球", pinyin: "pīngpāngqiú", wordType: "n.", meaning: "table tennis, ping-pong" },
      { chinese: "羽毛球", pinyin: "yǔmáoqiú", wordType: "n.", meaning: "badminton" },
      {
        chinese: "场",
        pinyin: "chǎng",
        wordType: "m.",
        meaning: "used for sports or recreational events, etc.",
      },
      { chinese: "禁止", pinyin: "jìnzhǐ", wordType: "v.", meaning: "to prohibit, to forbid" },
      { chinese: "座位", pinyin: "zuòwèi", wordType: "n.", meaning: "seat" },
    ],
  },
  {
    chapterNumber: 20,
    words: [
      { chinese: "加油站", pinyin: "jiāyóuzhàn", wordType: "n.", meaning: "gas station" },
      { chinese: "航班", pinyin: "hángbān", wordType: "n.", meaning: "scheduled flight" },
      { chinese: "推迟", pinyin: "tuīchí", wordType: "v.", meaning: "to postpone, to delay" },
      { chinese: "高速公路", pinyin: "gāosù gōnglù", wordType: null, meaning: "expressway" },
      { chinese: "登机牌", pinyin: "dēngjīpái", wordType: "n.", meaning: "boarding pass" },
      { chinese: "首都", pinyin: "shǒudū", wordType: "n.", meaning: "capital (of a country)" },
      { chinese: "旅行", pinyin: "lǚxíng", wordType: "v.", meaning: "to travel, to tour" },
      { chinese: "怪", pinyin: "guài", wordType: "adv.", meaning: "rather, quite" },
      { chinese: "可怜", pinyin: "kělián", wordType: "adj.", meaning: "pitiable, poor" },
      { chinese: "对面", pinyin: "duìmiàn", wordType: "n.", meaning: "opposite, across" },
      { chinese: "烤鸭", pinyin: "kǎoyā", wordType: "n.", meaning: "roast duck" },
      { chinese: "祝贺", pinyin: "zhùhè", wordType: "v.", meaning: "to congratulate" },
      { chinese: "合格", pinyin: "hégé", wordType: "adj.", meaning: "qualified, up to standard" },
      { chinese: "干杯", pinyin: "gān bēi", wordType: "v.", meaning: "to drink a toast" },
      { chinese: "民族", pinyin: "mínzú", wordType: "n.", meaning: "nationality, ethnic group" },
      { chinese: "打扮", pinyin: "dǎbàn", wordType: "v.", meaning: "to dress up, to deck out" },
      { chinese: "笑话", pinyin: "xiàohua", wordType: "n.", meaning: "joke" },
      { chinese: "存", pinyin: "cún", wordType: "v.", meaning: "to store, to keep" },
      { chinese: "钥匙", pinyin: "yàoshi", wordType: "n.", meaning: "key" },
      {
        chinese: "究竟",
        pinyin: "jiūjìng",
        wordType: "adv.",
        meaning: "(used in questions for emphasis) exactly",
      },
      { chinese: "棵", pinyin: "kē", wordType: "m.", meaning: "used for plants" },
      { chinese: "汤", pinyin: "tāng", wordType: "n.", meaning: "soup" },
      { chinese: "对话", pinyin: "duìhuà", wordType: "v.", meaning: "to have a dialogue" },
      { chinese: "普通话", pinyin: "pǔtōnghuà", wordType: "n.", meaning: "Mandarin Chinese" },
      { chinese: "小吃", pinyin: "xiǎochī", wordType: "n.", meaning: "small and cheap dishes" },
      { chinese: "收拾", pinyin: "shōushi", wordType: "v.", meaning: "to put in order, to pack" },
      { chinese: "出发", pinyin: "chūfā", wordType: "v.", meaning: "to depart, to set off" },
      { chinese: "辣", pinyin: "là", wordType: "adj.", meaning: "hot, spicy" },
      { chinese: "香", pinyin: "xiāng", wordType: "adj.", meaning: "fragrant, scented" },
      { chinese: "酸", pinyin: "suān", wordType: "adj.", meaning: "sour, tart" },
    ],
  },
];
