// HSK4A's per-lesson chapter data, transcribed directly from Part 1 of the
// HSK 4 (上册) Standard Course textbook's "生词 New Words" lists, the same
// way HSK3's chapters are in-repo data rather than parsed markdown (see
// hsk3-chapters-data.ts). Each lesson's 专有名词 Proper Nouns section is
// deliberately excluded — see the no-proper-nouns rule in project memory.
//
// wordType uses the same abbreviations as the source (n., v., adj., ...);
// entries with no part-of-speech marker in the source (multi-word verb
// phrases like 开玩笑) get null.
export interface Hsk4aWordData {
  chinese: string;
  pinyin: string;
  wordType: string | null;
  meaning: string;
}

export interface Hsk4aChapterData {
  chapterNumber: number;
  words: Hsk4aWordData[];
}

export const HSK4A_CHAPTERS: Hsk4aChapterData[] = [
  {
    chapterNumber: 1,
    words: [
      { chinese: "法律", pinyin: "fǎlǜ", wordType: "n.", meaning: "law" },
      { chinese: "俩", pinyin: "liǎ", wordType: "num.-m.", meaning: "two, both" },
      { chinese: "印象", pinyin: "yìnxiàng", wordType: "n.", meaning: "impression" },
      { chinese: "深", pinyin: "shēn", wordType: "adj.", meaning: "deep" },
      { chinese: "熟悉", pinyin: "shúxī", wordType: "v.", meaning: "to be familiar with" },
      { chinese: "不仅", pinyin: "bùjǐn", wordType: "conj.", meaning: "not only" },
      { chinese: "性格", pinyin: "xìnggé", wordType: "n.", meaning: "character, personality" },
      { chinese: "开玩笑", pinyin: "kāi wánxiào", wordType: null, meaning: "to be kidding" },
      { chinese: "从来", pinyin: "cónglái", wordType: "adv.", meaning: "always, all along" },
      { chinese: "最好", pinyin: "zuìhǎo", wordType: "adv.", meaning: "had better" },
      { chinese: "共同", pinyin: "gòngtóng", wordType: "adj.", meaning: "common, shared" },
      { chinese: "适合", pinyin: "shìhé", wordType: "v.", meaning: "to suit, to fit" },
      { chinese: "幸福", pinyin: "xìngfú", wordType: "adj.", meaning: "happy" },
      { chinese: "生活", pinyin: "shēnghuó", wordType: "n./v.", meaning: "life; to live" },
      { chinese: "刚", pinyin: "gāng", wordType: "adv.", meaning: "just, not long" },
      { chinese: "浪漫", pinyin: "làngmàn", wordType: "adj.", meaning: "romantic" },
      { chinese: "够", pinyin: "gòu", wordType: "v.", meaning: "to be enough" },
      { chinese: "缺点", pinyin: "quēdiǎn", wordType: "n.", meaning: "shortcoming" },
      { chinese: "接受", pinyin: "jiēshòu", wordType: "v.", meaning: "to accept" },
      { chinese: "羡慕", pinyin: "xiànmù", wordType: "v.", meaning: "to envy, to admire" },
      { chinese: "爱情", pinyin: "àiqíng", wordType: "n.", meaning: "love (between a man and a woman)" },
      { chinese: "星星", pinyin: "xīngxing", wordType: "n.", meaning: "star" },
      { chinese: "即使", pinyin: "jíshǐ", wordType: "conj.", meaning: "even if" },
      { chinese: "加班", pinyin: "jiā bān", wordType: "v.", meaning: "to work overtime" },
      { chinese: "亮", pinyin: "liàng", wordType: "v.", meaning: "to shine, to be lit" },
      { chinese: "感动", pinyin: "gǎndòng", wordType: "v.", meaning: "to touch, to move" },
      { chinese: "自然", pinyin: "zìrán", wordType: "adv.", meaning: "naturally, certainly" },
      { chinese: "原因", pinyin: "yuányīn", wordType: "n.", meaning: "reason" },
      { chinese: "互相", pinyin: "hùxiāng", wordType: "adv.", meaning: "mutually" },
      { chinese: "吸引", pinyin: "xīyǐn", wordType: "v.", meaning: "to attract" },
      { chinese: "幽默", pinyin: "yōumò", wordType: "adj.", meaning: "humorous" },
      { chinese: "脾气", pinyin: "píqi", wordType: "n.", meaning: "temper, disposition" },
    ],
  },
  {
    chapterNumber: 2,
    words: [
      { chinese: "适应", pinyin: "shìyìng", wordType: "v.", meaning: "to get used to" },
      { chinese: "交", pinyin: "jiāo", wordType: "v.", meaning: "to make (friends)" },
      { chinese: "平时", pinyin: "píngshí", wordType: "n.", meaning: "normal times" },
      { chinese: "逛", pinyin: "guàng", wordType: "v.", meaning: "to stroll, to roam" },
      { chinese: "短信", pinyin: "duǎnxìn", wordType: "n.", meaning: "text message" },
      { chinese: "正好", pinyin: "zhènghǎo", wordType: "adv.", meaning: "just in time, just right" },
      {
        chinese: "聚会",
        pinyin: "jùhuì",
        wordType: "v./n.",
        meaning: "to have a party; party, get-together",
      },
      { chinese: "联系", pinyin: "liánxì", wordType: "v.", meaning: "to contact" },
      { chinese: "差不多", pinyin: "chàbuduō", wordType: "adv.", meaning: "almost" },
      { chinese: "专门", pinyin: "zhuānmén", wordType: "adv.", meaning: "specially" },
      { chinese: "毕业", pinyin: "bì yè", wordType: "v.", meaning: "to graduate" },
      { chinese: "麻烦", pinyin: "máfan", wordType: "v.", meaning: "to bother" },
      { chinese: "好像", pinyin: "hǎoxiàng", wordType: "adv.", meaning: "as if" },
      { chinese: "重新", pinyin: "chóngxīn", wordType: "adv.", meaning: "again, once more" },
      { chinese: "尽管", pinyin: "jǐnguǎn", wordType: "conj.", meaning: "although" },
      { chinese: "真正", pinyin: "zhēnzhèng", wordType: "adj.", meaning: "true, real" },
      { chinese: "友谊", pinyin: "yǒuyì", wordType: "n.", meaning: "friendship" },
      { chinese: "丰富", pinyin: "fēngfù", wordType: "v.", meaning: "to enrich" },
      { chinese: "无聊", pinyin: "wúliáo", wordType: "adj.", meaning: "boring" },
      { chinese: "讨厌", pinyin: "tǎoyàn", wordType: "v.", meaning: "to dislike" },
      { chinese: "却", pinyin: "què", wordType: "adv.", meaning: "but, yet" },
      { chinese: "周围", pinyin: "zhōuwéi", wordType: "n.", meaning: "surrounding" },
      { chinese: "交流", pinyin: "jiāoliú", wordType: "v.", meaning: "to exchange, to communicate" },
      { chinese: "理解", pinyin: "lǐjiě", wordType: "v.", meaning: "to understand" },
      { chinese: "镜子", pinyin: "jìngzi", wordType: "n.", meaning: "mirror" },
      { chinese: "而", pinyin: "ér", wordType: "conj.", meaning: "(showing a contrast) while, yet" },
      { chinese: "当", pinyin: "dāng", wordType: "prep.", meaning: "when, just at (a time or place)" },
      { chinese: "困难", pinyin: "kùnnan", wordType: "n.", meaning: "difficulty" },
      { chinese: "及时", pinyin: "jíshí", wordType: "adv.", meaning: "in time" },
      { chinese: "陪", pinyin: "péi", wordType: "v.", meaning: "to accompany" },
    ],
  },
  {
    chapterNumber: 3,
    words: [
      { chinese: "挺", pinyin: "tǐng", wordType: "adv.", meaning: "quite, rather" },
      { chinese: "紧张", pinyin: "jǐnzhāng", wordType: "adj.", meaning: "nervous" },
      { chinese: "信心", pinyin: "xìnxīn", wordType: "n.", meaning: "confidence" },
      { chinese: "能力", pinyin: "nénglì", wordType: "n.", meaning: "ability, competence" },
      { chinese: "招聘", pinyin: "zhāopìn", wordType: "v.", meaning: "to recruit" },
      { chinese: "提供", pinyin: "tígōng", wordType: "v.", meaning: "to provide" },
      { chinese: "负责", pinyin: "fùzé", wordType: "v.", meaning: "to be in charge of" },
      { chinese: "本来", pinyin: "běnlái", wordType: "adv.", meaning: "originally, at first" },
      { chinese: "应聘", pinyin: "yìngpìn", wordType: "v.", meaning: "to apply for a job" },
      { chinese: "材料", pinyin: "cáiliào", wordType: "n.", meaning: "data, material" },
      { chinese: "符合", pinyin: "fúhé", wordType: "v.", meaning: "to accord with" },
      { chinese: "通知", pinyin: "tōngzhī", wordType: "v.", meaning: "to inform" },
      { chinese: "律师", pinyin: "lǜshī", wordType: "n.", meaning: "lawyer" },
      { chinese: "专业", pinyin: "zhuānyè", wordType: "n.", meaning: "major, specialty" },
      { chinese: "另外", pinyin: "lìngwài", wordType: "conj.", meaning: "besides, in addition" },
      { chinese: "收入", pinyin: "shōurù", wordType: "n.", meaning: "income" },
      { chinese: "咱们", pinyin: "zánmen", wordType: "pron.", meaning: "we, us" },
      { chinese: "安排", pinyin: "ānpái", wordType: "v.", meaning: "to arrange" },
      { chinese: "首先", pinyin: "shǒuxiān", wordType: "pron.", meaning: "first" },
      { chinese: "正式", pinyin: "zhèngshì", wordType: "adj.", meaning: "formal" },
      { chinese: "留", pinyin: "liú", wordType: "v.", meaning: "to leave" },
      { chinese: "其次", pinyin: "qícì", wordType: "pron.", meaning: "second, next" },
      { chinese: "诚实", pinyin: "chéngshí", wordType: "adj.", meaning: "honest" },
      { chinese: "改变", pinyin: "gǎibiàn", wordType: "v.", meaning: "to change" },
      { chinese: "感觉", pinyin: "gǎnjué", wordType: "n.", meaning: "feeling" },
      { chinese: "判断", pinyin: "pànduàn", wordType: "v.", meaning: "to judge, to decide" },
      { chinese: "顾客", pinyin: "gùkè", wordType: "n.", meaning: "customer, client" },
      { chinese: "准时", pinyin: "zhǔnshí", wordType: "adj.", meaning: "punctual, on time" },
      { chinese: "不管", pinyin: "bùguǎn", wordType: "conj.", meaning: "no matter (what, how, etc.)" },
      { chinese: "与", pinyin: "yǔ", wordType: "prep.", meaning: "with" },
      { chinese: "约会", pinyin: "yuēhuì", wordType: "v.", meaning: "to date, to go to an appointment" },
    ],
  },
  {
    chapterNumber: 4,
    words: [
      { chinese: "提", pinyin: "tí", wordType: "v.", meaning: "to mention" },
      { chinese: "以为", pinyin: "yǐwéi", wordType: "v.", meaning: "to think, to believe" },
      { chinese: "份", pinyin: "fèn", wordType: "m.", meaning: "used for jobs among other things" },
      { chinese: "完全", pinyin: "wánquán", wordType: "adv.", meaning: "completely" },
      { chinese: "赚", pinyin: "zhuàn", wordType: "v.", meaning: "to earn" },
      { chinese: "调查", pinyin: "diàochá", wordType: "v.", meaning: "to survey, to investigate" },
      { chinese: "原来", pinyin: "yuánlái", wordType: "adj.", meaning: "original" },
      { chinese: "计划", pinyin: "jìhuà", wordType: "n./v.", meaning: "plan; to intend to" },
      { chinese: "提前", pinyin: "tíqián", wordType: "v.", meaning: "to do (sth.) in advance or ahead of time" },
      { chinese: "保证", pinyin: "bǎozhèng", wordType: "v.", meaning: "to guarantee" },
      { chinese: "提醒", pinyin: "tí xǐng", wordType: "v.", meaning: "to remind" },
      { chinese: "乱", pinyin: "luàn", wordType: "adj.", meaning: "hurry-scurry, confused" },
      { chinese: "生意", pinyin: "shēngyi", wordType: "n.", meaning: "business, trade" },
      { chinese: "谈", pinyin: "tán", wordType: "v.", meaning: "to talk, to discuss" },
      { chinese: "并", pinyin: "bìng", wordType: "adv.", meaning: "used before a negative for emphasis" },
      { chinese: "积累", pinyin: "jīlěi", wordType: "v.", meaning: "to accumulate" },
      { chinese: "经验", pinyin: "jīngyàn", wordType: "n.", meaning: "experience" },
      { chinese: "一切", pinyin: "yíqiè", wordType: "pron.", meaning: "all, every" },
      { chinese: "按照", pinyin: "ànzhào", wordType: "prep.", meaning: "according to" },
      { chinese: "成功", pinyin: "chénggōng", wordType: "adj.", meaning: "successful" },
      { chinese: "顺利", pinyin: "shùnlì", wordType: "adj.", meaning: "smooth" },
      { chinese: "感谢", pinyin: "gǎnxiè", wordType: "v.", meaning: "to thank" },
      { chinese: "消息", pinyin: "xiāoxi", wordType: "n.", meaning: "news" },
      { chinese: "按时", pinyin: "ànshí", wordType: "adv.", meaning: "on time, on schedule" },
      { chinese: "奖金", pinyin: "jiǎngjīn", wordType: "n.", meaning: "money award, bonus" },
      { chinese: "工资", pinyin: "gōngzī", wordType: "n.", meaning: "pay, salary" },
      { chinese: "方法", pinyin: "fāngfǎ", wordType: "n.", meaning: "method, way" },
      { chinese: "知识", pinyin: "zhīshi", wordType: "n.", meaning: "knowledge" },
      { chinese: "不得不", pinyin: "bù dé bù", wordType: null, meaning: "to have to, to have no choice but" },
      { chinese: "甚至", pinyin: "shènzhì", wordType: "conj.", meaning: "even, so far as to" },
      { chinese: "责任", pinyin: "zérèn", wordType: "n.", meaning: "responsibility, duty" },
    ],
  },
  {
    chapterNumber: 5,
    words: [
      { chinese: "家具", pinyin: "jiājù", wordType: "n.", meaning: "furniture" },
      { chinese: "沙发", pinyin: "shāfā", wordType: "n.", meaning: "sofa" },
      { chinese: "打折", pinyin: "dǎ zhé", wordType: "v.", meaning: "to give a discount" },
      { chinese: "价格", pinyin: "jiàgé", wordType: "n.", meaning: "price" },
      { chinese: "质量", pinyin: "zhìliàng", wordType: "n.", meaning: "quality" },
      { chinese: "肯定", pinyin: "kěndìng", wordType: "adv.", meaning: "surely, certainly" },
      { chinese: "流行", pinyin: "liúxíng", wordType: "v.", meaning: "to be popular" },
      { chinese: "顺便", pinyin: "shùnbiàn", wordType: "adv.", meaning: "in passing" },
      { chinese: "台", pinyin: "tái", wordType: "m.", meaning: "used for machines" },
      { chinese: "光", pinyin: "guāng", wordType: "adv.", meaning: "only, merely" },
      { chinese: "实在", pinyin: "shízài", wordType: "adv.", meaning: "really" },
      { chinese: "制冷", pinyin: "zhìlěng", wordType: "v.", meaning: "to refrigerate" },
      { chinese: "效果", pinyin: "xiàoguǒ", wordType: "n.", meaning: "effect" },
      { chinese: "现金", pinyin: "xiànjīn", wordType: "n.", meaning: "cash" },
      { chinese: "邀请", pinyin: "yāoqǐng", wordType: "v.", meaning: "to invite" },
      { chinese: "葡萄", pinyin: "pútáo", wordType: "n.", meaning: "grape" },
      { chinese: "艺术", pinyin: "yìshù", wordType: "n.", meaning: "art" },
      { chinese: "广告", pinyin: "guǎnggào", wordType: "n.", meaning: "advertisement" },
      { chinese: "味道", pinyin: "wèidào", wordType: "n.", meaning: "taste" },
      { chinese: "优点", pinyin: "yōudiǎn", wordType: "n.", meaning: "merit" },
      { chinese: "实际", pinyin: "shíjì", wordType: "n.", meaning: "reality" },
      { chinese: "考虑", pinyin: "kǎolǜ", wordType: "v.", meaning: "to consider" },
      { chinese: "标准", pinyin: "biāozhǔn", wordType: "n.", meaning: "standard" },
      { chinese: "样子", pinyin: "yàngzi", wordType: "n.", meaning: "look, appearance" },
      { chinese: "年龄", pinyin: "niánlíng", wordType: "n.", meaning: "age" },
      { chinese: "浪费", pinyin: "làngfèi", wordType: "v.", meaning: "to waste" },
      { chinese: "购物", pinyin: "gòu wù", wordType: null, meaning: "to shop, to buy things" },
      { chinese: "尤其", pinyin: "yóuqí", wordType: "adv.", meaning: "especially" },
      { chinese: "受到", pinyin: "shòudào", wordType: "v.", meaning: "to receive" },
      { chinese: "任何", pinyin: "rènhé", wordType: "pron.", meaning: "any, whatever" },
      { chinese: "寄", pinyin: "jì", wordType: "v.", meaning: "to mail, to send" },
    ],
  },
  {
    chapterNumber: 6,
    words: [
      { chinese: "果汁", pinyin: "guǒzhī", wordType: "n.", meaning: "fruit juice" },
      { chinese: "售货员", pinyin: "shòuhuòyuán", wordType: "n.", meaning: "salesperson" },
      { chinese: "袜子", pinyin: "wàzi", wordType: "n.", meaning: "socks" },
      { chinese: "打扰", pinyin: "dǎrǎo", wordType: "v.", meaning: "to disturb, to bother" },
      { chinese: "竟然", pinyin: "jìngrán", wordType: "adv.", meaning: "indicating unexpectedness" },
      { chinese: "西红柿", pinyin: "xīhóngshì", wordType: "n.", meaning: "tomato" },
      { chinese: "百分之", pinyin: "bǎi fēn zhī", wordType: null, meaning: "percent" },
      { chinese: "倍", pinyin: "bèi", wordType: "m.", meaning: "times, -fold" },
      { chinese: "皮肤", pinyin: "pífū", wordType: "n.", meaning: "skin" },
      { chinese: "好处", pinyin: "hǎochù", wordType: "n.", meaning: "benefit, advantage" },
      { chinese: "尝", pinyin: "cháng", wordType: "v.", meaning: "to taste" },
      { chinese: "轻", pinyin: "qīng", wordType: "adj.", meaning: "light, of little weight" },
      { chinese: "方面", pinyin: "fāngmiàn", wordType: "n.", meaning: "aspect" },
      { chinese: "值得", pinyin: "zhídé", wordType: "v.", meaning: "to be worth" },
      { chinese: "活动", pinyin: "huódòng", wordType: "n.", meaning: "activity, event" },
      { chinese: "内", pinyin: "nèi", wordType: "n.", meaning: "in, within" },
      { chinese: "免费", pinyin: "miǎn fèi", wordType: "v.", meaning: "to be free of charge" },
      { chinese: "修理", pinyin: "xiūlǐ", wordType: "v.", meaning: "to repair, to mend" },
      { chinese: "支持", pinyin: "zhīchí", wordType: "v.", meaning: "to support" },
      { chinese: "举行", pinyin: "jǔxíng", wordType: "v.", meaning: "to hold (a meeting, event, etc.)" },
      { chinese: "满", pinyin: "mǎn", wordType: "v.", meaning: "to reach a quota or limit" },
      { chinese: "其中", pinyin: "qízhōng", wordType: "n.", meaning: "among (which, them, etc.)" },
      { chinese: "小说", pinyin: "xiǎoshuō", wordType: "n.", meaning: "novel, fiction" },
      { chinese: "会员卡", pinyin: "huìyuánkǎ", wordType: "n.", meaning: "membership card" },
      { chinese: "所有", pinyin: "suǒyǒu", wordType: "adj.", meaning: "all" },
      { chinese: "获得", pinyin: "huòdé", wordType: "v.", meaning: "to get, to obtain" },
      { chinese: "情况", pinyin: "qíngkuàng", wordType: "n.", meaning: "situation, circumstances" },
      { chinese: "例如", pinyin: "lìrú", wordType: "v.", meaning: "for example" },
      { chinese: "举办", pinyin: "jǔbàn", wordType: "v.", meaning: "to hold, to conduct" },
      { chinese: "各", pinyin: "gè", wordType: "pron.", meaning: "various, different" },
      { chinese: "降低", pinyin: "jiàngdī", wordType: "v.", meaning: "to lower, to reduce" },
    ],
  },
  {
    chapterNumber: 7,
    words: [
      { chinese: "流血", pinyin: "liú xiě", wordType: "v.", meaning: "to bleed" },
      { chinese: "擦", pinyin: "cā", wordType: "v.", meaning: "to wipe" },
      { chinese: "气候", pinyin: "qìhòu", wordType: "n.", meaning: "climate" },
      { chinese: "估计", pinyin: "gūjì", wordType: "v.", meaning: "to estimate, to reckon" },
      { chinese: "咳嗽", pinyin: "késou", wordType: "v.", meaning: "to cough" },
      { chinese: "严重", pinyin: "yánzhòng", wordType: "adj.", meaning: "serious, grave" },
      { chinese: "窗户", pinyin: "chuānghu", wordType: "n.", meaning: "window" },
      { chinese: "空气", pinyin: "kōngqì", wordType: "n.", meaning: "air" },
      { chinese: "抽烟", pinyin: "chōu yān", wordType: null, meaning: "to smoke" },
      { chinese: "动作", pinyin: "dòngzuò", wordType: "n.", meaning: "action, movement" },
      { chinese: "帅", pinyin: "shuài", wordType: "adj.", meaning: "handsome" },
      { chinese: "出现", pinyin: "chūxiàn", wordType: "v.", meaning: "to appear, to emerge" },
      { chinese: "后悔", pinyin: "hòuhuǐ", wordType: "v.", meaning: "to regret" },
      {
        chinese: "来不及",
        pinyin: "láibují",
        wordType: "v.",
        meaning: "to have not enough time to, to be too late to",
      },
      { chinese: "反对", pinyin: "fǎnduì", wordType: "v.", meaning: "to oppose, to object to" },
      { chinese: "大夫", pinyin: "dàifu", wordType: "n.", meaning: "doctor" },
      { chinese: "植物", pinyin: "zhíwù", wordType: "n.", meaning: "plant" },
      { chinese: "研究", pinyin: "yánjiū", wordType: "v.", meaning: "to study, to do research" },
      { chinese: "超过", pinyin: "chāoguò", wordType: "v.", meaning: "to exceed, to surpass" },
      { chinese: "散步", pinyin: "sàn bù", wordType: "v.", meaning: "to take a walk" },
      { chinese: "指", pinyin: "zhǐ", wordType: "v.", meaning: "to refer to" },
      { chinese: "精神", pinyin: "jīngshén", wordType: "n.", meaning: "spirit, mind" },
      { chinese: "教授", pinyin: "jiàoshòu", wordType: "n.", meaning: "professor" },
      { chinese: "数字", pinyin: "shùzì", wordType: "n.", meaning: "number" },
      { chinese: "说明", pinyin: "shuōmíng", wordType: "v.", meaning: "to explain, to show" },
      { chinese: "要是", pinyin: "yàoshi", wordType: "conj.", meaning: "if, supposing" },
      { chinese: "既", pinyin: "jì", wordType: "adv.", meaning: "(used together with \"又\") both...and..." },
      { chinese: "减肥", pinyin: "jiǎn féi", wordType: null, meaning: "to lose weight" },
      { chinese: "辛苦", pinyin: "xīnkǔ", wordType: "adj.", meaning: "hard, toilsome" },
      { chinese: "肚子", pinyin: "dùzi", wordType: "n.", meaning: "belly, stomach" },
      { chinese: "感情", pinyin: "gǎnqíng", wordType: "n.", meaning: "affection, love" },
      { chinese: "烦恼", pinyin: "fánnǎo", wordType: "adj.", meaning: "worried, vexed" },
      {
        chinese: "掉",
        pinyin: "diào",
        wordType: "v.",
        meaning: "used after certain verbs, indicating the result of an action",
      },
    ],
  },
  {
    chapterNumber: 8,
    words: [
      { chinese: "巧克力", pinyin: "qiǎokèlì", wordType: "n.", meaning: "chocolate" },
      { chinese: "亲戚", pinyin: "qīnqi", wordType: "n.", meaning: "relative, kinsfolk" },
      { chinese: "伤心", pinyin: "shāng xīn", wordType: "adj.", meaning: "sad, sorrowful" },
      { chinese: "使", pinyin: "shǐ", wordType: "v.", meaning: "to make, to cause" },
      { chinese: "心情", pinyin: "xīnqíng", wordType: "n.", meaning: "mood, state of mind" },
      { chinese: "愉快", pinyin: "yúkuài", wordType: "adj.", meaning: "glad, cheerful" },
      { chinese: "景色", pinyin: "jǐngsè", wordType: "n.", meaning: "scene, view" },
      { chinese: "放松", pinyin: "fàngsōng", wordType: "v.", meaning: "to relax" },
      { chinese: "压力", pinyin: "yālì", wordType: "n.", meaning: "pressure, stress" },
      { chinese: "回忆", pinyin: "huíyì", wordType: "v.", meaning: "to call to mind, to recall" },
      { chinese: "发生", pinyin: "fāshēng", wordType: "v.", meaning: "to happen, to take place" },
      { chinese: "成为", pinyin: "chéngwéi", wordType: "v.", meaning: "to become" },
      { chinese: "只要", pinyin: "zhǐyào", wordType: "conj.", meaning: "as long as, provided" },
      {
        chinese: "师傅",
        pinyin: "shīfu",
        wordType: "n.",
        meaning: "a polite title for one with accomplished skills in a trade or handicraft",
      },
      { chinese: "大使馆", pinyin: "dàshǐguǎn", wordType: "n.", meaning: "embassy" },
      { chinese: "堵车", pinyin: "dǔ chē", wordType: null, meaning: "traffic jam" },
      { chinese: "距离", pinyin: "jùlí", wordType: "n.", meaning: "distance" },
      { chinese: "耐心", pinyin: "nàixīn", wordType: "n.", meaning: "patience" },
      { chinese: "生命", pinyin: "shēngmìng", wordType: "n.", meaning: "life" },
      { chinese: "缺少", pinyin: "quēshǎo", wordType: "v.", meaning: "to lack" },
      { chinese: "到处", pinyin: "dàochù", wordType: "adv.", meaning: "everywhere" },
      { chinese: "态度", pinyin: "tàidù", wordType: "n.", meaning: "attitude" },
      { chinese: "因此", pinyin: "yīncǐ", wordType: "conj.", meaning: "therefore, so" },
      { chinese: "科学", pinyin: "kēxué", wordType: "n.", meaning: "science" },
      { chinese: "证明", pinyin: "zhèngmíng", wordType: "v.", meaning: "to prove" },
      { chinese: "往往", pinyin: "wǎngwǎng", wordType: "adv.", meaning: "often, usually" },
      { chinese: "阳光", pinyin: "yángguāng", wordType: "adj.", meaning: "optimistic, cheerful" },
      { chinese: "积极", pinyin: "jījí", wordType: "adj.", meaning: "positive" },
      { chinese: "特点", pinyin: "tèdiǎn", wordType: "n.", meaning: "characteristic" },
    ],
  },
  {
    chapterNumber: 9,
    words: [
      { chinese: "饼干", pinyin: "bǐnggān", wordType: "n.", meaning: "biscuit" },
      { chinese: "难道", pinyin: "nándào", wordType: "adv.", meaning: "used in a rhetorical question for emphasis" },
      { chinese: "得", pinyin: "děi", wordType: "mod.", meaning: "must, have to" },
      { chinese: "坚持", pinyin: "jiānchí", wordType: "v.", meaning: "to insist, to persist" },
      { chinese: "放弃", pinyin: "fàngqì", wordType: "v.", meaning: "to give up" },
      { chinese: "主意", pinyin: "zhǔyi", wordType: "n.", meaning: "idea, plan" },
      { chinese: "网球", pinyin: "wǎngqiú", wordType: "n.", meaning: "tennis" },
      { chinese: "国际", pinyin: "guójì", wordType: "n.", meaning: "international" },
      { chinese: "轻松", pinyin: "qīngsōng", wordType: "adj.", meaning: "relaxed, effortless" },
      { chinese: "赢", pinyin: "yíng", wordType: "v.", meaning: "to win" },
      { chinese: "随便", pinyin: "suíbiàn", wordType: "adj.", meaning: "casual, at random" },
      { chinese: "汗", pinyin: "hàn", wordType: "n.", meaning: "sweat, perspiration" },
      { chinese: "通过", pinyin: "tōngguò", wordType: "prep.", meaning: "through, by means of" },
      { chinese: "篇", pinyin: "piān", wordType: "m.", meaning: "used for writings, papers or articles" },
      { chinese: "作家", pinyin: "zuòjiā", wordType: "n.", meaning: "writer" },
      { chinese: "当时", pinyin: "dāngshí", wordType: "n.", meaning: "then, at that time" },
      { chinese: "可是", pinyin: "kěshì", wordType: "conj.", meaning: "but, however" },
      { chinese: "正确", pinyin: "zhèngquè", wordType: "adj.", meaning: "correct" },
      { chinese: "理想", pinyin: "lǐxiǎng", wordType: "n.", meaning: "ideal" },
      { chinese: "勇敢", pinyin: "yǒnggǎn", wordType: "adj.", meaning: "brave, courageous" },
      { chinese: "结果", pinyin: "jiéguǒ", wordType: "n.", meaning: "result" },
      { chinese: "失败", pinyin: "shībài", wordType: "v.", meaning: "to fail" },
      { chinese: "过程", pinyin: "guòchéng", wordType: "n.", meaning: "course, process" },
      { chinese: "至少", pinyin: "zhìshǎo", wordType: "adv.", meaning: "at least" },
      { chinese: "总结", pinyin: "zǒngjié", wordType: "v.", meaning: "to sum up" },
      { chinese: "取", pinyin: "qǔ", wordType: "v.", meaning: "to gain, to seek" },
      { chinese: "经历", pinyin: "jīnglì", wordType: "v.", meaning: "to go through, to experience" },
      { chinese: "许多", pinyin: "xǔduō", wordType: "num.", meaning: "many, plenty of" },
      { chinese: "区别", pinyin: "qūbié", wordType: "n.", meaning: "difference, distinction" },
      { chinese: "暂时", pinyin: "zànshí", wordType: "n.", meaning: "temporary, for the time being" },
      { chinese: "面对", pinyin: "miànduì", wordType: "v.", meaning: "to face, to confront" },
    ],
  },
  {
    chapterNumber: 10,
    words: [
      { chinese: "礼拜天", pinyin: "lǐbàitiān", wordType: "n.", meaning: "Sunday" },
      { chinese: "空儿", pinyin: "kòngr", wordType: "n.", meaning: "free time, spare time" },
      { chinese: "母亲", pinyin: "mǔqīn", wordType: "n.", meaning: "mother" },
      { chinese: "不过", pinyin: "búguò", wordType: "conj.", meaning: "but, yet" },
      { chinese: "永远", pinyin: "yǒngyuǎn", wordType: "adv.", meaning: "forever" },
      { chinese: "方向", pinyin: "fāngxiàng", wordType: "n.", meaning: "direction, orientation" },
      { chinese: "优秀", pinyin: "yōuxiù", wordType: "adj.", meaning: "excellent, outstanding" },
      { chinese: "硕士", pinyin: "shuòshì", wordType: "n.", meaning: "Master, person who has a master's degree" },
      { chinese: "翻译", pinyin: "fānyì", wordType: "n.", meaning: "translator, interpreter" },
      { chinese: "确实", pinyin: "quèshí", wordType: "adv.", meaning: "truly, indeed" },
      { chinese: "兴奋", pinyin: "xīngfèn", wordType: "adj.", meaning: "excited" },
      { chinese: "拉", pinyin: "lā", wordType: "v.", meaning: "to pull, to drag" },
      { chinese: "建议", pinyin: "jiànyì", wordType: "n.", meaning: "suggestion, advice" },
      { chinese: "职业", pinyin: "zhíyè", wordType: "n.", meaning: "occupation, profession" },
      { chinese: "关键", pinyin: "guānjiàn", wordType: "n.", meaning: "hinge, crux" },
      { chinese: "将来", pinyin: "jiānglái", wordType: "n.", meaning: "future" },
      { chinese: "发展", pinyin: "fāzhǎn", wordType: "v.", meaning: "to develop, to promote" },
      { chinese: "躺", pinyin: "tǎng", wordType: "v.", meaning: "to lie (on one's back)" },
      { chinese: "困", pinyin: "kùn", wordType: "adj.", meaning: "sleepy" },
      { chinese: "经济", pinyin: "jīngjì", wordType: "n.", meaning: "economy" },
      { chinese: "条件", pinyin: "tiáojiàn", wordType: "n.", meaning: "condition" },
      { chinese: "富", pinyin: "fù", wordType: "adj.", meaning: "rich, wealthy" },
      { chinese: "穷", pinyin: "qióng", wordType: "adj.", meaning: "poor, impoverished" },
      { chinese: "等", pinyin: "děng", wordType: "part.", meaning: "etc., and so on" },
      { chinese: "由于", pinyin: "yóuyú", wordType: "conj.", meaning: "because, since" },
      { chinese: "比如", pinyin: "bǐrú", wordType: "v.", meaning: "for example, such as" },
      { chinese: "橡皮", pinyin: "xiàngpí", wordType: "n.", meaning: "eraser, rubber" },
      { chinese: "糖", pinyin: "táng", wordType: "n.", meaning: "sugar, candy" },
      { chinese: "低", pinyin: "dī", wordType: "adj.", meaning: "low" },
      { chinese: "答案", pinyin: "dá'àn", wordType: "n.", meaning: "answer, key" },
    ],
  },
];
