// HSK5B's per-lesson chapter data, transcribed directly from Part 1 of the
// HSK 5 (下册) Standard Course textbook's "生词 New Words" lists, the same
// way HSK5A's is. Each lesson's 专有名词 Proper Nouns section is
// deliberately excluded — see the no-proper-nouns rule in project memory.
//
// chapterNumber follows the textbook's own continuous lesson numbering
// (19-36, picking up where HSK5A's eighteenth lesson left off) rather than
// restarting at 1, the same convention used for HSK4B.
export interface Hsk5bWordData {
  chinese: string;
  pinyin: string;
  wordType: string | null;
  meaning: string;
}

export interface Hsk5bChapterData {
  chapterNumber: number;
  words: Hsk5bWordData[];
}

export const HSK5B_CHAPTERS: Hsk5bChapterData[] = [
  {
    chapterNumber: 19,
    words: [
      { chinese: "家乡", pinyin: "jiāxiāng", wordType: "n.", meaning: "hometown, native place" },
      { chinese: "萝卜", pinyin: "luóbo", wordType: "n.", meaning: "turnip, radish" },
      { chinese: "怀念", pinyin: "huáiniàn", wordType: "v.", meaning: "to miss, to feel nostalgic" },
      { chinese: "色彩", pinyin: "sècǎi", wordType: "n.", meaning: "color" },
      { chinese: "想念", pinyin: "xiǎngniàn", wordType: "v.", meaning: "to recall with longing, to miss" },
      { chinese: "青", pinyin: "qīng", wordType: "adj.", meaning: "greenish blue" },
      { chinese: "紫", pinyin: "zǐ", wordType: "adj.", meaning: "purple" },
      {
        chinese: "赏心悦目",
        pinyin: "shǎngxīn-yuèmù",
        wordType: null,
        meaning: "pleasing to both the eye and the mind",
      },
      { chinese: "般", pinyin: "bān", wordType: "part.", meaning: "sort, kind" },
      { chinese: "清淡", pinyin: "qīngdàn", wordType: "adj.", meaning: "lightly flavored and not greasy" },
      { chinese: "可口", pinyin: "kěkǒu", wordType: "adj.", meaning: "tasty, delicious" },
      { chinese: "夸", pinyin: "kuā", wordType: "v.", meaning: "to praise" },
      { chinese: "橘子", pinyin: "júzi", wordType: "n.", meaning: "tangerine" },
      { chinese: "梨", pinyin: "lí", wordType: "n.", meaning: "pear" },
      { chinese: "炒", pinyin: "chǎo", wordType: "v.", meaning: "to stir-fry" },
      { chinese: "煮", pinyin: "zhǔ", wordType: "v.", meaning: "to boil, to stew" },
      { chinese: "油炸", pinyin: "yóuzhá", wordType: "v.", meaning: "to deep-fry" },
      { chinese: "切", pinyin: "qiē", wordType: "v.", meaning: "to cut, to chop, to slice" },
      { chinese: "丝", pinyin: "sī", wordType: "n.", meaning: "shred, anything threadlike" },
      { chinese: "搅拌", pinyin: "jiǎobàn", wordType: "v.", meaning: "to stir, to mix" },
      { chinese: "均匀", pinyin: "jūnyún", wordType: "adj.", meaning: "even, well-distributed" },
      { chinese: "原料", pinyin: "yuánliào", wordType: "n.", meaning: "raw material" },
      { chinese: "擀", pinyin: "gǎn", wordType: "v.", meaning: "to roll (dough etc. with a rolling pin)" },
      { chinese: "薄", pinyin: "báo", wordType: "adj.", meaning: "thin" },
      { chinese: "折叠", pinyin: "zhédié", wordType: "v.", meaning: "to fold" },
      { chinese: "透明", pinyin: "tòumíng", wordType: "adj.", meaning: "transparent" },
      { chinese: "淋", pinyin: "lín", wordType: "v.", meaning: "to spatter, to sprinkle" },
      { chinese: "圈", pinyin: "quān", wordType: "n.", meaning: "circle, ring" },
      {
        chinese: "烫",
        pinyin: "tàng",
        wordType: "v./adj.",
        meaning: "to scald, to burn; very hot, scalding",
      },
      { chinese: "盖", pinyin: "gài", wordType: "v./n.", meaning: "to cover; lid, cover" },
      { chinese: "预防", pinyin: "yùfáng", wordType: "v.", meaning: "to guard against, to prevent" },
      { chinese: "糊", pinyin: "hú", wordType: "v.", meaning: "to be burnt" },
      { chinese: "文火", pinyin: "wénhuǒ", wordType: "n.", meaning: "slow fire, gentle heat" },
      { chinese: "闻", pinyin: "wén", wordType: "v.", meaning: "to smell" },
      {
        chinese: "趁",
        pinyin: "chèn",
        wordType: "prep.",
        meaning: "to take advantage of, (to do...) at the time when",
      },
      { chinese: "口味", pinyin: "kǒuwèi", wordType: "n.", meaning: "taste, flavor" },
      { chinese: "少许", pinyin: "shǎoxǔ", wordType: "adj.", meaning: "a little, some" },
      { chinese: "酱油", pinyin: "jiàngyóu", wordType: "n.", meaning: "soy sauce" },
      { chinese: "醋", pinyin: "cù", wordType: "n.", meaning: "vinegar" },
      { chinese: "焦", pinyin: "jiāo", wordType: "adj.", meaning: "burnt, scorched" },
      { chinese: "嫩", pinyin: "nèn", wordType: "adj.", meaning: "soft, tender" },
      { chinese: "特色", pinyin: "tèsè", wordType: "n.", meaning: "characteristic, distinctive feature" },
      { chinese: "痰", pinyin: "tán", wordType: "n.", meaning: "phlegm, sputum" },
      { chinese: "平安", pinyin: "píng'ān", wordType: "adj.", meaning: "safe, well" },
    ],
  },
  {
    chapterNumber: 20,
    words: [
      { chinese: "摊", pinyin: "tān", wordType: "n.", meaning: "stall, stand" },
      { chinese: "出版", pinyin: "chūbǎn", wordType: "v.", meaning: "to publish" },
      { chinese: "连环画", pinyin: "liánhuánhuà", wordType: "n.", meaning: "picture-story book" },
      { chinese: "年代", pinyin: "niándài", wordType: "n.", meaning: "decade of a century" },
      { chinese: "单调", pinyin: "dāndiào", wordType: "adj.", meaning: "monotonous, dull" },
      { chinese: "网络", pinyin: "wǎngluò", wordType: "n.", meaning: "network, web" },
      { chinese: "动画片", pinyin: "dònghuàpiàn", wordType: "n.", meaning: "animated cartoon" },
      {
        chinese: "娱乐",
        pinyin: "yúlè",
        wordType: "n./v.",
        meaning: "entertainment; to amuse, to entertain",
      },
      { chinese: "无数", pinyin: "wúshù", wordType: "adj.", meaning: "countless, innumerable" },
      { chinese: "青少年", pinyin: "qīng-shàonián", wordType: "n.", meaning: "youngsters, teenagers" },
      { chinese: "从事", pinyin: "cóngshì", wordType: "v.", meaning: "to engage in" },
      { chinese: "毫无", pinyin: "háowú", wordType: null, meaning: "not in the least" },
      { chinese: "疑问", pinyin: "yíwèn", wordType: "n.", meaning: "question, doubt" },
      { chinese: "棚子", pinyin: "péngzi", wordType: "n.", meaning: "shed, shack" },
      { chinese: "砖头", pinyin: "zhuāntóu", wordType: "n.", meaning: "brick" },
      { chinese: "支", pinyin: "zhī", wordType: "v.", meaning: "to prop up, to support" },
      { chinese: "粗糙", pinyin: "cūcāo", wordType: "adj.", meaning: "rough, crude" },
      { chinese: "木头", pinyin: "mùtou", wordType: "n.", meaning: "wood, timber" },
      { chinese: "题材", pinyin: "tícái", wordType: "n.", meaning: "theme, subject matter" },
      { chinese: "翻", pinyin: "fān", wordType: "v.", meaning: "to turn (over)" },
      { chinese: "搭", pinyin: "dā", wordType: "v.", meaning: "to hang over, to lay over" },
      { chinese: "整齐", pinyin: "zhěngqí", wordType: "adj.", meaning: "tidy, orderly" },
      { chinese: "年纪", pinyin: "niánjì", wordType: "n.", meaning: "age" },
      { chinese: "身材", pinyin: "shēncái", wordType: "n.", meaning: "figure, stature" },
      { chinese: "成人", pinyin: "chéngrén", wordType: "n.", meaning: "adult" },
      { chinese: "册", pinyin: "cè", wordType: "m.", meaning: "volume" },
      { chinese: "假如", pinyin: "jiǎrú", wordType: "conj.", meaning: "if, in case" },
      { chinese: "登记", pinyin: "dēngjì", wordType: "v.", meaning: "to register, to enter one's name" },
      { chinese: "记录", pinyin: "jìlù", wordType: "n./v.", meaning: "record, note; to record" },
      { chinese: "手续", pinyin: "shǒuxù", wordType: "n.", meaning: "procedure" },
      { chinese: "办理", pinyin: "bànlǐ", wordType: "v.", meaning: "to handle, to deal with" },
      { chinese: "押金", pinyin: "yājīn", wordType: "n.", meaning: "cash pledge, deposit" },
      { chinese: "凭", pinyin: "píng", wordType: "v./prep.", meaning: "to rely on; on the basis of" },
      {
        chinese: "印刷",
        pinyin: "yìnshuā",
        wordType: "v.",
        meaning: "to print (books, newspapers, etc.)",
      },
      { chinese: "涨", pinyin: "zhǎng", wordType: "v.", meaning: "to rise, to go up" },
      { chinese: "收藏", pinyin: "shōucáng", wordType: "v.", meaning: "to collect, to store up" },
    ],
  },
  {
    chapterNumber: 21,
    words: [
      { chinese: "情缘", pinyin: "qíngyuán", wordType: "n.", meaning: "predestined love, sentimental bond" },
      { chinese: "逻辑", pinyin: "luóji", wordType: "n.", meaning: "logic" },
      { chinese: "硬", pinyin: "yìng", wordType: "adv.", meaning: "rigidly, mechanically" },
      {
        chinese: "死记硬背",
        pinyin: "sǐjì-yìngbèi",
        wordType: null,
        meaning: "to memorize mechanically without understanding",
      },
      { chinese: "偶然", pinyin: "ǒurán", wordType: "adj./adv.", meaning: "accidental; by chance" },
      { chinese: "演变", pinyin: "yǎnbiàn", wordType: "v.", meaning: "to change, to evolve" },
      { chinese: "遗憾", pinyin: "yíhàn", wordType: "adj./n.", meaning: "regretful; deep regret" },
      { chinese: "心脏", pinyin: "xīnzàng", wordType: "n.", meaning: "heart" },
      { chinese: "思考", pinyin: "sīkǎo", wordType: "v.", meaning: "to think deeply, to ponder" },
      { chinese: "抓紧", pinyin: "zhuā jǐn", wordType: "v.", meaning: "to firmly grasp" },
      { chinese: "尽快", pinyin: "jǐnkuài", wordType: "adv.", meaning: "as soon as possible" },
      { chinese: "经典", pinyin: "jīngdiǎn", wordType: "n./adj.", meaning: "classics; classical" },
      { chinese: "库", pinyin: "kù", wordType: "n.", meaning: "storehouse, bank" },
      { chinese: "输入", pinyin: "shūrù", wordType: "v.", meaning: "to input" },
      { chinese: "元旦", pinyin: "Yuándàn", wordType: "n.", meaning: "New Year's Day" },
      { chinese: "疾病", pinyin: "jíbìng", wordType: "n.", meaning: "disease, illness" },
      { chinese: "创办", pinyin: "chuàngbàn", wordType: "v.", meaning: "to establish, to set up" },
      {
        chinese: "公开",
        pinyin: "gōngkāi",
        wordType: "v./adj.",
        meaning: "to make known to the public; open",
      },
      { chinese: "最初", pinyin: "zuìchū", wordType: "n.", meaning: "first, earliest" },
      { chinese: "痛苦", pinyin: "tòngkǔ", wordType: "adj.", meaning: "painful, suffering" },
      { chinese: "微博", pinyin: "wēibó", wordType: "n.", meaning: "microblog" },
      {
        chinese: "称呼",
        pinyin: "chēnghu",
        wordType: "v./n.",
        meaning: "to call, to address; form of address",
      },
      { chinese: "克服", pinyin: "kèfú", wordType: "v.", meaning: "to overcome, to conquer" },
      { chinese: "收集", pinyin: "shōují", wordType: "v.", meaning: "to collect, to gather" },
      { chinese: "包含", pinyin: "bāohán", wordType: "v.", meaning: "to contain, to include" },
      {
        chinese: "繁体(字)",
        pinyin: "fántǐ(zì)",
        wordType: "n.",
        meaning: "complex form, traditional Chinese characters",
      },
      {
        chinese: "简体(字)",
        pinyin: "jiǎntǐ(zì)",
        wordType: "n.",
        meaning: "simplified form, simplified Chinese characters",
      },
      { chinese: "方言", pinyin: "fāngyán", wordType: "n.", meaning: "dialect" },
      { chinese: "称赞", pinyin: "chēngzàn", wordType: "v.", meaning: "to praise, to commend" },
      { chinese: "真相", pinyin: "zhēnxiàng", wordType: "n.", meaning: "truth, fact" },
      { chinese: "佩服", pinyin: "pèifú", wordType: "v.", meaning: "to admire" },
      { chinese: "开放", pinyin: "kāifàng", wordType: "v.", meaning: "to open to the public" },
      { chinese: "下载", pinyin: "xiàzài", wordType: "v.", meaning: "to download" },
      { chinese: "单位", pinyin: "dānwèi", wordType: "n.", meaning: "company, employer" },
      { chinese: "识别", pinyin: "shíbié", wordType: "v.", meaning: "to recognize, to identify" },
      { chinese: "查询", pinyin: "cháxún", wordType: "v.", meaning: "to search, to retrieve" },
      { chinese: "物理", pinyin: "wùlǐ", wordType: "n.", meaning: "physics" },
      {
        chinese: "完善",
        pinyin: "wánshàn",
        wordType: "v./adj.",
        meaning: "to make perfect, to improve; perfect",
      },
      { chinese: "退休", pinyin: "tuì xiū", wordType: "v.", meaning: "to retire" },
      { chinese: "日程", pinyin: "rìchéng", wordType: "n.", meaning: "schedule" },
      { chinese: "追求", pinyin: "zhuīqiú", wordType: "v.", meaning: "to pursue, to go after" },
      { chinese: "梦想", pinyin: "mèngxiǎng", wordType: "n./v.", meaning: "dream; to dream" },
    ],
  },
  {
    chapterNumber: 22,
    words: [
      { chinese: "过分", pinyin: "guòfèn", wordType: "adj.", meaning: "excessive" },
      { chinese: "强调", pinyin: "qiángdiào", wordType: "v.", meaning: "to emphasize" },
      { chinese: "作文", pinyin: "zuòwén", wordType: "n.", meaning: "essay, composition" },
      { chinese: "观点", pinyin: "guāndiǎn", wordType: "n.", meaning: "idea, opinion" },
      { chinese: "客观", pinyin: "kèguān", wordType: "adj.", meaning: "objective" },
      { chinese: "全面", pinyin: "quánmiàn", wordType: "adj.", meaning: "all-round, comprehensive" },
      { chinese: "转变", pinyin: "zhuǎnbiàn", wordType: "v.", meaning: "to change, to transform" },
      { chinese: "观念", pinyin: "guānniàn", wordType: "n.", meaning: "mentality, concept" },
      { chinese: "火柴", pinyin: "huǒchái", wordType: "n.", meaning: "match (for producing a flame, etc.)" },
      { chinese: "灰", pinyin: "huī", wordType: "n./adj.", meaning: "dust; gray" },
      { chinese: "一旦", pinyin: "yídàn", wordType: "adv.", meaning: "once, when" },
      { chinese: "王宫", pinyin: "wánggōng", wordType: "n.", meaning: "royal palace" },
      { chinese: "王子", pinyin: "wángzǐ", wordType: "n.", meaning: "prince" },
      { chinese: "属于", pinyin: "shǔyú", wordType: "v.", meaning: "to belong to" },
      {
        chinese: "对待",
        pinyin: "duìdài",
        wordType: "v.",
        meaning: "to treat, to adopt a certain attitude towards",
      },
      { chinese: "交换", pinyin: "jiāohuàn", wordType: "v.", meaning: "to exchange, to interchange" },
      { chinese: "拥有", pinyin: "yōngyǒu", wordType: "v.", meaning: "to own, to possess" },
      { chinese: "巨大", pinyin: "jùdà", wordType: "adj.", meaning: "huge, tremendous" },
      { chinese: "承认", pinyin: "chéngrèn", wordType: "v.", meaning: "to admit, to acknowledge" },
      { chinese: "人性", pinyin: "rénxìng", wordType: "n.", meaning: "human nature" },
      { chinese: "完美", pinyin: "wánměi", wordType: "adj.", meaning: "perfect, flawless" },
      { chinese: "难免", pinyin: "nánmiǎn", wordType: "adj.", meaning: "hard to avoid" },
      { chinese: "疼爱", pinyin: "téng'ài", wordType: "v.", meaning: "to love dearly" },
      { chinese: "平等", pinyin: "píngděng", wordType: "adj.", meaning: "equal" },
      { chinese: "自私", pinyin: "zìsī", wordType: "adj.", meaning: "selfish" },
      {
        chinese: "倾向",
        pinyin: "qīngxiàng",
        wordType: "v./n.",
        meaning: "to be inclined to; tendency, inclination",
      },
      { chinese: "理由", pinyin: "lǐyóu", wordType: "n.", meaning: "reason, ground" },
      { chinese: "道德", pinyin: "dàodé", wordType: "n.", meaning: "morality, ethics" },
      { chinese: "童话", pinyin: "tónghuà", wordType: "n.", meaning: "fairy tale" },
      { chinese: "价值", pinyin: "jiàzhí", wordType: "n.", meaning: "value" },
      { chinese: "单纯", pinyin: "dānchún", wordType: "adj.", meaning: "simple, mere" },
      {
        chinese: "主张",
        pinyin: "zhǔzhāng",
        wordType: "v./n.",
        meaning: "to hold, to advocate; view, stand",
      },
      { chinese: "知感", pinyin: "zhīgǎn", wordType: "n.", meaning: "sense, perception" },
    ],
  },
  {
    chapterNumber: 23,
    words: [
      { chinese: "乖", pinyin: "guāi", wordType: "adj.", meaning: "obedient, well-behaved" },
      { chinese: "刻苦", pinyin: "kèkǔ", wordType: "adj.", meaning: "hardworking, assiduous" },
      { chinese: "遵守", pinyin: "zūnshǒu", wordType: "v.", meaning: "to abide by, to observe" },
      { chinese: "纪律", pinyin: "jìlǜ", wordType: "n.", meaning: "discipline, rule" },
      { chinese: "征求", pinyin: "zhēngqiú", wordType: "v.", meaning: "to seek, to ask for" },
      { chinese: "念", pinyin: "niàn", wordType: "v.", meaning: "to study" },
      { chinese: "基本", pinyin: "jīběn", wordType: "adv.", meaning: "basically, on the whole" },
      { chinese: "阶段", pinyin: "jiēduàn", wordType: "n.", meaning: "stage, phase" },
      { chinese: "亲爱", pinyin: "qīn'ài", wordType: "adj.", meaning: "dear, beloved" },
      { chinese: "违反", pinyin: "wéifǎn", wordType: "v.", meaning: "to violate, to go against" },
      { chinese: "规矩", pinyin: "guīju", wordType: "n.", meaning: "rule, established practice" },
      { chinese: "能干", pinyin: "nénggàn", wordType: "adj.", meaning: "capable" },
      { chinese: "讲座", pinyin: "jiǎngzuò", wordType: "n.", meaning: "lecture" },
      { chinese: "出席", pinyin: "chūxí", wordType: "v.", meaning: "to attend, to be present" },
      { chinese: "酒吧", pinyin: "jiǔbā", wordType: "n.", meaning: "bar (for drinks)" },
      { chinese: "担任", pinyin: "dānrèn", wordType: "v.", meaning: "to serve as, to hold the post of" },
      { chinese: "主席", pinyin: "zhǔxí", wordType: "n.", meaning: "chairperson" },
      { chinese: "组织", pinyin: "zǔzhī", wordType: "v.", meaning: "to organize" },
      { chinese: "外交", pinyin: "wàijiāo", wordType: "n.", meaning: "diplomacy" },
      { chinese: "经商", pinyin: "jīng shāng", wordType: "v.", meaning: "to do business, to engage in trade" },
      { chinese: "目标", pinyin: "mùbiāo", wordType: "n.", meaning: "goal, objective" },
      { chinese: "系", pinyin: "xì", wordType: "n.", meaning: "department (of a university)" },
      { chinese: "名牌", pinyin: "míngpái", wordType: "n.", meaning: "famous brand" },
      { chinese: "录取", pinyin: "lùqǔ", wordType: "v.", meaning: "to enroll, to admit" },
      { chinese: "面临", pinyin: "miànlín", wordType: "v.", meaning: "to face, to confront" },
      { chinese: "一致", pinyin: "yízhì", wordType: "adj.", meaning: "identical, unanimous" },
      { chinese: "让步", pinyin: "ràng bù", wordType: "v.", meaning: "to concede, to give in" },
      { chinese: "隐约", pinyin: "yǐnyuē", wordType: "adj.", meaning: "indistinct, vague" },
      { chinese: "陌生", pinyin: "mòshēng", wordType: "adj.", meaning: "strange, unfamiliar" },
      { chinese: "某", pinyin: "mǒu", wordType: "pron.", meaning: "some, certain" },
      { chinese: "建立", pinyin: "jiànlì", wordType: "v.", meaning: "to build, to establish" },
      { chinese: "单独", pinyin: "dāndú", wordType: "adv.", meaning: "alone, by oneself" },
      { chinese: "沟通", pinyin: "gōutōng", wordType: "v.", meaning: "to communicate" },
      { chinese: "横", pinyin: "héng", wordType: "adj.", meaning: "across" },
      { chinese: "沙滩", pinyin: "shātān", wordType: "n.", meaning: "sand beach" },
      { chinese: "沉默", pinyin: "chénmò", wordType: "v.", meaning: "to be silent" },
      { chinese: "吻", pinyin: "wěn", wordType: "v.", meaning: "to kiss" },
      { chinese: "忍不住", pinyin: "rěn bú zhù", wordType: null, meaning: "cannot help (doing sth.)" },
      { chinese: "幸亏", pinyin: "xìngkuī", wordType: "adv.", meaning: "fortunately" },
      { chinese: "暗", pinyin: "àn", wordType: "adj.", meaning: "dark, dim" },
    ],
  },
  {
    chapterNumber: 24,
    words: [
      {
        chinese: "支教",
        pinyin: "zhī jiào",
        wordType: "v.",
        meaning: "to volunteer to teach in a backward region",
      },
      { chinese: "行动", pinyin: "xíngdòng", wordType: "n.", meaning: "action, activity" },
      { chinese: "家访", pinyin: "jiāfǎng", wordType: "v.", meaning: "to visit the parents of schoolchildren" },
      { chinese: "发言", pinyin: "fā yán", wordType: "v.", meaning: "to speak, to make a speech" },
      { chinese: "及格", pinyin: "jí gé", wordType: "v.", meaning: "to pass an exam" },
      { chinese: "交往", pinyin: "jiāowǎng", wordType: "v.", meaning: "to associate, to contact" },
      { chinese: "家务", pinyin: "jiāwù", wordType: "n.", meaning: "household duties" },
      { chinese: "体贴", pinyin: "tǐtiē", wordType: "adj.", meaning: "thoughtful, considerate" },
      { chinese: "排练", pinyin: "páiliàn", wordType: "v.", meaning: "to rehearse" },
      { chinese: "蝴蝶", pinyin: "húdié", wordType: "n.", meaning: "butterfly" },
      { chinese: "舞蹈", pinyin: "wǔdǎo", wordType: "n.", meaning: "dance" },
      { chinese: "冠军", pinyin: "guànjūn", wordType: "n.", meaning: "champion, first-prize winner" },
      { chinese: "鼓掌", pinyin: "gǔ zhǎng", wordType: "v.", meaning: "to applaud" },
      { chinese: "用功", pinyin: "yònggōng", wordType: "adj.", meaning: "hardworking, diligent" },
      { chinese: "进步", pinyin: "jìn bù", wordType: "v.", meaning: "to make progress, to improve" },
      { chinese: "题目", pinyin: "tímù", wordType: "n.", meaning: "title" },
      { chinese: "朗读", pinyin: "lǎngdú", wordType: "v.", meaning: "to read aloud" },
      { chinese: "温柔", pinyin: "wēnróu", wordType: "adj.", meaning: "gentle" },
      { chinese: "勇气", pinyin: "yǒngqì", wordType: "n.", meaning: "courage" },
      {
        chinese: "青壮年",
        pinyin: "qīng-zhuàngnián",
        wordType: null,
        meaning: "young and middle-aged adults",
      },
      { chinese: "闯", pinyin: "chuǎng", wordType: "v.", meaning: "to go around (to accomplish certain goals)" },
      { chinese: "留守", pinyin: "liúshǒu", wordType: "v.", meaning: "to stay behind to take care of things" },
      { chinese: "主题", pinyin: "zhǔtí", wordType: "n.", meaning: "theme, subject" },
      { chinese: "地理", pinyin: "dìlǐ", wordType: "n.", meaning: "geography" },
      { chinese: "采访", pinyin: "cǎifǎng", wordType: "v.", meaning: "to interview" },
      { chinese: "利用", pinyin: "lìyòng", wordType: "v.", meaning: "to utilize, to make use of" },
      { chinese: "空闲", pinyin: "kòngxián", wordType: "adj.", meaning: "leisurely, free" },
      { chinese: "指导", pinyin: "zhǐdǎo", wordType: "v.", meaning: "to guide, to instruct" },
      { chinese: "培训", pinyin: "péixùn", wordType: "v.", meaning: "to train" },
      { chinese: "建设", pinyin: "jiànshè", wordType: "v.", meaning: "to build, to construct" },
      { chinese: "操心", pinyin: "cāoxīn", wordType: "v.", meaning: "to worry about, to be concerned about" },
      { chinese: "承担", pinyin: "chéngdān", wordType: "v.", meaning: "to undertake, to shoulder" },
      { chinese: "义务", pinyin: "yìwù", wordType: "n.", meaning: "duty, obligation" },
      { chinese: "艰巨", pinyin: "jiānjù", wordType: "adj.", meaning: "arduous, formidable" },
      { chinese: "力量", pinyin: "lìliàng", wordType: "n.", meaning: "strength, capability" },
      { chinese: "收获", pinyin: "shōuhuò", wordType: "n.", meaning: "gain" },
    ],
  },
  {
    chapterNumber: 25,
    words: [
      { chinese: "返航", pinyin: "fǎnháng", wordType: "v.", meaning: "to be on the homeward voyage" },
      { chinese: "恶劣", pinyin: "èliè", wordType: "adj.", meaning: "bad, vile" },
      { chinese: "可怕", pinyin: "kěpà", wordType: "adj.", meaning: "terrible, dreadful" },
      { chinese: "风浪", pinyin: "fēnglàng", wordType: "n.", meaning: "storm, stormy waves" },
      { chinese: "慌张", pinyin: "huāngzhāng", wordType: "adj.", meaning: "flurried, flustered" },
      { chinese: "舱", pinyin: "cāng", wordType: "n.", meaning: "cabin" },
      { chinese: "使劲(儿)", pinyin: "shǐjìn(r)", wordType: "v.", meaning: "to exert oneself, to make efforts" },
      { chinese: "朝", pinyin: "cháo", wordType: "prep.", meaning: "towards" },
      { chinese: "简直", pinyin: "jiǎnzhí", wordType: "adv.", meaning: "simply, virtually" },
      { chinese: "沉", pinyin: "chén", wordType: "v.", meaning: "to sink" },
      { chinese: "严肃", pinyin: "yánsù", wordType: "adj.", meaning: "serious, solemn" },
      { chinese: "猛烈", pinyin: "měngliè", wordType: "adj.", meaning: "strong, violent, fierce" },
      { chinese: "狂", pinyin: "kuáng", wordType: "adj.", meaning: "wildly, unrestrainedly" },
      { chinese: "威胁", pinyin: "wēixié", wordType: "v.", meaning: "to threaten" },
      { chinese: "平衡", pinyin: "pínghéng", wordType: "adj.", meaning: "balanced" },
      { chinese: "吨", pinyin: "dūn", wordType: "m.", meaning: "metric ton" },
      { chinese: "钢铁", pinyin: "gāngtiě", wordType: "n.", meaning: "steel" },
      { chinese: "根基", pinyin: "gēnjī", wordType: "n.", meaning: "basis, foundation" },
      { chinese: "重量", pinyin: "zhòngliàng", wordType: "n.", meaning: "weight" },
      { chinese: "相似", pinyin: "xiāngsì", wordType: "adj.", meaning: "similar" },
      { chinese: "风景", pinyin: "fēngjǐng", wordType: "n.", meaning: "scenery, view" },
      { chinese: "窄", pinyin: "zhǎi", wordType: "adj.", meaning: "narrow" },
      { chinese: "万丈", pinyin: "wànzhàng", wordType: "num.-m.", meaning: "lofty, bottomless" },
      { chinese: "深渊", pinyin: "shēnyuān", wordType: "n.", meaning: "abyss, bottomless pit" },
      { chinese: "游览", pinyin: "yóulǎn", wordType: "v.", meaning: "to visit, to tour" },
      { chinese: "发抖", pinyin: "fādǒu", wordType: "v.", meaning: "to tremble, to shiver" },
      { chinese: "负重", pinyin: "fùzhòng", wordType: "v.", meaning: "to bear a load or weight" },
      { chinese: "摔倒", pinyin: "shuāidǎo", wordType: null, meaning: "to fall down, to tumble" },
      { chinese: "妇女", pinyin: "fùnǚ", wordType: "n.", meaning: "woman" },
      { chinese: "起", pinyin: "qǐ", wordType: "m.", meaning: "case, instance" },
      { chinese: "丝毫", pinyin: "sīháo", wordType: "adj.", meaning: "slightest, at all" },
      { chinese: "滚", pinyin: "gǔn", wordType: "v.", meaning: "to roll, to tumble" },
      { chinese: "风险", pinyin: "fēngxiǎn", wordType: "n.", meaning: "risk" },
      { chinese: "谨慎", pinyin: "jǐnshèn", wordType: "adj.", meaning: "cautious, prudent" },
      { chinese: "效应", pinyin: "xiàoyìng", wordType: "n.", meaning: "effect" },
      { chinese: "胸", pinyin: "xiōng", wordType: "n.", meaning: "chest, bosom" },
      { chinese: "承受", pinyin: "chéngshòu", wordType: "v.", meaning: "to bear, to endure" },
      { chinese: "和尚", pinyin: "héshang", wordType: "n.", meaning: "(Buddhist) monk" },
      { chinese: "钟", pinyin: "zhōng", wordType: "n.", meaning: "bell" },
      { chinese: "彻底", pinyin: "chèdǐ", wordType: "adj.", meaning: "thorough, complete" },
    ],
  },
  {
    chapterNumber: 26,
    words: [
      { chinese: "忙碌", pinyin: "mánglù", wordType: "adj.", meaning: "busy, fully occupied" },
      { chinese: "被动", pinyin: "bèidòng", wordType: "adj.", meaning: "passive" },
      { chinese: "奴隶", pinyin: "núlì", wordType: "n.", meaning: "slave" },
      { chinese: "虚伪", pinyin: "xūwěi", wordType: "adj.", meaning: "hypocritical" },
      { chinese: "思想", pinyin: "sīxiǎng", wordType: "n.", meaning: "thought, thinking" },
      { chinese: "反省", pinyin: "fǎnxǐng", wordType: "v.", meaning: "to reflect on oneself, to self-examine" },
      { chinese: "据说", pinyin: "jùshuō", wordType: "v.", meaning: "it is said, reputedly" },
      { chinese: "个性", pinyin: "gèxìng", wordType: "n.", meaning: "individual character, personality" },
      { chinese: "冒险", pinyin: "mào xiǎn", wordType: "v.", meaning: "to venture, to have an adventure" },
      { chinese: "丛林", pinyin: "cónglín", wordType: "n.", meaning: "jungle, forest" },
      { chinese: "文明", pinyin: "wénmíng", wordType: "n.", meaning: "civilization" },
      {
        chinese: "纪录",
        pinyin: "jìlù",
        wordType: "n./v.",
        meaning: "record, note; to record, to note down",
      },
      { chinese: "雇", pinyin: "gù", wordType: "v.", meaning: "to employ, to hire" },
      {
        chinese: "来",
        pinyin: "lái",
        wordType: "part.",
        meaning: "used after round numbers to indicate approximation",
      },
      { chinese: "批", pinyin: "pī", wordType: "m.", meaning: "group, batch" },
      { chinese: "出色", pinyin: "chūsè", wordType: "adj.", meaning: "remarkable, outstanding" },
      {
        chinese: "健步如飞",
        pinyin: "jiànbù-rúfēi",
        wordType: null,
        meaning: "to walk as if on wings",
      },
      { chinese: "一连", pinyin: "yīlián", wordType: "adv.", meaning: "in a row, in succession" },
      { chinese: "耽误", pinyin: "dānwù", wordType: "v.", meaning: "to delay, to spoil through delay" },
      { chinese: "至于", pinyin: "zhìyú", wordType: "prep.", meaning: "as for, as to" },
      { chinese: "投资", pinyin: "tóu zī", wordType: "v.", meaning: "to invest, to fund" },
      { chinese: "人物", pinyin: "rénwù", wordType: "n.", meaning: "figure, personage" },
      { chinese: "得罪", pinyin: "dézuì", wordType: "v.", meaning: "to offend, to displease" },
      { chinese: "总算", pinyin: "zǒngsuàn", wordType: "adv.", meaning: "at last, finally" },
      {
        chinese: "搞",
        pinyin: "gǎo",
        wordType: "v.",
        meaning: "(followed by a complement) to produce a certain effect or result",
      },
      { chinese: "习俗", pinyin: "xísú", wordType: "n.", meaning: "custom, convention" },
      { chinese: "灵魂", pinyin: "línghún", wordType: "n.", meaning: "soul, spirit" },
      { chinese: "疲劳", pinyin: "píláo", wordType: "adj.", meaning: "tired, fatigued" },
      { chinese: "哲理", pinyin: "zhélǐ", wordType: "n.", meaning: "philosophy" },
      { chinese: "提倡", pinyin: "tíchàng", wordType: "v.", meaning: "to advocate, to encourage" },
      { chinese: "步骤", pinyin: "bùzhòu", wordType: "n.", meaning: "step, procedure" },
      { chinese: "闭关", pinyin: "bìguān", wordType: "v.", meaning: "to stay secluded (a Taoist practice)" },
      { chinese: "一律", pinyin: "yīlǜ", wordType: "adv.", meaning: "all, without exception" },
      { chinese: "寂寞", pinyin: "jìmò", wordType: "adj.", meaning: "lonely" },
      { chinese: "效率", pinyin: "xiàolǜ", wordType: "n.", meaning: "efficiency" },
    ],
  },
  {
    chapterNumber: 27,
    words: [
      { chinese: "(象)棋", pinyin: "(xiàng)qí", wordType: "n.", meaning: "(Chinese) chess, board game" },
      { chinese: "教练", pinyin: "jiàoliàn", wordType: "n.", meaning: "coach, instructor" },
      { chinese: "答应", pinyin: "dāyìng", wordType: "v.", meaning: "to agree, to promise" },
      { chinese: "损失", pinyin: "sǔnshī", wordType: "v.", meaning: "to lose" },
      { chinese: "睁", pinyin: "zhēng", wordType: "v.", meaning: "to open (one's eyes)" },
      {
        chinese: "眼睁睁",
        pinyin: "yǎnzhēngzhēng",
        wordType: "adj.",
        meaning: "(looking on) helplessly or indifferently",
      },
      {
        chinese: "将军",
        pinyin: "jiāngjūn",
        wordType: "n./v.",
        meaning: "(military) general; (in chess) to put one's king/general in check",
      },
      { chinese: "服气", pinyin: "fúqì", wordType: "v.", meaning: "to be convinced, to be won over" },
      { chinese: "运气", pinyin: "yùnqì", wordType: "n.", meaning: "luck, fortune" },
      { chinese: "局", pinyin: "jú", wordType: "m.", meaning: "game, set" },
      { chinese: "发挥", pinyin: "fāhuī", wordType: "v.", meaning: "to bring into play, to give rein to" },
      { chinese: "灰心", pinyin: "huīxīn", wordType: "adj.", meaning: "discouraged" },
      { chinese: "吸取", pinyin: "xīqǔ", wordType: "v.", meaning: "to absorb, to draw" },
      { chinese: "教训", pinyin: "jiàoxùn", wordType: "n.", meaning: "lesson, moral" },
      { chinese: "未必", pinyin: "wèibì", wordType: "adv.", meaning: "may not, not necessarily" },
      { chinese: "次要", pinyin: "cìyào", wordType: "adj.", meaning: "less important, secondary" },
      { chinese: "因素", pinyin: "yīnsù", wordType: "n.", meaning: "factor" },
      { chinese: "在于", pinyin: "zàiyú", wordType: "v.", meaning: "to lie in, to consist in" },
      { chinese: "心态", pinyin: "xīntài", wordType: "n.", meaning: "psychology, mental attitude" },
      { chinese: "珍惜", pinyin: "zhēnxī", wordType: "v.", meaning: "to cherish, to treasure" },
      { chinese: "否认", pinyin: "fǒurèn", wordType: "v.", meaning: "to deny, to disavow" },
      { chinese: "观察", pinyin: "guānchá", wordType: "v.", meaning: "to observe, to watch" },
      { chinese: "失去", pinyin: "shīqù", wordType: "v.", meaning: "to lose" },
      { chinese: "期间", pinyin: "qījiān", wordType: "n.", meaning: "time, period" },
      { chinese: "把握", pinyin: "bǎwò", wordType: "n.", meaning: "assurance, confidence" },
      {
        chinese: "不假思索",
        pinyin: "bùjiǎ-sīsuǒ",
        wordType: null,
        meaning: "without thinking or hesitation",
      },
      { chinese: "犯", pinyin: "fàn", wordType: "v.", meaning: "to commit (an error, a crime, etc.)" },
      { chinese: "过于", pinyin: "guòyú", wordType: "adv.", meaning: "too, excessively" },
      { chinese: "原则", pinyin: "yuánzé", wordType: "n.", meaning: "principle, tenet" },
      { chinese: "责备", pinyin: "zébèi", wordType: "v.", meaning: "to blame, to reproach" },
      { chinese: "必然", pinyin: "bìrán", wordType: "adj.", meaning: "inevitable, certain" },
      { chinese: "事先", pinyin: "shìxiān", wordType: "n.", meaning: "beforehand, in advance" },
      {
        chinese: "舍不得",
        pinyin: "shěbude",
        wordType: "v.",
        meaning: "to be unwilling to part with or give up, to grudge",
      },
      { chinese: "后果", pinyin: "hòuguǒ", wordType: "n.", meaning: "consequence, aftermath" },
      { chinese: "屡", pinyin: "lǚ", wordType: "adv.", meaning: "repeatedly, time and again" },
    ],
  },
  {
    chapterNumber: 28,
    words: [
      { chinese: "届", pinyin: "jiè", wordType: "m.", meaning: "session, year, class" },
      { chinese: "本科", pinyin: "běnkē", wordType: "n.", meaning: "undergraduate education" },
      { chinese: "面对", pinyin: "miànduì", wordType: "v.", meaning: "to face, to confront" },
      { chinese: "乐观", pinyin: "lèguān", wordType: "adj.", meaning: "optimistic" },
      { chinese: "就业", pinyin: "jiù yè", wordType: "v.", meaning: "to find employment" },
      { chinese: "实话", pinyin: "shíhuà", wordType: "n.", meaning: "truth, true words" },
      { chinese: "优势", pinyin: "yōushì", wordType: "n.", meaning: "superiority, advantage" },
      { chinese: "简历", pinyin: "jiǎnlì", wordType: "n.", meaning: "resume, CV" },
      { chinese: "现场", pinyin: "xiànchǎng", wordType: "n.", meaning: "site, spot" },
      { chinese: "职位", pinyin: "zhíwèi", wordType: "n.", meaning: "position, post" },
      { chinese: "体验", pinyin: "tǐyàn", wordType: "v.", meaning: "to feel and experience" },
      { chinese: "从此", pinyin: "cóngcǐ", wordType: "adv.", meaning: "from then on, since then" },
      { chinese: "范围", pinyin: "fànwéi", wordType: "n.", meaning: "scope, range" },
      { chinese: "初(级)中(学)", pinyin: "chū(jí) zhōng(xué)", wordType: "n.", meaning: "junior high school" },
      { chinese: "顾问", pinyin: "gùwèn", wordType: "n.", meaning: "consultant, adviser" },
      { chinese: "参考", pinyin: "cānkǎo", wordType: "v.", meaning: "to consult, to refer to" },
      { chinese: "成长", pinyin: "chéngzhǎng", wordType: "v.", meaning: "to grow up" },
      { chinese: "制作", pinyin: "zhìzuò", wordType: "v.", meaning: "to make, to produce" },
      { chinese: "才艺", pinyin: "cáiyì", wordType: "n.", meaning: "talent and skill" },
      { chinese: "假设", pinyin: "jiǎshè", wordType: "v.", meaning: "to suppose, to assume" },
      { chinese: "乘", pinyin: "chéng", wordType: "v.", meaning: "to ride, to travel by" },
      { chinese: "反应", pinyin: "fǎnyìng", wordType: "v.", meaning: "to respond, to react" },
      { chinese: "到达", pinyin: "dàodá", wordType: "v.", meaning: "to reach, to arrive" },
      { chinese: "老板", pinyin: "lǎobǎn", wordType: "n.", meaning: "boss, employer" },
      { chinese: "陆续", pinyin: "lùxù", wordType: "adv.", meaning: "one after another, in succession" },
      { chinese: "提问", pinyin: "tíwèn", wordType: "v.", meaning: "to ask a question" },
      { chinese: "堆", pinyin: "duī", wordType: "m.", meaning: "heap, pack, pile" },
      { chinese: "情侣", pinyin: "qínglǚ", wordType: "n.", meaning: "couple, lovers" },
      { chinese: "制订", pinyin: "zhìdìng", wordType: "v.", meaning: "to make, to draw up, to work out" },
      { chinese: "休闲", pinyin: "xiūxián", wordType: "v.", meaning: "to have leisure, to relax" },
      { chinese: "具体", pinyin: "jùtǐ", wordType: "adj.", meaning: "specific, detailed" },
      { chinese: "专注", pinyin: "zhuānzhù", wordType: "adj.", meaning: "concentrated, engrossed" },
      { chinese: "显然", pinyin: "xiǎnrán", wordType: "adj.", meaning: "obvious, evident" },
      { chinese: "成立", pinyin: "chénglì", wordType: "v.", meaning: "to establish, to set up" },
      { chinese: "部门", pinyin: "bùmén", wordType: "n.", meaning: "department, section" },
      { chinese: "执着", pinyin: "zhízhuó", wordType: "adj.", meaning: "persistent, persevering" },
      { chinese: "光明", pinyin: "guāngmíng", wordType: "adj.", meaning: "bright, promising" },
      { chinese: "前途", pinyin: "qiántú", wordType: "n.", meaning: "future, prospect" },
      { chinese: "行业", pinyin: "hángyè", wordType: "n.", meaning: "trade, profession, industry" },
      { chinese: "缺乏", pinyin: "quēfá", wordType: "v.", meaning: "to lack, to be short of" },
    ],
  },
  {
    chapterNumber: 29,
    words: [
      { chinese: "培养", pinyin: "péiyǎng", wordType: "v.", meaning: "to foster, to train" },
      { chinese: "对手", pinyin: "duìshǒu", wordType: "n.", meaning: "opponent, rival" },
      { chinese: "公寓", pinyin: "gōngyù", wordType: "n.", meaning: "apartment, flat" },
      { chinese: "文具", pinyin: "wénjù", wordType: "n.", meaning: "stationery" },
      { chinese: "电池", pinyin: "diànchí", wordType: "n.", meaning: "battery, cell" },
      {
        chinese: "日用品",
        pinyin: "rìyòngpǐn",
        wordType: "n.",
        meaning: "articles of everyday use, daily necessities",
      },
      { chinese: "利润", pinyin: "lìrùn", wordType: "n.", meaning: "profit" },
      { chinese: "诚信", pinyin: "chéngxìn", wordType: "adj.", meaning: "honest, in good faith" },
      { chinese: "媒体", pinyin: "méitǐ", wordType: "n.", meaning: "media, mass media" },
      { chinese: "对象", pinyin: "duìxiàng", wordType: "n.", meaning: "target, object" },
      { chinese: "营业", pinyin: "yíngyè", wordType: "v.", meaning: "to do business, to operate" },
      {
        chinese: "额",
        pinyin: "é",
        wordType: "n.",
        meaning: "specified number, sum, volume or amount",
      },
      { chinese: "不如", pinyin: "bùrú", wordType: "v.", meaning: "to be not as good as, to be inferior to" },
      { chinese: "干脆", pinyin: "gāncuì", wordType: "adv.", meaning: "simply, just" },
      { chinese: "挤", pinyin: "jī", wordType: "v.", meaning: "to squeeze out, to push out" },
      { chinese: "垮", pinyin: "kuǎ", wordType: "v.", meaning: "to collapse, to break down" },
      { chinese: "垄断", pinyin: "lǒngduàn", wordType: "v.", meaning: "to monopolize" },
      { chinese: "倒闭", pinyin: "dǎobì", wordType: "v.", meaning: "to close down, to go bankrupt" },
      { chinese: "热心", pinyin: "rèxīn", wordType: "adj.", meaning: "enthusiastic, earnest" },
      { chinese: "资金", pinyin: "zījīn", wordType: "n.", meaning: "capital, fund" },
      { chinese: "傻", pinyin: "shǎ", wordType: "adj.", meaning: "stupid, foolish" },
      { chinese: "倒霉", pinyin: "dǎo méi", wordType: "adj.", meaning: "having bad luck, unlucky" },
      { chinese: "生态", pinyin: "shēngtài", wordType: "n.", meaning: "ecology" },
      { chinese: "商业", pinyin: "shāngyè", wordType: "n.", meaning: "business, commerce" },
      { chinese: "领域", pinyin: "lǐngyù", wordType: "n.", meaning: "field, domain, realm" },
      { chinese: "适当", pinyin: "shìdàng", wordType: "adj.", meaning: "proper, adequate" },
      { chinese: "促使", pinyin: "cùshǐ", wordType: "v.", meaning: "to urge, to spur, to prompt" },
      { chinese: "生长", pinyin: "shēngzhǎng", wordType: "v.", meaning: "to grow" },
      { chinese: "妨碍", pinyin: "fáng'ài", wordType: "v.", meaning: "to hinder, to impede" },
      { chinese: "促进", pinyin: "cùjìn", wordType: "v.", meaning: "to promote, to accelerate" },
      { chinese: "利益", pinyin: "lìyì", wordType: "n.", meaning: "benefit, interest" },
      { chinese: "合理", pinyin: "hélǐ", wordType: "adj.", meaning: "reasonable" },
      { chinese: "万一", pinyin: "wànyī", wordType: "conj.", meaning: "in case, if by any chance" },
      { chinese: "维持", pinyin: "wéichí", wordType: "v.", meaning: "to keep, to maintain" },
      { chinese: "饱和", pinyin: "bǎohé", wordType: "v.", meaning: "to be saturated, to be filled to capacity" },
      {
        chinese: "不见得",
        pinyin: "bùjiàndé",
        wordType: "adv.",
        meaning: "not necessarily, may not",
      },
    ],
  },
  {
    chapterNumber: 30,
    words: [
      { chinese: "沙丁鱼", pinyin: "shādīngyú", wordType: "n.", meaning: "sardine" },
      { chinese: "运输", pinyin: "yùnshū", wordType: "v.", meaning: "to transport, to convey" },
      { chinese: "岸", pinyin: "àn", wordType: "n.", meaning: "bank (of a river, lake, etc.), shore, coast" },
      { chinese: "商品", pinyin: "shāngpǐn", wordType: "n.", meaning: "goods, commodity" },
      { chinese: "延长", pinyin: "yáncháng", wordType: "v.", meaning: "to prolong, to lengthen" },
      { chinese: "存活", pinyin: "cúnhuó", wordType: "v.", meaning: "to survive, to exist" },
      { chinese: "改善", pinyin: "gǎishàn", wordType: "v.", meaning: "to improve, to make sth. better" },
      { chinese: "无意", pinyin: "wúyì", wordType: "adv.", meaning: "accidentally, inadvertently" },
      { chinese: "巧妙", pinyin: "qiǎomiào", wordType: "adj.", meaning: "ingenious, clever" },
      { chinese: "实用", pinyin: "shíyòng", wordType: "adj.", meaning: "practical" },
      { chinese: "天敌", pinyin: "tiāndí", wordType: "n.", meaning: "natural enemy" },
      {
        chinese: "设备",
        pinyin: "shèbèi",
        wordType: "n.",
        meaning: "(referring to a container in this text) equipment, device",
      },
      { chinese: "和平", pinyin: "hépíng", wordType: "adj.", meaning: "peaceful" },
      { chinese: "构成", pinyin: "gòuchéng", wordType: "v.", meaning: "to compose, to form, to pose" },
      { chinese: "逃避", pinyin: "táobì", wordType: "v.", meaning: "to escape, to evade" },
      { chinese: "不断", pinyin: "búduàn", wordType: "adv.", meaning: "continuously, unceasingly" },
      { chinese: "旺盛", pinyin: "wàngshèng", wordType: "adj.", meaning: "exuberant, vibrant" },
      { chinese: "比例", pinyin: "bǐlì", wordType: "n.", meaning: "proportion, scale" },
      { chinese: "感想", pinyin: "gǎnxiǎng", wordType: "n.", meaning: "impressions, thoughts" },
      { chinese: "体会", pinyin: "tǐhuì", wordType: "n.", meaning: "feeling, understanding" },
      { chinese: "经济学", pinyin: "jīngjìxué", wordType: "n.", meaning: "economics" },
      { chinese: "概念", pinyin: "gàiniàn", wordType: "n.", meaning: "concept, notion" },
      { chinese: "核心", pinyin: "héxīn", wordType: "n.", meaning: "core, kernel" },
      { chinese: "刺激", pinyin: "cìjī", wordType: "v.", meaning: "to stimulate, to excite" },
      { chinese: "活力", pinyin: "huólì", wordType: "n.", meaning: "vigor, vitality" },
      { chinese: "落后", pinyin: "luòhòu", wordType: "v.", meaning: "to fall behind, to lag behind" },
      { chinese: "危机", pinyin: "wēijī", wordType: "n.", meaning: "crisis" },
      { chinese: "适度", pinyin: "shìdù", wordType: "adj.", meaning: "moderate, proper" },
      { chinese: "状态", pinyin: "zhuàngtài", wordType: "n.", meaning: "state, condition" },
      { chinese: "挖掘", pinyin: "wājué", wordType: "v.", meaning: "to dig, to unearth" },
      { chinese: "潜力", pinyin: "qiánlì", wordType: "n.", meaning: "potential" },
      { chinese: "决赛", pinyin: "juésài", wordType: "n.", meaning: "final, final match" },
      { chinese: "接近", pinyin: "jiējìn", wordType: "v.", meaning: "to approach, to be close to" },
      { chinese: "佳", pinyin: "jiā", wordType: "adj.", meaning: "good, fine" },
      { chinese: "的确", pinyin: "díquè", wordType: "adv.", meaning: "indeed, really" },
    ],
  },
  {
    chapterNumber: 31,
    words: [
      { chinese: "门槛", pinyin: "ménkǎn", wordType: "n.", meaning: "threshold" },
      { chinese: "报社", pinyin: "bàoshè", wordType: "n.", meaning: "newspaper office, headquarters of a newspaper" },
      { chinese: "编辑", pinyin: "biānjí", wordType: "n.", meaning: "editor" },
      { chinese: "嗯", pinyin: "ŋ", wordType: "int.", meaning: "used to indicate positive response" },
      { chinese: "轻易", pinyin: "qīngyì", wordType: "adj.", meaning: "easy, effortless" },
      { chinese: "处理", pinyin: "chǔlǐ", wordType: "v.", meaning: "to handle, to deal with" },
      { chinese: "社区", pinyin: "shèqū", wordType: "n.", meaning: "community" },
      { chinese: "劝", pinyin: "quàn", wordType: "v.", meaning: "to try to persuade" },
      { chinese: "圆", pinyin: "yuán", wordType: "adj.", meaning: "round, circular" },
      { chinese: "标志", pinyin: "biāozhì", wordType: "n.", meaning: "sign, mark" },
      { chinese: "出示", pinyin: "chūshì", wordType: "v.", meaning: "to show, to produce" },
      { chinese: "赞成", pinyin: "zànchéng", wordType: "v.", meaning: "to agree with, to approve of" },
      { chinese: "请愿书", pinyin: "qǐngyuànshū", wordType: "n.", meaning: "petition" },
      { chinese: "恋爱", pinyin: "liàn'ài", wordType: "n.", meaning: "(romantic) love" },
      { chinese: "迫切", pinyin: "pòqiè", wordType: "adj.", meaning: "urgent, pressing, eager" },
      { chinese: "犹豫", pinyin: "yóuyù", wordType: "adj.", meaning: "hesitant" },
      { chinese: "冷淡", pinyin: "lěngdàn", wordType: "adj.", meaning: "cold, indifferent" },
      {
        chinese: "无所谓",
        pinyin: "wúsuǒwèi",
        wordType: "v.",
        meaning: "to not care, to not mind, to not take seriously",
      },
      { chinese: "值班", pinyin: "zhí bān", wordType: "v.", meaning: "to be on duty or shift" },
      { chinese: "报告", pinyin: "bàogào", wordType: "n.", meaning: "report" },
      {
        chinese: "八成(儿)",
        pinyin: "bāchéng(r)",
        wordType: "adv.",
        meaning: "most probably, most likely; eighty percent",
      },
      { chinese: "模糊", pinyin: "móhu", wordType: "adj.", meaning: "blurred, indistinct, vague" },
      { chinese: "狡猾", pinyin: "jiǎohuá", wordType: "adj.", meaning: "crafty, cunning" },
      { chinese: "了不起", pinyin: "liǎobuqǐ", wordType: "adj.", meaning: "great, amazing" },
      { chinese: "身段", pinyin: "shēnduàn", wordType: "n.", meaning: "posture, manner, attitude" },
      { chinese: "缩短", pinyin: "suōduǎn", wordType: "v.", meaning: "to shorten" },
      { chinese: "看不起", pinyin: "kànbuqǐ", wordType: "v.", meaning: "to look down upon, to despise" },
      { chinese: "谦虚", pinyin: "qiānxū", wordType: "adj.", meaning: "modest" },
      { chinese: "实践", pinyin: "shíjiàn", wordType: "v.", meaning: "to put into practice" },
    ],
  },
  {
    chapterNumber: 32,
    words: [
      { chinese: "消失", pinyin: "xiāoshī", wordType: "v.", meaning: "to disappear, to vanish" },
      { chinese: "洪水", pinyin: "hóngshuǐ", wordType: "n.", meaning: "flood" },
      { chinese: "地震", pinyin: "dìzhèn", wordType: "n.", meaning: "earthquake" },
      { chinese: "破坏", pinyin: "pòhuài", wordType: "v.", meaning: "to destroy, to damage" },
      { chinese: "砍", pinyin: "kǎn", wordType: "v.", meaning: "to cut, to chop, to fell" },
      { chinese: "生存", pinyin: "shēngcún", wordType: "v.", meaning: "to live, to subsist" },
      { chinese: "沙漠", pinyin: "shāmò", wordType: "n.", meaning: "desert" },
      { chinese: "公布", pinyin: "gōngbù", wordType: "v.", meaning: "to announce, to make public" },
      { chinese: "数据", pinyin: "shùjù", wordType: "n.", meaning: "data" },
      { chinese: "真实", pinyin: "zhēnshí", wordType: "adj.", meaning: "real, actual" },
      { chinese: "夸张", pinyin: "kuāzhāng", wordType: "adj.", meaning: "exaggerated" },
      { chinese: "资源", pinyin: "zīyuán", wordType: "n.", meaning: "resource" },
      { chinese: "车祸", pinyin: "chēhuò", wordType: "n.", meaning: "traffic accident" },
      { chinese: "不安", pinyin: "bù'ān", wordType: "adj.", meaning: "upset, disturbed" },
      { chinese: "工业", pinyin: "gōngyè", wordType: "n.", meaning: "industry" },
      { chinese: "农业", pinyin: "nóngyè", wordType: "n.", meaning: "agriculture" },
      { chinese: "生产", pinyin: "shēngchǎn", wordType: "v.", meaning: "to produce, to manufacture" },
      { chinese: "大型", pinyin: "dàxíng", wordType: "adj.", meaning: "large-scale" },
      { chinese: "工厂", pinyin: "gōngchǎng", wordType: "n.", meaning: "factory" },
      { chinese: "废", pinyin: "fèi", wordType: "adj.", meaning: "waste, useless" },
      { chinese: "燃烧", pinyin: "ránshāo", wordType: "v.", meaning: "to burn, to combust" },
      { chinese: "煤炭", pinyin: "méitàn", wordType: "n.", meaning: "coal" },
      { chinese: "密切", pinyin: "mìqiè", wordType: "adj.", meaning: "close, intimate" },
      { chinese: "尾气", pinyin: "wěiqì", wordType: "n.", meaning: "exhaust gas, vehicle emission" },
      { chinese: "幸运", pinyin: "xìngyùn", wordType: "adj.", meaning: "lucky, fortunate" },
      { chinese: "敏感", pinyin: "mǐngǎn", wordType: "adj.", meaning: "sensitive, susceptible" },
      { chinese: "自觉", pinyin: "zìjué", wordType: "adj.", meaning: "conscious, on one's own initiative" },
      { chinese: "设施", pinyin: "shèshī", wordType: "n.", meaning: "installation, facilities" },
      { chinese: "能源", pinyin: "néngyuán", wordType: "n.", meaning: "energy resource" },
      { chinese: "逐步", pinyin: "zhúbù", wordType: "adv.", meaning: "gradually, step by step" },
      {
        chinese: "尽量",
        pinyin: "jǐnliàng",
        wordType: "adv.",
        meaning: "to the best of one's abilities, to the greatest extent",
      },
      { chinese: "私(人)", pinyin: "sī(rén)", wordType: "n.", meaning: "private" },
      { chinese: "尊敬", pinyin: "zūnjìng", wordType: "v.", meaning: "to respect, to esteem" },
      { chinese: "鼓舞", pinyin: "gǔwǔ", wordType: "v.", meaning: "to encourage, to inspire" },
      { chinese: "消极", pinyin: "xiāojí", wordType: "adj.", meaning: "passive, inactive" },
      { chinese: "幻想", pinyin: "huànxiǎng", wordType: "n.", meaning: "fantasy, illusion" },
      {
        chinese: "贡献",
        pinyin: "gòngxiàn",
        wordType: "n./v.",
        meaning: "contribution; to contribute, to devote",
      },
      { chinese: "命运", pinyin: "mìngyùn", wordType: "n.", meaning: "fate, destiny" },
      { chinese: "掌握", pinyin: "zhǎngwò", wordType: "v.", meaning: "to take charge of, to control" },
    ],
  },
  {
    chapterNumber: 33,
    words: [
      { chinese: "缓解", pinyin: "huǎnjiě", wordType: "v.", meaning: "to alleviate, to ease up" },
      { chinese: "招(儿)", pinyin: "zhāo(r)", wordType: "n.", meaning: "trick, move, method" },
      { chinese: "繁荣", pinyin: "fánróng", wordType: "adj.", meaning: "prosperous, thriving" },
      { chinese: "体现", pinyin: "tǐxiàn", wordType: "v.", meaning: "to manifest, to reflect" },
      { chinese: "拥挤", pinyin: "yōngjǐ", wordType: "adj.", meaning: "crowded, congested" },
      { chinese: "家常", pinyin: "jiācháng", wordType: "n.", meaning: "daily life of a family" },
      { chinese: "面积", pinyin: "miànjī", wordType: "n.", meaning: "area, space" },
      { chinese: "宽", pinyin: "kuān", wordType: "adj.", meaning: "wide, broad" },
      { chinese: "主观", pinyin: "zhǔguān", wordType: "adj.", meaning: "subjective" },
      { chinese: "扩(大)", pinyin: "kuò(dà)", wordType: "v.", meaning: "to enlarge, to expand, to broaden" },
      { chinese: "根治", pinyin: "gēnzhì", wordType: "v.", meaning: "to cure once and for all" },
      { chinese: "不妨", pinyin: "bùfáng", wordType: "adv.", meaning: "might as well" },
      { chinese: "展开", pinyin: "zhǎnkāi", wordType: "v.", meaning: "to launch, to set off, to carry out" },
      { chinese: "归纳", pinyin: "guīnà", wordType: "v.", meaning: "to infer, to sum up" },
      { chinese: "虚心", pinyin: "xūxīn", wordType: "adj.", meaning: "open-minded, modest" },
      { chinese: "咨询", pinyin: "zīxún", wordType: "v.", meaning: "to consult, to seek advice" },
      { chinese: "中旬", pinyin: "zhōngxún", wordType: "n.", meaning: "middle ten days of a month" },
      { chinese: "照常", pinyin: "zhàocháng", wordType: "adv.", meaning: "as usual" },
      { chinese: "健身", pinyin: "jiànshēn", wordType: "v.", meaning: "to keep fit, to work out" },
      { chinese: "图", pinyin: "tú", wordType: "v.", meaning: "to covet, to be after" },
      { chinese: "受(伤)", pinyin: "shòu(shāng)", wordType: "v.", meaning: "to be hurt, to be injured" },
      { chinese: "保险", pinyin: "bǎoxiǎn", wordType: "n.", meaning: "insurance" },
      { chinese: "赔偿", pinyin: "péicháng", wordType: "v.", meaning: "to compensate, to indemnify" },
      { chinese: "政府", pinyin: "zhèngfǔ", wordType: "n.", meaning: "government" },
      { chinese: "批准", pinyin: "pīzhǔn", wordType: "v.", meaning: "to ratify, to approve" },
      { chinese: "改革", pinyin: "gǎigé", wordType: "v.", meaning: "to reform" },
      { chinese: "取消", pinyin: "qǔxiāo", wordType: "v.", meaning: "to cancel, to call off" },
      { chinese: "行人", pinyin: "xíngrén", wordType: "n.", meaning: "pedestrian" },
      { chinese: "广场", pinyin: "guǎngchǎng", wordType: "n.", meaning: "square, plaza" },
      { chinese: "商务", pinyin: "shāngwù", wordType: "n.", meaning: "business affairs" },
      { chinese: "大厦", pinyin: "dàshà", wordType: "n.", meaning: "large building, mansion" },
      { chinese: "自愿", pinyin: "zìyuàn", wordType: "adj.", meaning: "voluntary" },
      { chinese: "难怪", pinyin: "nánguài", wordType: "v.", meaning: "to be understandable, to be reasonable" },
      { chinese: "与其", pinyin: "yǔqí", wordType: "conj.", meaning: "(would rather...) than, rather than" },
      { chinese: "汽油", pinyin: "qìyóu", wordType: "n.", meaning: "gasoline" },
      { chinese: "明确", pinyin: "míngquè", wordType: "adj.", meaning: "clear and definite, explicit" },
      { chinese: "期待", pinyin: "qīdài", wordType: "v.", meaning: "to look forward to" },
      { chinese: "解放", pinyin: "jiěfàng", wordType: "v.", meaning: "to liberate, to free" },
    ],
  },
  {
    chapterNumber: 34,
    words: [
      { chinese: "接触", pinyin: "jiēchù", wordType: "v.", meaning: "to contact, to get in touch with" },
      { chinese: "特征", pinyin: "tèzhēng", wordType: "n.", meaning: "feature, characteristic" },
      { chinese: "翅膀", pinyin: "chìbǎng", wordType: "n.", meaning: "wing" },
      { chinese: "昆虫", pinyin: "kūnchóng", wordType: "n.", meaning: "insect" },
      { chinese: "天空", pinyin: "tiānkōng", wordType: "n.", meaning: "sky" },
      { chinese: "区分", pinyin: "qūfēn", wordType: "v.", meaning: "to distinguish, to differentiate" },
      { chinese: "唯一", pinyin: "wéiyī", wordType: "adj.", meaning: "only, sole" },
      { chinese: "斑", pinyin: "bān", wordType: "n.", meaning: "spot, speckle, stripe" },
      { chinese: "充当", pinyin: "chōngdāng", wordType: "v.", meaning: "to serve as, to play the part of" },
      { chinese: "总之", pinyin: "zǒngzhī", wordType: "conj.", meaning: "in short, in brief" },
      { chinese: "角色", pinyin: "juésè", wordType: "n.", meaning: "role, part" },
      { chinese: "爱惜", pinyin: "àixī", wordType: "v.", meaning: "to cherish, to treasure" },
      { chinese: "保养", pinyin: "bǎoyǎng", wordType: "v.", meaning: "to take good care of, to maintain" },
      { chinese: "反复", pinyin: "fǎnfù", wordType: "adv.", meaning: "repeatedly, over and over again" },
      { chinese: "啄", pinyin: "zhuó", wordType: "v.", meaning: "to peck" },
      {
        chinese: "随身",
        pinyin: "suíshēn",
        wordType: "adj.",
        meaning: "(to carry/take...) with one, personally",
      },
      { chinese: "梳子", pinyin: "shūzi", wordType: "n.", meaning: "comb" },
      { chinese: "光滑", pinyin: "guānghuá", wordType: "adj.", meaning: "smooth, glossy" },
      { chinese: "抓", pinyin: "zhuā", wordType: "v.", meaning: "to grab, to seize" },
      {
        chinese: "寄生",
        pinyin: "jìshēng",
        wordType: "v.",
        meaning: "to live on another animal or plant, to be parasitic",
      },
      { chinese: "肥皂", pinyin: "féizào", wordType: "n.", meaning: "soap" },
      { chinese: "种类", pinyin: "zhǒnglèi", wordType: "n.", meaning: "kind, category" },
      {
        chinese: "概括",
        pinyin: "gàikuò",
        wordType: "adj./v.",
        meaning: "brief and to the point; to summarize, to sum up",
      },
      { chinese: "岛屿", pinyin: "dǎoyǔ", wordType: "n.", meaning: "island" },
      { chinese: "知更鸟", pinyin: "zhīgēngniǎo", wordType: "n.", meaning: "robin, redbreast" },
      { chinese: "坑", pinyin: "kēng", wordType: "n.", meaning: "pit, hollow" },
      { chinese: "池塘", pinyin: "chítáng", wordType: "n.", meaning: "pond" },
      { chinese: "老鹰", pinyin: "lǎoyīng", wordType: "n.", meaning: "eagle, hawk" },
      { chinese: "痛快", pinyin: "tòngkuài", wordType: "adj.", meaning: "to one's heart's content" },
      { chinese: "迎接", pinyin: "yíngjiē", wordType: "v.", meaning: "to receive, to greet, to welcome" },
      { chinese: "洗礼", pinyin: "xǐlǐ", wordType: "n.", meaning: "baptism, washing ceremony" },
      { chinese: "沙子", pinyin: "shāzi", wordType: "n.", meaning: "sand" },
      { chinese: "干燥", pinyin: "gānzào", wordType: "adj.", meaning: "dry, arid" },
      { chinese: "秘密", pinyin: "mìmì", wordType: "adj./n.", meaning: "secret" },
    ],
  },
  {
    chapterNumber: 35,
    words: [
      { chinese: "炎热", pinyin: "yánrè", wordType: "adj.", meaning: "scorching, burning hot" },
      { chinese: "歇", pinyin: "xiē", wordType: "v.", meaning: "to rest, to take a rest" },
      { chinese: "开水", pinyin: "kāishuǐ", wordType: "n.", meaning: "boiled water" },
      { chinese: "冰激凌", pinyin: "bīngjīlíng", wordType: "n.", meaning: "ice cream" },
      { chinese: "肌肉", pinyin: "jīròu", wordType: "n.", meaning: "muscle" },
      { chinese: "恢复", pinyin: "huīfù", wordType: "v.", meaning: "to recover, to regain" },
      { chinese: "湿润", pinyin: "shīrùn", wordType: "adj.", meaning: "moist, humid" },
      { chinese: "荫凉", pinyin: "yīnliáng", wordType: "adj.", meaning: "shady and cool" },
      { chinese: "指挥", pinyin: "zhǐhuī", wordType: "v.", meaning: "to command, to direct" },
      { chinese: "赶快", pinyin: "gǎnkuài", wordType: "adv.", meaning: "at once, hurriedly" },
      { chinese: "汗腺", pinyin: "hànxiàn", wordType: "n.", meaning: "sweat gland" },
      { chinese: "毛孔", pinyin: "máokǒng", wordType: "n.", meaning: "pore" },
      { chinese: "冒", pinyin: "mào", wordType: "v.", meaning: "to emit, to give off, to send out" },
      { chinese: "片", pinyin: "piàn", wordType: "n.", meaning: "flat and thin piece" },
      { chinese: "常识", pinyin: "chángshí", wordType: "n.", meaning: "common knowledge" },
      { chinese: "根", pinyin: "gēn", wordType: "n.", meaning: "root" },
      { chinese: "吸收", pinyin: "xīshōu", wordType: "v.", meaning: "to absorb, to take in" },
      { chinese: "控制", pinyin: "kòngzhì", wordType: "v.", meaning: "to control, to take command of" },
      { chinese: "成分", pinyin: "chéngfèn", wordType: "n.", meaning: "element, component, ingredient" },
      { chinese: "梢", pinyin: "shāo", wordType: "n.", meaning: "tip, thin end of a twig, etc." },
      { chinese: "管子", pinyin: "guǎnzi", wordType: "n.", meaning: "tube, pipe" },
      { chinese: "玻璃", pinyin: "bōli", wordType: "n.", meaning: "glass" },
      { chinese: "测验", pinyin: "cèyàn", wordType: "v.", meaning: "to test" },
      {
        chinese: "根本",
        pinyin: "gēnběn",
        wordType: "adv.",
        meaning: "(often used in the negative) at all, simply",
      },
      { chinese: "枝干", pinyin: "zhīgàn", wordType: "n.", meaning: "branch, limb" },
      { chinese: "释放", pinyin: "shìfàng", wordType: "v.", meaning: "to release, to emit" },
      { chinese: "自动", pinyin: "zìdòng", wordType: "adv.", meaning: "voluntarily, spontaneously" },
      { chinese: "补充", pinyin: "bǔchōng", wordType: "v.", meaning: "to supplement, to replenish" },
      { chinese: "抽", pinyin: "chōu", wordType: "v.", meaning: "to draw, to obtain by drawing" },
      { chinese: "蒸腾", pinyin: "zhēngténg", wordType: "v.", meaning: "(of steam) to rise, to vaporize" },
      { chinese: "特殊", pinyin: "tèshū", wordType: "adj.", meaning: "special, particular" },
      { chinese: "内部", pinyin: "nèibù", wordType: "n.", meaning: "inside, interior, inner part" },
      { chinese: "系统", pinyin: "xìtǒng", wordType: "n.", meaning: "system" },
      { chinese: "状况", pinyin: "zhuàngkuàng", wordType: "n.", meaning: "condition, situation, state" },
      { chinese: "秩序", pinyin: "zhìxù", wordType: "n.", meaning: "order, orderly state" },
    ],
  },
  {
    chapterNumber: 36,
    words: [
      { chinese: "养", pinyin: "yǎng", wordType: "v.", meaning: "to raise, to keep, to grow" },
      { chinese: "除非", pinyin: "chúfēi", wordType: "conj.", meaning: "only if, unless" },
      { chinese: "奋斗", pinyin: "fèndòu", wordType: "v.", meaning: "to fight, to struggle, to strive" },
      { chinese: "乐趣", pinyin: "lèqù", wordType: "n.", meaning: "joy, pleasure" },
      { chinese: "在乎", pinyin: "zàihu", wordType: "v.", meaning: "to care, to mind" },
      { chinese: "朵", pinyin: "duǒ", wordType: "m.", meaning: "used for flowers and clouds" },
      { chinese: "剪刀", pinyin: "jiǎndāo", wordType: "n.", meaning: "scissors" },
      { chinese: "捡", pinyin: "jiǎn", wordType: "v.", meaning: "to pick up, to collect" },
      { chinese: "装饰", pinyin: "zhuāngshì", wordType: "n.", meaning: "decoration" },
      { chinese: "结合", pinyin: "jiéhé", wordType: "v.", meaning: "to combine, to integrate" },
      { chinese: "暴雨", pinyin: "bàoyǔ", wordType: "n.", meaning: "rainstorm" },
      { chinese: "紧急", pinyin: "jǐnjí", wordType: "adj.", meaning: "urgent, emergent" },
      { chinese: "劳驾", pinyin: "láojià", wordType: "v.", meaning: "to trouble sb. (to do sth.)" },
      { chinese: "抢救", pinyin: "qiǎngjiù", wordType: "v.", meaning: "to rescue, to save" },
      { chinese: "腰", pinyin: "yāo", wordType: "n.", meaning: "waist" },
      { chinese: "直", pinyin: "zhí", wordType: "adv.", meaning: "continuously, straight" },
      { chinese: "不然", pinyin: "bùrán", wordType: "conj.", meaning: "or else, otherwise" },
      { chinese: "回报", pinyin: "huíbào", wordType: "v.", meaning: "to repay, to requite" },
      { chinese: "真理", pinyin: "zhēnlǐ", wordType: "n.", meaning: "truth" },
      { chinese: "浇", pinyin: "jiāo", wordType: "v.", meaning: "to water, to pour (liquid on sth.)" },
      { chinese: "潮湿", pinyin: "cháoshī", wordType: "adj.", meaning: "wet, moist" },
      { chinese: "施肥", pinyin: "shī féi", wordType: "v.", meaning: "to apply fertilizer" },
      { chinese: "熟练", pinyin: "shúliàn", wordType: "adj.", meaning: "skilled, practiced" },
      { chinese: "应付", pinyin: "yìngfu", wordType: "v.", meaning: "to handle, to cope with" },
      { chinese: "鲜艳", pinyin: "xiānyàn", wordType: "adj.", meaning: "bright-colored" },
      { chinese: "自豪", pinyin: "zìháo", wordType: "adj.", meaning: "proud" },
      { chinese: "吹", pinyin: "chuī", wordType: "v.", meaning: "to boast, to brag" },
      { chinese: "爱心", pinyin: "àixīn", wordType: "n.", meaning: "love, compassion" },
      {
        chinese: "分享",
        pinyin: "fēnxiǎng",
        wordType: "v.",
        meaning: "to share (good things such as joy and rights)",
      },
      { chinese: "昙花", pinyin: "tánhuā", wordType: "n.", meaning: "broad-leaved epiphyllum" },
      { chinese: "庆祝", pinyin: "qìngzhù", wordType: "v.", meaning: "to celebrate" },
      { chinese: "保留", pinyin: "bǎoliú", wordType: "v.", meaning: "to reserve, to save" },
      { chinese: "菊花", pinyin: "júhuā", wordType: "n.", meaning: "chrysanthemum" },
      { chinese: "砸", pinyin: "zá", wordType: "v.", meaning: "to crush, to smash" },
      { chinese: "悲(伤)", pinyin: "bēi(shāng)", wordType: "adj.", meaning: "sad, sorrowful" },
      {
        chinese: "反正",
        pinyin: "fǎnzhèng",
        wordType: "adv.",
        meaning:
          "(used to indicate the same result despite different circumstances) anyway, no matter what",
      },
      { chinese: "热爱", pinyin: "rè'ài", wordType: "v.", meaning: "to love ardently" },
    ],
  },
];
