// HSK5A's per-lesson chapter data, transcribed directly from Part 1 of the
// HSK 5 (上册) Standard Course textbook's "生词 New Words" lists, the same
// way HSK4A's/HSK4B's are. Each lesson's 专有名词 Proper Nouns section is
// deliberately excluded — see the no-proper-nouns rule in project memory.
export interface Hsk5aWordData {
  chinese: string;
  pinyin: string;
  wordType: string | null;
  meaning: string;
}

export interface Hsk5aChapterData {
  chapterNumber: number;
  words: Hsk5aWordData[];
}

export const HSK5A_CHAPTERS: Hsk5aChapterData[] = [
  {
    chapterNumber: 1,
    words: [
      { chinese: "细节", pinyin: "xìjié", wordType: "n.", meaning: "detail" },
      { chinese: "电台", pinyin: "diàntái", wordType: "n.", meaning: "radio station" },
      { chinese: "恩爱", pinyin: "ēn'ài", wordType: "adj.", meaning: "(of husband and wife) loving" },
      { chinese: "对比", pinyin: "duìbǐ", wordType: "v.", meaning: "to compare, to contrast" },
      { chinese: "入围", pinyin: "rùwéi", wordType: "v.", meaning: "to be shortlisted" },
      { chinese: "评委", pinyin: "píngwěi", wordType: "n.", meaning: "judge, member of a judging panel" },
      { chinese: "如何", pinyin: "rúhé", wordType: "pron.", meaning: "how" },
      { chinese: "瘫痪", pinyin: "tānhuàn", wordType: "v.", meaning: "to be paralyzed" },
      { chinese: "离婚", pinyin: "lí hūn", wordType: "v.", meaning: "to divorce" },
      { chinese: "自杀", pinyin: "zìshā", wordType: "v.", meaning: "to commit suicide" },
      { chinese: "抱怨", pinyin: "bàoyuàn", wordType: "v.", meaning: "to complain" },
      { chinese: "爱护", pinyin: "àihù", wordType: "v.", meaning: "to take good care of" },
      { chinese: "婚姻", pinyin: "hūnyīn", wordType: "n.", meaning: "marriage" },
      { chinese: "吵架", pinyin: "chǎo jià", wordType: "v.", meaning: "to quarrel" },
      {
        chinese: "相敬如宾",
        pinyin: "xiāngjìng rúbīn",
        wordType: null,
        meaning: "(of husband and wife) to respect each other like guests",
      },
      { chinese: "暗暗", pinyin: "àn'àn", wordType: "adv.", meaning: "secretly, to oneself" },
      { chinese: "轮", pinyin: "lún", wordType: "v.", meaning: "to take turns" },
      { chinese: "不耐烦", pinyin: "bú nàifán", wordType: null, meaning: "impatient" },
      { chinese: "靠", pinyin: "kào", wordType: "v.", meaning: "to lean against" },
      { chinese: "肩膀", pinyin: "jiānbǎng", wordType: "n.", meaning: "shoulder" },
      { chinese: "喊", pinyin: "hǎn", wordType: "v.", meaning: "to shout, to call" },
      { chinese: "伸", pinyin: "shēn", wordType: "v.", meaning: "to stretch, to extend" },
      { chinese: "手指", pinyin: "shǒuzhǐ", wordType: "n.", meaning: "finger" },
      { chinese: "歪歪扭扭", pinyin: "wāiwāiniǔniǔ", wordType: "adj.", meaning: "crooked, askew" },
      { chinese: "递", pinyin: "dì", wordType: "v.", meaning: "to hand over, to pass" },
      { chinese: "脑袋", pinyin: "nǎodai", wordType: "n.", meaning: "head" },
      { chinese: "女士", pinyin: "nǚshì", wordType: "n.", meaning: "lady, madam" },
      { chinese: "叙述", pinyin: "xùshù", wordType: "v.", meaning: "to narrate" },
      { chinese: "居然", pinyin: "jūrán", wordType: "adv.", meaning: "indicating unexpectedness" },
      { chinese: "催", pinyin: "cuī", wordType: "v.", meaning: "to urge, to push" },
      { chinese: "等待", pinyin: "děngdài", wordType: "v.", meaning: "to wait" },
      { chinese: "蚊子", pinyin: "wénzi", wordType: "n.", meaning: "mosquito" },
      { chinese: "半夜", pinyin: "bànyè", wordType: "n.", meaning: "midnight" },
      { chinese: "叮", pinyin: "dīng", wordType: "v.", meaning: "to bite, to sting" },
      { chinese: "老婆", pinyin: "lǎopo", wordType: "n.", meaning: "wife" },
      { chinese: "吵", pinyin: "chǎo", wordType: "v./adj.", meaning: "to make a noise; noisy" },
      { chinese: "项", pinyin: "xiàng", wordType: "m.", meaning: "used for itemized things" },
      { chinese: "患难与共", pinyin: "huànnàn yǔgòng", wordType: null, meaning: "to share weal and woe" },
    ],
  },
  {
    chapterNumber: 2,
    words: [
      { chinese: "串", pinyin: "chuàn", wordType: "m.", meaning: "bunch, string" },
      { chinese: "一辈子", pinyin: "yíbèizi", wordType: "n.", meaning: "all one's life" },
      { chinese: "农村", pinyin: "nóngcūn", wordType: "n.", meaning: "countryside" },
      { chinese: "屋(子)", pinyin: "wū(zi)", wordType: "n.", meaning: "house" },
      { chinese: "断", pinyin: "duàn", wordType: "v.", meaning: "to cut off, to stop" },
      { chinese: "以来", pinyin: "yǐlái", wordType: "n.", meaning: "since" },
      { chinese: "姥姥", pinyin: "lǎolao", wordType: "n.", meaning: "maternal grandma" },
      { chinese: "舅舅", pinyin: "jiùjiu", wordType: "n.", meaning: "uncle, mother's brother" },
      { chinese: "姑姑", pinyin: "gūgu", wordType: "n.", meaning: "aunt, father's sister" },
      { chinese: "坚决", pinyin: "jiānjué", wordType: "adj.", meaning: "resolute, determined" },
      { chinese: "打工", pinyin: "dǎ gōng", wordType: "v.", meaning: "to work for others, to do a temporary job" },
      { chinese: "挣", pinyin: "zhèng", wordType: "v.", meaning: "to earn" },
      { chinese: "县", pinyin: "xiàn", wordType: "n.", meaning: "county" },
      { chinese: "套", pinyin: "tào", wordType: "m.", meaning: "set, suite" },
      { chinese: "装修", pinyin: "zhuāngxiū", wordType: "v.", meaning: "to decorate (a house, room, etc.)" },
      { chinese: "不得了", pinyin: "bùdéliǎo", wordType: "adj.", meaning: "extremely, exceedingly" },
      { chinese: "醉", pinyin: "zuì", wordType: "v.", meaning: "to be drunk" },
      { chinese: "强烈", pinyin: "qiángliè", wordType: "adj.", meaning: "strong and vehement" },
      { chinese: "夜", pinyin: "yè", wordType: "n.", meaning: "night" },
      { chinese: "锁", pinyin: "suǒ", wordType: "n./v.", meaning: "lock; to lock up" },
      { chinese: "临", pinyin: "lín", wordType: "prep.", meaning: "about to, just before" },
      { chinese: "悄悄", pinyin: "qiāoqiāo", wordType: "adv.", meaning: "quietly, secretly" },
      { chinese: "晒", pinyin: "shài", wordType: "v.", meaning: "to dry in the sun" },
      { chinese: "被子", pinyin: "bèizi", wordType: "n.", meaning: "quilt" },
      { chinese: "长途", pinyin: "chángtú", wordType: "adj.", meaning: "long-distance" },
      { chinese: "冻", pinyin: "dòng", wordType: "v.", meaning: "to freeze, to feel very cold" },
      { chinese: "想象", pinyin: "xiǎngxiàng", wordType: "v.", meaning: "to imagine" },
      { chinese: "灰尘", pinyin: "huīchén", wordType: "n.", meaning: "dust, dirt" },
      { chinese: "亮", pinyin: "liàng", wordType: "adj./v.", meaning: "bright; to shine" },
      { chinese: "微笑", pinyin: "wēixiào", wordType: "v./n.", meaning: "to smile; smile" },
      { chinese: "温暖", pinyin: "wēnnuǎn", wordType: "adj./v.", meaning: "warm; to make sb./sth. warm" },
      { chinese: "立刻", pinyin: "lìkè", wordType: "adv.", meaning: "at once, immediately" },
      { chinese: "扑", pinyin: "pū", wordType: "v.", meaning: "to pounce on, to dash at" },
      { chinese: "卧室", pinyin: "wòshì", wordType: "n.", meaning: "bedroom" },
      { chinese: "铺", pinyin: "pū", wordType: "v.", meaning: "to spread, to unfold" },
      { chinese: "飘", pinyin: "piāo", wordType: "v.", meaning: "to float (in the air), to waft" },
      {
        chinese: "阵",
        pinyin: "zhèn",
        wordType: "m.",
        meaning: "used for a short period or spell of an occurrence or action",
      },
      { chinese: "感受", pinyin: "gǎnshòu", wordType: "v./n.", meaning: "to feel; feeling" },
      { chinese: "流泪", pinyin: "liú lèi", wordType: "v.", meaning: "to shed tears" },
    ],
  },
  {
    chapterNumber: 3,
    words: [
      { chinese: "人生", pinyin: "rénshēng", wordType: "n.", meaning: "life" },
      { chinese: "工人", pinyin: "gōngrén", wordType: "n.", meaning: "worker" },
      { chinese: "稳定", pinyin: "wěndìng", wordType: "adj.", meaning: "stable" },
      { chinese: "待遇", pinyin: "dàiyù", wordType: "n.", meaning: "pay and perks" },
      { chinese: "发愁", pinyin: "fā chóu", wordType: "v.", meaning: "to worry" },
      { chinese: "平静", pinyin: "píngjìng", wordType: "adj.", meaning: "quiet, peaceful" },
      { chinese: "帆船", pinyin: "fānchuán", wordType: "n.", meaning: "sailing boat/ship" },
      { chinese: "撞", pinyin: "zhuàng", wordType: "v.", meaning: "to bump against" },
      { chinese: "艘", pinyin: "sōu", wordType: "m.", meaning: "used for boats/ships" },
      { chinese: "航行", pinyin: "hángxíng", wordType: "v.", meaning: "to sail, to navigate by air or water" },
      { chinese: "积蓄", pinyin: "jīxù", wordType: "n./v.", meaning: "savings; to save" },
      { chinese: "二手", pinyin: "èrshǒu", wordType: "adj.", meaning: "second-hand" },
      { chinese: "彩虹", pinyin: "cǎihóng", wordType: "n.", meaning: "rainbow" },
      { chinese: "包括", pinyin: "bāokuò", wordType: "v.", meaning: "to include" },
      { chinese: "疯", pinyin: "fēng", wordType: "v.", meaning: "to be crazy, to go mad" },
      { chinese: "辞职", pinyin: "cí zhí", wordType: "v.", meaning: "to quit a job" },
      { chinese: "驾驶", pinyin: "jiàshǐ", wordType: "v.", meaning: "to drive, to pilot" },
      { chinese: "轮流", pinyin: "lúnliú", wordType: "v.", meaning: "to take turns" },
      { chinese: "钓", pinyin: "diào", wordType: "v.", meaning: "to fish with a hook and line" },
      { chinese: "顿", pinyin: "dùn", wordType: "m.", meaning: "used for meals" },
      { chinese: "海鲜", pinyin: "hǎixiān", wordType: "n.", meaning: "seafood" },
      { chinese: "傍晚", pinyin: "bàngwǎn", wordType: "n.", meaning: "towards evening, at dusk" },
      { chinese: "舒适", pinyin: "shūshì", wordType: "adj.", meaning: "comfortable, cozy" },
      { chinese: "干活儿", pinyin: "gàn huór", wordType: "v.", meaning: "to work" },
      { chinese: "盼望", pinyin: "pànwàng", wordType: "v.", meaning: "to look forward to" },
      { chinese: "陆地", pinyin: "lùdì", wordType: "n.", meaning: "land" },
      { chinese: "各自", pinyin: "gèzì", wordType: "pron.", meaning: "each, respective" },
      { chinese: "勿", pinyin: "wù", wordType: "adv.", meaning: "(used in imperative sentences) don't" },
      { chinese: "时刻", pinyin: "shíkè", wordType: "n.", meaning: "moment" },
      { chinese: "着火", pinyin: "zháo huǒ", wordType: "v.", meaning: "to catch fire" },
      { chinese: "漏", pinyin: "lòu", wordType: "v.", meaning: "(of a container) to leak" },
      { chinese: "雷", pinyin: "léi", wordType: "n.", meaning: "thunder" },
      { chinese: "随时", pinyin: "suíshí", wordType: "adv.", meaning: "at any time" },
      { chinese: "闪电", pinyin: "shǎndiàn", wordType: "n.", meaning: "lightning" },
      { chinese: "击", pinyin: "jī", wordType: "v.", meaning: "to hit, to strike" },
      { chinese: "拥抱", pinyin: "yōngbào", wordType: "v.", meaning: "to hug, to embrace" },
      { chinese: "海里", pinyin: "hǎilǐ", wordType: "m.", meaning: "sea mile" },
      { chinese: "台阶", pinyin: "táijiē", wordType: "n.", meaning: "flight of steps" },
      { chinese: "未来", pinyin: "wèilái", wordType: "n.", meaning: "future" },
      { chinese: "太太", pinyin: "tàitai", wordType: "n.", meaning: "wife" },
      { chinese: "时代", pinyin: "shídài", wordType: "n.", meaning: "era, age, epoch" },
    ],
  },
  {
    chapterNumber: 4,
    words: [
      { chinese: "背", pinyin: "bēi", wordType: "v.", meaning: "to carry on the back" },
      { chinese: "从前", pinyin: "cóngqián", wordType: "n.", meaning: "before, in the past" },
      { chinese: "时期", pinyin: "shíqī", wordType: "n.", meaning: "period, stage" },
      { chinese: "流传", pinyin: "liúchuán", wordType: "v.", meaning: "to spread, to hand down" },
      { chinese: "至今", pinyin: "zhìjīn", wordType: null, meaning: "up to now" },
      { chinese: "孝敬", pinyin: "xiàojìng", wordType: "v.", meaning: "to show filial respect for" },
      { chinese: "农民", pinyin: "nóngmín", wordType: "n.", meaning: "farmer, peasant" },
      { chinese: "战争", pinyin: "zhànzhēng", wordType: "n.", meaning: "war" },
      { chinese: "满足", pinyin: "mǎnzú", wordType: "v.", meaning: "to be satisfied" },
      { chinese: "惭愧", pinyin: "cánkuì", wordType: "adj.", meaning: "ashamed" },
      {
        chinese: "决心",
        pinyin: "juéxīn",
        wordType: "n./v.",
        meaning: "determination; to make up one's mind",
      },
      {
        chinese: "委屈",
        pinyin: "wěiqu",
        wordType: "v./adj.",
        meaning: "to do (sb.) wrong; feeling wronged",
      },
      { chinese: "打听", pinyin: "dǎting", wordType: "v.", meaning: "to inquire about" },
      { chinese: "主人", pinyin: "zhǔrén", wordType: "n.", meaning: "master, owner" },
      { chinese: "结实", pinyin: "jiēshi", wordType: "adj.", meaning: "strong, sturdy" },
      { chinese: "勤奋", pinyin: "qínfèn", wordType: "adj.", meaning: "diligent" },
      { chinese: "银(子)", pinyin: "yín(zi)", wordType: "n.", meaning: "silver" },
      { chinese: "老实", pinyin: "lǎoshi", wordType: "adj.", meaning: "honest, frank" },
      { chinese: "镇", pinyin: "zhèn", wordType: "n.", meaning: "town" },
      { chinese: "后背", pinyin: "hòubèi", wordType: "n.", meaning: "back (of the human body)" },
      { chinese: "滑", pinyin: "huá", wordType: "adj./v.", meaning: "slippery; to slip, to slide" },
      { chinese: "甩", pinyin: "shuǎi", wordType: "v.", meaning: "to throw off, to swing" },
      { chinese: "顶", pinyin: "dǐng", wordType: "v.", meaning: "to go against, to move towards" },
      { chinese: "扶", pinyin: "fú", wordType: "v.", meaning: "to support with one's hand" },
      {
        chinese: "不行",
        pinyin: "bùxíng",
        wordType: "v.",
        meaning: "(indicating degree, intensity, etc.) terribly, extremely",
      },
      { chinese: "团圆", pinyin: "tuányuán", wordType: "v.", meaning: "to be reunited" },
      { chinese: "去世", pinyin: "qùshì", wordType: "v.", meaning: "to die, to pass away" },
      { chinese: "国君", pinyin: "guójūn", wordType: "n.", meaning: "king" },
      { chinese: "本领", pinyin: "běnlǐng", wordType: "n.", meaning: "ability, capability" },
      { chinese: "人才", pinyin: "réncái", wordType: "n.", meaning: "talented person" },
      { chinese: "官", pinyin: "guān", wordType: "n.", meaning: "government official" },
      { chinese: "物质", pinyin: "wùzhì", wordType: "n.", meaning: "material" },
      { chinese: "反而", pinyin: "fǎn'ér", wordType: "adv.", meaning: "on the contrary, instead" },
      { chinese: "诚恳", pinyin: "chéngkěn", wordType: "adj.", meaning: "sincere, earnest" },
      { chinese: "成就", pinyin: "chéngjiù", wordType: "n.", meaning: "achievement, accomplishment" },
      { chinese: "古代", pinyin: "gǔdài", wordType: "n.", meaning: "ancient times" },
      {
        chinese: "孝顺",
        pinyin: "xiàoshùn",
        wordType: "v./adj.",
        meaning: "to show filial piety; obedient and respectful to one's parents",
      },
      { chinese: "美德", pinyin: "měidé", wordType: "n.", meaning: "virtue, goodness" },
      { chinese: "占", pinyin: "zhàn", wordType: "v.", meaning: "to occupy, to take, to hold, to make up" },
      { chinese: "食物", pinyin: "shíwù", wordType: "n.", meaning: "food" },
    ],
  },
  {
    chapterNumber: 5,
    words: [
      { chinese: "悠久", pinyin: "yōujiǔ", wordType: "adj.", meaning: "long-standing, age-old" },
      { chinese: "文字", pinyin: "wénzì", wordType: "n.", meaning: "written language" },
      { chinese: "记载", pinyin: "jìzǎi", wordType: "v.", meaning: "to record, to put down in writing" },
      { chinese: "形状", pinyin: "xíngzhuàng", wordType: "n.", meaning: "shape" },
      { chinese: "描写", pinyin: "miáoxiě", wordType: "v.", meaning: "to describe, to depict" },
      { chinese: "赞美", pinyin: "zànměi", wordType: "v.", meaning: "to praise, to extol" },
      { chinese: "诗", pinyin: "shī", wordType: "n.", meaning: "poem" },
      { chinese: "老百姓", pinyin: "lǎobǎixìng", wordType: "n.", meaning: "ordinary people, civilians" },
      { chinese: "充满", pinyin: "chōngmǎn", wordType: "v.", meaning: "to be full of" },
      { chinese: "感激", pinyin: "gǎnjī", wordType: "v.", meaning: "to feel grateful" },
      { chinese: "从而", pinyin: "cóng'ér", wordType: "conj.", meaning: "thus, consequently" },
      { chinese: "产生", pinyin: "chǎnshēng", wordType: "v.", meaning: "to emerge, to arise" },
      { chinese: "传说", pinyin: "chuánshuō", wordType: "n.", meaning: "legend" },
      { chinese: "善良", pinyin: "shànliáng", wordType: "adj.", meaning: "kind-hearted" },
      { chinese: "救", pinyin: "jiù", wordType: "v.", meaning: "to save, to rescue" },
      { chinese: "晕", pinyin: "yūn", wordType: "v.", meaning: "to faint, to pass out" },
      { chinese: "龙", pinyin: "lóng", wordType: "n.", meaning: "dragon" },
      { chinese: "治(疗)", pinyin: "zhì(liáo)", wordType: "v.", meaning: "to treat, to cure" },
      { chinese: "玉", pinyin: "yù", wordType: "n.", meaning: "jade" },
      { chinese: "壶", pinyin: "hú", wordType: "n.", meaning: "pot, kettle" },
      { chinese: "抢", pinyin: "qiǎng", wordType: "v.", meaning: "to rob, to snatch" },
      { chinese: "埋", pinyin: "mái", wordType: "v.", meaning: "to bury" },
      { chinese: "(躲)藏", pinyin: "(duǒ)cáng", wordType: "v.", meaning: "to hide" },
      { chinese: "如今", pinyin: "rújīn", wordType: "n.", meaning: "nowadays, present" },
      {
        chinese: "分布",
        pinyin: "fēnbù",
        wordType: "v.",
        meaning: "to be distributed (over an area), to be scattered",
      },
      { chinese: "天然", pinyin: "tiānrán", wordType: "adj.", meaning: "natural" },
      { chinese: "优美", pinyin: "yōuměi", wordType: "adj.", meaning: "graceful, beautiful" },
      { chinese: "独特", pinyin: "dútè", wordType: "adj.", meaning: "unique, distinctive" },
      { chinese: "反映", pinyin: "fǎnyìng", wordType: "v.", meaning: "to reflect, to mirror" },
      { chinese: "珍珠", pinyin: "zhēnzhū", wordType: "n.", meaning: "pearl" },
      { chinese: "形成", pinyin: "xíngchéng", wordType: "v.", meaning: "to form, to take shape" },
      { chinese: "于", pinyin: "yú", wordType: "prep.", meaning: "from, out of" },
      { chinese: "广大", pinyin: "guǎngdà", wordType: "adj.", meaning: "vast, extensive" },
      { chinese: "岩石", pinyin: "yánshí", wordType: "n.", meaning: "rock" },
      { chinese: "亿", pinyin: "yì", wordType: "num.", meaning: "hundred million" },
      { chinese: "石灰岩", pinyin: "shíhuīyán", wordType: "n.", meaning: "limestone" },
      { chinese: "地区", pinyin: "dìqū", wordType: "n.", meaning: "area, region" },
      { chinese: "表面", pinyin: "biǎomiàn", wordType: "n.", meaning: "surface" },
      { chinese: "角度", pinyin: "jiǎodù", wordType: "n.", meaning: "angle, degree of angle" },
      { chinese: "斜", pinyin: "xié", wordType: "adj.", meaning: "oblique, slanting" },
      { chinese: "为", pinyin: "wéi", wordType: "v.", meaning: "to become" },
      { chinese: "火成岩", pinyin: "huǒchéngyán", wordType: "n.", meaning: "igneous rock" },
      { chinese: "碰", pinyin: "pèng", wordType: "v.", meaning: "to meet, to come across" },
      { chinese: "挡", pinyin: "dǎng", wordType: "v.", meaning: "to block, to get in the way of" },
      { chinese: "地势", pinyin: "dìshì", wordType: "n.", meaning: "terrain, topography" },
      { chinese: "冲", pinyin: "chōng", wordType: "v.", meaning: "to rush, to dash" },
    ],
  },
  {
    chapterNumber: 6,
    words: [
      { chinese: "除夕", pinyin: "chúxī", wordType: "n.", meaning: "eve of the Lunar New Year/Spring Festival" },
      { chinese: "由来", pinyin: "yóulái", wordType: "n.", meaning: "origin, source" },
      { chinese: "农历", pinyin: "nónglì", wordType: "n.", meaning: "lunar calendar" },
      {
        chinese: "守岁",
        pinyin: "shǒusuì",
        wordType: "v.",
        meaning: "to stay up late or all night on New Year's Eve",
      },
      { chinese: "怪物", pinyin: "guàiwu", wordType: "n.", meaning: "monster" },
      { chinese: "伤害", pinyin: "shānghài", wordType: "v.", meaning: "to hurt, to harm" },
      { chinese: "恨", pinyin: "hèn", wordType: "v.", meaning: "to hate" },
      { chinese: "骨(头)", pinyin: "gǔ(tou)", wordType: "n.", meaning: "bone" },
      { chinese: "无奈", pinyin: "wúnài", wordType: "v.", meaning: "to have no way out, to be helpless" },
      { chinese: "英雄", pinyin: "yīngxióng", wordType: "n.", meaning: "hero" },
      { chinese: "英俊", pinyin: "yīngjùn", wordType: "adj.", meaning: "handsome" },
      { chinese: "咬", pinyin: "yǎo", wordType: "v.", meaning: "to bite" },
      { chinese: "外公", pinyin: "wàigōng", wordType: "n.", meaning: "maternal grandfather" },
      { chinese: "询问", pinyin: "xúnwèn", wordType: "v.", meaning: "to ask, to inquire" },
      { chinese: "天真", pinyin: "tiānzhēn", wordType: "adj.", meaning: "naïve, innocent" },
      { chinese: "杀", pinyin: "shā", wordType: "v.", meaning: "to kill" },
      { chinese: "(代)替", pinyin: "(dài)tì", wordType: "prep.", meaning: "for, on behalf of" },
      { chinese: "除", pinyin: "chú", wordType: "v.", meaning: "to get rid of, to remove" },
      { chinese: "制造", pinyin: "zhìzào", wordType: "v.", meaning: "to make, to produce" },
      { chinese: "灾害", pinyin: "zāihài", wordType: "n.", meaning: "disaster, calamity" },
      { chinese: "逃", pinyin: "táo", wordType: "v.", meaning: "to escape" },
      { chinese: "影子", pinyin: "yǐngzi", wordType: "n.", meaning: "shadow" },
      { chinese: "此外", pinyin: "cǐwài", wordType: "conj.", meaning: "in addition, moreover" },
      {
        chinese: "说不定",
        pinyin: "shuōbùdìng",
        wordType: "adv.",
        meaning: "perhaps, possibly, it's likely that...",
      },
      { chinese: "熬夜", pinyin: "áo yè", wordType: "v.", meaning: "to stay up late" },
      { chinese: "赶紧", pinyin: "gǎnjǐn", wordType: "adv.", meaning: "immediately, at once" },
      { chinese: "果然", pinyin: "guǒrán", wordType: "adv.", meaning: "as expected, really" },
      { chinese: "姑娘", pinyin: "gūniang", wordType: "n.", meaning: "girl" },
      { chinese: "锅", pinyin: "guō", wordType: "n.", meaning: "pot, pan" },
      { chinese: "盆(子)", pinyin: "pén(zi)", wordType: "n.", meaning: "basin, tub" },
      { chinese: "整个", pinyin: "zhěnggè", wordType: "adj.", meaning: "whole, entire" },
      { chinese: "吓", pinyin: "xià", wordType: "v.", meaning: "to frighten, to scare" },
      { chinese: "似的", pinyin: "shìde", wordType: "part.", meaning: "(indicating similarity) like, as" },
      { chinese: "追", pinyin: "zhuī", wordType: "v.", meaning: "to chase, to go after" },
      { chinese: "箭", pinyin: "jiàn", wordType: "n.", meaning: "arrow" },
      { chinese: "射(击)", pinyin: "shè(jī)", wordType: "v.", meaning: "to shoot" },
      {
        chinese: "纷纷",
        pinyin: "fēnfēn",
        wordType: "adv./adj.",
        meaning: "one after another, all at once",
      },
      { chinese: "表达", pinyin: "biǎodá", wordType: "v.", meaning: "to express, to voice" },
      { chinese: "意义", pinyin: "yìyì", wordType: "n.", meaning: "meaning, significance" },
      { chinese: "鞭炮", pinyin: "biānpào", wordType: "n.", meaning: "firecrackers" },
      { chinese: "风俗", pinyin: "fēngsú", wordType: "n.", meaning: "custom, convention" },
    ],
  },
  {
    chapterNumber: 7,
    words: [
      { chinese: "成语", pinyin: "chéngyǔ", wordType: "n.", meaning: "idiom, set phrase" },
      { chinese: "则", pinyin: "zé", wordType: "m.", meaning: "(used for news or writings) piece" },
      { chinese: "盲人", pinyin: "mángrén", wordType: "n.", meaning: "blind person" },
      { chinese: "摸", pinyin: "mō", wordType: "v.", meaning: "to touch, to feel, to stroke" },
      { chinese: "(大)象", pinyin: "(dà)xiàng", wordType: "n.", meaning: "elephant" },
      { chinese: "智慧", pinyin: "zhìhuì", wordType: "n.", meaning: "wisdom" },
      { chinese: "士兵", pinyin: "shìbīng", wordType: "n.", meaning: "soldier" },
      { chinese: "瞎", pinyin: "xiā", wordType: "v./adv.", meaning: "to be blind; blindly, foolishly" },
      { chinese: "分别", pinyin: "fēnbié", wordType: "adv.", meaning: "respectively, separately" },
      { chinese: "寻找", pinyin: "xúnzhǎo", wordType: "v.", meaning: "to look for, to seek" },
      { chinese: "牙齿", pinyin: "yáchǐ", wordType: "n.", meaning: "tooth" },
      { chinese: "胡说", pinyin: "húshuō", wordType: "v.", meaning: "to talk nonsense" },
      { chinese: "尾巴", pinyin: "wěiba", wordType: "n.", meaning: "tail" },
      { chinese: "绳子", pinyin: "shéngzi", wordType: "n.", meaning: "rope" },
      { chinese: "平", pinyin: "píng", wordType: "adj.", meaning: "flat, level" },
      { chinese: "墙", pinyin: "qiáng", wordType: "n.", meaning: "wall" },
      { chinese: "扇子", pinyin: "shànzi", wordType: "n.", meaning: "fan" },
      { chinese: "片面", pinyin: "piànmiàn", wordType: "adj.", meaning: "one-sided" },
      { chinese: "结论", pinyin: "jiélùn", wordType: "n.", meaning: "conclusion" },
      {
        chinese: "精诚所至，金石为开",
        pinyin: "jīngchéng suǒzhì, jīnshí wéi kāi",
        wordType: null,
        meaning:
          "absolute sincerity can affect even metal and stone—no difficulty is insurmountable if one sets his/her mind on it",
      },
      { chinese: "将军", pinyin: "jiāngjūn", wordType: "n.", meaning: "(military rank) general" },
      { chinese: "善于", pinyin: "shànyú", wordType: "v.", meaning: "to be good at" },
      { chinese: "称", pinyin: "chēng", wordType: "v.", meaning: "to call, to give sb. a particular name" },
      { chinese: "打猎", pinyin: "dǎ liè", wordType: "v.", meaning: "to go hunting" },
      { chinese: "忽然", pinyin: "hūrán", wordType: "adv.", meaning: "suddenly" },
      { chinese: "蹲", pinyin: "dūn", wordType: "v.", meaning: "to squat, to crouch" },
      { chinese: "摇", pinyin: "yáo", wordType: "v.", meaning: "to wave, to shake" },
      { chinese: "不要紧", pinyin: "bù yàojǐn", wordType: null, meaning: "it doesn't matter" },
      { chinese: "支", pinyin: "zhī", wordType: "m.", meaning: "used for long, thin, inflexible objects" },
      { chinese: "摆", pinyin: "bǎi", wordType: "v.", meaning: "to put, to place, to set in order" },
      { chinese: "姿势", pinyin: "zīshì", wordType: "n.", meaning: "pose, posture" },
      {
        chinese: "全神贯注",
        pinyin: "quánshén guànzhù",
        wordType: null,
        meaning: "to concentrate on, to be absorbed in",
      },
      { chinese: "尽(力)", pinyin: "jìn(lì)", wordType: "v.", meaning: "to try one's best" },
      { chinese: "反应", pinyin: "fǎnyìng", wordType: "n./v.", meaning: "response; to react" },
      { chinese: "确定", pinyin: "quèdìng", wordType: "v.", meaning: "to confirm, to make sure" },
      { chinese: "石头", pinyin: "shítou", wordType: "n.", meaning: "stone, rock" },
      { chinese: "连续", pinyin: "liánxù", wordType: "v.", meaning: "to be continuous, to be in succession" },
      {
        chinese: "根",
        pinyin: "gēn",
        wordType: "m./n.",
        meaning: "a measure word for long and thin objects; long thin piece",
      },
      { chinese: "碎", pinyin: "suì", wordType: "v./adj.", meaning: "to break into pieces; broken, fragmentary" },
      { chinese: "杆", pinyin: "gǎn", wordType: "n.", meaning: "pole, shaft" },
      { chinese: "哎", pinyin: "āi", wordType: "int.", meaning: "used to express surprise or dissatisfaction" },
      {
        chinese: "唉",
        pinyin: "ài",
        wordType: "int.",
        meaning: "sighing sound indicating sadness or regret",
      },
      { chinese: "金属", pinyin: "jīnshǔ", wordType: "n.", meaning: "metal" },
      { chinese: "硬", pinyin: "yìng", wordType: "adj.", meaning: "hard, tough" },
      {
        chinese: "便",
        pinyin: "biàn",
        wordType: "adv.",
        meaning: "used to indicate that sth. comes naturally under certain conditions or circumstances",
      },
    ],
  },
  {
    chapterNumber: 8,
    words: [
      {
        chinese: "朝三暮四",
        pinyin: "zhāosān mùsì",
        wordType: null,
        meaning: "to give three in the morning and four in the evening—to play fast and loose, to chop and change",
      },
      { chinese: "词汇", pinyin: "cíhuì", wordType: "n.", meaning: "vocabulary" },
      { chinese: "固定", pinyin: "gùdìng", wordType: "adj./v.", meaning: "fixed, settled; to fix" },
      { chinese: "结构", pinyin: "jiégòu", wordType: "n.", meaning: "structure" },
      { chinese: "整体", pinyin: "zhěngtǐ", wordType: "n.", meaning: "whole, entirety" },
      {
        chinese: "综合",
        pinyin: "zōnghé",
        wordType: "v./adj.",
        meaning: "to synthesize, to summarize; comprehensive, integrated",
      },
      { chinese: "完整", pinyin: "wánzhěng", wordType: "adj.", meaning: "complete" },
      { chinese: "哲学家", pinyin: "zhéxuéjiā", wordType: "n.", meaning: "philosopher" },
      { chinese: "寓言", pinyin: "yùyán", wordType: "n.", meaning: "fable" },
      { chinese: "喂养", pinyin: "wèiyǎng", wordType: "v.", meaning: "to feed, to raise" },
      { chinese: "群", pinyin: "qún", wordType: "m.", meaning: "group, herd, flock" },
      { chinese: "猴子", pinyin: "hóuzi", wordType: "n.", meaning: "monkey" },
      { chinese: "宠物", pinyin: "chǒngwù", wordType: "n.", meaning: "pet" },
      { chinese: "相处", pinyin: "xiāngchǔ", wordType: "v.", meaning: "to get along (with one another)" },
      { chinese: "彼此", pinyin: "bǐcǐ", wordType: "n.", meaning: "each other" },
      { chinese: "表情", pinyin: "biǎoqíng", wordType: "n.", meaning: "(facial) expression" },
      { chinese: "行为", pinyin: "xíngwéi", wordType: "n.", meaning: "behavior" },
      { chinese: "对方", pinyin: "duìfāng", wordType: "n.", meaning: "the other side, the other party" },
      { chinese: "蔬菜", pinyin: "shūcài", wordType: "n.", meaning: "vegetable" },
      { chinese: "粮食", pinyin: "liángshi", wordType: "n.", meaning: "grain, cereal, food" },
      { chinese: "家庭", pinyin: "jiātíng", wordType: "n.", meaning: "family" },
      { chinese: "财产", pinyin: "cáichǎn", wordType: "n.", meaning: "property, fortune" },
      { chinese: "消费", pinyin: "xiāofèi", wordType: "v.", meaning: "to consume" },
      { chinese: "节省", pinyin: "jiéshěng", wordType: "v.", meaning: "to save, to economize" },
      { chinese: "限制", pinyin: "xiànzhì", wordType: "v.", meaning: "to limit, to restrict" },
      { chinese: "猪", pinyin: "zhū", wordType: "n.", meaning: "pig" },
      { chinese: "调皮", pinyin: "tiáopí", wordType: "adj.", meaning: "naughty, mischievous" },
      { chinese: "淘气", pinyin: "táoqì", wordType: "adj.", meaning: "naughty, mischievous" },
      { chinese: "橡子", pinyin: "xiàngzi", wordType: "n.", meaning: "acorn" },
      { chinese: "果实", pinyin: "guǒshí", wordType: "n.", meaning: "fruit" },
      { chinese: "不足", pinyin: "bùzú", wordType: "adj./v.", meaning: "insufficient; to be less than" },
      {
        chinese: "倒",
        pinyin: "dào",
        wordType: "adv.",
        meaning: "indicating being contrary to what is expected or thought",
      },
      { chinese: "馒头", pinyin: "mántou", wordType: "n.", meaning: "steamed bun" },
      { chinese: "颗", pinyin: "kē", wordType: "m.", meaning: "used for things small and roundish" },
      { chinese: "似乎", pinyin: "sìhū", wordType: "adv.", meaning: "it seems that..., seemingly" },
      { chinese: "吃亏", pinyin: "chī kuī", wordType: "v.", meaning: "to suffer losses" },
      { chinese: "方式", pinyin: "fāngshì", wordType: "n.", meaning: "way, method" },
      { chinese: "安慰", pinyin: "ānwèi", wordType: "v.", meaning: "to comfort, to console" },
      { chinese: "要不", pinyin: "yàobu", wordType: "conj.", meaning: "otherwise, or else" },
      { chinese: "显得", pinyin: "xiǎnde", wordType: "v.", meaning: "to seem, to appear" },
      { chinese: "格外", pinyin: "géwài", wordType: "adv.", meaning: "especially, extraordinarily" },
      {
        chinese: "哈",
        pinyin: "hā",
        wordType: "onom./int.",
        meaning: "sound of laughter indicating complacency or satisfaction",
      },
    ],
  },
  {
    chapterNumber: 9,
    words: [
      { chinese: "表现", pinyin: "biǎoxiàn", wordType: "v./n.", meaning: "to show, to display; manifestation" },
      { chinese: "突出", pinyin: "tūchū", wordType: "adj.", meaning: "prominent, salient" },
      { chinese: "文学家", pinyin: "wénxuéjiā", wordType: "n.", meaning: "writer, man of letters" },
      { chinese: "算", pinyin: "suàn", wordType: "v.", meaning: "to regard as, to count as" },
      { chinese: "地道", pinyin: "dìdao", wordType: "adj.", meaning: "true, genuine" },
      { chinese: "行家", pinyin: "hángjia", wordType: "n.", meaning: "expert" },
      { chinese: "亲自", pinyin: "qīnzì", wordType: "adv.", meaning: "personally, in person" },
      { chinese: "见解", pinyin: "jiànjiě", wordType: "n.", meaning: "understanding, opinion" },
      {
        chinese: "近代",
        pinyin: "jìndài",
        wordType: "n.",
        meaning: "modern times (referring to the period between mid-19th century and 1919 in Chinese history)",
      },
      { chinese: "时尚", pinyin: "shíshàng", wordType: "n.", meaning: "fashion" },
      { chinese: "写作", pinyin: "xiězuò", wordType: "v.", meaning: "to write" },
      { chinese: "点心", pinyin: "diǎnxin", wordType: "n.", meaning: "dessert, dim sum" },
      { chinese: "作为", pinyin: "zuòwéi", wordType: "v./prep.", meaning: "to be; as, being" },
      { chinese: "学问", pinyin: "xuéwen", wordType: "n.", meaning: "knowledge, learning" },
      {
        chinese: "讲究",
        pinyin: "jiǎngjiu",
        wordType: "v./adj.",
        meaning: "to be particular about, to stress; exquisite",
      },
      { chinese: "平均", pinyin: "píngjūn", wordType: "adj.", meaning: "average" },
      { chinese: "胡同", pinyin: "hútòng", wordType: "n.", meaning: "alley, lane" },
      { chinese: "位于", pinyin: "wèiyú", wordType: "v.", meaning: "to be located at (in, on, etc.)" },
      { chinese: "首", pinyin: "shǒu", wordType: "n./m.", meaning: "head, first" },
      { chinese: "豪华", pinyin: "háohuá", wordType: "adj.", meaning: "luxurious, lavish" },
      { chinese: "光临", pinyin: "guānglín", wordType: "v.", meaning: "to visit, to frequent" },
      { chinese: "交际", pinyin: "jiāojì", wordType: "n.", meaning: "social contact, communication" },
      { chinese: "大方", pinyin: "dàfang", wordType: "adj.", meaning: "generous" },
      { chinese: "好客", pinyin: "hàokè", wordType: "v.", meaning: "to be hospitable" },
      {
        chinese: "呼朋唤友",
        pinyin: "hūpéng huànyǒu",
        wordType: null,
        meaning: "to invite friends, to have friends gather together",
      },
      { chinese: "招待", pinyin: "zhāodài", wordType: "v.", meaning: "to receive, to entertain" },
      { chinese: "胃", pinyin: "wèi", wordType: "n.", meaning: "stomach" },
      { chinese: "胃口", pinyin: "wèikǒu", wordType: "n.", meaning: "appetite" },
      { chinese: "酒", pinyin: "jiǔ", wordType: "n.", meaning: "wine, liquor" },
      { chinese: "戒", pinyin: "jiè", wordType: "v.", meaning: "to give up, to quit" },
      { chinese: "保存", pinyin: "bǎocún", wordType: "v.", meaning: "to keep, to save" },
      { chinese: "形象", pinyin: "xíngxiàng", wordType: "adj.", meaning: "vivid" },
      { chinese: "曾经", pinyin: "céngjīng", wordType: "adv.", meaning: "once, in the past" },
      { chinese: "明明", pinyin: "míngmíng", wordType: "adv.", meaning: "evidently, undoubtedly" },
      { chinese: "悠悠", pinyin: "yōuyōu", wordType: "adj.", meaning: "leisurely, unhurriedly" },
    ],
  },
  {
    chapterNumber: 10,
    words: [
      { chinese: "争论", pinyin: "zhēnglùn", wordType: "v.", meaning: "to argue, to dispute" },
      { chinese: "奇迹", pinyin: "qíjì", wordType: "n.", meaning: "miracle, wonder" },
      { chinese: "围绕", pinyin: "wéirào", wordType: "v.", meaning: "to center around" },
      { chinese: "奔跑", pinyin: "bēnpǎo", wordType: "v.", meaning: "to run, to gallop" },
      { chinese: "蹄(子)", pinyin: "tí(zi)", wordType: "n.", meaning: "hoof" },
      { chinese: "辩论", pinyin: "biànlùn", wordType: "v.", meaning: "to debate" },
      { chinese: "青蛙", pinyin: "qīngwā", wordType: "n.", meaning: "frog" },
      {
        chinese: "啦",
        pinyin: "la",
        wordType: "part.",
        meaning:
          "combination of the sounds of \"了(le)\" and \"啊(a)\", expressing exclamation, interrogation, etc.",
      },
      { chinese: "始终", pinyin: "shǐzhōng", wordType: "adv.", meaning: "from the beginning to the end, all along" },
      { chinese: "脖子", pinyin: "bózi", wordType: "n.", meaning: "neck" },
      { chinese: "说服", pinyin: "shuōfú", wordType: "v.", meaning: "to persuade, to convince" },
      { chinese: "摄影师", pinyin: "shèyǐngshī", wordType: "n.", meaning: "photographer" },
      { chinese: "毕竟", pinyin: "bìjìng", wordType: "adv.", meaning: "after all, in the final analysis" },
      { chinese: "操场", pinyin: "cāochǎng", wordType: "n.", meaning: "sports ground, playground" },
      { chinese: "洞", pinyin: "dòng", wordType: "n.", meaning: "hole" },
      { chinese: "插", pinyin: "chā", wordType: "v.", meaning: "to insert, to stick in" },
      { chinese: "棍", pinyin: "gùn", wordType: "n.", meaning: "stick, cudgel" },
      { chinese: "系", pinyin: "jì", wordType: "v.", meaning: "to tie, to fasten" },
      { chinese: "匹", pinyin: "pǐ", wordType: "m.", meaning: "used for horses" },
      { chinese: "拦", pinyin: "lán", wordType: "v.", meaning: "to block, to hold back" },
      { chinese: "拍", pinyin: "pāi", wordType: "v.", meaning: "to take (a photo), to shoot (a video)" },
      { chinese: "差距", pinyin: "chājù", wordType: "n.", meaning: "gap, difference" },
      { chinese: "显示", pinyin: "xiǎnshì", wordType: "v.", meaning: "to show, to display" },
      {
        chinese: "意识",
        pinyin: "yìshí",
        wordType: "n./v.",
        meaning: "consciousness; to be aware of, to realize",
      },
      { chinese: "艰苦", pinyin: "jiānkǔ", wordType: "adj.", meaning: "arduous, difficult, tough" },
      { chinese: "试验", pinyin: "shìyàn", wordType: "n./v.", meaning: "trial, test; to make a trial" },
      { chinese: "逐渐", pinyin: "zhújiàn", wordType: "adv.", meaning: "gradually" },
      { chinese: "改进", pinyin: "gǎijìn", wordType: "v.", meaning: "to improve, to ameliorate" },
      { chinese: "成熟", pinyin: "chéngshú", wordType: "v./adj.", meaning: "to ripen; mature" },
      { chinese: "兄弟", pinyin: "xiōngdì", wordType: "n.", meaning: "brother" },
      { chinese: "播放", pinyin: "bōfàng", wordType: "v.", meaning: "to broadcast, to play (music or videos)" },
      { chinese: "纪念", pinyin: "jìniàn", wordType: "v.", meaning: "to commemorate" },
      {
        chinese: "导演",
        pinyin: "dǎoyǎn",
        wordType: "n./v.",
        meaning: "director (of a show or movie); to direct",
      },
      { chinese: "瞬间", pinyin: "shùnjiān", wordType: "n.", meaning: "a short period of time" },
      { chinese: "请求", pinyin: "qǐngqiú", wordType: "v./n.", meaning: "to request, to ask; request" },
      { chinese: "或许", pinyin: "huòxǔ", wordType: "adv.", meaning: "maybe, perhaps" },
      { chinese: "重大", pinyin: "zhòngdà", wordType: "adj.", meaning: "great, significant" },
    ],
  },
  {
    chapterNumber: 11,
    words: [
      { chinese: "闹钟", pinyin: "nàozhōng", wordType: "n.", meaning: "alarm clock" },
      { chinese: "危害", pinyin: "wēihài", wordType: "v.", meaning: "to harm, to jeopardize" },
      { chinese: "人类", pinyin: "rénlèi", wordType: "n.", meaning: "humankind" },
      { chinese: "机制", pinyin: "jīzhì", wordType: "n.", meaning: "mechanism" },
      { chinese: "生物", pinyin: "shēngwù", wordType: "n.", meaning: "living things" },
      { chinese: "规律", pinyin: "guīlǜ", wordType: "n./adj.", meaning: "law, regular pattern; regular" },
      { chinese: "光线", pinyin: "guāngxiàn", wordType: "n.", meaning: "light, ray" },
      { chinese: "必要", pinyin: "bìyào", wordType: "adj.", meaning: "necessary, essential" },
      { chinese: "过渡", pinyin: "guòdù", wordType: "v.", meaning: "to transit" },
      { chinese: "浅", pinyin: "qiǎn", wordType: "adj.", meaning: "shallow, light" },
      { chinese: "现代", pinyin: "xiàndài", wordType: "n./adj.", meaning: "modern times; modern" },
      { chinese: "享受", pinyin: "xiǎngshòu", wordType: "v.", meaning: "to enjoy" },
      { chinese: "用途", pinyin: "yòngtú", wordType: "n.", meaning: "use, purpose" },
      { chinese: "实验", pinyin: "shíyàn", wordType: "v./n.", meaning: "to make an experiment; experiment" },
      { chinese: "铃", pinyin: "líng", wordType: "n.", meaning: "bell" },
      {
        chinese: "所",
        pinyin: "suǒ",
        wordType: "part.",
        meaning: "used before a verb which is the receiver of the action",
      },
      { chinese: "状态", pinyin: "zhuàngtài", wordType: "n.", meaning: "state, status" },
      { chinese: "清醒", pinyin: "qīngxǐng", wordType: "adj./v.", meaning: "sober; to regain consciousness" },
      { chinese: "呼吸", pinyin: "hūxī", wordType: "v.", meaning: "to breathe" },
      { chinese: "心理", pinyin: "xīnlǐ", wordType: "n.", meaning: "mentality, psychology" },
      { chinese: "慌(张)", pinyin: "huāng(zhāng)", wordType: "adj.", meaning: "flurried, flustered" },
      { chinese: "情绪", pinyin: "qíngxù", wordType: "n.", meaning: "emotion, mood" },
      { chinese: "低落", pinyin: "dīluò", wordType: "adj.", meaning: "down, depressed" },
      { chinese: "记忆", pinyin: "jìyì", wordType: "v./n.", meaning: "to remember; memory" },
      { chinese: "计算", pinyin: "jìsuàn", wordType: "v.", meaning: "to calculate, to compute" },
      { chinese: "相当", pinyin: "xiāngdāng", wordType: "v.", meaning: "to be equal to" },
      { chinese: "持续", pinyin: "chíxù", wordType: "v.", meaning: "to continue, to last" },
      { chinese: "数", pinyin: "shù", wordType: "num.", meaning: "several" },
      { chinese: "导致", pinyin: "dǎozhì", wordType: "v.", meaning: "to cause, to lead to" },
      { chinese: "失眠", pinyin: "shīmián", wordType: "v.", meaning: "to suffer from insomnia" },
      { chinese: "精神", pinyin: "jīngshén", wordType: "n./adj.", meaning: "spirit, vigor; lively, vigorous" },
      { chinese: "专家", pinyin: "zhuānjiā", wordType: "n.", meaning: "expert" },
      { chinese: "采用", pinyin: "cǎiyòng", wordType: "v.", meaning: "to use, to employ" },
      { chinese: "柔和", pinyin: "róuhé", wordType: "adj.", meaning: "gentle, soft" },
      { chinese: "愿望", pinyin: "yuànwàng", wordType: "n.", meaning: "wish, hope" },
      { chinese: "窗帘", pinyin: "chuānglián", wordType: "n.", meaning: "curtain" },
      { chinese: "市场", pinyin: "shìchǎng", wordType: "n.", meaning: "market" },
      { chinese: "产品", pinyin: "chǎnpǐn", wordType: "n.", meaning: "product, produce" },
      { chinese: "模仿", pinyin: "mófǎng", wordType: "v.", meaning: "to imitate, to model on" },
      { chinese: "避免", pinyin: "bìmiǎn", wordType: "v.", meaning: "to prevent, to avoid" },
      { chinese: "传统", pinyin: "chuántǒng", wordType: "n./adj.", meaning: "tradition; traditional" },
    ],
  },
  {
    chapterNumber: 12,
    words: [
      { chinese: "用户", pinyin: "yònghù", wordType: "n.", meaning: "user" },
      { chinese: "颠球", pinyin: "diān qiú", wordType: "v.", meaning: "to juggle a soccer ball" },
      { chinese: "明星", pinyin: "míngxīng", wordType: "n.", meaning: "star, celebrity" },
      { chinese: "直播", pinyin: "zhíbō", wordType: "v.", meaning: "to make a live broadcast" },
      { chinese: "宝贝", pinyin: "bǎobèi", wordType: "n.", meaning: "baby" },
      { chinese: "逗", pinyin: "dòu", wordType: "v.", meaning: "to amuse, to tease" },
      { chinese: "宣传", pinyin: "xuānchuán", wordType: "v.", meaning: "to publicize, to promote" },
      { chinese: "手笔", pinyin: "shǒubǐ", wordType: "n.", meaning: "style (of handling affairs)" },
      { chinese: "推广", pinyin: "tuīguǎng", wordType: "v.", meaning: "to popularize, to promote" },
      { chinese: "注册", pinyin: "zhùcè", wordType: "v.", meaning: "to register" },
      { chinese: "召开", pinyin: "zhàokāi", wordType: "v.", meaning: "to hold (a meeting), to convene" },
      { chinese: "合作", pinyin: "hézuò", wordType: "v.", meaning: "to cooperate, to work together" },
      { chinese: "伙伴", pinyin: "huǒbàn", wordType: "n.", meaning: "partner" },
      { chinese: "总裁", pinyin: "zǒngcái", wordType: "n.", meaning: "president (of a company)" },
      { chinese: "实现", pinyin: "shíxiàn", wordType: "v.", meaning: "to realize, to achieve" },
      { chinese: "覆盖", pinyin: "fùgài", wordType: "v.", meaning: "to cover" },
      { chinese: "移动", pinyin: "yídòng", wordType: "v.", meaning: "to move; mobile" },
      { chinese: "通信", pinyin: "tōngxìn", wordType: "n./v.", meaning: "communication; to communicate" },
      { chinese: "应用", pinyin: "yìngyòng", wordType: "n./v.", meaning: "application; to apply" },
      { chinese: "企业", pinyin: "qǐyè", wordType: "n.", meaning: "enterprise, company" },
      { chinese: "称霸", pinyin: "chēngbà", wordType: "v.", meaning: "to dominate, to maintain hegemony" },
      { chinese: "背景", pinyin: "bèijǐng", wordType: "n.", meaning: "background" },
      { chinese: "高级", pinyin: "gāojí", wordType: "adj.", meaning: "senior, high-ranking" },
      { chinese: "副", pinyin: "fù", wordType: "adj.", meaning: "deputy, vice" },
      { chinese: "开发", pinyin: "kāifā", wordType: "v.", meaning: "to develop, to exploit" },
      { chinese: "中心", pinyin: "zhōngxīn", wordType: "n.", meaning: "center" },
      { chinese: "相关", pinyin: "xiāngguān", wordType: "v.", meaning: "to correlate, to be relevant" },
      { chinese: "业务", pinyin: "yèwù", wordType: "n.", meaning: "professional work, business" },
      { chinese: "现实", pinyin: "xiànshí", wordType: "n.", meaning: "reality" },
      { chinese: "个人", pinyin: "gèrén", wordType: "n.", meaning: "individual" },
      { chinese: "以及", pinyin: "yǐjí", wordType: "conj.", meaning: "and also, as well" },
      { chinese: "程度", pinyin: "chéngdù", wordType: "n.", meaning: "degree, level" },
      { chinese: "发达", pinyin: "fādá", wordType: "adj.", meaning: "developed, advanced" },
      { chinese: "创新", pinyin: "chuàngxīn", wordType: "v.", meaning: "to create sth. new, to innovate" },
      { chinese: "领导", pinyin: "lǐngdǎo", wordType: "n.", meaning: "leader" },
      { chinese: "地位", pinyin: "dìwèi", wordType: "n.", meaning: "position, status" },
      { chinese: "经营", pinyin: "jīngyíng", wordType: "v.", meaning: "to manage, to run" },
      { chinese: "销售", pinyin: "xiāoshòu", wordType: "v.", meaning: "to sell, to market" },
      { chinese: "针对", pinyin: "zhènduì", wordType: "v.", meaning: "to be targeted at" },
      { chinese: "当地", pinyin: "dāngdì", wordType: "n.", meaning: "local, in the locality" },
      {
        chinese: "代言",
        pinyin: "dàiyán",
        wordType: "v.",
        meaning: "to speak on behalf of, to star in a commercial",
      },
      { chinese: "华裔", pinyin: "huáyì", wordType: "n.", meaning: "foreign citizen of Chinese origin" },
      { chinese: "移民", pinyin: "yímín", wordType: "n.", meaning: "immigrant" },
    ],
  },
  {
    chapterNumber: 13,
    words: [
      { chinese: "锯(子)", pinyin: "jù(zi)", wordType: "v./n.", meaning: "to cut with a saw; saw" },
      { chinese: "筐", pinyin: "kuāng", wordType: "n.", meaning: "basket" },
      { chinese: "训练", pinyin: "xùnliàn", wordType: "v.", meaning: "to train" },
      { chinese: "缺乏", pinyin: "quēfá", wordType: "v.", meaning: "to lack, to be short of" },
      { chinese: "项目", pinyin: "xiàngmù", wordType: "n.", meaning: "item, project" },
      { chinese: "桃", pinyin: "táo", wordType: "n.", meaning: "peach" },
      { chinese: "装", pinyin: "zhuāng", wordType: "v.", meaning: "to load, to hold" },
      { chinese: "启发", pinyin: "qǐfā", wordType: "v.", meaning: "to enlighten, to inspire" },
      { chinese: "安装", pinyin: "ānzhuāng", wordType: "v.", meaning: "to install, to fix" },
      { chinese: "栏杆", pinyin: "lángān", wordType: "n.", meaning: "railing, balustrade" },
      { chinese: "甲", pinyin: "jiǎ", wordType: "n.", meaning: "first" },
      { chinese: "乙", pinyin: "yǐ", wordType: "n.", meaning: "second" },
      { chinese: "工具", pinyin: "gōngjù", wordType: "n.", meaning: "tool, instrument" },
      { chinese: "投篮", pinyin: "tóu lán", wordType: "v.", meaning: "to shoot (a basket)" },
      { chinese: "踩", pinyin: "cǎi", wordType: "v.", meaning: "to step on, to tread on" },
      { chinese: "一再", pinyin: "yīzài", wordType: "adv.", meaning: "over and over again" },
      { chinese: "重复", pinyin: "chóngfù", wordType: "v.", meaning: "to repeat" },
      {
        chinese: "断断续续",
        pinyin: "duànduàn xùxù",
        wordType: "adj.",
        meaning: "off and on, intermittent",
      },
      { chinese: "激烈", pinyin: "jīliè", wordType: "adj.", meaning: "intense, fierce" },
      { chinese: "气氛", pinyin: "qìfēn", wordType: "n.", meaning: "atmosphere" },
      { chinese: "何况", pinyin: "hékuàng", wordType: "conj.", meaning: "let alone" },
      { chinese: "球迷", pinyin: "qiúmí", wordType: "n.", meaning: "ball game fan" },
      { chinese: "工程师", pinyin: "gōngchéngshī", wordType: "n.", meaning: "engineer" },
      { chinese: "机器", pinyin: "jīqì", wordType: "n.", meaning: "machine" },
      { chinese: "顺畅", pinyin: "shùnchàng", wordType: "adj.", meaning: "smooth, unhindered" },
      { chinese: "幼儿园", pinyin: "yòu'éryuán", wordType: "n.", meaning: "kindergarten" },
      { chinese: "好奇", pinyin: "hàoqí", wordType: "adj.", meaning: "curious" },
      {
        chinese: "何必",
        pinyin: "hébì",
        wordType: "adv.",
        meaning: "(indicating that there is no need for sth.) why",
      },
      { chinese: "多亏", pinyin: "duōkuī", wordType: "v.", meaning: "luckily, thank to" },
      { chinese: "连忙", pinyin: "liánmáng", wordType: "adv.", meaning: "promptly, at once" },
      { chinese: "瞧", pinyin: "qiáo", wordType: "v.", meaning: "to look, to see" },
      { chinese: "困扰", pinyin: "kùnrǎo", wordType: "v.", meaning: "to trouble, to haunt" },
      { chinese: "思维", pinyin: "sīwéi", wordType: "n./v.", meaning: "thinking; to think" },
      { chinese: "呆", pinyin: "dāi", wordType: "adj./v.", meaning: "dull, dumb; to stagnate" },
      { chinese: "造成", pinyin: "zàochéng", wordType: "v.", meaning: "to cause, to give rise to" },
      {
        chinese: "仿佛",
        pinyin: "fǎngfú",
        wordType: "adv./v.",
        meaning: "as if; to be like, to be similar to",
      },
      { chinese: "阻碍", pinyin: "zǔ'ài", wordType: "v.", meaning: "to hinder, to impede" },
    ],
  },
  {
    chapterNumber: 14,
    words: [
      { chinese: "四合院", pinyin: "sìhéyuàn", wordType: "n.", meaning: "quadrangle courtyard" },
      { chinese: "民居", pinyin: "mínjū", wordType: "n.", meaning: "civilian dwelling" },
      { chinese: "组合", pinyin: "zǔhé", wordType: "v./n.", meaning: "to combine; combination" },
      { chinese: "建筑", pinyin: "jiànzhù", wordType: "n.", meaning: "building, architecture" },
      { chinese: "形式", pinyin: "xíngshì", wordType: "n.", meaning: "form, mode" },
      { chinese: "所谓", pinyin: "suǒwèi", wordType: "adj.", meaning: "so-called" },
      { chinese: "方", pinyin: "fāng", wordType: "adj.", meaning: "square" },
      { chinese: "广泛", pinyin: "guǎngfàn", wordType: "adj.", meaning: "wide, extensive" },
      { chinese: "样式", pinyin: "yàngshì", wordType: "n.", meaning: "style, pattern" },
      { chinese: "代表", pinyin: "dàibiǎo", wordType: "n./v.", meaning: "typical case; to represent" },
      { chinese: "通常", pinyin: "tōngcháng", wordType: "adv.", meaning: "usually" },
      { chinese: "并列", pinyin: "bìngliè", wordType: "v.", meaning: "to stand side by side" },
      { chinese: "组成", pinyin: "zǔchéng", wordType: "v.", meaning: "to form, to constitute" },
      { chinese: "长辈", pinyin: "zhǎngbèi", wordType: "n.", meaning: "senior member of a family" },
      { chinese: "具备", pinyin: "jùbèi", wordType: "v.", meaning: "to have, to possess" },
      { chinese: "日常", pinyin: "rìcháng", wordType: "adj.", meaning: "day-to-day, daily" },
      { chinese: "起居", pinyin: "qǐjū", wordType: "n.", meaning: "daily life" },
      { chinese: "接待", pinyin: "jiēdài", wordType: "v.", meaning: "to receive (sb.), to entertain" },
      { chinese: "功能", pinyin: "gōngnéng", wordType: "n.", meaning: "function" },
      { chinese: "厢房", pinyin: "xiāngfáng", wordType: "n.", meaning: "wing, wing room" },
      { chinese: "走廊", pinyin: "zǒuláng", wordType: "n.", meaning: "corridor, passageway" },
      { chinese: "空间", pinyin: "kōngjiān", wordType: "n.", meaning: "space" },
      { chinese: "种", pinyin: "zhòng", wordType: "v.", meaning: "to plant, to grow" },
      { chinese: "竹子", pinyin: "zhúzi", wordType: "n.", meaning: "bamboo" },
      { chinese: "则", pinyin: "zé", wordType: "conj.", meaning: "(indicating contrast) while" },
      { chinese: "金鱼", pinyin: "jīnyú", wordType: "n.", meaning: "goldfish" },
      { chinese: "创造", pinyin: "chuàngzào", wordType: "v.", meaning: "to create, to produce" },
      { chinese: "情趣", pinyin: "qíngqù", wordType: "n.", meaning: "emotional appeal, interest" },
      { chinese: "因而", pinyin: "yīn'ér", wordType: "conj.", meaning: "therefore, thus" },
      { chinese: "为", pinyin: "wéi", wordType: "prep.", meaning: "(often used together with \"所\") by (sb.)" },
      { chinese: "关闭", pinyin: "guānbì", wordType: "v.", meaning: "to close, to shut" },
      { chinese: "封闭", pinyin: "fēngbì", wordType: "v.", meaning: "to close, to seal" },
      { chinese: "打交道", pinyin: "dǎ jiāodào", wordType: null, meaning: "to make contact with" },
      { chinese: "日子", pinyin: "rìzi", wordType: "n.", meaning: "life, livelihood" },
      { chinese: "充分", pinyin: "chōngfèn", wordType: "adj.", meaning: "ample, sufficient" },
      { chinese: "令", pinyin: "lìng", wordType: "v.", meaning: "to make, to cause" },
      { chinese: "亲切", pinyin: "qīnqiè", wordType: "adj.", meaning: "warm, cordial, affectionate" },
      {
        chinese: "劳动",
        pinyin: "láodòng",
        wordType: "n./v.",
        meaning: "work, labor; to work, to do physical labor",
      },
      { chinese: "人民", pinyin: "rénmín", wordType: "n.", meaning: "people" },
      { chinese: "矛盾", pinyin: "máodùn", wordType: "n./adj.", meaning: "conflict; conflicting" },
      { chinese: "浓", pinyin: "nóng", wordType: "adj.", meaning: "strong, deep" },
    ],
  },
  {
    chapterNumber: 15,
    words: [
      { chinese: "纸上谈兵", pinyin: "zhǐshàng tánbīng", wordType: null, meaning: "to be an armchair strategist" },
      { chinese: "军事", pinyin: "jūnshì", wordType: "n.", meaning: "military affairs" },
      { chinese: "敌(人)", pinyin: "dí(rén)", wordType: "n.", meaning: "enemy" },
      { chinese: "理论", pinyin: "lǐlùn", wordType: "n.", meaning: "theory" },
      { chinese: "作战", pinyin: "zuòzhàn", wordType: "v.", meaning: "to fight a battle" },
      { chinese: "毛病", pinyin: "máobìng", wordType: "n.", meaning: "shortcoming, weakness" },
      { chinese: "道理", pinyin: "dàolǐ", wordType: "n.", meaning: "principle, theory" },
      { chinese: "迟早", pinyin: "chízǎo", wordType: "adv.", meaning: "sooner or later" },
      { chinese: "军队", pinyin: "jūnduì", wordType: "n.", meaning: "army" },
      { chinese: "派", pinyin: "pài", wordType: "v.", meaning: "to send, to assign, to appoint" },
      { chinese: "弱", pinyin: "ruò", wordType: "adj.", meaning: "weak" },
      { chinese: "形势", pinyin: "xíngshì", wordType: "n.", meaning: "situation, state of affairs" },
      { chinese: "命令", pinyin: "mìnglìng", wordType: "v./n.", meaning: "to command; order" },
      { chinese: "守", pinyin: "shǒu", wordType: "v.", meaning: "to guard, to defend" },
      { chinese: "阵地", pinyin: "zhèndì", wordType: "n.", meaning: "position, front" },
      { chinese: "绝对", pinyin: "juéduì", wordType: "adv./adj.", meaning: "absolutely, definitely; absolute" },
      { chinese: "主动", pinyin: "zhǔdòng", wordType: "adj.", meaning: "on one's own initiative" },
      { chinese: "挑战", pinyin: "tiǎozhàn", wordType: "v./n.", meaning: "to challenge, to battle; challenge" },
      { chinese: "骂", pinyin: "mà", wordType: "v.", meaning: "to curse, to call names" },
      { chinese: "胆小鬼", pinyin: "dǎnxiǎoguǐ", wordType: "n.", meaning: "coward" },
      { chinese: "胜利", pinyin: "shènglì", wordType: "v.", meaning: "to win a victory" },
      { chinese: "调(动)", pinyin: "diào(dòng)", wordType: "v.", meaning: "to transfer, to shift" },
      { chinese: "散布", pinyin: "sànbù", wordType: "v.", meaning: "to spread, to disseminate" },
      { chinese: "谣言", pinyin: "yáoyán", wordType: "n.", meaning: "rumor" },
      { chinese: "上当", pinyin: "shàng dàng", wordType: "v.", meaning: "to be taken in, to be deceived" },
      { chinese: "再三", pinyin: "zàisān", wordType: "adv.", meaning: "again and again" },
      { chinese: "阻止", pinyin: "zǔzhǐ", wordType: "v.", meaning: "to stop, to prevent" },
      { chinese: "任命", pinyin: "rènmìng", wordType: "v.", meaning: "to appoint" },
      { chinese: "独立", pinyin: "dúlì", wordType: "v.", meaning: "to be on one's own" },
      { chinese: "资格", pinyin: "zīgé", wordType: "n.", meaning: "qualification" },
      { chinese: "糊涂", pinyin: "hútú", wordType: "adj.", meaning: "muddleheaded" },
      { chinese: "公元", pinyin: "gōngyuán", wordType: "n.", meaning: "Christian era" },
      { chinese: "盲目", pinyin: "mángmù", wordType: "adj.", meaning: "blind, ignorant" },
      { chinese: "轻视", pinyin: "qīngshì", wordType: "v.", meaning: "to look down upon, to belittle" },
      { chinese: "方案", pinyin: "fāng'àn", wordType: "n.", meaning: "plan, scheme" },
      { chinese: "进攻", pinyin: "jìngōng", wordType: "v.", meaning: "to attack, to assault" },
      { chinese: "宝贵", pinyin: "bǎoguì", wordType: "adj.", meaning: "precious, valuable" },
      { chinese: "讽刺", pinyin: "fěngcì", wordType: "v.", meaning: "to satirize" },
      { chinese: "灵活", pinyin: "línghuó", wordType: "adj.", meaning: "flexible, elastic" },
    ],
  },
  {
    chapterNumber: 16,
    words: [
      { chinese: "节食", pinyin: "jiéshí", wordType: "v.", meaning: "to go on a diet" },
      { chinese: "报道", pinyin: "bàodào", wordType: "n./v.", meaning: "to report, to cover; report" },
      { chinese: "营养", pinyin: "yíngyǎng", wordType: "n.", meaning: "nutrition" },
      { chinese: "摄入", pinyin: "shèrù", wordType: "v.", meaning: "to take in, to ingest" },
      { chinese: "模式", pinyin: "móshì", wordType: "n.", meaning: "model, pattern" },
      { chinese: "波动", pinyin: "bōdòng", wordType: "v.", meaning: "to undulate, to rise and fall" },
      { chinese: "总共", pinyin: "zǒnggòng", wordType: "adv.", meaning: "altogether, in total" },
      { chinese: "参与", pinyin: "cānyù", wordType: "v.", meaning: "to take part in" },
      { chinese: "人员", pinyin: "rényuán", wordType: "n.", meaning: "personnel, staff" },
      { chinese: "相对", pinyin: "xiāngduì", wordType: "adj.", meaning: "relative, comparative" },
      { chinese: "类型", pinyin: "lèixíng", wordType: "n.", meaning: "type, category" },
      { chinese: "称", pinyin: "chēng", wordType: "v.", meaning: "to weigh" },
      { chinese: "可靠", pinyin: "kěkào", wordType: "adj.", meaning: "reliable, dependable" },
      { chinese: "纳入", pinyin: "nàrù", wordType: "v.", meaning: "to include, to incorporate into" },
      { chinese: "分析", pinyin: "fēnxī", wordType: "v.", meaning: "to analyze" },
      { chinese: "志愿者", pinyin: "zhìyuànzhě", wordType: "n.", meaning: "volunteer" },
      { chinese: "跟踪", pinyin: "gēnzōng", wordType: "v.", meaning: "to follow, to track" },
      { chinese: "成果", pinyin: "chéngguǒ", wordType: "n.", meaning: "result, achievement" },
      { chinese: "清晰", pinyin: "qīngxī", wordType: "adj.", meaning: "clear, distinct" },
      { chinese: "即", pinyin: "jí", wordType: "v./adv.", meaning: "to be; namely" },
      { chinese: "升", pinyin: "shēng", wordType: "v.", meaning: "to rise, to go up" },
      { chinese: "达到", pinyin: "dádào", wordType: "v.", meaning: "to reach, to attain" },
      { chinese: "意外", pinyin: "yìwài", wordType: "adj./n.", meaning: "unexpected; accident" },
      { chinese: "存在", pinyin: "cúnzài", wordType: "v.", meaning: "to exist" },
      { chinese: "明显", pinyin: "míngxiǎn", wordType: "adj.", meaning: "obvious, apparent" },
      { chinese: "补偿", pinyin: "bǔcháng", wordType: "v.", meaning: "to compensate" },
      { chinese: "立即", pinyin: "lìjí", wordType: "adv.", meaning: "immediately, at once" },
      { chinese: "趋势", pinyin: "qūshì", wordType: "n.", meaning: "trend, tendency" },
      { chinese: "差异", pinyin: "chāyì", wordType: "n.", meaning: "difference" },
      { chinese: "联合", pinyin: "liánhé", wordType: "v./adj.", meaning: "to unite, to ally; joint, combined" },
      { chinese: "个别", pinyin: "gèbié", wordType: "adv./adj.", meaning: "one or two; exceptional" },
      { chinese: "表明", pinyin: "biǎomíng", wordType: "v.", meaning: "to indicate, to manifest" },
      { chinese: "临时", pinyin: "línshí", wordType: "adv./adj.", meaning: "for a short time; temporary" },
      { chinese: "现象", pinyin: "xiànxiàng", wordType: "n.", meaning: "phenomenon" },
      { chinese: "非", pinyin: "fēi", wordType: "v.", meaning: "to be not" },
      { chinese: "就餐", pinyin: "jiùcān", wordType: "v.", meaning: "to have one's meal" },
      { chinese: "放纵", pinyin: "fàngzòng", wordType: "v.", meaning: "to indulge, to be unrestrained" },
      { chinese: "苗条", pinyin: "miáotiáo", wordType: "adj.", meaning: "slim, slender" },
      { chinese: "借口", pinyin: "jièkǒu", wordType: "n./v.", meaning: "excuse, pretext; to use as an excuse" },
      { chinese: "采取", pinyin: "cǎiqǔ", wordType: "v.", meaning: "to take, to adopt" },
      { chinese: "措施", pinyin: "cuòshī", wordType: "n.", meaning: "measure, step" },
    ],
  },
  {
    chapterNumber: 17,
    words: [
      { chinese: "事物", pinyin: "shìwù", wordType: "n.", meaning: "thing, object" },
      { chinese: "高峰", pinyin: "gāofēng", wordType: "n.", meaning: "peak, summit" },
      { chinese: "终点", pinyin: "zhōngdiǎn", wordType: "n.", meaning: "end, destination" },
      { chinese: "迅速", pinyin: "xùnsù", wordType: "adj.", meaning: "quick, rapid" },
      { chinese: "深刻", pinyin: "shēnkè", wordType: "adj.", meaning: "deep, profound" },
      { chinese: "戏剧", pinyin: "xìjù", wordType: "n.", meaning: "drama, play" },
      { chinese: "投入", pinyin: "tóurù", wordType: "v./n./adj.", meaning: "to put into, to spend on; input; devoted" },
      { chinese: "服装", pinyin: "fúzhuāng", wordType: "n.", meaning: "clothing, costume" },
      { chinese: "化妆", pinyin: "huàzhuāng", wordType: "v.", meaning: "to put on make-up" },
      { chinese: "道具", pinyin: "dàojù", wordType: "n.", meaning: "stage property, prop" },
      { chinese: "美术", pinyin: "měishù", wordType: "n.", meaning: "fine art" },
      { chinese: "以", pinyin: "yǐ", wordType: "conj.", meaning: "in order to, so as to" },
      { chinese: "良好", pinyin: "liánghǎo", wordType: "adj.", meaning: "good, fine" },
      { chinese: "争取", pinyin: "zhēngqǔ", wordType: "v.", meaning: "to strive for, to endeavor to" },
      { chinese: "忽视", pinyin: "hūshì", wordType: "v.", meaning: "to ignore, to overlook" },
      { chinese: "魅力", pinyin: "mèilì", wordType: "n.", meaning: "charm" },
      { chinese: "糟糕", pinyin: "zāogāo", wordType: "adj.", meaning: "bad, awful" },
      { chinese: "婚礼", pinyin: "hūnlǐ", wordType: "n.", meaning: "wedding" },
      { chinese: "等于", pinyin: "děngyú", wordType: "v.", meaning: "to be equal to" },
      { chinese: "度过", pinyin: "dùguò", wordType: "v.", meaning: "to pass, to spend" },
      { chinese: "告别", pinyin: "gàobié", wordType: "v.", meaning: "to say goodbye" },
      { chinese: "平常", pinyin: "píngcháng", wordType: "adj./n.", meaning: "common, ordinary; mediocrity" },
      { chinese: "依然", pinyin: "yīrán", wordType: "adv.", meaning: "still, nonetheless" },
      { chinese: "推荐", pinyin: "tuījiàn", wordType: "v.", meaning: "to recommend" },
      { chinese: "淋漓尽致", pinyin: "línlí jìnzhì", wordType: null, meaning: "fully, thoroughly" },
      { chinese: "评价", pinyin: "píngjià", wordType: "v./n.", meaning: "to evaluate; evaluation, comment" },
      { chinese: "烂", pinyin: "làn", wordType: "adj.", meaning: "bad, lame" },
      { chinese: "主持", pinyin: "zhǔchí", wordType: "v./n.", meaning: "to host, to preside over; host/hostess" },
      { chinese: "运用", pinyin: "yùnyòng", wordType: "v.", meaning: "to put into practice, to apply" },
      { chinese: "开幕式", pinyin: "kāimùshì", wordType: "n.", meaning: "opening ceremony" },
      { chinese: "宁可", pinyin: "nìngkě", wordType: "adv.", meaning: "would rather" },
      { chinese: "集中", pinyin: "jízhōng", wordType: "v./adj.", meaning: "to concentrate, to focus; concentrated" },
      { chinese: "体会", pinyin: "tǐhuì", wordType: "v./n.", meaning: "to learn from experience, to realize; feeling" },
    ],
  },
  {
    chapterNumber: 18,
    words: [
      {
        chinese: "抽象",
        pinyin: "chōuxiàng",
        wordType: "adj./v.",
        meaning: "abstract; to draw a correct conclusion from objective facts",
      },
      { chinese: "古典", pinyin: "gǔdiǎn", wordType: "adj.", meaning: "classical" },
      { chinese: "欣赏", pinyin: "xīnshǎng", wordType: "v.", meaning: "to enjoy, to admire" },
      { chinese: "布", pinyin: "bù", wordType: "n.", meaning: "cloth" },
      { chinese: "规则", pinyin: "guīzé", wordType: "adj./n.", meaning: "regular; rule" },
      {
        chinese: "派",
        pinyin: "pài",
        wordType: "n.",
        meaning: "faction, school, group of people sharing identical ideas, style or tastes",
      },
      { chinese: "作品", pinyin: "zuòpǐn", wordType: "n.", meaning: "work (of art or literature)" },
      { chinese: "洒", pinyin: "sǎ", wordType: "v.", meaning: "to sprinkle, to spray" },
      { chinese: "极其", pinyin: "jíqí", wordType: "adv.", meaning: "extremely" },
      { chinese: "神秘", pinyin: "shénmì", wordType: "adj.", meaning: "mystical, mysterious" },
      { chinese: "丑(陋)", pinyin: "chǒu(lòu)", wordType: "adj.", meaning: "ugly" },
      { chinese: "自由", pinyin: "zìyóu", wordType: "n./adj.", meaning: "freedom; free" },
      { chinese: "设计", pinyin: "shèjì", wordType: "v./n.", meaning: "to design; design" },
      { chinese: "组", pinyin: "zǔ", wordType: "n./m.", meaning: "group, team, set" },
      { chinese: "幅", pinyin: "fú", wordType: "m.", meaning: "used for paintings and scrolls, etc." },
      { chinese: "出自", pinyin: "chūzì", wordType: "v.", meaning: "to come from, to stem from" },
      { chinese: "业余", pinyin: "yèyú", wordType: "adj.", meaning: "amateur" },
      { chinese: "婴儿", pinyin: "yīng'ér", wordType: "n.", meaning: "infant, baby" },
      { chinese: "猩猩", pinyin: "xīngxīng", wordType: "n.", meaning: "gorilla, ape" },
      { chinese: "涂鸦", pinyin: "túyā", wordType: "v.", meaning: "to scrawl" },
      { chinese: "签", pinyin: "qiān", wordType: "v.", meaning: "to sign, to autograph" },
      { chinese: "其余", pinyin: "qíyú", wordType: "pron.", meaning: "the rest, the others" },
      { chinese: "身份", pinyin: "shēnfèn", wordType: "n.", meaning: "identity" },
      { chinese: "确认", pinyin: "quèrèn", wordType: "v.", meaning: "to confirm, to affirm" },
      { chinese: "随手", pinyin: "suíshǒu", wordType: "adv.", meaning: "randomly, without extra trouble" },
      { chinese: "分辨", pinyin: "fēnbiàn", wordType: "v.", meaning: "to distinguish, to differentiate" },
      { chinese: "挥", pinyin: "huī", wordType: "v.", meaning: "to wave, to wield" },
      { chinese: "可见", pinyin: "kějiàn", wordType: "conj.", meaning: "it can be seen that..." },
      { chinese: "哪怕", pinyin: "nǎpà", wordType: "conj.", meaning: "even if" },
      { chinese: "元素", pinyin: "yuánsù", wordType: "n.", meaning: "element" },
      { chinese: "调整", pinyin: "tiáozhěng", wordType: "v./n.", meaning: "to adjust, to revise; adjustment" },
      { chinese: "位置", pinyin: "wèizhì", wordType: "n.", meaning: "position, location" },
      { chinese: "含意", pinyin: "hányì", wordType: "n.", meaning: "implied meaning, implication" },
      { chinese: "区域", pinyin: "qūyù", wordType: "n.", meaning: "region, district" },
      { chinese: "活跃", pinyin: "huóyuè", wordType: "adj./v.", meaning: "active, dynamic; to activate" },
      { chinese: "布局", pinyin: "bùjú", wordType: "n.", meaning: "composition (of a piece of art or writing)" },
      { chinese: "事实", pinyin: "shìshí", wordType: "n.", meaning: "fact" },
      { chinese: "目前", pinyin: "mùqián", wordType: "n.", meaning: "now, present" },
      { chinese: "证据", pinyin: "zhèngjù", wordType: "n.", meaning: "proof, evidence" },
      { chinese: "话题", pinyin: "huàtí", wordType: "n.", meaning: "topic" },
    ],
  },
];
