// HSK1 memory-aid mnemonics (docs/39) — one entry per word new to HSK1.
// Keyed by the exact `chinese` text from prisma's Word.chinese column.
export const hsk1Mnemonics: Record<string, string> = {
  "啊": "啊 (a) has 口 (mouth) on the left — it's the sound your mouth makes when you blurt out a reaction, ah.",
  "爱": "爱 (ài, to love) sounds like 'eye' — you only have eyes for the one you love, and inside the character sits 友 (friend), because love grows from friendship",
  "八": "八 (bā) is just two strokes splayed apart like a wishbone — imagine snapping a wishbone at a party of eight",
  "爸爸": "爸爸 (bàba) stacks the father radical 父 next to 巴 — baba is the easiest word a baby says, right after mama",
  "吧": "吧 (ba) has 口 (mouth) beside 巴 — tack it onto a sentence like a soft nudge from the mouth, 'let's go, ba'",
  "杯子": "杯子 (bēizi, cup) has 木 (wood) on the left, since early cups were carved from wood, and bēi sounds like 'bay' — picture a bay you'd scoop a drink from",
  "北京": "北京 (Běijīng) is 北 (north) plus 京 (capital) — literally the 'northern capital'",
  "本": "本 (běn) is 木 (tree) with an extra line marking the roots — the 'root' character, used to count books since a book is the root of knowledge",
  "不": "不 (bù) looks like a bird flying up and away, refusing to land — just like bù means 'no'.",
  "不客气": "不客气 (bú kèqi) is literally 'don't be a guest about it' — 客 means guest and 气 means manner, so drop the polite guest-manners, you're welcome",
  "不少": "不少 (bùshǎo) is 不 (not) plus 少 (few) — 'not few' flips into a double-negative meaning quite a lot",
  "菜": "菜 (cài) has 艹 (the grass/plant radical) on top — vegetables you pick 采 to cook into a dish",
  "茶": "茶 (chá) has the grass radical 艹 over 木 (tree) — tea leaves growing on a bush, and chá sounds like 'cha' as in a cup of cha",
  "车": "车 (chē) is a simplified pictograph of a cart seen from above, wheels on an axle — chē echoes the start of 'chariot'",
  "吃": "吃 (chī) pairs 口 (mouth) with 乞 (to beg) — begging with your mouth open, hungry to eat",
  "吃饭": "吃饭 (chī fàn) is simply 吃 (eat) plus 饭 (rice/meal) — eat your rice, i.e. eat a meal",
  "出租车": "出租车 (chūzūchē) breaks into 出 (go out) plus 租 (rent) plus 车 (car) — literally a 'go-out rental car', a taxi",
  "打": "打 (dǎ) has the hand radical 扌 next to 丁 (nail) — a hand hammering a nail, to strike or send",
  "打电话": "打电话 (dǎ diànhuà) is 打 (to strike/do) plus 电话 (telephone) — you 'strike up' the telephone to make a call",
  "大": "大 (dà) is a stick figure with arms flung wide open — as big as you can stretch",
  "大卫": "大卫 (Dàwèi) is 大 (big) plus 卫 (guard) — picture a big bodyguard named David",
  "大学": "大学 (dàxué) is 大 (big) plus 学 (study/school) — the 'big school' after regular school, university",
  "的": "的 (de) sounds like 'duh' — the tiny word so obvious it gets tacked onto everything you own",
  "点": "点 (diǎn) has four dots 灬 (fire) at the bottom, like a clock's face lit up with dots marking the hour",
  "电话": "电话 (diànhuà) is 电 (electricity) plus 话 (speech) — words carried by electricity, the telephone",
  "电脑": "电脑 (diànnǎo) is 电 (electricity) plus 脑 (brain) — an electric brain, the computer",
  "电视": "电视 (diànshì) is 电 (electricity) plus 视 (to view) — electric viewing, the television",
  "电影": "电影 (diànyǐng) is 电 (electricity) plus 影 (shadow) — electric shadows flickering on a screen, the movies",
  "东西": "东西 (dōngxi) literally joins 东 (east) and 西 (west) — from goods gathered from every direction, it now just means 'stuff'",
  "都": "都 (dōu) sounds like 'dome' — under one big dome, everybody and everything is covered, all of it",
  "读": "读 (dú) has the speech radical 讠 beside 卖 (sell) — a reader 'sells' the words aloud, to read",
  "对不起": "对不起 (duìbuqǐ) literally means 'cannot face you' — 对 (face) plus 不起 (cannot rise up) — too ashamed to look up, I'm sorry",
  "多": "多 (duō) stacks two 夕 (evening/moon) radicals — night after night after night, that's many",
  "多少": "多少 (duōshao) pairs 多 (many) with 少 (few) — asking 'many or few?' is how you ask how much",
  "儿子": "儿子 (érzi) — 儿 looks like a pair of legs running around, a little boy, your son",
  "二": "二 (èr) is simply two flat strokes stacked — the plainest way to draw 'two'",
  "饭店": "饭店 (fàndiàn) is 饭 (rice/food) plus 店 (shop) — a food shop that doubles as a place for guests to stay, hotel or restaurant",
  "飞机": "飞机 (fēijī) is 飞 (to fly) plus 机 (machine) — a flying machine, the airplane",
  "分": "分 (fēn) has 刀 (knife) under a splitting shape 八 — a knife dividing something into parts, whether minutes or coins",
  "分钟": "分钟 (fēnzhōng) is 分 (divide) plus 钟 (clock) — a clock divided into minutes",
  "高兴": "高兴 (gāoxìng) pairs 高 (tall/high) with 兴 (to rise/excite) — spirits rising sky-high, that's happiness",
  "个": "个 (gè) looks like a single person standing, a stick figure with a pole — the go-to measure word for counting one of almost anything",
  "给": "给 (gěi) has the thread radical 纟 next to 合 (unite) — handing over a thread that ties two people together, to give",
  "工作": "工作 (gōngzuò) — 工 looks like an I-beam, the sign for labor, plus 作 (to do) — doing labor is work",
  "狗": "狗 (gǒu) has the animal radical 犭 (a crouching dog) next to 句 — gǒu sounds like a gruff little growl, a dog's bark",
  "国": "国 (guó) is a box 囗 (a border) wrapped around 玉 (a king's jewel) — a kingdom sealed within its borders, the country",
  "汉语": "汉语 (Hànyǔ) is 汉 (the Han people) plus 语 (language) — the language of the Han, Chinese",
  "汉字": "汉字 (Hànzì) is 汉 (Han) plus 字 (character) — a Han character, i.e. a Chinese character",
  "好": "好 (hǎo, good) is 女 (woman) next to 子 (child) — a mother with her child is a good thing",
  "好吃": "好吃 (hǎochī) is just 好 (good) plus 吃 (eat) — good to eat, delicious",
  "号": "号 (hào) has 口 (mouth) on the left — calling out a number loud, like a shout, hào",
  "喝": "喝 (hē) has 口 (mouth) beside 曷 — hē sounds like a quick 'huh' gulp as you drink",
  "和": "和 (hé) pairs 禾 (grain) with 口 (mouth) — grain and mouths together, everyone fed and joined, 'and'",
  "很": "很 (hěn) sounds like 'hen' — imagine a hen very proud of her very big egg",
  "后": "后 (hòu) sounds like 'ho' — as in 'ho, wait for what comes after'",
  "后面": "后面 (hòumiàn) is 后 (after) plus 面 (side) — the side that comes after, the back",
  "回": "回 (huí) is a little square nested inside a bigger square — going around in a loop and coming back to where you started",
  "回来": "回来 (huílai) is 回 (return) plus 来 (come) — return-come, to come back",
  "会": "会 (huì) sounds like 'hway' — a person who's been sized up and found capable, so they can do it",
  "几": "几 (jǐ) looks like a little stool with just a couple of legs — few enough to count, how many",
  "家": "家 (jiā) is a roof 宀 over 豕 (a pig) — in old China, a house with a pig under the roof meant a family had enough to eat",
  "叫": "叫 (jiào) has 口 (mouth) on the left — jiào sounds like 'jaw', open your jaw and call out a name",
  "今年": "今年 (jīnnián) is 今 (now) plus 年 (year) — the year that is now, this year",
  "今天": "今天 (jīntiān) is 今 (now) plus 天 (day) — the day that is now, today",
  "九": "九 (jiǔ) already curves like the numeral 9 — it even looks like a fishhook, easy to hook onto nine",
  "开": "开 (kāi) looks like two hands prying a bar off a gate — kāi sounds like a door creaking open, 'kaiii'",
  "看": "看 (kàn) stacks 手 (hand) over 目 (eye) — shading your eyes with a hand to look far away",
  "看见": "看见 (kànjiàn) is 看 (to look) plus 见 (to see) — you look, and then you actually see",
  "口": "口 (kǒu) is drawn as a plain open square — a wide-open mouth, and also how families are counted, by 'mouths to feed'",
  "块": "块 (kuài) has the earth radical 土 — a solid lump of earth, and by extension a solid 'chunk' of cash, a yuan",
  "来": "来 (lái) is a pictograph of a person carrying stalks of wheat home — the harvest has arrived, to come",
  "老师": "老师 (lǎoshī) is 老 (old, venerable) plus 师 (master) — an elder master of a subject, the teacher",
  "了": "了 (le) is just a tiny hook stroke — a quick little checkmark you tack on to mark 'done, it happened'",
  "冷": "冷 (lěng) has the two-dot ice radical 冫 on the left — those two icy dots are your first clue it means cold",
  "李": "李 (Lǐ) is 木 (tree) over 子 (child, here meaning fruit) — a plum tree, and also a very common surname, Li",
  "李月": "李月 (Lǐ Yuè) combines the surname 李 (Li, 'plum tree') with 月 (yuè, moon) — picture a plum tree under the moon, a name: Li Yue",
  "里": "里 (lǐ) looks like a field 田 planted in the earth 土 — deep inside the land, inside",
  "六": "六 (liù) has a little roof-like top over two legs — picture a tiny hut sheltering six people packed inside",
  "妈妈": "妈妈 (māma) has 女 (woman) beside 马 (horse) — a woman working hard as a horse for her kids, mama",
  "吗": "吗 (ma) has 口 (mouth) next to 马 (horse) — your mouth trotting up in pitch at the end, turning a statement into a question",
  "买": "买 (mǎi) sits atop where 贝 (shell/money) used to be in the traditional form — reaching down to grab something with money, to buy",
  "猫": "猫 (māo) has the animal radical 犭 next to 苗 — māo sounds just like the meow of a cat",
  "没": "没 (méi) has the water radical 氵 on the left — like something sinking under water and no longer there, 'not have'",
  "没关系": "没关系 (méi guānxi) is 没 (not) plus 关系 (connection/relation) — 'no connection to worry about', it's OK",
  "没有": "没有 (méiyǒu) is simply 没 (not) plus 有 (have) — 'not have', there isn't any",
  "美国": "美国 (Měiguó) is 美 (beautiful) plus 国 (country) — the 'beautiful country', how Chinese refers to the USA",
  "米饭": "米饭 (mǐfàn) is 米 (rice, its shape like scattered grains) plus 饭 (cooked food) — cooked rice",
  "名字": "名字 (míngzi) — 名 stacks 夕 (evening) over 口 (mouth), from calling out someone's name in the dark when you can't see their face; add 字 (word) for a full name",
  "明天": "明天 (míngtiān) is 明 (bright, sun 日 next to moon 月) plus 天 (day) — the next bright day, tomorrow",
  "哪": "哪 (nǎ) has 口 (mouth) on the left — asking aloud 'which one', nǎ",
  "哪儿": "哪儿 (nǎr) is 哪 (which) plus 儿 (the 'r' suffix) — 'which place', where",
  "那": "那 (nà) ends in 阝, the place radical — pointing to a place over there, that",
  "那儿": "那儿 (nàr) is 那 (that) plus 儿 — 'that place', there",
  "呢": "呢 (ne) has 口 (mouth) on the left — ne sounds like a soft 'nuh?' trailing question at a sentence's end",
  "能": "能 (néng) was originally a picture of a bear — strong enough to do anything, hence 'can, able to'",
  "你": "你 (nǐ) has the person radical 亻 on the left — pointing at the person radical right in front of you, you",
  "你们": "你们 (nǐmen) is 你 (you) plus 们 (the plural marker) — not just you, all of you",
  "年": "年 (nián) is an old pictograph of a person carrying a ripe stalk of grain — one harvest cycle, one year",
  "您": "您 (nín) is 你 (you) with 心 (heart) added underneath — putting your heart into how you address someone, the polite 'you'",
  "女儿": "女儿 (nǚ'ér) is 女 (woman/girl) plus 儿 (child) — a girl-child, your daughter",
  "朋友": "朋友 (péngyou) — 朋 is two 月 shapes side by side like two moons keeping each other company, and 友 shows two hands clasped, friends together",
  "漂亮": "漂亮 (piàoliang) pairs 漂 (to float, elegant) with 亮 (bright, shining) — someone who floats in and lights up the room, pretty",
  "苹果": "苹果 (píngguǒ) — 苹 has the plant radical 艹 on top, and 果 shows 木 (tree) topped with a round shape, fruit on a tree, an apple",
  "七": "七 (qī) looks like a cross with the bottom curved like a hook — a small sickle, cutting through to seven",
  "前": "前 (qián) has a boat-like base at the bottom — being at the front, ahead of everyone else, before",
  "前面": "前面 (qiánmiàn) is 前 (before) plus 面 (side) — the side that's before you, the front",
  "钱": "钱 (qián) has the metal radical 钅 on the left — coins are metal, and qián is the word for money",
  "请": "请 (qǐng) has the speech radical 讠 next to 青 (green/fresh) — polite, fresh speech, a request: please",
  "去": "去 (qù) sounds like a puff of air, 'chü' — like exhaling as you head off, to go",
  "热": "热 (rè) has four fire dots 灬 across the bottom — flames licking up from underneath, hot",
  "人": "人 (rén) is drawn as two legs, one striding in front of the other — the simplest picture of a person walking",
  "认识": "认识 (rènshi) — 认 has speech 讠 next to 人 (person), and 识 has speech 讠 next to 只 — talking with a person until you truly know them",
  "三": "三 (sān) is just three flat lines stacked — the simplest possible 'three'",
  "商店": "商店 (shāngdiàn) is 商 (commerce/trade) plus 店 (shop, a roof 广 over a stall 占) — a roofed stall for trade, a shop",
  "上": "上 (shàng) is a short mark sitting above a long baseline — clearly above it, up",
  "上午": "上午 (shàngwǔ) is 上 (before/on top of) plus 午 (noon) — the stretch before noon, morning",
  "少": "少 (shǎo) looks like 小 (small) with one stroke shaved off — even smaller, so few",
  "谁": "谁 (shéi) has the speech radical 讠 next to 隹 (a bird) — calling out into a flock, 'who's there?'",
  "身体": "身体 (shēntǐ) — 身 is an old pictograph of a torso, and 体 shows 亻(person) next to 本 (root/base) — your frame and your foundation together, the body",
  "什么": "什么 (shénme) — 什 pairs the person radical 亻 with 十 (ten, meaning 'various'), and 么 means tiny — asking about all sorts of little things, what",
  "十": "十 (shí) is a simple cross — two lines meeting at the center, all ten fingers crossed together",
  "时候": "时候 (shíhou) — 时 has 日 (sun) marking the passing day, and 候 shows a person 亻 waiting — waiting for the sun to reach the right moment, time",
  "是": "是 (shì) has 日 (sun) on top — as certain and undeniable as the sun being up there, 'to be' true",
  "书": "书 (shū) looks like pages bound together with a single stroke down the spine — a book",
  "水": "水 (shuǐ) is drawn as a central current with little splashes branching off each side — water flowing",
  "水果": "水果 (shuǐguǒ) is 水 (water/juice) plus 果 (fruit, a round shape on a tree 木) — juicy things from a tree, fruit",
  "睡觉": "睡觉 (shuì jiào) — 睡 has 目 (eye) next to 垂 (drooping) — your eyes drooping shut, to sleep",
  "说": "说 (shuō) has the speech radical 讠 next to 兑 (exchange) — exchanging words, to speak",
  "四": "四 (sì) is a box with two strokes inside like little legs — sì sounds like a hushed 'sss', four fingers held up quietly",
  "岁": "岁 (suì) has 山 (mountain) on top — climbing one more mountain each year you age, suì",
  "他": "他 (tā) has the person radical 亻 next to 也 (also) — 'that person, also' — a third person, he",
  "她": "她 (tā) swaps the person radical for 女 (woman) next to 也 — the female version of 'he', she",
  "太": "太 (tài) is 大 (big) with one more dot added — bigger than big, too much, excessively",
  "天": "天 (tiān) is 大 (a big person, arms out) with a line over the head — what's above even a big person's head, the sky, and by extension a day",
  "天气": "天气 (tiānqì) is 天 (sky) plus 气 (air) — the state of the sky and air, weather",
  "听": "听 (tīng) has 口 (mouth) on the left — tīng sounds like 'ting', the little chime you perk your ears up to listen for",
  "同学": "同学 (tóngxué) is 同 (same) plus 学 (study) — someone who studies the same as you, a classmate",
  "王": "王 (Wáng) is drawn as three stacked lines joined by one vertical stroke — a king linking heaven, earth, and man; also a very common surname, Wang",
  "王方": "王方 (Wáng Fāng) pairs the surname 王 (Wang, 'king') with 方 (fāng, 'square/direction') — a king who's very direct and square-dealing, a name: Wang Fang",
  "喂": "喂 (wèi) has 口 (mouth) on the left — wèi is literally the shout of 'hey!' you fling from your mouth, the old-school way to answer a phone",
  "问": "问 (wèn) has 口 (mouth) tucked inside 门 (a gate) — knocking with your mouth, calling through the gate to ask",
  "我": "我 (wǒ) originally pictured a hand gripping a serrated weapon — defending your own turf, that's 'I, me'",
  "我们": "我们 (wǒmen) is 我 (I) plus 们 (the plural marker) — not just me, all of us",
  "五": "五 (wǔ) is an X boxed inside two lines — fingers crossed together, five",
  "喜欢": "喜欢 (xǐhuan) pairs 喜 (joy, with a mouth 口 grinning underneath) and 欢 (delight) — pure double joy, to like something",
  "下": "下 (xià) is a short mark sitting below a long baseline — clearly under it, down below",
  "下面": "下面 (xiàmiàn) is 下 (under) plus 面 (side) — the side underneath, below",
  "下午": "下午 (xiàwǔ) is 下 (after/below) plus 午 (noon) — the stretch after noon, afternoon",
  "下雨": "下雨 (xià yǔ) is 下 (to come down) plus 雨 (rain, drops under a cloud) — rain falling down, to rain",
  "先生": "先生 (xiānsheng) is 先 (first, born before) plus 生 (born) — the one born first, an elder addressed respectfully as 'Mister'",
  "现在": "现在 (xiànzài) is 现 (to appear) plus 在 (to exist) — what's appearing and existing right this moment, now",
  "想": "想 (xiǎng) sits 心 (heart) under 相 (to look at) — looking at something with your heart, wanting it",
  "小": "小 (xiǎo) is just three short strokes pinched together — as small a character as you can draw",
  "小姐": "小姐 (xiǎojiě) is 小 (little) plus 姐 (elder sister) — a 'little sister', the polite term for a young lady",
  "些": "些 (xiē) sits on top of 此 (this) — 'this and a bit more', some, a few",
  "写": "写 (xiě) sounds like 'shyeah' — picture scribbling out a quick note, to write",
  "谢": "谢 (xiè) has the speech radical 讠 next to 射 (to shoot) — shooting out words of gratitude, to thank",
  "谢朋": "谢朋 (Xiè Péng) combines the surname 谢 (Xie) with 朋 (friend) — a name that reads almost like 'thank you, friend'",
  "谢谢": "谢谢 (xièxie) is just 谢 (to thank) said twice — thanking someone twice as hard, thank you",
  "星期": "星期 (xīngqī) is 星 (star) plus 期 (period of time) — originally counting days by the stars' cycle, a week",
  "学": "学 (xué) has 子 (child) under a roof 冖 with crossed strokes above like sparks in the mind — a child under a roof, learning",
  "学生": "学生 (xuésheng) is 学 (to learn) plus 生 (life/growing) — one whose life right now is learning, a student",
  "学习": "学习 (xuéxí) is 学 (to learn) plus 习 (to practice, originally a bird flapping its wings) — learning by practicing again and again",
  "学校": "学校 (xuéxiào) is 学 (to learn) plus 校 (institution, with 木 wood on the left for the old wooden schoolhouse) — the place you learn, school",
  "也": "也 (yě) was once a pictograph of a coiled snake — yě sounds like 'yeah', tacking on an extra 'yeah, me too', also",
  "一": "一 (yī) is a single flat stroke — you can't get more 'one' than that",
  "一点儿": "一点儿 (yīdiǎnr) is 一 (one) plus 点 (a dot/point) — just one tiny dot's worth, a little",
  "一起": "一起 (yìqǐ) is 一 (one) plus 起 (to rise/start) — rising and starting out as one, together",
  "衣服": "衣服 (yīfu) — 衣 is an old pictograph of a robe's collar and sleeves, and 服 adds 'garment' — clothes on your back",
  "医生": "医生 (yīshēng) is 医 (medicine, originally a chest of arrows for treating wounds) plus 生 (life) — one who saves lives with medicine, a doctor",
  "医院": "医院 (yīyuàn) is 医 (medicine) plus 院 (a walled courtyard/institution) — the walled place full of medicine, hospital",
  "椅子": "椅子 (yǐzi) has 木 (wood) on the left, since chairs were made of wood, and yǐ sounds like a little 'ee' as you settle into your seat",
  "有": "有 (yǒu) originally showed a hand holding a piece of meat 月 — holding something in hand, to have",
  "雨": "雨 (yǔ) is drawn as droplets falling under a cloud line — a direct little picture of rain",
  "月": "月 (yuè) is a curved crescent shape — literally the moon, and since months were once tracked by moon cycles, also 'month'",
  "再见": "再见 (zàijiàn) is 再 (again) plus 见 (to see) — 'see you again', goodbye",
  "在": "在 (zài) has 土 (earth) at the base — rooted firmly in the ground at a place, to be at/in",
  "怎么": "怎么 (zěnme) starts with 怎, built from 乍 (suddenly) over 心 (heart) — your heart suddenly puzzled, asking 'how?'",
  "怎么样": "怎么样 (zěnmeyàng) is 怎么 (how) plus 样 (manner/kind) — asking about the manner of something, how's it going",
  "张": "张 (Zhāng) has 弓 (a bow) next to 长 (long) — a long bow drawn taut, and also one of China's most common surnames, Zhang",
  "这": "这 (zhè) has the walking radical 辶 — the thing right in your path as you walk, this",
  "这儿": "这儿 (zhèr) is 这 (this) plus 儿 — 'this place', here",
  "这些": "这些 (zhèxiē) is 这 (this) plus 些 (some) — 'this some', these",
  "中国": "中国 (Zhōngguó) is 中 (middle, a line through a box) plus 国 (country) — the 'middle kingdom', China",
  "中午": "中午 (zhōngwǔ) is 中 (middle) plus 午 (noon) — the exact middle of the day, noon",
  "住": "住 (zhù) has the person radical 亻 next to 主 (host/master) — being the master of your own place, to live",
  "桌子": "桌子 (zhuōzi) has 木 (wood) at the bottom under 卓 (outstanding/tall) — a wooden surface standing tall above the floor, a table",
  "字": "字 (zì) is a child 子 under a roof 宀 — characters are 'born' and raised under the roof of writing, hence 'word, character'",
  "昨天": "昨天 (zuótiān) — 昨 has 日 (sun) next to 乍 (once, suddenly) — the day the sun already went by, yesterday",
  "坐": "坐 (zuò) shows two 人 (people) sitting on top of 土 (earth) — two people plopped down on the ground, to sit",
  "做": "做 (zuò) has the person radical 亻 next to 故 (reason/cause) — a person with a reason behind their actions, to make",
};
