// HSK2 memory-aid mnemonics (docs/39) — one entry per word new to HSK2 (not
// a repeat of HSK1's words, even though HSK2's "combined" word list is
// cumulative and includes them — those already have entries in hsk1.ts).
// Keyed by the exact `chinese` text from prisma's Word.chinese column.
export const hsk2Mnemonics: Record<string, string> = {
  "白": "白 (bái, white) looks like 日 (sun) with a stroke poking out the top — a ray of sunlight so bright it's white.",
  "白色": "白色 is just 白 (white) plus 色 (color) — the color white, literally.",
  "百": "百 (bǎi, hundred) is 白 (white) with an extra top stroke, like a bai that grew a hat — a hundred is a bai and then some.",
  "班": "班 (bān, class/team) has 王 (jade/king) on both sides of 刂 (knife) — carving the group into two neat rows, like a class lined up.",
  "半": "半 (bàn, half) looks like something split down the middle by a vertical line, with two even sides — a picture of halving.",
  "帮": "帮 (bāng, to help) sounds like bang — imagine banging on someone's door because they need help.",
  "帮助": "帮助 doubles up 帮 (to help) and 助 (to assist) — two helping words stacked for extra help.",
  "报纸": "报纸 (bàozhǐ, newspaper) has 纸 (paper) — a report printed on paper is a newspaper.",
  "杯": "杯 (bēi, cup) has 木 (wood) beside 不 — old cups were carved from wood; picture a wooden cup you sip from.",
  "比": "比 (bǐ, than) is two nearly identical hooked strokes standing side by side, like two things placed next to each other to compare.",
  "便宜": "便宜 (piányi, cheap) — think 'pian' as in 'plain,' a plain price with nothing fancy added, so it's cheap.",
  "别": "别 (bié, don't) has 刀 (knife)-like 刂 on the right — a sharp 'don't' cuts off an action before it happens.",
  "宾馆": "宾馆 (bīnguǎn, hotel) has 宀 (roof) over 宾 (guest) — a roof for guests is exactly what a hotel is.",
  "病": "病 (bìng, illness) is wrapped in 疒, the sickness radical (a person lying on a sickbed) — any character with that shape as a shell means illness.",
  "不错": "不错 (búcuò) is literally 'not wrong' — 不 (not) plus 错 (wrong) — and 'not wrong' is how Chinese says 'pretty good.'",
  "唱歌": "唱歌 (chàng gē, to sing) has 口 (mouth) inside 唱 — you open your mouth twice over to belt out a song.",
  "出": "出 (chū, to go out) looks like a shape poking further out of a box than 山 does — something sticking out and going forth.",
  "出院": "出院 combines 出 (to exit) with 院 (hospital/institution) — exiting the hospital, i.e. discharged.",
  "穿": "穿 (chuān, to wear) has 穴 (cave/hole) over 牙 (tooth) — pushing something through a hole, like poking your arm through a sleeve to wear it.",
  "次": "次 (cì, time/occurrence) sounds like 'tsuh' — think of a tally mark each time something happens, counting occurrences.",
  "从": "从 (cóng, from) is literally two 人 (person) characters, one following the other — one person coming from behind another, i.e. following from.",
  "错": "错 (cuò, wrong) has 金 (metal) beside 昔 (past) — an old rusted metal tool no longer works right, so it's wrong.",
  "打篮球": "打篮球 (dǎ lánqiú) is 打 (to hit/play) plus 篮球 (basketball, literally 'basket ball') — hitting the ball into the basket.",
  "打球": "打球 (dǎqiú, to play ball) is just 打 (to hit) plus 球 (ball) — hitting a ball around, the generic 'play ball.'",
  "大家": "大家 (dàjiā, everybody) is 大 (big) plus 家 (family/home) — one big family, meaning everyone together.",
  "但是": "但是 (dànshì, but) — think of 但 alone as 'but,' with 是 (is) tacked on for emphasis: 'but, it is...'",
  "到": "到 (dào, to arrive) has 至 (arrive/reach) beside 刂 — a sharp, decisive arrival, cutting straight to the destination.",
  "到时候": "到时候 (dào shíhou) is 到 (arrive) plus 时候 (time) — 'when the time arrives,' i.e. 'by then.'",
  "得": "得 (de) sits after a verb like a little tag; picture it as the 'result stamp' you 'get' (dé) once an action is done well.",
  "等": "等 (děng, to wait) has 竹 (bamboo) over 寺 (temple) — monks waiting patiently under bamboo at a temple.",
  "弟弟": "弟弟 (dìdi, younger brother) repeats 弟, the character showing a rope wound around a pole in order — the younger sibling in the ordered line.",
  "第一": "第一 (dì yī, first) has 竹 (bamboo) over 弟 (younger brother, but also 'sequence') — 一 (one) makes it the very first in the sequence.",
  "点儿": "点儿 (diǎnr) is 点 (dot/point) with the diminutive 儿 — just a tiny dot's worth, i.e. 'a little bit.'",
  "懂": "懂 (dǒng, to understand) has 忄 (heart) beside 董 — when your heart finally grasps something, it clicks and you understand.",
  "度": "度 (dù, degree) — picture a thermometer scale under a roof-like top stroke, marking off degrees one by one.",
  "对": "对 (duì, to/for) is two short strokes over 寸 (a hand/inch) — facing directly toward something, aimed 'at' or 'for' it.",
  "饭": "饭 (fàn, meal/rice) has 饣 (food radical) beside 反 — any character with 饣 on the left is about eating, and rice is the classic meal.",
  "饭馆": "饭馆 (fànguǎn, restaurant) is 饭 (meal) plus 馆 (building/hall) — a hall for meals is a restaurant.",
  "房间": "房间 (fángjiān, room) is 房 (house) plus 间 (space between, like a gap between two doors 门) — the space inside a house is a room.",
  "房子": "房子 (fángzi, house) is 房 (house/room) with the noun suffix 子 — a plain word for a house or building.",
  "非常": "非常 (fēicháng, very) is 非 (not) plus 常 (ordinary) — 'not ordinary,' meaning extraordinarily, i.e. 'very.'",
  "粉": "粉 (fěn, pink) has 米 (rice) beside 分 (divide/portion) — ground rice powder is pale pink-white, giving the color its name.",
  "粉色": "粉色 pairs 粉 (pink/powder) with 色 (color) — spelling out 'pink color' explicitly.",
  "服务员": "服务员 (fúwùyuán, attendant) is 服务 (to serve) plus 员 (member/person) — a person whose job is to serve you.",
  "高": "高 (gāo, tall) looks like a tall building with a roof on top and a door below — a tower shape standing tall.",
  "告诉": "告诉 (gàosu, to tell) is 告 (to announce) plus 诉 (to speak/complain, with the speech radical 讠) — announcing something with words, i.e. telling someone.",
  "哥哥": "哥哥 (gēge, elder brother) repeats 哥, which contains 可 twice — think of him as the 'okay okay' brother who always agrees, being the responsible elder.",
  "跟": "跟 (gēn, with) has 足 (foot) beside 艮 — your foot follows right along with someone, i.e. going 'with' them.",
  "更": "更 (gèng, more) looks like 束 with a top hat added — piling more on top of what was already there.",
  "公共汽车": "公共汽车 (gōnggòng qìchē, bus) is 公共 (public) plus 汽车 (steam/gas vehicle, i.e. car) — a public car for everyone, the bus.",
  "公斤": "公斤 (gōngjīn, kilogram) is 公 (public/official) plus 斤 (catty, a weight unit) — the official, standardized weight unit, the kilogram.",
  "公司": "公司 (gōngsī, company) is 公 (public) plus 司 (to manage/administer) — a body that manages public/shared business, a company.",
  "贵": "贵 (guì, expensive) has 贝 (shell/money, the currency radical) at the bottom — anything built on the money radical costs you dearly.",
  "过": "过 (guò, to pass/spend time) has 辶 (walking radical) — walking past something, letting time pass by.",
  "还": "还 (hái, still/rather) has 辶 (walking radical) beside 不 (not) — you haven't stopped walking yet, you're 'still' going, or going 'rather' further than expected.",
  "孩子": "孩子 (háizi, child) has 子 (child) on the right — the core meaning is baked right into the character.",
  "黑": "黑 (hēi, black) shows 灬 (fire dots) under a chimney shape — soot from a fire blackens everything above it.",
  "红": "红 (hóng, red) has 纟 (silk thread) beside 工 — dyed red silk thread, the color of celebration.",
  "红色": "红色 is simply 红 (red) plus 色 (color) — 'red color,' spelled out plainly.",
  "花花": "花花 (Huāhua) doubles 花 (flower) — a cute, flowery double name, fitting for a pet cat.",
  "欢": "欢 (huān, joyful) has 又 (hand/again) beside 欠 (lack/yawn, but also open mouth) — an open, cheering mouth again and again in joy.",
  "欢迎": "欢迎 (huānyíng, to welcome) is 欢 (joyful) plus 迎 (to greet, with the walking radical 辶) — joyfully walking out to greet someone, welcoming them.",
  "火车站": "火车站 (huǒchēzhàn, railway station) is 火车 (fire vehicle, i.e. train — old trains ran on steam/fire) plus 站 (station) — the fire-vehicle's stop.",
  "机场": "机场 (jīchǎng, airport) is 飞机's 机 (machine, short for airplane) plus 场 (field/ground) — the ground where flying machines land.",
  "鸡蛋": "鸡蛋 (jīdàn, egg) is 鸡 (chicken) plus 蛋 (egg) — literally 'chicken egg.'",
  "见": "见 (jiàn, to see) looks like 目 (eye) sitting on top of legs — an eye out walking around, going to see something.",
  "件": "件 (jiàn, measure word for items) has 亻(person) beside 牛 (ox/cow) — a person dividing up an ox into separate pieces, hence a counter for individual items.",
  "教室": "教室 (jiàoshì, classroom) is 教 (to teach) plus 室 (room) — the room where teaching happens.",
  "接": "接 (jiē, to receive) has 扌 (hand) beside 妾 — reaching out a hand to receive or pick someone up.",
  "姐姐": "姐姐 (jiějie, elder sister) repeats 姐, which has 女 (woman) beside 且 — doubling up the woman radical for the sister who came first.",
  "介绍": "介绍 (jièshào, to introduce) — 介 looks like a person standing between two things, bridging them, which is exactly what an introduction does.",
  "斤": "斤 (jīn, catty/weight unit) looks like a small axe — an old tool used to measure and chop out portions of weight.",
  "近": "近 (jìn, near) has 辶 (walking radical) beside 斤 (axe, small unit) — only a small step's walk away, so it's near.",
  "进": "进 (jìn, to enter) has 辶 (walking radical) beside 井 (well) — walking down into a well-like opening, going in.",
  "经常": "经常 (jīngcháng, often) is 经 (to pass through, as in经过) plus 常 (ordinary/constant) — something that passes through your life constantly, i.e. often.",
  "就": "就 (jiù) sounds like 'jyo' — think of it as the word that clinches a decision, 'that settles it, so...'",
  "觉得": "觉得 (juéde, to think/feel) is 觉 (to sense/realize, with 见 'see' at the bottom) plus 得 (get) — sensing and arriving at a feeling.",
  "咖啡": "咖啡 (kāfēi, coffee) is a sound loan — kāfēi mimics the English word 'coffee' almost exactly.",
  "开始": "开始 (kāishǐ, to begin) is 开 (to open) plus 始 (to start, with 女 'woman' beside 台) — opening up the start of something.",
  "考试": "考试 (kǎoshì, exam) is 考 (to test) plus 试 (to try, with 讠speech radical) — testing your knowledge by trying to answer.",
  "可能": "可能 (kěnéng, maybe) is 可 (can/may) plus 能 (be able to) — something that 'can be able to' happen, i.e. it's possible.",
  "可以": "可以 (kěyǐ) here means 'not bad' — think of it as a modest nod: 'it can be done, it's fine.'",
  "课": "课 (kè, class/lesson) has 讠(speech radical) beside 果 (fruit/result) — a lesson delivered by speech that bears fruit in learning.",
  "快": "快 (kuài, fast) has 忄 (heart) beside 夬 — your heart races when things move fast.",
  "快乐": "快乐 (kuàilè, happy) is 快 (fast/quick) plus 乐 (joy/music) — a quick burst of joy, like music that lifts your mood instantly.",
  "累": "累 (lèi, tired) has 田 (field) over 糸 (thread/silk) — a farmer worn out after threading through the fields all day.",
  "离": "离 (lí, away from) — the shape looks like something splitting off and separating from a whole, drifting away from it.",
  "两": "两 (liǎng, two) looks like a symmetrical shape split evenly in half, two matching sides — a natural picture of a pair.",
  "零": "零 (líng, zero) has 雨 (rain) over 令 (command) — like raindrops scattering to nothing, vanishing to zero.",
  "路": "路 (lù, road) has 足 (foot) beside 各 (each) — each foot takes its own path down the road.",
  "路口": "路口 (lùkǒu, crossroads) is 路 (road) plus 口 (mouth/opening) — the opening where roads meet, a crossing.",
  "旅游": "旅游 (lǚyóu, to travel) is 旅 (to travel/troop) plus 游 (to roam, with 氵water radical) — roaming freely like water, taking a trip.",
  "卖": "卖 (mài, to sell) sits atop 买 (to buy) with an extra stroke — add one line to 'buy' and it flips to 'sell,' the two sides of a transaction.",
  "慢": "慢 (màn, slow) has 忄 (heart) beside 曼 (long, stretched) — your heart rate stretched long and unhurried, taking it slow.",
  "忙": "忙 (máng, busy) has 忄 (heart) beside 亡 (to lose/die) — your heart feels like it's dying from how busy you are.",
  "每": "每 (měi, every) has 母 (mother) hidden inside — a mother who tends to every single one of her children.",
  "每天": "每天 (měi tiān, every day) is 每 (every) plus 天 (day/sky) — every single day.",
  "妹妹": "妹妹 (mèimei, younger sister) repeats 妹, with 女 (woman) beside 未 (not yet) — the sister who has 'not yet' grown up, the younger one.",
  "门": "门 (mén, door) is a simple pictograph of a two-panel swinging door — it looks exactly like a doorway.",
  "米": "米 (mǐ, meter) — the measurement unit borrows the character for rice grains, small scattered marks like tick marks on a ruler.",
  "面条": "面条 (miàntiáo, noodles) is 面 (flour/face) plus 条 (strip) — flour rolled out into long strips, i.e. noodles.",
  "明年": "明年 (míngnián, next year) is 明 (bright/next, as in 明天 'tomorrow') plus 年 (year) — the bright year ahead, next year.",
  "拿": "拿 (ná, to hold) has 合 (to combine/close) over 手 (hand) — closing your hand around something to hold it.",
  "男": "男 (nán, man) is 田 (field) over 力 (strength) — a man is the one out in the field using his strength.",
  "牛奶": "牛奶 (niúnǎi, milk) is 牛 (cow/ox) plus 奶 (milk, with 女 woman radical, nursing) — milk that comes from a cow.",
  "女": "女 (nǚ, woman) is a pictograph of a kneeling figure with arms crossed gracefully — one of the oldest, simplest radicals.",
  "女孩儿": "女孩儿 (nǚháir, girl) is 女 (woman) plus 孩 (child) plus 儿 — a female child, a girl.",
  "旁边": "旁边 (pángbiān, beside) is 旁 (side) plus 边 (edge/side) — doubling the 'side' meaning to sit right alongside something.",
  "跑步": "跑步 (pǎobù, to run) has 足 (foot) beside 包 (wrap/bag) plus 步 (step) — feet pumping through steps, running.",
  "票": "票 (piào, ticket) has 示 (show) under a top piece — you show your slip of paper, the ticket, to get in.",
  "妻子": "妻子 (qīzi, wife) has 女 (woman) at the bottom of 妻 — the woman of the house, the wife.",
  "起": "起 (qǐ, to rise) has 走 (to walk) beside 己 (self) — getting yourself up and walking, rising to your feet.",
  "起床": "起床 (qǐchuáng, to get up) is 起 (to rise) plus 床 (bed) — rising up out of bed.",
  "千": "千 (qiān, thousand) looks like 十 (ten) with a stroke through it — ten intensified into a much bigger number, a thousand.",
  "铅笔": "铅笔 (qiānbǐ, pencil) is 铅 (lead, with 钅metal radical) plus 笔 (writing brush/pen) — a 'lead pen,' the pencil.",
  "前边": "前边 (qiánbian, front) is 前 (front/before) plus 边 (side) — the side that faces forward, the front.",
  "晴": "晴 (qíng, sunny) has 日 (sun) beside 青 (blue-green/clear) — a clear blue sky with the sun out, sunny weather.",
  "去年": "去年 (qùnián, last year) is 去 (to go/leave) plus 年 (year) — the year that has already gone, last year.",
  "让": "让 (ràng, to let) has 讠(speech radical) beside 上/上让 shape — using words to yield the floor to someone, letting them go ahead.",
  "日": "日 (rì, day/sun) is a pictograph of the sun with a stroke inside it — the sun marks the day.",
  "上班": "上班 (shàngbān, to work) is 上 (to go up/attend) plus 班 (team/shift) — going up to join your work shift.",
  "生病": "生病 (shēng bìng, to fall ill) is 生 (to arise/be born) plus 病 (illness) — an illness being born in you, falling sick.",
  "生日": "生日 (shēngrì, birthday) is 生 (to be born) plus 日 (day) — literally your 'birth day.'",
  "时间": "时间 (shíjiān, time) is 时 (time/hour, with 日 sun radical) plus 间 (space between) — the space that flows between moments, time.",
  "事情": "事情 (shìqíng, matter) is 事 (affair/thing) plus 情 (feeling, with 忄heart radical) — a matter that involves your feelings, an affair to deal with.",
  "手": "手 (shǒu, hand) is a pictograph of an open palm with fingers splayed out — it looks like a simplified hand.",
  "手表": "手表 (shǒubiǎo, watch) is 手 (hand) plus 表 (surface/display) — the display you wear on your hand, a wristwatch.",
  "手机": "手机 (shǒujī, cell phone) is 手 (hand) plus 机 (machine) — the machine you hold in your hand.",
  "睡": "睡 (shuì, to sleep) has 目 (eye) beside 垂 (to droop/hang down) — your eyes drooping shut as you fall asleep.",
  "说话": "说话 (shuōhuà, to speak) is 说 (to say) plus 话 (words/speech) — saying words out loud, speaking.",
  "送": "送 (sòng, to send) has 辶 (walking radical) beside 关-like top — walking a gift or a person over to deliver it.",
  "虽然": "虽然 (suīrán, although) has 虫 (insect) tucked inside 虽 — even though a bug is buzzing around (a complication), the sentence continues anyway — that's the 'although' feel.",
  "所以": "所以 (suǒyǐ, therefore) — think of 所 as 'the place/reason' and 以 as 'by means of' — by means of that reason, therefore.",
  "它": "它 (tā, it) has 宀 (roof) over 匕 — a small creature under a roof, not a person, hence 'it' for animals and things.",
  "踢": "踢 (tī, to kick) has 足 (foot) beside 易 (easy) — it's easy for a foot to just kick something.",
  "踢足球": "踢足球 (tī zúqiú, to play football) is 踢 (to kick) plus 足球 (foot ball, i.e. soccer) — kicking the foot-ball.",
  "题": "题 (tí, question/topic) has 页 (page/head) beside 是 — the heading on a page of an exam, the topic or question.",
  "跳舞": "跳舞 (tiào wǔ, to dance) is 跳 (to jump, with 足 foot radical) plus 舞 (to dance) — jumping and moving your feet to dance.",
  "听说": "听说 (tīngshuō, to hear about) is 听 (to listen) plus 说 (to say) — hearing what others have said, i.e. hearsay.",
  "外": "外 (wài, outside) has 夕 (evening/moon) beside 卜 — divination was traditionally done outdoors in the evening, giving 外 its 'outside' sense.",
  "外边": "外边 (wàibian, outside) is 外 (outside) plus 边 (side) — the outer side of something.",
  "外面": "外面 (wàimiàn, outside) is 外 (outside) plus 面 (face/surface) — the outer face of a place, outside.",
  "完": "完 (wán, to finish) has 宀 (roof) over 元 (origin/first) — once the roof is finally placed on a building from its very foundation, the job is complete.",
  "玩儿": "玩儿 (wánr, to play) has 王-like 玉 (jade) beside 元 — children playing with a little jade toy, having fun.",
  "晚上": "晚上 (wǎnshang, evening) is 晚 (late, with 日 sun radical) plus 上 (on) — when the sun runs late, it's evening.",
  "往": "往 (wǎng, towards) has 彳 (step radical) beside 主 (main/lord) — stepping in the main direction toward a destination.",
  "为什么": "为什么 (wèi shénme, why) is 为 (for/because of) plus 什么 (what) — literally 'for what,' i.e. why.",
  "问题": "问题 (wèntí, question/problem) is 问 (to ask, with 口 mouth inside a door 门) plus 题 (topic) — a topic you ask about, a question.",
  "午饭": "午饭 (wǔfàn, lunch) is 午 (noon) plus 饭 (meal) — the meal eaten at noon, lunch.",
  "西瓜": "西瓜 (xīguā, watermelon) is 西 (west) plus 瓜 (melon) — watermelons were said to have arrived in China from the west, hence 'western melon.'",
  "希望": "希望 (xīwàng, to hope) is 希 (rare/hope for) plus 望 (to gaze at, with 月 moon) — gazing hopefully at something rare and wished-for.",
  "洗": "洗 (xǐ, to wash) has 氵(water radical) beside 先 (first) — the first thing you do with water is wash.",
  "小时": "小时 (xiǎoshí, hour) is 小 (small) plus 时 (time) — a small slice of time, an hour.",
  "笑": "笑 (xiào, to smile) has 竹 (bamboo) over 夭 — bamboo leaves curving upward like the corners of a smiling mouth.",
  "新": "新 (xīn, new) has 斤 (axe) beside 立木 — freshly chopping new wood with an axe, something newly made.",
  "新京": "新京 (Xīnjīng) is 新 (new) plus 京 (capital) — literally 'new capital,' fitting as a hotel name evoking a grand city.",
  "新年": "新年 (xīnnián, New Year) is 新 (new) plus 年 (year) — the new year, plainly.",
  "姓": "姓 (xìng, surname) has 女 (woman) beside 生 (birth) — ancient clan names traced through the mother's birth line.",
  "休息": "休息 (xiūxi, to rest) — 休 shows 亻(person) leaning against 木 (tree), a person resting against a tree trunk.",
  "雪": "雪 (xuě, snow) has 雨 (rain) over 彐-like top — frozen rain falling from the sky, snow.",
  "颜色": "颜色 (yánsè, color) is 颜 (face/complexion) plus 色 (color) — the color and hue of one's face and everything else, color in general.",
  "眼睛": "眼睛 (yǎnjing, eye) has 目 (eye radical) in both characters — doubly marked as being about eyes.",
  "羊肉": "羊肉 (yángròu, mutton) is 羊 (sheep, a pictograph of a sheep's head with horns) plus 肉 (meat) — meat from a sheep.",
  "杨": "杨 (Yáng, surname) has 木 (tree) beside 阳 (sun/yang) — named after the poplar tree, a common Chinese surname.",
  "杨笑笑": "杨笑笑 (Yáng Xiàoxiào) is the surname 杨 (Yang) plus a doubled 笑 (to smile) — a cheerful-sounding name, someone always smiling.",
  "药": "药 (yào, medicine) has 艹 (grass/plant radical) over 约 — medicine traditionally came from herbs and plants.",
  "要": "要 (yào, to want) has 覀 (west-like cover) over 女 (woman) — picture reaching eagerly for something you want, covering it with both hands.",
  "一下": "一下 (yīxià) is 一 (one) plus 下 (down/below) — doing something just 'once, briefly,' a quick attempt.",
  "一直": "一直 (yīzhí, straight/all along) is 一 (one) plus 直 (straight) — going in one straight line the whole time, continuously.",
  "已经": "已经 (yǐjīng, already) — 已 alone means 'already stopped/ceased,' and 经 (to pass through) reinforces that the event has already happened.",
  "以后": "以后 (yǐhòu, after) is 以 (by means of/from) plus 后 (behind/after) — from this point onward, afterwards.",
  "意思": "意思 (yìsi, meaning) is 意 (idea, with 心 heart at the bottom) plus 思 (to think, also with 心) — the idea your heart is thinking of, the meaning behind words.",
  "因为": "因为 (yīnwèi, because) has 因 (cause, a person 大 boxed inside 囗) — the cause boxed in, the reason why, 'because.'",
  "阴": "阴 (yīn, overcast) has 阝(mound) beside 月 (moon) — the shady side of a hill where the sun rarely reaches, an overcast feel.",
  "游泳": "游泳 (yóuyǒng, to swim) has 氵(water radical) in both characters — twice marked with water, unmistakably about swimming.",
  "友": "友 (yǒu, friend) looks like two hands clasped together — friends joining hands, as seen in 朋友.",
  "有点儿": "有点儿 (yǒudiǎnr, a little) is 有 (to have) plus 点儿 (a dot's worth) — having just a small dot of something, a little bit.",
  "有意思": "有意思 (yǒu yìsi, interesting) is 有 (to have) plus 意思 (meaning) — something that 'has meaning' to you, i.e. it's interesting.",
  "右": "右 (yòu, right direction) has 口 (mouth) under a hand-like top stroke — most people eat with their right hand near their mouth.",
  "右边": "右边 (yòubiān, right side) is 右 (right) plus 边 (side) — the right-hand side.",
  "鱼": "鱼 (yú, fish) is a pictograph of a fish — head at top, body and fins in the middle, tail as the bottom cross-strokes.",
  "远": "远 (yuǎn, far) has 辶 (walking radical) beside 元 (origin) — you'd have to walk all the way back to the very origin, a long way off.",
  "运动": "运动 (yùndòng, sport) is 运 (to move, with 辶 walking radical) plus 动 (to move/act) — doubled motion, i.e. physical exercise.",
  "再": "再 (zài, again) looks like a stack with an extra layer piled on top of an existing shape — doing something one more time, again.",
  "早": "早 (zǎo, early) has 日 (sun) over 十 — the sun just barely up, early in the morning.",
  "早上": "早上 (zǎoshang, morning) is 早 (early) plus 上 (on/at) — at the early part of the day, morning.",
  "长": "长 (cháng, long) is a pictograph of long flowing hair or a beard — something stretched out and long.",
  "丈夫": "丈夫 (zhàngfu, husband) has 夫 (man/husband, a pictograph of a man with a hairpin, an adult) — an adult man who's the head of household, husband.",
  "找": "找 (zhǎo, to look for) has 扌(hand radical) beside 戈 (spear) — reaching out a hand, even grabbing a weapon if needed, to search for something.",
  "这么": "这么 (zhème, so/such) is 这 (this) plus 么 (a light suffix) — 'this-way,' meaning 'so' or 'like this.'",
  "着": "着 (zhe) attaches right after a verb like a sticker, marking that the action is still 'stuck' in an ongoing state.",
  "真": "真 (zhēn, really) has 十 (ten) capped on top of a boxed shape — ten confirmations stacked up, so it must really be true.",
  "正在": "正在 (zhèngzài, in the process of) is 正 (exactly/right) plus 在 (at/in) — 'right at' this moment, in the middle of doing something.",
  "知道": "知道 (zhīdào, to know) is 知 (to know, with 矢 arrow beside 口 mouth) plus 道 (way/path) — knowing the way of things.",
  "准备": "准备 (zhǔnbèi, to plan) is 准 (accurate/to allow) plus 备 (to prepare) — accurately preparing for something, planning it out.",
  "自己": "自己 (zìjǐ, self) is 自 (self, a pictograph of a nose — people point to their nose to mean 'me') plus 己 (oneself) — doubled up for emphasis on 'self.'",
  "自行车": "自行车 (zìxíngchē, bike) is 自 (self) plus 行 (to go/move) plus 车 (vehicle) — a vehicle that moves by itself, powered by you.",
  "走": "走 (zǒu, to walk) has 土 (earth) over legs in motion — feet moving across the earth, walking.",
  "最": "最 (zuì, most) has 曰 (say) under 冃-like top — picture piling everything up to the very top, the highest degree, 'most.'",
  "左边": "左边 (zuǒbiān, left side) is 左 (left) plus 边 (side) — the left-hand side.",
};
