// HSK3 memory-aid mnemonics (docs/39) — one entry per word new to HSK3 (not
// a repeat of HSK1/HSK2's words, even though HSK3's "combined" word list is
// cumulative and includes them — those already have entries in hsk1.ts/
// hsk2.ts).
// Keyed by the exact `chinese` text from prisma's Word.chinese column.
export const hsk3Mnemonics: Record<string, string> = {
  "阿姨": "阿姨 (āyí) has the 女 woman radical in 姨 — the 阿 prefix is a friendly, familiar tag, like saying ah, auntie when she walks in.",
  "矮": "矮 (ǎi) has 矢 (arrow) on the left — picture a short arrow next to a short person; contrast with 短 (duǎn) which is for objects, not height.",
  "爱好": "爱好 is just 爱 (love) plus 好 (good) — the thing you love that's good for you is your hobby.",
  "安静": "安 is a roof 宀 over 女 (woman) — a peaceful household; 静 adds 青 (calm green) settling after 争 (fighting stops) — together, peace and quiet.",
  "把": "把 is 扌 (hand) next to 巴 (cling on) — you grab an object by its handle before doing something to it, which is exactly the grammar job 把 does.",
  "搬": "搬 is 扌 (hand) plus 般 (a kind/sort) — hands hauling all sorts of boxes when you move house.",
  "办法": "办法 pairs 办 (to handle) with 法 (method) — the method you use to handle a problem.",
  "办公室": "办公室 is the 室 (room) where you 办公, handle public business — the office.",
  "办事": "办事 is literally handle (办) affairs (事) — getting things done at the office.",
  "帮忙": "帮忙 pairs 帮 (help) with 忙 (busy, 忄heart + 亡) — when someone's heart is too busy, you lend a hand.",
  "包": "包 is a wrap 勹 curled around 巳 — a bundled-up shape, like a bag.",
  "饱": "饱 is 饣 (food radical) next to 包 (wrapped up) — food wrapped up tight inside you, stuffed full.",
  "北方": "北 shows two people 匕匕 standing back to back — one facing north, one south; add 方 (direction) for the northern region.",
  "被": "被 has 衤 (clothing radical) — the passive voice drapes over the subject like being covered by a garment, something is done to you.",
  "鼻子": "鼻 sits atop 自, which originally was a pictograph of a nose before it came to mean self — point to your own nose and you're pointing at 自.",
  "比较": "比 is two 匕 side by side, comparing; 较 adds the cart radical 车 — comparing two cars to see which is rather better.",
  "比赛": "比 (compare) plus 赛, a roof 宀 over 贝 (shell/money) — a contest comparing who wins the prize.",
  "笔记本": "笔 is 竹 (bamboo) over 毛 (hair), an old brush; 记 means record; 本 means book — a pen that records in a book, a notebook.",
  "笔记本电脑": "笔记本 (notebook) plus 电脑, literally electric brain — a notebook-shaped electric brain, the laptop.",
  "必须": "必 is a heart 心 with a stroke piercing straight through it — a feeling so sharp you simply must act on it.",
  "边": "边 combines 辶 (walk) with a border-like top — walking right along the edge of something, the side.",
  "变": "变 looks like tangled threads being pulled apart by a hand 又 at the bottom — reshaping something into a different form, to change.",
  "变化": "变 (change) plus 化, a person 亻 flipped by 匕 — a person turned around is transformed, change.",
  "表": "表 was originally a coat worn with the fur showing outward — what's on the surface; a watch shows time right on its face.",
  "别人": "别 already means other, as in 别的 — add 人 (person) and you get other people.",
  "冰箱": "冰 is 冫(ice) beside 水 (water) — frozen water; 箱 is a bamboo-topped box — the box that makes ice, a fridge.",
  "不但": "不但 pairs not (不) with but (但, 亻person + 旦 dawn) — not only... but also, the classic partner of 而且.",
  "才": "才 looks like 木 (tree) missing a stroke — a sapling that has only just now sprouted, hence only then, just.",
  "菜单": "菜 has 艹 (grass) on top for vegetables/dishes; 单 means single or list — a list of dishes, the menu.",
  "参加": "参加 pairs 参 (to join) with 加 (to add) — you add yourself to something by joining in.",
  "草": "草 wears the grass radical 艹 right on top — plainly, grass.",
  "层": "层 stacks a roof-like 尸 over lower strokes — layers piled on layers, like the floors of a building.",
  "差": "差 looks slightly crooked and uneven on the page — something crooked falls short of the mark.",
  "常常": "常 (constant) doubled up — doing something over and over, constantly — often.",
  "唱": "唱 is 口 (mouth) beside 昌 (bright, two suns 日日) — mouths belting it out bright and loud, singing.",
  "超市": "超 is 走 (run) plus 召 (call) — running past and beyond; 市 is market — a market so big it exceeds a normal shop, a supermarket.",
  "衬衫": "Both characters carry 衤, the clothing radical — garments for your torso, a shirt.",
  "成绩": "成 (to succeed) plus 绩, a silk thread 纟 finished into cloth — the woven result of your effort, your grade.",
  "城市": "城 is earth 土 plus 成 (become) — earthen walls that became a city; add 市 (market) for the city itself.",
  "迟到": "迟 combines 辶 (walk) with 尺 (ruler/measure) — walking too slowly against the measure of time; 到 is arrive — arriving late.",
  "出生": "出 shows a foot stepping out of an enclosure; 生 is life/grow — stepping out into life, being born.",
  "除了": "除 has 阝 (a mound, a boundary) beside 余 (remainder) — set the boundary and what's left over is other than that.",
  "船": "船 wears the boat radical 舟 — a vessel carrying you across water, a boat.",
  "春": "春 has sprouting plant strokes sitting over 日 (sun) — the sun warming seedlings into growth, spring.",
  "春节": "春 (spring) plus 节 (festival) — the festival that marks the turn into spring, Chinese New Year.",
  "春天": "春 (spring) plus 天 (day/sky) — the days of spring.",
  "词典": "词 carries 讠 (speech radical); 典 looks like a book resting on a stand — a canon of words, a dictionary.",
  "词语": "词 (word, 讠speech) plus 语 (language, 讠speech + 吾 I/me) — speech doubled up into words and expressions.",
  "聪明": "聪 has the ear radical 耳 — sharp hearing; 明 is bright (日 sun + 月 moon) — sharp ears and a bright mind, clever.",
  "打扫": "打 is 扌 (hand) doing something; 扫 is 扌 (hand) plus 帚 (broom) — hands sweeping with a broom, to clean.",
  "打算": "打 (to do) plus 算, bamboo counting rods 竹 over 目 — calculating what you're going to do, a plan.",
  "大夫": "大 (big) plus 夫 (man) — the big man you trust with your health, read specially as dàifu for doctor.",
  "带": "带 looks like a sash with things dangling from it — you bring things tied to your belt.",
  "担心": "担 is 扌 (hand) plus 旦 (dawn) — carrying a burden; add 心 (heart) — carrying a heavy heart, to worry.",
  "蛋糕": "蛋 is egg-shaped on the page; 糕 has the rice radical 米 plus 羔 (lamb) — a cake made rich with rice flour and eggs.",
  "当然": "当 means to act as; 然 (like this, with 犬 dog over 灬 fire) means so — acting as it naturally should, of course.",
  "地": "地 is earth 土 beside 也 — the grounding particle that links an adverb to the verb it modifies, like solid ground under the action.",
  "地方": "地 (earth/ground) plus 方 (square) — a square patch of ground, a place.",
  "地铁": "地 (ground) plus 铁, iron with the metal radical 钅 — an iron train that runs underground, the subway.",
  "地图": "地 (earth) plus 图, an enclosure 囗 holding a layout — a picture of the earth's layout, a map.",
  "灯": "灯 is fire 火 next to 丁 (a nail) — a nail-shaped fire source mounted on the wall, a lamp.",
  "电梯": "电 (electric) plus 梯, wood 木 beside 弟 (younger brother, a rung-climbing shape) — an electric ladder, the elevator.",
  "电影院": "电影 is literally electric shadow, a movie; 院 (courtyard/institution) is the building that houses them — the cinema.",
  "电子邮件": "电子 (electronic) plus 邮件 (mail item) — electronic mail, email.",
  "东": "东 is the sun 日 tangled behind a tree — the sun rising through the branches in the east.",
  "冬": "冬 ends in 冫 (the ice radical) — icicles hanging at the bottom of the character, winter.",
  "冬天": "冬 (winter) plus 天 (day) — the days of winter.",
  "动物": "动 is movement, 力 (power) driving something; 物 is thing, with the ox radical 牛 — a thing that moves under its own power, an animal.",
  "短": "短 pairs 矢 (arrow) with 豆 (bean) — a tiny bean-sized arrow, short in length, as opposed to 矮 for short height.",
  "段": "段 has a striking radical 殳 on the right, like something cut off — a section chopped out of a longer whole, a period.",
  "锻炼": "锻 carries the metal radical 钅, forging; 炼 carries fire 火, refining — tempering your body through exercise just like tempering steel.",
  "多么": "多 (many/much) plus 么 (a light question tag) — how much, how — an intensifier for extent.",
  "多云": "多 (many) plus 云 (cloud) — plenty of clouds overhead, cloudy.",
  "饿": "饿 is 饣 (food radical) next to 我 (I/me) — me wanting food, hungry.",
  "儿": "儿 is a simple pictograph of legs — think of a small child scampering around, hence son and the soft diminutive suffix.",
  "而且": "而 looks like a hanging beard (and/but); 且 stacks layers on top of each other (also) — piling more on top, moreover.",
  "耳朵": "耳 traces the outline of an ear; 朵 (a flower cluster) softens it into a noun — the fleshy, petal-like shape of an ear.",
  "发": "发 pictures strands scattering outward from a center — things being sent out, or hair spreading from the scalp.",
  "发烧": "发 (to emit) plus 烧, fire 火 — your body emitting heat, a fever.",
  "发现": "发 (to issue/emit) plus 现, jade 王 catching light 见 (see) — something suddenly appears before your eyes, a discovery.",
  "方便": "方 (square/direction) plus 便, a person 亻 who can change 更 course easily — flexible for the person, convenient.",
  "房": "房 is a door 户 beside 方 (a squared-off space) — a boxed-in space behind a door, a room.",
  "放": "放 is 方 (direction) plus 攵 (a light tapping action) — directing an action to set something down, to put.",
  "放心": "放 (to release) plus 心 (heart) — releasing your worried heart, to rest assured.",
  "父母": "父 pictures a hand gripping a tool, the father; 母 pictures a nursing woman with two dots, the mother — the pair, parents.",
  "附近": "附 has 阝 (a mound, a place marker) attached to 付 (to attach); 近 adds 辶 walk plus 斤 axe (near) — a spot attached close by, nearby.",
  "复习": "复 means to repeat; 习 looks like a bird's wing flapping again and again in practice — repeating your practice, to review.",
  "感冒": "感 has 心 (heart) at the bottom, to feel; 冒 (to risk/emit) — your body feels it's been exposed to risk, catching a cold.",
  "感兴趣": "感 (feel) plus 兴趣 (excitement, interest) — feeling excited and drawn in, to be interested in.",
  "干净": "干 (dry) plus 净, water 氵 beside 争 (contested clean) — wiped dry and pure, clean.",
  "刚": "刚 is 冈 (a ridge) beside 刂 (a blade) — a blade freshly sharpened on the ridge, just done, recently.",
  "刚才": "刚 (just, recently) doubled up with 才 (only just) — stack both just words together for just a moment ago.",
  "歌": "歌 is 哥 (older brother) opening his mouth 欠 wide — big brother belting out a song.",
  "歌舞": "歌 (song) plus 舞, a figure with feathers waving in each hand — singing while dancing.",
  "个子": "个 (a general measure word for one individual) plus 子 (suffix) — describing one individual's build, their height and stature.",
  "各": "各 is a foot 夂 stepping down into its own mouth-shaped opening 口 — each person walking through their own doorway, each.",
  "根据": "根 is 木 (tree) — roots; 据 is 扌 (hand) plus 居 (dwell), to rely on — relying on the roots of the matter, according to.",
  "公园": "公 (public) plus 园, a garden 元 fenced by an enclosure 囗 — a public garden, a park.",
  "故事": "故 is 古 (old) plus 攵 (action) — an old happening retold; add 事 (matter) for a story.",
  "刮风": "刮 is 舌 (tongue) beside 刂 (knife) — a scraping blade; 风 is wind — wind scraping across your face, windy.",
  "关": "关 pictures a bar drawn across a gate — barring the gate shut, to close or turn off.",
  "关系": "关 (to connect) plus 系, a thread 纟 tying things together — threads connecting two people, a relationship.",
  "关心": "关 (to connect) plus 心 (heart) — connecting your heart to someone else's wellbeing, to care for them.",
  "关于": "关 (connect/concern) plus 于 (at/to) — connected to a topic, about.",
  "国家": "国 encloses 玉 (jade) inside 囗 (borders) — a treasured jewel kept safe within the nation's walls; 家 (home, a roof 宀 over 豕 pig) is the home that jewel protects.",
  "过去": "过 is 辶 (walk) plus 寸 (an inch) — passing by; 去 is to go — walking on and going away from now, the past.",
  "还是": "还 (still/also) plus 是 (to be) — is it still this, or is it that — used for or in questions.",
  "孩": "孩 carries the child radical 子 with 亥 as a sound component — the child radical marks this as related to kids, as in 孩子.",
  "害怕": "害 is a roof 宀 over 丰 and 口, harm coming down on you; 怕 pairs heart 忄 with white 白 — harm makes your heart turn pale with fear.",
  "黑板": "黑 has fire 灬 at the base, soot-blackened; 板 is wood 木 beside 反 — a wooden board blackened by chalk dust, the blackboard.",
  "红酒": "红 is silk 纟 dyed red; 酒 is water 氵 beside a wine jar 酉 — red liquid from the jar, red wine.",
  "后来": "后 (behind/after) plus 来 (to come) — what comes after, later.",
  "候": "候 has the person radical 亻 — someone standing and waiting for the right moment, as in 等候.",
  "护照": "护 is 扌 (hand) beside 户 (door), to protect; 照 (to shine/photograph) has fire 灬 at the base — a photo-bearing document that protects you abroad, a passport.",
  "花": "花 is grass 艹 over 化 (transform) — a plant transformed into a flower; the same 化 hints how quickly money transforms away when you spend it.",
  "画": "画 frames a field-like shape inside a box with a stroke underneath — a scene boxed onto a canvas, to draw or paint.",
  "坏": "坏 is earth 土 beside 不 (not) — earth that is no longer whole, broken or bad.",
  "环境": "环 has the jade radical 王, a ring encircling something; 境 is earth 土 plus 竟 (territory) — the ring of land surrounding you, environment.",
  "换": "换 is 扌 (hand) beside 奂 (to swap) — hands trading one thing for another, to exchange.",
  "回答": "回 is a box nested inside a box, to return; 答 pairs bamboo 竹 with 合 (fit) — sending back words that fit the question, an answer.",
  "会议": "会 (to gather) plus 议, speech 讠 beside 义 (righteous) — gathering to discuss things properly, a meeting.",
  "或者": "或 hints at a spear 戈 guarding a territory, maybe this one; 者 means one who — perhaps this one, or, used in statements.",
  "机会": "机 is wood 木 plus 几 (a small stand), the machinery of chance; 会 (to converge) — when circumstances line up just right, an opportunity.",
  "极（了）": "极 pairs wood 木 with 及 (to reach) — a tree reaching its absolute peak, extremely.",
  "极了": "极 (reach the limit) plus 了 (already done) — having reached the very limit, extremely.",
  "几乎": "几乎 pairs 几 (nearly, a small stand) with 乎 (a breathy question tag) — so close you might as well call it done, almost.",
  "记得": "记 is speech 讠 beside 己 (self), to record; 得 is to obtain — you record it and get to keep it in mind, to remember.",
  "季节": "季 stacks grain 禾 over child 子, the youngest; 节 is joint/festival — the joints of the year marked by the grain cycle, the seasons.",
  "假": "假 has the person radical 亻 beside 叚 (borrow) — a person borrowing time off from work, a vacation.",
  "检查": "检 pairs wood 木 with 佥 (all together), to inspect; 查 is a tree 木 under 旦, to investigate — inspecting closely, to check.",
  "简单": "简 has bamboo 竹 on top, recalling the old bamboo writing strips; 单 means single — reduced to one simple strip, simple.",
  "见面": "见 (to see) plus 面 (face) — to see someone's face, to meet.",
  "健康": "健 is the person radical 亻 beside 建 (to build) — a person built strong; 康 means wellbeing — built strong and well, healthy.",
  "讲": "讲 is speech 讠 beside 井 (a well, a neat grid) — organizing your words as neatly as the grid of a well, to explain.",
  "角": "角 traces a horn's shape — a small pointed fraction of the whole animal, hence a small fraction of a yuan.",
  "脚": "脚 has the flesh radical 月 beside 却 (retreat/but) — the fleshy part of you that lets you walk away, the foot.",
  "教": "教 is 孝 (filial devotion, a child 子 supporting an elder) plus 攵 (an action tap) — actively passing wisdom down, to teach.",
  "街道": "街 sits inside the crossroads radical 行; 道 is 辶 (walk) plus 首 (head) — the walkway threading between shops at a crossroads, the street.",
  "节目": "节 (a segment/joint) plus 目 (item, eye) — one segmented item in a broadcast lineup, a programme.",
  "节日": "节 (festival, a joint of bamboo) plus 日 (day) — a special festival day.",
  "结婚": "结 pairs thread 纟 with 吉 (lucky), to tie; 婚 has woman 女 beside 昏 (dusk, when weddings traditionally happened) — tying the knot at dusk, to marry.",
  "结束": "结 (to tie) plus 束, a tree 木 wrapped into a bundle — tying up the bundle, bringing things to an end.",
  "解决": "解 pairs horn 角, knife 刀 and ox 牛 — cutting apart a tangle; 决 has ice 冫 beside 夬 (decide) — cutting cleanly through and deciding, to solve.",
  "借": "借 has the person radical 亻 beside 昔 (formerly) — a person taking something for the time being, to borrow or lend.",
  "今晚": "今 (now) plus 晚 (evening) — the evening of now, tonight.",
  "经过": "经 is thread 纟 running through; 过 means to pass — a thread passing through a point, to pass by or undergo.",
  "经理": "经 (to manage, thread running through) plus 理 (jade 王 plus village 里, to reason and arrange) — the one who manages the threads and logic of a business, the manager.",
  "静": "静 pairs 青 (calm blue-green) with 争 (strife) — once the fighting stops, calm settles in, quiet.",
  "久": "久 pictures a figure with one leg dragging behind — taking a long time to get anywhere.",
  "酒": "酒 is water 氵 beside a wine jar 酉 — the liquid inside the jar, wine or liquor.",
  "旧": "旧 shows the sun 日 mounted on an old stand — like a well-worn sundial, old and used.",
  "举行": "举 shows hands lifting a bar overhead, to raise; 行 means to go/act — lifting an event into action, to hold a ceremony.",
  "句": "句 wraps 勹 around a mouth 口 — words wrapped into a single unit, a sentence.",
  "句子": "句 (sentence) plus 子 (noun suffix) — the everyday word for sentence.",
  "决定": "决 has ice 冫 beside 夬 (resolve, like a clean break); 定 is a roof 宀 over 正 (settle) — resolving something and settling it under one roof, to decide.",
  "觉": "觉 sits over 见 (see) with a top like closing eyes — shutting your eyes to see nothing, the sleep in 睡觉.",
  "咖啡店": "咖啡 borrows the sound of coffee, both written with the mouth radical 口 since you drink it; 店 (shop, 广 shelter plus 占) is the shop that serves it — the coffee shop.",
  "可爱": "可 (can/may) plus 爱 (love) — something you can't help but love, adorable.",
  "可乐": "可 (can) plus 乐 (happy) — a drink that can make you happy, and its sound loosely echoes cola.",
  "渴": "渴 is water 氵 beside 曷 (exhausted) — your water supply running dry, thirsty; it looks almost like 喝 (drink) but with water instead of a mouth.",
  "刻": "刻 pairs 亥 (a sound component) with the knife radical 刂 — carving notches into a clock face to mark the quarters, a quarter hour.",
  "客气": "客 is a roof 宀 sheltering a visitor 各, a guest; 气 means manner/air — treating people with guest-worthy manners, polite.",
  "客人": "客 (guest, sheltered under a roof 宀) plus 人 (person) — the person you shelter as a guest.",
  "空调": "空 is a cave 穴 over 工 (empty); 调 is speech 讠 beside 周 (adjust) — adjusting the empty air of a room, air conditioning.",
  "哭": "哭 stacks two mouths 口口 over a dog 犬 — wailing loud enough to sound like a howling dog, to cry.",
  "裤子": "裤 carries the clothing radical 衤 beside 库 (storehouse, the sound) — a clothing item that stores both your legs, pants.",
  "筷子": "筷 is bamboo 竹 beside 快 (fast) — bamboo sticks that let you eat fast, chopsticks.",
  "蓝": "蓝 has grass 艹 over 监 (to view/supervise) — an indigo plant whose dye reflects the color blue.",
  "篮球": "篮 wears the bamboo radical 竹, a woven basket; 球 means ball — shooting a ball into a bamboo basket, basketball.",
  "老": "老 pictures a bent figure with long hair leaning on a stick — an old person.",
  "了解": "了 (to finish/complete) plus 解 (to untangle) — you've fully untangled the matter, to understand.",
  "离开": "离 pictures a bird slipping out of a net, to separate; 开 means to open — opening the way to break apart from a place, to leave.",
  "礼物": "礼 carries the altar radical 礻, a ceremony; 物 means thing — a ceremonial thing given to someone, a gift.",
  "李小美": "李 (surname Li, from 木 tree plus 子 child, the plum tree) plus 小美, little beauty — picture a pretty girl standing under a plum tree.",
  "历史": "历 suggests passing through time, like flipping a calendar; 史 pictures a hand 又 holding records — the scribe's record of what has passed, history.",
  "脸": "脸 has the flesh radical 月 beside 佥 (all together) — all the fleshy features gathered on your face.",
  "练习": "练 is thread 纟 refined through training; 习 shows a wing flapping again and again — training through repeated practice.",
  "辆": "辆 carries the vehicle radical 车 beside 两 (two, since wheels come in pairs) — the measure word for vehicles.",
  "聊": "聊 has the ear radical 耳 — lending an ear while someone rambles on, to chat.",
  "聊天（儿）": "聊天 combines 聊 (chat) with 天 (sky/day) — casual small talk under the open sky, chit-chat.",
  "聊天儿": "Same as 聊天 with the soft retroflex 儿 ending common in casual Beijing speech — to chat.",
  "邻居": "邻 has the place radical 阝 beside 令 (adjacent); 居 (to dwell, 尸 body over 古) — someone dwelling right next door, a neighbour.",
  "留学": "留 pictures something held back on a field 田; 学 means to study — staying somewhere else to study, studying abroad.",
  "楼": "楼 is wood 木 beside 娄 (hollow, stacked layers) — a wooden structure stacked story upon story, a building.",
  "绿": "绿 is silk 纟 beside 录 (record) — dyed threads taking on the recorded color of nature, green.",
  "马": "马 is a simplified pictograph of a horse's mane and legs.",
  "马可": "马 (horse, surname Ma) plus 可 (can/may) — picture Marco free to ride his horse wherever he can.",
  "马上": "马 (horse) plus 上 (on/up) — up on horseback and ready to gallop off right away, immediately.",
  "满意": "满 has water 氵 filling something all the way up; 意 is 音 (sound) over 心 (heart) — your heart's idea filled completely, satisfied.",
  "帽子": "帽 carries the cloth radical 巾 beside 冒 (to cover) — a piece of cloth covering your head, a hat.",
  "没事": "没 (not have) plus 事 (matter) — there's not a matter to worry about, no problem.",
  "们": "们 pairs the person radical 亻 with 门 (door/gate) — a whole gateway full of people, the plural marker.",
  "秘书": "秘 pairs grain 禾 with 必 (must, keep close); 书 means book/write — someone who keeps your secret documents, a secretary.",
  "面": "面 outlines a face — the outward surface of anything.",
  "面包": "面 (flour, also face/surface) plus 包 (wrapped bundle) — flour wrapped and baked, bread.",
  "明白": "明 is bright, sun 日 beside moon 月; 白 is plain white — bright and plain, clearly understood.",
  "哪里": "哪 (which) plus 里 (place) — literally which place, used to deflect a compliment: oh, where do you even see that.",
  "那么": "那 (that) plus 么 (a light particle) — in that way, so.",
  "奶奶": "奶 has the woman radical 女 beside 乃 (breast/milk); doubled up, it's the woman who nursed your parent, grandma.",
  "南": "南 pictures an instrument hung facing the warm sun — the direction it faces, south.",
  "南方": "南 (south) plus 方 (direction) — the southern region.",
  "难": "难 pairs a hand 又 with 隹 (a short-tailed bird) — trying to catch a bird by hand, difficult.",
  "难过": "难 (difficult) plus 过 (to pass through) — a hard stretch to get through, feeling sad.",
  "年级": "年 (year) plus 级, a rank tied by thread 纟 — the rank matched to your year in school, a grade.",
  "年轻": "年 (year) plus 轻 (light in weight, cart 车 plus 又) — few years weigh lightly on you, young.",
  "鸟": "鸟 pictures a bird with a wing, tail, and eye — a bird.",
  "努力": "努 pairs woman 女 with hand 又, exerting effort; 力 means strength — putting your strength into it, working hard.",
  "爬": "爬 carries the claw radical 爪 — gripping with claws to climb.",
  "爬山": "爬 (to climb) plus 山, a pictograph of three peaks — climbing the peaks, mountain climbing.",
  "盘子": "盘 has a carrying-vessel shape on top of a dish-like base — a wide vessel for holding food, a plate.",
  "胖": "胖 pairs flesh 月 with 半 (half) — half again as much flesh as before, fat.",
  "皮鞋": "皮 pictures skin being peeled back, leather; 鞋 wears the leather radical 革 — shoes made of hide, leather shoes.",
  "啤酒": "啤 uses the mouth radical 口 for its sound pí; 酒 (wine, water 氵 beside jar 酉) — a drink gulped by the mouthful, beer.",
  "瓶子": "瓶 carries the tile/pottery radical 瓦 — a pottery-shaped vessel, a bottle.",
  "其实": "其 means that/its; 实 is a roof 宀 over a solid base, real — what's actually real beneath that appearance, actually.",
  "其他": "其 (that) plus 他 (he/other) — those other ones besides that one, the rest.",
  "奇怪": "奇 pairs big 大 with 可 (odd); 怪 has heart 忄 beside 圣 (strange) — something so odd it strikes your heart, strange.",
  "骑": "骑 carries the horse radical 马 beside 奇 (odd, here just the sound) — sitting astride a horse, to ride.",
  "起飞": "起 is 走 (run) beside 己 (self), to rise; 飞 pictures wings — rising and flying, an aircraft taking off.",
  "起来": "起 (rise) plus 来 (come) — rising up and coming into being, indicating upward motion.",
  "钱包": "钱 carries the metal radical 钅, money; 包 means bag — a bag for your money, a wallet.",
  "清楚": "清 is water 氵 beside 青 (clear blue-green) — water so clean everything shows through; 楚 adds vividness — perfectly clear.",
  "情况": "情 pairs heart 忄 with 青 (feeling); 况 is water 氵 beside 兄 (elder brother) — the emotional current of how things stand, the situation.",
  "请假": "请 is speech 讠 beside 青 (to request politely); 假 means borrowed time — politely requesting borrowed time off, asking for leave.",
  "秋": "秋 pairs grain 禾 with fire 火 — grain turning the color of fire at harvest time, autumn.",
  "秋天": "秋 (autumn) plus 天 (day) — the days of autumn.",
  "球赛": "球 (ball, jade radical 王 plus 求) plus 赛, a roof 宀 over a prize 贝 — a ball contest, a match.",
  "裙子": "裙 carries the clothing radical 衤 beside 君 (ruler, the sound) — flowing clothing fit for a ruler's robe, a skirt.",
  "然后": "然 (like this, so) plus 后 (after) — so, after that — then.",
  "热情": "热 has fire 灬 at the base, hot; 情 pairs heart 忄 with 青 (feeling) — a heart burning hot, enthusiastic and warm.",
  "人名": "人 (person) plus 名, an evening 夕 beside a mouth 口 — calling out someone's name when it's too dark to see their face.",
  "认": "认 pairs speech 讠 with a component hinting at identifying someone by name — to recognise, to identify.",
  "认为": "认 (to recognise) plus 为 (to be/act as) — recognising something to be true, to think or believe.",
  "认真": "认 (recognise) plus 真 (true) — recognising something as genuinely important, being serious.",
  "容易": "容 is a roof 宀 sheltering a valley 谷, to hold; 易 resembles a shifting lizard, easily changed — something a sheltered valley makes go easily.",
  "如果": "如 pairs woman 女 with mouth 口, as if; 果 means fruit/result — as if the result were true, if.",
  "伞": "伞 pictures an umbrella's ribs spread open under its canopy.",
  "山": "山 pictures three peaks side by side, a mountain.",
  "商场": "商 looks like a shop sign, to trade; 场 is earth 土 beside an open field — a large open place for trading, a shopping mall.",
  "上面": "上 (up/on) plus 面 (surface) — the surface that's on top, above.",
  "上网": "上 (to go on) plus 网, a mesh-like pictograph — going on the net, surfing the internet.",
  "生活": "生 pictures a sprouting plant, life; 活 is water 氵 beside tongue 舌 — life needs water to stay alive, daily living.",
  "生气": "生 (to generate) plus 气 (air) — generating hot air inside you, getting angry.",
  "声音": "声 evokes a struck instrument, sound; 音 is 立 (stand) over 日 — the sound of a voice.",
  "时": "时 pairs sun 日 with 寺 (temple, the sound) — the sun's movement marks the hour.",
  "使": "使 has the person radical 亻 beside 吏 (an official holding a document) — a person directed by an official's order, to make or cause.",
  "世界": "世 stacks three tens 十, a generation; 界 is field 田 beside 介 (boundary) — all the bounded generations together, the world.",
  "事": "事 shows a hand-like base gripping a pole or flag — the matter you're holding onto, an affair.",
  "试": "试 is speech 讠 beside 式 (form/style) — talking your way through the proper form to test it out, to try.",
  "瘦": "瘦 carries the sickness radical 疒 beside 叟 (an old man) — a gaunt, sickly figure, thin.",
  "叔叔": "叔 pairs a hand 又 with a small shape, someone younger — a younger male relative than father, doubled up for uncle.",
  "舒服": "舒 is 舍 (house) plus 予 (give), stretching out at ease; 服 means clothing/to submit — settling into clothes that fit just right, comfortable.",
  "树": "树 pairs wood 木 with an upright-looking component — a tree standing tall.",
  "数学": "数 has rice grains 米 being tapped and counted 攵; 学 means to study — the study of counting, mathematics.",
  "刷牙": "刷 combines 尸, 巾 and a blade-like stroke, to scrub; 牙 pictures interlocking teeth — scrubbing your teeth.",
  "双": "双 is two 又 (hand) radicals standing side by side — two hands together, a pair.",
  "水平": "水 (water) plus 平 (flat/even) — water always settles flat and even, hence level, your standard.",
  "睡着": "睡 has eye 目 beside 垂 (droop) — eyelids drooping shut; 着 marks arriving at a state — drooping off into sleep.",
  "司机": "司 looks like a hand on a lever, to control; 机 means machine — the one who controls the machine, a driver.",
  "他们": "他 (he, person 亻 plus 也) plus 们 (the plural gate) — he, plus everyone else, they.",
  "太太": "太 (very, big 大 with an extra dot) doubled up — an extra-respectful double title for a married woman, Mrs.",
  "太阳": "太 (very/extremely) plus 阳, the mound radical 阝 beside 日 (sun, the bright yang side) — the extremely bright side of the sky, the sun.",
  "特别": "特 pairs ox 牛 with 寺 (temple) — an ox singled out at the temple as special; 别 (different) reinforces it, extraordinarily.",
  "特点": "特 (special) plus 点 (a dot/point) — a special point that stands out, a feature.",
  "疼": "疼 carries the sickness radical 疒 beside 冬 (winter, the sound) — an ache as bitter as winter, pain.",
  "提高": "提 is hand 扌 beside 是, to lift; 高 means tall — hands lifting something higher, to improve.",
  "体育": "体 pairs person 亻 with 本 (root), the body; 育 means to raise/nurture — nurturing the body, physical education.",
  "甜": "甜 pairs tongue 舌 with 甘 (sweet) — your tongue tasting something sweet.",
  "条": "条 has wood 木 at its base — a long thin branch, used for long thin things like trousers and fish.",
  "同": "同 is an enclosure 冂 over one 一 and a mouth 口 — everyone under one roof sharing the same opinion, same.",
  "同事": "同 (same) plus 事 (work/matter) — someone who shares the same work matters as you, a colleague.",
  "同意": "同 (same) plus 意, sound 音 over heart 心 — sharing the same idea, to agree.",
  "头发": "头 (head) plus 发 (to emit) — what emits from your head, hair.",
  "突然": "突 has a cave 穴 over a dog 犬 — a dog bursting out of its den; 然 (like this) — happening just like that, suddenly.",
  "图书馆": "图 encloses a picture 囗; 书 means book; 馆 pairs the food radical 饣 with 官 (official) — a hall full of pictures and books, the library.",
  "腿": "腿 has the flesh radical 月 beside 退 (to retreat, walk 辶 backward) — the fleshy limb that lets you walk away, the leg.",
  "外地": "外 is evening 夕 beside 卜 — beyond the familiar; 地 means ground — ground outside your hometown, other places.",
  "完成": "完 is a roof 宀 over 元 (whole), finished; 成 means to become — bringing something whole into being, to complete.",
  "晚": "晚 pairs sun 日 with 免 (to escape) — the sun has nearly escaped below the horizon, late in the day.",
  "碗": "碗 pairs stone 石 with 宛 (curved) — a curved stone vessel, a bowl.",
  "万": "万 is a simplified pictograph once representing a swarming scorpion, borrowed to mean a swarm of ten thousand.",
  "网上": "网 (net) plus 上 (on) — on the net, online.",
  "忘": "忘 stacks 亡 (to vanish) over 心 (heart) — the memory has vanished from your heart, to forget.",
  "忘记": "忘 (to forget) plus 记 (to record) — the recorded memory has vanished, forgotten.",
  "为": "为 shows a hand shaping something for a purpose — doing something for someone or something.",
  "为了": "为 (for) plus 了 (marking purpose) — acting for the sake of a goal.",
  "位": "位 pairs the person radical 亻 with 立 (to stand) — a person standing in their rightful place, a respectful measure word for people.",
  "文化": "文 crosses lines like early script, writing; 化 is person 亻 beside 匕 (transform) — writing that transforms a society, culture.",
  "西": "西 pictures a bird settling into its nest at sunset — the direction the sun sets, west.",
  "西服": "西 (west) plus 服 (clothing) — Western-style clothing, a suit.",
  "习惯": "习 pictures flapping wings, practice; 惯 pairs heart 忄 with 贯 (pierce through) — practicing something until it's pierced straight into your mind, a habit.",
  "洗手间": "洗 is water 氵 beside 先 (first), to wash; 手 is hand; 间 is room — the room where you wash your hands, the bathroom.",
  "洗澡": "洗 (to wash) plus 澡, water 氵 beside 喿 (chattering birds bathing) — splashing water like bathing birds, to bathe.",
  "夏": "夏 pictures a figure with arms and legs spread wide, sweating in the heat, summer.",
  "夏天": "夏 (summer) plus 天 (day) — the hot days of summer.",
  "先": "先 has a growing top 生-like shape over legs 儿 — a person stepping ahead of everyone else, first.",
  "鲜花": "鲜 pairs fish 鱼 with sheep 羊, the freshest of foods; 花 means flower — as fresh as a flower just cut.",
  "相同": "相 pairs tree 木 with eye 目, looking at each other; 同 means same — looking at two things and finding them identical.",
  "相信": "相 (mutually) plus 信, person 亻 beside speech 言, trust — mutually trusting someone's word, to believe.",
  "香瓜": "香 pairs grain 禾 with sun 日, fragrant; 瓜 pictures a melon on the vine — a fragrant melon.",
  "香蕉": "香 (fragrant) plus 蕉, grass 艹 over 焦 (scorched, the banana plant's dry leaves) — a fragrant tropical fruit, banana.",
  "向": "向 shows a mouth-shaped opening 口 under a roof-like top facing outward — an opening pointed in a direction, towards.",
  "像": "像 has the person radical 亻 beside 象 (elephant) — a person resembling an elephant in a painting, to be like or resemble.",
  "小刚": "小 (little) plus 刚 (firm, just now) — picture a firm, sturdy little boy named Little Gang.",
  "小丽": "小 (little) plus 丽 (beautiful) — Little Beauty, a pretty little girl.",
  "小明": "小 (little) plus 明 (bright) — Little Bright, the cheerful, bright-eyed kid from every textbook.",
  "小心": "小 (small) plus 心 (heart) — keeping your heart small and cautious, being careful.",
  "小云": "小 (little) plus 云 (cloud) — Little Cloud, a light, breezy name.",
  "校长": "校 pairs wood 木 with 交 (to intersect); 长 means chief — the chief of the school, the headmaster.",
  "新闻": "新 shows an axe 斤 splitting fresh wood, new; 闻 is a gate 门 beside ear 耳, to hear — hearing what's new through the gate, the news.",
  "新鲜": "新 (new) plus 鲜 (fresh, fish plus sheep) — new and fresh.",
  "信用卡": "信用 means trust/credit; 卡 looks like squeezed strokes, a small slip — a card issued on trust, a credit card.",
  "行": "行 pictures a crossroads — a road open and passable, so it'll work, OK.",
  "行李": "行 (to travel) plus 李 (here just a sound, plum) — the stuff you carry while traveling, luggage.",
  "行李箱": "行李 (luggage) plus 箱 (box) — a box for your luggage, a suitcase.",
  "熊猫": "熊 pairs 能 (ability) with paw-like strokes 灬, a bear; 猫 carries the beast radical 犭 beside 苗 (cat) — a bear that looks like a giant cat, panda.",
  "需要": "需 is rain 雨 over 而, waiting on something you require like waiting for rain; 要 means to want — needing and wanting it.",
  "选": "选 is 辶 (walk) beside 巽 (select) — walking through options to pick one, to choose.",
  "选择": "选 (choose) plus 择, hand 扌 beside 睪 (to pick) — picking by hand after narrowing it down, to select.",
  "牙": "牙 pictures interlocking teeth or tusks — a tooth.",
  "呀": "呀 is mouth 口 beside 牙 (tooth, the sound) — a sound slipping right out of your mouth, an exclamatory oh.",
  "眼镜": "眼 carries the eye radical 目; 镜 pairs metal 钅 with 竟 (mirror) — a metal lens for your eyes, glasses.",
  "要求": "要 (to want) plus 求 (to seek) — wanting and seeking something specific, a requirement.",
  "爷爷": "爷 relates to father figures, doubled up for extra respect — father's father, grandpa.",
  "一般": "一 (one) plus 般 (a kind/sort, boat 舟 plus 殳) — just one of the usual kinds, ordinary.",
  "一般来说": "一般 (usual) plus 来说 (to come and say) — speaking in the usual way, generally speaking.",
  "一边": "一 (one) plus 边 (side) — doing one thing on one side while another happens on the other side, simultaneously.",
  "一定": "一 (entirely) plus 定, a roof 宀 over 正 (settled) — entirely settled on it, definitely.",
  "一共": "一 (one) plus 共, hands 廾 sharing something together — everything brought together as one sum, in total.",
  "一会儿": "一 (one) plus 会 (a gathering, here a moment) plus 儿 (diminutive) — just one little moment, a short while.",
  "一刻钟": "一 (one) plus 刻 (a carved notch) plus 钟, metal 钅 beside 中 (a clock/bell) — one notch carved on the clock, a quarter hour.",
  "一样": "一 (one) plus 样, wood 木 beside sheep 羊 (appearance) — of one and the same appearance, identical.",
  "以前": "以 (from) plus 前 (ahead) — reckoning from a point ahead, before.",
  "以外": "以 (from) plus 外 (outside) — starting from and going outside a boundary, beyond.",
  "音乐": "音 is 立 (stand) over 日, sound; 乐 pictures a hand-drum on a stand, joy — organized sound that brings joy, music.",
  "音乐会": "音乐 (music) plus 会 (gathering) — a gathering for music, a concert.",
  "银行": "银 carries the metal radical 钅, silver; 行 recalls the crossroads pictograph, a business — a business built on silver, a bank.",
  "饮料": "饮 pairs the food radical 饣 with 欠 (an open mouth), to drink; 料 has rice 米 beside 斗 (a measure) — a drinkable prepared ingredient, a beverage.",
  "应该": "应 is a shelter 广 over heart 心, to respond; 该 is speech 讠 beside 亥, ought — your heart's natural response tells you what you ought to do.",
  "影响": "影 combines scenery 景 with fine strokes 彡, a shadow; 响 is mouth 口 beside 乡 (echo) — a shadow casting an echo on everything nearby, influence.",
  "用": "用 pictures a bucket with a handle — a useful tool you reach for, to need or use.",
  "游戏": "游 is water 氵 beside 斿 (to roam), to swim/roam; 戏 means to play — roaming around at play, a game.",
  "有名": "有 (to have) plus 名 (name) — someone who has a name everyone knows, famous.",
  "又": "又 is a simplified pictograph of a right hand — reaching out with the same hand once more, again.",
  "遇到": "遇 is 辶 (walk) beside 禺, to meet unexpectedly; 到 means arrive — walking along and arriving unexpectedly at someone, to run into them.",
  "元": "元 stacks two 二 over legs 儿 — originally primary or first, now the primary unit of currency, the yuan.",
  "愿意": "愿 pairs 原 (original) with heart-related strokes, a wish; 意 means idea — the original idea in your heart, willing to.",
  "月亮": "月 is the crescent moon; 亮 pictures a lit window 亠口几 — the moon shining bright.",
  "越": "越 is 走 (run) beside 戉 (an axe, the sound) — running further and further past a point, more and more.",
  "运动服": "运动 (movement, walk 辶 plus power 力) plus 服 (clothing) — clothing made for movement, sportswear.",
  "澡": "澡 is water 氵 beside 喿 (chattering birds) — splashing water like bathing birds, the bath in 洗澡.",
  "怎么办": "怎么 (how) plus 办 (to handle) — how do we handle this, what to do.",
  "站": "站 pairs 立 (to stand) with 占 (to occupy) — standing and occupying a spot, to stand, or a station where you wait.",
  "长跑": "长 (long) plus 跑, the foot radical 足 beside 包 — running a long distance.",
  "照": "照 is 昭 (bright, sun 日 beside 召) plus fire 灬 (light) — bright light captured, to photograph.",
  "照顾": "照 (to shine light on) plus 顾, head 页 beside 雇 (to look back) — turning your head to shine attention on someone, to take care of them.",
  "照片": "照 (to photograph) plus 片 (a flat slice) — a flat piece capturing light, a photo.",
  "照相机": "照相 (to take a likeness) plus 机 (machine) — the machine that captures a likeness, a camera.",
  "这样": "这 (this) plus 样 (appearance/kind) — the appearance of this, like this.",
  "着急": "着 (to reach a state) plus 急, heart 忄 beside 及 (urgent) — an urgent feeling reaching straight into your heart, worried.",
  "真正": "真 (true) plus 正 (correct/upright) — truly and correctly, really.",
  "正": "正 is one line 一 over 止 (stop) — stopping exactly on the line, precisely.",
  "只": "只 pairs mouth 口 with splayed legs 八 — a small creature with a mouth and legs, the measure word for birds and animals.",
  "中间": "中 is a line straight through a box, the middle; 间 is a gate 门 with sunlight 日 peeking through — the space between, right in the center.",
  "中介": "中 (middle) plus 介 (a person-like shape standing between two lines) — standing right in the middle, between two parties, an agent.",
  "中秋节": "中 (middle) plus 秋 (autumn) plus 节 (festival) — the festival at the middle of autumn, Mid-Autumn Festival.",
  "中文": "中 (middle, short for 中国 China) plus 文 (writing) — the written language of the Middle Kingdom, Chinese.",
  "终于": "终 pairs thread 纟 with 冬 (the sound), the end of a thread knotted off; 于 means at — arriving at the very end of the thread, finally.",
  "种": "种 pairs grain 禾 with 中 (center) — grain sorted by its central type, a kind or type; also the verb to plant when read zhòng.",
  "重要": "重 pictures a heavy load; 要 means to want or need — something so heavy it's badly needed, important.",
  "周": "周 encloses dots inside a border, originally circuit or week — now also a common surname, Zhou.",
  "周明": "周 (Zhou) plus 明 (bright) — picture a cheerful guy named Bright Zhou.",
  "周末": "周 (week, a cycle) plus 末, a tree 木 with its top stroke extended to mark the very tip — the end tip of the week's cycle, the weekend.",
  "主要": "主 pictures a lamp flame steady on its stand, the master; 要 means want or need — what the master needs most, the main thing.",
  "注意": "注 is water 氵 beside 主 (to focus), to pour; 意 means idea/mind — pouring your mind's focus onto something, to pay attention.",
  "桌椅": "桌 is wood 木 beside 卓 (outstanding), a table; 椅 is wood 木 beside 奇 (odd, the sound), a chair — wooden tables and chairs, furniture.",
  "总是": "总 gathers a thread 纟 and heart 心 all together, overall; 是 means to be — gathering everything together as it always is, always.",
  "足球": "足 carries the foot radical; 球 means ball — a ball played with your feet, football.",
  "嘴": "嘴 pairs mouth 口 with 此 (this) and a beak-like flourish — the fuller, fleshier word for mouth beyond simple 口.",
  "最后": "最 is sun 日 over 取 (to take), the utmost; 后 means behind — the most behind of all, the very last.",
  "最近": "最 (most) plus 近, walk 辶 beside axe 斤 (near) — the most near point in time, recently.",
  "左右": "左 (left) plus 右 (right) — somewhere between left and right, approximately.",
  "作业": "作 has the person radical 亻 beside 乍 (to make); 业 looks like a workbench — the task you must make happen, homework.",
};
