// One-pass (re-runnable/idempotent) generator for docs/47's word/sentence
// audio: synthesizes one MP3 per distinct `Word.chinese` text and one per
// distinct `DialogLine.chinese` sentence via node-edge-tts (free, no API
// key — see docs/47 for why), writes them to public/audio/{words,sentences}/,
// and regenerates the two manifest files
// (src/quiz/audio/{words,sentences}.ts) that map exact Chinese text to its
// filename, the same Record<string,string>-keyed-by-text convention
// src/quiz/mnemonics/*.ts already uses.
//
// Read-only against the DB (only SELECTs, no confirm-write.ts gate needed —
// that guard is specifically for scripts that mutate the shared production
// database; this one only writes local files) — safe to run against the
// shared dev/prod DB from anywhere.
//
// Filenames are a short hash of the text, not the text itself, to keep
// them plain ASCII (avoids non-ASCII-URL edge cases across browsers) and
// keyed by content rather than by any particular Word/DialogLine row's id,
// so the same word/sentence occurring under multiple levels/chapters/
// sources shares one file.
import "dotenv/config";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { EdgeTTS } from "node-edge-tts";
import { prisma } from "@/lib/db";

const VOICE = "zh-CN-XiaoxiaoNeural";
const PUBLIC_DIR = path.join(process.cwd(), "public", "audio");
const MANIFEST_DIR = path.join(process.cwd(), "src", "quiz", "audio");

function hashFor(text: string): string {
  return createHash("sha1").update(text, "utf8").digest("hex").slice(0, 12);
}

function writeManifest(name: string, entries: Map<string, string>) {
  const sorted = [...entries.entries()].sort(([a], [b]) => a.localeCompare(b, "zh"));
  const lines = sorted.map(([text, filename]) => `  ${JSON.stringify(text)}: ${JSON.stringify(filename)},`);
  const content = `// Generated by scripts/generate-audio.ts — do not hand-edit. Maps exact
// Chinese text to its pre-generated MP3 filename under public/audio/${name}/.
// See docs/47-word-sentence-audio-plan.md.
export const ${name}Audio: Record<string, string> = {
${lines.join("\n")}
};
`;
  writeFileSync(path.join(MANIFEST_DIR, `${name}.ts`), content, "utf8");
}

// Small delay between requests — polite to the (free, unofficial) service
// rather than firing hundreds of requests back to back.
function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function synthesize(tts: EdgeTTS, text: string, outFile: string): Promise<boolean> {
  if (existsSync(outFile)) return false; // already generated, idempotent skip
  try {
    await tts.ttsPromise(text, outFile);
    return true;
  } catch (err) {
    console.error(`Failed to synthesize "${text}":`, err);
    return false;
  }
}

async function generateSet(
  name: "words" | "sentences",
  texts: string[]
): Promise<Map<string, string>> {
  const outDir = path.join(PUBLIC_DIR, name);
  mkdirSync(outDir, { recursive: true });
  const tts = new EdgeTTS({ voice: VOICE });
  const manifest = new Map<string, string>();
  let generated = 0;

  for (const text of texts) {
    const filename = `${hashFor(text)}.mp3`;
    manifest.set(text, filename);
    const outFile = path.join(outDir, filename);
    const didGenerate = await synthesize(tts, text, outFile);
    if (didGenerate) {
      generated += 1;
      await sleep(150);
    }
  }

  console.log(`${name}: ${generated} newly generated, ${texts.length - generated} already present, ${texts.length} total.`);
  return manifest;
}

async function main() {
  const words = await prisma.word.findMany({ select: { chinese: true }, distinct: ["chinese"] });
  const lines = await prisma.dialogLine.findMany({ select: { chinese: true }, distinct: ["chinese"] });
  await prisma.$disconnect();

  const wordManifest = await generateSet("words", words.map((w) => w.chinese));
  const sentenceManifest = await generateSet("sentences", lines.map((l) => l.chinese));

  mkdirSync(MANIFEST_DIR, { recursive: true });
  writeManifest("words", wordManifest);
  writeManifest("sentences", sentenceManifest);

  console.log("Manifests written to src/quiz/audio/{words,sentences}.ts.");
}

main();
